force-app/main/default/objects/Payment_Transaction_POE__c/Payment_Transaction_POE__c.object-meta.xml
<CustomObject>
    <label>Payment Transaction</label>
    <nameField>
        <displayFormat>{YY}{00000000}</displayFormat>
        <label>Payment Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Transaction_POE__c/fields/amount_original__c.field-meta.xml
<CustomField>
    <fullName>amount_original__c</fullName>
    <inlineHelpText>This is the amount of the payment being made in this transaction not including the Amount Surcharge.</inlineHelpText>
    <label>Amount Original</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction_POE__c/fields/amount_surcharge__c.field-meta.xml
<CustomField>
    <fullName>amount_surcharge__c</fullName>
    <inlineHelpText>This is any surcharge amount that may be charged such as a VISA, MasterCard or AMEX fee.</inlineHelpText>
    <label>Amount Surcharge</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction_POE__c/fields/currency_code__c.field-meta.xml
<CustomField>
    <fullName>currency_code__c</fullName>
    <label>Currency Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AUD</fullName>
            </value>
            <value>
                <fullName>NZD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Transaction_POE__c/fields/method__c.field-meta.xml
<CustomField>
    <fullName>method__c</fullName>
    <label>Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PayPX</fullName>
            </value>
            <value>
                <fullName>Ingenico</fullName>
            </value>
            <value>
                <fullName>BPoint</fullName>
            </value>
            <value>
                <fullName>Bank Transfer</fullName>
            </value>
            <value>
                <fullName>zipMoney</fullName>
                <label>zipmoney</label>
            </value>
            <value>
                <fullName>Paypal</fullName>
                <label>PayPal</label>
            </value>
            <value>
                <fullName>Coupon</fullName>
            </value>
            <value>
                <fullName>Poli</fullName>
                <label>POLi</label>
            </value>
            <value>
                <fullName>eNett</fullName>
            </value>
            <value>
                <fullName>TravelTek</fullName>
            </value>
            <value>
                <fullName>VT Transaction</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>BPAY</fullName>
            </value>
            <value>
                <fullName>QFF</fullName>
            </value>
            <value>
                <fullName>LatitudePay</fullName>
            </value>
            <value>
                <fullName>PayTo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Transaction_POE__c/fields/ordexp_tad_order__c.field-meta.xml
<CustomField>
    <fullName>ordexp_tad_order__c</fullName>
    <label>TAD Order</label>
    <referenceTo>TAD_Order__c</referenceTo>
    <relationshipLabel>Payment Transactions</relationshipLabel>
    <relationshipName>Payment_Transactions_POE</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction_POE__c/fields/transaction_idenifier__c.field-meta.xml
<CustomField>
    <fullName>transaction_idenifier__c</fullName>
    <caseSensitive>true</caseSensitive>
    <inlineHelpText>This field is to help identify the transaction entry in the transaction method system. For example, a BPOINT Reciept,  a ZipMoney Reference, a Bank transfer reference etc.</inlineHelpText>
    <label>Transaction Identifier</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Payment_Transaction_POE__c/fields/transaction_type__c.field-meta.xml
<CustomField>
    <fullName>transaction_type__c</fullName>
    <label>Transaction Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MobileAppPaymentCreation.cls
@RestResource(urlmapping='/settingAppPaymentTAD/*')
global class MobileAppPaymentCreation {
    
    
    global class mainWrapper{
        global String Transaction_Type{get;set;}
        global String Method{get;set;}
        global String Transaction_Identifier{get;set;}
        global Decimal Amount_Original{get;set;}
        global Decimal Amount_Charged{get;set;}
        global Decimal Amount_Surcharge{get;set;}
        global Date Transaction_Date{get;set;}
        
        global String Currency_Code{get;set;}
        global String TAD_Order{get;set;}
        
    }
    
    @HttpPost
    global static string OrderPayment(mainWrapper orderData){
        
        
        
            Payment_Transaction_POE__c pt = new Payment_Transaction_POE__c();
            pt.transaction_type__c = orderData.Transaction_Type;
            pt.method__c = orderData.method;
            pt.transaction_idenifier__c = orderData.Transaction_Identifier;
            pt.amount_original__c = orderData.Amount_Original/100;
            pt.amount_charged__c = orderData.Amount_Charged/100;
            pt.amount_surcharge__c = orderData.Amount_Surcharge!=null?orderData.Amount_Surcharge /100:0;
            pt.transaction_date__c= orderData.Transaction_Date;
            pt.currency_code__c = orderData.Currency_Code;
            pt.ordexp_tad_order__c = orderData.TAD_Order;
            insert pt;
            return pt.Id;
        
    }
    
    
}