force-app/main/default/objects/Payment_Transaction_POE__c/Payment_Transaction_POE__c.object-meta.xml
<CustomObject>
    <label>Payment Transaction</label>
    <nameField>
        <displayFormat>{YY}{00000000}</displayFormat>
        <label>Payment Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Transaction_POE__c/fields/amount_original__c.field-meta.xml
<CustomField>
    <fullName>amount_original__c</fullName>
    <inlineHelpText>This is the amount of the payment being made in this transaction not including the Amount Surcharge.</inlineHelpText>
    <label>Amount Original</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction_POE__c/fields/amount_surcharge__c.field-meta.xml
<CustomField>
    <fullName>amount_surcharge__c</fullName>
    <inlineHelpText>This is any surcharge amount that may be charged such as a VISA, MasterCard or AMEX fee.</inlineHelpText>
    <label>Amount Surcharge</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction_POE__c/fields/ordexp_tad_order__c.field-meta.xml
<CustomField>
    <fullName>ordexp_tad_order__c</fullName>
    <label>TAD Order</label>
    <referenceTo>TAD_Order__c</referenceTo>
    <relationshipLabel>Payment Transactions</relationshipLabel>
    <relationshipName>Payment_Transactions_POE</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction_POE__c/fields/transaction_type__c.field-meta.xml
<CustomField>
    <fullName>transaction_type__c</fullName>
    <label>Transaction Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TAD_Order__c/TAD_Order__c.object-meta.xml
<CustomObject>
    <label>TAD Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TAD Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_status_check__c.field-meta.xml
<CustomField>
    <fullName>ordexp_status_check__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field especially created for Order Status Updation</description>
    <label>Status Check</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_total_payment_received__c.field-meta.xml
<CustomField>
    <fullName>ordexp_total_payment_received__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Payment Received</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/Sum_of_Charged_Amount__c.field-meta.xml
<CustomField>
    <fullName>Sum_of_Charged_Amount__c</fullName>
    <label>Sum of Charged Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/Sum_of_Surcharge_Amount__c.field-meta.xml
<CustomField>
    <fullName>Sum_of_Surcharge_Amount__c</fullName>
    <label>Sum of Surcharge Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/PaymentTransactionTriggerHandler.cls
/**
* ────────────────────────────────────────────────────────────────────────────────────────────────
* PaymentTransactionTriggerHandler-
* Purpose: Handler class for  PaymentTransactionTrigger
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* @author         Samriddh M   <sachin@psagtechnologies.com.p1>
* @lastModifiedBy Samriddh M   <sachin@psagtechnologies.com.p1>
* @maintainedBy   Samriddh M   <sachin@psagtechnologies.com.p1>
* @version        1.0
* @created        2019-11-21
* @modified       2019-11-21
* @systemLayer    Apex Class
* ────────────────────────────────────────────────────────────────────────────────────────────────── */

public class PaymentTransactionTriggerHandler {
    
    public static  void paymentUpdationForTadOrder(Payment_Transaction_POE__c[] newListPayment,Map<id,Payment_Transaction_POE__c>oldPaymentMap,String context){
       
        Set<Id> TadOrderIds = new Set<Id>(); 
        //List<tad_order__c> orderToUpdate = new List<tad_order__c>();
        Map<id,tad_order__c>orderToUpdateMap = new Map<id,tad_order__c>();
        
        for(Payment_Transaction_POE__c payment : newListPayment) {
            if(context=='Insert'){
                if(payment.transaction_type__c=='Payment'){
                    TadOrderIds.add(payment.ordexp_tad_order__c);   
                }
            }else if (context=='Update'){
                if(payment.transaction_type__c=='Payment'){
                    if(payment.amount_original__c != oldPaymentMap.get(payment.id).amount_original__c){
                        TadOrderIds.add(payment.ordexp_tad_order__c);  
                    }  
                } 
            } 
        }
        if(!TadOrderIds.isempty()){
            list<tad_order__c> orderdata = [Select id , ordexp_status_check__c,(select id,amount_original__c,amount_surcharge__c,transaction_type__c,amount_charged__c   from Payment_Transactions_POE__r where transaction_type__c='Payment' )  from tad_order__c where id IN:TadOrderIds  AND Name!='O-00000' ] ;
            System.debug('Order Data' + orderdata );
            for(tad_order__c order : orderdata){
                Decimal PaymentAmount =0;
                Decimal paymentCharged = 0;//PBP - 358
                Decimal paymentSurcharged = 0;//PBP - 358
                for(Payment_Transaction_POE__c pay :order.Payment_Transactions_POE__r){
                    PaymentAmount = PaymentAmount + pay.amount_original__c;  
                    
                    //PBP - 358 Start
                    if(pay.amount_charged__c != Null){
                       paymentCharged = paymentCharged +pay.amount_charged__c; 
                    }
                    
                    if(pay.amount_surcharge__c != Null){
                       paymentSurcharged = paymentSurcharged +pay.amount_surcharge__c;
                    }
                    //PBP - 358 Stop
                    
                }
                tad_order__c newTadOrder = new  tad_order__c(id=order.id);
                newTadOrder.ordexp_total_payment_received__c=PaymentAmount;
                newTadOrder.Sum_of_Charged_Amount__c = paymentCharged;//PBP - 358
                
                if(paymentSurcharged != Null){
                    newTadOrder.Sum_of_Surcharge_Amount__c = paymentSurcharged;//PBP - 358
                }
                
                orderToUpdateMap.put(newTadOrder.id,newTadOrder);
                //orderToUpdate.add(newTadOrder) ;
            }
            if(!orderToUpdateMap.isEmpty()){ 
                update orderToUpdateMap.values();
            }   
        }
        
        
    }   
    
    
    public static void generatePDFAndAttachToTADOrder(List<Payment_Transaction_POE__c> newPaymentsList){
        
        Set<Id>orderIds = new Set<Id>();
        system.debug('newPaymentsList'+newPaymentsList);
        for(Payment_Transaction_POE__c tr : newPaymentsList){
            if(tr.transaction_type__c == 'Refund'){
                orderIds.add(tr.ordexp_tad_order__c);                
            }
        }
        if(!orderIds.isEmpty()){
            //   pdfGeneration(orderIds); 
        }
    } 
    
    @future (callout=true)
    public static void pdfGeneration (Set<ID> orderIds){
        
        List<Attachment> listToBeInserted = new List<Attachment>();
        System.debug('orderIds'+orderIds);
        for(Id order :orderIds ){
            PageReference pdf = new PageReference('/apex/TADOrderReceiptPDFGenerator?id=' + order);
            Attachment attach = new Attachment();
            Blob bodyData;
            if(!Test.isRunningTest())
            {
                bodyData = pdf.getContent();
            } else {
                bodyData = Blob.valueof('test');
            } 
            attach.ParentId = order;
            attach.name = 'TripADeal_Payment_Receipt.pdf';
            attach.body = bodyData;
            listToBeInserted.add(attach); 
        }
        System.debug('listToBeInserted'+listToBeInserted);
        if(!listToBeInserted.isEmpty()){
            insert listToBeInserted; 
        } 
        
    }
}