force-app/main/default/objects/Payment_Transaction_POE__c/Payment_Transaction_POE__c.object-meta.xml
<CustomObject>
    <label>Payment Transaction</label>
    <nameField>
        <displayFormat>{YY}{00000000}</displayFormat>
        <label>Payment Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Transaction_POE__c/fields/amount_original__c.field-meta.xml
<CustomField>
    <fullName>amount_original__c</fullName>
    <inlineHelpText>This is the amount of the payment being made in this transaction not including the Amount Surcharge.</inlineHelpText>
    <label>Amount Original</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction_POE__c/fields/currency_code__c.field-meta.xml
<CustomField>
    <fullName>currency_code__c</fullName>
    <label>Currency Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AUD</fullName>
            </value>
            <value>
                <fullName>NZD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Transaction_POE__c/fields/method__c.field-meta.xml
<CustomField>
    <fullName>method__c</fullName>
    <label>Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PayPX</fullName>
            </value>
            <value>
                <fullName>Ingenico</fullName>
            </value>
            <value>
                <fullName>BPoint</fullName>
            </value>
            <value>
                <fullName>Bank Transfer</fullName>
            </value>
            <value>
                <fullName>zipMoney</fullName>
                <label>zipmoney</label>
            </value>
            <value>
                <fullName>Paypal</fullName>
                <label>PayPal</label>
            </value>
            <value>
                <fullName>Coupon</fullName>
            </value>
            <value>
                <fullName>Poli</fullName>
                <label>POLi</label>
            </value>
            <value>
                <fullName>eNett</fullName>
            </value>
            <value>
                <fullName>TravelTek</fullName>
            </value>
            <value>
                <fullName>VT Transaction</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>BPAY</fullName>
            </value>
            <value>
                <fullName>QFF</fullName>
            </value>
            <value>
                <fullName>LatitudePay</fullName>
            </value>
            <value>
                <fullName>PayTo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Transaction_POE__c/fields/Order_No__c.field-meta.xml
<CustomField>
    <fullName>Order_No__c</fullName>
    <label>Order No</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction_POE__c/fields/ordexp_tad_order__c.field-meta.xml
<CustomField>
    <fullName>ordexp_tad_order__c</fullName>
    <label>TAD Order</label>
    <referenceTo>TAD_Order__c</referenceTo>
    <relationshipLabel>Payment Transactions</relationshipLabel>
    <relationshipName>Payment_Transactions_POE</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction_POE__c/fields/paid_by_email__c.field-meta.xml
<CustomField>
    <fullName>paid_by_email__c</fullName>
    <label>Paid By Email</label>
    <length>72</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction_POE__c/fields/Receipt_Status__c.field-meta.xml
<CustomField>
    <fullName>Receipt_Status__c</fullName>
    <inlineHelpText>Setting this field to Send will fire a receipt of this record to the customer</inlineHelpText>
    <label>Receipt Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Sent</fullName>
                <default>true</default>
                <label>Not Sent</label>
            </value>
            <value>
                <fullName>Send</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Transaction_POE__c/fields/reference_number__c.field-meta.xml
<CustomField>
    <fullName>reference_number__c</fullName>
    <description>Used by web to link to order</description>
    <inlineHelpText>Used by web to link to order</inlineHelpText>
    <label>Reference Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction_POE__c/fields/transaction_idenifier__c.field-meta.xml
<CustomField>
    <fullName>transaction_idenifier__c</fullName>
    <caseSensitive>true</caseSensitive>
    <inlineHelpText>This field is to help identify the transaction entry in the transaction method system. For example, a BPOINT Reciept,  a ZipMoney Reference, a Bank transfer reference etc.</inlineHelpText>
    <label>Transaction Identifier</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Payment_Transaction_POE__c/fields/transaction_type__c.field-meta.xml
<CustomField>
    <fullName>transaction_type__c</fullName>
    <label>Transaction Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TAD_Order__c/TAD_Order__c.object-meta.xml
<CustomObject>
    <label>TAD Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TAD Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_email_purchaser__c.field-meta.xml
<CustomField>
    <fullName>ordexp_email_purchaser__c</fullName>
    <label>Email(purchaser)</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_purchase_date__c.field-meta.xml
<CustomField>
    <fullName>ordexp_purchase_date__c</fullName>
    <label>Purchase date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/PaymentDataCreateByCSV.cls
public class PaymentDataCreateByCSV {
    
    public class Bpay{
        @auraenabled public date paymentDate{get;set;}
        @auraenabled public string BillerCode{get;set;}
        @auraenabled public string CustomerRefNo{get;set;}
        @auraenabled public string ReceivableType{get;set;}
        @auraenabled public string PaymentMethod{get;set;}
        @auraenabled public string BpayType{get;set;}
        @auraenabled public string TranscnRef{get;set;}
        @auraenabled public date SettlementDate{get;set;}
        @auraenabled public double Amount{get;set;}
    }
	
    @AuraEnabled
    public static String createPaymentRecords(String strFileName, String base64Data) {
        system.debug('in function');
        system.debug('base64Data 18 '+base64Data);
        if(!test.isRunningTest())
        base64Data = JSON.deserializeUntyped(base64Data).toString();
        system.debug('base64Data '+base64Data);
        List<Payment_Transaction_POE__c> paymentList = new List<Payment_Transaction_POE__c>();
        list<string> orderno=new list<string>();
        List<String> lstCSVLines = base64Data.split('\n');
        system.debug('lstCSVLines '+lstCSVLines);
        lstCSVLines.remove(0);
        list<Bpay> bpayList=new list<Bpay>();
        if(!lstCSVLines.isEmpty()){
            for(string s:lstCSVLines){
            list<string> DataString = s.split(',');
            system.debug('DataString.size '+DataString.size());
            if(DataString.size()<2){
               continue;
            }
           	system.debug('DataString31 '+DataString);
            Bpay bp = new Bpay();
            string pDate = DataString[0];
                system.debug('pDate 34 '+pDate);
                if(DataString[2]==null || DataString[2]==''){
                    continue;
                }
                system.debug('pDate '+pDate);
                
                list<string> date1 = new list<string>();
                if(pDate.Contains('-')){  
                  date1 = pDate.split('-');
                }else{
                  date1 = pDate.split('/');    
                }
                system.debug('date1 '+date1);
            date1[0]=date1[0].replaceAll('"','');
            string payDate;
            date Datepay;
                system.debug('date1[0] '+date1[0]);
            integer day=integer.valueOf(date1[0]);
            string syear='20'+date1[2];
            integer year = integer.valueOf(syear);
            if(date1[1]=='JAN'){
                integer month =01;                
               	Datepay=date.newInstance(year, month, day);
            }else if(date1[1]=='FEB'){
                integer month =02;
               	Datepay=date.newInstance(year, month, day);
            }else if(date1[1]=='MAR'){
                integer month =03;
               	Datepay=date.newInstance(year, month, day);
            }
            else if(date1[1]=='APR'){
                integer month =04;
               	Datepay=date.newInstance(year, month, day);
            }
            else if(date1[1]=='MAY'){
                integer month =05;
               	Datepay=date.newInstance(year, month, day);
            }
            else if(date1[1]=='JUN'){
                integer month =06;
               	Datepay=date.newInstance(year, month, day);
            }else if(date1[1]=='JUL'){
                integer month =07;
               	Datepay=date.newInstance(year, month, day);
            }
            else if(date1[1]=='AUG'){
                integer month =08;
               	Datepay=date.newInstance(year, month, day);
            }
            else if(date1[1]=='SEP'){
                integer month =09;
               	Datepay=date.newInstance(year, month, day);
            }
            else if(date1[1]=='OCT'){
                integer month =10;
               	Datepay=date.newInstance(year, month, day);
            }
            else if(date1[1]=='NOV'){
                integer month =11;
               	Datepay=date.newInstance(year, month, day);
            }
            else if(date1[1]=='DEC'){
                integer month =12;
               	Datepay=date.newInstance(year, month, day);
            }
           // bp.paymentDate=date.valueOf(payDate);
           	bp.paymentDate=Datepay;
            bp.BillerCode=DataString[1];
            string order;
            if(!test.isRunningTest())
                order=DataString[2].substring(0,6);
                else{
                    order=DataString[2];
                }
            bp.CustomerRefNo=order;
            orderno.add(order);
            bp.ReceivableType=DataString[3];
            bp.PaymentMethod='BPAY';
            bp.BpayType=DataString[5];
            bp.TranscnRef=DataString[6];
            bp.SettlementDate=Datepay;
            DataString[8] = DataString[8].replaceAll('"','');    
            bp.Amount = double.valueOf(DataString[8]);
            bpayList.add(bp);
        }
        }
        
        
        list<tad_order__c> tadorderlist=[Select id, name, ordexp_purchase_date__c, ordexp_email_purchaser__c from tad_order__c where name in:orderno];
        if(!tadorderlist.isEmpty()){
            for(tad_order__c to:tadorderlist){
            for(Bpay b:bpayList){
                if(b.CustomerRefNo==to.name){
                    Payment_Transaction_POE__c pt = new Payment_Transaction_POE__c();
                    pt.ordexp_tad_order__c=to.id;
                    pt.email__c = to.ordexp_email_purchaser__c;
                    pt.paid_by_email__c=to.ordexp_email_purchaser__c;
                    pt.Order_No__c =  to.name;
                    pt.amount_charged__c=b.Amount;
                 //   pt.transaction_date__c=system.today();
                    if(to.ordexp_purchase_date__c!=null){
                     //   datetime dt=to.ordexp_purchase_date__c;
                    //	date transcnDate = date.newInstance(dt.year(), dt.month(), dt.day());
                    	pt.transaction_date__c = system.today();
                    }else{
                        pt.transaction_date__c = b.paymentDate;
                    }               
                    pt.transaction_idenifier__c=b.TranscnRef;
                    pt.reference_number__c=b.TranscnRef;
                    pt.method__c= b.PaymentMethod;
                    pt.transaction_type__c='Payment';
                    pt.currency_code__c='AUD';
                    pt.amount_original__c=b.Amount;
                    pt.Receipt_Status__c='Send';
                    paymentList.add(pt);
                }
            }
        }
        }
        system.debug('Line151 '+paymentList.size());
        if(!paymentList.isEmpty()){
            try{
                PaymentDataBatch batch= new PaymentDataBatch(paymentList); 
        		database.executeBatch(batch, 50);
            }
            catch(DmlException e){
                system.debug('An Exception occurred: '+e.getMessage());
            }
            //insert paymentList;
        }
        return base64Data;
    }
   
    
      
}