force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Country</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/coupon__c/coupon__c.object-meta.xml
<CustomObject>
    <label>coupon</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>coupon</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/coupon__c/fields/account__c.field-meta.xml
<CustomField>
    <fullName>account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>coupon</relationshipLabel>
    <relationshipName>coupon</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/coupon__c/fields/balance_remaining__c.field-meta.xml
<CustomField>
    <fullName>balance_remaining__c</fullName>
    <formula>aggregate_discount__c - (aggregate_used__c + OLI_Aggregate_Used__c + EB_used__c + Order_aggregate_used__c  )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Balance Remaining</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/coupon__c/fields/Coupon_Restrictions__c.field-meta.xml
<CustomField>
    <fullName>Coupon_Restrictions__c</fullName>
    <label>Coupon Restrictions</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/coupon__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>coupon</relationshipLabel>
    <relationshipName>coupon</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/coupon__c/fields/Min_order_value__c.field-meta.xml
<CustomField>
    <fullName>Min_order_value__c</fullName>
    <label>Min order value</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/coupon__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Coupon Name</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/coupon__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Enabled</fullName>
            </value>
            <value>
                <fullName>Disabled</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
                <default>true</default>
                <label>Pending Approval</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/coupon__c/fields/Usage__c.field-meta.xml
<CustomField>
    <fullName>Usage__c</fullName>
    <inlineHelpText>Single : Single use no balance | Balance : Single user but can be used incrementally | Multi : Multiple users can use the one coupon code</inlineHelpText>
    <label>Usage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single</fullName>
            </value>
            <value>
                <fullName>Balance</fullName>
            </value>
            <value>
                <fullName>Multi</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal__c/Deal__c.object-meta.xml
<CustomObject>
    <label>Deal</label>
    <nameField>
        <label>Deal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal__c/fields/Cloned_From__c.field-meta.xml
<CustomField>
    <fullName>Cloned_From__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cloned From</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Deal</relationshipLabel>
    <relationshipName>Deal</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua &amp; Deps</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bali</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Borneo</fullName>
            </value>
            <value>
                <fullName>Bosnia Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Brunei</fullName>
            </value>
            <value>
                <fullName>Bulgaria</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal__c/fields/Merchant__c.field-meta.xml
<CustomField>
    <fullName>Merchant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Merchant</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Product Partner, General Expense Vendors</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Deal</relationshipLabel>
    <relationshipName>Deal</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal__c/fields/name__c.field-meta.xml
<CustomField>
    <fullName>name__c</fullName>
    <label>Landing Page Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Africa</fullName>
            </value>
            <value>
                <fullName>Asia</fullName>
            </value>
            <value>
                <fullName>Australia &amp; NZ</fullName>
            </value>
            <value>
                <fullName>Central America</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>Mediterranean</fullName>
            </value>
            <value>
                <fullName>Middle East</fullName>
            </value>
            <value>
                <fullName>North America</fullName>
            </value>
            <value>
                <fullName>South America</fullName>
            </value>
            <value>
                <fullName>South Pacific</fullName>
            </value>
            <value>
                <fullName>Gold Coast</fullName>
            </value>
            <value>
                <fullName>Sunshine Coast</fullName>
            </value>
            <value>
                <fullName>North Island</fullName>
            </value>
            <value>
                <fullName>South Island</fullName>
            </value>
            <value>
                <fullName>Queensland</fullName>
            </value>
            <value>
                <fullName>New South Wales</fullName>
            </value>
            <value>
                <fullName>Victoria</fullName>
            </value>
            <value>
                <fullName>Northern Territory</fullName>
            </value>
            <value>
                <fullName>Tasmania</fullName>
            </value>
            <value>
                <fullName>South Australia</fullName>
            </value>
            <value>
                <fullName>Western Australia</fullName>
            </value>
            <value>
                <fullName>Australian Capital Territory</fullName>
            </value>
            <value>
                <fullName>New York</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Hero</fullName>
            </value>
            <value>
                <fullName>Published(NRMA)</fullName>
            </value>
            <value>
                <fullName>Published(Staging)</fullName>
            </value>
            <value>
                <fullName>Hero(Staging)</fullName>
            </value>
            <value>
                <fullName>Hidden</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Region__c/Region__c.object-meta.xml
<CustomObject>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Region</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/MobileAppGetCouponDetailsv2.cls
@RestResource(urlMapping='/getCouponDetailsv2')
global class MobileAppGetCouponDetailsv2 {
    global class mainWrapper{
        global String Coupon{get;set;}
        global Double Discount{get;set;}
        global string errorMessage{get;set;}
        global boolean isSuccess{get;set;}
    }
    global class couponRequest{
        global String CouponName{get;set;}
        global Double orderAmount{get;set;}
        global string DealId {get;set;}
        
        //New attributes as per Elmin's request, also check an 
        global string appSessionCode {get;set;}
        global string accountSFId {get;set;}
    }
    
    @HttpPost
    global static mainWrapper discountSearch(){
        
        String requestBody = RestContext.request.requestBody.toString();
        couponRequest CouponDetail = (couponRequest)JSON.deserialize(requestBody, couponRequest.class);
        
        mainWrapper mainwrap1 =new mainWrapper();
        Boolean proceed = false;
        List<Account> actList = [Select id, firstname, lastname, app_session__c from Account 
                                 where Id =:CouponDetail.accountSFId Limit 1];
        
        if(!actList.isEmpty() && (actList[0].app_session__c == CouponDetail.appSessionCode)){ 
            proceed = true;
        }
        
        if(proceed==true){
            Map<String, List<String>> mapString = new Map<String, List<String>>();
            mainwrap1.isSuccess = true;
            Boolean displayCoupon = false;
            List<String> dealCountries = new List<String>();
            List<String> dealRegions = new List<String>();
            List<Coupon__c> couponList = [Select Id,Name,Name__c,Discount__c,Status__c,balance_remaining__c,Coupon_Restrictions__c,Deal__c, account__c,Usage__c,
                                          Deal__r.Country__c,Deal__r.Region__c,Deal__r.Name,Min_order_value__c  from coupon__c where Name__c =: CouponDetail.couponName limit 1];
            
            
            
            if(!couponList.isEmpty()){     
                for(Coupon__c cp : couponList){
                    if(cp.Deal__r.Country__c != null){
                        dealCountries = cp.Deal__r.Country__c.split(';');
                    }
                    
                    if(cp.Deal__r.Region__c != null){
                        dealRegions = cp.Deal__r.Region__c.split(';');
                    }
                    
                    //Condition to check if the AccountId is matched, Status is Enabled and Balance Remaining is greater than zero.
                    if(CouponDetail.accountSFId != null && cp.Status__c == 'Enabled' && cp.balance_remaining__c > 0){
                        if(CouponDetail.accountSFId == cp.account__c){
                            displayCoupon = true; 
                        }else{
                            displayCoupon = false;
                        }
                    }
                    if(displayCoupon == false){
                        mainwrap1.errorMessage = 'There is something wrong with this Coupon. It cannot be applied right now!';
                        break;
                    }
                    
                    //Condition to check if DealId is matched, Status is Enabled and Balance Remaining is greater than zero.
                    if(CouponDetail.DealId != null && cp.Status__c == 'Enabled' && cp.balance_remaining__c > 0 && cp.Deal__c != null){
                        if(CouponDetail.DealId == cp.Deal__c){
                            displayCoupon = true; 
                        }else{
                            displayCoupon = false;
                        }
                    }
                    
                    if(displayCoupon == false){
                        mainwrap1.errorMessage = 'There is something wrong with this Coupon. It cannot be applied right now!';
                        break;
                    }
                    
                    //Condition to see if the Minimum Value is not null and is less than Order Price, Status is Enabled and Balance Remaining is greater than zero.
                    if(cp.Min_order_value__c != null && cp.Status__c == 'Enabled' && cp.balance_remaining__c > 0){
                        if(cp.Min_order_value__c < CouponDetail.orderAmount){
                            displayCoupon = true; 
                        }else{
                            displayCoupon = false;
                        } 
                    }
                    
                    if(displayCoupon == false){
                        mainwrap1.errorMessage = 'There is something wrong with this Coupon. It cannot be applied right now!';
                        break;
                    }					
                    
                    //Condition when Coupon Restrictions are null, Status is Enabled and Balance Remaining is greater than zero.
                    if((cp.Coupon_Restrictions__c == null || cp.Coupon_Restrictions__c == '') && cp.Status__c == 'Enabled' && cp.balance_remaining__c > 0){
                        displayCoupon = true;
                    }
                    /*else{
displayCoupon = false;
}

if(displayCoupon == false){
mainwrap1.errorMessage = 'There is something wrong with this Coupon. It cannot be applied right now!';
break;
} */
                    
                    //Condition when Coupon Restrictions exists, Status is Enabled and Balance Remaining is greater than zero.
                    if(cp.Coupon_Restrictions__c != null && cp.Status__c == 'Enabled' && cp.balance_remaining__c > 0){
                        String couponRestrictions = cp.Coupon_Restrictions__c;
                        List<String> firstSplit = couponRestrictions.split('\\|');
                        for(String str : firstSplit){
                            List<String> secondSplit = str.split(':');
                            List<String> keyValuesList = secondSplit[1].split(';');
                            if(mapString.keyset().contains(secondSplit[0])){
                                List<String> alreadyContainedValue = mapString.get(secondSplit[0]);
                                alreadyContainedValue.addAll(keyValuesList);
                            }else{
                                mapString.put(secondSplit[0], keyValuesList); 
                            }
                        }
                        
                        if(mapString != null){
                            
                            //Checking for CEXC i.e. List of Excluded Countries
                            if(mapString.keyset().contains('Cexc')){
                                List<String> listOfExcludedCountries = mapString.get('Cexc');
                                if(!listOfExcludedCountries.isEmpty()){
                                    for(String excCountry : dealCountries){
                                        if(listOfExcludedCountries.contains(excCountry)){
                                            displayCoupon = false;
                                            break;
                                        }
                                    }
                                }
                            }
                            
                            if(displayCoupon == false){
                                mainwrap1.errorMessage = 'There is something wrong with this Coupon. It cannot be applied right now!';
                                break;
                            }
                            
                            
                            //Checking for REXC i.e. List of Excluded Regions
                            if(mapString.keyset().contains('Rexc')){
                                List<String> listOfExcludedRegions = mapString.get('Rexc');
                                if(!listOfExcludedRegions.isEmpty()){
                                    for(String excRegion : dealRegions){
                                        if(listOfExcludedRegions.contains(excRegion)){
                                            displayCoupon = false;
                                            break;
                                        }
                                    }
                                }
                            }
                            
                            if(displayCoupon == false){
                                mainwrap1.errorMessage = 'There is something wrong with this Coupon. It cannot be applied right now!';
                                break;
                            }
                            
                            //Checking for CINC i.e. List of Included Countries
                            if(mapString.keyset().contains('Cinc')){
                                List<String> listOfIncludedCountries = mapString.get('Cinc');
                                if(!listOfIncludedCountries.isEmpty()){
                                    for(String incCountry : dealCountries){
                                        if(!listOfIncludedCountries.contains(incCountry)){
                                            displayCoupon = false;
                                            break; 
                                        }
                                    }
                                }
                            }
                            
                            if(displayCoupon == false){
                                mainwrap1.errorMessage = 'There is something wrong with this Coupon. It cannot be applied right now!';
                                break;
                            }
                            
                            //Checking for RINC i.e. List of Included Regions
                            if(mapString.keyset().contains('Rinc')){
                                List<String> listOfIncludedRegions = mapString.get('Rinc');
                                if(!listOfIncludedRegions.isEmpty()){
                                    for(String incRegion : dealRegions){
                                        if(!listOfIncludedRegions.contains(incRegion)){
                                            displayCoupon = false;
                                            break;
                                        }
                                    }
                                }
                            }
                            
                            if(displayCoupon == false){
                                mainwrap1.errorMessage = 'There is something wrong with this Coupon. It cannot be applied right now!';
                                break;
                            }
                            
                            //Checking for Deal Name now
                            if(mapString.keyset().contains('Deal')){
                                List<String> listOfIncludedDeal = mapString.get('Deal');
                                if(!listOfIncludedDeal.isEmpty()){
                                    if(!listOfIncludedDeal.contains(couponList[0].Deal__r.Name)){
                                        displayCoupon = false;
                                        // break;
                                    }
                                }
                            }
                            if(displayCoupon == false){
                                mainwrap1.errorMessage = 'There is something wrong with this Coupon. It cannot be applied right now!';
                                break;
                            }                            
                        }
                    }
                    
                    if(displayCoupon == true){
                        mainwrap1.coupon = cp.Name__c;
                        
                        if(cp.Usage__c == 'Single'){
                            if(cp.balance_remaining__c < CouponDetail.orderAmount){
                                mainwrap1.discount = cp.balance_remaining__c; 
                            }else{
                                mainwrap1.discount = CouponDetail.orderAmount;
                            }
                        }
                        
                        if(cp.Usage__c == 'Multi'){
                            if(cp.Discount__c  < CouponDetail.orderAmount){
                                mainwrap1.discount = cp.Discount__c ; 
                            }else{
                                mainwrap1.discount = CouponDetail.orderAmount;
                            }
                        }
                        
                        if(cp.Usage__c == 'Balance'){
                            if(cp.balance_remaining__c  < CouponDetail.orderAmount){
                                mainwrap1.discount = cp.balance_remaining__c ; 
                            }else{
                                mainwrap1.discount = CouponDetail.orderAmount;
                            }
                        }
                        
                    }
                }  
            }
            else{
                mainwrap1.errorMessage = 'This coupon does not exists! Please try entering a valid Coupon code.'; 
            }
        }else{
            mainwrap1.isSuccess = false;
            mainwrap1.errorMessage = 'Please try to Login again!';
        }
        return mainwrap1;
    }
}