force-app/main/default/objects/airline_upgrade__c/airline_upgrade__c.object-meta.xml
<CustomObject>
    <label>airline upgrade</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>airline upgrade</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/airline_upgrade__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>airline upgrade</relationshipLabel>
    <relationshipName>airline_upgrade</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Allocation__c/Allocation__c.object-meta.xml
<CustomObject>
    <description>Auto Generated Name: {DEAL ID}-{DATE}-{POOL DIFFERENTIATOR} Example 1234-2020-11-1-A</description>
    <label>Allocation</label>
    <nameField>
        <label>Allocation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Allocation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Allocation__c/fields/deal__c.field-meta.xml
<CustomField>
    <fullName>deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Allocation</relationshipLabel>
    <relationshipName>Allocation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/coupon__c/coupon__c.object-meta.xml
<CustomObject>
    <label>coupon</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>coupon</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/coupon__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>coupon</relationshipLabel>
    <relationshipName>coupon</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/coupon__c/fields/type__c.field-meta.xml
<CustomField>
    <fullName>type__c</fullName>
    <label>type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
                <default>true</default>
                <label>All</label>
            </value>
            <value>
                <fullName>Travel</fullName>
            </value>
            <value>
                <fullName>Cruise</fullName>
            </value>
            <value>
                <fullName>Stay</fullName>
            </value>
            <value>
                <fullName>Airline</fullName>
            </value>
            <value>
                <fullName>Exclusives</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal__c/Deal__c.object-meta.xml
<CustomObject>
    <label>Deal</label>
    <nameField>
        <label>Deal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal__c/fields/Allocation_by__c.field-meta.xml
<CustomField>
    <fullName>Allocation_by__c</fullName>
    <label>Allocation by</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Deal</fullName>
                <default>true</default>
                <label>Deal</label>
            </value>
            <value>
                <fullName>Option</fullName>
            </value>
            <value>
                <fullName>Sub option</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal__c/fields/deal_archetype__c.field-meta.xml
<CustomField>
    <fullName>deal_archetype__c</fullName>
    <label>Deal Archetype</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MADU1</fullName>
            </value>
            <value>
                <fullName>MADUZ1</fullName>
            </value>
            <value>
                <fullName>MADU2</fullName>
            </value>
            <value>
                <fullName>MADUZ2</fullName>
            </value>
            <value>
                <fullName>TAIU1</fullName>
            </value>
            <value>
                <fullName>TAIZ1</fullName>
            </value>
            <value>
                <fullName>TAIUZ1</fullName>
            </value>
            <value>
                <fullName>TAIU2</fullName>
            </value>
            <value>
                <fullName>TAIZ2</fullName>
            </value>
            <value>
                <fullName>TAIUZ2</fullName>
            </value>
            <value>
                <fullName>TANU1</fullName>
            </value>
            <value>
                <fullName>TANZ1</fullName>
            </value>
            <value>
                <fullName>TANUZ1</fullName>
            </value>
            <value>
                <fullName>TANU2</fullName>
            </value>
            <value>
                <fullName>TANZ2</fullName>
            </value>
            <value>
                <fullName>TANUZ2</fullName>
            </value>
            <value>
                <fullName>MANU1</fullName>
            </value>
            <value>
                <fullName>MANUZ1</fullName>
            </value>
            <value>
                <fullName>MANU2</fullName>
            </value>
            <value>
                <fullName>MANUZ2</fullName>
            </value>
            <value>
                <fullName>RADU1</fullName>
            </value>
            <value>
                <fullName>RADUZ1</fullName>
            </value>
            <value>
                <fullName>RADU2</fullName>
            </value>
            <value>
                <fullName>RADUZ2</fullName>
            </value>
            <value>
                <fullName>CAIU1</fullName>
            </value>
            <value>
                <fullName>CAIZ1</fullName>
            </value>
            <value>
                <fullName>CAIUZ1</fullName>
            </value>
            <value>
                <fullName>CAIU2</fullName>
            </value>
            <value>
                <fullName>CAIZ2</fullName>
            </value>
            <value>
                <fullName>CAIUZ2</fullName>
            </value>
            <value>
                <fullName>SANUZ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal__c/fields/Deal_Draft__c.field-meta.xml
<CustomField>
    <fullName>Deal_Draft__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal Draft</label>
    <referenceTo>Deal_Draft__c</referenceTo>
    <relationshipLabel>Deal</relationshipLabel>
    <relationshipName>Deal</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal__c/fields/deal_type__c.field-meta.xml
<CustomField>
    <fullName>deal_type__c</fullName>
    <label>deal type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>travel</fullName>
            </value>
            <value>
                <fullName>cruise</fullName>
            </value>
            <value>
                <fullName>stay</fullName>
            </value>
            <value>
                <fullName>Siteminder Hotel</fullName>
            </value>
            <value>
                <fullName>Experiences</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal__c/fields/number_of_days__c.field-meta.xml
<CustomField>
    <fullName>number_of_days__c</fullName>
    <label>number of days</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Deal__c/fields/per_night_allocation__c.field-meta.xml
<CustomField>
    <fullName>per_night_allocation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Per Night Allocation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Deal_Draft__c/Deal_Draft__c.object-meta.xml
<CustomObject>
    <description>This object is a child object to Deal and provides details for the deal provided by the BDM and also &quot;proofed content&quot; for Product Analysts which are then used by Publishers.

This includes information for both AU and NZ</description>
    <label>Deal Draft</label>
    <nameField>
        <label>Deal Draft Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal Drafts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Draft__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Deal Drafts</relationshipLabel>
    <relationshipName>Deal_Drafts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/departure_cities__c/departure_cities__c.object-meta.xml
<CustomObject>
    <label>departure cities</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>departure cities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/departure_cities__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>departure cities</relationshipLabel>
    <relationshipName>departure_cities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/departures_dates__c.object-meta.xml
<CustomObject>
    <label>departures dates</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>departures dates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/departures_dates__c/fields/allocation__c.field-meta.xml
<CustomField>
    <fullName>allocation__c</fullName>
    <label>TOTAL v2 ALLOCATION</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>departures dates</relationshipLabel>
    <relationshipName>departures_dates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/options__c/options__c.object-meta.xml
<CustomObject>
    <label>Options</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/options__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipName>options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/options__c/recordTypes/Option.recordType-meta.xml
<RecordType>
    <fullName>Option</fullName>
    <active>true</active>
    <description>This is a record type for creating a normal Option Record.</description>
    <label>Option</label>
</RecordType>

force-app/main/default/objects/order_line_item__c/order_line_item__c.object-meta.xml
<CustomObject>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>OLI-{000000}</displayFormat>
        <label>Order Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/order_line_item__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Saved_Deals__c/Saved_Deals__c.object-meta.xml
<CustomObject>
    <label>Sales Lead</label>
    <nameField>
        <label>Sales Lead Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Leads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Saved_Deals__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipName>Saved_Deals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/sub_options__c/sub_options__c.object-meta.xml
<CustomObject>
    <label>Sub Options</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/sub_options__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Sub Options</relationshipLabel>
    <relationshipName>Sub_Options</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/createTadOrderControllerTest.cls
@isTest
public class createTadOrderControllerTest {
    @isTest
    static void testMethod1(){
        
        List<RecordType> RCTProductPartner = TADUtils.getRecordType(Label.TAD_RT_Product_Partner);
        
        Account acctBussiness = TestDataFactory.createBussinessAccount(RCTProductPartner[0].Id);   // Bussiness account Inserted
        insert acctBussiness;
        
        List<RecordType> RCTTadDeal = TADUtils.getRecordType(Label.TAD_RT_TAD_Deal);
        
        // Inserting Deal with Allocation By Deal
        Deal__c deal = TestDataFactory.createMerchantDeal(RCTTadDeal[0].Id , acctBussiness.Id );   // Deals created
        deal.Allocation_by__c = 'Deal';
        deal.number_of_days__c = 12;
        deal.deal_type__c = 'travel';
        deal.per_night_allocation__c = true;
        deal.deal_archetype__c = 'SANUZ';
        insert deal;
        
        
        // Inserting Deal Draft for Deal with Allocation by Deal
        Deal_Draft__c dealDraft = new Deal_Draft__c();
        dealDraft.Deal__c = deal.Id;
        dealDraft.Name = deal.Name;
        insert dealDraft;  
        
        
        // Inserting Options for Deal with Allocation by Deal
        options__c options = TestDataFactory.CreateOptions(deal.Id);       // Options crested using the deal
        insert options;
        
        
        
        // Inserting sub options for Deal with allocation by Deal
        sub_options__c subOptions = TestDataFactory.createSubOptions(options.Id);   // Sub options created
        subOptions.Price1__c  = 1499;
        insert subOptions;
        
       
        
        //Creating Allocations for Deal with Allocation by Deal
        Allocation__c allocation = TestDataFactory.createAllocationDeal(deal);
        insert allocation;
        
        
        
        //Creating departure dates for Deal with Allocation by Deal
        departures_dates__c departureDates = TestDataFactory.createDDWithAllocation(deal,options,subOptions,allocation); 
        departureDates.Linked_Deal_D_O_S__c = deal.Id;
        departureDates.MinNotMetApproval__c = 'Processed';
        departureDates.online_status__c ='Online';
        departureDates.Deal__c = deal.id;
        insert departureDates;
        
        //Creating departure dates for Deal with Allocation by Deal
        departures_dates__c departureDates1 = TestDataFactory.createDDWithAllocation(deal,options,subOptions,allocation); 
        departureDates1.Linked_Deal_D_O_S__c = deal.Id;
        departureDates1.MinNotMetApproval__c = 'Not Required';
        departureDates1.online_status__c ='Online';
        departureDates1.Deal__c = deal.id;
        insert departureDates1;
        system.debug('departureDates'+departureDates1);
        departure_cities__c departureCities = TestDataFactory.createDepartureCities(deal.Id);       // Departure cities created
        insert departureCities;
        
        airline_upgrade__c au = TestDataFactory.createAirlineUpgrade(deal);
        insert au;
        
        List<RecordType> RCTPersonAccount = TADUtils.getRecordType(Label.TAD_RT_TAD_Person_Account);
        Account acctPerson = TestDataFactory.createPersonAccount(RCTPersonAccount[0].Id);
        insert acctPerson;
        
        ID RTTADOrder1 = Schema.SObjectType.Tad_Order__C.getRecordTypeInfosByDeveloperName().get('TAD').getRecordTypeId();
        Tad_Order__C order1 = TestDataFactory.createTADOrder(acctPerson,deal,options,departureDates,RTTADOrder1);
        order1.ordexp_master_status__c = 'On Hold';
        order1.ordexp_sub_status__c = 'Initial Payment Pending';
        insert order1;
        
        test.startTest();
        Order_Line_Item__c oli = TestDataFactory.createOrderLineItem(order1,subOptions,departureCities,'2', options, deal);
        oli.Deal__c=deal.id;
        oli.ordexp_Options__c=options.id;
        oli.Sub_Options__c = subOptions.Id;
        oli.ordexp_approval_status__c='Pending Documentation';
        oli.Quantity__c = '2';
        insert oli;
        
        coupon__c c = TestDataFactory.createCoupon();
        c.type__c='All';
        c.Coupon_type__c = 'Customer Compensation';
        insert c;
        String temp1 = c.Id;
        temp1 = temp1.right(9);
        String temp2 = c.Name__c;
        String keyword = temp1.left(6)+temp2.left(4);
        
         Saved_Deals__c sv=new Saved_Deals__c();
        sv.Deal__c=deal.id;
        sv.Lead_Source__c ='Web';
        sv.Account__c=acctBussiness.id;
        sv.TAD_Order__c=order1.id;
        
        insert sv;
        Case cs=new Case();
        cs.Saved_Deal__c=sv.id;
        
        insert cs;
        
        System.debug('c = '+c);
        CreateTadOrderController.tadOrderData tadord= new CreateTadOrderController.tadOrderData();
        tadord.dealId = deal.Id;
        tadord.optionId = options.id;
        tadord.recordType = 'TAD';
        tadord.accountId= acctPerson.id;
        tadord.departureDateId = departureDates.Id;
        
        createTadOrderController.fetchDealValuesApex ('1234','test');
        createTadOrderController.fetchAccountDetailsApex (acctPerson.id);
        createTadOrderController.getAvailableOptionsApex (deal.id, 'TAD');
        createTadOrderController.getAllocationData ( 'Deal' , tadord );
        createTadOrderController.getAllocationData ( 'Option' , tadord );
        createTadOrderController.getAllocationData ( 'Sub option' , tadord );
        createTadOrderController.saveTadOrderApex (tadord,false,'123333' );
        test.stopTest();
		createTadOrderController.returnMonthName(1);
        createTadOrderController.returnMonthName(2);
        createTadOrderController.returnMonthName(3);
        createTadOrderController.returnMonthName(4);
        createTadOrderController.returnMonthName(5);
        createTadOrderController.returnMonthName(6);
        createTadOrderController.returnMonthName(7);
        createTadOrderController.returnMonthName(8);
        createTadOrderController.returnMonthName(9);
        createTadOrderController.returnMonthName(10);
        createTadOrderController.returnMonthName(11);
        createTadOrderController.returnMonthName(12);
        createTadOrderController.tagOrdertoCase(order1.id,cs.id);
        createTadOrderController.TagOrderToSavedDeal(order1.id,sv.id);
        createTadOrderController.TadOrdercreation(sv.Id);

        
    }
    
}