force-app/main/default/objects/airline_upgrade__c/airline_upgrade__c.object-meta.xml
<CustomObject>
    <label>airline upgrade</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>airline upgrade</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/airline_upgrade__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Used to take options on or off the web checked is on</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/airline_upgrade__c/fields/price_nz__c.field-meta.xml
<CustomField>
    <fullName>price_nz__c</fullName>
    <label>Price - NZD</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/General_Pricing__c/General_Pricing__c.object-meta.xml
<CustomObject>
    <label>General Pricing</label>
    <nameField>
        <displayFormat>GP-{0000000}</displayFormat>
        <label>General Pricing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>General Pricings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/General_Pricing__c/fields/Airline_Upgrade__c.field-meta.xml
<CustomField>
    <fullName>Airline_Upgrade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Airline Upgrade</label>
    <referenceTo>airline_upgrade__c</referenceTo>
    <relationshipLabel>General Pricings</relationshipLabel>
    <relationshipName>General_Pricings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/General_Pricing__c/fields/Price_Airline_upgrade__c.field-meta.xml
<CustomField>
    <fullName>Price_Airline_upgrade__c</fullName>
    <label>Price</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/General_Pricing__c/fields/Price_Airline_upgrade_NZD__c.field-meta.xml
<CustomField>
    <fullName>Price_Airline_upgrade_NZD__c</fullName>
    <label>Price - NZD</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/General_Pricing__c/recordTypes/Airline_Upgrade.recordType-meta.xml
<RecordType>
    <fullName>Airline_Upgrade</fullName>
    <active>true</active>
    <label>Airline Upgrade</label>
</RecordType>

force-app/main/default/classes/Tad_BatchToCreateAUGP.cls
public class Tad_BatchToCreateAUGP implements  Database.Batchable<sObject> {
    
    public Database.QueryLocator start(Database.BatchableContext bc){
         return Database.getQueryLocator('select id,name,price_nz__c,price__c from airline_upgrade__c where id NOT IN (select Airline_Upgrade__c from General_Pricing__c where Active__c = true)');
    }
    public void execute(Database.BatchableContext bc, List<airline_upgrade__c> auRecords){
        List<General_Pricing__c> gpRecordsToInsert = new List<General_Pricing__c>();
        String airlineUpgradeRCT = Schema.SObjectType.general_pricing__c.getRecordTypeInfosByDeveloperName().get('Airline_Upgrade').getRecordTypeId();
        for(airline_upgrade__c au:auRecords){
            General_Pricing__c gp= new General_Pricing__c();
            gp.Active__c = true;
            gp.Price_Airline_upgrade__c = au.price__c;
            gp.Price_Airline_upgrade_NZD__c = au.price_nz__c;
            gp.Airline_Upgrade__c = au.Id;
            gp.RecordTypeId = airlineUpgradeRCT;
            gpRecordsToInsert.add(gp);
        }
        try{
            insert gpRecordsToInsert;
        }catch(Exception ex){
            System.debug('Error while creating new gp records for Airline upgrade'+ex.getMessage());
        }
    } 
    public void finish(Database.BatchableContext bc){
        System.debug('GP records Created successfuly');
    } 
}