force-app/main/default/objects/airline_upgrade__c/airline_upgrade__c.object-meta.xml
<CustomObject>
    <label>airline upgrade</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>airline upgrade</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/airline_upgrade__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Used to take options on or off the web checked is on</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/airline_upgrade__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>airline upgrade</relationshipLabel>
    <relationshipName>airline_upgrade</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/airline_upgrade__c/fields/order_filter__c.field-meta.xml
<CustomField>
    <fullName>order_filter__c</fullName>
    <label>Order Filter</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Component__c/Component__c.object-meta.xml
<CustomObject>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Component__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Components</relationshipLabel>
    <relationshipName>Components</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Component__c/fields/Options__c.field-meta.xml
<CustomField>
    <fullName>Options__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Options</label>
    <referenceTo>options__c</referenceTo>
    <relationshipLabel>Components</relationshipLabel>
    <relationshipName>Components</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Component_Pricing__c/Component_Pricing__c.object-meta.xml
<CustomObject>
    <label>Component Pricing</label>
    <nameField>
        <label>Component Pricing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Component Pricing</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Component_Pricing__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <formula>OR(AND(QTY_Sold__c   &gt;=  Min_Pax__c ,QTY_Sold__c  &lt;= Max_Pax__c),
AND(QTY_Sold__c   &gt;=  Min_Pax__c ,ISNULL(Max_Pax__c)),
AND(ISNULL(Max_Pax__c),ISNULL(Min_Pax__c)))</formula>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Deal__c/Deal__c.object-meta.xml
<CustomObject>
    <label>Deal</label>
    <nameField>
        <label>Deal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal__c/fields/deal_archetype__c.field-meta.xml
<CustomField>
    <fullName>deal_archetype__c</fullName>
    <label>Deal Archetype</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MADU1</fullName>
            </value>
            <value>
                <fullName>MADUZ1</fullName>
            </value>
            <value>
                <fullName>MADU2</fullName>
            </value>
            <value>
                <fullName>MADUZ2</fullName>
            </value>
            <value>
                <fullName>TAIU1</fullName>
            </value>
            <value>
                <fullName>TAIZ1</fullName>
            </value>
            <value>
                <fullName>TAIUZ1</fullName>
            </value>
            <value>
                <fullName>TAIU2</fullName>
            </value>
            <value>
                <fullName>TAIZ2</fullName>
            </value>
            <value>
                <fullName>TAIUZ2</fullName>
            </value>
            <value>
                <fullName>TANU1</fullName>
            </value>
            <value>
                <fullName>TANZ1</fullName>
            </value>
            <value>
                <fullName>TANUZ1</fullName>
            </value>
            <value>
                <fullName>TANU2</fullName>
            </value>
            <value>
                <fullName>TANZ2</fullName>
            </value>
            <value>
                <fullName>TANUZ2</fullName>
            </value>
            <value>
                <fullName>MANU1</fullName>
            </value>
            <value>
                <fullName>MANUZ1</fullName>
            </value>
            <value>
                <fullName>MANU2</fullName>
            </value>
            <value>
                <fullName>MANUZ2</fullName>
            </value>
            <value>
                <fullName>RADU1</fullName>
            </value>
            <value>
                <fullName>RADUZ1</fullName>
            </value>
            <value>
                <fullName>RADU2</fullName>
            </value>
            <value>
                <fullName>RADUZ2</fullName>
            </value>
            <value>
                <fullName>CAIU1</fullName>
            </value>
            <value>
                <fullName>CAIZ1</fullName>
            </value>
            <value>
                <fullName>CAIUZ1</fullName>
            </value>
            <value>
                <fullName>CAIU2</fullName>
            </value>
            <value>
                <fullName>CAIZ2</fullName>
            </value>
            <value>
                <fullName>CAIUZ2</fullName>
            </value>
            <value>
                <fullName>SANUZ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal__c/fields/deal_type__c.field-meta.xml
<CustomField>
    <fullName>deal_type__c</fullName>
    <label>deal type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>travel</fullName>
            </value>
            <value>
                <fullName>cruise</fullName>
            </value>
            <value>
                <fullName>stay</fullName>
            </value>
            <value>
                <fullName>Siteminder Hotel</fullName>
            </value>
            <value>
                <fullName>Experiences</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal__c/fields/merchant_sharing_deadline__c.field-meta.xml
<CustomField>
    <fullName>merchant_sharing_deadline__c</fullName>
    <inlineHelpText>Number of days prior to departure that merchant will receive booking confirmation. If multi-merchant deal, please use the most restrictive deadline e.g 120 days instead of 90.</inlineHelpText>
    <label>Merchant Sharing Deadline - Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Deal__c/fields/order_filter__c.field-meta.xml
<CustomField>
    <fullName>order_filter__c</fullName>
    <label>Order Filter</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/departure_cities__c/departure_cities__c.object-meta.xml
<CustomObject>
    <label>departure cities</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>departure cities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/departure_cities__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>departure cities</relationshipLabel>
    <relationshipName>departure_cities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/departure_cities__c/fields/order_filter__c.field-meta.xml
<CustomField>
    <fullName>order_filter__c</fullName>
    <label>Order Filter</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/options__c/options__c.object-meta.xml
<CustomObject>
    <label>Options</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/options__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipName>options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/options__c/fields/itinerary_context__c.field-meta.xml
<CustomField>
    <fullName>itinerary_context__c</fullName>
    <label>Itinerary Context</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>Both Extensions</fullName>
                <isActive>false</isActive>
                <label>Both Extensions</label>
            </value>
            <value>
                <fullName>Main Package</fullName>
                <isActive>false</isActive>
                <label>Main Package</label>
            </value>
            <value>
                <fullName>Post Extension</fullName>
                <isActive>false</isActive>
                <label>Post Extension</label>
            </value>
            <value>
                <fullName>Pre Extension</fullName>
                <isActive>false</isActive>
                <label>Pre Extension</label>
            </value>
            <value>
                <fullName>Upgrade</fullName>
                <isActive>false</isActive>
                <label>Upgrade</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/options__c/recordTypes/Option.recordType-meta.xml
<RecordType>
    <fullName>Option</fullName>
    <active>true</active>
    <description>This is a record type for creating a normal Option Record.</description>
    <label>Option</label>
</RecordType>

force-app/main/default/objects/sub_options__c/sub_options__c.object-meta.xml
<CustomObject>
    <label>Sub Options</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/sub_options__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Sub Options</relationshipLabel>
    <relationshipName>Sub_Options</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sub_options__c/fields/itinerary_context__c.field-meta.xml
<CustomField>
    <fullName>itinerary_context__c</fullName>
    <label>Itinerary Context</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Main Package</fullName>
            </value>
            <value>
                <fullName>Pre Extension</fullName>
            </value>
            <value>
                <fullName>Post Extension</fullName>
            </value>
            <value>
                <fullName>Both Extensions</fullName>
            </value>
            <value>
                <fullName>Upgrade</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/sub_options__c/fields/options__c.field-meta.xml
<CustomField>
    <fullName>options__c</fullName>
    <label>options</label>
    <referenceTo>options__c</referenceTo>
    <relationshipLabel>Sub Options</relationshipLabel>
    <relationshipName>sub_options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/tad_cloneChildRecordApexHandlerTest.cls
@isTest
public class tad_cloneChildRecordApexHandlerTest {
    
    @isTest static  void testExecute1(){
        List<RecordType> RCTProductPartner = TADUtils.getRecordType(Label.TAD_RT_Product_Partner);
        
        Account acctBussiness = TestDataFactory.createBussinessAccount(RCTProductPartner[0].Id); // Bussiness account Inserted
        acctBussiness.Name = 'test Account for Addon';
        insert acctBussiness;
        
        List<RecordType> RCTTadDeal = TADUtils.getRecordType(Label.TAD_RT_TAD_Deal);
        
        Deal__c deal = TestDataFactory.createMerchantDeal(RCTTadDeal[0].Id , acctBussiness.Id );   // Deals created
        deal.Name = '1214';
        deal.deal_type__c = 'travel';
        deal.deal_archetype__c = 'SANUZ';
        deal.merchant_sharing_deadline__c = 60;
        insert deal;
        
        departure_cities__c depCities = TestDataFactory.createDepartureCitiesBasedonVariable(deal.Id,'AU','Adelaide');
        depCities.Active__c = true;
        depCities.data_refresh__c = false;
        depCities.order_filter__c = 'TAD TC NRMA';
        insert depCities;
        
        options__c options = TestDataFactory.CreateOptions(deal.Id);       // Options crested using the deal
        options.itinerary_context__c='1';
        insert options;
        
        sub_options__c subOptions = TestDataFactory.createSubOptions(options.Id);   // Sub options created
        subOptions.STD_OPT__c ='Standard';
        subOptions.Price1__c  = 1499;
        subOptions.price_nz__c  = 1499;
        subOptions.Name = 'suboption-option-1214';
        insert subOptions;
        
        airline_upgrade__c au = TestDataFactory.createAirlineUpgrade(deal);
        insert au;
        
        Product_FX_Pricing__c pfp = TestDataFactory.createPFXP();
        insert pfp;
        
        List<Component__c> compList = new  List<Component__c>();
        
        Component__c dealComp = TestDataFactory.cutomComponent(acctBussiness,'Rail',pfp);
        dealComp.Deal__c = deal.id;
        dealComp.LinkedDeal_D_O_S__c = deal.id;
        dealComp.ff_Every_X_PAX_is_free__c = 2;
        dealComp.Identifier__c='4';

        compList.add(dealComp);
        
        Component__c auComp = TestDataFactory.cutomComponent(acctBussiness,'Flight Upgrade',pfp);
        auComp.Airline_Upgrade__c = au.id;
        auComp.ff_Every_X_PAX_is_free__c = 4;
        auComp.Identifier__c='1';
        compList.add(auComp);
        
                Component__c subComp = TestDataFactory.cutomComponent(acctBussiness,'Cruise',pfp);
        subComp.LinkedDeal_D_O_S__c = deal.id;
        subComp.ff_Every_X_PAX_is_free__c = 4;
        subComp.Sub_Options__c=subOptions.id;
        subComp.Identifier__c='2';

        compList.add(subComp);

                Component__c opComp = TestDataFactory.cutomComponent(acctBussiness,'Cruise',pfp);
        opComp.LinkedDeal_D_O_S__c = deal.id;
        opComp.ff_Every_X_PAX_is_free__c = 4;
        opComp.Options__c=options.Id;
        opComp.Identifier__c='3';
        compList.add(opComp);

            Component__c depComp = TestDataFactory.cutomComponent(acctBussiness,'Cruise',pfp);
        depComp.ff_Every_X_PAX_is_free__c = 4;
        depComp.Identifier__c='5';
        depComp.City__c=depCities.Id;
        compList.add(depComp);

        insert compList;
        
        Component_Pricing__c price = TestDataFactory.createComPricing(10.0, 1000.0, Date.today(), date.newInstance(2030, 07, 05), 2000.0,1500.0);
        price.Component__c = opComp.Id;
        price.Category__c = 'Single';
        price.solo_rate_total__c = 150;
        price.Cost__c = 120;
        insert price;
        List<tad_cloneChildRecordApexHandler.selectedData> selectedList=new List<tad_cloneChildRecordApexHandler.selectedData>();
        tad_cloneChildRecordApexHandler.selectedData sldata=new tad_cloneChildRecordApexHandler.selectedData();
        sldata.rcdId=subOptions.id;
        sldata.type='suboption';
        sldata.identifier='5';
        selectedList.add(sldata);
        tad_cloneChildRecordApexHandler.selectedData sldata1=new tad_cloneChildRecordApexHandler.selectedData();
        sldata1.rcdId=auComp.id;
        sldata1.type='Component';
        sldata1.identifier='6';

        selectedList.add(sldata1);
        
        tad_cloneChildRecordApexHandler.selectedData sldata2=new tad_cloneChildRecordApexHandler.selectedData();
        sldata2.rcdId=options.id;
        sldata2.type='option';
        sldata2.identifier='7';
        selectedList.add(sldata2);
        tad_cloneChildRecordApexHandler.selectedData sldata3=new tad_cloneChildRecordApexHandler.selectedData();
        sldata3.rcdId=price.id;
        sldata3.type='Component Pricing';
        sldata3.identifier='8';

        selectedList.add(sldata3);
        
        tad_cloneChildRecordApexHandler.selectedData sldata4=new tad_cloneChildRecordApexHandler.selectedData();
        sldata4.rcdId=depCities.id;
        sldata4.type='Departure City';
        sldata4.identifier='9';
        
        selectedList.add(sldata4);
        tad_cloneChildRecordApexHandler.getAllDepartureCityData(depCities.id, 'Departure City');
        tad_cloneChildRecordApexHandler.getAllOptionData(options.Id, 'option');
        //tad_cloneChildRecordApexHandler.getAllOptionData(auComp.Id, 'Component');
      //  tad_cloneChildRecordApexHandler.getAllOptionData(opComp.Id, 'Component');

        tad_cloneChildRecordApexHandler.getAllOptionData(price.Id, 'Component Pricing');
        //tad_cloneChildRecordApexHandler.getAllOptionData(subOptions.Id, 'suboption');
        tad_cloneChildRecordApexHandler.getComponentData(selectedList,'Component',opComp.id);
        tad_cloneChildRecordApexHandler.getComponentPricingData(selectedList);
        tad_cloneChildRecordApexHandler.checkComponentName(selectedList);
        tad_cloneChildRecordApexHandler.saveCloneData(selectedList,'option');
        //tad_cloneChildRecordApexHandler.saveCloneData(selectedList,'Departure City');
      /*  tad_cloneChildRecordApexHandler.saveCloneData(selectedList,'suboption');
        tad_cloneChildRecordApexHandler.saveCloneData(selectedList,'Component');
        tad_cloneChildRecordApexHandler.saveCloneData(selectedList,'Component Pricing');*/
        
    }
    
    @isTest static  void testExecute2(){
        List<RecordType> RCTProductPartner = TADUtils.getRecordType(Label.TAD_RT_Product_Partner);
        
        Account acctBussiness = TestDataFactory.createBussinessAccount(RCTProductPartner[0].Id); // Bussiness account Inserted
        acctBussiness.Name = 'test Account for Addon';
        insert acctBussiness;
        
        List<RecordType> RCTTadDeal = TADUtils.getRecordType(Label.TAD_RT_TAD_Deal);
        
        Deal__c deal = TestDataFactory.createMerchantDeal(RCTTadDeal[0].Id , acctBussiness.Id );   // Deals created
        deal.Name = '1214';
        deal.deal_type__c = 'travel';
        deal.deal_archetype__c = 'SANUZ';
        deal.merchant_sharing_deadline__c = 60;
        insert deal;
        
        options__c options = TestDataFactory.CreateOptions(deal.Id);       // Options created using the deal
        options.itinerary_context__c='1';
        insert options;
        
        departure_cities__c depCities = TestDataFactory.createDepartureCitiesBasedonVariable(deal.Id,'AU','Adelaide');
        depCities.Active__c = true;
        depCities.data_refresh__c = false;
        depCities.order_filter__c = 'TAD TC NRMA';
        insert depCities;
        
        sub_options__c subOptions = TestDataFactory.createSubOptions(options.Id);   // Sub options created
        subOptions.STD_OPT__c ='Standard';
        subOptions.Price1__c  = 1499;
        subOptions.price_nz__c  = 1499;
        subOptions.Name = 'suboption-option-1214';
        insert subOptions;
        
        airline_upgrade__c au = TestDataFactory.createAirlineUpgrade(deal);
        insert au;
        
        Product_FX_Pricing__c pfp = TestDataFactory.createPFXP();
        insert pfp;
        
        List<Component__c> compList = new  List<Component__c>();
        
        Component__c dealComp = TestDataFactory.cutomComponent(acctBussiness,'Rail',pfp);
        dealComp.Deal__c = deal.id;
        dealComp.LinkedDeal_D_O_S__c = deal.id;
        dealComp.ff_Every_X_PAX_is_free__c = 2;
        dealComp.Identifier__c='4';

        compList.add(dealComp);
        
        Component__c auComp = TestDataFactory.cutomComponent(acctBussiness,'Flight Upgrade',pfp);
        auComp.Airline_Upgrade__c = au.id;
        auComp.ff_Every_X_PAX_is_free__c = 4;
        auComp.Identifier__c='1';
        compList.add(auComp);
        
                Component__c subComp = TestDataFactory.cutomComponent(acctBussiness,'Cruise',pfp);
        subComp.LinkedDeal_D_O_S__c = deal.id;
        subComp.ff_Every_X_PAX_is_free__c = 4;
        subComp.Sub_Options__c=subOptions.id;
        subComp.Identifier__c='2';

        compList.add(subComp);

        Component__c opComp = TestDataFactory.cutomComponent(acctBussiness,'Cruise',pfp);
        opComp.LinkedDeal_D_O_S__c = deal.id;
        opComp.ff_Every_X_PAX_is_free__c = 4;
        opComp.Options__c=options.Id;
        opComp.Identifier__c='3';
        compList.add(opComp);

            

        insert compList;
        
        Component_Pricing__c price = TestDataFactory.createComPricing(10.0, 1000.0, Date.today(), date.newInstance(2030, 07, 05), 2000.0,1500.0);
        price.Component__c = opComp.Id;
        price.Category__c = 'Single';
        price.solo_rate_total__c = 150;
        price.Cost__c = 120;
        insert price;
        List<tad_cloneChildRecordApexHandler.selectedData> selectedList=new List<tad_cloneChildRecordApexHandler.selectedData>();
        tad_cloneChildRecordApexHandler.selectedData sldata=new tad_cloneChildRecordApexHandler.selectedData();
        sldata.rcdId=subOptions.id;
        sldata.type='suboption';
        sldata.identifier='5';
        selectedList.add(sldata);
        tad_cloneChildRecordApexHandler.selectedData sldata1=new tad_cloneChildRecordApexHandler.selectedData();
        sldata1.rcdId=auComp.id;
        sldata1.type='Component';
        sldata1.identifier='6';

        selectedList.add(sldata1);
        
        tad_cloneChildRecordApexHandler.selectedData sldata2=new tad_cloneChildRecordApexHandler.selectedData();
        sldata2.rcdId=options.id;
        sldata2.type='option';
        sldata2.identifier='7';
        selectedList.add(sldata2);
        tad_cloneChildRecordApexHandler.selectedData sldata3=new tad_cloneChildRecordApexHandler.selectedData();
        sldata3.rcdId=price.id;
        sldata3.type='Component Pricing';
        sldata2.identifier='8';

        selectedList.add(sldata3);
        
        //tad_cloneChildRecordApexHandler.getAllOptionData(options.Id, 'option');
        //tad_cloneChildRecordApexHandler.getAllOptionData(auComp.Id, 'Component');
      //  tad_cloneChildRecordApexHandler.getAllOptionData(opComp.Id, 'Component');

        tad_cloneChildRecordApexHandler.getAllOptionData(price.Id, 'Component Pricing');
        tad_cloneChildRecordApexHandler.getAllOptionData(subOptions.Id, 'suboption');
        tad_cloneChildRecordApexHandler.getComponentData(selectedList,'',opComp.id);
        tad_cloneChildRecordApexHandler.getComponentPricingData(selectedList);
        tad_cloneChildRecordApexHandler.checkComponentName(selectedList);
        //tad_cloneChildRecordApexHandler.saveCloneData(selectedList,'option');
        tad_cloneChildRecordApexHandler.saveCloneData(selectedList,'suboption');
       // tad_cloneChildRecordApexHandler.saveCloneData(selectedList,'Component');
       // tad_cloneChildRecordApexHandler.saveCloneData(selectedList,'Component Pricing');
        
    }
     @isTest static  void testExecute3(){
        List<RecordType> RCTProductPartner = TADUtils.getRecordType(Label.TAD_RT_Product_Partner);
        
        Account acctBussiness = TestDataFactory.createBussinessAccount(RCTProductPartner[0].Id); // Bussiness account Inserted
        acctBussiness.Name = 'test Account for Addon';
        insert acctBussiness;
        
        List<RecordType> RCTTadDeal = TADUtils.getRecordType(Label.TAD_RT_TAD_Deal);
        
        Deal__c deal = TestDataFactory.createMerchantDeal(RCTTadDeal[0].Id , acctBussiness.Id );   // Deals created
        deal.Name = '1214';
        deal.deal_type__c = 'travel';
        deal.deal_archetype__c = 'SANUZ';
        deal.merchant_sharing_deadline__c = 60;
        insert deal;
        
        options__c options = TestDataFactory.CreateOptions(deal.Id);       // Options crested using the deal
        options.itinerary_context__c='1';
        insert options;
        
        sub_options__c subOptions = TestDataFactory.createSubOptions(options.Id);   // Sub options created
        subOptions.STD_OPT__c ='Standard';
        subOptions.Price1__c  = 1499;
        subOptions.price_nz__c  = 1499;
        subOptions.Name = 'suboption-option-1214';
        insert subOptions;
        
        airline_upgrade__c au = TestDataFactory.createAirlineUpgrade(deal);
        insert au;
        
        Product_FX_Pricing__c pfp = TestDataFactory.createPFXP();
        insert pfp;
        
        List<Component__c> compList = new  List<Component__c>();
        
        Component__c dealComp = TestDataFactory.cutomComponent(acctBussiness,'Rail',pfp);
        dealComp.Deal__c = deal.id;
        dealComp.LinkedDeal_D_O_S__c = deal.id;
        dealComp.ff_Every_X_PAX_is_free__c = 2;
        dealComp.Identifier__c='4';

        compList.add(dealComp);
        
        Component__c auComp = TestDataFactory.cutomComponent(acctBussiness,'Flight Upgrade',pfp);
        auComp.Airline_Upgrade__c = au.id;
        auComp.ff_Every_X_PAX_is_free__c = 4;
        auComp.Identifier__c='1';
        compList.add(auComp);
        
                Component__c subComp = TestDataFactory.cutomComponent(acctBussiness,'Cruise',pfp);
        subComp.LinkedDeal_D_O_S__c = deal.id;
        subComp.ff_Every_X_PAX_is_free__c = 4;
        subComp.Sub_Options__c=subOptions.id;
        subComp.Identifier__c='2';

        compList.add(subComp);

                Component__c opComp = TestDataFactory.cutomComponent(acctBussiness,'Cruise',pfp);
        opComp.LinkedDeal_D_O_S__c = deal.id;
        opComp.ff_Every_X_PAX_is_free__c = 4;
        opComp.Options__c=options.Id;
        opComp.Identifier__c='3';
        compList.add(opComp);

            

        insert compList;
        
        Component_Pricing__c price = TestDataFactory.createComPricing(10.0, 1000.0, Date.today(), date.newInstance(2030, 07, 05), 2000.0,1500.0);
        price.Component__c = opComp.Id;
        price.Category__c = 'Single';
        price.solo_rate_total__c = 150;
        price.Cost__c = 120;
        insert price;
        List<tad_cloneChildRecordApexHandler.selectedData> selectedList=new List<tad_cloneChildRecordApexHandler.selectedData>();
        tad_cloneChildRecordApexHandler.selectedData sldata=new tad_cloneChildRecordApexHandler.selectedData();
        sldata.rcdId=subOptions.id;
        sldata.type='suboption';
        sldata.identifier='5';
        selectedList.add(sldata);
        tad_cloneChildRecordApexHandler.selectedData sldata1=new tad_cloneChildRecordApexHandler.selectedData();
        sldata1.rcdId=auComp.id;
        sldata1.type='Component';
        sldata1.identifier='6';

        selectedList.add(sldata1);
        
        tad_cloneChildRecordApexHandler.selectedData sldata2=new tad_cloneChildRecordApexHandler.selectedData();
        sldata2.rcdId=options.id;
        sldata2.type='option';
        sldata2.identifier='7';
        selectedList.add(sldata2);
        tad_cloneChildRecordApexHandler.selectedData sldata3=new tad_cloneChildRecordApexHandler.selectedData();
        sldata3.rcdId=price.id;
        sldata3.type='Component Pricing';
        sldata2.identifier='8';

        selectedList.add(sldata3);
        

        tad_cloneChildRecordApexHandler.getAllOptionData(price.Id, 'Component Pricing');
        tad_cloneChildRecordApexHandler.getAllOptionData(subOptions.Id, 'sub option');
        tad_cloneChildRecordApexHandler.getComponentData(selectedList,'',opComp.id);
        tad_cloneChildRecordApexHandler.getComponentPricingData(selectedList);
        tad_cloneChildRecordApexHandler.checkComponentName(selectedList);
        //tad_cloneChildRecordApexHandler.saveCloneData(selectedList,'option');
        //tad_cloneChildRecordApexHandler.saveCloneData(selectedList,'suboption');
        tad_cloneChildRecordApexHandler.saveCloneData(selectedList,'Component');
       // tad_cloneChildRecordApexHandler.saveCloneData(selectedList,'Component Pricing');
        
    }
    
}