force-app/main/default/objects/Deal__c/Deal__c.object-meta.xml
<CustomObject>
    <label>Deal</label>
    <nameField>
        <label>Deal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Hero</fullName>
            </value>
            <value>
                <fullName>Published(NRMA)</fullName>
            </value>
            <value>
                <fullName>Published(Staging)</fullName>
            </value>
            <value>
                <fullName>Hero(Staging)</fullName>
            </value>
            <value>
                <fullName>Hidden</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Saved_Deals__c/Saved_Deals__c.object-meta.xml
<CustomObject>
    <label>Sales Lead</label>
    <nameField>
        <label>Sales Lead Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Leads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Saved_Deals__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipName>Saved_Deals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Saved_Deals__c/fields/Reason_Not_Converted__c.field-meta.xml
<CustomField>
    <fullName>Reason_Not_Converted__c</fullName>
    <label>Reason Not Converted L1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>too expensive</fullName>
                <label>Too Expensive</label>
            </value>
            <value>
                <fullName>Customer No Longer Wants</fullName>
            </value>
            <value>
                <fullName>Lead Expired</fullName>
            </value>
            <value>
                <fullName>Order Expired</fullName>
            </value>
            <value>
                <fullName>Order booked by other Agent</fullName>
                <label>Order booked by Other Agent</label>
            </value>
            <value>
                <fullName>Booked with a competitor</fullName>
            </value>
            <value>
                <fullName>Don&apos;t want to risk waiting for minimum number</fullName>
            </value>
            <value>
                <fullName>Can&apos;t book as children not old enough</fullName>
            </value>
            <value>
                <fullName>Dates out of range 2024</fullName>
            </value>
            <value>
                <fullName>Vaccination uncertainty/ Entry requirements</fullName>
            </value>
            <value>
                <fullName>Availability specifically too close to travel date</fullName>
            </value>
            <value>
                <fullName>Surcharge cost for departure city</fullName>
            </value>
            <value>
                <fullName>Wanted to change arrival/departure city</fullName>
            </value>
            <value>
                <fullName>Accommodation deal doesn&apos;t include flights</fullName>
            </value>
            <value>
                <fullName>Internal - Unable to complete purchase</fullName>
            </value>
            <value>
                <fullName>Date affected</fullName>
            </value>
            <value>
                <fullName>Flight affected</fullName>
            </value>
            <value>
                <fullName>We didn&apos;t have want the customer was after</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Only wanted deposit</fullName>
            </value>
            <value>
                <fullName>Wanted payment flexibility</fullName>
            </value>
            <value>
                <fullName>Wanted specific airline booked</fullName>
            </value>
            <value>
                <fullName>Not ready to purchase -general questions</fullName>
                <label>Not ready to purchase-general questions</label>
            </value>
            <value>
                <fullName>Blackout dates on AE and SB</fullName>
                <isActive>false</isActive>
                <label>Blackout dates on AE and SB</label>
            </value>
            <value>
                <fullName>Can&apos;t customise</fullName>
                <isActive>false</isActive>
                <label>Can&apos;t customise</label>
            </value>
            <value>
                <fullName>Competitor better price</fullName>
                <isActive>false</isActive>
                <label>Competitor Better Price</label>
            </value>
            <value>
                <fullName>Didn’t want to include flights</fullName>
                <isActive>false</isActive>
                <label>Didn’t Want to Include Flights</label>
            </value>
            <value>
                <fullName>Internal - No Allocation</fullName>
                <isActive>false</isActive>
                <label>Internal - No Allocation</label>
            </value>
            <value>
                <fullName>Internal - Unable To Complete Request</fullName>
                <isActive>false</isActive>
                <label>Internal - Unable to Complete Request</label>
            </value>
            <value>
                <fullName>Not Ready To Purchase - General Questions</fullName>
                <isActive>false</isActive>
                <label>Not Ready To Purchase - General Questions</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Saved_Deals__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Closed Converted</fullName>
            </value>
            <value>
                <fullName>Closed Not Converted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Tad_BatchClassToUpdateSavedDeals.cls
public class Tad_BatchClassToUpdateSavedDeals implements  Database.Batchable<sObject> {
    @InvocableMethod(label = 'update sales lead records')
    public static void processBatch(List<Id> dealIds){
        Tad_BatchClassToUpdateSavedDeals batchInstance = new Tad_BatchClassToUpdateSavedDeals(dealIds);
        Database.executeBatch(batchInstance);
    }
    private List<Id> dealIds;
    
    public Tad_BatchClassToUpdateSavedDeals(List<Id> dealIds){
        this.dealIds = dealIds;
    }
     public List<Saved_Deals__c> start(Database.BatchableContext bc) {
        List<Saved_Deals__c> recordsToUpdate = [select status__c, Reason_Not_Converted__c from Saved_Deals__c where Deal__c IN :dealIds AND status__c = 'In Progress'];
         return recordsToUpdate;
    }
    public void execute(Database.BatchableContext bc, List<Saved_Deals__c> recordsToUpdate){
        List<Saved_Deals__c> sleadList = new List<Saved_Deals__c>();
        if(recordsToUpdate.size()> 0){
            for (Saved_Deals__c sLead : recordsToUpdate){
                sLead.status__c = 'Closed Not Converted';
                sLead.Reason_Not_Converted__c = 'Lead Expired';
                sleadList.add(sLead);
            }
            try{
                update sleadList;
            }catch(exception e){
                system.debug('Error while updating records'+e.getMessage());
            }
        }
       
        
    }    
    public void finish(Database.BatchableContext bc){
        System.debug('sales lead records updated successfuly');
    } 

}