force-app/main/default/objects/Deal__c/Deal__c.object-meta.xml
<CustomObject>
    <label>Deal</label>
    <nameField>
        <label>Deal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal__c/fields/merchant_sharing_deadline__c.field-meta.xml
<CustomField>
    <fullName>merchant_sharing_deadline__c</fullName>
    <inlineHelpText>Number of days prior to departure that merchant will receive booking confirmation. If multi-merchant deal, please use the most restrictive deadline e.g 120 days instead of 90.</inlineHelpText>
    <label>Merchant Sharing Deadline - Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/departures_dates__c.object-meta.xml
<CustomObject>
    <label>departures dates</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>departures dates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/departures_dates__c/fields/Approved_to_Run_Under_Mins__c.field-meta.xml
<CustomField>
    <fullName>Approved_to_Run_Under_Mins__c</fullName>
    <defaultValue>false</defaultValue>
    <description>For Flight Ticketing team use - can be checked as true if approval received by BDM/Merchant to go ahead with ticketing if mins not yet met</description>
    <inlineHelpText>Check this as true if approval received to run under min numbers</inlineHelpText>
    <label>Approved to Run Under Mins?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/Create_Days_POE__c.field-meta.xml
<CustomField>
    <fullName>Create_Days_POE__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Create Days POE</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/date__c.field-meta.xml
<CustomField>
    <fullName>date__c</fullName>
    <label>date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>departures dates</relationshipLabel>
    <relationshipName>departures_dates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/Deal_for_Reporting__c.field-meta.xml
<CustomField>
    <fullName>Deal_for_Reporting__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Deal for Reporting</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>departures dates (Deal for Reporting)</relationshipLabel>
    <relationshipName>departures_dates1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/finalise_date__c.field-meta.xml
<CustomField>
    <fullName>finalise_date__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Finalise Date</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/options__c.field-meta.xml
<CustomField>
    <fullName>options__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>options</label>
    <referenceTo>options__c</referenceTo>
    <relationshipLabel>departures dates</relationshipLabel>
    <relationshipName>departures_dates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/sub_options__c.field-meta.xml
<CustomField>
    <fullName>sub_options__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>sub options</label>
    <referenceTo>sub_options__c</referenceTo>
    <relationshipLabel>departures dates</relationshipLabel>
    <relationshipName>departures_dates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/options__c/options__c.object-meta.xml
<CustomObject>
    <label>Options</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/options__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipName>options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/sub_options__c/sub_options__c.object-meta.xml
<CustomObject>
    <label>Sub Options</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/sub_options__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Sub Options</relationshipLabel>
    <relationshipName>Sub_Options</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sub_options__c/fields/options__c.field-meta.xml
<CustomField>
    <fullName>options__c</fullName>
    <label>options</label>
    <referenceTo>options__c</referenceTo>
    <relationshipLabel>Sub Options</relationshipLabel>
    <relationshipName>sub_options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/TAD_Order__c.object-meta.xml
<CustomObject>
    <label>TAD Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TAD Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_flights_ticketed__c.field-meta.xml
<CustomField>
    <fullName>ordexp_flights_ticketed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Flights ticketed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_master_status__c.field-meta.xml
<CustomField>
    <fullName>ordexp_master_status__c</fullName>
    <label>Master status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
                <default>true</default>
                <label>On Hold</label>
            </value>
            <value>
                <fullName>Temporary Hold</fullName>
            </value>
            <value>
                <fullName>Secured</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Travelled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>In Progress-Cruise only</fullName>
                <isActive>false</isActive>
                <label>In Progress-Cruise only</label>
            </value>
            <value>
                <fullName>In Progress-Flight only</fullName>
                <isActive>false</isActive>
                <label>In Progress-Flight only</label>
            </value>
            <value>
                <fullName>In Progress-Flights + Cruise</fullName>
                <isActive>false</isActive>
                <label>In Progress-Flights + Cruise</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_stopover_check__c.field-meta.xml
<CustomField>
    <fullName>ordexp_stopover_check__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Stopover Check</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_sub_status__c.field-meta.xml
<CustomField>
    <fullName>ordexp_sub_status__c</fullName>
    <label>Sub status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ordexp_master_status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial Payment Pending</fullName>
            </value>
            <value>
                <fullName>Cancellation Request</fullName>
            </value>
            <value>
                <fullName>Class (Sub Option) - Accom/Cabin Upgrade</fullName>
            </value>
            <value>
                <fullName>Duration/Extention (Option) - Upgrade</fullName>
            </value>
            <value>
                <fullName>Flight Quote Request</fullName>
            </value>
            <value>
                <fullName>Internal Correction/Change</fullName>
            </value>
            <value>
                <fullName>PAX Change Pending</fullName>
            </value>
            <value>
                <fullName>Paid - PIF/s Overdue</fullName>
            </value>
            <value>
                <fullName>Paid - PIF/s Due</fullName>
            </value>
            <value>
                <fullName>Stay Booking - No Ticketing Required</fullName>
            </value>
            <value>
                <fullName>Cabins Pending - Mins Not Met</fullName>
            </value>
            <value>
                <fullName>Flights Pending - Mins Not Met</fullName>
            </value>
            <value>
                <fullName>Flights Pending - Out of Range</fullName>
            </value>
            <value>
                <fullName>Flights Pending - Ready to Ticket</fullName>
            </value>
            <value>
                <fullName>Cabins Pending/Flights Booked - Cabin Ready to Ticket</fullName>
            </value>
            <value>
                <fullName>Cabins Booked</fullName>
            </value>
            <value>
                <fullName>Flights Booked</fullName>
            </value>
            <value>
                <fullName>Cabins Booked/Flights Booked</fullName>
            </value>
            <value>
                <fullName>BC Sent</fullName>
            </value>
            <value>
                <fullName>TP Sent &amp; Cruise Ticket Pending</fullName>
            </value>
            <value>
                <fullName>Travelling</fullName>
            </value>
            <value>
                <fullName>Survey Sent</fullName>
            </value>
            <value>
                <fullName>Survey Returned</fullName>
            </value>
            <value>
                <fullName>Expired/Time out</fullName>
            </value>
            <value>
                <fullName>Offloaded</fullName>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Customer Request</fullName>
            </value>
            <value>
                <fullName>Min Number - Credit/Refund</fullName>
            </value>
            <value>
                <fullName>Pax No Show</fullName>
            </value>
            <value>
                <fullName>Flights Ticketed - NO S/O</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TAD_Order__c/recordTypes/TAD.recordType-meta.xml
<RecordType>
    <fullName>TAD</fullName>
    <active>true</active>
    <label>TAD</label>
</RecordType>

force-app/main/default/classes/PopulateDealValidFromToBatchTest.cls
@isTest
public class PopulateDealValidFromToBatchTest {

    static testmethod void testMethod1(){
        
        List<RecordType> RCTProductPartner = TADUtils.getRecordType(Label.TAD_RT_Product_Partner);
        
        Account acctBussiness = TestDataFactory.createBussinessAccount(RCTProductPartner[0].Id);   // Bussiness account Inserted
        insert acctBussiness;
        
        List<RecordType> RCTTadDeal = TADUtils.getRecordType(Label.TAD_RT_TAD_Deal);
        
        Deal__c deal = TestDataFactory.createMerchantDeal(RCTTadDeal[0].Id , acctBussiness.Id );   // Deals created
        deal.merchant_sharing_deadline__c = 60;
        insert deal;
        
        options__c options = TestDataFactory.CreateOptions(deal.Id);       // Options crested using the deal
        insert options;
        
        sub_options__c subOptions = TestDataFactory.createSubOptions(options.Id);   // Sub options created
        insert subOptions;
        
        List<departures_dates__c> depList = new List<departures_dates__c>();
        departures_dates__c departureDates = TestDataFactory.createDepartureDates(deal.Id,options.Id,subOptions.Id);  // Departure dates data created
        departureDates.date__c=Date.today().addDays(45);
        departureDates.finalise_date__c=true;
        departureDates.create_days_poe__c=true;
        departureDates.Deal_for_Reporting__c = deal.Id;
        depList.add(departureDates);
        
        departures_dates__c departureDates1 = TestDataFactory.createDepartureDates(deal.Id,options.Id,subOptions.Id);  // Departure dates data created
        departureDates1.date__c=Date.today().addDays(50);
        departureDates1.finalise_date__c=true;
        departureDates1.Deal_for_Reporting__c = deal.Id;
        departureDates1.create_days_poe__c=true;
        depList.add(departureDates1);
        
        departures_dates__c departureDates2 = TestDataFactory.createDepartureDates(deal.Id,options.Id,subOptions.Id);  // Departure dates data created
        departureDates2.date__c=Date.today().addDays(55);
        departureDates2.finalise_date__c=true;
        departureDates2.Deal_for_Reporting__c = deal.Id;
        departureDates2.create_days_poe__c=true;
        depList.add(departureDates2);
        
        departures_dates__c departureDates3 = TestDataFactory.createDepartureDates(deal.Id,options.Id,subOptions.Id);  // Departure dates data created
        departureDates3.date__c=Date.today().addDays(60);
        departureDates3.finalise_date__c=true;
        departureDates3.Deal_for_Reporting__c = deal.Id;
        departureDates3.create_days_poe__c=true;
        departureDates3.Approved_to_Run_Under_Mins__c = false;
        depList.add(departureDates3);
        
        insert depList;
        
        
        
        ID RTTADOrder1 = Schema.SObjectType.Tad_Order__C.getRecordTypeInfosByDeveloperName().get('TAD').getRecordTypeId();
        Tad_Order__C order1 = TestDataFactory.createTADOrder(acctBussiness,deal,options,departureDates3,RTTADOrder1);
        order1.ordexp_flights_ticketed__c=true;
        order1.ordexp_stopover_check__c = false;
        order1.ordexp_master_status__c = 'In Progress';
        order1.ordexp_sub_status__c = 'Cabins Pending - Mins Not Met';
        insert order1;

        departureDates3.Approved_to_Run_Under_Mins__c = true;
        update departureDates3;
        
        Test.StartTest();
        PopulateDealValidFromToBatchSchedule testsche = new PopulateDealValidFromToBatchSchedule();
        String sch = '0 0 23 * * ?';
        system.schedule('Test status Check', sch, testsche );
        Test.stopTest();
        
    }
}