force-app/main/default/objects/Deal__c/Deal__c.object-meta.xml
<CustomObject>
    <label>Deal</label>
    <nameField>
        <label>Deal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal__c/fields/BNCDL__c.field-meta.xml
<CustomField>
    <fullName>BNCDL__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BNCDL</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Deal__c/fields/BNCDL_BBD_1_Week__c.field-meta.xml
<CustomField>
    <fullName>BNCDL_BBD_1_Week__c</fullName>
    <formula>BNCDL_BBD__c - 7</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>BNCDL BBD - 1 Week</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Deal__c/fields/BNCDL_BBD_1_Week_Comms__c.field-meta.xml
<CustomField>
    <fullName>BNCDL_BBD_1_Week_Comms__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BNCDL BBD - 1 Week Comms</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Deal__c/fields/BNCDL_BBD_4_Weeks__c.field-meta.xml
<CustomField>
    <fullName>BNCDL_BBD_4_Weeks__c</fullName>
    <formula>BNCDL_BBD__c - ((365/52)*4)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>BNCDL BBD - 4 Weeks</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Deal__c/fields/BNCDL_BBD_4_Weeks_Comms__c.field-meta.xml
<CustomField>
    <fullName>BNCDL_BBD_4_Weeks_Comms__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BNCDL BBD - 4 Weeks Comms</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Deal__c/fields/BNCDL_BBD__c.field-meta.xml
<CustomField>
    <fullName>BNCDL_BBD__c</fullName>
    <label>BNCDL BBD</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Deal__c/fields/BNCDL_BBD_Final_Comms__c.field-meta.xml
<CustomField>
    <fullName>BNCDL_BBD_Final_Comms__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BNCDL BBD - Final Comms</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/departures_dates__c.object-meta.xml
<CustomObject>
    <label>departures dates</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>departures dates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/departures_dates__c/fields/BNCDL__c.field-meta.xml
<CustomField>
    <fullName>BNCDL__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BNCDL</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>departures dates</relationshipLabel>
    <relationshipName>departures_dates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Communication_POE__c/Order_Communication_POE__c.object-meta.xml
<CustomObject>
    <description>Records created by scheduled apex</description>
    <label>Order Communication</label>
    <nameField>
        <displayFormat>OC-{00000000}</displayFormat>
        <label>Order Communication Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Communications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Communication_POE__c/fields/communication_code__c.field-meta.xml
<CustomField>
    <fullName>communication_code__c</fullName>
    <label>Communication Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Communication_POE__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <formula>TAD_Order__r.Deal_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Deal</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Communication_POE__c/fields/email_purchaser__c.field-meta.xml
<CustomField>
    <fullName>email_purchaser__c</fullName>
    <label>Email(Purchaser)</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Order_Communication_POE__c/fields/orderexp_Purchaser_Full_Name__c.field-meta.xml
<CustomField>
    <fullName>orderexp_Purchaser_Full_Name__c</fullName>
    <formula>TAD_Order__r.ordexp_account__r.PersonContact.FirstName &amp;&quot; &quot;&amp; TAD_Order__r.ordexp_account__r.PersonContact.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Purchaser Full Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Communication_POE__c/fields/ordexp_Departure_Date__c.field-meta.xml
<CustomField>
    <fullName>ordexp_Departure_Date__c</fullName>
    <formula>TAD_Order__r.ordexp_departure_date__r.date__c</formula>
    <label>Departure Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order_Communication_POE__c/fields/ordexp_Purchase_Date__c.field-meta.xml
<CustomField>
    <fullName>ordexp_Purchase_Date__c</fullName>
    <formula>TAD_Order__r.ordexp_purchase_date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Purchase Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Order_Communication_POE__c/fields/TAD_Order__c.field-meta.xml
<CustomField>
    <fullName>TAD_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TAD Order</label>
    <referenceTo>TAD_Order__c</referenceTo>
    <relationshipLabel>Order Communications</relationshipLabel>
    <relationshipName>Order_Communications_POE</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/TAD_Order__c.object-meta.xml
<CustomObject>
    <label>TAD Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TAD Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TAD_Order__c/fields/Account_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Account_Email_Address__c</fullName>
    <formula>IF( RecordType.Name=&apos;TAD&apos; || RecordType.Name=&apos;TNZ&apos; || RecordType.Name=&apos;Hotel&apos;  , IF(OR(ordexp_account__r.RecordType.Name = &apos;Product Partner&apos;,ordexp_account__r.RecordType.Name = &apos;PAF Corp Client&apos;), ordexp_account__r.Company_Email__c , ordexp_account__r.PersonEmail),  IF(OR(Agency_Id__r.RecordType.Name = &apos;Product Partner&apos;,Agency_Id__r.RecordType.Name = &apos;PAF Corp Client&apos;), Agency_Id__r.Company_Email__c , Agency_Id__r.PersonEmail))</formula>
    <label>Account Email Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/Account_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Phone_Number__c</fullName>
    <formula>IF(
NOT(ISBLANK(ordexp_account__r.PersonContact.MobilePhone)),
ordexp_account__r.PersonContact.MobilePhone,
(ordexp_account__r.Phone)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Phone Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/Automate_Cancellation__c.field-meta.xml
<CustomField>
    <fullName>Automate_Cancellation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Automate Cancellation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_deal__c.field-meta.xml
<CustomField>
    <fullName>ordexp_deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>TAD_Orders_Deal</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_departure_date__c.field-meta.xml
<CustomField>
    <fullName>ordexp_departure_date__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Departure date</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>(1 OR 2) AND 3</booleanFilter>
        <filterItems>
            <field>departures_dates__c.Deal__c</field>
            <operation>equals</operation>
            <valueField>$Source.ordexp_deal__c</valueField>
        </filterItems>
        <filterItems>
            <field>departures_dates__c.options__c</field>
            <operation>equals</operation>
            <valueField>$Source.ordexp_option__c</valueField>
        </filterItems>
        <filterItems>
            <field>departures_dates__c.online_status__c</field>
            <operation>equals</operation>
            <value>Online</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>departures_dates__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>TAD_Orders_DD</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_master_status__c.field-meta.xml
<CustomField>
    <fullName>ordexp_master_status__c</fullName>
    <label>Master status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
                <default>true</default>
                <label>On Hold</label>
            </value>
            <value>
                <fullName>Temporary Hold</fullName>
            </value>
            <value>
                <fullName>Secured</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Travelled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>In Progress-Cruise only</fullName>
                <isActive>false</isActive>
                <label>In Progress-Cruise only</label>
            </value>
            <value>
                <fullName>In Progress-Flight only</fullName>
                <isActive>false</isActive>
                <label>In Progress-Flight only</label>
            </value>
            <value>
                <fullName>In Progress-Flights + Cruise</fullName>
                <isActive>false</isActive>
                <label>In Progress-Flights + Cruise</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_Order_Cancelled__c.field-meta.xml
<CustomField>
    <fullName>ordexp_Order_Cancelled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Order Cancelled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_purchase_date__c.field-meta.xml
<CustomField>
    <fullName>ordexp_purchase_date__c</fullName>
    <label>Purchase date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_sub_status__c.field-meta.xml
<CustomField>
    <fullName>ordexp_sub_status__c</fullName>
    <label>Sub status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ordexp_master_status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial Payment Pending</fullName>
            </value>
            <value>
                <fullName>Cancellation Request</fullName>
            </value>
            <value>
                <fullName>Class (Sub Option) - Accom/Cabin Upgrade</fullName>
            </value>
            <value>
                <fullName>Duration/Extention (Option) - Upgrade</fullName>
            </value>
            <value>
                <fullName>Flight Quote Request</fullName>
            </value>
            <value>
                <fullName>Internal Correction/Change</fullName>
            </value>
            <value>
                <fullName>PAX Change Pending</fullName>
            </value>
            <value>
                <fullName>Paid - PIF/s Overdue</fullName>
            </value>
            <value>
                <fullName>Paid - PIF/s Due</fullName>
            </value>
            <value>
                <fullName>Stay Booking - No Ticketing Required</fullName>
            </value>
            <value>
                <fullName>Cabins Pending - Mins Not Met</fullName>
            </value>
            <value>
                <fullName>Flights Pending - Mins Not Met</fullName>
            </value>
            <value>
                <fullName>Flights Pending - Out of Range</fullName>
            </value>
            <value>
                <fullName>Flights Pending - Ready to Ticket</fullName>
            </value>
            <value>
                <fullName>Cabins Pending/Flights Booked - Cabin Ready to Ticket</fullName>
            </value>
            <value>
                <fullName>Cabins Booked</fullName>
            </value>
            <value>
                <fullName>Flights Booked</fullName>
            </value>
            <value>
                <fullName>Cabins Booked/Flights Booked</fullName>
            </value>
            <value>
                <fullName>BC Sent</fullName>
            </value>
            <value>
                <fullName>TP Sent &amp; Cruise Ticket Pending</fullName>
            </value>
            <value>
                <fullName>Travelling</fullName>
            </value>
            <value>
                <fullName>Survey Sent</fullName>
            </value>
            <value>
                <fullName>Survey Returned</fullName>
            </value>
            <value>
                <fullName>Expired/Time out</fullName>
            </value>
            <value>
                <fullName>Offloaded</fullName>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Customer Request</fullName>
            </value>
            <value>
                <fullName>Min Number - Credit/Refund</fullName>
            </value>
            <value>
                <fullName>Pax No Show</fullName>
            </value>
            <value>
                <fullName>Flights Ticketed - NO S/O</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/RecordType_Name__c.field-meta.xml
<CustomField>
    <fullName>RecordType_Name__c</fullName>
    <formula>RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Record Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/recordTypes/TAD.recordType-meta.xml
<RecordType>
    <fullName>TAD</fullName>
    <active>true</active>
    <label>TAD</label>
</RecordType>

force-app/main/default/objects/TAD_Order__c/recordTypes/TC.recordType-meta.xml
<RecordType>
    <fullName>TC</fullName>
    <active>true</active>
    <label>TC</label>
</RecordType>

force-app/main/default/objects/TAD_Order__c/recordTypes/TNZ.recordType-meta.xml
<RecordType>
    <fullName>TNZ</fullName>
    <active>true</active>
    <label>TNZ</label>
</RecordType>

force-app/main/default/objects/TAD_Order__c/recordTypes/WT.recordType-meta.xml
<RecordType>
    <fullName>WT</fullName>
    <active>true</active>
    <label>WT</label>
</RecordType>

force-app/main/default/classes/tad_BNCDLAutoCreditNotificationBatch.cls
global class tad_BNCDLAutoCreditNotificationBatch implements Database.Batchable<sObject> {
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([select id,RecordType_Name__c,Account_Email_Address__c,Account_phone_number__c,ordexp_deal__c,ordexp_deal__r.BNCDL_BBD_Final_Comms__c,ordexp_deal__r.BNCDL_BBD_1_Week_Comms__c,ordexp_deal__r.BNCDL_BBD_4_Weeks_Comms__c,ordexp_deal__r.BNCDL__c,ordexp_deal__r.BNCDL_BBD__c,ordexp_deal__r.BNCDL_BBD_1_Week__c,ordexp_deal__r.BNCDL_BBD_4_Weeks__c from tad_order__c where ordexp_deal__r.BNCDL__c = true AND ordexp_deal__r.BNCDL_BBD__c != Null AND ordexp_departure_date__r.BNCDL__c = true and ordexp_master_status__c !='Cancelled']);
    } 
    
    
    global void execute(Database.BatchableContext bc, List<tad_order__c> scope) {
        system.debug('scope '+scope);
        list<Order_Communication_POE__c> ocListToInsert = new list<Order_Communication_POE__c>();
        list<deal__c> dealListToUpdate = new list<deal__c>();
        list<tad_order__c> tadOrdListToUpdate = new list<tad_order__c>();
        
        
        date todayDate = system.today();
        
        for(tad_order__c ord:scope){
            system.debug('ord.ordexp_deal__r.BNCDL_BBD__c '+ord.ordexp_deal__r.BNCDL_BBD__c);
            system.debug('ord.ordexp_deal__r.BNCDL_BBD__c '+ord.ordexp_deal__r.BNCDL_BBD_1_Week__c);
            system.debug('ord.ordexp_deal__r.BNCDL_BBD__c '+ord.ordexp_deal__r.BNCDL_BBD_4_Weeks__c);
            system.debug('ord.ordexp_deal__r.BNCDL_BBD__c '+todayDate);
            if(ord.ordexp_deal__r.BNCDL__c == true){
                
                if(todayDate == ord.ordexp_deal__r.BNCDL_BBD__c && ord.ordexp_deal__r.BNCDL_BBD_Final_Comms__c == false){
                    Order_Communication_POE__c  ordCmms = new Order_Communication_POE__c();
                    ordCmms.TAD_Order__c = ord.Id;
                    ordCmms.email_purchaser__c = ord.Account_Email_Address__c;
                    ordCmms.phone__c = ord.Account_phone_number__c;
                    if(ord.RecordType_Name__c == 'TAD'){
                        ordCmms.communication_code__c = 'TADQF_BNCDL_Offload'; 
                    }
                    if(ord.RecordType_Name__c == 'TC'){
                        ordCmms.communication_code__c = 'TCQF_BNCDL_Offload'; 
                    }
                    if(ord.RecordType_Name__c == 'TNZ'){
                        ordCmms.communication_code__c = 'TNZQF_BNCDL_Offload'; 
                    }
                    if(ord.RecordType_Name__c == 'WT'){
                        ordCmms.communication_code__c = 'WTQF_BNCDL_Offload'; 
                    }
                    
                    //update tad order
                    tad_order__c ordUpdate = new tad_order__c(Id = ord.Id);
                    ordUpdate.ordexp_master_status__c = 'Cancelled';
                    ordUpdate.ordexp_sub_status__c = 'Offloaded';
                    ordUpdate.Automate_Cancellation__c= true;
                    ordUpdate.ordexp_Order_Cancelled__c = true;
                    ordUpdate.Order_Cancelled_On__c = system.today();
                    tadOrdListToUpdate.add(ordUpdate);
                    
                    //update deal record
                    deal__c deal = new deal__c(id = ord.ordexp_deal__c);
                    deal.BNCDL_BBD_Final_Comms__c = true;
                    dealListToUpdate.add(deal);
                    ocListToInsert.add(ordCmms);
                }
                
                if(todayDate == ord.ordexp_deal__r.BNCDL_BBD_1_Week__c && ord.ordexp_deal__r.BNCDL_BBD_1_Week_Comms__c == false){
                    Order_Communication_POE__c  ordCmms = new Order_Communication_POE__c();
                    ordCmms.TAD_Order__c = ord.Id;
                    ordCmms.email_purchaser__c = ord.Account_Email_Address__c;
                    ordCmms.phone__c = ord.Account_phone_number__c;
                    if(ord.RecordType_Name__c == 'TAD'){
                        ordCmms.communication_code__c = 'TADQF_BNCDL_1_Week_Reminder';
                    }
                    if(ord.RecordType_Name__c == 'TC'){
                        ordCmms.communication_code__c = 'TCQF_BNCDL_1_Week_Reminder'; 
                    }
                    if(ord.RecordType_Name__c == 'TNZ'){
                        ordCmms.communication_code__c = 'TNQF_BNCDL_1_Week_Reminder'; 
                    }
                    if(ord.RecordType_Name__c == 'WT'){
                        ordCmms.communication_code__c = 'WtQF_BNCDL_1_Week_Reminder'; 
                    }
                    
                    //update deal record
                    deal__c deal = new deal__c(id = ord.ordexp_deal__c);
                    deal.BNCDL_BBD_1_Week_Comms__c = true;
                    dealListToUpdate.add(deal);
                    ocListToInsert.add(ordCmms);
                }
                
                if(todayDate == ord.ordexp_deal__r.BNCDL_BBD_4_Weeks__c && ord.ordexp_deal__r.BNCDL_BBD_4_Weeks_Comms__c == false){
                    Order_Communication_POE__c  ordCmms = new Order_Communication_POE__c();
                    ordCmms.TAD_Order__c = ord.Id;
                    ordCmms.email_purchaser__c = ord.Account_Email_Address__c;
                    ordCmms.phone__c = ord.Account_phone_number__c;
                    
                    if(ord.RecordType_Name__c == 'TAD'){
                        ordCmms.communication_code__c = 'TADQF_BNCDL_4_Week_Reminder';
                    }
                    if(ord.RecordType_Name__c == 'TC'){
                        ordCmms.communication_code__c = 'TCQF_BNCDL_4_Week_Reminder'; 
                    }
                    if(ord.RecordType_Name__c == 'TNZ'){
                        ordCmms.communication_code__c = 'TNZQF_BNCDL_4_Week_Reminder'; 
                    }
                    if(ord.RecordType_Name__c == 'WT'){
                        ordCmms.communication_code__c = 'WtQF_BNCDL_4_Week_Reminder'; 
                    }
                    
                    //update deal record
                    deal__c deal = new deal__c(id = ord.ordexp_deal__c);
                    deal.BNCDL_BBD_4_Weeks_Comms__c = true;
                    dealListToUpdate.add(deal);
                    ocListToInsert.add(ordCmms);
                }
            }
        }
        try {
            if(!ocListToInsert.isEmpty()){
                //system.debug('ocListToInsert '+ocListToInsert);
                insert ocListToInsert;
            }
            if(!tadOrdListToUpdate.isEmpty()){
                //update tad order status to cancelled
                system.debug('tadOrdListToUpdate '+tadOrdListToUpdate);
                update tadOrdListToUpdate;
            }
            //update deal record
            if(!dealListToUpdate.isEmpty()){
                update dealListToUpdate;
            }
        } catch (Exception e) {
            System.debug(e.getMessage());
        }
        
        /*
List<EmailTemplate> fetchEmailTemplList = [Select Id, Name,DeveloperName, Subject, Body, HtmlValue from EmailTemplate where DeveloperName IN : emailTemplateName];
Map<string,EmailTemplate> emailTmpMap = new Map<string,EmailTemplate>();
for(EmailTemplate objET:fetchEmailTemplList){
emailTmpMap.put(objET.DeveloperName,objET);
}


List<Messaging.SingleEmailMessage> allmsg = new List<Messaging.SingleEmailMessage>();
list<Order_Communication_POE__c> fetchOrdCmmsListToSendEmail = [SELECT Id,communication_code__c,ordexp_Purchase_Date__c,orderexp_Purchaser_Full_Name__c,email_purchaser__c,order_number__c,Stay_Property_Name__c,ordexp_DealFC_fromTADOrder__c,OptionsPC_fromTADOrder__c,
TAD_Coupon_Name__c,Coupon_Total__c,Deal_and_Title__c,ordexp_Purchaser_First_Name__c,BNCDL_Book_By_Date__c from Order_Communication_POE__c WHERE Id IN:ocListToInsert];
system.debug('fetchOrdCmmsListToSendEmail '+fetchOrdCmmsListToSendEmail);
for(Order_Communication_POE__c oc:fetchOrdCmmsListToSendEmail){
system.debug('oc.communication_code__c '+oc.communication_code__c);
Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
if(oc.communication_code__c.contains('TADQF_BNCDL_1_Week_Reminder') || oc.communication_code__c.contains('WtQF_BNCDL_1_Week_Reminder') || oc.communication_code__c.contains('TCQF_BNCDL_1_Week_Reminder') || oc.communication_code__c.contains('TNQF_BNCDL_1_Week_Reminder')){
system.debug('oc.communication_code__c '+oc.communication_code__c);
list<string> strList = oc.communication_code__c.split(' ');
EmailTemplate emailTemp1Week = emailTmpMap.get(strList[0]);

system.debug('oc.communication_code__c '+oc.communication_code__c);
String emailBody = emailTemp1Week.HTMLValue;
emailbody=emailBody.replace('{!Order_Communication_POE__c.ordexp_Purchaser_First_Name__c}',oc.ordexp_Purchaser_First_Name__c);
emailbody=emailBody.replace('{!Order_Communication_POE__c.Deal_and_Title__c}',oc.Deal_and_Title__c);
DateTime yourDate = oc.BNCDL_Book_By_Date__c;
String dateStr = yourDate.format('dd/MM/yy'); 
emailbody=emailBody.replace('{!Order_Communication_POE__c.BNCDL_Book_By_Date__c}',string.valueOf(dateStr));

if(emailTemp1Week.subject.contains('{!Order_Communication_POE__c.order_number__c}')){
String emailSubject = emailTemp1Week.Subject;
emailSubject = emailSubject.replace('{!Order_Communication_POE__c.order_number__c}',oc.order_number__c);
mail.setSubject(emailSubject);    
}else{
mail.setSubject(emailTemp1Week.subject);  
}

mail.toAddresses = new String[] { 'pawan.kumar@psagtechnologies.com' };
mail.setTemplateID(emailTemp1Week.Id);
mail.setHtmlBody(emailbody);
allmsg.add(mail);
}
if(oc.communication_code__c.contains('TADQF_BNCDL_4_Week_Reminder') || oc.communication_code__c.contains('WtQF_BNCDL_4_Week_Reminder') || oc.communication_code__c.contains('TCQF_BNCDL_4_Week_Reminder') || oc.communication_code__c.contains('TNZQF_BNCDL_4_Week_Reminder')){
system.debug('oc.communication_code__c '+oc.communication_code__c);
list<string> strList = oc.communication_code__c.split(' ');
EmailTemplate emailTemp4Week = emailTmpMap.get(strList[0]);

String emailBody = emailTemp4Week.HTMLValue;
emailbody=emailBody.replace('{!Order_Communication_POE__c.ordexp_Purchaser_First_Name__c}',oc.ordexp_Purchaser_First_Name__c);
emailbody=emailBody.replace('{!Order_Communication_POE__c.Deal_and_Title__c}',oc.Deal_and_Title__c);
DateTime yourDate = oc.BNCDL_Book_By_Date__c;
String dateStr = yourDate.format('dd/MM/yy'); 
emailbody=emailBody.replace('{!Order_Communication_POE__c.BNCDL_Book_By_Date__c}',string.valueOf(dateStr));

if(emailTemp4Week.subject.contains('{!Order_Communication_POE__c.order_number__c}')){
String emailSubject = emailTemp4Week.Subject;
emailSubject = emailSubject.replace('{!Order_Communication_POE__c.order_number__c}',oc.order_number__c);
mail.setSubject(emailSubject);    
}else{
mail.setSubject(emailTemp4Week.subject);  
}

mail.toAddresses = new String[] { 'pawan.kumar@psagtechnologies.com' };
mail.setTemplateID(emailTemp4Week.Id); 
mail.setHtmlBody(emailbody);
allmsg.add(mail);
}
if(oc.communication_code__c.contains('TADQF_BNCDL_Offload') || oc.communication_code__c.contains('TNZQF_BNCDL_Offload') || oc.communication_code__c.contains('WTQF_BNCDL_Offload') || oc.communication_code__c.contains('TCQF_BNCDL_Offload')){
system.debug('oc.communication_code__c '+oc.communication_code__c);
list<string> strList = oc.communication_code__c.split(' ');
EmailTemplate emailTempOffLoad = emailTmpMap.get(strList[0]);

String emailSubject = emailTempOffLoad.Subject;
emailSubject = emailSubject.replace('{!Order_Communication_POE__c.order_number__c}',oc.order_number__c);

String emailBody = emailTempOffLoad.HTMLValue;
if(oc.orderexp_Purchaser_Full_Name__c!=Null){
emailbody=emailBody.replace('{!Order_Communication_POE__c.orderexp_Purchaser_Full_Name__c}',oc.orderexp_Purchaser_Full_Name__c); 
}else{
emailbody=emailBody.replace('{!Order_Communication_POE__c.orderexp_Purchaser_Full_Name__c}','');   
}
if(oc.email_purchaser__c!=Null){
emailbody=emailBody.replace('{!Order_Communication_POE__c.email_purchaser__c}',oc.email_purchaser__c); 
}else{
emailbody=emailBody.replace('{!Order_Communication_POE__c.orderexp_Purchaser_Full_Name__c}','');   
}   
if(oc.Stay_Property_Name__c!=Null){
emailbody=emailBody.replace('{!Order_Communication_POE__c.Stay_Property_Name__c}',oc.Stay_Property_Name__c);
}
if(oc.ordexp_Purchase_Date__c!=Null){
DateTime yourDate = oc.ordexp_Purchase_Date__c;
String dateStr = yourDate.format('dd/MM/yy'); 
emailbody=emailBody.replace('{!Order_Communication_POE__c.ordexp_Purchase_Date__c}',string.valueOf(dateStr));
}
if(oc.BNCDL_Book_By_Date__c!=Null){
DateTime yourDate = oc.BNCDL_Book_By_Date__c;
String dateStr = yourDate.format('dd/MM/yy');
emailbody=emailBody.replace('{!Order_Communication_POE__c.BNCDL_Book_By_Date__c}',string.valueOf(dateStr));
}
emailbody=emailBody.replace('{!Order_Communication_POE__c.order_number__c}',oc.order_number__c); 
emailbody=emailBody.replace('{!Order_Communication_POE__c.ordexp_DealFC_fromTADOrder__c}',oc.ordexp_DealFC_fromTADOrder__c);

emailbody=emailBody.replace('{!Order_Communication_POE__c.OptionsPC_fromTADOrder__c}',string.valueOf(oc.OptionsPC_fromTADOrder__c));
//emailbody=emailBody.replace('{!Order_Communication_POE__c.TAD_Coupon_Name__c}',oc.TAD_Coupon_Name__c);
//emailbody=emailBody.replace('{!Order_Communication_POE__c.Coupon_Total__c}',oc.Coupon_Total__c);
emailbody=emailBody.replace('{!Order_Communication_POE__c.ordexp_DealFC_fromTADOrder__c}',oc.ordexp_DealFC_fromTADOrder__c);

DateTime TodayDateEmailBody = System.Today().addMonths(6);
String dateStrToday = TodayDateEmailBody.format('dd/MM/yy');    
emailbody=emailBody.replace('{!ADDMONTHS(TODAY(),6)}',string.valueOf(dateStrToday));

mail.toAddresses = new String[] { 'pawan.kumar@psagtechnologies.com' };
mail.setTemplateID(emailTempOffLoad.Id);
mail.setSubject(emailSubject);
mail.setHtmlBody(emailbody);
allmsg.add(mail);
}
}
system.debug('allmsg   '+allmsg);*/
    }
    
    global void finish(Database.BatchableContext bc) {
        
    }
}