force-app/main/default/objects/Deal__c/Deal__c.object-meta.xml
<CustomObject>
    <label>Deal</label>
    <nameField>
        <label>Deal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketing_Spend__c/Marketing_Spend__c.object-meta.xml
<CustomObject>
    <label>Marketing Spend</label>
    <nameField>
        <displayFormat>MA-{000000}</displayFormat>
        <label>Marketing Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Marketing Spend</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketing_Spend__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Marketing Spend</relationshipLabel>
    <relationshipName>Marketing_Spend</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Marketing_Spend__c/fields/ms_Marketing_inventory__c.field-meta.xml
<CustomField>
    <fullName>ms_Marketing_inventory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Marketing Inventory</label>
    <referenceTo>ms_Marketing_Inventory__c</referenceTo>
    <relationshipLabel>Marketing Spend</relationshipLabel>
    <relationshipName>Marketing_Spend</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Marketing_Spend_Child__c/Marketing_Spend_Child__c.object-meta.xml
<CustomObject>
    <label>Marketing Spend Child</label>
    <nameField>
        <displayFormat>Marketing ActivityC-{000000}</displayFormat>
        <label>Marketing Spend Child Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Marketing Spend Dates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ms_Marketing_Inventory__c/ms_Marketing_Inventory__c.object-meta.xml
<CustomObject>
    <label>Marketing Inventory</label>
    <nameField>
        <label>Marketing Inventory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing Inventories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ms_Marketing_Inventory__c/fields/ms_Marketing_Inventory__c.field-meta.xml
<CustomField>
    <fullName>ms_Marketing_Inventory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Marketing Inventory</label>
    <referenceTo>ms_Marketing_Inventory__c</referenceTo>
    <relationshipLabel>Marketing Inventories</relationshipLabel>
    <relationshipName>Marketing_Inventories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ViewCalendarDueDateTest.cls
@isTest
public class ViewCalendarDueDateTest {
 @isTest
    static void myTest(){
         test.startTest();
        ViewCalendarDueDate.fetchAllSpendRecords();
     List<String> searchBookingId = new List<String>() ;
        searchBookingId.add('1484510');
        List<String> selectedDealtypes = new List<String>();
        selectedDealtypes.add('sdca');
        List<String> selectedDeals = new List<String>();
        selectedDeals.add('test');
        List<String> selectedChannels = new List<String>();
		selectedChannels.add('test');
                
        List<String> selectedTitles = new List<String>(); 
       
        
        List<String> selectedsuppliers = new List<String>();
        selectedsuppliers.add('test');
        
        List<String> selectedPlacement = new List<String>();
        selectedPlacement.add('test');
        
        Decimal cost=152;
        
        List<String> selectedGeo = new List<String>();
        selectedGeo.add('test');
        
        List<String> approvalStatusValue = new List<String>();
        approvalStatusValue.add('test');
        
        List<String> statusValue = new List<String>(); 
        statusValue.add('test');
        
        String countryValue ='Australia';
        Deal__c d = TestDataFactory.createMarketingDeal();
        ms_Marketing_Inventory__c mi = TestDataFactory.createMarketingInventory('testInv');
        Marketing_Spend__c ms = TestDataFactory.createMarketingSpend(mi.Id, d.Id);
        Marketing_Spend_Child__c msc = TestDataFactory.createMarketingSpendChild(ms.Id);
       
        List<Marketing_Spend__c> marketingSpendList = new List<Marketing_Spend__c>();
    marketingSpendList.add(ms);
       
        ViewCalendarDueDate.filterSpendRecords(searchBookingId, selectedDealtypes, selectedDeals, selectedChannels, selectedTitles, selectedsuppliers, selectedPlacement, cost, selectedGeo, approvalStatusValue, statusValue, countryValue, marketingSpendList);
      test.stopTest();
        
    }
}