force-app/main/default/objects/Deal__c/Deal__c.object-meta.xml
<CustomObject>
    <label>Deal</label>
    <nameField>
        <label>Deal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal__c/fields/Allocation_by__c.field-meta.xml
<CustomField>
    <fullName>Allocation_by__c</fullName>
    <label>Allocation by</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Deal</fullName>
                <default>true</default>
                <label>Deal</label>
            </value>
            <value>
                <fullName>Option</fullName>
            </value>
            <value>
                <fullName>Sub option</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal__c/fields/deal_archetype__c.field-meta.xml
<CustomField>
    <fullName>deal_archetype__c</fullName>
    <label>Deal Archetype</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MADU1</fullName>
            </value>
            <value>
                <fullName>MADUZ1</fullName>
            </value>
            <value>
                <fullName>MADU2</fullName>
            </value>
            <value>
                <fullName>MADUZ2</fullName>
            </value>
            <value>
                <fullName>TAIU1</fullName>
            </value>
            <value>
                <fullName>TAIZ1</fullName>
            </value>
            <value>
                <fullName>TAIUZ1</fullName>
            </value>
            <value>
                <fullName>TAIU2</fullName>
            </value>
            <value>
                <fullName>TAIZ2</fullName>
            </value>
            <value>
                <fullName>TAIUZ2</fullName>
            </value>
            <value>
                <fullName>TANU1</fullName>
            </value>
            <value>
                <fullName>TANZ1</fullName>
            </value>
            <value>
                <fullName>TANUZ1</fullName>
            </value>
            <value>
                <fullName>TANU2</fullName>
            </value>
            <value>
                <fullName>TANZ2</fullName>
            </value>
            <value>
                <fullName>TANUZ2</fullName>
            </value>
            <value>
                <fullName>MANU1</fullName>
            </value>
            <value>
                <fullName>MANUZ1</fullName>
            </value>
            <value>
                <fullName>MANU2</fullName>
            </value>
            <value>
                <fullName>MANUZ2</fullName>
            </value>
            <value>
                <fullName>RADU1</fullName>
            </value>
            <value>
                <fullName>RADUZ1</fullName>
            </value>
            <value>
                <fullName>RADU2</fullName>
            </value>
            <value>
                <fullName>RADUZ2</fullName>
            </value>
            <value>
                <fullName>CAIU1</fullName>
            </value>
            <value>
                <fullName>CAIZ1</fullName>
            </value>
            <value>
                <fullName>CAIUZ1</fullName>
            </value>
            <value>
                <fullName>CAIU2</fullName>
            </value>
            <value>
                <fullName>CAIZ2</fullName>
            </value>
            <value>
                <fullName>CAIUZ2</fullName>
            </value>
            <value>
                <fullName>SANUZ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal__c/fields/deal_type__c.field-meta.xml
<CustomField>
    <fullName>deal_type__c</fullName>
    <label>deal type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>travel</fullName>
            </value>
            <value>
                <fullName>cruise</fullName>
            </value>
            <value>
                <fullName>stay</fullName>
            </value>
            <value>
                <fullName>Siteminder Hotel</fullName>
            </value>
            <value>
                <fullName>Experiences</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal__c/fields/Flight_Book_By__c.field-meta.xml
<CustomField>
    <fullName>Flight_Book_By__c</fullName>
    <label>Flight Book By</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Deal__c/fields/merchant_sharing_deadline__c.field-meta.xml
<CustomField>
    <fullName>merchant_sharing_deadline__c</fullName>
    <inlineHelpText>Number of days prior to departure that merchant will receive booking confirmation. If multi-merchant deal, please use the most restrictive deadline e.g 120 days instead of 90.</inlineHelpText>
    <label>Merchant Sharing Deadline - Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Deal__c/fields/price__c.field-meta.xml
<CustomField>
    <fullName>price__c</fullName>
    <label>price</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Test_TAD_DealCreationViewOpportunity.cls
@isTest
private class Test_TAD_DealCreationViewOpportunity {
    
    @TestSetup
    static void makeData(){
    
        RecordType rec = [Select Id from RecordType where SobjectType= 'Account' AND DeveloperName = 'Product_Partner'];
        RecordType oppRec = [Select Id from RecordType where SobjectType = 'Opportunity' AND DeveloperName = 'Merchant_Opportunity'];
        
        Account account = new Account();
        account.Name = 'Merchant';
        account.RecordTypeId = rec .Id;
        account.Phone = '+68 22 1234 1234';
        account.BillingStreet= '456 Fake St';
        account.BillingCity = 'ShlongDong';
        account.BillingState = 'Long Juan';
        account.BillingPostalCode = '123456';
        account.BillingCountry = 'China';
        insert account;
        
        Opportunity opp = new Opportunity();
        opp.AccountId = account.Id;
        opp.StageName = 'Closed Won';
        opp.RecordTypeId = oppRec.Id;
        opp.CloseDate = system.today();
        opp.Name = 'Opp-1-'+System.today() + '-'+ System.now().year();
        opp.Proposed_Go_Live_Date__c = System.today().addDays(10);
        opp.Physical_Region__c = 'Australia & NZ';
        opp.Physical_Country__c = 'Australia';
        opp.Travel_From__c = System.today().addDays(10);
        opp.Travel_To__c = System.today().addDays(15);
        opp.price__c = '2000';
        opp.Approx_Allocations__c = '2';
        insert opp;  //dummy contact inserted.
    }
    
    @isTest
    static void  checkForOpportunityStage(){
        String sName = 'Opp-1-'+System.today() + '-'+ System.now().year();
        Opportunity opp = [Select Id from Opportunity where Name =: sName limit 1];
        opp.StageName = 'Product Pipeline';
        update opp;
        
        Test.startTest();
        TAD_DealCreationViewOpportunity.checkForOpportunityStage(opp.Id);
        Test.stopTest();
    }
    
    @isTest
    static void  dealCreationFromOpportunity(){

        Account acctBussiness = [SELECT Id FROM Account WHERE Name = 'Merchant'];  // Bussiness account Inserted
        
        List<RecordType> RCTTadDeal = TADUtils.getRecordType(Label.TAD_RT_TAD_Deal);
        
        // Inserting Deal with Allocation By Sub Option
        Deal__c deal2 = TestDataFactory.createMerchantDeal(RCTTadDeal[0].Id , acctBussiness.Id );   // Deals created
        deal2.Allocation_by__c = 'Sub option';
        deal2.Name = '3456';
        deal2.deal_type__c = 'travel';
        deal2.deal_archetype__c = 'SANUZ';
        deal2.merchant_sharing_deadline__c = 60;
        deal2.Flight_Book_By__c = 2;
        insert deal2;
        
        String sName = 'Opp-1-'+System.today() + '-'+ System.now().year();
        Opportunity opp = [Select Id,Proposed_Go_Live_Date__c,Physical_Region__c,Physical_Country__c,Travel_From__c,
                          Travel_To__c,price__c,Approx_Allocations__c from Opportunity where Name =: sName limit 1];
        
        opp.StageName = 'Product Pipeline';
        update opp;
        
        Test.startTest();
        TAD_DealCreationViewOpportunity.getMultiPiklistValues();
        TAD_DealCreationViewOpportunity.getPiklistValues();
        TAD_DealCreationViewOpportunity.checkDeal(opp.Id);
        TAD_DealCreationViewOpportunity.dealCreationFromOpportunity(opp.Id,'Cruise',deal2.Id,'Dates/Domestic Flights');
        Test.stopTest();
    }
}