force-app/main/default/objects/Deal__c/Deal__c.object-meta.xml
<CustomObject>
    <label>Deal</label>
    <nameField>
        <label>Deal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/order_line_item__c/order_line_item__c.object-meta.xml
<CustomObject>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>OLI-{000000}</displayFormat>
        <label>Order Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/order_line_item__c/fields/FFStatus__c.field-meta.xml
<CustomField>
    <fullName>FFStatus__c</fullName>
    <label>FFStatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unprocessed</fullName>
                <default>true</default>
                <label>Unprocessed</label>
            </value>
            <value>
                <fullName>Processing - Initial Sale</fullName>
            </value>
            <value>
                <fullName>Processing - Post Sale</fullName>
            </value>
            <value>
                <fullName>Processing - Cancellation</fullName>
            </value>
            <value>
                <fullName>Processed - Initial Sale</fullName>
            </value>
            <value>
                <fullName>Processed - Post Sale</fullName>
            </value>
            <value>
                <fullName>Processed - Cancellation</fullName>
            </value>
            <value>
                <fullName>Processed - OLI Cancellation</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
                <isActive>false</isActive>
                <label>Processed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/order_line_item__c/fields/Journal_Records_Create__c.field-meta.xml
<CustomField>
    <fullName>Journal_Records_Create__c</fullName>
    <label>Journal Records Create</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial/Post Sale</fullName>
            </value>
            <value>
                <fullName>Cancellation Sale</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/order_line_item__c/fields/ordexp_TAD_Order__c.field-meta.xml
<CustomField>
    <fullName>ordexp_TAD_Order__c</fullName>
    <label>Order</label>
    <referenceTo>TAD_Order__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items_orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/TAD_Order__c.object-meta.xml
<CustomObject>
    <label>TAD Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TAD Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TAD_Order__c/fields/FF_status_Batch__c.field-meta.xml
<CustomField>
    <fullName>FF_status_Batch__c</fullName>
    <label>FF Pending Processing</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/FFStatus__c.field-meta.xml
<CustomField>
    <fullName>FFStatus__c</fullName>
    <label>FFStatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unprocessed</fullName>
                <default>true</default>
                <label>Unprocessed</label>
            </value>
            <value>
                <fullName>Processing - Initial Sale</fullName>
            </value>
            <value>
                <fullName>Processing - Post Sale</fullName>
            </value>
            <value>
                <fullName>Processing - Cancellation</fullName>
            </value>
            <value>
                <fullName>Processed - Initial Sale</fullName>
            </value>
            <value>
                <fullName>Processed - Post Sale</fullName>
            </value>
            <value>
                <fullName>Processed - Cancellation</fullName>
            </value>
            <value>
                <fullName>Pending Processing</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
                <isActive>false</isActive>
                <label>Processed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_deal__c.field-meta.xml
<CustomField>
    <fullName>ordexp_deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>TAD_Orders_Deal</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_master_status__c.field-meta.xml
<CustomField>
    <fullName>ordexp_master_status__c</fullName>
    <label>Master status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
                <default>true</default>
                <label>On Hold</label>
            </value>
            <value>
                <fullName>Temporary Hold</fullName>
            </value>
            <value>
                <fullName>Secured</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Travelled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>In Progress-Cruise only</fullName>
                <isActive>false</isActive>
                <label>In Progress-Cruise only</label>
            </value>
            <value>
                <fullName>In Progress-Flight only</fullName>
                <isActive>false</isActive>
                <label>In Progress-Flight only</label>
            </value>
            <value>
                <fullName>In Progress-Flights + Cruise</fullName>
                <isActive>false</isActive>
                <label>In Progress-Flights + Cruise</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TAD_Order__c/recordTypes/TAD.recordType-meta.xml
<RecordType>
    <fullName>TAD</fullName>
    <active>true</active>
    <label>TAD</label>
</RecordType>

force-app/main/default/classes/JournalCancellationProcessBatch.cls
global class JournalCancellationProcessBatch implements Database.Batchable<sObject> {
    
    global Database.QueryLocator start(Database.BatchableContext bc){
        if(test.isRunningTest()){
           return Database.getQueryLocator([SELECT Id, Name,ordexp_master_status__c ,FF_status_Batch__c,FFStatus__c FROM TAD_order__c WHERE FF_status_Batch__c != null AND ordexp_deal__r.name='1234' Limit 1 ]);
        }else{
            return Database.getQueryLocator([SELECT Id, Name,ordexp_master_status__c ,FF_status_Batch__c,FFStatus__c FROM TAD_order__c WHERE FF_status_Batch__c != null  ]);
        }
       
    }
    
    global void execute(Database.BatchableContext bc,List<TAD_order__c> scope){
        system.debug('Tad-Order-->scope'+scope);
        Map<String,TAD_Order__c> initialSaleMap = new Map<String,TAD_Order__c>();
        Map<String,TAD_Order__c> postSaleMap = new Map<String,TAD_Order__c>();
        Map<String,TAD_Order__c> cancellationMap = new Map<String,TAD_Order__c>();
        Map<String, Object> inputs = new Map<String, Object>();
        String str ;
        
        List<String> FFstatus = new List<String>();
        Set<String> setofFFstatus = new Set<String>();
        
        
        TAD_Order__c ord = scope[0];
        
        str = ord.FF_status_Batch__c;
        FFstatus = str.split(';');
        setofFFstatus.addAll(FFstatus );
        Boolean inCancellation = false;  
        
        // Scenerios for Cancellation
        
        if(setofFFstatus.contains('Processing - Cancellation') && !(setofFFstatus.contains('Processing - Initial Sale')) && !(setofFFstatus.contains('Processing - Post Sale'))){
            if(ord.FFStatus__c != 'Processing - Cancellation'){
                ord.FFStatus__c = 'Processing - Cancellation';
                System.debug('Order Updated Cancellation');
                update ord;
            }
            
            if(ord.FFStatus__c == 'Processing - Cancellation'){
                System.debug('Order Updated Cancellation 1');
                inCancellation = true;
                Flow.Interview flow = new Flow.Interview.Sales_Cancellation_AutoLaunched_Flow(new map<String,Object> {'tadOrderId' => ord.Id});     
                flow.start();
                
                if(ord.ordexp_master_status__c!='Cancelled'){
                    
                    // Oli Cancellation flow
                    list<order_line_item__c> oliRec1 = [select id  from order_line_item__c where ordexp_tad_order__c =: ord.id ];
                    
                    if(!oliRec1.isempty()){
                        list<order_line_item__c> oliToUpdate = new list<order_line_item__c>();
                        for(order_line_item__c oldata :oliRec1){
                            order_line_item__c ol = new order_line_item__c();
                            ol.Journal_Records_Create__c='Cancellation Sale';
                            ol.Id=oldata.id;
                            oliToUpdate.add(ol);
                        }
                        update oliToUpdate;
                    }
                    // Oli Cancellation flow ends
                    Flow.Interview flow1 = new Flow.Interview.Sales_Journal_Creation_Post_Cancellation(new map<String,Object> {'TADOrderId' => ord.Id});     
                    flow1.start();
                }
            }  
            
            tad_order__c tad = new tad_order__c();
            tad.id=ord.id;
            tad.FF_status_Batch__c = null;
            if(inCancellation==true){
                tad.FFStatus__c = 'Processed - Cancellation';  
            }
            update tad;
        }
        
    }
    
    global void finish(Database.BatchableContext BC) {
        
    }
}