force-app/main/default/objects/Deal__c/Deal__c.object-meta.xml
<CustomObject>
    <label>Deal</label>
    <nameField>
        <label>Deal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal__c/fields/Cloned_From__c.field-meta.xml
<CustomField>
    <fullName>Cloned_From__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cloned From</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Deal</relationshipLabel>
    <relationshipName>Deal</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Hero</fullName>
            </value>
            <value>
                <fullName>Published(NRMA)</fullName>
            </value>
            <value>
                <fullName>Published(Staging)</fullName>
            </value>
            <value>
                <fullName>Hero(Staging)</fullName>
            </value>
            <value>
                <fullName>Hidden</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Saved_Deals__c/Saved_Deals__c.object-meta.xml
<CustomObject>
    <label>Sales Lead</label>
    <nameField>
        <label>Sales Lead Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Leads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Saved_Deals__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Saved_Deals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Saved_Deals__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipName>Saved_Deals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Saved_Deals__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Closed Converted</fullName>
            </value>
            <value>
                <fullName>Closed Not Converted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Saved_Deals__c/fields/TAD_Order__c.field-meta.xml
<CustomField>
    <fullName>TAD_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TAD Order</label>
    <referenceTo>TAD_Order__c</referenceTo>
    <relationshipName>Saved_Deals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/TAD_Order__c.object-meta.xml
<CustomObject>
    <label>TAD Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TAD Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_master_status__c.field-meta.xml
<CustomField>
    <fullName>ordexp_master_status__c</fullName>
    <label>Master status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
                <default>true</default>
                <label>On Hold</label>
            </value>
            <value>
                <fullName>Temporary Hold</fullName>
            </value>
            <value>
                <fullName>Secured</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Travelled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>In Progress-Cruise only</fullName>
                <isActive>false</isActive>
                <label>In Progress-Cruise only</label>
            </value>
            <value>
                <fullName>In Progress-Flight only</fullName>
                <isActive>false</isActive>
                <label>In Progress-Flight only</label>
            </value>
            <value>
                <fullName>In Progress-Flights + Cruise</fullName>
                <isActive>false</isActive>
                <label>In Progress-Flights + Cruise</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_total_price__c.field-meta.xml
<CustomField>
    <fullName>ordexp_total_price__c</fullName>
    <formula>ordexp_gross_amount_final__c +  TAD_Surcharge_Amount__c</formula>
    <label>Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/case_CustomerServiceAgent.cls
public class case_CustomerServiceAgent {
    
    public class mainWrapper{
        @AuraEnabled public string dealName {get;set;}
        @AuraEnabled public string tadOrderName {get;set;}
         @AuraEnabled public string tadOrderId {get;set;}
        @AuraEnabled public string status {get;set;}
        @AuraEnabled public string savedDealName {get;set;}
        @AuraEnabled public Decimal totalPrice {get;set;}
        @AuraEnabled public Date createdDate {get;set;}
        
        
    }
    
    
    @AuraEnabled 
    public static List<mainWrapper> fetchResult(String recordId){
       
        
        List<Case>  CaseList = [Select id,AccountId from Case where id =: recordId];
        system.debug('AccountId-----'+CaseList[0].AccountId);   
                      system.debug('CaseList-----'+CaseList[0]);   

        List<Saved_Deals__c>  saveDealList = [Select id,Name,Account__c,Deal__r.Name,Status__c,TAD_Order__r.ordexp_master_status__c,TAD_Order__r.Name,TAD_Order__r.ordexp_total_price__c, CreatedDate from Saved_Deals__c where Account__c =: CaseList[0].AccountId];
                List<mainWrapper>mainWrapList =new List<mainWrapper>();
        for (Saved_Deals__c dl :saveDealList){
              system.debug('tadOrder-----'+dl.TAD_Order__c);  
         system.debug('Price-----'+dl.TAD_Order__r.ordexp_total_price__c);  
         system.debug('status-----'+dl.TAD_Order__r.ordexp_master_status__c);   
             mainWrapper mainWrap = new mainWrapper();
            mainWrap.dealName = dl.Deal__r.Name;
            mainWrap.createdDate = dl.CreatedDate.Date();
           mainWrap.savedDealName=dl.Name;
            if(dl.TAD_Order__c != null ){
                mainWrap.tadOrderId = dl.TAD_Order__c;
                 mainWrap.tadOrderName = dl.TAD_Order__r.Name;
                  mainWrap.status = dl.TAD_Order__r.ordexp_master_status__c;
                 mainWrap.totalPrice = dl.TAD_Order__r.ordexp_total_price__c;
            }else{
                  mainWrap.status = dl.Status__c;
                 mainWrap.totalPrice = 0.00;
                 mainWrap.tadOrderName = dl.TAD_Order__r.Name;
            }
          mainWrapList.add(mainWrap);
           
        }
        
   //     system.debug('MainWrap--------'+mainWrap);
        return mainWrapList;
        
        
    }
    
    
    
    
    
    
}