force-app/main/default/objects/Deal__c/Deal__c.object-meta.xml
<CustomObject>
    <label>Deal</label>
    <nameField>
        <label>Deal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal__c/fields/Cloned_From__c.field-meta.xml
<CustomField>
    <fullName>Cloned_From__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cloned From</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Deal</relationshipLabel>
    <relationshipName>Deal</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal__c/fields/Deal_ID_Title__c.field-meta.xml
<CustomField>
    <fullName>Deal_ID_Title__c</fullName>
    <formula>IF( ISBLANK(title__c) , 
Name&amp;&quot;-&quot;&amp;title_nz__c , 
Name&amp;&quot;-&quot;&amp;title__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Deal ID &amp; Title</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal__c/fields/Merchant__c.field-meta.xml
<CustomField>
    <fullName>Merchant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Merchant</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Product Partner, General Expense Vendors</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Deal</relationshipLabel>
    <relationshipName>Deal</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal__c/fields/PDF_Image__c.field-meta.xml
<CustomField>
    <fullName>PDF_Image__c</fullName>
    <label>PDF Image</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal__c/fields/title__c.field-meta.xml
<CustomField>
    <fullName>title__c</fullName>
    <label>title</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal__c/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <label>URL</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/media__c/media__c.object-meta.xml
<CustomObject>
    <label>media</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>media</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/media__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>media</relationshipLabel>
    <relationshipName>media</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Saved_Deals__c/Saved_Deals__c.object-meta.xml
<CustomObject>
    <label>Sales Lead</label>
    <nameField>
        <label>Sales Lead Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Leads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Saved_Deals__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Saved_Deals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Saved_Deals__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipName>Saved_Deals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/MobileAppGetSavedDeals.cls
@RestResource(urlmapping='/settingGetSavedDeals/*')
global class MobileAppGetSavedDeals {
    
    global class mainWrapper{
        
        global String accountSFId{get;set;}
        
        //New attributes as per Elmin's request, also check an 
        global string appSessionCode {get;set;}
    }
    global class result{
       
        global list<dealData> deal{get;set;}
        global String errorMessage{get;set;}
        global Boolean isSuccess{get;set;}
        
    }
    
    global class dealData
    {
         global String DealSFid{get;set;}
        global String DealName{get;set;}
        global String DealIDTitle{get;set;}
        global String ImageUrl{get;set;}
        global String Title{get;set;}
        
    }
    
    
    @Httppost
    global Static result createSavedDeals(mainWrapper AccountData)
    {
        result res = new result ();
        Boolean proceed = false;
        List<Account> actList = [Select id, firstname, lastname, app_session__c from Account 
                                 where Id =:AccountData.accountSFId Limit 1];
        
        if(!actList.isEmpty() && (actList[0].app_session__c == AccountData.appSessionCode)){
            proceed = true;
        }
        
        if(proceed==true){
           list<Saved_Deals__c> svedDealsList = [Select id,Account__c,Deal__c,Deal__r.title__c,Deal__r.Name,Deal__r.PDF_Image__c,Deal__r.Deal_ID_Title__c from Saved_Deals__c where Account__c=:AccountData.accountSFId ];
        	system.debug('svedDealsList '+svedDealsList);
        
        	if(svedDealsList.size()>0){
            list<dealData> dealList = new list<dealData>();
                
                list<string> d = new list<string>();
            for(Saved_Deals__c sdo:svedDealsList )
            {
                      d.add(sdo.Deal__c);
            }  
              list<media__c> mLIst =  [select Id,url__c ,Deal__c from media__c where Deal__c=:d];
          map<string,string> mapmedia= new  map<string,string>();
                if(mLIst.size()>0)
                {
                for(media__c m:mLIst)
                {
                    if(!mapmedia.containsKey(m.Deal__c))
                    {
                        mapmedia.put(m.Deal__c,m.url__c);
                    }
                }
                }
            for(Saved_Deals__c sdo:svedDealsList )
            {
                dealData resobj = new dealData();
                resobj.DealSFid =  sdo.Deal__c;    
                resobj.DealName =  sdo.Deal__r.Name;        
                resobj.DealIDTitle =  sdo.Deal__r.Deal_ID_Title__c; 
                resobj.ImageUrl =  mapmedia.get(sdo.Deal__c);
                resobj.Title= sdo.Deal__r.title__c;
                dealList.add(resobj);
            }
                if(!dealList.isEmpty()){
                    res.deal = dealList;
            		res.isSuccess = true;  
                }
        	}else{
            	res.errorMessage =  'You have no Saved Deals';
                res.isSuccess = true;
                } 
        }
        else{
            res.errorMessage =  'Please try to Login again!';
            res.isSuccess = false; 
        }
        return res;
    }
    
}