force-app/main/default/objects/Deal__c/Deal__c.object-meta.xml
<CustomObject>
    <label>Deal</label>
    <nameField>
        <label>Deal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/departures_dates__c/departures_dates__c.object-meta.xml
<CustomObject>
    <label>departures dates</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>departures dates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/departures_dates__c/fields/Approved_to_Run_Under_Mins__c.field-meta.xml
<CustomField>
    <fullName>Approved_to_Run_Under_Mins__c</fullName>
    <defaultValue>false</defaultValue>
    <description>For Flight Ticketing team use - can be checked as true if approval received by BDM/Merchant to go ahead with ticketing if mins not yet met</description>
    <inlineHelpText>Check this as true if approval received to run under min numbers</inlineHelpText>
    <label>Approved to Run Under Mins?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/BC_Due__c.field-meta.xml
<CustomField>
    <fullName>BC_Due__c</fullName>
    <formula>IF(date__c&gt; DATE(2100,01,01) , date__c, IF (
(ISBLANK( BC_Due_Extension__c )),

IF (
(ISBLANK( Deal_for_Reporting__r.merchant_sharing_deadline_date__c )),
(date__c - Deal_for_Reporting__r.merchant_sharing_deadline__c ),
Deal_for_Reporting__r.merchant_sharing_deadline_date__c
),BC_Due_Extension__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Number of days prior to departure that merchant will receive booking confirmation. If multi-merchant deal, please use the most restrictive deadline e.g 120 days instead of 90.</inlineHelpText>
    <label>BC Due</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/date__c.field-meta.xml
<CustomField>
    <fullName>date__c</fullName>
    <label>date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/Deal_for_Reporting__c.field-meta.xml
<CustomField>
    <fullName>Deal_for_Reporting__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Deal for Reporting</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>departures dates (Deal for Reporting)</relationshipLabel>
    <relationshipName>departures_dates1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/finalise_date__c.field-meta.xml
<CustomField>
    <fullName>finalise_date__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Finalise Date</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/min_numbers_met__c.field-meta.xml
<CustomField>
    <fullName>min_numbers_met__c</fullName>
    <defaultValue>false</defaultValue>
    <description>For Flight Ticketing team use - checks as true if number of pax confirmed &gt;= min numbers</description>
    <inlineHelpText>Process Builder - Auto checks as true if number of pax confirmed greater or equal to min. numbers</inlineHelpText>
    <label>Min Numbers Met?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/online_status__c.field-meta.xml
<CustomField>
    <fullName>online_status__c</fullName>
    <label>Online Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Offline - Auto</fullName>
            </value>
            <value>
                <fullName>Offline - Manual</fullName>
            </value>
            <value>
                <fullName>Hidden</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MP_departureDateFinalizeAutomatically.cls
global class MP_departureDateFinalizeAutomatically implements Database.Batchable < sobject >,Database.Stateful {
    global set<Id> listofDeptIds = new set<Id>();
       global set<Id> DeptIdSet = new set<Id>();
      
       global Database.QueryLocator start(Database.BatchableContext bc) {
           String Query;
           Date dt = system.today();
           String NotificationLabel = System.Label.MP_Batch_Notification;
   
           
           List<departures_dates__c> deptlist = [select Id,Name,Deal_for_Reporting__r.Name from departures_dates__c where BC_Due__c =:dt AND  date__c >= TODAY AND  (Approved_to_Run_Under_Mins__c = True OR min_numbers_met__c = True) AND (online_status__c = 'Offline - Auto' OR online_status__c = 'Offline - Manual')];
           system.debug('deptlist112-8-->'+deptlist);
           
           for(departures_dates__c d:deptlist){
               
               listofDeptIds.add(d.Id);
               
               
           }
            system.debug('listofDeptIds--->'+listofDeptIds);
           
           if(NotificationLabel == 'true'){
               Query = 'Select Id,Name,BC_Due__c,finalise_date__c from departures_dates__c WHERE Id =: listofDeptIds';
           }
           else{
               Query = 'Select Id,Name,BC_Due__c,finalise_date__c from departures_dates__c WHERE Id =: NotificationLabel';
               
           }
           
           return Database.getquerylocator(Query);
       }
       
       global void execute(Database.BatchableContext bc, List < departures_dates__c > deptDateList) {
           List<departures_dates__c> updateDeptList = New List<departures_dates__c>();
           system.debug('deptDateList--');
           for(departures_dates__c dept : deptDateList){
               system.debug('dept--->'+dept);
               if(dept.finalise_date__c == false){
               dept.finalise_date__c = True;
               }
               DeptIdSet.add(dept.Id);
               system.debug('DeptIdSet--33->'+DeptIdSet);
               updateDeptList.add(dept);
           }
           system.debug('DeptIdSet--35->'+DeptIdSet);
           update updateDeptList;
   
       }
       
       global void finish(database.BatchableContext bc) {
           MP_BCAvailableNotification.publishedDealEmailToMerchant(listofDeptIds);
       }
        
       
   }