force-app/main/default/objects/Deal__c/Deal__c.object-meta.xml
<CustomObject>
    <label>Deal</label>
    <nameField>
        <label>Deal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/departure_cities__c/departure_cities__c.object-meta.xml
<CustomObject>
    <label>departure cities</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>departure cities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/departure_cities__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>departure cities</relationshipLabel>
    <relationshipName>departure_cities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/StopOver_Departure_Cities__c/StopOver_Departure_Cities__c.object-meta.xml
<CustomObject>
    <label>StopOver Departure City</label>
    <nameField>
        <displayFormat>Dept-{0000}</displayFormat>
        <label>StopOver Departure Cities Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>StopOver Departure Cities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/StopOver_Departure_Cities__c/fields/ordexp_Active__c.field-meta.xml
<CustomField>
    <fullName>ordexp_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/StopOver_Departure_Cities__c/fields/ordexp_departure_cities__c.field-meta.xml
<CustomField>
    <fullName>ordexp_departure_cities__c</fullName>
    <label>departure cities</label>
    <referenceTo>departure_cities__c</referenceTo>
    <relationshipLabel>StopOver Departure Cities</relationshipLabel>
    <relationshipName>StopOver_Departure_Cities</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/StopOver_Departure_Cities__c/fields/ordexp_sub_stopover__c.field-meta.xml
<CustomField>
    <fullName>ordexp_sub_stopover__c</fullName>
    <label>sub stopover</label>
    <referenceTo>sub_stopover__c</referenceTo>
    <relationshipLabel>StopOver Departure Cities</relationshipLabel>
    <relationshipName>StopOver_Departure_Cities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/sub_stopover__c/sub_stopover__c.object-meta.xml
<CustomObject>
    <label>sub stopover</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>sub stopover</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sub_stopover__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Used to make sub Stop active or not on website</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/sub_stopover__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>sub stopover</relationshipLabel>
    <relationshipName>sub_stopover</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TAD_SelectCitiesForSubStopOver.cls
public class TAD_SelectCitiesForSubStopOver {

    public class selectActiveCityWrapper
    {
        @auraEnabled
        public Boolean active  {get;set;}
         @auraEnabled
        public String CityName {get;set;}
         @auraEnabled
        public String recordId {get;set;}
    }
    
     @auraEnabled
    public static List<selectActiveCityWrapper> fetchdepartureCity(Id stopOverId){
        List<selectActiveCityWrapper> wrapList = new List<selectActiveCityWrapper>();
        sub_stopover__c stopOver = [Select Id , Deal__c from sub_stopover__c where Id=: stopOverId];
        Set<Id> deptCityIds = new Set<Id>();
        if(stopOver != null && stopOver.Deal__c != null){
            for(StopOver_Departure_Cities__c stopCity : [select Name, ordexp_departure_cities__c from StopOver_Departure_Cities__c where ordexp_sub_stopover__c =: stopOver.Id ]){
                deptCityIds.add(stopCity.ordexp_departure_cities__c);
            }
            
            
            for(departure_cities__c deptCity: [Select Id, Name, Active__c from departure_cities__c where Active__c = true AND 	Deal__c =: stopOver.Deal__c]){
                if(!deptCityIds.contains(deptCity.Id)){
                    selectActiveCityWrapper wrap = new selectActiveCityWrapper();
                    wrap.active = deptCity.Active__c;
                    wrap.CityName = deptCity.Name;
                    wrap.recordId = deptCity.Id;
                    wrapList.add(wrap);
                }
                
            }
            if(!wrapList.isEmpty()){
                return wrapList;
            }
            
        }
            return null;
    }
    
     @auraEnabled
    public static void saveDepartureCityWithStopOver(Id stopOverId, List<Id> deptCityList){
        system.debug('stopOverId '+stopOverId+' & deptCityList'+deptCityList);
      List<StopOver_Departure_Cities__c> listToupdate = new List<StopOver_Departure_Cities__c>();
        for(Id deptCity : deptCityList){
            StopOver_Departure_Cities__c juncObj = new StopOver_Departure_Cities__c();
            juncObj.ordexp_departure_cities__c = deptCity;
            juncObj.ordexp_sub_stopover__c = stopoverId;
            juncObj.ordexp_Active__c = true;
            listToupdate.add(juncObj);
            
        }
        system.debug('listToupdate '+listToupdate);
        if(!listToupdate.isEmpty()){
            insert listToupdate;
        }
    }
}