force-app/main/default/objects/Deal__c/Deal__c.object-meta.xml
<CustomObject>
    <label>Deal</label>
    <nameField>
        <label>Deal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Hero</fullName>
            </value>
            <value>
                <fullName>Published(NRMA)</fullName>
            </value>
            <value>
                <fullName>Published(Staging)</fullName>
            </value>
            <value>
                <fullName>Hero(Staging)</fullName>
            </value>
            <value>
                <fullName>Hidden</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Saved_Deals__c/Saved_Deals__c.object-meta.xml
<CustomObject>
    <label>Sales Lead</label>
    <nameField>
        <label>Sales Lead Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Leads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Saved_Deals__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Saved_Deals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Saved_Deals__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipName>Saved_Deals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Saved_Deals__c/fields/Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source__c</fullName>
    <label>Lead Source</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Advertisement</fullName>
            </value>
            <value>
                <fullName>Employee Referral</fullName>
            </value>
            <value>
                <fullName>External Referral</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Public Relations</fullName>
            </value>
            <value>
                <fullName>Seminar - Internal</fullName>
            </value>
            <value>
                <fullName>Seminar - Partner</fullName>
            </value>
            <value>
                <fullName>Trade Show</fullName>
            </value>
            <value>
                <fullName>Web</fullName>
            </value>
            <value>
                <fullName>Word of mouth</fullName>
            </value>
            <value>
                <fullName>Leadpages</fullName>
            </value>
            <value>
                <fullName>Facebook</fullName>
            </value>
            <value>
                <fullName>Instagram</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
                <default>true</default>
                <label>Other</label>
            </value>
            <value>
                <fullName>Newspaper</fullName>
            </value>
            <value>
                <fullName>Radio</fullName>
            </value>
            <value>
                <fullName>Friends/Family</fullName>
            </value>
            <value>
                <fullName>Socials</fullName>
            </value>
            <value>
                <fullName>App</fullName>
            </value>
            <value>
                <fullName>TV</fullName>
            </value>
            <value>
                <fullName>Billboard</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Sporting Partner</fullName>
            </value>
            <value>
                <fullName>Social Media</fullName>
            </value>
            <value>
                <fullName>Google</fullName>
            </value>
            <value>
                <fullName>Existing Customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Saved_Deals__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Closed Converted</fullName>
            </value>
            <value>
                <fullName>Closed Not Converted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ScheduleCallbackTask.cls
public class ScheduleCallbackTask {

  
     public class mainWrapper{
         @AuraEnabled public string id {get;set;}
        @AuraEnabled public string dealName {get;set;}
        @AuraEnabled public string reminderSet {get;set;}        
        @AuraEnabled public string status {get;set;}
        @AuraEnabled public string savedDealName {get;set;}
        @AuraEnabled public Boolean isReminder {get;set;}
        @AuraEnabled public String Subject {get;set;}
        @AuraEnabled public String Time1 {get;set;}
        
        
    }
    
    
    @AuraEnabled
    public static List<mainWrapper> createTask(Id recId, String selectedDay, String selectedTime, Id dealid){
      
        LiveChatTranscript chatTr  = [Select id,CaseId from LiveChatTranscript where id=:recId];
       
        List<mainWrapper>mainWrapList =new List<mainWrapper>();        
      
        Case caseobj = [Select id ,AccountId,OwnerId,Saved_Deal__r.Id from Case where id=:chatTr.CaseId];      
        String phoneRecordTypeID = Schema.getGlobalDescribe().get('Saved_Deals__c').getDescribe().getRecordTypeInfosByName().get('Phone Lead').getRecordTypeId();
            
        system.debug('caseobj--'+caseobj);
        String datefinal ;
        Date actDate;        
        if(selectedDay == 'Today'){
            datefinal = String.valueOf(Date.today()).removeEnd(' 00:00:00'); 
            actDate =Date.today();
        }else{
            datefinal = String.valueOf(Date.today().addDays(+1)).removeEnd(' 00:00:00'); 
            actDate =Date.today().addDays(+1);
        }
        string[] splitted = datefinal.split('-');
        String NewDate = splitted[2]+'/'+splitted[1]+'/'+splitted[0]+' '+selectedTime;   
        DateTime testDate = DateTime.parse(NewDate);
        system.debug('saved deal41--'+caseobj.Saved_Deal__r.Id);
          Saved_Deals__c sv=new Saved_Deals__c();
        Id savedId;
        if(caseobj.Saved_Deal__r.Id == null){
        system.debug('saved deal41-inner-'+caseobj.Saved_Deal__r.Id);
        sv.Deal__c= dealid;
        sv.Lead_Source__c ='Web';
        sv.Account__c=caseobj.AccountId;
        sv.Status__c ='In Progress';
        sv.RecordTypeId =phoneRecordTypeID;        
        insert sv;
       
        }

        Task tk=new Task();
        tk.Subject = 'Follow up call';
        tk.OwnerId = caseobj.OwnerId;
        tk.Status = 'In Progress';
        tk.IsReminderSet = true;
        tk.ActivityDate = actDate;
        tk.ReminderDateTime = testDate;
        
        if(sv.Id != null){
            tk.WhatId = sv.Id;
             savedId =sv.id;
            system.debug('savedDeal Id'+sv.Id);
             caseobj.Saved_Deal__c = sv.Id;
            system.debug('updated Case--'+tk);
            update caseobj;
        }else{
           tk.WhatId = caseobj.Saved_Deal__r.Id; 
            savedId =caseobj.Saved_Deal__r.Id;
             system.debug('savedDeal Id'+caseobj.Saved_Deal__r.Id);
        }      
       
        insert tk;
        
      
        system.debug('tk.id'+tk.id);
        if(tk.id != null){
            system.debug('tk.id===inner'+tk.id);
            List<Task> Tasklist = [Select id,Subject,OwnerId,Status,IsReminderSet,ReminderDateTime,WhatId from Task where WhatId=:savedId];
           system.debug('TaskObj--'+Tasklist);
            for(Task tkobj : Tasklist ){
                 mainWrapper mainWrap = new mainWrapper();
                 mainWrap.id= tkobj.Id;
                 String dateTimeStr = tkobj.ReminderDateTime.format('dd/MM/yyyy hh:mm:ss a');
                 mainWrap.reminderSet =dateTimeStr;
                 mainWrap.isReminder = tkobj.IsReminderSet;
                 mainWrap.status =tkobj.Status;
                 mainWrap.Subject=tkobj.Subject;
                 mainWrap.savedDealName =tkobj.WhatId;
                 mainWrapList.add(mainWrap);  
                system.debug('TaskObj--'+tkobj);
            }
            system.debug('mainWrapList--'+mainWrapList);
           

        }
       //  
      return mainWrapList;    
    }
    
      @AuraEnabled
    public static List<mainWrapper> getData(Id recId){
        system.debug('RecId---'+recId);
         LiveChatTranscript chatTr  = [Select id,CaseId from LiveChatTranscript where id=:recId];
      
        List<mainWrapper>mainWrapList =new List<mainWrapper>();      
         Case caseobj = [Select id ,AccountId,OwnerId,Saved_Deal__r.Id from Case where id=:chatTr.CaseId]; 
       
        if(caseobj.Id != null){
             List<Task> Tasklist = [Select id,Subject,OwnerId,Status,IsReminderSet,ReminderDateTime,WhatId from Task where WhatId=:caseobj.Saved_Deal__r.Id ];
           system.debug('TaskObj--'+Tasklist);
           
            if(!Tasklist.isEmpty()){
             
                for(Task tkobj : Tasklist ){
                 mainWrapper mainWrap = new mainWrapper();
                 mainWrap.id= tkobj.Id;
                 //  system.debug('ReminderDateTime--'+tkobj.ReminderDateTime);                
                 String dateTimeStr = tkobj.ReminderDateTime.format('dd/MM/yyyy hh:mm:ss a');
                // system.debug('dateTimeStr--'+dateTimeStr1);
                 mainWrap.reminderSet =dateTimeStr;
                 mainWrap.isReminder = tkobj.IsReminderSet;
                 mainWrap.Subject=tkobj.Subject;
                 mainWrap.status =tkobj.Status;
                 mainWrap.savedDealName =tkobj.WhatId;
                 mainWrapList.add(mainWrap);  
                    system.debug('mainWrap--'+mainWrap);    
        }  
            }
            
              system.debug('mainWrapList--'+mainWrapList);          
       
        }
         return mainWrapList;    
    }
}