force-app/main/default/objects/Deal__c/Deal__c.object-meta.xml
<CustomObject>
    <label>Deal</label>
    <nameField>
        <label>Deal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal__c/fields/Cloned_From__c.field-meta.xml
<CustomField>
    <fullName>Cloned_From__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cloned From</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Deal</relationshipLabel>
    <relationshipName>Deal</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Hero</fullName>
            </value>
            <value>
                <fullName>Published(NRMA)</fullName>
            </value>
            <value>
                <fullName>Published(Staging)</fullName>
            </value>
            <value>
                <fullName>Hero(Staging)</fullName>
            </value>
            <value>
                <fullName>Hidden</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice_Line_Mapping__c/Invoice_Line_Mapping__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Mapping</label>
    <nameField>
        <displayFormat>ILM-{000000}</displayFormat>
        <label>Invoice Line Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Mapping</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Line_Mapping__c/fields/Order_Line__c.field-meta.xml
<CustomField>
    <fullName>Order_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Line</label>
    <referenceTo>order_line_POE__c</referenceTo>
    <relationshipLabel>Invoice Line Mapping</relationshipLabel>
    <relationshipName>Invoice_Line_Mapping</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Mapping__c/fields/Payable_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Payable_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payable Invoice</label>
    <referenceTo>c2g__codaPurchaseInvoice__c</referenceTo>
    <relationshipLabel>Invoice Line Mapping</relationshipLabel>
    <relationshipName>Invoice_Line_Mapping</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Mapping__c/fields/Payable_Invoice_Expense_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Payable_Invoice_Expense_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payable Invoice Expense Line Item</label>
    <referenceTo>c2g__codaPurchaseInvoiceExpenseLineItem__c</referenceTo>
    <relationshipLabel>Invoice Line Mapping</relationshipLabel>
    <relationshipName>Invoice_Line_Mapping</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/order_line__c/order_line__c.object-meta.xml
<CustomObject>
    <label>Order Line (Old)</label>
    <nameField>
        <displayFormat>OL-{00000000}</displayFormat>
        <label>Order Lines Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Lines (Old)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/order_line__c/fields/Departure_Date__c.field-meta.xml
<CustomField>
    <fullName>Departure_Date__c</fullName>
    <formula>order__r.departure_date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Departure Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/order_line_POE__c/order_line_POE__c.object-meta.xml
<CustomObject>
    <label>Order Line</label>
    <nameField>
        <displayFormat>OL-{00000000}</displayFormat>
        <label>Order Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/order_line_POE__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Order Lines</relationshipLabel>
    <relationshipName>Order_Lines_POE</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/order_line_POE__c/fields/Departure_date__c.field-meta.xml
<CustomField>
    <fullName>Departure_date__c</fullName>
    <formula>TAD_Order__r.ordexp_departure_date__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Departure date</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/order_line_POE__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Updated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/order_line_POE__c/fields/TAD_Order__c.field-meta.xml
<CustomField>
    <fullName>TAD_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TAD Order</label>
    <referenceTo>TAD_Order__c</referenceTo>
    <relationshipLabel>Order Lines</relationshipLabel>
    <relationshipName>Order_Lines_POE</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/order_line_POE__c/fields/Unique_Key_for_DealDD_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Unique_Key_for_DealDD_Mapping__c</fullName>
    <formula>IF( NOT( ISBLANK(  Deal__c ) ) &amp;&amp; NOT( ISBLANK(   Order_Line_Item__r.ordexp_departure_date__c ) ) , mp_merchant__r.Name + &quot;;&quot;+ Deal__r.Name +&quot;;&quot;+ Order_Line_Item__r.ordexp_departure_date__r.Name , &quot;Deal &amp; Departure Date Is  Empty&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unique Key for DealDD Mapping</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/order_line_POE__c/fields/Unique_Key_for_Order_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Unique_Key_for_Order_Mapping__c</fullName>
    <formula>IF( NOT( ISBLANK( TAD_Order__c ) ) , mp_merchant__r.Name + &quot;;&quot;+ TAD_Order__r.Name , &quot;TAD Order Is  Empty&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unique Key for Order Mapping</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/TAD_Order__c.object-meta.xml
<CustomObject>
    <label>TAD Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TAD Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TAD_Order__c/fields/Order_Line__c.field-meta.xml
<CustomField>
    <fullName>Order_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Line</label>
    <referenceTo>order_line__c</referenceTo>
    <relationshipLabel>TAD Orders</relationshipLabel>
    <relationshipName>TAD_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/payableInvoiceTriggerHandler.cls
public class payableInvoiceTriggerHandler {
	@future
    public static void createInvoiceLineMapping(list<string> pinList){
        
        list<string> pinId = new list<string>();
        list<string> expId = new list<string>();
        list<string> olId = new list<string>();
        list<string> uniqKey = new list<string>();
        List<Invoice_Line_Mapping__c> ILMtoInsert = new List<Invoice_Line_Mapping__c>();
        
        /*for(c2g__codaPurchaseInvoice__c pin:pinList){
            pinId.add(pin.id);
        }*/
        
        list<c2g__codaPurchaseInvoiceExpenseLineItem__c> expList = [SELECT Id,Unique_Key_for_Mapping__c, Name,CurrencyIsoCode, Deal__c,Deal__r.name, Departure_Date__c, Departure_Date__r.name, TAD_Order__c,TAD_Order__r.name, c2g__PurchaseInvoice__c, c2g__PurchaseInvoice__r.Deal__c, c2g__PurchaseInvoice__r.Deal__r.name, c2g__PurchaseInvoice__r.TAD_Order__r.name FROM c2g__codaPurchaseInvoiceExpenseLineItem__c where c2g__PurchaseInvoice__c In :pinList];
        system.debug('expList '+expList);
        for(c2g__codaPurchaseInvoiceExpenseLineItem__c exp:expList){
			expId.add(exp.id);
			uniqKey.add(exp.Unique_Key_for_Mapping__c);       
        }
        system.debug('uniqKey '+uniqKey);
        list<order_line_POE__c> olList = [Select id, name, tad_order__c, tad_order__r.name, Unique_Key_for_Order_Mapping__c, Unique_Key_for_DealDD_Mapping__c, status__c from order_line_POE__c where  (Unique_Key_for_DealDD_Mapping__c IN: uniqKey  OR Unique_Key_for_Order_Mapping__c IN: uniqKey) AND Status__c!='Cancelled'];
        system.debug('uniqKey '+olList);
        for(order_line_POE__c ol2:olList){
            olId.add(ol2.id);
        }
        if(!olList.isEmpty()){
            for(c2g__codaPurchaseInvoiceExpenseLineItem__c exp1:expList){
                for(order_line_POE__c ol:olList){
                    if((ol.Unique_Key_for_DealDD_Mapping__c==exp1.Unique_Key_for_Mapping__c || ol.Unique_Key_for_Order_Mapping__c== exp1.Unique_Key_for_Mapping__c)){
                        Invoice_Line_Mapping__c ILM = new Invoice_Line_Mapping__c();
                        ILM.Payable_Invoice_Expense_Line_Item__c =exp1.id;
                		ILM.Payable_Invoice__c = exp1.c2g__PurchaseInvoice__c;
                		ILM.Order_Line__c = ol.id;
                        ILMtoInsert.add(ILM);
                    }
                }
            }
        }
        List<Invoice_Line_Mapping__c> existingList =[select Id,name, Payable_Invoice_Expense_Line_Item__c, Payable_Invoice__c,Order_Line__c from Invoice_Line_Mapping__c where Payable_Invoice__c IN : pinId AND Payable_Invoice_Expense_Line_Item__c IN: expId AND Order_Line__c IN :olId ];  
        system.debug('existingList:- '+existingList);
        
        try{
            Delete existingList;
            insert ILMtoInsert;
            system.debug('ILMtoInsert:- '+ILMtoInsert);
        }catch(exception ex){
            system.debug('Exception Occurred '+ex.getMessage());
        }
    }
}