force-app/main/default/objects/Deal__c/Deal__c.object-meta.xml
<CustomObject>
    <label>Deal</label>
    <nameField>
        <label>Deal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal__c/fields/Deal_Status__c.field-meta.xml
<CustomField>
    <fullName>Deal_Status__c</fullName>
    <inlineHelpText>This field drives the status in the &quot;path&quot; at the top of the page to show the &quot;overall status&quot; of the deal.</inlineHelpText>
    <label>Deal Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BDM - Deal Draft In Progress</fullName>
                <default>true</default>
                <label>BDM - Deal Draft In Progress</label>
            </value>
            <value>
                <fullName>BDM - Submitted</fullName>
            </value>
            <value>
                <fullName>Plan &amp; Configure</fullName>
            </value>
            <value>
                <fullName>Submitted for Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>With_Publishing</fullName>
                <label>With Publishing</label>
            </value>
            <value>
                <fullName>Ready for Proofing</fullName>
            </value>
            <value>
                <fullName>Pre-Published</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
                <color>#57F17C</color>
                <label>Published</label>
            </value>
            <value>
                <fullName>Not Approved</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Analysis &amp; Approval</fullName>
                <isActive>false</isActive>
                <label>Analysis &amp; Approval</label>
            </value>
            <value>
                <fullName>BDM</fullName>
                <isActive>false</isActive>
                <label>BDM</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <isActive>false</isActive>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Marketing</fullName>
                <isActive>false</isActive>
                <label>Marketing</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal__c/fields/Flight_Book_By__c.field-meta.xml
<CustomField>
    <fullName>Flight_Book_By__c</fullName>
    <label>Flight Book By</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Deal__c/fields/Real_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Real_End_Date__c</fullName>
    <label>Real End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Deal__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Hero</fullName>
            </value>
            <value>
                <fullName>Published(NRMA)</fullName>
            </value>
            <value>
                <fullName>Published(Staging)</fullName>
            </value>
            <value>
                <fullName>Hero(Staging)</fullName>
            </value>
            <value>
                <fullName>Hidden</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BAU_DealExpiredRealEndDatePassed_Batch.cls
global class BAU_DealExpiredRealEndDatePassed_Batch implements Database.Batchable < sobject >,Database.Stateful {
    
    global Database.QueryLocator start(Database.BatchableContext BC)
    {
          if(test.isRunningTest()){
            return Database.getQueryLocator([Select Id,Deal_Status__c,Status__c,Real_End_Date__c from Deal__c where Real_End_Date__c < TODAY AND Deal_Status__c != 'Expired' AND Status__c != 'Expired' AND Flight_Book_By__c !=NULL ]);
        }else{
            return Database.getQueryLocator([Select Id,Deal_Status__c,Status__c,Real_End_Date__c from Deal__c where Real_End_Date__c < TODAY AND Deal_Status__c != 'Expired' AND Status__c != 'Expired' AND Flight_Book_By__c !=NULL AND (Status__c = 'Published' OR Status__c = 'Hero') ]);
        }
    }
    
    global void execute(Database.BatchableContext BC, List<Deal__c> scope) { 
        
        List<Deal__c> dealStatusExpiredUpdateList = new List<Deal__c>();
        
        for(Deal__c d : scope)
        {
            if(d != null){
                
                d.Deal_Status__c = 'Expired';
                d.Status__c = 'Expired';
                dealStatusExpiredUpdateList.add(d);
                
            }
            
        }
        
        if(!dealStatusExpiredUpdateList.isEmpty()){
            update dealStatusExpiredUpdateList;
        }
    }
    
    global void finish(Database.BatchableContext BC){
        
    }
}