force-app/main/default/objects/Deal__c/Deal__c.object-meta.xml
<CustomObject>
    <label>Deal</label>
    <nameField>
        <label>Deal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal__c/fields/Cloned_From__c.field-meta.xml
<CustomField>
    <fullName>Cloned_From__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cloned From</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Deal</relationshipLabel>
    <relationshipName>Deal</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal__c/fields/Deal_ID_Title__c.field-meta.xml
<CustomField>
    <fullName>Deal_ID_Title__c</fullName>
    <formula>IF( ISBLANK(title__c) , 
Name&amp;&quot;-&quot;&amp;title_nz__c , 
Name&amp;&quot;-&quot;&amp;title__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Deal ID &amp; Title</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal__c/fields/Merchant__c.field-meta.xml
<CustomField>
    <fullName>Merchant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Merchant</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Product Partner, General Expense Vendors</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Deal</relationshipLabel>
    <relationshipName>Deal</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Hero</fullName>
            </value>
            <value>
                <fullName>Published(NRMA)</fullName>
            </value>
            <value>
                <fullName>Published(Staging)</fullName>
            </value>
            <value>
                <fullName>Hero(Staging)</fullName>
            </value>
            <value>
                <fullName>Hidden</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Marketing_Cloud_Preferences__c/Marketing_Cloud_Preferences__c.object-meta.xml
<CustomObject>
    <label>Marketing Cloud Preferences</label>
    <nameField>
        <displayFormat>MAP-{00000000}</displayFormat>
        <label>Marketing Cloud Preferences Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Marketing Cloud Preferences</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketing_Cloud_Preferences__c/fields/AccountID__c.field-meta.xml
<CustomField>
    <fullName>AccountID__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>AccountID</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Marketing Cloud Preferences</relationshipLabel>
    <relationshipName>Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Saved_Deals__c/Saved_Deals__c.object-meta.xml
<CustomObject>
    <label>Sales Lead</label>
    <nameField>
        <label>Sales Lead Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Leads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Saved_Deals__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Saved_Deals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Saved_Deals__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipName>Saved_Deals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Saved_Deals__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Closed Converted</fullName>
            </value>
            <value>
                <fullName>Closed Not Converted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Saved_Deals__c/fields/TAD_Order__c.field-meta.xml
<CustomField>
    <fullName>TAD_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TAD Order</label>
    <referenceTo>TAD_Order__c</referenceTo>
    <relationshipName>Saved_Deals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/TAD_Order__c.object-meta.xml
<CustomObject>
    <label>TAD Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TAD Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_amount_outstanding__c.field-meta.xml
<CustomField>
    <fullName>ordexp_amount_outstanding__c</fullName>
    <formula>(ordexp_nett_amount__c + TAD_Surcharge_Amount__c + ordexp_Date_City_Change_Refund__c) - (ordexp_total_payment_received__c + ( IF( Old_Credit_orders__c=true, Total_Credit_Amount__c,0 ) ) - ordexp_total_refund_amount__c - Total_Coupon_Amount__c -  
( IF( RecordType_Name__c  == &apos;Hotel&apos;, Total_QFF_Refund__c,0 ) ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount outstanding</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/recordTypes/TAD.recordType-meta.xml
<RecordType>
    <fullName>TAD</fullName>
    <active>true</active>
    <label>TAD</label>
</RecordType>

force-app/main/default/objects/TAD_Order__c/recordTypes/TC.recordType-meta.xml
<RecordType>
    <fullName>TC</fullName>
    <active>true</active>
    <label>TC</label>
</RecordType>

force-app/main/default/classes/case_TadOrderFlow.cls
public class case_TadOrderFlow {
    
    public class taddPaymentDeatails
    {
      @AuraEnabled  public string  QFFUrl{get;set;}
      @AuraEnabled public Decimal  OutstandingAmount{get;set;}
    }
    
 public class forTadData
    {
      @AuraEnabled  public string  accountId{get;set;}
         @AuraEnabled  public string  accountName{get;set;}
      @AuraEnabled public string  dealId{get;set;}
        @AuraEnabled public string  dealName{get;set;}
        @AuraEnabled public string  caseId{get;set;}
         @AuraEnabled public string  tadOrderId{get;set;}
         @AuraEnabled public string  savedDealId{get;set;}
        @AuraEnabled public string  savedDealStatus{get;set;}
    }    
     @AuraEnabled 
    public static forTadData TadOrdercreation(Id saveddealId){
       forTadData ftd = new forTadData();
         System.debug('saveddealId=121===>');
         List<Case>  cases = new List<Case>();
         cases =[select id,Saved_Deal__c from Case  where Saved_Deal__c=:saveddealId];
        System.debug('cases====>'+cases);
        Saved_Deals__c savedDealName = [select id,name,Status__c,Account__c,Account__r.name,Deal__c,Deal__r.Deal_ID_Title__c,TAD_Order__c from Saved_Deals__c  where id=:saveddealId];
        //String value = String.valueof(orderobj.ordexp_amount_outstanding__c);
         System.debug('savedDealName====>'+savedDealName);
   
        ftd.accountId = savedDealName.Account__c;
        ftd.accountName = savedDealName.Account__r.name;
        ftd.dealId = savedDealName.Deal__c;
        ftd.dealName = savedDealName.Deal__r.Deal_ID_Title__c;
        ftd.savedDealStatus=savedDealName.Status__c;
        if(!cases.isEmpty()){
            ftd.caseId = cases[0].Id; 
        }
       
        ftd.tadOrderId = savedDealName.TAD_Order__c;
        ftd.savedDealId = savedDealName.Id;
         System.debug('ftd====>'+ftd);
        return ftd;
    }
    
    
    @AuraEnabled 
    public static taddPaymentDeatails fetchAmmount(Id ordId){
        System.debug('ordId====>'+ordId);
        taddPaymentDeatails tpdObj = new taddPaymentDeatails();
        
        TAD_Order__c order = [select id,name,recordtype.name,ordexp_amount_outstanding__c from TAD_Order__c  where id=:ordId];
        //String value = String.valueof(orderobj.ordexp_amount_outstanding__c);
         System.debug('amountutstanding====>'+order.recordtype.name);
         System.debug('recordtype====>'+order.ordexp_amount_outstanding__c);
        if(order.RecordType.Name == 'TAD' || order.RecordType.Name == 'TC'){
            String baseUrlTADTC = System.Label.AbTest_BaseURL;
            String str = baseUrlTADTC+order.Name+'&total='+order.ordexp_amount_outstanding__c;
            tpdObj.QFFUrl = str;
                System.debug('strif====>'+str);
            
        }else{
            String baseUrlTNZWT = System.Label.AbTest_BaseURL_TNZ_WT ;
            String str = baseUrlTNZWT+order.Name+'&total='+order.ordexp_amount_outstanding__c;
            tpdObj.QFFUrl = str;
              System.debug('strElse====>'+str);
        }
        tpdObj.OutstandingAmount = order.ordexp_amount_outstanding__c;
        
         System.debug('tpdObj====>'+tpdObj);
        return tpdObj;
    }
    
    @AuraEnabled
    public static string getThePaylineURL(String tadOrderRecordId){
        
        TAD_Order__c tadOrder = [Select id, Name, ordexp_amount_outstanding__c from TAD_Order__c where id =: tadOrderRecordId];
        User currentUser = [Select id, Payline_Token__c, Payline_Username__c from User where ID =: UserInfo.getUserId()];
        String paylineURL = System.Label.Payline_Base_URL + currentUser.Payline_Username__c + System.Label.Payline_Base_URL_1 + currentUser.Payline_Token__c + System.Label.Payline_Base_URL_2 + tadOrder.Name + System.Label.Payline_Base_URL_3 + Integer.valueOf((tadOrder.ordexp_amount_outstanding__c * 100)) + System.Label.Payline_Base_URL_4;
            
        return paylineURL;
    }
}