force-app/main/default/objects/Deal__c/Deal__c.object-meta.xml
<CustomObject>
    <label>Deal</label>
    <nameField>
        <label>Deal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal__c/fields/Channel_Partner__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner__c</fullName>
    <label>Channel Partner</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Siteminder</fullName>
                <default>true</default>
                <label>Siteminder</label>
            </value>
            <value>
                <fullName>TravelClick</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal__c/fields/Hotel_Code__c.field-meta.xml
<CustomField>
    <fullName>Hotel_Code__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Hotel Code</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Deal__c/recordTypes/Hotel.recordType-meta.xml
<RecordType>
    <fullName>Hotel</fullName>
    <active>true</active>
    <description>This isa new Record Type, for integrating with Siteminder/TravelClcik (Deal shall work as the primary object -- HOTEL).</description>
    <label>Hotel</label>
</RecordType>

force-app/main/default/objects/departures_dates__c/departures_dates__c.object-meta.xml
<CustomObject>
    <label>departures dates</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>departures dates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/departures_dates__c/fields/date__c.field-meta.xml
<CustomField>
    <fullName>date__c</fullName>
    <label>date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>departures dates</relationshipLabel>
    <relationshipName>departures_dates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/options__c.field-meta.xml
<CustomField>
    <fullName>options__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>options</label>
    <referenceTo>options__c</referenceTo>
    <relationshipLabel>departures dates</relationshipLabel>
    <relationshipName>departures_dates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/sub_options__c.field-meta.xml
<CustomField>
    <fullName>sub_options__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>sub options</label>
    <referenceTo>sub_options__c</referenceTo>
    <relationshipLabel>departures dates</relationshipLabel>
    <relationshipName>departures_dates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/options__c/options__c.object-meta.xml
<CustomObject>
    <label>Options</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/options__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipName>options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/options__c/fields/Hotel_Code__c.field-meta.xml
<CustomField>
    <fullName>Hotel_Code__c</fullName>
    <formula>if( Deal__r.RecordType.Name = &apos;Hotel&apos;,  Deal__r.Hotel_Code__c , &apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Hotel Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rate_Plan__c/Rate_Plan__c.object-meta.xml
<CustomObject>
    <label>Rate Plan</label>
    <nameField>
        <label>Rate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Rate_Plan__c/fields/Rate_Plan_Code__c.field-meta.xml
<CustomField>
    <fullName>Rate_Plan_Code__c</fullName>
    <label>Rate Plan Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sub_options__c/sub_options__c.object-meta.xml
<CustomObject>
    <label>Sub Options</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/sub_options__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Sub Options</relationshipLabel>
    <relationshipName>Sub_Options</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sub_options__c/fields/Hotel_Code__c.field-meta.xml
<CustomField>
    <fullName>Hotel_Code__c</fullName>
    <formula>Deal__r.Hotel_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Hotel Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sub_options__c/fields/options__c.field-meta.xml
<CustomField>
    <fullName>options__c</fullName>
    <label>options</label>
    <referenceTo>options__c</referenceTo>
    <relationshipLabel>Sub Options</relationshipLabel>
    <relationshipName>sub_options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/sub_options__c/fields/Rate_Plan__c.field-meta.xml
<CustomField>
    <fullName>Rate_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rate Plan</label>
    <referenceTo>Rate_Plan__c</referenceTo>
    <relationshipLabel>Sub Options</relationshipLabel>
    <relationshipName>Sub_Options</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sub_options__c/fields/Rate_Plan_Code__c.field-meta.xml
<CustomField>
    <fullName>Rate_Plan_Code__c</fullName>
    <formula>Rate_Plan__r.Rate_Plan_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Rate Plan Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sub_options__c/fields/Room_Type_Code__c.field-meta.xml
<CustomField>
    <fullName>Room_Type_Code__c</fullName>
    <label>Room Type Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OTA_HotelRatePlanNotifRQ_OTAConnectTest.cls
@isTest
public class OTA_HotelRatePlanNotifRQ_OTAConnectTest {
  @isTest
    static void testHttpPostError() {
        // prepare test-data
        
        //As Per Best Practice it is important to instantiate the Rest Context
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        req.requestURI = '/services/apexrest/Something'; //Request URL
        req.httpMethod = 'POST';
        String postData = '{"POS": {"Source": {"BookingChannel": {"CompanyName": {"Code": "PartnerCode","text": "Partner Name"},"Type": "7"}}},"RatePlans": {"RatePlan": [{"Rates": {"Rate": [{"BaseByGuestAmts": {"BaseByGuestAmt": [{"AmountAfterTax": "100.00","NumberOfGuests": "1","AgeQualifyingCode": "10"},{"AmountAfterTax": "100.00","NumberOfGuests": "2","AgeQualifyingCode": "10"}]},"AdditionalGuestAmounts": {"AdditionalGuestAmount": [{"Amount": "25.00","AgeQualifyingCode": "10"},{"Amount": "0.00","AgeQualifyingCode": "8"}]},"InvTypeCode": "GSR","CurrencyCode": "AUD"}]},"RatePlanCode": "GLD","Start": "2027-06-01","endDate": "2027-01-03"}],"HotelCode": "CP121"}}';

        req.requestBody=Blob.valueof(postData);
        RestContext.request = req;
        RestContext.response= res;
        
        Test.startTest();
        OTA_HotelRatePlanNotifRQ_OTAConnect.createRateDetailsRecords();
        Test.stopTest();
        
    }
    
  
    @isTest
    static void testHttpPostHotelExistWithRoomType() {
        
        List<RecordType> RCTProductPartner = TADUtils.getRecordType(Label.TAD_RT_Product_Partner);
        List<RecordType> RCTTadDeal = TADUtils.getRecordType(Label.TAD_RT_TAD_Deal);
        Account account = TestDataFactory.createBussinessAccount(RCTProductPartner[0].Id);   // Bussiness account Inserted
        insert account;
        
        Deal__c deal = TestDataFactory.createMerchantDeal(RCTTadDeal[0].Id , account.Id );   // Deals created
        deal.RecordTypeId = Schema.SObjectType.Deal__c.getRecordTypeInfosByName().get('Hotel').getRecordTypeId();
        deal.Hotel_Code__c='CP121';
        deal.Channel_Partner__c='TravelClick';
        insert deal;
        
        options__c options =  TestDataFactory.CreateOptions(deal.Id); 
        insert options;
        
        Rate_Plan__c  rp = new Rate_Plan__c ();
        rp.Rate_Plan_Code__c='GLD';
        insert rp;
        
        sub_options__c subOptions = TestDataFactory.createSubOptions(options.Id);
        subOptions.Room_Type_Code__c ='PSWP';
        subOptions.RecordTypeId = Schema.SObjectType.sub_options__c.getRecordTypeInfosByName().get('Room Type').getRecordTypeId();
        subOptions.Rate_Plan__c =rp.id;
        insert subOptions;
        
        
        //As Per Best Practice it is important to instantiate the Rest Context
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        req.requestURI = '/services/apexrest/Something'; //Request URL
        req.httpMethod = 'POST';
        
        String postData = '{"POS": {"Source": {"BookingChannel": {"CompanyName": {"Code": "PartnerCode","text": "Partner Name"},"Type": "7"}}},"RatePlans": {"RatePlan": [{"Rates": {"Rate": [{"BaseByGuestAmts": {"BaseByGuestAmt": [{"AmountAfterTax": "100.00","NumberOfGuests": "1","AgeQualifyingCode": "10"},{"AmountAfterTax": "100.00","NumberOfGuests": "2","AgeQualifyingCode": "10"}]},"AdditionalGuestAmounts": {"AdditionalGuestAmount": [{"Amount": "25.00","AgeQualifyingCode": "10"},{"Amount": "0.00","AgeQualifyingCode": "8"}]},"InvTypeCode": "GSR","CurrencyCode": "AUD"}]},"RatePlanCode": "GLD","Start": "2027-06-01","endDate": "2027-01-03"}],"HotelCode": "CP121"}}';

        req.requestBody=Blob.valueof(postData);
        
        RestContext.request = req;
        RestContext.response= res;
        
        Test.startTest();
        OTA_HotelRatePlanNotifRQ_OTAConnect.createRateDetailsRecords();
        Test.stopTest();
        
    }
    
    @isTest
    static void testHttpPostHotelExistWithRoomType1() {
        
        List<RecordType> RCTProductPartner = TADUtils.getRecordType(Label.TAD_RT_Product_Partner);
        List<RecordType> RCTTadDeal = TADUtils.getRecordType(Label.TAD_RT_TAD_Deal);
        Account account = TestDataFactory.createBussinessAccount(RCTProductPartner[0].Id);   // Bussiness account Inserted
        insert account;
        
        Deal__c deal = TestDataFactory.createMerchantDeal(RCTTadDeal[0].Id , account.Id );   // Deals created
        deal.RecordTypeId = Schema.SObjectType.Deal__c.getRecordTypeInfosByName().get('Hotel').getRecordTypeId();
        deal.Hotel_Code__c='CP121';
        deal.Channel_Partner__c='TravelClick';
        insert deal;
        
        options__c options =  TestDataFactory.CreateOptions(deal.Id); 
        insert options;
        
        Rate_Plan__c  rp = new Rate_Plan__c ();
        rp.Rate_Plan_Code__c='GLD';
        insert rp;
        
        sub_options__c subOptions = TestDataFactory.createSubOptions(options.Id);
        subOptions.Room_Type_Code__c ='GSR';
        subOptions.RecordTypeId = Schema.SObjectType.sub_options__c.getRecordTypeInfosByName().get('Room Type').getRecordTypeId();
        subOptions.Rate_Plan__c =rp.id;
        insert subOptions;
        
        departures_dates__c dd = TestDataFactory.createDepartureDates(deal.Id, options.Id,subOptions.id);
        dd.date__c= date.newInstance(2027, 06, 01);
        insert dd;
 
        //As Per Best Practice it is important to instantiate the Rest Context
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        req.requestURI = '/services/apexrest/Something'; //Request URL
        req.httpMethod = 'POST';
        
        String postData = '{"POS": {"Source": {"BookingChannel": {"CompanyName": {"Code": "PartnerCode","text": "Partner Name"},"Type": "7"}}},"RatePlans": {"RatePlan": [{"Rates": {"Rate": [{"BaseByGuestAmts": {"BaseByGuestAmt": [{"AmountAfterTax": "100.00","NumberOfGuests": "1","AgeQualifyingCode": "10"},{"AmountAfterTax": "100.00","NumberOfGuests": "2","AgeQualifyingCode": "10"}]},"AdditionalGuestAmounts": {"AdditionalGuestAmount": [{"Amount": "25.00","AgeQualifyingCode": "10"},{"Amount": "0.00","AgeQualifyingCode": "8"}]},"InvTypeCode": "GSR","CurrencyCode": "AUD"}]},"RatePlanCode": "GLD","Start": "2027-06-01","endDate": "2027-06-03"}],"HotelCode": "CP121"}}';
        req.requestBody=Blob.valueof(postData);
        
        RestContext.request = req;
        RestContext.response= res;
        
        Test.startTest();
         OTA_HotelRatePlanNotifRQ_OTAConnect.createRateDetailsRecords();
        Test.stopTest();
        
    } 
  
}