force-app/main/default/objects/Deal__c/Deal__c.object-meta.xml
<CustomObject>
    <label>Deal</label>
    <nameField>
        <label>Deal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal__c/fields/order__c.field-meta.xml
<CustomField>
    <fullName>order__c</fullName>
    <label>order on site</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/order__c/order__c.object-meta.xml
<CustomObject>
    <label>orders</label>
    <nameField>
        <displayFormat>{00}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>order</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/order__c/fields/Account_phone_number__c.field-meta.xml
<CustomField>
    <fullName>Account_phone_number__c</fullName>
    <description>Points to mobile if there is a mobile if not then will pull regular phone field from account</description>
    <formula>IF( 
    NOT(ISBLANK(Account__r.PersonContact.MobilePhone)),
    Account__r.PersonContact.MobilePhone,
    (Account__r.Phone)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account phone number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/order__c/fields/AP_Deal_has_flights__c.field-meta.xml
<CustomField>
    <fullName>AP_Deal_has_flights__c</fullName>
    <description>Initially used for AP processes</description>
    <formula>deal__r.has_flights__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Deal has flights</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/order__c/fields/China_EDM__c.field-meta.xml
<CustomField>
    <fullName>China_EDM__c</fullName>
    <formula>AND

(INCLUDES( deal__r.Country__c ,&apos;China&apos;),




    (  NOW() - PIF_outstanding_to_zero_time__c ) &gt;=  ( 24 / 24 ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>China EDM</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/order__c/fields/Days_until_Departure_Date__c.field-meta.xml
<CustomField>
    <fullName>Days_until_Departure_Date__c</fullName>
    <description>To count days left until DD</description>
    <formula>IF(
    NOT(ISBLANK(pre_tour_stopover__c)),
    departure_date__c - Sub_Stop_over_nights_date__c,
    IF(
        AND(
            NOT(ISBLANK(AE_Nights__c)),
            AE_Nights__c &gt; 0
        ),
        True_departure_date_from_AE_nights__c -TODAY(),
        departure_date__c -  TODAY()
    )
)
- IF(day_zero_departure__c, 1, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Days until Departure Date</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/order__c/fields/deal__c.field-meta.xml
<CustomField>
    <fullName>deal__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Deal</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Deal__c.Status__c</field>
            <operation>equals</operation>
            <value>Published, Hero, Hidden</value>
        </filterItems>
        <filterItems>
            <field>Deal__c.Status_NZ__c</field>
            <operation>equals</operation>
            <value>Published, Hero, Hidden</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>order</relationshipLabel>
    <relationshipName>order</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/order__c/fields/departure_city__c.field-meta.xml
<CustomField>
    <fullName>departure_city__c</fullName>
    <label>Departure City</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/order__c/fields/departure_date__c.field-meta.xml
<CustomField>
    <fullName>departure_date__c</fullName>
    <label>Departure Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/order__c/fields/email_purchaser__c.field-meta.xml
<CustomField>
    <fullName>email_purchaser__c</fullName>
    <label>Email(Purchaser)</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/order__c/fields/first_name_purchaser__c.field-meta.xml
<CustomField>
    <fullName>first_name_purchaser__c</fullName>
    <label>Purchaser First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/order__c/fields/full_name_purchaser__c.field-meta.xml
<CustomField>
    <fullName>full_name_purchaser__c</fullName>
    <label>Purchaser Full Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/order__c/fields/Is_Escape_Deal__c.field-meta.xml
<CustomField>
    <fullName>Is_Escape_Deal__c</fullName>
    <formula>OR(deal__r.Is_Escapes__c,
deal__r.show_as_escape__c,
INCLUDES( deal__r.deal_type__c , &quot;stay&quot;),
INCLUDES( deal__r.deal_type_nz__c , &quot;stay&quot;) 
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Escape Deal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/order__c/fields/isstay__c.field-meta.xml
<CustomField>
    <fullName>isstay__c</fullName>
    <formula>IF(OR(INCLUDES(deal__r.deal_type__c, &apos;stay&apos;), INCLUDES(deal__r.deal_type_nz__c, &apos;stay&apos;)), TRUE, FALSE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>isstay</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/order__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <formula>Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/order__c/fields/order_status__c.field-meta.xml
<CustomField>
    <fullName>order_status__c</fullName>
    <inlineHelpText>OH - Order is held|
con - Order paid awaiting PIF|
RFE - PIF/PAX = QTY|
Ex - Order is locked, ticketing has begun|
pending C - If purchaser cancels order|
cancelled - Auto set by booking status DNT|
expired - Not required</inlineHelpText>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>On Hold</fullName>
                <default>true</default>
                <label>On Hold</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Ready For Export</fullName>
            </value>
            <value>
                <fullName>Exported</fullName>
            </value>
            <value>
                <fullName>Pending Cancellation</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Migrate</fullName>
            </value>
            <value>
                <fullName>Migrated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/order__c/fields/PIF_outstanding_to_zero_time__c.field-meta.xml
<CustomField>
    <fullName>PIF_outstanding_to_zero_time__c</fullName>
    <label>PIF outstanding to zero time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/order__c/fields/Purchaser_Second_Name__c.field-meta.xml
<CustomField>
    <fullName>Purchaser_Second_Name__c</fullName>
    <formula>Account__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Purchaser Second Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/order__c/fields/return_date__c.field-meta.xml
<CustomField>
    <fullName>return_date__c</fullName>
    <formula>departure_date__c +  deal__r.number_of_days__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>return date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/order__c/recordTypes/TC.recordType-meta.xml
<RecordType>
    <fullName>TC</fullName>
    <active>true</active>
    <label>TC</label>
</RecordType>

force-app/main/default/objects/order__c/recordTypes/WT.recordType-meta.xml
<RecordType>
    <fullName>WT</fullName>
    <active>true</active>
    <description>World Traveller - NZ Wholesale</description>
    <label>WT</label>
</RecordType>

force-app/main/default/objects/Order_Communication__c/Order_Communication__c.object-meta.xml
<CustomObject>
    <description>Records created by scheduled apex</description>
    <label>Order Communication (Old)</label>
    <nameField>
        <displayFormat>OC-{00000000}</displayFormat>
        <label>Order Communication Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Communications (Old)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Communication__c/fields/Days_until_Departure_Date__c.field-meta.xml
<CustomField>
    <fullName>Days_until_Departure_Date__c</fullName>
    <formula>order__r.Days_until_Departure_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Days until Departure Date</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Communication__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <formula>order__r.Deal_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Deal</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Communication__c/fields/departure_date__c.field-meta.xml
<CustomField>
    <fullName>departure_date__c</fullName>
    <label>Departure Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order_Communication__c/fields/order__c.field-meta.xml
<CustomField>
    <fullName>order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>order__c</referenceTo>
    <relationshipLabel>Order Communications</relationshipLabel>
    <relationshipName>Order_Communications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Communication__c/fields/phone__c.field-meta.xml
<CustomField>
    <fullName>phone__c</fullName>
    <label>Phone</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Communication__c/fields/purchaser_last_name__c.field-meta.xml
<CustomField>
    <fullName>purchaser_last_name__c</fullName>
    <label>Purchaser Last Name</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ScheduleOrderCommunications.cls
global class ScheduleOrderCommunications implements Schedulable {

    global void execute(SchedulableContext ctx) {

        Set<String> statuses = new Set<String>{'Confirmed', 'Ready For Export', 'Exported'};
        Set<Id> nzRtIds = new Set<Id>();
        Id tcRecordTypeId = Schema.SObjectType.order__c.getRecordTypeInfosByName().get('TC').getRecordTypeId();
        nzRtIds.add(tcRecordTypeId);
        Id wtRecordTypeId = Schema.SObjectType.order__c.getRecordTypeInfosByName().get('WT').getRecordTypeId();
        nzRtIds.add(wtRecordTypeId);

        List<Order_Communication__c> oComms = new List<Order_Communication__c>();

        // ##### WELCOME HOME
        List<order__c> ordersWelcomeHome = [SELECT Id, Name, email_purchaser__c, first_name_purchaser__c, full_name_purchaser__c,
                Purchaser_Second_Name__c, RecordTypeId, RecordType.Name, deal__c, departure_date__c, departure_city__c, return_date__c,
                Account_phone_number__c FROM order__c WHERE return_date__c = :Date.today().addDays(-1) AND isstay__c = false
        AND order_status__c IN :statuses AND RecordTypeId NOT IN :nzRtIds];

        for (order__c o : ordersWelcomeHome) {
            Order_Communication__c oc = new Order_Communication__c();
            oc.order__c = o.Id;
            oc.purchaser_first_name__c = o.first_name_purchaser__c;
            oc.purchaser_last_name__c = o.Purchaser_Second_Name__c;
            oc.purchaser_full_name__c = o.full_name_purchaser__c;
            oc.email_purchaser__c = o.email_purchaser__c;
            oc.phone__c = o.Account_phone_number__c;
            oc.departure_date__c = o.departure_date__c;
            oc.return_date__c = o.return_date__c;
            oc.departure_city__c = o.departure_city__c;
            oc.communication_code__c = 'Welcome Home';
            oComms.add(oc);
        }

        // ##### ORDER SURVEY
        List<order__c> orderSurvey = [SELECT Id, Name, email_purchaser__c, first_name_purchaser__c, full_name_purchaser__c,
                Purchaser_Second_Name__c, RecordTypeId, RecordType.Name, deal__c, departure_date__c, departure_city__c, return_date__c,
                Account_phone_number__c, Is_Escape_Deal__c, isstay__c FROM order__c WHERE return_date__c = :Date.today().addDays(-2)
        AND order_status__c IN :statuses AND RecordTypeId NOT IN :nzRtIds];

        for (order__c o : orderSurvey) {
            if (o.Is_Escape_Deal__c) {
                Order_Communication__c oc = new Order_Communication__c();
                oc.order__c = o.Id;
                oc.purchaser_first_name__c = o.first_name_purchaser__c;
                oc.purchaser_last_name__c = o.Purchaser_Second_Name__c;
                oc.purchaser_full_name__c = o.full_name_purchaser__c;
                oc.email_purchaser__c = o.email_purchaser__c;
                oc.phone__c = o.Account_phone_number__c;
                oc.departure_date__c = o.departure_date__c;
                oc.return_date__c = o.return_date__c;
                oc.departure_city__c = o.departure_city__c;
                oc.communication_code__c = 'Escapes Survey';
                oComms.add(oc);
            } else if (!o.isstay__c) {
                Order_Communication__c oc = new Order_Communication__c();
                oc.order__c = o.Id;
                oc.purchaser_first_name__c = o.first_name_purchaser__c;
                oc.purchaser_last_name__c = o.Purchaser_Second_Name__c;
                oc.purchaser_full_name__c = o.full_name_purchaser__c;
                oc.email_purchaser__c = o.email_purchaser__c;
                oc.phone__c = o.Account_phone_number__c;
                oc.departure_date__c = o.departure_date__c;
                oc.return_date__c = o.return_date__c;
                oc.departure_city__c = o.departure_city__c;
                oc.communication_code__c = 'WH Survey';
                oComms.add(oc);
            }
        }

        // ##### BON VOYAGE
        List<order__c> bonVoyageEmail = [SELECT Id, Name, email_purchaser__c, first_name_purchaser__c, full_name_purchaser__c,
                Purchaser_Second_Name__c, RecordTypeId, RecordType.Name, deal__c, departure_date__c, departure_city__c, return_date__c,
                Account_phone_number__c FROM order__c WHERE Days_until_Departure_Date__c = 3 AND isstay__c = false AND AP_Deal_has_flights__c = true
        AND order_status__c IN :statuses AND RecordTypeId NOT IN :nzRtIds];

        for (order__c o : bonVoyageEmail) {
            Order_Communication__c oc = new Order_Communication__c();
            oc.order__c = o.Id;
            oc.purchaser_first_name__c = o.first_name_purchaser__c;
            oc.purchaser_last_name__c = o.Purchaser_Second_Name__c;
            oc.purchaser_full_name__c = o.full_name_purchaser__c;
            oc.email_purchaser__c = o.email_purchaser__c;
            oc.phone__c = o.Account_phone_number__c;
            oc.departure_date__c = o.departure_date__c;
            oc.return_date__c = o.return_date__c;
            oc.departure_city__c = o.departure_city__c;
            oc.communication_code__c = 'Bon Voyage Email';
            oComms.add(oc);
        }

        // ##### CHINA EDM
        Datetime yesterday = Datetime.newInstance(Date.today().addDays(-1),Time.newInstance(14,0,0,0));
        List<order__c> chinaEDM = [SELECT Id, Name, email_purchaser__c, first_name_purchaser__c, full_name_purchaser__c,
                Purchaser_Second_Name__c, RecordTypeId, RecordType.Name, deal__c, departure_date__c, departure_city__c, return_date__c,
                Account_phone_number__c FROM order__c WHERE China_EDM__c = true AND PIF_outstanding_to_zero_time__c > :yesterday
        AND order_status__c IN :statuses AND RecordTypeId NOT IN :nzRtIds];

        for (order__c o : chinaEDM) {
            Order_Communication__c oc = new Order_Communication__c();
            oc.order__c = o.Id;
            oc.purchaser_first_name__c = o.first_name_purchaser__c;
            oc.purchaser_last_name__c = o.Purchaser_Second_Name__c;
            oc.purchaser_full_name__c = o.full_name_purchaser__c;
            oc.email_purchaser__c = o.email_purchaser__c;
            oc.phone__c = o.Account_phone_number__c;
            oc.departure_date__c = o.departure_date__c;
            oc.return_date__c = o.return_date__c;
            oc.departure_city__c = o.departure_city__c;
            oc.communication_code__c = 'China EDM';
            oComms.add(oc);
        }

        insert oComms;

        // #### Remove record deletion scheduling
        // Clean out old Order Comms
        //Datetime deletionDateLine = Datetime.now().addDays(-15);
        //List<Order_Communication__c> ocsForDeletion = [SELECT Id FROM Order_Communication__c WHERE CreatedDate < :deletionDateLine];

        //delete ocsForDeletion;
    }
}