force-app/main/default/objects/Deal__c/Deal__c.object-meta.xml
<CustomObject>
    <label>Deal</label>
    <nameField>
        <label>Deal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal__c/fields/Channel_Partner__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner__c</fullName>
    <label>Channel Partner</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Siteminder</fullName>
                <default>true</default>
                <label>Siteminder</label>
            </value>
            <value>
                <fullName>TravelClick</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal__c/fields/Hotel_Code__c.field-meta.xml
<CustomField>
    <fullName>Hotel_Code__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Hotel Code</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Deal__c/recordTypes/Hotel.recordType-meta.xml
<RecordType>
    <fullName>Hotel</fullName>
    <active>true</active>
    <description>This isa new Record Type, for integrating with Siteminder/TravelClcik (Deal shall work as the primary object -- HOTEL).</description>
    <label>Hotel</label>
</RecordType>

force-app/main/default/objects/departures_dates__c/departures_dates__c.object-meta.xml
<CustomObject>
    <label>departures dates</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>departures dates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/departures_dates__c/fields/Close_Arrival__c.field-meta.xml
<CustomField>
    <fullName>Close_Arrival__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Close Arrival</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/date__c.field-meta.xml
<CustomField>
    <fullName>date__c</fullName>
    <label>date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>departures dates</relationshipLabel>
    <relationshipName>departures_dates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/Minimum_LOS__c.field-meta.xml
<CustomField>
    <fullName>Minimum_LOS__c</fullName>
    <label>Minimum LOS</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/Stop_Sell_Open_Sell__c.field-meta.xml
<CustomField>
    <fullName>Stop_Sell_Open_Sell__c</fullName>
    <label>Stop Sell/Open Sell</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Stop Sell</fullName>
            </value>
            <value>
                <fullName>Open Sell</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/sub_options__c.field-meta.xml
<CustomField>
    <fullName>sub_options__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>sub options</label>
    <referenceTo>sub_options__c</referenceTo>
    <relationshipLabel>departures dates</relationshipLabel>
    <relationshipName>departures_dates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rate_Plan__c/Rate_Plan__c.object-meta.xml
<CustomObject>
    <label>Rate Plan</label>
    <nameField>
        <label>Rate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Rate_Plan__c/fields/Rate_Plan_Code__c.field-meta.xml
<CustomField>
    <fullName>Rate_Plan_Code__c</fullName>
    <label>Rate Plan Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Room_Rate_Detail__c/Room_Rate_Detail__c.object-meta.xml
<CustomObject>
    <label>Room Rate Detail</label>
    <nameField>
        <label>Room Rate Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Room Rate Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Room_Rate_Detail__c/fields/AgeQualifyingCode__c.field-meta.xml
<CustomField>
    <fullName>AgeQualifyingCode__c</fullName>
    <label>AgeQualifyingCode</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Room_Rate_Detail__c/fields/AmountAfterTax__c.field-meta.xml
<CustomField>
    <fullName>AmountAfterTax__c</fullName>
    <label>AmountAfterTax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Room_Rate_Detail__c/fields/departures_dates__c.field-meta.xml
<CustomField>
    <fullName>departures_dates__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>departures dates</label>
    <referenceTo>departures_dates__c</referenceTo>
    <relationshipLabel>Room Rate Details</relationshipLabel>
    <relationshipName>Room_Rate_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Room_Rate_Detail__c/fields/NumberOfGuests__c.field-meta.xml
<CustomField>
    <fullName>NumberOfGuests__c</fullName>
    <label>NumberOfGuests</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Room_Rate_Detail__c/fields/Rate_Description__c.field-meta.xml
<CustomField>
    <fullName>Rate_Description__c</fullName>
    <label>Rate Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Room_Rate_Detail__c/fields/Room_Rate_Unique_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Room_Rate_Unique_Identifier__c</fullName>
    <externalId>true</externalId>
    <label>Room Rate Unique Identifier</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sub_options__c/sub_options__c.object-meta.xml
<CustomObject>
    <label>Sub Options</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/sub_options__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Sub Options</relationshipLabel>
    <relationshipName>Sub_Options</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sub_options__c/fields/Hotel_Code__c.field-meta.xml
<CustomField>
    <fullName>Hotel_Code__c</fullName>
    <formula>Deal__r.Hotel_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Hotel Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sub_options__c/fields/Rate_Plan__c.field-meta.xml
<CustomField>
    <fullName>Rate_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rate Plan</label>
    <referenceTo>Rate_Plan__c</referenceTo>
    <relationshipLabel>Sub Options</relationshipLabel>
    <relationshipName>Sub_Options</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sub_options__c/fields/Rate_Plan_Code__c.field-meta.xml
<CustomField>
    <fullName>Rate_Plan_Code__c</fullName>
    <formula>Rate_Plan__r.Rate_Plan_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Rate Plan Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sub_options__c/fields/Room_Type_Code__c.field-meta.xml
<CustomField>
    <fullName>Room_Type_Code__c</fullName>
    <label>Room Type Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sub_options__c/fields/Room_Type_Description__c.field-meta.xml
<CustomField>
    <fullName>Room_Type_Description__c</fullName>
    <label>Room Type Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/sub_options__c/fields/Room_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Room_Type_Name__c</fullName>
    <label>Room Type Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TravelClick_OTAConnect_Errors__mdt/TravelClick_OTAConnect_Errors__mdt.object-meta.xml
<CustomObject>
    <description>This contains the Error Handling Data for OTA Connect by Travel Click.</description>
    <label>TravelClick_OTAConnect Error</label>
    <pluralLabel>TravelClick_OTAConnect Error</pluralLabel>
</CustomObject>

force-app/main/default/objects/TravelClick_OTAConnect_Errors__mdt/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <label>Error Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TravelClick_OTAConnect_Errors__mdt/fields/Short_Text__c.field-meta.xml
<CustomField>
    <fullName>Short_Text__c</fullName>
    <label>Short Text</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/Get_OTA_HotelRatePlanRQ.cls
@RestResource(urlmapping='/getTheExistingRatePlans')
global class Get_OTA_HotelRatePlanRQ {
    
    // REQUEST WRAPPER STARTS
    
    global class mainWrapperReq{
        global POS POS{get;set;}
        global RatePlans RatePlans{get;set;}
    }
    
    global class POS{
        global Source Source{get;set;}
    }
    
    global class Source{
        global BookingChannel BookingChannel{get;set;}
    }
    
    global class BookingChannel{
        global integer Type{get;set;}
        global CompanyName CompanyName{get;set;} 
    }
    
    global class CompanyName{
        global string Code{get;set;}
        global string value{get;set;}  
    }
    
    global class DateRange{
        global String Start{get;set;}
        global String EndDate{get;set;}  
    }
    
    global class RatePlanCandidates{
        global list<RatePlanCandidate> RatePlanCandidate{get;set;}   
    }
    
    global class RatePlanCandidate{
        global String RatePlanCode{get;set;}    
    }
    
    global class HotelRef{
        global String HotelCode{get;set;}   
    }
    // REQUEST WRAPPER ENDS 
    
    //RESPONSE WRAPPER STARTS
    
    global class mainWrapper{
        global RatePlans RatePlans{get;set;}
        global Errors Errors {get;set;}
    }
    
    //Also being used in Request Wrapper
    global class RatePlans{
        global string HotelCode{get;set;}
        global List<RatePlan> RatePlan{get;set;} 
    }
    
    //Also being used in Request Wrapper
    global class RatePlan{
        global string RatePlanCode{get;set;}
        global string Start{get;set;}
        global string EndDate{get;set;}
        global List<Rates> Rates{get;set;} // Not necessarily be a List, but has been taken as per the Documentation.
        global DateRange DateRange{get;set;}//only used with request
        global RatePlanCandidates RatePlanCandidates{get;set;}
        global HotelRef HotelRef{get;set;}
    }     
    global class Rates{
        global List<Rate> Rate{get;set;} 
        
    }
    
    global class Rate{
        global string InvTypeCode{get;set;}
        global string CurrencyCode{get;set;}
        global BaseByGuestAmts BaseByGuestAmts{get;set;}
        global AdditionalGuestAmounts AdditionalGuestAmounts{get;set;}
    }
    
    global class BaseByGuestAmts{
        global List<BaseByGuestAmt> BaseByGuestAmt{get;set;} 
    }
    
    global class BaseByGuestAmt{
        global string AmountAfterTax{get;set;}
        global string NumberOfGuests{get;set;}
    }
    
    global class AdditionalGuestAmounts{
        global List<AdditionalGuestAmount> AdditionalGuestAmount{get;set;}
    }
    
    global class AdditionalGuestAmount{
        global string Amount{get;set;}
        global string AgeQualifyingCode {get;set;}
    }
    
    global class Errors{
        global Error Error{get;set;}
    }
    
    global class Error{     
        global integer errorType{get;set;}
        global integer Code{get;set;}
        global string ShortText{get;set;} 
        global string errorMessage_Value{get;set;}
    }
    
    //RESPONSE WRAPPER ENDS
    
    @HttpPost
    global static mainWrapper doPost(){
        
        mainWrapper response = new mainWrapper();
        
        RestRequest req = RestContext.request;
        string requestBodyString = req.requestBody.tostring();
        mainWrapperReq requestWrapper = (mainWrapperReq)JSON.deserialize(requestBodyString, mainWrapperReq.class);
        system.debug('requestWrapper'+requestWrapper.RatePlans.RatePlan[0].HotelRef.HotelCode);
        
        if(requestWrapper.RatePlans.RatePlan[0].HotelRef.HotelCode != null && requestWrapper.RatePlans.RatePlan[0].HotelRef.HotelCode != ''){
            List<Deal__c> hotelList = [Select id, Hotel_Code__c from Deal__c where Hotel_Code__c =: requestWrapper.RatePlans.RatePlan[0].HotelRef.HotelCode and RecordType.Name = 'Hotel' and Channel_Partner__c ='TravelClick']; 
            system.debug('hotelList125'+hotelList);
            if(hotelList.isEmpty()){               
                TravelClick_OTAConnect_Errors__mdt  invalidHotelCodeError = [Select id, Code__c , Short_Text__c , Type__c, Error_Message__c  from TravelClick_OTAConnect_Errors__mdt where DeveloperName = 'Invalid_Hotel'];
                Errors errorsInstance = new Errors();
                Error errorD = new Error();
                errorD.errorType = integer.valueOf(invalidHotelCodeError.Type__c);
                errorD.Code = integer.valueOf(invalidHotelCodeError.Code__c);
                errorD.ShortText = invalidHotelCodeError.Short_Text__c;  
                errorD.errorMessage_Value =  invalidHotelCodeError.Error_Message__c +' '+requestWrapper.RatePlans.RatePlan[0].HotelRef.HotelCode;
                errorsInstance.Error = errorD;
                response.Errors = errorsInstance;        
            }else{
                
                Set<String> setOfRatePlans = new Set<String>();
                for(RatePlanCandidate RatePlanCandidateInstance : requestWrapper.RatePlans.RatePlan[0].RatePlanCandidates.RatePlanCandidate){
                    setOfRatePlans.add(RatePlanCandidateInstance.RatePlanCode);
                }
                
                if(!setOfRatePlans.isEmpty()){
                    List<sub_options__c> listOfRoomTypes = [Select id, Hotel_Code__c, Rate_Plan__r.Rate_Plan_Description__c, Rate_Plan__r.Name, Rate_Plan__r.Rate_Plan_Code__c, Room_Type_Code__c, Room_Type_Description__c, Room_Type_Name__c,Rate_Plan_Code__c from sub_options__c where Deal__c  =: hotelList[0].Id and Rate_Plan_Code__c in:setOfRatePlans];
                     system.debug('listOfRoomTypes144'+listOfRoomTypes);
                    if(listOfRoomTypes.isEmpty()){
                        TravelClick_OTAConnect_Errors__mdt  invalidRoomType = [Select id, Code__c , Short_Text__c , Type__c from TravelClick_OTAConnect_Errors__mdt where DeveloperName = 'Invalid_Room_Type'];       
                        Errors errorsInstance = new Errors();
                        Error errorD = new Error();
                        errorD.errorType = integer.valueOf(invalidRoomType.Type__c);
                        errorD.Code = integer.valueOf(invalidRoomType.Code__c);
                        errorD.ShortText = invalidRoomType.Short_Text__c;
                        errorD.errorMessage_Value = 'No rooms have been found to exist under the Hotel Code: '+requestWrapper.RatePlans.RatePlan[0].HotelRef.HotelCode;
                        errorsInstance.Error = errorD;
                        response.Errors = errorsInstance; 
                    }else{
                        List<String> startDateList = requestWrapper.RatePlans.RatePlan[0].DateRange.Start.split('-');
                        List<String> endDateList = requestWrapper.RatePlans.RatePlan[0].DateRange.EndDate.split('-');
                        
                        Set<Date> datesSet = new Set<Date>();
                        Date startDateToBeSet = date.newInstance(integer.valueOf(startDateList[0]),integer.valueOf(startDateList[1]),integer.valueOf(startDateList[2])); 
                        Date endDateToBeSet = date.newInstance(integer.valueOf(endDateList[0]),integer.valueOf(endDateList[1]),integer.valueOf(endDateList[2]));
                        
                        Integer diff  = startDateToBeSet.daysBetween(endDateToBeSet);
                        Integer inclusiveDates = diff+1;
                        
                        for(integer i = 0; i<inclusiveDates;i++){
                            
                            if(datesSet.isEmpty()){
                                datesSet.add(startDateToBeSet);
                            }else{
                                datesSet.add(startDateToBeSet+i);
                            }
                        }
                        
                        List<departures_dates__c> listOfDeparturesDates = [Select id, date__c,Stop_Sell_Open_Sell__c,Close_Arrival__c,Minimum_LOS__c,sub_options__r.Room_Type_Code__c,sub_options__r.Rate_Plan_Code__c from departures_dates__c where date__c in :datesSet and sub_options__c in:listOfRoomTypes];
                        system.debug('listOfDeparturesDates'+listOfDeparturesDates.size());
                        List<Room_Rate_Detail__c> listofRoomRateDetail = [SELECT AgeQualifyingCode__c,AmountAfterTax__c,Amount__c,departures_dates__c,Id,NumberOfGuests__c,Rate_Description__c,RecordType.Name,Room_Rate_Unique_Identifier__c,departures_dates__r.Id FROM Room_Rate_Detail__c where departures_dates__c in:listOfDeparturesDates];
                        map<id,List<Room_Rate_Detail__c>> mapofDepartureDate = new map<id,List<Room_Rate_Detail__c>>();                      
                        for(Room_Rate_Detail__c rateObj:listofRoomRateDetail)
                        {
                            if(mapofDepartureDate.containsKey(rateObj.departures_dates__r.Id))
                            {
                                List<Room_Rate_Detail__c> rateList = mapofDepartureDate.get(rateObj.departures_dates__r.ID);
                                rateList.add(rateObj);
                                
                            }
                            else
                            {
                                List<Room_Rate_Detail__c> rateList = new List<Room_Rate_Detail__c>();
                                rateList.add(rateObj);
                                mapofDepartureDate.put(rateObj.departures_dates__r.Id,rateList);
                                
                            }
                        }
                        System.debug('');
                        RatePlans rateplansObj = new RatePlans();
                        rateplansObj.HotelCode= requestWrapper.RatePlans.RatePlan[0].HotelRef.HotelCode;
                        list<RatePlan> RatePlanList = new list<RatePlan>();
                        for(Date d:datesSet)
                        {
                            for(String s:setOfRatePlans)
                            {
                                RatePlan ratePlanObj = new RatePlan();
                                ratePlanObj.RatePlanCode = s;
                                ratePlanObj.Start= String.valueof(d);
                                ratePlanObj.EndDate=String.valueof(d);
                                List<Rates> RatesList = new List<Rates>();
                                Rates ratesObj = new Rates();
                                List<Rate> RateList = new List<Rate>();
                                for(departures_dates__c depDate:listOfDeparturesDates)
                                {
                                    if(depDate.sub_options__r.Rate_Plan_Code__c==s && depDate.date__c==d )
                                    {
                                        List<Room_Rate_Detail__c> RoomRateDetailList =   mapofDepartureDate.get(depDate.id);
                                        Rate rateObj = new Rate();
                                        rateObj.InvTypeCode = depDate.sub_options__r.Room_Type_Code__c;
                                        rateObj.CurrencyCode= 'AUD';
                                        BaseByGuestAmts bbgas = new  BaseByGuestAmts();
                                        List<BaseByGuestAmt> bbgaList = new List<BaseByGuestAmt>();
                                        AdditionalGuestAmounts agas = new AdditionalGuestAmounts();
                                        List<AdditionalGuestAmount> agaList = new List<AdditionalGuestAmount>();
                                        for(Room_Rate_Detail__c rrdObj : RoomRateDetailList)
                                        {
                                            if(rrdObj.RecordType.Name=='Base Guest Details')
                                            {
                                                BaseByGuestAmt bbgaObj = new BaseByGuestAmt();
                                                bbgaObj.AmountAfterTax = string.valueof(rrdObj.AmountAfterTax__c);
                                                bbgaObj.NumberOfGuests = string.valueof(rrdObj.NumberOfGuests__c);
                                                bbgaList.add(bbgaObj);
                                            }
                                            if(rrdObj.RecordType.Name=='Additional Guest Details')
                                            {
                                                AdditionalGuestAmount agaObj = new AdditionalGuestAmount();
                                                agaObj.Amount = string.valueof(rrdObj.Amount__c);
                                                agaObj.AgeQualifyingCode = string.valueof(rrdObj.AgeQualifyingCode__c);
                                                agaList.add(agaObj);
                                            }
                                        }
                                        if(bbgaList!=null)
                                        {
                                        bbgas.BaseByGuestAmt = bbgaList;
                                        rateObj.BaseByGuestAmts = bbgas;
                                        }
                                        if(agaList!=null)
                                        {
                                        agas.AdditionalGuestAmount = agaList;
                                        rateObj.AdditionalGuestAmounts=agas;
                                        }
                                        RateList.add(rateObj);
                                        
                                    }
                                    
                                    
                                }
                                
                                ratesObj.Rate = RateList;
                                RatesList.add(ratesObj);
                                ratePlanObj.Rates = RatesList;
                                if(RatesList != null)
                                {
                                RatePlanList.add(ratePlanObj);
                                }
                            }
                            
                            
                        }
                        
                        rateplansObj.RatePlan = RatePlanList;
                        
                        response.RatePlans = rateplansObj;
                    }
                }    
            } 
        }   
        return response;
    }   
}