force-app/main/default/objects/AddOn__c/AddOn__c.object-meta.xml
<CustomObject>
    <label>AddOn</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AddOns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AddOn__c/fields/AE_SB__c.field-meta.xml
<CustomField>
    <fullName>AE_SB__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AE/SB</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>AE_SB__c.Deal__c</field>
            <operation>equals</operation>
            <valueField>$Source.Deal__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AE_SB__c</referenceTo>
    <relationshipLabel>AddOns</relationshipLabel>
    <relationshipName>AddOns_AESB</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AddOn__c/fields/Airline_Upgrade__c.field-meta.xml
<CustomField>
    <fullName>Airline_Upgrade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Airline Upgrade</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>airline_upgrade__c.Deal__c</field>
            <operation>equals</operation>
            <valueField>$Source.Deal__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>airline_upgrade__c</referenceTo>
    <relationshipLabel>AddOns</relationshipLabel>
    <relationshipName>AddOns_airlineUpgrade</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AddOn__c/fields/land_activity__c.field-meta.xml
<CustomField>
    <fullName>land_activity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>land activity</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Value does not exist or does not match filter criteria LA Deal</errorMessage>
        <filterItems>
            <field>land_activity__c.Deal__c</field>
            <operation>equals</operation>
            <valueField>$Source.Deal__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>land_activity__c</referenceTo>
    <relationshipLabel>AddOns</relationshipLabel>
    <relationshipName>AddOns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AddOn__c/fields/Order_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Order_Line_Item__c</fullName>
    <label>Order Line Item</label>
    <referenceTo>order_line_item__c</referenceTo>
    <relationshipLabel>AddOns</relationshipLabel>
    <relationshipName>AddOns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AddOn__c/fields/ordexp_new_aesb_date__c.field-meta.xml
<CustomField>
    <fullName>ordexp_new_aesb_date__c</fullName>
    <inlineHelpText>The arrival date you select is the date the customer will depart from their departure city. It is NOT the date they are arriving at their first destination</inlineHelpText>
    <label>New AE/SB Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AddOn__c/fields/Sub_Stopover__c.field-meta.xml
<CustomField>
    <fullName>Sub_Stopover__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stopover</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>sub_stopover__c.Deal__c</field>
            <operation>equals</operation>
            <valueField>$Source.Deal__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>sub_stopover__c</referenceTo>
    <relationshipLabel>AddOns</relationshipLabel>
    <relationshipName>AddOns_subStopover</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AE_SB__c/AE_SB__c.object-meta.xml
<CustomObject>
    <label>AE/SB</label>
    <nameField>
        <label>AE/SB Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AE/SB</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/airline_upgrade__c/airline_upgrade__c.object-meta.xml
<CustomObject>
    <label>airline upgrade</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>airline upgrade</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/customer_POE__c/customer_POE__c.object-meta.xml
<CustomObject>
    <label>Passengers</label>
    <nameField>
        <displayFormat>PIF-{00000000}</displayFormat>
        <label>id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/customer_POE__c/fields/last_name__c.field-meta.xml
<CustomField>
    <fullName>last_name__c</fullName>
    <label>Last Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/customer_POE__c/fields/Order_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Order_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Line Item</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>order_line_item__c.ordexp_TAD_Order__c</field>
            <operation>equals</operation>
            <valueField>$Source.ordexp_tad_order__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>order_line_item__c</referenceTo>
    <relationshipLabel>Passengers</relationshipLabel>
    <relationshipName>Passengers_POE</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/land_activity__c/land_activity__c.object-meta.xml
<CustomObject>
    <label>land activity</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>land activity</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/order_line_item__c/order_line_item__c.object-meta.xml
<CustomObject>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>OLI-{000000}</displayFormat>
        <label>Order Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/order_line_item__c/fields/ordexp_departure_date__c.field-meta.xml
<CustomField>
    <fullName>ordexp_departure_date__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Note :- For Stay type Orders, change to Departure Date will be applied to all the OLIs of this Order</inlineHelpText>
    <label>Departure date</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>departures_dates__c.sub_options__c</field>
            <operation>equals</operation>
            <valueField>$Source.Sub_Options__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>departures_dates__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/order_line_item__c/fields/ordexp_Options__c.field-meta.xml
<CustomField>
    <fullName>ordexp_Options__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Options</label>
    <referenceTo>options__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/order_line_item__c/fields/Sub_Options__c.field-meta.xml
<CustomField>
    <fullName>Sub_Options__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Note :-  For Stay type Orders, change to Sub-Option will be applied to all the OLIs of this Order</inlineHelpText>
    <label>Sub Options</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>sub_options__c.options__c</field>
            <operation>equals</operation>
            <valueField>$Source.ordexp_Options__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>sub_options__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sub_options__c/sub_options__c.object-meta.xml
<CustomObject>
    <label>Sub Options</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/sub_stopover__c/sub_stopover__c.object-meta.xml
<CustomObject>
    <label>sub stopover</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>sub stopover</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TAD_Order__c/TAD_Order__c.object-meta.xml
<CustomObject>
    <label>TAD Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TAD Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TAD_Order__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <formula>ordexp_account__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Last Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_amount_outstanding__c.field-meta.xml
<CustomField>
    <fullName>ordexp_amount_outstanding__c</fullName>
    <formula>(ordexp_nett_amount__c + TAD_Surcharge_Amount__c + ordexp_Date_City_Change_Refund__c) - (ordexp_total_payment_received__c + ( IF( Old_Credit_orders__c=true, Total_Credit_Amount__c,0 ) ) - ordexp_total_refund_amount__c - Total_Coupon_Amount__c -  
( IF( RecordType_Name__c  == &apos;Hotel&apos;, Total_QFF_Refund__c,0 ) ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount outstanding</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_Date_City_Change_Refund__c.field-meta.xml
<CustomField>
    <fullName>ordexp_Date_City_Change_Refund__c</fullName>
    <label>Date/City Change Refund</label>
    <summarizedField>Cancellation_Refund_POE__c.Total_Cancellation_Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Cancellation_Refund_POE__c.Cancellation_Type__c</field>
        <operation>equals</operation>
        <value>Departure date change, Departure city change</value>
    </summaryFilterItems>
    <summaryForeignKey>Cancellation_Refund_POE__c.ordexp_tad_order__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_departure_date__c.field-meta.xml
<CustomField>
    <fullName>ordexp_departure_date__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Departure date</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>(1 OR 2) AND 3</booleanFilter>
        <filterItems>
            <field>departures_dates__c.Deal__c</field>
            <operation>equals</operation>
            <valueField>$Source.ordexp_deal__c</valueField>
        </filterItems>
        <filterItems>
            <field>departures_dates__c.options__c</field>
            <operation>equals</operation>
            <valueField>$Source.ordexp_option__c</valueField>
        </filterItems>
        <filterItems>
            <field>departures_dates__c.online_status__c</field>
            <operation>equals</operation>
            <value>Online</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>departures_dates__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>TAD_Orders_DD</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_option__c.field-meta.xml
<CustomField>
    <fullName>ordexp_option__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Option</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>options__c.Deal__c</field>
            <operation>equals</operation>
            <valueField>$Source.ordexp_deal__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>options__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>TAD_Orders_Options</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MobileAppTADOrderUpdationv2.cls
@RestResource(urlmapping='/settingAppTADOrderUpdationv2')
global class MobileAppTADOrderUpdationv2 {
    
    global class mainWrapper{
        global String orderid{get;set;}
        global String departureDateId{get;set;}
        global String optionsId{get;set;}
        global list<OLI> oliList{get;set;}
    }
	global class globWrapper{
        global list<mainWrapper> mainWrapper{get;set;}
        
        //New attributes as per Elmin's request, also check an 
        global string appSessionCode {get;set;}
        global string accountSFId {get;set;}
    }
    global class OLI{
        global string oliId{get;set;}
        //global string orderId{get;set;}
        // global string optionsId{get;set;}
        //  global string dealId{get;set;}
        global string subOptionId{get;set;}
        global string quantity{get;set;}
        global string PaxQuantity{get;set;}
        global boolean isContainsAESB{get;set;}
        global string travelType{get;set;}
        global string departureCitiesId{get;set;}
        global string departureDateId{get;set;}
        global list<Passanger> PassangerList{get;set;}
        
    }
    
    global class Passanger{
        global string ID{get;set;}
        global string lastName{get;set;}
        //global string orderId{get;set;}
        // global string oliId{get;set;}
        global list<AddOn> AddOnList{get;set;}
        
    }
    global class AddOn{
        global string ID{get;set;}
        global String addonOptionId{get;set;}
        global String typeOfAddon{get;set;}
        global String AddonName{get;set;}
        global Date aesbDate{get;set;}
        
    }
    
    global class ResponseStructure{
        global string tadOrderId {get;set;}
        global string tadOrderNumber {get;set;}
        global string tadOrderCurrencyCode {get;set;}
        global decimal tadOrderOutstandingAmount {get;set;}
        global decimal tadOrderDepDateCityChangeRefundAmount {get;set;}
        global string errorMessage{get;set;}
        global Boolean isSuccess {get;set;}
    }
    
    @HttpPost
    global static List<ResponseStructure> createAddon(globWrapper UpdationData)
    {	
        List<Tad_Order__c> orderList = new List<Tad_Order__c>();
        List<Order_Line_Item__c> OLIList = new List<Order_Line_Item__c>();
        List<AddOn__c> addonList=new List<AddOn__c>();
        List<customer_POE__c> pessList=new List<customer_POE__c>();
        ResponseStructure responseInstance = new ResponseStructure();
        List<ResponseStructure> listOfTadOrderAmountDetails = new List<ResponseStructure>();
        Boolean proceed = false;
        
        List<Account> actList = [Select id, firstname, lastname, app_session__c from Account 
                                 where Id =:UpdationData.accountSFId Limit 1];
        
        if(!actList.isEmpty() && (actList[0].app_session__c == UpdationData.appSessionCode)){
            proceed = true;
        }
        
        if(proceed==true){
           // Savepoint sp=database.setSavepoint();
        Savepoint sp = Database.setSavepoint();
        try{
            for(mainWrapper mw:UpdationData.mainWrapper)
            {
                Tad_Order__c order = new Tad_Order__c();
                order.ordexp_departure_date__c = mw.departureDateId;
                order.ordexp_option__c = mw.optionsId;
                order.Id = mw.orderid;
                orderList.add(order);
                if(mw.oliList!=null)
                {
                    for(OLI o:mw.oliList)
                    {
                        Order_Line_Item__c oli = new Order_Line_Item__c();
                        oli.ordexp_Options__c = mw.optionsId;
                        oli.Sub_Options__c = o.subOptionId;
                        oli.ordexp_departure_date__c = mw.departureDateId;
                        //oli.ordexp_departure_date__c = o.departureDateId;
                        oli.Id = o.oliId;
                        system.debug('OLI ID Line 75'+ o.oliId);
                        if(o.PassangerList!=null){
                            for(Passanger ps:o.PassangerList){
                                customer_POE__c p = new customer_POE__c();
                                p.ID = ps.Id;
                                p.last_name__c=ps.lastName;
                                pessList.add(p);
                                
                                if(ps.AddOnList!=null){
                                    for(AddOn Aon:ps.AddOnList)
                                    {
                                        
                                        AddOn__c addonObj = new AddOn__c();
                                        addonObj.ID = Aon.Id;
                                        if(Aon.typeOfAddon=='Airline Upgrade')
                                        {
                                            addonObj.Airline_Upgrade__c = Aon.addonOptionId;
                                        }
                                        if(Aon.typeOfAddon=='Land Activity')
                                        {
                                            addonObj.land_activity__c = Aon.addonOptionId;
                                        }    
                                        if(Aon.typeOfAddon=='Stop Over')
                                        {
                                            // system.debug('Stop Over'+Aon.typeOfAddon);
                                            addonObj.Sub_Stopover__c = Aon.addonOptionId;
                                        } 
                                        if(Aon.typeOfAddon=='Arrive Early' || Aon.typeOfAddon=='Stay Behind' || Aon.typeOfAddon=='AE/SB')
                                        {
                                            
                                            //addonObj.AE_SB__r.City__c = Aon.AddonName ;
                                            addonObj.ordexp_new_aesb_date__c = Aon.aesbDate ;
                                            addonObj.AE_SB__c = Aon.addonOptionId;
                                        }  
                                        addonList.add(addonObj);
                                    }}
                                
                                
                            }}
                        
                        OLIList.add(oli);  
                    }
                }
            }
            
            
            
            if(orderList!=null)
            {
                update orderList;
            }
            if(OLIList!=null)
            {
                update OLIList;
            } 
            if(pessList!=null)
            {
                update pessList;
            }
            if(addonList!=null)
            {
                update addonList;
            }
            system.debug('orderList line 151 '+orderList);
            List<Tad_Order__c> listOfTadOrders = [Select id, Name, CurrencyIsoCode, ordexp_amount_outstanding__c, ordexp_Date_City_Change_Refund__c from TAD_Order__c where id in:orderList];
            
            
            
            for(Tad_Order__c order : listOfTadOrders){
                
                responseInstance.tadOrderId = order.Id;
                responseInstance.tadOrderNumber = order.Name;
                responseInstance.tadOrderCurrencyCode = order.CurrencyIsoCode;
                responseInstance.tadOrderOutstandingAmount = order.ordexp_amount_outstanding__c;
                if(responseInstance.tadOrderOutstandingAmount<0){
                    responseInstance.tadOrderDepDateCityChangeRefundAmount = order.ordexp_amount_outstanding__c*(-1);
                    
                }
                
                else{
                    responseInstance.tadOrderDepDateCityChangeRefundAmount  =0;
                }
                
            }
        }
        catch(exception e)
        {	
            if(string.valueof(e).contains('Requested Allocation are not available')){
                responseInstance.errorMessage='Requested Allocation are not available';  
            }else{
                responseInstance.errorMessage=string.valueof(e);   
            } 
            system.debug('Exception Occured line 171'+e);
            Database.RollBack(sp);
            // Database.rollback(sp);
        } 
            responseInstance.isSuccess = true;
            listOfTadOrderAmountDetails.add(responseInstance);
        	system.debug('listOfTadOrderAmountDetails'+listOfTadOrderAmountDetails);
            
        }else{
            responseInstance.isSuccess = false;
            responseInstance.errorMessage = 'Please try to Login again!';
        }
        return listOfTadOrderAmountDetails;
    }
}