force-app/main/default/objects/AddOn__c/AddOn__c.object-meta.xml
<CustomObject>
    <label>AddOn</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AddOns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AddOn__c/fields/AddOn_Status__c.field-meta.xml
<CustomField>
    <fullName>AddOn_Status__c</fullName>
    <label>AddOn Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On Hold</fullName>
                <default>true</default>
                <label>On Hold</label>
            </value>
            <value>
                <fullName>Secured</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AddOn__c/fields/Order_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Order_Line_Item__c</fullName>
    <label>Order Line Item</label>
    <referenceTo>order_line_item__c</referenceTo>
    <relationshipLabel>AddOns</relationshipLabel>
    <relationshipName>AddOns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/order_line_item__c/order_line_item__c.object-meta.xml
<CustomObject>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>OLI-{000000}</displayFormat>
        <label>Order Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/order_line_item__c/fields/OLI_Status__c.field-meta.xml
<CustomField>
    <fullName>OLI_Status__c</fullName>
    <label>OLI Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On Hold</fullName>
                <default>true</default>
                <label>On Hold</label>
            </value>
            <value>
                <fullName>Secured</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/order_line_item__c/fields/ordexp_TAD_Order__c.field-meta.xml
<CustomField>
    <fullName>ordexp_TAD_Order__c</fullName>
    <label>Order</label>
    <referenceTo>TAD_Order__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items_orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/TAD_Order__c.object-meta.xml
<CustomObject>
    <label>TAD Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TAD Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_master_status__c.field-meta.xml
<CustomField>
    <fullName>ordexp_master_status__c</fullName>
    <label>Master status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
                <default>true</default>
                <label>On Hold</label>
            </value>
            <value>
                <fullName>Temporary Hold</fullName>
            </value>
            <value>
                <fullName>Secured</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Travelled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>In Progress-Cruise only</fullName>
                <isActive>false</isActive>
                <label>In Progress-Cruise only</label>
            </value>
            <value>
                <fullName>In Progress-Flight only</fullName>
                <isActive>false</isActive>
                <label>In Progress-Flight only</label>
            </value>
            <value>
                <fullName>In Progress-Flights + Cruise</fullName>
                <isActive>false</isActive>
                <label>In Progress-Flights + Cruise</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/batchValidateAddonStatus.cls
global class batchValidateAddonStatus implements Database.Batchable<sObject> {

    global Database.QueryLocator start(Database.BatchableContext bc){
         return Database.getQueryLocator([Select id,AddOn_Status__c,Order_Line_Item__c,order_line_item__r.OLI_Status__c,Order_Line_Item__r.ordexp_TAD_Order__r.ordexp_master_status__c from AddOn__c WHERE ((AddOn_Status__c != 'Secured' AND Order_Line_Item__r.OLI_Status__c = 'Secured') OR 
                                          (AddOn_Status__c != 'Active' AND Order_Line_Item__r.OLI_Status__c = 'Active') OR (AddOn_Status__c != 'Cancelled' AND Order_Line_Item__r.OLI_Status__c = 'Cancelled'))  and AddOn_Status__c!='Cancelled' AND Order_Line_Item__r.ordexp_TAD_Order__r.ordexp_master_status__c!='On Hold' ]);
    }
    
    global void execute(Database.BatchableContext bc,List<AddOn__c> scope){
        List<AddOn__c>  addUpdate = new List<AddOn__c> ();
        
        for(AddOn__c addOn : scope ){
  
            if(/*addOn.Order_Line_Item__r.ordexp_TAD_Order__r.ordexp_master_status__c == 'Secured' && */addOn.Order_Line_Item__r.OLI_Status__c == 'Secured' &&  addOn.AddOn_Status__c!='Cancelled'){
                addOn.AddOn_Status__c = 'Secured';
                addUpdate.add(addOn);
            }
            else if(/*addOn.Order_Line_Item__r.ordexp_TAD_Order__r.ordexp_master_status__c == 'In Progress' && */addOn.Order_Line_Item__r.OLI_Status__c == 'Active' &&  addOn.AddOn_Status__c!='Cancelled'){
                addOn.AddOn_Status__c = 'Active';
                addUpdate.add(addOn);
            }
            else if(/*addOn.Order_Line_Item__r.ordexp_TAD_Order__r.ordexp_master_status__c == 'Cancelled' &&*/ addOn.Order_Line_Item__r.OLI_Status__c == 'Cancelled' &&  addOn.AddOn_Status__c!='Cancelled'){
                addOn.AddOn_Status__c = 'Cancelled';
                addUpdate.add(addOn);
            }
            system.debug('AddOn Status '+addOn.AddOn_Status__c);
        }
        
        update addUpdate;
        
    }
    
    global void finish(Database.BatchableContext BC) {}
}