force-app/main/default/objects/AddOn__c/AddOn__c.object-meta.xml
<CustomObject>
    <label>AddOn</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AddOns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AddOn__c/fields/AddOn_Status__c.field-meta.xml
<CustomField>
    <fullName>AddOn_Status__c</fullName>
    <label>AddOn Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On Hold</fullName>
                <default>true</default>
                <label>On Hold</label>
            </value>
            <value>
                <fullName>Secured</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AddOn__c/fields/Credit_Utilized__c.field-meta.xml
<CustomField>
    <fullName>Credit_Utilized__c</fullName>
    <label>Credit Utilized</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AddOn__c/fields/Order_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Order_Line_Item__c</fullName>
    <label>Order Line Item</label>
    <referenceTo>order_line_item__c</referenceTo>
    <relationshipLabel>AddOns</relationshipLabel>
    <relationshipName>AddOns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AddOn__c/fields/ordexp_amount__c.field-meta.xml
<CustomField>
    <fullName>ordexp_amount__c</fullName>
    <label>Amount</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/order_line_item__c/order_line_item__c.object-meta.xml
<CustomObject>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>OLI-{000000}</displayFormat>
        <label>Order Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/order_line_item__c/fields/Credit_Utilized__c.field-meta.xml
<CustomField>
    <fullName>Credit_Utilized__c</fullName>
    <label>Credit Utilized</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/order_line_item__c/fields/Deal_ID_Title__c.field-meta.xml
<CustomField>
    <fullName>Deal_ID_Title__c</fullName>
    <formula>Deal__r.Deal_ID_Title__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Deal ID Title</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/order_line_item__c/fields/Dep_Date__c.field-meta.xml
<CustomField>
    <fullName>Dep_Date__c</fullName>
    <formula>ordexp_departure_date__r.date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Dep Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/order_line_item__c/fields/HSS_Amount__c.field-meta.xml
<CustomField>
    <fullName>HSS_Amount__c</fullName>
    <formula>on_hss_amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>HSS Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/order_line_item__c/fields/OLI_Status__c.field-meta.xml
<CustomField>
    <fullName>OLI_Status__c</fullName>
    <label>OLI Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On Hold</fullName>
                <default>true</default>
                <label>On Hold</label>
            </value>
            <value>
                <fullName>Secured</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/order_line_item__c/fields/ordexp_city_surcharge_amount__c.field-meta.xml
<CustomField>
    <fullName>ordexp_city_surcharge_amount__c</fullName>
    <formula>IF(ordexp_orderRT__c=&apos;TAD&apos; || ordexp_orderRT__c=&apos;TC&apos;,  Departure_cities__r.Surcharge__c,  IF(ordexp_orderRT__c=&apos;TNZ&apos; || ordexp_orderRT__c=&apos;WT&apos;, Departure_cities__r.surcharge_nz__c , 0) ) * PAX_Qty__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>City Surcharge Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/order_line_item__c/fields/ordexp_suboption_amount__c.field-meta.xml
<CustomField>
    <fullName>ordexp_suboption_amount__c</fullName>
    <formula>IF(ordexp_orderRT__c=&apos;TAD&apos; || ordexp_orderRT__c=&apos;TC&apos;,  General_Pricing__r.Price_AUD__c * VALUE( TEXT(Quantity__c) ),  IF(ordexp_orderRT__c=&apos;TNZ&apos; || ordexp_orderRT__c=&apos;WT&apos;,  General_Pricing__r.Price_NZD__c* VALUE(TEXT(Quantity__c)) , 0) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Suboption Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/order_line_item__c/fields/ordexp_TAD_Order__c.field-meta.xml
<CustomField>
    <fullName>ordexp_TAD_Order__c</fullName>
    <label>Order</label>
    <referenceTo>TAD_Order__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items_orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/order_line_item__c/fields/Total_surcharge__c.field-meta.xml
<CustomField>
    <fullName>Total_surcharge__c</fullName>
    <formula>IF(ordexp_orderRT__c=&apos;TAD&apos; || ordexp_orderRT__c=&apos;TC&apos; , IF(TEXT(Pricing_Model__c ) = &apos;Solo&apos;, General_Pricing__r.Solo_Surcharge_AUD__c, 0),  
  IF(ordexp_orderRT__c=&apos;TNZ&apos; || ordexp_orderRT__c=&apos;WT&apos;, IF(TEXT(Pricing_Model__c ) = &apos;Solo&apos;, General_Pricing__r.Solo_Surcharge_NZD__c, 0), 0) ) 
* PAX_Qty__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Surcharge</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/TAD_Order__c.object-meta.xml
<CustomObject>
    <label>TAD Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TAD Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_master_status__c.field-meta.xml
<CustomField>
    <fullName>ordexp_master_status__c</fullName>
    <label>Master status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
                <default>true</default>
                <label>On Hold</label>
            </value>
            <value>
                <fullName>Temporary Hold</fullName>
            </value>
            <value>
                <fullName>Secured</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Travelled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>In Progress-Cruise only</fullName>
                <isActive>false</isActive>
                <label>In Progress-Cruise only</label>
            </value>
            <value>
                <fullName>In Progress-Flight only</fullName>
                <isActive>false</isActive>
                <label>In Progress-Flight only</label>
            </value>
            <value>
                <fullName>In Progress-Flights + Cruise</fullName>
                <isActive>false</isActive>
                <label>In Progress-Flights + Cruise</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_status_check__c.field-meta.xml
<CustomField>
    <fullName>ordexp_status_check__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field especially created for Order Status Updation</description>
    <label>Status Check</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/Total_Credit_Remaining__c.field-meta.xml
<CustomField>
    <fullName>Total_Credit_Remaining__c</fullName>
    <formula>Total_Credit_Amount__c  -  Total_Credit_Utilized__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Credit Remaining</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/batchValidateOLIAddonStatus.cls
global class batchValidateOLIAddonStatus implements Database.Batchable<sObject> {
    
    global Database.QueryLocator start(Database.BatchableContext bc){
        
        if(test.isRunningTest()){
            return Database.getQueryLocator([select id, Deal_ID_Title__c,ordexp_suboption_amount__c,Total_surcharge__c,HSS_Amount__c,ordexp_city_surcharge_amount__c,Credit_Utilized__c,ordexp_TAD_Order__r.Total_Credit_Remaining__c,ordexp_TAD_Order__c,ordexp_TAD_Order__r.ordexp_status_check__c, ordexp_TAD_Order__r.ordexp_master_status__c,OLI_Status__c,(Select id,AddOn_Status__c,ordexp_amount__c,Credit_Utilized__c  from AddOns__r) from order_line_item__c where ((OLI_Status__c='On Hold' and (ordexp_TAD_Order__r.ordexp_master_status__c ='Secured' or ordexp_TAD_Order__r.ordexp_master_status__c ='In Progress' )) or (OLI_Status__c='Secured' and ordexp_TAD_Order__r.ordexp_master_status__c ='In Progress') or (OLI_Status__c!='Cancelled' and ordexp_TAD_Order__r.ordexp_master_status__c ='Cancelled')) ]);
            
        }else{
            return Database.getQueryLocator([select id, Deal_ID_Title__c,ordexp_suboption_amount__c,Total_surcharge__c,HSS_Amount__c,ordexp_city_surcharge_amount__c,Credit_Utilized__c,ordexp_TAD_Order__r.Total_Credit_Remaining__c,ordexp_TAD_Order__c,ordexp_TAD_Order__r.ordexp_status_check__c, ordexp_TAD_Order__r.ordexp_master_status__c,OLI_Status__c,(Select id,AddOn_Status__c,ordexp_amount__c,Credit_Utilized__c  from AddOns__r) from order_line_item__c where ((OLI_Status__c='On Hold' and (ordexp_TAD_Order__r.ordexp_master_status__c ='Secured' or ordexp_TAD_Order__r.ordexp_master_status__c ='In Progress' )) or (OLI_Status__c='Secured' and ordexp_TAD_Order__r.ordexp_master_status__c ='In Progress') or (OLI_Status__c!='Cancelled' and ordexp_TAD_Order__r.ordexp_master_status__c ='Cancelled')) and Dep_Date__c > today  ]);
            
        }
    }
    
    global void execute(Database.BatchableContext bc,List<order_line_item__c> scope){
        
        order_line_item__c oliRec = scope[0];
        Decimal totalCreditRemaining = oliRec.ordexp_TAD_Order__r.Total_Credit_Remaining__c;
        TAD_Order__c  tadRec = new TAD_Order__c();
        tadRec.id= oliRec.ordexp_TAD_Order__c;
        if(oliRec.ordexp_TAD_Order__r.ordexp_status_check__c == true){
            tadRec.ordexp_status_check__c=false; 
        }else{
            tadRec.ordexp_status_check__c=true;
        }
        update tadRec;
        
        order_line_item__c oliUpdate = new order_line_item__c();
        List<AddOn__c>  addUpdate = new List<AddOn__c> ();
        
        oliUpdate.id=oliRec.id;
        TAD_Order__c getTadOrder = [Select id,ordexp_master_status__c from TAD_Order__c where id =:tadRec.id];
        
        if(getTadOrder.ordexp_master_status__c=='Secured'){
            if(totalCreditRemaining >= (oliRec.ordexp_suboption_amount__c+oliRec.Total_surcharge__c+oliRec.HSS_Amount__c +oliRec.ordexp_city_surcharge_amount__c) && oliRec.OLI_Status__c == 'On Hold'){
                oliUpdate.Credit_Utilized__c = (oliRec.Credit_Utilized__c!=null?oliRec.Credit_Utilized__c:0) + oliRec.ordexp_suboption_amount__c+oliRec.Total_surcharge__c+oliRec.HSS_Amount__c +oliRec.ordexp_city_surcharge_amount__c;
                totalCreditRemaining = totalCreditRemaining - (oliRec.ordexp_suboption_amount__c+oliRec.Total_surcharge__c+oliRec.HSS_Amount__c +oliRec.ordexp_city_surcharge_amount__c);
            }
            oliUpdate.OLI_Status__c='Secured';
            for(AddOn__c add :oliRec.AddOns__r ){
                if(totalCreditRemaining >= add.ordexp_amount__c && add.AddOn_Status__c == 'On Hold'){
                    add.Credit_Utilized__c = (add.Credit_Utilized__c!=null?add.Credit_Utilized__c:0) + add.ordexp_amount__c;
                    totalCreditRemaining = totalCreditRemaining - add.ordexp_amount__c;
                }
               add.AddOn_Status__c='Secured';
                addUpdate.add(add);
            }
        }else if(getTadOrder.ordexp_master_status__c=='In Progress'){
            oliUpdate.OLI_Status__c='Active';
            for(AddOn__c add :oliRec.AddOns__r ){
                add.AddOn_Status__c='Active';
                addUpdate.add(add);
            }
        }else if(getTadOrder.ordexp_master_status__c=='Cancelled'){
            oliUpdate.OLI_Status__c='Cancelled';
            for(AddOn__c add :oliRec.AddOns__r ){
                add.AddOn_Status__c='Cancelled';
                addUpdate.add(add);
            }
        }
        
        update oliUpdate;
        update addUpdate;
    }
    
    global void finish(Database.BatchableContext BC) {
        
    }
}