force-app/main/default/objects/AddOn__c/AddOn__c.object-meta.xml
<CustomObject>
    <label>AddOn</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AddOns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AddOn__c/fields/Order_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Order_Line_Item__c</fullName>
    <label>Order Line Item</label>
    <referenceTo>order_line_item__c</referenceTo>
    <relationshipLabel>AddOns</relationshipLabel>
    <relationshipName>AddOns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AddOn__c/fields/Pricing_Model__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Model__c</fullName>
    <label>Pricing Model</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Solo</fullName>
            </value>
            <value>
                <fullName>Twin</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AddOn__c/fields/Sub_Stopover__c.field-meta.xml
<CustomField>
    <fullName>Sub_Stopover__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stopover</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>sub_stopover__c.Deal__c</field>
            <operation>equals</operation>
            <valueField>$Source.Deal__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>sub_stopover__c</referenceTo>
    <relationshipLabel>AddOns</relationshipLabel>
    <relationshipName>AddOns_subStopover</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AddOn__c/recordTypes/Land_Activity.recordType-meta.xml
<RecordType>
    <fullName>Land_Activity</fullName>
    <active>true</active>
    <label>Land Activity</label>
</RecordType>

force-app/main/default/objects/AddOn__c/recordTypes/SubStopover.recordType-meta.xml
<RecordType>
    <fullName>SubStopover</fullName>
    <active>true</active>
    <label>Stopover</label>
</RecordType>

force-app/main/default/objects/Booking_Hotel__c/Booking_Hotel__c.object-meta.xml
<CustomObject>
    <label>Booking Hotel</label>
    <nameField>
        <displayFormat>Booking Hotel-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking Hotels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking_Hotel__c/fields/TAD_Order__c.field-meta.xml
<CustomField>
    <fullName>TAD_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TAD Order</label>
    <referenceTo>TAD_Order__c</referenceTo>
    <relationshipLabel>Booking Hotels</relationshipLabel>
    <relationshipName>Booking_Hotels</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/order_line_item__c/order_line_item__c.object-meta.xml
<CustomObject>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>OLI-{000000}</displayFormat>
        <label>Order Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/order_line_item__c/fields/OLI_Status__c.field-meta.xml
<CustomField>
    <fullName>OLI_Status__c</fullName>
    <label>OLI Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On Hold</fullName>
                <default>true</default>
                <label>On Hold</label>
            </value>
            <value>
                <fullName>Secured</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/order_line_item__c/fields/orderxp_total_amount__c.field-meta.xml
<CustomField>
    <fullName>orderxp_total_amount__c</fullName>
    <formula>orderxp_addons_amount__c + ordexp_suboption_amount__c + ordexp_total_customisations_amount__c +
ordexp_city_surcharge_amount__c +ordexp_total_insurance_amount__c + ordexp_total_visa_amount__c +  Total_surcharge__c+on_hss_amount__c - ordexp_oli_CanAmount__c +  sm_Hotel_Price__c + Cruise_Upgrade__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/order_line_item__c/fields/ordexp_TAD_Order__c.field-meta.xml
<CustomField>
    <fullName>ordexp_TAD_Order__c</fullName>
    <label>Order</label>
    <referenceTo>TAD_Order__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items_orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/order_line_item__c/fields/PAX_Quantity__c.field-meta.xml
<CustomField>
    <fullName>PAX_Quantity__c</fullName>
    <label>PAX Quantity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>26</fullName>
                <isActive>false</isActive>
                <label>26</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/order_line_item__c/fields/Pricing_Model__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Model__c</fullName>
    <label>Pricing Model</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Solo</fullName>
            </value>
            <value>
                <fullName>Twin</fullName>
            </value>
            <value>
                <fullName>QTY</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TAD_Order__c/TAD_Order__c.object-meta.xml
<CustomObject>
    <label>TAD Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TAD Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TAD_Order__c/fields/Account_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Account_Email_Address__c</fullName>
    <formula>IF( RecordType.Name=&apos;TAD&apos; || RecordType.Name=&apos;TNZ&apos; || RecordType.Name=&apos;Hotel&apos;  , IF(OR(ordexp_account__r.RecordType.Name = &apos;Product Partner&apos;,ordexp_account__r.RecordType.Name = &apos;PAF Corp Client&apos;), ordexp_account__r.Company_Email__c , ordexp_account__r.PersonEmail),  IF(OR(Agency_Id__r.RecordType.Name = &apos;Product Partner&apos;,Agency_Id__r.RecordType.Name = &apos;PAF Corp Client&apos;), Agency_Id__r.Company_Email__c , Agency_Id__r.PersonEmail))</formula>
    <label>Account Email Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/Booking_Hotel__c.field-meta.xml
<CustomField>
    <fullName>Booking_Hotel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking Hotel</label>
    <referenceTo>Booking_Hotel__c</referenceTo>
    <relationshipLabel>TAD Orders</relationshipLabel>
    <relationshipName>TAD_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_account__c.field-meta.xml
<CustomField>
    <fullName>ordexp_account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>TAD Orders</relationshipLabel>
    <relationshipName>TAD_Orders_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_amount_outstanding__c.field-meta.xml
<CustomField>
    <fullName>ordexp_amount_outstanding__c</fullName>
    <formula>(ordexp_nett_amount__c + TAD_Surcharge_Amount__c + ordexp_Date_City_Change_Refund__c) - (ordexp_total_payment_received__c + ( IF( Old_Credit_orders__c=true, Total_Credit_Amount__c,0 ) ) - ordexp_total_refund_amount__c - Total_Coupon_Amount__c -  
( IF( RecordType_Name__c  == &apos;Hotel&apos;, Total_QFF_Refund__c,0 ) ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount outstanding</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_cabin_required__c.field-meta.xml
<CustomField>
    <fullName>ordexp_cabin_required__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Cabin Required</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_cabins_booked__c.field-meta.xml
<CustomField>
    <fullName>ordexp_cabins_booked__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Contains count of Cabins Booked</description>
    <label>Cabins Booked</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_deal_type__c.field-meta.xml
<CustomField>
    <fullName>ordexp_deal_type__c</fullName>
    <formula>IF(INCLUDES(ordexp_deal__r.deal_type__c , &apos;stay&apos;), &apos;Stay|&apos;,&apos;&apos;) + IF(INCLUDES(ordexp_deal__r.deal_type__c , &apos;travel&apos;), &apos;Travel|&apos;,&apos;&apos;) +  IF(INCLUDES(ordexp_deal__r.deal_type__c , &apos;Cruise&apos;),&apos;Cruise|&apos; ,&apos;&apos;) + IF(TEXT(ordexp_deal__r.Dates_Flights__c) =&apos;Dates/Domestic Flights&apos; || TEXT(ordexp_deal__r.Dates_Flights__c) =&apos;Dates/International Flights&apos;, &apos;Flight|&apos;,&apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Deal Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_master_status__c.field-meta.xml
<CustomField>
    <fullName>ordexp_master_status__c</fullName>
    <label>Master status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
                <default>true</default>
                <label>On Hold</label>
            </value>
            <value>
                <fullName>Temporary Hold</fullName>
            </value>
            <value>
                <fullName>Secured</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Travelled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>In Progress-Cruise only</fullName>
                <isActive>false</isActive>
                <label>In Progress-Cruise only</label>
            </value>
            <value>
                <fullName>In Progress-Flight only</fullName>
                <isActive>false</isActive>
                <label>In Progress-Flight only</label>
            </value>
            <value>
                <fullName>In Progress-Flights + Cruise</fullName>
                <isActive>false</isActive>
                <label>In Progress-Flights + Cruise</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/Override_Pricing_Model__c.field-meta.xml
<CustomField>
    <fullName>Override_Pricing_Model__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Override Pricing Model</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/RecordType_Name__c.field-meta.xml
<CustomField>
    <fullName>RecordType_Name__c</fullName>
    <formula>RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Record Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/recordTypes/Hotel.recordType-meta.xml
<RecordType>
    <fullName>Hotel</fullName>
    <active>true</active>
    <description>Used for Expedia Bookings</description>
    <label>Hotel</label>
</RecordType>

force-app/main/default/objects/TAD_Order__c/recordTypes/TAD.recordType-meta.xml
<RecordType>
    <fullName>TAD</fullName>
    <active>true</active>
    <label>TAD</label>
</RecordType>

force-app/main/default/objects/TAD_Order__c/recordTypes/TC.recordType-meta.xml
<RecordType>
    <fullName>TC</fullName>
    <active>true</active>
    <label>TC</label>
</RecordType>

force-app/main/default/classes/TAD_ValidateOrderController.cls
/**
* @description - This Method validates the Twin Pricing Model Logic on TAD Order
* @author - Samrat M. (PSAG)
* @createdOn - 07-Nov-2019
* @modifiedOn -
* @modifiedBy
*/
public class TAD_ValidateOrderController {
    
    //Wrapper to be used for Display
    public class ValidateOrderWrapper
    {
        @auraEnabled
        public Boolean status {get;set;}
        @auraEnabled
        public String recordType {get;set;}
        @auraEnabled
        public String email {get;set;}
        @auraEnabled
        public String Name {get;set;}
    }
    
    
    /** This Method would validate Pricing for TWIN addons on TAD Order page  ***
* @param : String id -> TAD_ORDER ID
* @returnType : ValidateOrderWrapper  
* *********************/
    @auraEnabled
    public static ValidateOrderWrapper validateOrder(String id)
    {
        TAD_Order__c orders = [Select Account_Email_Address__c, ordexp_account__r.Name,RecordType_Name__c from TAD_Order__c  where Id =: id];
        //String landActRCT = Schema.SObjectType.Addon__c.getRecordTypeInfosByDeveloperName().get(Label.Land_Activity).getRecordTypeId();
        String subStopRCT = Schema.SObjectType.Addon__c.getRecordTypeInfosByDeveloperName().get(Label.SubStopover).getRecordTypeId();
        //String rctClub = landActRCT+','+subStopRCT;
        
        ValidateOrderWrapper wrap = new ValidateOrderWrapper();
        wrap.email = orders.Account_Email_Address__c;
        wrap.Name = orders.ordexp_account__r.Name;
        wrap.recordType = orders.RecordType_Name__c;
        // System.debug('#LandRCT:'+landActRCT);
        
        List<AddOn__c >  addonData =[select id,name,recordtypeid,pricing_model__c,Sub_Stopover__c  from AddOn__c  where recordtypeid=:subStopRCT AND Pricing_Model__c='Twin' AND Order_Line_Item__r.ordexp_TAD_Order__c =:id ];
        
        Boolean subStatus=false;
        Map<String,Integer> subMap = new map<String,Integer>();
        for(AddOn__c  add : addonData){
            if(subMap.get(add.Sub_Stopover__c)==null ){
                subMap.put(add.Sub_Stopover__c,1);
            }else{
                Integer count =  subMap.get(add.Sub_Stopover__c);
                subMap.put(add.Sub_Stopover__c,count+1) ;  
            }
        }
        System.debug('subMap'+subMap);
        for(String data : subMap.keyset()){
            Integer countValue = subMap.get(data);
            if (math.mod(countValue,2)!=0){
                subStatus=true;
                break;
            }
        }
        
        if(subStatus==true)
        {
            wrap.status=true;
        }
        else
        {
            wrap.status=false;
        }
        System.debug('##Wrap:'+wrap);
        return wrap;
    }
    
    /** This Method Would Validate correct pax at OLI level based on Pricing Model
It will populate Cabin Required and Total amount at order level ***
* @param : String id -> TAD_ORDER ID
* @returnType : String  
* *********************/
    
    
    public class initWrapper{
        @AuraEnabled public string recordType{get;set;}
        @AuraEnabled public string validate{get;set;}
        @AuraEnabled public string sourceUrl{get;set;}
        @Auraenabled public string paylineURL{get;set;}
    }
    
    public class PaytoWrap{
        @AuraEnabled public string returnurl{get;set;}
         @AuraEnabled public Boolean returnStatus{get;set;}
       
    }
    
    @auraEnabled
    public static initWrapper updateOrder (Id orderId){
        
        initWrapper wrapNew = new initWrapper();
        wrapNew.validate = 'fail';
        
        Decimal Amount = 0 ;
        //String validate ='fail';
        Integer  twinPax=0;
        Integer  soloPax=0;
        Integer cabinBooking =0;
        
        TAD_Order__c order =  [Select id, Name,Booking_Hotel__c , ordexp_amount_outstanding__c, RecordType.Name from TAD_Order__c where id =: orderId];
        
        List<order_line_item__c> orderLines = [Select id ,ordexp_TAD_Order__r.RecordType_Name__c,OLI_Status__c, orderxp_total_amount__c,PAX_Quantity__c,Pricing_Model__c from order_line_item__c where ordexp_TAD_Order__c=:orderId];
        List<TAD_Order__c> orderList = [Select id,Booking_Hotel__c,recordtype.name,Override_Pricing_Model__c ,ordexp_deal_type__c,ordexp_cabin_required__c,ordexp_cabins_booked__c, ordexp_master_status__c, ordexp_sub_status__c, Secure_allocation__c from TAD_Order__c where id =: orderId LIMIT 1];
        
        for (order_line_item__c oli : orderLines){
            wrapNew.recordType = oli.ordexp_TAD_Order__r.RecordType_Name__c;
            Amount = oli.orderxp_total_amount__c + Amount;												 // Populates Total amount on TAD Order
            if(oli.Pricing_Model__c=='Twin'){
                twinPax=twinPax+integer.valueof(oli.PAX_Quantity__c);   
            }
            if(oli.Pricing_Model__c=='Solo'){
                soloPax=soloPax+integer.valueof(oli.PAX_Quantity__c); 
            }
        }
        // Added by vinti
        
        for(order_line_item__c olitem : orderLines){
            
            if(olitem.Pricing_Model__c=='Twin' && olitem.OLI_Status__c != 'Cancelled'){
                cabinBooking = cabinBooking + integer.valueof(olitem.PAX_Quantity__c)/2;        //To set the value of cabin booking outstanding
                
            }
            if((olitem.Pricing_Model__c=='Solo' || olitem.Pricing_Model__c=='QTY') && olitem.OLI_Status__c != 'Cancelled'){
                cabinBooking = cabinBooking + integer.valueof(olitem.PAX_Quantity__c);
                
            }
            
        }        
        // end by vinti
        if (math.mod(twinPax,2)==0){																 	// If OlI's are correct
            wrapNew.validate ='pass';
            
            if(order.RecordType.Name == 'TAD' || order.RecordType.Name == 'TC' || order.RecordType.Name == 'Hotel'){
                String baseUrlTADTC = System.Label.AbTest_BaseURL;
                String str = baseUrlTADTC+order.Name+'&total='+order.ordexp_amount_outstanding__c;
                wrapNew.sourceUrl = str;
            }else{
                String baseUrlTNZWT = System.Label.AbTest_BaseURL_TNZ_WT ;
                String str = baseUrlTNZWT+order.Name+'&total='+order.ordexp_amount_outstanding__c;
                wrapNew.sourceUrl = str;
            }
            
            User currentUser = [Select id, Payline_Token__c, Payline_Username__c from User where ID =: UserInfo.getUserId()];
            wrapNew.paylineURL = System.Label.Payline_Base_URL + currentUser.Payline_Username__c + System.Label.Payline_Base_URL_1 + currentUser.Payline_Token__c + System.Label.Payline_Base_URL_2 + order.Name + System.Label.Payline_Base_URL_3 + Integer.valueOf((order.ordexp_amount_outstanding__c * 100)) + System.Label.Payline_Base_URL_4;
            
            
            TAD_Order__c OrderToUpdate = new TAD_Order__c(id=orderId);
            System.debug('DealType: '+orderList[0].ordexp_deal_type__c);
            
            
            if (order.recordtype.name =='Hotel' && order.Booking_Hotel__c !=null ){
                Booking_Hotel__c booking = [Select id, Gross_Cost__c  from Booking_Hotel__c  where id =: order.Booking_Hotel__c limit 1 ];
                
                OrderToUpdate.ordexp_gross_amount__c=booking.Gross_Cost__c ;
                update OrderToUpdate;  
                
                wrapNew.validate ='pass';
            }else{
                if(orderList[0].ordexp_deal_type__c != 'Flight'){
                    OrderToUpdate.ordexp_cabin_required__c= cabinBooking;
                    OrderToUpdate.mp_Rooms_Required__c = (twinPax/2)+soloPax;
                }
                OrderToUpdate.ordexp_gross_amount__c=Amount;
                update OrderToUpdate;  
            }
            
            
        }
        
        
        //sso-74 if status= quote validation fails
        if(!orderList.isEmpty() && orderList[0].ordexp_master_status__c=='Quote' && orderList[0].ordexp_sub_status__c=='Quote Sent' && orderList[0].Secure_allocation__c==false){
            wrapNew.validate ='failQuote';
        }else{
            if(!orderList.isEmpty()){
                if(orderList[0].Override_Pricing_Model__c ==true){
                    wrapNew.validate ='pass';
                }  
            }
        }
        /*if(!orderList.isEmpty()){
if(orderList[0].Override_Pricing_Model__c ==true){
wrapNew.validate ='pass';
}  
}*/
        System.debug('wrapNew'+wrapNew);
        system.debug('wrapNew.paylineURL wrapNew.paylineURL ===> '+wrapNew.paylineURL);
        return wrapNew;
    } 
    
      @auraEnabled
     public static PaytoWrap payToOrder (Id orderId){
        
         PaytoWrap wrapNew = new PaytoWrap();
         wrapNew.returnStatus = false;
      
         TAD_Order__c order =  [Select id, Name, ordexp_amount_outstanding__c, RecordType.Name from TAD_Order__c where id =: orderId];
         if(order.ordexp_amount_outstanding__c > 0){
           wrapNew.returnStatus = true;  
           wrapNew.returnurl =  System.Label.PayToURL +'/'+ order.Name+'/'+ order.id;
         }
         else{
          wrapNew.returnurl =  ''; 
          wrapNew.returnStatus = false;  
         }
       
        return wrapNew;
    } 
   
}