force-app/main/default/objects/AddOn__c/AddOn__c.object-meta.xml
<CustomObject>
    <label>AddOn</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AddOns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AddOn__c/fields/AddOn_Name__c.field-meta.xml
<CustomField>
    <fullName>AddOn_Name__c</fullName>
    <formula>IF(Pre_Post_Stopover__c  == &apos;Pre Tour&apos;, &apos;Pre Tour Stopover - &apos;+Order_Line_Item__r.ordexp_TAD_Order__r.Name ,  IF(Pre_Post_Stopover__c  == &apos;Post Tour&apos;, &apos;Post Tour Stopover - &apos;+Order_Line_Item__r.ordexp_TAD_Order__r.Name,  Name ) )</formula>
    <label>AddOn Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AddOn__c/fields/AE_SB__c.field-meta.xml
<CustomField>
    <fullName>AE_SB__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AE/SB</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>AE_SB__c.Deal__c</field>
            <operation>equals</operation>
            <valueField>$Source.Deal__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AE_SB__c</referenceTo>
    <relationshipLabel>AddOns</relationshipLabel>
    <relationshipName>AddOns_AESB</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AddOn__c/fields/Departure_Date__c.field-meta.xml
<CustomField>
    <fullName>Departure_Date__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Departure Date</label>
    <referenceTo>departures_dates__c</referenceTo>
    <relationshipLabel>AddOns</relationshipLabel>
    <relationshipName>AddOns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AddOn__c/fields/Order_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Order_Line_Item__c</fullName>
    <label>Order Line Item</label>
    <referenceTo>order_line_item__c</referenceTo>
    <relationshipLabel>AddOns</relationshipLabel>
    <relationshipName>AddOns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AddOn__c/fields/ordexp_new_aesb_date__c.field-meta.xml
<CustomField>
    <fullName>ordexp_new_aesb_date__c</fullName>
    <inlineHelpText>The arrival date you select is the date the customer will depart from their departure city. It is NOT the date they are arriving at their first destination</inlineHelpText>
    <label>New AE/SB Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order_Customisations_POE__c/Order_Customisations_POE__c.object-meta.xml
<CustomObject>
    <description>Order Customisation 
This is a combination of additional accommodations, flight Customisations and Cruise Customisation</description>
    <label>Order Customisation</label>
    <nameField>
        <displayFormat>Customisatio-{0000}</displayFormat>
        <label>Order Customisations  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Customisations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Customisations_POE__c/fields/Order_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Order_Line_Item__c</fullName>
    <label>Order Line Item</label>
    <referenceTo>order_line_item__c</referenceTo>
    <relationshipLabel>Order Customisations</relationshipLabel>
    <relationshipName>Order_Customisations_POE</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/order_line_item__c/order_line_item__c.object-meta.xml
<CustomObject>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>OLI-{000000}</displayFormat>
        <label>Order Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/order_line_item__c/fields/Consolidated_Field__c.field-meta.xml
<CustomField>
    <fullName>Consolidated_Field__c</fullName>
    <formula>Name + &apos; | &apos; + LEFT(Sub_Options__r.Name, (LEN(Sub_Options__r.Name)-5)) + &apos; | &apos;  +TEXT(PAX_Quantity__c)   + &apos; PAX&apos; + &apos; | &apos;  +LEFT(Departure_cities__r.Name, (LEN(Departure_cities__r.Name)-5)) + &apos; - &apos; + Departure_cities__r.ordexp_pincode__c + &apos; | &apos; + TEXT(OLI_Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Consolidated Field</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/order_line_item__c/fields/orderxp_total_amount__c.field-meta.xml
<CustomField>
    <fullName>orderxp_total_amount__c</fullName>
    <formula>orderxp_addons_amount__c + ordexp_suboption_amount__c + ordexp_total_customisations_amount__c +
ordexp_city_surcharge_amount__c +ordexp_total_insurance_amount__c + ordexp_total_visa_amount__c +  Total_surcharge__c+on_hss_amount__c - ordexp_oli_CanAmount__c +  sm_Hotel_Price__c + Cruise_Upgrade__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/order_line_item__c/fields/ordexp_departure_date__c.field-meta.xml
<CustomField>
    <fullName>ordexp_departure_date__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Note :- For Stay type Orders, change to Departure Date will be applied to all the OLIs of this Order</inlineHelpText>
    <label>Departure date</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>departures_dates__c.sub_options__c</field>
            <operation>equals</operation>
            <valueField>$Source.Sub_Options__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>departures_dates__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/order_line_item__c/fields/ordexp_oli_name__c.field-meta.xml
<CustomField>
    <fullName>ordexp_oli_name__c</fullName>
    <formula>HYPERLINK(&quot;/&quot;&amp;Id, Name +&apos;--&apos;+TEXT(Departure_cities__r.city__c)+&apos;--&apos;+TEXT(PAX_Qty__c)+&apos;--&apos;+Sub_Options__r.Name, &quot;_self&quot;)</formula>
    <label>Order Line Item Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/order_line_item__c/fields/ordexp_total_customisations_amount__c.field-meta.xml
<CustomField>
    <fullName>ordexp_total_customisations_amount__c</fullName>
    <label>Total Customisations Amount</label>
    <summarizedField>Order_Customisations_POE__c.ff_Total_Price__c</summarizedField>
    <summaryFilterItems>
        <field>Order_Customisations_POE__c.Status__c</field>
        <operation>equals</operation>
        <value>Accepted and Paid, Customer Approved, Cancelled</value>
    </summaryFilterItems>
    <summaryForeignKey>Order_Customisations_POE__c.Order_Line_Item__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/TAD_Order__c.object-meta.xml
<CustomObject>
    <label>TAD Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TAD Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_amount_outstanding__c.field-meta.xml
<CustomField>
    <fullName>ordexp_amount_outstanding__c</fullName>
    <formula>(ordexp_nett_amount__c + TAD_Surcharge_Amount__c + ordexp_Date_City_Change_Refund__c) - (ordexp_total_payment_received__c + ( IF( Old_Credit_orders__c=true, Total_Credit_Amount__c,0 ) ) - ordexp_total_refund_amount__c - Total_Coupon_Amount__c -  
( IF( RecordType_Name__c  == &apos;Hotel&apos;, Total_QFF_Refund__c,0 ) ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount outstanding</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_deal_id_title__c.field-meta.xml
<CustomField>
    <fullName>ordexp_deal_id_title__c</fullName>
    <formula>ordexp_deal__r.Deal_ID_Title__c</formula>
    <label>Deal ID + Title</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_departure_date__c.field-meta.xml
<CustomField>
    <fullName>ordexp_departure_date__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Departure date</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>(1 OR 2) AND 3</booleanFilter>
        <filterItems>
            <field>departures_dates__c.Deal__c</field>
            <operation>equals</operation>
            <valueField>$Source.ordexp_deal__c</valueField>
        </filterItems>
        <filterItems>
            <field>departures_dates__c.options__c</field>
            <operation>equals</operation>
            <valueField>$Source.ordexp_option__c</valueField>
        </filterItems>
        <filterItems>
            <field>departures_dates__c.online_status__c</field>
            <operation>equals</operation>
            <value>Online</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>departures_dates__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>TAD_Orders_DD</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_master_status__c.field-meta.xml
<CustomField>
    <fullName>ordexp_master_status__c</fullName>
    <label>Master status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
                <default>true</default>
                <label>On Hold</label>
            </value>
            <value>
                <fullName>Temporary Hold</fullName>
            </value>
            <value>
                <fullName>Secured</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Travelled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>In Progress-Cruise only</fullName>
                <isActive>false</isActive>
                <label>In Progress-Cruise only</label>
            </value>
            <value>
                <fullName>In Progress-Flight only</fullName>
                <isActive>false</isActive>
                <label>In Progress-Flight only</label>
            </value>
            <value>
                <fullName>In Progress-Flights + Cruise</fullName>
                <isActive>false</isActive>
                <label>In Progress-Flights + Cruise</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_option_purchased__c.field-meta.xml
<CustomField>
    <fullName>ordexp_option_purchased__c</fullName>
    <formula>ordexp_option__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Option purchased</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_total_price__c.field-meta.xml
<CustomField>
    <fullName>ordexp_total_price__c</fullName>
    <formula>ordexp_gross_amount_final__c +  TAD_Surcharge_Amount__c</formula>
    <label>Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/total_customisation_amount__c.field-meta.xml
<CustomField>
    <fullName>total_customisation_amount__c</fullName>
    <label>Total Order Customisation</label>
    <summarizedField>order_line_item__c.ordexp_total_customisations_amount__c</summarizedField>
    <summaryForeignKey>order_line_item__c.ordexp_TAD_Order__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Visa_Insurance_POE__c/Visa_Insurance_POE__c.object-meta.xml
<CustomObject>
    <label>Visa &amp; Insurance</label>
    <nameField>
        <displayFormat>VI-{00000000}</displayFormat>
        <label>Visa &amp; Insurance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visa &amp; Insurance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Visa_Insurance_POE__c/fields/Order_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Order_Line_Item__c</fullName>
    <label>Order Line Item</label>
    <referenceTo>order_line_item__c</referenceTo>
    <relationshipLabel>Visa &amp; Insurance</relationshipLabel>
    <relationshipName>Visa_Insurance_POE</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TADOrderSummary.cls
public class TADOrderSummary {
    
    @AuraEnabled        
    public static TAD_Order__c  fetchSummary(String recId){
        List<TAD_Order__c>  tadOrder = [select name,ordexp_total_price__c , total_customisation_amount__c,ordexp_deal_id_title__c ,ordexp_option_purchased__c , ordexp_master_status__c, ordexp_amount_outstanding__c, ordexp_departure_date__r.Name from TAD_Order__c where id  = :recId]; 
        if(tadOrder!=null) {
            return tadOrder[0];
        }
        else {
         	return null;   
        }
    }
    
    @AuraEnabled        
    public static List<Order_line_item__c>  fetchOLIRec(String recId){
        List<Order_line_item__c>  oliList = [select name, ordexp_oli_name__c, orderxp_total_amount__c, Consolidated_Field__c, ordexp_total_customisations_amount__c, ordexp_departure_date__r.Name,  (Select Id, AddOn_Name__c, ordexp_AddOn_Name__c, AE_SB__c, AE_SB__r.Name, ordexp_new_aesb_date__c, Add_On_Type__c, land_activity__c, land_activity__r.name, land_activity__r.title__c,ordexp_passenger_name__c, ordexp_amount__c from AddOns__r),(Select id,Name,RecordType.Name,ordexp_passenger_name__c,Visa_Total__c,Date_Display_on_Accordian__c,Insurance_Total_TAD__c,Insurance_Sale_Price__c,Total_to_TAD__c from Visa_Insurance_POE__r), (Select id , Name, Type__c ,Requested_Details__c ,Total_Final_Cost__c from Order_Customisations_POE__r) from order_line_item__c where ordexp_TAD_Order__c  = :recId]; 
        return oliList;
        
    }

}