force-app/main/default/objects/AddOn__c/AddOn__c.object-meta.xml
<CustomObject>
    <label>AddOn</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AddOns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AddOn__c/fields/AE_SB__c.field-meta.xml
<CustomField>
    <fullName>AE_SB__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AE/SB</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>AE_SB__c.Deal__c</field>
            <operation>equals</operation>
            <valueField>$Source.Deal__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AE_SB__c</referenceTo>
    <relationshipLabel>AddOns</relationshipLabel>
    <relationshipName>AddOns_AESB</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AddOn__c/fields/Airline_Upgrade__c.field-meta.xml
<CustomField>
    <fullName>Airline_Upgrade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Airline Upgrade</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>airline_upgrade__c.Deal__c</field>
            <operation>equals</operation>
            <valueField>$Source.Deal__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>airline_upgrade__c</referenceTo>
    <relationshipLabel>AddOns</relationshipLabel>
    <relationshipName>AddOns_airlineUpgrade</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AddOn__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Deal</description>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>AddOns</relationshipLabel>
    <relationshipName>AddOns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AddOn__c/fields/land_activity__c.field-meta.xml
<CustomField>
    <fullName>land_activity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>land activity</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Value does not exist or does not match filter criteria LA Deal</errorMessage>
        <filterItems>
            <field>land_activity__c.Deal__c</field>
            <operation>equals</operation>
            <valueField>$Source.Deal__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>land_activity__c</referenceTo>
    <relationshipLabel>AddOns</relationshipLabel>
    <relationshipName>AddOns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AddOn__c/fields/Order_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Order_Line_Item__c</fullName>
    <label>Order Line Item</label>
    <referenceTo>order_line_item__c</referenceTo>
    <relationshipLabel>AddOns</relationshipLabel>
    <relationshipName>AddOns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AddOn__c/fields/ordexp_new_aesb_date__c.field-meta.xml
<CustomField>
    <fullName>ordexp_new_aesb_date__c</fullName>
    <inlineHelpText>The arrival date you select is the date the customer will depart from their departure city. It is NOT the date they are arriving at their first destination</inlineHelpText>
    <label>New AE/SB Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AddOn__c/fields/Passenger__c.field-meta.xml
<CustomField>
    <fullName>Passenger__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Passenger</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Value does not exist or does not match filter criteria Pax OLI</errorMessage>
        <filterItems>
            <field>customer_POE__c.Order_Line_Item__c</field>
            <operation>equals</operation>
            <valueField>$Source.Order_Line_Item__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>customer_POE__c</referenceTo>
    <relationshipLabel>AddOns</relationshipLabel>
    <relationshipName>AddOns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AddOn__c/fields/Sub_Stopover__c.field-meta.xml
<CustomField>
    <fullName>Sub_Stopover__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stopover</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>sub_stopover__c.Deal__c</field>
            <operation>equals</operation>
            <valueField>$Source.Deal__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>sub_stopover__c</referenceTo>
    <relationshipLabel>AddOns</relationshipLabel>
    <relationshipName>AddOns_subStopover</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AddOn__c/recordTypes/AE_SB.recordType-meta.xml
<RecordType>
    <fullName>AE_SB</fullName>
    <active>true</active>
    <label>AE/SB</label>
</RecordType>

force-app/main/default/objects/AddOn__c/recordTypes/Airline_Upgrade.recordType-meta.xml
<RecordType>
    <fullName>Airline_Upgrade</fullName>
    <active>true</active>
    <label>Airline Upgrade</label>
</RecordType>

force-app/main/default/objects/AddOn__c/recordTypes/Land_Activity.recordType-meta.xml
<RecordType>
    <fullName>Land_Activity</fullName>
    <active>true</active>
    <label>Land Activity</label>
</RecordType>

force-app/main/default/objects/AddOn__c/recordTypes/SubStopover.recordType-meta.xml
<RecordType>
    <fullName>SubStopover</fullName>
    <active>true</active>
    <label>Stopover</label>
</RecordType>

force-app/main/default/objects/AE_SB__c/AE_SB__c.object-meta.xml
<CustomObject>
    <label>AE/SB</label>
    <nameField>
        <label>AE/SB Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AE/SB</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AE_SB__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>AE/SB</relationshipLabel>
    <relationshipName>AE_SB</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/airline_upgrade__c/airline_upgrade__c.object-meta.xml
<CustomObject>
    <label>airline upgrade</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>airline upgrade</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/airline_upgrade__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>airline upgrade</relationshipLabel>
    <relationshipName>airline_upgrade</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Deal__c/Deal__c.object-meta.xml
<CustomObject>
    <label>Deal</label>
    <nameField>
        <label>Deal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/land_activity__c/land_activity__c.object-meta.xml
<CustomObject>
    <label>land activity</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>land activity</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/land_activity__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>land activity</relationshipLabel>
    <relationshipName>land_activity</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/order_line_item__c/order_line_item__c.object-meta.xml
<CustomObject>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>OLI-{000000}</displayFormat>
        <label>Order Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/order_line_item__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sub_stopover__c/sub_stopover__c.object-meta.xml
<CustomObject>
    <label>sub stopover</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>sub stopover</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sub_stopover__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>sub stopover</relationshipLabel>
    <relationshipName>sub_stopover</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MobileAppAddonCreation.cls
@RestResource(urlmapping='/settingAppAddonCreation')
global class MobileAppAddonCreation {
    
    global class mainWrapper
    {
        global String addonOptionId{get;set;}
        global String orderLineItem{get;set;}
        global String dealId{get;set;}
        global String passenger{get;set;}
        global String typeOfAddon{get;set;}
        global String depDateValue{get;set;}
        
        
    }
    
    @HttpPost
    global static list<AddOn__c> createAddon(list<mainWrapper> creationData)
    {
         List<AddOn__c> addonList = new List<AddOn__c>();
       if(creationData.size()>0)
       {
        System.debug('creationData--------'+creationData);
       set<id> ids= new set<id>();
        
        for(mainWrapper mw:creationData)
        {
            ids.add(mw.orderLineItem);
        }
         System.debug('oli ids '+ids);
           
     list<AddOn__c> addonLists=[SELECT id from AddOn__c WHERE Order_Line_Item__c=:ids];
        if(addonLists.size()>0){
            System.debug('inside del '+addonLists);
            delete addonLists;
        }
      
          if(creationData[0].typeOfAddon!=null)
      {  
        for(mainWrapper mw:creationData)
        {
            AddOn__c addon = new AddOn__c();
            addon.Order_Line_Item__c=mw.OrderLineItem; 
            addon.Passenger__c = mw.Passenger;
            addon.Deal__c = mw.DealId;
            
            if(mw.typeOfAddon =='Airline Upgrade')
            {
                addon.Airline_Upgrade__c=mw.AddonOptionId;
                
                addon.RecordTypeId=TADUtils.getRecordTypeList('Airline_Upgrade','AddOn__c');
            }
            if(mw.typeOfAddon =='Land Activity')
            {
                addon.land_activity__c=mw.AddonOptionId;
                
                addon.RecordTypeId=TADUtils.getRecordTypeList('Land_Activity','AddOn__c');
            } 
            if(mw.typeOfAddon =='Land Activity')
            {
                addon.land_activity__c=mw.AddonOptionId;
                
                addon.RecordTypeId=TADUtils.getRecordTypeList('Land_Activity','AddOn__c');
            }  
            if(mw.typeOfAddon =='Stop Over')
            {
                addon.Sub_Stopover__c=mw.AddonOptionId;
                
                addon.RecordTypeId=TADUtils.getRecordTypeList('SubStopover','AddOn__c');
            }
            if(mw.typeOfAddon =='AE')
            {
                addon.AE_SB__c=mw.AddonOptionId;
                addon.ordexp_new_aesb_date__c=date.parse(mw.depDateValue);
                
                addon.RecordTypeId=TADUtils.getRecordTypeList('AE_SB','AddOn__c');
            }  
            if(mw.typeOfAddon =='SB')
            {
                addon.AE_SB__c=mw.AddonOptionId;
                addon.ordexp_new_aesb_date__c=date.parse(mw.depDateValue);
                
                addon.RecordTypeId=TADUtils.getRecordTypeList('AE_SB','AddOn__c');
            } 
            addonList.add(addon);
            
        }
      }
        if(addonList.size()>0)
        {
      insert addonList;
      System.debug('addonList'+addonList);
        }
       }
        return addonList;
        
       
        
    }   
    
}