force-app/main/default/objects/AddOn__c/AddOn__c.object-meta.xml
<CustomObject>
    <label>AddOn</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AddOns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AddOn__c/fields/Attribution__c.field-meta.xml
<CustomField>
    <fullName>Attribution__c</fullName>
    <formula>1- (Credit_Utilized__c/ordexp_amount__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Attribution %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/AddOn__c/fields/Order_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Order_Line_Item__c</fullName>
    <label>Order Line Item</label>
    <referenceTo>order_line_item__c</referenceTo>
    <relationshipLabel>AddOns</relationshipLabel>
    <relationshipName>AddOns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CS_Attribution_POE__c/CS_Attribution_POE__c.object-meta.xml
<CustomObject>
    <label>CS Attribution</label>
    <nameField>
        <displayFormat>CSAtt-{000000}</displayFormat>
        <label>CS Attribution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CS Attribution</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CS_Attribution_POE__c/fields/cs_Attribution_Type__c.field-meta.xml
<CustomField>
    <fullName>cs_Attribution_Type__c</fullName>
    <label>Attribution Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customisation</fullName>
            </value>
            <value>
                <fullName>OLI</fullName>
            </value>
            <value>
                <fullName>Addon</fullName>
            </value>
            <value>
                <fullName>Sub Option</fullName>
            </value>
            <value>
                <fullName>Dep Date HSS</fullName>
            </value>
            <value>
                <fullName>Dep City Surcharge</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CS_Attribution_POE__c/fields/TAD_Order__c.field-meta.xml
<CustomField>
    <fullName>TAD_Order__c</fullName>
    <label>TAD Order</label>
    <referenceTo>TAD_Order__c</referenceTo>
    <relationshipLabel>CS Attribution</relationshipLabel>
    <relationshipName>CS_Attribution_POE</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/departures_dates__c.object-meta.xml
<CustomObject>
    <label>departures dates</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>departures dates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/departures_dates__c/fields/date__c.field-meta.xml
<CustomField>
    <fullName>date__c</fullName>
    <label>date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/HSS_amount__c.field-meta.xml
<CustomField>
    <fullName>HSS_amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>HSS amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Itinerary__c/Itinerary__c.object-meta.xml
<CustomObject>
    <label>Itinerary</label>
    <nameField>
        <displayFormat>Itinerary-{00000}</displayFormat>
        <label>Itinerary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Itineraries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Itinerary__c/fields/Itinerary__c.field-meta.xml
<CustomField>
    <fullName>Itinerary__c</fullName>
    <label>Itinerary #</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>1</label>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/order_line_item__c/order_line_item__c.object-meta.xml
<CustomObject>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>OLI-{000000}</displayFormat>
        <label>Order Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/order_line_item__c/fields/Attribution__c.field-meta.xml
<CustomField>
    <fullName>Attribution__c</fullName>
    <formula>(1- (Credit_Utilized__c/ (OLI_Price__c)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Attribution %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/order_line_item__c/fields/HSS_Amount__c.field-meta.xml
<CustomField>
    <fullName>HSS_Amount__c</fullName>
    <formula>on_hss_amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>HSS Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/order_line_item__c/fields/ordexp_city_surcharge_amount__c.field-meta.xml
<CustomField>
    <fullName>ordexp_city_surcharge_amount__c</fullName>
    <formula>IF(ordexp_orderRT__c=&apos;TAD&apos; || ordexp_orderRT__c=&apos;TC&apos;,  Departure_cities__r.Surcharge__c,  IF(ordexp_orderRT__c=&apos;TNZ&apos; || ordexp_orderRT__c=&apos;WT&apos;, Departure_cities__r.surcharge_nz__c , 0) ) * PAX_Qty__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>City Surcharge Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/order_line_item__c/fields/ordexp_departure_date__c.field-meta.xml
<CustomField>
    <fullName>ordexp_departure_date__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Note :- For Stay type Orders, change to Departure Date will be applied to all the OLIs of this Order</inlineHelpText>
    <label>Departure date</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>departures_dates__c.sub_options__c</field>
            <operation>equals</operation>
            <valueField>$Source.Sub_Options__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>departures_dates__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/order_line_item__c/fields/ordexp_suboption_amount__c.field-meta.xml
<CustomField>
    <fullName>ordexp_suboption_amount__c</fullName>
    <formula>IF(ordexp_orderRT__c=&apos;TAD&apos; || ordexp_orderRT__c=&apos;TC&apos;,  General_Pricing__r.Price_AUD__c * VALUE( TEXT(Quantity__c) ),  IF(ordexp_orderRT__c=&apos;TNZ&apos; || ordexp_orderRT__c=&apos;WT&apos;,  General_Pricing__r.Price_NZD__c* VALUE(TEXT(Quantity__c)) , 0) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Suboption Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/order_line_item__c/fields/ordexp_TAD_Order__c.field-meta.xml
<CustomField>
    <fullName>ordexp_TAD_Order__c</fullName>
    <label>Order</label>
    <referenceTo>TAD_Order__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items_orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/order_line_item__c/fields/Total_surcharge__c.field-meta.xml
<CustomField>
    <fullName>Total_surcharge__c</fullName>
    <formula>IF(ordexp_orderRT__c=&apos;TAD&apos; || ordexp_orderRT__c=&apos;TC&apos; , IF(TEXT(Pricing_Model__c ) = &apos;Solo&apos;, General_Pricing__r.Solo_Surcharge_AUD__c, 0),  
  IF(ordexp_orderRT__c=&apos;TNZ&apos; || ordexp_orderRT__c=&apos;WT&apos;, IF(TEXT(Pricing_Model__c ) = &apos;Solo&apos;, General_Pricing__r.Solo_Surcharge_NZD__c, 0), 0) ) 
* PAX_Qty__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Surcharge</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/order_line_item__c/fields/Web_Agent__c.field-meta.xml
<CustomField>
    <fullName>Web_Agent__c</fullName>
    <formula>ordexp_TAD_Order__r.Web_Agent__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Web Agent</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/order_line_POE__c/order_line_POE__c.object-meta.xml
<CustomObject>
    <label>Order Line</label>
    <nameField>
        <displayFormat>OL-{00000000}</displayFormat>
        <label>Order Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/order_line_POE__c/fields/AddOn__c.field-meta.xml
<CustomField>
    <fullName>AddOn__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AddOn</label>
    <referenceTo>AddOn__c</referenceTo>
    <relationshipLabel>Order Lines</relationshipLabel>
    <relationshipName>Order_Lines_POE</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/order_line_POE__c/fields/Order_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Order_Line_Item__c</fullName>
    <label>Order Line Item</label>
    <referenceTo>order_line_item__c</referenceTo>
    <relationshipLabel>Order Lines</relationshipLabel>
    <relationshipName>Order_Lines_POE</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/order_line_POE__c/fields/TAD_Order__c.field-meta.xml
<CustomField>
    <fullName>TAD_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TAD Order</label>
    <referenceTo>TAD_Order__c</referenceTo>
    <relationshipLabel>Order Lines</relationshipLabel>
    <relationshipName>Order_Lines_POE</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/TAD_Order__c.object-meta.xml
<CustomObject>
    <label>TAD Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TAD Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_departure_date__c.field-meta.xml
<CustomField>
    <fullName>ordexp_departure_date__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Departure date</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>(1 OR 2) AND 3</booleanFilter>
        <filterItems>
            <field>departures_dates__c.Deal__c</field>
            <operation>equals</operation>
            <valueField>$Source.ordexp_deal__c</valueField>
        </filterItems>
        <filterItems>
            <field>departures_dates__c.options__c</field>
            <operation>equals</operation>
            <valueField>$Source.ordexp_option__c</valueField>
        </filterItems>
        <filterItems>
            <field>departures_dates__c.online_status__c</field>
            <operation>equals</operation>
            <value>Online</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>departures_dates__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>TAD_Orders_DD</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_master_status__c.field-meta.xml
<CustomField>
    <fullName>ordexp_master_status__c</fullName>
    <label>Master status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
                <default>true</default>
                <label>On Hold</label>
            </value>
            <value>
                <fullName>Temporary Hold</fullName>
            </value>
            <value>
                <fullName>Secured</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Travelled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>In Progress-Cruise only</fullName>
                <isActive>false</isActive>
                <label>In Progress-Cruise only</label>
            </value>
            <value>
                <fullName>In Progress-Flight only</fullName>
                <isActive>false</isActive>
                <label>In Progress-Flight only</label>
            </value>
            <value>
                <fullName>In Progress-Flights + Cruise</fullName>
                <isActive>false</isActive>
                <label>In Progress-Flights + Cruise</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TAD_Order__c/recordTypes/TAD.recordType-meta.xml
<RecordType>
    <fullName>TAD</fullName>
    <active>true</active>
    <label>TAD</label>
</RecordType>

force-app/main/default/classes/BatchForDeletingOldCSRecords.cls
global class BatchForDeletingOldCSRecords implements Database.Batchable<SObject>{
    
    global Database.QueryLocator start(Database.BatchableContext bc)
    {       
        
        Date depDate = Date.parse('31/01/2023');
        String dt = String.valueOf(depDate);
        system.debug('Line8'+dt);
        String query= 'Select Id, ordexp_master_status__c from TAD_Order__c where (ordexp_master_status__c =\'In Progress\' OR ordexp_master_status__c =\'Cancelled\' OR ordexp_master_status__c =\'Secured\') AND'+
            +  ' ordexp_departure_date__r.date__c > '+ dt + ' ' ;
        
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext bc, List<TAD_Order__c> scope)
    {
        
        system.debug('scope of TAD Orders '+scope);
        Set<Id> orderIdSet = new Set<Id>();        
        Set<Id> oliList = new Set<Id>();
        List<order_line_item__c> oliDataList = new List<order_line_item__c>();
        List<Addon__c> addonDataList = new List<Addon__c>();        
        List<Itinerary__c> itnList = new List<Itinerary__c>();        
        List<order_line_POE__c> olList = New List<order_line_POE__c>();
        Set<Id> tadOrderPositiveSet = new Set<Id>();
        
        for(TAD_Order__c d: scope)
        {
            if(d.ordexp_master_status__c != 'Cancelled'){
                tadOrderPositiveSet.add(d.Id);
            }
            orderIdSet.add(d.Id);
        }
        
        system.debug('orderIdSet-21-->'+orderIdSet.size());
        
        if(orderIdSet.size() > 0){            
            // Delete for old cs attribution record
            List<CS_Attribution_POE__c> csDataList = [select id,cs_Attribution_Type__c,TAD_Order__r.ordexp_master_status__c from CS_Attribution_POE__c where TAD_Order__c IN: orderIdSet];
            system.debug('csDataList-42-->'+csDataList); 
            if(!csDataList.isEmpty()){
                Delete csDataList;  
            }
            
            if(tadOrderPositiveSet.size() > 0){
                oliDataList = [select id,Attribution__c,ordexp_suboption_amount__c,HSS_Amount__c,ordexp_city_surcharge_amount__c,Total_surcharge__c,CreatedById,ordexp_TAD_Order__c,ordexp_TAD_Order__r.Web_Agent__c,CurrencyIsoCode from order_line_item__c where ordexp_TAD_Order__c IN: tadOrderPositiveSet AND (OLI_Status__c = 'Active' OR OLI_Status__c = 'Secured')];
                
                if(!oliDataList.isEmpty()){
                    for(order_line_item__c ol: oliDataList)
                    {
                        oliList.add(ol.Id);
                        //  system.debug('oliList-28-->'+oliList);
                    }
                }
                if(oliList.size() > 0){
                    addonDataList = [select id,ordexp_amount__c,CreatedById,CurrencyIsoCode,TAD_Order_Id__c,Order_Line_Item__r.ordexp_TAD_Order__r.Web_Agent__c,Order_Line_Item__c,Attribution__c from AddOn__c where Order_Line_Item__c IN: oliList AND (AddOn_Status__c ='Active' Or AddOn_Status__c ='Secured')];
                }  
            }
        } 
        system.debug('addonDataList'+addonDataList);
        
        
        List<CS_Attribution_POE__c> listOfOliCsAttribute = new List<CS_Attribution_POE__c>();
        if(!oliDataList.isEmpty()){
        for(Order_line_item__c oli : oliDataList){ 
            CS_Attribution_POE__c cs = new CS_Attribution_POE__c();
            CS_Attribution_POE__c cs1 = new CS_Attribution_POE__c();
            CS_Attribution_POE__c cs2 = new CS_Attribution_POE__c(); 
            
            // Card CSA-7 For hss Amount and ordexp_city_surcharge_amount__c is Equal to 0
            cs.cs_Attribution_Type__c = 'Sub Option';
            cs.cs_OLI__c = oli.Id;
            if(oli.Attribution__c != Null){
                cs.cs_Sale_Amount__c = oli.ordexp_suboption_amount__c==null?0:(((oli.ordexp_suboption_amount__c + oli.Total_surcharge__c)*oli.Attribution__c)/100);   
                    }
            cs.TAD_Order__c = oli.ordexp_TAD_Order__c;
            cs.cs_status__c ='Sold';
            cs.CurrencyIsoCode =oli.CurrencyIsoCode;
            cs.User__c = oli.ordexp_TAD_Order__r.Web_Agent__c == null ? oli.CreatedById : oli.ordexp_TAD_Order__r.Web_Agent__c;
            
            
            listOfOliCsAttribute.add(cs);   
            
            // Card CSA-9 For ordexp_city_surcharge_amount__c greater than 0
            if(oli.ordexp_city_surcharge_amount__c >0){
                cs1.cs_Attribution_Type__c = 'Dep City Surcharge';
                cs1.cs_OLI__c = oli.Id;               
                if(oli.Attribution__c != Null){
                    cs1.cs_Sale_Amount__c = oli.ordexp_city_surcharge_amount__c==null?0:((oli.ordexp_city_surcharge_amount__c*oli.Attribution__c)/(100));
                        }
                cs1.TAD_Order__c = oli.ordexp_TAD_Order__c;
                cs1.cs_status__c ='Sold';
                cs1.CurrencyIsoCode =oli.CurrencyIsoCode;
                cs1.User__c = oli.ordexp_TAD_Order__r.Web_Agent__c == null ? oli.CreatedById : oli.ordexp_TAD_Order__r.Web_Agent__c;
                listOfOliCsAttribute.add(cs1);                  
            }
            
            // Card CSA-8 For hss Amount s greater than 0
            if(oli.HSS_Amount__c > 0){
                cs2.cs_Attribution_Type__c = 'Dep Date HSS';
                cs2.cs_OLI__c = oli.Id;
                if(oli.Attribution__c != Null){
                    cs2.cs_Sale_Amount__c = oli.HSS_Amount__c==null?0:((oli.HSS_Amount__c*oli.Attribution__c)/(100)); 
                        }
                cs2.TAD_Order__c = oli.ordexp_TAD_Order__c;
                cs2.cs_status__c ='Sold';
                cs2.CurrencyIsoCode =oli.CurrencyIsoCode;
                cs2.User__c = oli.ordexp_TAD_Order__r.Web_Agent__c == null ? oli.CreatedById : oli.ordexp_TAD_Order__r.Web_Agent__c;
                listOfOliCsAttribute.add(cs2);  
                
            }    
        }
        }
        
        system.debug('line90'+listOfOliCsAttribute);       
        
        List<CS_Attribution_POE__c> listOfAddonCsAttribute = new List<CS_Attribution_POE__c>();
        
        if(!addonDataList.isEmpty()){
            for(AddOn__c addOn : addonDataList){
                CS_Attribution_POE__c csAttForAddOn = new CS_Attribution_POE__c();
                csAttForAddOn.cs_Attribution_Type__c = 'Addon';
                csAttForAddOn.cs_AddOn__c = addOn.Id;
                csAttForAddOn.cs_OLI__c = addOn.Order_Line_Item__c;
                if(addOn.Attribution__c != Null){
                    csAttForAddOn.cs_Sale_Amount__c = addOn.ordexp_amount__c == null || addOn.ordexp_amount__c == 0.00 ? 0 :((addOn.ordexp_amount__c * addOn.Attribution__c)/(100)); 
                        }
                system.debug('ordexp_amount__c line 123'+csAttForAddOn.cs_Sale_Amount__c);
                csAttForAddOn.TAD_Order__c = addOn.TAD_Order_Id__c;
                csAttForAddOn.cs_status__c ='Sold';
                csAttForAddOn.CurrencyIsoCode =addOn.CurrencyIsoCode;
                csAttForAddOn.User__c =  addOn.Order_Line_Item__r.ordexp_TAD_Order__r.Web_Agent__c == null ? addOn.CreatedById : addOn.Order_Line_Item__r.ordexp_TAD_Order__r.Web_Agent__c;
                listOfAddonCsAttribute.add(csAttForAddOn); 
                
            }  
        }
        
        
        
        
        if(!listOfOliCsAttribute.isEmpty()){
            Database.insert(listOfOliCsAttribute, false);
            
            
        }  
        if(!listOfAddonCsAttribute.isEmpty()){
            Database.insert(listOfAddonCsAttribute, false);
            
        }
        
        
    }
    
    
    
    
    global void finish(Database.BatchableContext bc)
    {
    }
}