force-app/main/default/objects/AddOn__c/AddOn__c.object-meta.xml
<CustomObject>
    <label>AddOn</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AddOns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AddOn__c/fields/AddOn_Status__c.field-meta.xml
<CustomField>
    <fullName>AddOn_Status__c</fullName>
    <label>AddOn Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On Hold</fullName>
                <default>true</default>
                <label>On Hold</label>
            </value>
            <value>
                <fullName>Secured</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AddOn__c/fields/AE_SB__c.field-meta.xml
<CustomField>
    <fullName>AE_SB__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AE/SB</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>AE_SB__c.Deal__c</field>
            <operation>equals</operation>
            <valueField>$Source.Deal__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AE_SB__c</referenceTo>
    <relationshipLabel>AddOns</relationshipLabel>
    <relationshipName>AddOns_AESB</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AddOn__c/fields/Airline_Upgrade__c.field-meta.xml
<CustomField>
    <fullName>Airline_Upgrade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Airline Upgrade</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>airline_upgrade__c.Deal__c</field>
            <operation>equals</operation>
            <valueField>$Source.Deal__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>airline_upgrade__c</referenceTo>
    <relationshipLabel>AddOns</relationshipLabel>
    <relationshipName>AddOns_airlineUpgrade</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AddOn__c/fields/General_Pricing__c.field-meta.xml
<CustomField>
    <fullName>General_Pricing__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>General Pricing</label>
    <referenceTo>General_Pricing__c</referenceTo>
    <relationshipLabel>AddOns</relationshipLabel>
    <relationshipName>AddOns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AddOn__c/fields/land_activity__c.field-meta.xml
<CustomField>
    <fullName>land_activity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>land activity</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Value does not exist or does not match filter criteria LA Deal</errorMessage>
        <filterItems>
            <field>land_activity__c.Deal__c</field>
            <operation>equals</operation>
            <valueField>$Source.Deal__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>land_activity__c</referenceTo>
    <relationshipLabel>AddOns</relationshipLabel>
    <relationshipName>AddOns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AddOn__c/fields/ordexp_amount__c.field-meta.xml
<CustomField>
    <fullName>ordexp_amount__c</fullName>
    <label>Amount</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AddOn__c/fields/Pricing_Model__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Model__c</fullName>
    <label>Pricing Model</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Solo</fullName>
            </value>
            <value>
                <fullName>Twin</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AddOn__c/fields/Sub_Stopover__c.field-meta.xml
<CustomField>
    <fullName>Sub_Stopover__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stopover</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>sub_stopover__c.Deal__c</field>
            <operation>equals</operation>
            <valueField>$Source.Deal__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>sub_stopover__c</referenceTo>
    <relationshipLabel>AddOns</relationshipLabel>
    <relationshipName>AddOns_subStopover</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AddOn__c/recordTypes/AE_SB.recordType-meta.xml
<RecordType>
    <fullName>AE_SB</fullName>
    <active>true</active>
    <label>AE/SB</label>
</RecordType>

force-app/main/default/objects/AddOn__c/recordTypes/Airline_Upgrade.recordType-meta.xml
<RecordType>
    <fullName>Airline_Upgrade</fullName>
    <active>true</active>
    <label>Airline Upgrade</label>
</RecordType>

force-app/main/default/objects/AddOn__c/recordTypes/Land_Activity.recordType-meta.xml
<RecordType>
    <fullName>Land_Activity</fullName>
    <active>true</active>
    <label>Land Activity</label>
</RecordType>

force-app/main/default/objects/AddOn__c/recordTypes/SubStopover.recordType-meta.xml
<RecordType>
    <fullName>SubStopover</fullName>
    <active>true</active>
    <label>Stopover</label>
</RecordType>

force-app/main/default/objects/AE_SB__c/AE_SB__c.object-meta.xml
<CustomObject>
    <label>AE/SB</label>
    <nameField>
        <label>AE/SB Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AE/SB</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AE_SB__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Used to make AE/SB active on the website - used to make this controllable by product team</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/airline_upgrade__c/airline_upgrade__c.object-meta.xml
<CustomObject>
    <label>airline upgrade</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>airline upgrade</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/airline_upgrade__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Used to take options on or off the web checked is on</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/General_Pricing__c/General_Pricing__c.object-meta.xml
<CustomObject>
    <label>General Pricing</label>
    <nameField>
        <displayFormat>GP-{0000000}</displayFormat>
        <label>General Pricing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>General Pricings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/General_Pricing__c/fields/AE_SB__c.field-meta.xml
<CustomField>
    <fullName>AE_SB__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AE/SB</label>
    <referenceTo>AE_SB__c</referenceTo>
    <relationshipLabel>General Pricings</relationshipLabel>
    <relationshipName>General_Pricings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/General_Pricing__c/fields/AE_SB_Price__c.field-meta.xml
<CustomField>
    <fullName>AE_SB_Price__c</fullName>
    <label>AE/SB Price</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/General_Pricing__c/fields/Airline_Upgrade__c.field-meta.xml
<CustomField>
    <fullName>Airline_Upgrade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Airline Upgrade</label>
    <referenceTo>airline_upgrade__c</referenceTo>
    <relationshipLabel>General Pricings</relationshipLabel>
    <relationshipName>General_Pricings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/General_Pricing__c/fields/LA_Solo_Price__c.field-meta.xml
<CustomField>
    <fullName>LA_Solo_Price__c</fullName>
    <label>LA Solo Price</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/General_Pricing__c/fields/LA_Twin_Price__c.field-meta.xml
<CustomField>
    <fullName>LA_Twin_Price__c</fullName>
    <label>LA Twin Price</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/General_Pricing__c/fields/Land_Activity__c.field-meta.xml
<CustomField>
    <fullName>Land_Activity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Land Activity</label>
    <referenceTo>land_activity__c</referenceTo>
    <relationshipLabel>General Pricings</relationshipLabel>
    <relationshipName>General_Pricings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/General_Pricing__c/fields/Price_Airline_upgrade__c.field-meta.xml
<CustomField>
    <fullName>Price_Airline_upgrade__c</fullName>
    <label>Price</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/General_Pricing__c/fields/Price_Airline_upgrade_NZD__c.field-meta.xml
<CustomField>
    <fullName>Price_Airline_upgrade_NZD__c</fullName>
    <label>Price - NZD</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/General_Pricing__c/fields/Stopover_Solo_Price__c.field-meta.xml
<CustomField>
    <fullName>Stopover_Solo_Price__c</fullName>
    <label>Stopover Solo Price</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/General_Pricing__c/fields/Stopover_Twin_Price__c.field-meta.xml
<CustomField>
    <fullName>Stopover_Twin_Price__c</fullName>
    <label>Stopover Twin Price</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/General_Pricing__c/fields/Sub_Stopover__c.field-meta.xml
<CustomField>
    <fullName>Sub_Stopover__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stopover</label>
    <referenceTo>sub_stopover__c</referenceTo>
    <relationshipLabel>General Pricings</relationshipLabel>
    <relationshipName>General_Pricings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/General_Pricing__c/recordTypes/AE_SB.recordType-meta.xml
<RecordType>
    <fullName>AE_SB</fullName>
    <active>true</active>
    <label>AE/SB</label>
</RecordType>

force-app/main/default/objects/General_Pricing__c/recordTypes/Airline_Upgrade.recordType-meta.xml
<RecordType>
    <fullName>Airline_Upgrade</fullName>
    <active>true</active>
    <label>Airline Upgrade</label>
</RecordType>

force-app/main/default/objects/General_Pricing__c/recordTypes/Land_Activity.recordType-meta.xml
<RecordType>
    <fullName>Land_Activity</fullName>
    <active>true</active>
    <label>Land Activity</label>
</RecordType>

force-app/main/default/objects/General_Pricing__c/recordTypes/Sub_Stopover.recordType-meta.xml
<RecordType>
    <fullName>Sub_Stopover</fullName>
    <active>true</active>
    <label>Stopover</label>
</RecordType>

force-app/main/default/objects/land_activity__c/land_activity__c.object-meta.xml
<CustomObject>
    <label>land activity</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>land activity</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/sub_stopover__c/sub_stopover__c.object-meta.xml
<CustomObject>
    <label>sub stopover</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>sub stopover</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sub_stopover__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Used to make sub Stop active or not on website</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Tad_BatchToCreateAddonGP.cls
public class Tad_BatchToCreateAddonGP implements  Database.Batchable<sObject> {
    
    
    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([
            select Id, Name, ordexp_amount__c, RecordTypeId, land_activity__c, AE_SB__c, Airline_Upgrade__c, Sub_Stopover__c, Pricing_Model__c,general_pricing__c from Addon__c where general_pricing__c = null and addon_status__c !='Cancelled'
        ]);
    }
    
    public void execute(Database.BatchableContext bc, List<Addon__c> addonRecords){
        List<General_Pricing__c> gpRecordsToCreate = new List<General_Pricing__c>();
        String landActivityRCT = Schema.SObjectType.general_pricing__c.getRecordTypeInfosByDeveloperName().get('Land_Activity').getRecordTypeId();
        String aesbRCT = Schema.SObjectType.general_pricing__c.getRecordTypeInfosByDeveloperName().get('AE_SB').getRecordTypeId();
        String stopoverRCT = Schema.SObjectType.general_pricing__c.getRecordTypeInfosByDeveloperName().get('Sub_Stopover').getRecordTypeId();
        String airlineUpgradeRCT = Schema.SObjectType.general_pricing__c.getRecordTypeInfosByDeveloperName().get('Airline_Upgrade').getRecordTypeId();
        Map<String,String> landactivityGpMap = new Map<String,String>();
        Map<String,String> airlineGpMap = new Map<String,String>();
        Map<String,String> stopoverGpMap = new Map<String,String>();
        Map<String,String> aesbGpMap = new Map<String,String>();
        Map<String,general_pricing__c> addonGpMap = new Map<String,general_pricing__c>();
        Set<Id> laIds = new Set<Id>();
        Set<Id> aesbIds = new Set<Id>();
        Set<Id> substopIds = new Set<Id>();
        Set<Id> auIds = new Set<Id>();
        for(Addon__c addon :addonRecords){
            if(addon.RecordTypeId == Schema.SObjectType.AddOn__c.getRecordTypeInfosByDeveloperName().get('Land_Activity').getRecordTypeId()){
                laIds.add(addon.land_activity__c);
            }
            if(addon.RecordTypeId == Schema.SObjectType.AddOn__c.getRecordTypeInfosByDeveloperName().get('AE_SB').getRecordTypeId()){
                aesbIds.add(addon.AE_SB__c);
            }
            if(addon.RecordTypeId == Schema.SObjectType.AddOn__c.getRecordTypeInfosByDeveloperName().get('Airline_Upgrade').getRecordTypeId()){
                auIds.add(addon.Airline_Upgrade__c);
            }
            if(addon.RecordTypeId == Schema.SObjectType.AddOn__c.getRecordTypeInfosByDeveloperName().get('SubStopover').getRecordTypeId()){
                substopIds.add(addon.Sub_Stopover__c);
            }
        }
        List<General_Pricing__c> lagpRecords = [select id,name,LA_Solo_Price__c,LA_Twin_Price__c, land_activity__c from General_Pricing__c where Active__c = true and land_activity__c IN:laIds];
        List<General_Pricing__c> aesbgpRecords = [select id,name,AE_SB_Price__c, AE_SB__c from General_Pricing__c where Active__c = true and AE_SB__c IN:aesbIds];
        List<General_Pricing__c> augpRecords = [select id,name,Price_Airline_upgrade__c,Price_Airline_upgrade_NZD__c, Airline_Upgrade__c from General_Pricing__c where Active__c = true and Airline_Upgrade__c IN:auIds];
        List<General_Pricing__c> stopgpRecords = [select id,name,Stopover_Solo_Price__c,Stopover_Twin_Price__c, Sub_Stopover__c from General_Pricing__c where Active__c = true and Sub_Stopover__c IN:substopIds];
        
        for(Addon__c addon :addonRecords){
            Boolean isGpExist = false;
            if(addon.RecordTypeId == Schema.SObjectType.AddOn__c.getRecordTypeInfosByDeveloperName().get('Land_Activity').getRecordTypeId()){
                for(General_Pricing__c gp:lagpRecords){
                    if(addon.land_activity__c == gp.land_activity__c){
                        if(addon.Pricing_Model__c == 'Solo' && addon.ordexp_amount__c == gp.LA_Solo_Price__c || addon.Pricing_Model__c == 'Twin' && addon.ordexp_amount__c == gp.LA_Twin_Price__c){
                            isGpExist = true;
                            addonGpMap.put(addon.Id,gp);
                        }
                    }
                }
                if(!isGpExist){ 
                    general_pricing__c gp = new general_pricing__c();
                    gp.RecordTypeId = landActivityRCT;
                    if(addon.Pricing_Model__c=='Solo'){
                        gp.LA_Solo_Price__c = addon.ordexp_amount__c;
                    }else{
                        gp.LA_Twin_Price__c = addon.ordexp_amount__c;
                    }
                    gp.Active__c = false;
                    gp.Land_Activity__c = addon.land_activity__c;
                    gpRecordsToCreate.add(gp);
                    addonGpMap.put(addon.Id,gp);
                    landactivityGpMap.put(addon.land_activity__c, gp.Id);
                }
            }
            if(addon.RecordTypeId == Schema.SObjectType.AddOn__c.getRecordTypeInfosByDeveloperName().get('AE_SB').getRecordTypeId()){
                for(General_Pricing__c gp:aesbgpRecords){
                    if(addon.AE_SB__c == gp.AE_SB__c){
                        if(addon.ordexp_amount__c == gp.AE_SB_Price__c){
                            isGpExist = true;
                            addonGpMap.put(addon.Id,gp);
                        }
                    }
                }
                if(!isGpExist){
                    general_pricing__c gp = new general_pricing__c();
                    gp.RecordTypeId = aesbRCT;
                    gp.AE_SB_Price__c = addon.ordexp_amount__c;
                    gp.Active__c = false;
                    gp.AE_SB__c = addon.AE_SB__c;
                    gpRecordsToCreate.add(gp);
                    addonGpMap.put(addon.Id,gp);
                    aesbGpMap.put(addon.AE_SB__c, gp.Id);  
                }
                
            }
            if(addon.RecordTypeId == Schema.SObjectType.AddOn__c.getRecordTypeInfosByDeveloperName().get('Airline_Upgrade').getRecordTypeId()){
                for(General_Pricing__c gp:augpRecords){
                    if(addon.Airline_Upgrade__c == gp.Airline_Upgrade__c){
                        if(addon.ordexp_amount__c == gp.Price_Airline_upgrade__c || addon.ordexp_amount__c == gp.Price_Airline_upgrade_NZD__c){
                            isGpExist = true;
                            addonGpMap.put(addon.Id,gp);
                        }
                    }
                }
                if(!isGpExist){
                    general_pricing__c gp = new general_pricing__c();
                    gp.RecordTypeId = airlineUpgradeRCT;
                    gp.Price_Airline_upgrade__c = addon.ordexp_amount__c;
                    gp.Active__c = false;
                    gp.Airline_Upgrade__c = addon.Airline_Upgrade__c;
                    gpRecordsToCreate.add(gp);
                    addonGpMap.put(addon.Id,gp);
                    airlineGpMap.put(addon.Airline_Upgrade__c,gp.Id);
                }
            }
            if(addon.RecordTypeId == Schema.SObjectType.AddOn__c.getRecordTypeInfosByDeveloperName().get('SubStopover').getRecordTypeId()){
                for(General_Pricing__c gp:stopgpRecords){
                    if(addon.Sub_Stopover__c == gp.Sub_Stopover__c){
                        if(addon.Pricing_Model__c == 'Solo' && addon.ordexp_amount__c == gp.Stopover_Solo_Price__c || addon.Pricing_Model__c == 'Twin' && addon.ordexp_amount__c == gp.Stopover_Twin_Price__c){
                            isGpExist = true;
                            addonGpMap.put(addon.Id,gp);
                        }
                    }
                }
                if(!isGpExist){
                    general_pricing__c gp = new general_pricing__c();
                    gp.RecordTypeId = stopoverRCT;
                    if(addon.Pricing_Model__c=='Solo'){
                        gp.Stopover_Solo_Price__c = addon.ordexp_amount__c;
                    }else{
                        gp.Stopover_Solo_Price__c = addon.ordexp_amount__c;
                    }
                    gp.Active__c = false;
                    gp.Sub_Stopover__c = addon.Sub_Stopover__c;
                    gpRecordsToCreate.add(gp);
                    addonGpMap.put(addon.Id,gp);
                    stopoverGpMap.put(addon.Sub_Stopover__c,gp.Id);
                }
            }
        } 
        try{
            if(!gpRecordsToCreate.isEmpty()){
                //  insert gpRecordsToCreate;
            }
            for(Addon__c add:addonRecords){
                add.general_pricing__c = addonGpMap.get(add.Id).Id;
            }
            update addonRecords;
        }catch(Exception e){
            system.debug('Error occured while creating GP records :'+ e.getMessage());
        }
        /* if(!stopoverGpMap.keys().isEmpty()){
List<sub_stopover__c> stList  = [select Sub_Stopover__c from ];
}
if(!airlineGpMap.keys().isEmpty()){
List<airline_upgrade__c> stList  = [];
}
if(!aesbGpMap.keys().isEmpty()){
List<AE_SB__c> stList  = [];
}
if(!landactivityGpMap.keys().isEmpty()){
List<land_activity__c> stList  = [];
}*/
        
    }   
    public void finish(Database.BatchableContext bc){
        System.debug('GP records Created successfuly');
    } 
}