force-app/main/default/objects/AddOn__c/AddOn__c.object-meta.xml
<CustomObject>
    <label>AddOn</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AddOns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AddOn__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Deal</description>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>AddOns</relationshipLabel>
    <relationshipName>AddOns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AddOn__c/recordTypes/Insurance.recordType-meta.xml
<RecordType>
    <fullName>Insurance</fullName>
    <active>true</active>
    <label>Visa &amp; Insurance</label>
</RecordType>

force-app/main/default/objects/AddOn__c/recordTypes/SubStopover.recordType-meta.xml
<RecordType>
    <fullName>SubStopover</fullName>
    <active>true</active>
    <label>Stopover</label>
</RecordType>

force-app/main/default/objects/AE_SB__c/AE_SB__c.object-meta.xml
<CustomObject>
    <label>AE/SB</label>
    <nameField>
        <label>AE/SB Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AE/SB</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AE_SB__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>AE/SB</relationshipLabel>
    <relationshipName>AE_SB</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/airline_upgrade__c/airline_upgrade__c.object-meta.xml
<CustomObject>
    <label>airline upgrade</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>airline upgrade</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/airline_upgrade__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>airline upgrade</relationshipLabel>
    <relationshipName>airline_upgrade</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Allocation__c/Allocation__c.object-meta.xml
<CustomObject>
    <description>Auto Generated Name: {DEAL ID}-{DATE}-{POOL DIFFERENTIATOR} Example 1234-2020-11-1-A</description>
    <label>Allocation</label>
    <nameField>
        <label>Allocation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Allocation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Allocation__c/fields/deal__c.field-meta.xml
<CustomField>
    <fullName>deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Allocation</relationshipLabel>
    <relationshipName>Allocation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal__c/Deal__c.object-meta.xml
<CustomObject>
    <label>Deal</label>
    <nameField>
        <label>Deal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal__c/fields/Allocation_by__c.field-meta.xml
<CustomField>
    <fullName>Allocation_by__c</fullName>
    <label>Allocation by</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Deal</fullName>
                <default>true</default>
                <label>Deal</label>
            </value>
            <value>
                <fullName>Option</fullName>
            </value>
            <value>
                <fullName>Sub option</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal__c/fields/per_night_allocation__c.field-meta.xml
<CustomField>
    <fullName>per_night_allocation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Per Night Allocation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/departure_cities__c/departure_cities__c.object-meta.xml
<CustomObject>
    <label>departure cities</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>departure cities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/departure_cities__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>departure cities</relationshipLabel>
    <relationshipName>departure_cities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/departures_dates__c.object-meta.xml
<CustomObject>
    <label>departures dates</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>departures dates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/departures_dates__c/fields/allocation__c.field-meta.xml
<CustomField>
    <fullName>allocation__c</fullName>
    <label>TOTAL v2 ALLOCATION</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>departures dates</relationshipLabel>
    <relationshipName>departures_dates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Itinerary__c/Itinerary__c.object-meta.xml
<CustomObject>
    <label>Itinerary</label>
    <nameField>
        <displayFormat>Itinerary-{00000}</displayFormat>
        <label>Itinerary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Itineraries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Itinerary__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Itinerarys</relationshipLabel>
    <relationshipName>Itinerarys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/land_activity__c/land_activity__c.object-meta.xml
<CustomObject>
    <label>land activity</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>land activity</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/land_activity__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>land activity</relationshipLabel>
    <relationshipName>land_activity</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/options__c/options__c.object-meta.xml
<CustomObject>
    <label>Options</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/options__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipName>options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/options__c/recordTypes/Option.recordType-meta.xml
<RecordType>
    <fullName>Option</fullName>
    <active>true</active>
    <description>This is a record type for creating a normal Option Record.</description>
    <label>Option</label>
</RecordType>

force-app/main/default/objects/order_line_item__c/order_line_item__c.object-meta.xml
<CustomObject>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>OLI-{000000}</displayFormat>
        <label>Order Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/order_line_item__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sub_options__c/sub_options__c.object-meta.xml
<CustomObject>
    <label>Sub Options</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/sub_options__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Sub Options</relationshipLabel>
    <relationshipName>Sub_Options</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sub_stopover__c/sub_stopover__c.object-meta.xml
<CustomObject>
    <label>sub stopover</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>sub stopover</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sub_stopover__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>sub stopover</relationshipLabel>
    <relationshipName>sub_stopover</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TCPdfGeneratorSchedule_extensionTest.cls
@isTest
private class TCPdfGeneratorSchedule_extensionTest {
	@isTest
    private static void validatingPositive(){
        List<RecordType> RCTProductPartner = TADUtils.getRecordType(Label.TAD_RT_Product_Partner);
        
        Account acctBussiness = TestDataFactory.createBussinessAccount(RCTProductPartner[0].Id);   // Bussiness account Inserted
        insert acctBussiness;

		List<RecordType> RCTTadDeal = TADUtils.getRecordType(Label.TAD_RT_TAD_Deal);
        
        List<Deal__c> dealsToInsert = new List<Deal__c>();
          Deal__c dealNightOption = TestDataFactory.createMerchantDeal(RCTTadDeal[0].Id , acctBussiness.Id );   // Deals created
        dealNightOption.Name = '3333';
        dealNightOption.Allocation_by__c='Option';
        dealNightOption.per_night_allocation__c=true;
        dealsToInsert.add(dealNightOption);
        
        Deal__c dealNightSubOption = TestDataFactory.createMerchantDeal(RCTTadDeal[0].Id , acctBussiness.Id );   // Deals created
        dealNightSubOption.Name = '4444';
        dealNightSubOption.Allocation_by__c='Sub Option';
        dealNightSubOption.per_night_allocation__c=true;
        dealNightSubOption.deal_archetype__c='EAIU';
        dealsToInsert.add(dealNightSubOption);
        
        insert dealsToInsert;
   
	 List<options__c> optionsToInsert = new List<options__c>();
        
        options__c optionsNight = TestDataFactory.CreateOptions(dealNightOption.Id);       // Options crested using the deal
        optionsNight.itinerary_context__c='Main Package';
        optionsNight.NIghts__c=1;
        optionsToInsert.add(optionsNight);
        
        options__c optionsNight1 = TestDataFactory.CreateOptions(dealNightSubOption.Id);       // Options crested using the deal
        optionsNight1.itinerary_context__c='Main Package';
        optionsNight1.NIghts__c=1;
        optionsToInsert.add(optionsNight1);
        
        insert optionsToInsert;
        
        List<sub_options__c> subOptionsToInsert = new List<sub_options__c>();
        
        sub_options__c subOptionsNight = TestDataFactory.createSubOptions(optionsNight.Id);   // Sub options created
        subOptionsNight.STD_OPT__c ='Standard';
        subOptionsNight.Deal__c = dealNightOption.id;
        subOptionsToInsert.add(subOptionsNight);
        
        sub_options__c subOptionsNight1 = TestDataFactory.createSubOptions(optionsNight1.Id);   // Sub options created
        subOptionsNight1.STD_OPT__c ='Standard';
        subOptionsNight1.Deal__c = dealNightSubOption.id;
        subOptionsToInsert.add(subOptionsNight1);
        
        insert subOptionsToInsert;
        
          List<Allocation__c> allocationToInsert = new List<Allocation__c>();
        
        Allocation__c accNight = TestDataFactory.createAllocationDeal(dealNightOption);
        allocationToInsert.add(accNight);
        
        Allocation__c accNight1 = TestDataFactory.createAllocationDeal(dealNightSubOption);
        allocationToInsert.add(accNight1);
        
        insert allocationToInsert;
        
        List<departures_dates__c> ddToInsert = new List<departures_dates__c>();
        
        departures_dates__c departureDatesOptionsNight = TestDataFactory.createDDWithAllocation(null,optionsNight,null,accNight);
        departureDatesOptionsNight.Linked_Deal_D_O_S__c =dealNightOption.id;
        ddToInsert.add(departureDatesOptionsNight);
        
        departures_dates__c departureDatesSubOptionsNight = TestDataFactory.createDDWithAllocation(null,null,subOptionsNight1,accNight1);
        departureDatesSubOptionsNight.Linked_Deal_D_O_S__c =dealNightSubOption.id;
        ddToInsert.add(departureDatesSubOptionsNight);
        
        insert ddToInsert;
         
         List<departure_cities__c> ddCitiestToInsert = new List<departure_cities__c>();
        
        departure_cities__c departureCitiesOptionsNight = TestDataFactory.createDepartureCities(dealNightOption.Id);       // Departure cities created
        ddCitiestToInsert.add(departureCitiesOptionsNight);
        
        departure_cities__c departureCitiesSubOptionNight = TestDataFactory.createDepartureCities(dealNightSubOption.Id);       // Departure cities created
        ddCitiestToInsert.add(departureCitiesSubOptionNight);
        
        insert ddCitiestToInsert;
        
          Itinerary__c itinerary = TestDataFactory.createItinerary(dealNightOption,'Main Package',1);
        insert itinerary; 
        
        sub_stopover__c subStopover = TestDataFactory.createSubStopover(dealNightOption);
        insert subStopover; 
        
        AE_SB__c aeSb = TestDataFactory.createAE_SB(dealNightOption , optionsNight );
        aesb.Blockout__c='20/06/2018-21/06/2018';
        insert aeSb;
        
        land_activity__c la = TestDataFactory.createLandActivity(dealNightOption, itinerary);
        insert la;
        
        airline_upgrade__c au = TestDataFactory.createAirlineUpgrade(dealNightOption);
        insert au; 
        
        List<RecordType> RCTPersonAccount = TADUtils.getRecordType(Label.TAD_RT_TAD_Person_Account);
        Account acctPerson = TestDataFactory.createPersonAccount(RCTPersonAccount[0].Id);
        insert acctPerson;
        
        List<Tad_Order__c>   tadOrderToInsert = new  List<Tad_Order__c>();  
        List<Order_Line_Item__c>   oliToInsert = new  List<Order_Line_Item__c>();
        List<Order_Line_Item__c>   oliToUpdate = new  List<Order_Line_Item__c>();
        
        
        ID RTTADOrder1 = Schema.SObjectType.Tad_Order__C.getRecordTypeInfosByDeveloperName().get('TAD').getRecordTypeId();
        
        ID RTTADOrder2 = Schema.SObjectType.Tad_Order__C.getRecordTypeInfosByDeveloperName().get('TC').getRecordTypeId();
        Tad_Order__C order1 = TestDataFactory.createTADOrder(acctPerson,dealNightOption,optionsNight,departureDatesOptionsNight,RTTADOrder2);
        order1.ordexp_master_status__c = 'On Hold';
        order1.ordexp_sub_status__c = 'Initial Payment Pending';
        tadOrderToInsert.add(order1);
        
        Tad_Order__C order4 = TestDataFactory.createTADOrder(acctPerson,dealNightSubOption,optionsNight1,null,RTTADOrder1);
        order4.ordexp_departure_date__c=departureDatesSubOptionsNight.id;
        order4.ordexp_master_status__c = 'On Hold';
        order4.ordexp_sub_status__c = 'Initial Payment Pending';
        tadOrderToInsert.add(order4);
        
        insert tadOrderToInsert;
        
        Order_Line_Item__c oli1 = TestDataFactory.createOrderLineItem(order1,subOptionsNight,departureCitiesOptionsNight,'2');
        oli1.Deal__c=dealNightOption.id;
        oli1.ordexp_Options__c=optionsNight.id;
        oli1.Sub_Options__c = subOptionsNight.Id;
        oli1.ordexp_departure_date__c = departureDatesOptionsNight.Id;
        oliToInsert.add(oli1);
        
        Order_Line_Item__c oli4 = TestDataFactory.createOrderLineItem(order4,subOptionsNight1,departureCitiesSubOptionNight,'2');
        oli4.Deal__c=dealNightSubOption.id;
        oli4.ordexp_Options__c=optionsNight1.id;
        oli4.Sub_Options__c = subOptionsNight1.Id;
        oli4.ordexp_departure_date__c = departureDatesSubOptionsNight.Id;
        oliToInsert.add(oli4);
        
        insert oliToInsert;
        
        
        List<AddOn__c> addonList = new List<AddOn__c>();
         List<RecordType> RTAddOnAESB = TADUtils.getRecordType('AE/SB');
        system.debug('RTAddOnAESB debug '+RTAddOnAESB);
        AddOn__c addon = TestDataFactory.createAESBAddon(oli1,aeSb,RTAddOnAESB[0].id);
        addon.ordexp_new_aesb_date__c = Date.valueOf('2022-08-17');
        addonList.add(addon);
        
        List<RecordType> RTAddOnSubStopover = TADUtils.getRecordType('Sub Stopover');
        system.debug('RTAddOnSubStopover debug '+RTAddOnSubStopover);
        if(RTAddOnSubStopover.size() > 0){
            AddOn__c addon1 = TestDataFactory.createSubStopoverAddon(oli1,subStopover,RTAddOnSubStopover[0].id);
            addon1.Deal__c=dealNightOption.id;                                 
            addonList.add(addon);
        }
        
        
        List<RecordType> RTAddOnLActivity = TADUtils.getRecordType('Land Activity');
        system.debug('RTAddOnLActivity debug '+RTAddOnLActivity);
          
        AddOn__c addon2 = TestDataFactory.createLandActivityAddon(oli1,la,RTAddOnLActivity[0].id);
        addon2.Deal__c=dealNightOption.id;
        addonList.add(addon2);
        
        List<RecordType> RTAddOnUpgrade = TADUtils.getRecordType('Airline Upgrade');
        system.debug('RTAddOnUpgrade debug '+RTAddOnUpgrade);
        AddOn__c addon3 = TestDataFactory.createAirlineUpgradeAddon(oli1,au,RTAddOnUpgrade[0].id);
        addon3.Deal__c=dealNightOption.id;
        addonList.add(addon3); 
        
        test.startTest();
        
        insert addonList;
        
        customer_POE__c pax = TestDataFactory.createPassenger(oli1,order1);
        insert pax;
        
         Id RTVisa = TADUtils.getRecordTypeList('Visa','Visa_Insurance_POE__c');
        Visa_Insurance_POE__c visa = TestDataFactory.createInsuranceRecords('12345','Annual','TAD Insurance',RTVisa, oli1,pax);
        insert visa;
     
        Id RTCruiseCustomisation = TADUtils.getRecordTypeList('Cruise_Customisation','Order_Customisations_POE__c');
        Order_Customisations_POE__c customise = TestDataFactory.createOrderCustomisation(oli1,'Cruise Customisation',RTCruiseCustomisation,'Upgrade Carrier');
        
      
        ApexPages.StandardController sc = new ApexPages.StandardController(order1);
       
        TCPdfGeneratorSchedule_extension controller = new TCPdfGeneratorSchedule_extension(sc);
        Test.stopTest();
        
    }
}