force-app/main/default/objects/AddOn__c/AddOn__c.object-meta.xml
<CustomObject>
    <label>AddOn</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AddOns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AddOn__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Deal</description>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>AddOns</relationshipLabel>
    <relationshipName>AddOns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AE_SB__c/AE_SB__c.object-meta.xml
<CustomObject>
    <label>AE/SB</label>
    <nameField>
        <label>AE/SB Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AE/SB</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AE_SB__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>AE/SB</relationshipLabel>
    <relationshipName>AE_SB</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/airline_upgrade__c/airline_upgrade__c.object-meta.xml
<CustomObject>
    <label>airline upgrade</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>airline upgrade</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/airline_upgrade__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>airline upgrade</relationshipLabel>
    <relationshipName>airline_upgrade</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Deal__c/Deal__c.object-meta.xml
<CustomObject>
    <label>Deal</label>
    <nameField>
        <label>Deal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal__c/fields/PDF_Image__c.field-meta.xml
<CustomField>
    <fullName>PDF_Image__c</fullName>
    <label>PDF Image</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/departure_cities__c/departure_cities__c.object-meta.xml
<CustomObject>
    <label>departure cities</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>departure cities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/departure_cities__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>departure cities</relationshipLabel>
    <relationshipName>departure_cities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/departures_dates__c.object-meta.xml
<CustomObject>
    <label>departures dates</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>departures dates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/departures_dates__c/fields/date__c.field-meta.xml
<CustomField>
    <fullName>date__c</fullName>
    <label>date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>departures dates</relationshipLabel>
    <relationshipName>departures_dates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/ordexp_return_date__c.field-meta.xml
<CustomField>
    <fullName>ordexp_return_date__c</fullName>
    <formula>IF (  Nights__c  
 &gt; 0,(date__c+Nights__c)-1,IF ( Deal_for_Reporting__r.number_of_days__c
 &gt; 0, date__c + (Deal_for_Reporting__r.number_of_days__c
 - 1), date__c + (Deal_for_Reporting__r.number_of_days__c
 - 1)
))</formula>
    <label>Return Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/land_activity__c/land_activity__c.object-meta.xml
<CustomObject>
    <label>land activity</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>land activity</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/land_activity__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>land activity</relationshipLabel>
    <relationshipName>land_activity</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/media__c/media__c.object-meta.xml
<CustomObject>
    <label>media</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>media</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/media__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>media</relationshipLabel>
    <relationshipName>media</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/order_line_item__c/order_line_item__c.object-meta.xml
<CustomObject>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>OLI-{000000}</displayFormat>
        <label>Order Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/order_line_item__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/order_line_item__c/fields/ordexp_departure_date__c.field-meta.xml
<CustomField>
    <fullName>ordexp_departure_date__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Note :- For Stay type Orders, change to Departure Date will be applied to all the OLIs of this Order</inlineHelpText>
    <label>Departure date</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>departures_dates__c.sub_options__c</field>
            <operation>equals</operation>
            <valueField>$Source.Sub_Options__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>departures_dates__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sub_options__c/sub_options__c.object-meta.xml
<CustomObject>
    <label>Sub Options</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/sub_options__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Sub Options</relationshipLabel>
    <relationshipName>Sub_Options</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sub_stopover__c/sub_stopover__c.object-meta.xml
<CustomObject>
    <label>sub stopover</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>sub stopover</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sub_stopover__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>sub stopover</relationshipLabel>
    <relationshipName>sub_stopover</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/TAD_Order__c.object-meta.xml
<CustomObject>
    <label>TAD Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TAD Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_account__c.field-meta.xml
<CustomField>
    <fullName>ordexp_account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>TAD Orders</relationshipLabel>
    <relationshipName>TAD_Orders_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_deal__c.field-meta.xml
<CustomField>
    <fullName>ordexp_deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>TAD_Orders_Deal</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_departure_date__c.field-meta.xml
<CustomField>
    <fullName>ordexp_departure_date__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Departure date</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>(1 OR 2) AND 3</booleanFilter>
        <filterItems>
            <field>departures_dates__c.Deal__c</field>
            <operation>equals</operation>
            <valueField>$Source.ordexp_deal__c</valueField>
        </filterItems>
        <filterItems>
            <field>departures_dates__c.options__c</field>
            <operation>equals</operation>
            <valueField>$Source.ordexp_option__c</valueField>
        </filterItems>
        <filterItems>
            <field>departures_dates__c.online_status__c</field>
            <operation>equals</operation>
            <value>Online</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>departures_dates__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>TAD_Orders_DD</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_master_status__c.field-meta.xml
<CustomField>
    <fullName>ordexp_master_status__c</fullName>
    <label>Master status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
                <default>true</default>
                <label>On Hold</label>
            </value>
            <value>
                <fullName>Temporary Hold</fullName>
            </value>
            <value>
                <fullName>Secured</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Travelled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>In Progress-Cruise only</fullName>
                <isActive>false</isActive>
                <label>In Progress-Cruise only</label>
            </value>
            <value>
                <fullName>In Progress-Flight only</fullName>
                <isActive>false</isActive>
                <label>In Progress-Flight only</label>
            </value>
            <value>
                <fullName>In Progress-Flights + Cruise</fullName>
                <isActive>false</isActive>
                <label>In Progress-Flights + Cruise</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_return_date__c.field-meta.xml
<CustomField>
    <fullName>ordexp_return_date__c</fullName>
    <label>Return date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/MobileAppGetTADOrder.cls
@RestResource(urlmapping='/settingAppGetTADOrder/*')
global class MobileAppGetTADOrder {
    
    global class mainWrapper{
        global list<tadOrder> orderList{get;set;} 
        //global String errorMessage {get;set;}
       // global integer statusCode {get;set;}
      
    }
    
    global class tadOrder{
        global string ID{get;set;}
        global string tadOrderNumber{get;set;}
        global string personAccountId{get;set;}
        global string dealId{get;set;}
        global string optionsId{get;set;}
        global string departureDateId{get;set;}
        global string orderStatus{get;set;}
        global date fromDate{get;set;}
        global date toDate{get;set;}
        global string name_of_trip{get;set;}
        global string tripId{get;set;}
        global string imageUrl{get;set;}
        global list<OLI> OLIList{get;set;}
        global boolean hasDepartureDatePassed {get;set;}
        global string destination{get;set;}
        global boolean isContainsAESB {get;set;}
    }
    
    global class OLI{
        global string oliId{get;set;}
        //global string orderId{get;set;}
        // global string optionsId{get;set;}
        //  global string dealId{get;set;}
        global string subOptionId{get;set;}
        global string quantity{get;set;}
        global string PaxQuantity{get;set;}
        global boolean isContainsAESB{get;set;}
        global string travelType{get;set;}
        global string departureCitiesId{get;set;}
        global string departureDateId{get;set;}
        global list<Passanger> PassangerList{get;set;}
    }
    
    global class Passanger{
        global string ID{get;set;}
        global string lastName{get;set;}
        //global string orderId{get;set;}
        // global string oliId{get;set;}
        global list<AddOn> AddOnList{get;set;}
        
    }
    global class AddOn{
        global string ID{get;set;}
        global String addonOptionId{get;set;}
        global String typeOfAddon{get;set;}
        global String AddonName{get;set;}
        global Date aesbDate{get;set;}
        
        
    }
    
    @HttpGet
    global static mainWrapper createTADOrder(){
       
        mainWrapper mw = new mainWrapper();
        
        RestRequest request = RestContext.request;
        system.debug('request'+request);
        String AccountId = request.requestURI.substring(request.requestURI.lastIndexOf('/')+1);
        
        //system.debug('AccountId'+AccountId);
        
        list<Tad_Order__c> orderList = [select id,Name,ordexp_deal__r.PDF_Image__c ,ordexp_account__c,ordexp_master_status__c ,ordexp_deal__c,ordexp_departure_date__c,ordexp_departure_date__r.date__c,ordexp_departure_date__r.ordexp_return_date__c ,ordexp_option__c,ordexp_deal__r.title__c,ordexp_deal__r.Name,ordexp_deal__r.destination__c from Tad_Order__c where ordexp_account__c= :AccountId order By CreatedDate DESC];
        system.debug('orderList'+orderList);
        set<string> dealset = new set<string>();
        for(Tad_Order__c t:orderList)
        {
            dealset.add(t.ordexp_deal__c);
        }
         list<media__c> mLIst =  [select Id,url__c,Deal__c from media__c where Deal__c=:dealset];
        map<string,string> mapmedia= new  map<string,string>();
                if(mLIst.size()>0)
                {
                for(media__c m:mLIst)
                {
                    if(!mapmedia.containsKey(m.Deal__c))
                    {
                        mapmedia.put(m.Deal__c,m.url__c);
                    }
                }
                }
         
        list<Order_Line_Item__c> oliLIst = [select id,Deal__c,ordexp_Options__c,Sub_Options__c,PAX_Quantity__c,Quantity__c,Pricing_Model__c,Departure_cities__c,ordexp_TAD_Order__c,ordexp_departure_date__c from Order_Line_Item__c where ordexp_TAD_Order__c=:orderList];    
        system.debug('oliLIst'+oliLIst);
        list<customer_POE__c> PassengerLIst = [select id,Order_Line_Item__c,ordexp_tad_order__c,last_name__c from customer_POE__c where Order_Line_Item__c=:oliLIst];    
        list<AddOn__c> AddOnLIst = [select id,Passenger__c,AE_SB__r.Type__c,Airline_Upgrade__c,AE_SB__r.City__c,land_activity__c,Sub_Stopover__c,AE_SB__c,ordexp_new_aesb_date__c from AddOn__c where Passenger__c=:PassengerLIst];    
        
        //system.debug('PassengerLIst====>'+PassengerLIst);
        Map<Id,list<Order_Line_Item__c>> mapOrdervsOli = new  Map<Id,list<Order_Line_Item__c>>();
        for(Order_Line_Item__c oli:oliLIst)
        {
            list<Order_Line_Item__c> olilist1 =  new list<Order_Line_Item__c>();
            
            if(mapOrdervsOli.containsKey(oli.ordexp_TAD_Order__c))
            {
                olilist1 = mapOrdervsOli.get(oli.ordexp_TAD_Order__c);
                olilist1.add(oli);
                
            }
            else{
                olilist1.add(oli);
            }
            mapOrdervsOli.put(oli.ordexp_TAD_Order__c,olilist1);
        }
        Map<Id,list<customer_POE__c>> mapOliVsPassenger = new  Map<Id,list<customer_POE__c>>();
        for(customer_POE__c cust:PassengerLIst)
        {
            list<customer_POE__c> custlist1 =  new list<customer_POE__c>();
            
            if(mapOliVsPassenger.containsKey(cust.Order_Line_Item__c))
            {
                custlist1 = mapOliVsPassenger.get(cust.Order_Line_Item__c);
                custlist1.add(cust);
                
            }
            else{
                custlist1.add(cust);
            }
            mapOliVsPassenger.put(cust.Order_Line_Item__c,custlist1);
        }
        Map<Id,list<AddOn__c>> mapPassengerVsAddOn = new  Map<Id,list<AddOn__c>>();
        
        for(AddOn__c ado :AddOnLIst)
        {
            list<AddOn__c> AddOnlist1 =  new list<AddOn__c>();
            
            if(mapPassengerVsAddOn.containsKey(ado.Passenger__c))
            {
                AddOnlist1 = mapPassengerVsAddOn.get(ado.Passenger__c);
                AddOnlist1.add(ado);
                
            }
            else{
                AddOnlist1.add(ado);
            }
            mapPassengerVsAddOn.put(ado.Passenger__c,AddOnlist1);
        }
        
        // system.debug('mapOliVsPassenger---'+mapOliVsPassenger);
        list<tadOrder> TadorderList = new list<tadOrder>();
       
        
        if(orderList!=null){
            for(Tad_Order__c t: orderList)
            {
                boolean oliCheck=false;
                tadOrder order = new tadOrder();
                order.Id = t.Id;
                order.tadOrderNumber = t.Name;
                order.personAccountId = t.ordexp_account__c;
                order.dealId = t.ordexp_deal__c;
                order.optionsId= t.ordexp_option__c;
                order.departureDateId = t.ordexp_departure_date__c;
                order.orderStatus = t.ordexp_master_status__c ;
                
                order.fromDate=  t.ordexp_departure_date__r.date__c;
                order.toDate= t.ordexp_departure_date__r.ordexp_return_date__c;
                order.name_of_trip= t.ordexp_deal__r.title__c;
                order.tripId=t.ordexp_deal__r.Name;
                
                order.imageUrl=mapmedia.get(t.ordexp_deal__c);
                order.destination = t.ordexp_deal__r.destination__c;
                
                if(t.ordexp_departure_date__r.date__c > system.today()){
                    order.hasDepartureDatePassed = false;
                }else{
                    order.hasDepartureDatePassed = true;
                }
                
                list <Order_Line_Item__c> oliMapList = mapOrdervsOli.get(t.Id);
                List<OLI> listOli = new List<OLI>();
                
                if(oliMapList!=null)
                {
                    for(Order_Line_Item__c o:oliMapList)
                    {
                        boolean isAesb=false;
                        OLI oli = new OLI();
                        oli.oliId = o.Id;
                        //oli.orderId = o.ordexp_TAD_Order__c;
                        //   oli.optionsId = o.ordexp_Options__c;
                        //oli.dealId = o.Deal__c;
                        oli.subOptionId = o.Sub_Options__c;
                        oli.quantity = o.Quantity__c;
                        oli.PaxQuantity = o.PAX_Quantity__c;
                        oli.travelType = o.Pricing_Model__c;
                        oli.departureCitiesId = o.Departure_cities__c;
                        oli.departureDateId = o.ordexp_departure_date__c;
                        
                        
                        list <customer_POE__c> CutMapList = mapOliVsPassenger.get(o.Id);
                        // System.debug('CutMapList------'+CutMapList);
                        List<Passanger> listPassanger = new List<Passanger>();
                        if(CutMapList!=null)
                        {
                            for(customer_POE__c c:CutMapList)
                            {
                                Passanger pass = new Passanger();
                                pass.ID = c.Id;
                                pass.lastName = c.last_name__c;
                                //  pass.orderId = c.ordexp_TAD_Order__c;
                                //  pass.oliId = c.Order_Line_Item__c;
                                
                                list <AddOn__c> AddOnMapList = mapPassengerVsAddOn.get(pass.Id);
                                // System.debug('CutMapList------'+CutMapList);
                                List<AddOn> listAddOn = new List<AddOn>();
                                if(AddOnMapList!=null)
                                {
                                    for(AddOn__c a:AddOnMapList)
                                    {
                                        AddOn addonObj = new AddOn();
                                        addonObj.ID = a.Id;
                                        if(a.Airline_Upgrade__c!=null)
                                        {
                                            addonObj.AddonOptionId = a.Airline_Upgrade__c;
                                            addonObj.typeOfAddon ='Airline Upgrade' ; 
                                        }
                                        if(a.land_activity__c!=null)
                                        {
                                            addonObj.AddonOptionId = a.land_activity__c;
                                            addonObj.typeOfAddon ='Land Activity' ; 
                                        }    
                                        if(a.Sub_Stopover__c!=null)
                                        {
                                            addonObj.AddonOptionId = a.Sub_Stopover__c;
                                            addonObj.typeOfAddon ='Stop Over' ; 
                                        } 
                                        if(a.AE_SB__c !=null)
                                        {
                                            isAesb=true;
                                            oliCheck=true;
                                            addonObj.AddonName = a.AE_SB__r.City__c ;
                                            addonObj.aesbDate = a.ordexp_new_aesb_date__c ;
                                            addonObj.AddonOptionId = a.AE_SB__c;
                                            addonObj.typeOfAddon =a.AE_SB__r.Type__c  ; 
                                        }   
                                        
                                        
                                        listAddOn.add(addonObj);
                                    }
                                }
                                pass.AddOnList=listAddOn;
                                listPassanger.add(pass);
                            }
                        }
                        // system.debug('listPassanger===='+listPassanger);
                        oli.PassangerList= listPassanger;
                        oli.isContainsAESB=isaesb;
                        
                        listOli.add(oli);
                        
                    }
                }
                order.OLIList = listOli;
                order.isContainsAESB=oliCheck;
                TadorderList.add(order);
                
            }
        }
        mw.orderList = TadorderList;
        
        system.debug('mw'+mw);
        
        
        
        return mw;
    }
    
}