force-app/main/default/objects/AddOn__c/AddOn__c.object-meta.xml
<CustomObject>
    <label>AddOn</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AddOns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AddOn__c/fields/Add_On_Type__c.field-meta.xml
<CustomField>
    <fullName>Add_On_Type__c</fullName>
    <formula>IF( RecordType.Name==&apos;AE/SB&apos;,  IF( TEXT(AE_SB__r.Type__c)==&apos;Arrive Early&apos; , &apos;Arrive Early&apos;,&apos;Stay Behind&apos;),  
 IF(RecordType.Name==&apos;Stopover&apos;,  IF(TEXT(Sub_Stopover__r.type__c)==&apos;Pre Tour&apos;, &apos;Pre-Stopover&apos;,&apos;Post-Stopover&apos;) , RecordType.Name) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Add On Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AddOn__c/fields/AddOn_Status__c.field-meta.xml
<CustomField>
    <fullName>AddOn_Status__c</fullName>
    <label>AddOn Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On Hold</fullName>
                <default>true</default>
                <label>On Hold</label>
            </value>
            <value>
                <fullName>Secured</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AddOn__c/fields/land_activity__c.field-meta.xml
<CustomField>
    <fullName>land_activity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>land activity</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Value does not exist or does not match filter criteria LA Deal</errorMessage>
        <filterItems>
            <field>land_activity__c.Deal__c</field>
            <operation>equals</operation>
            <valueField>$Source.Deal__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>land_activity__c</referenceTo>
    <relationshipLabel>AddOns</relationshipLabel>
    <relationshipName>AddOns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AddOn__c/fields/Order_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Order_Line_Item__c</fullName>
    <label>Order Line Item</label>
    <referenceTo>order_line_item__c</referenceTo>
    <relationshipLabel>AddOns</relationshipLabel>
    <relationshipName>AddOns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AddOn__c/fields/Passenger__c.field-meta.xml
<CustomField>
    <fullName>Passenger__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Passenger</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Value does not exist or does not match filter criteria Pax OLI</errorMessage>
        <filterItems>
            <field>customer_POE__c.Order_Line_Item__c</field>
            <operation>equals</operation>
            <valueField>$Source.Order_Line_Item__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>customer_POE__c</referenceTo>
    <relationshipLabel>AddOns</relationshipLabel>
    <relationshipName>AddOns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/customer_POE__c/customer_POE__c.object-meta.xml
<CustomObject>
    <label>Passengers</label>
    <nameField>
        <displayFormat>PIF-{00000000}</displayFormat>
        <label>id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/customer_POE__c/fields/Order_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Order_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Line Item</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>order_line_item__c.ordexp_TAD_Order__c</field>
            <operation>equals</operation>
            <valueField>$Source.ordexp_tad_order__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>order_line_item__c</referenceTo>
    <relationshipLabel>Passengers</relationshipLabel>
    <relationshipName>Passengers_POE</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/customer_POE__c/fields/Order_Line_Item_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Line_Item_Status__c</fullName>
    <formula>TEXT(Order_Line_Item__r.OLI_Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order Line Item Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/customer_POE__c/fields/ordexp_PAX_Nickname__c.field-meta.xml
<CustomField>
    <fullName>ordexp_PAX_Nickname__c</fullName>
    <label>PAX Nickname</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/customer_POE__c/fields/Passenger_Name__c.field-meta.xml
<CustomField>
    <fullName>Passenger_Name__c</fullName>
    <formula>first_name__c&amp;&quot; &quot;&amp;last_name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Passenger_Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/customer_POE__c/fields/title__c.field-meta.xml
<CustomField>
    <fullName>title__c</fullName>
    <label>Title</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/land_activity__c/land_activity__c.object-meta.xml
<CustomObject>
    <label>land activity</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>land activity</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/order_line_item__c/order_line_item__c.object-meta.xml
<CustomObject>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>OLI-{000000}</displayFormat>
        <label>Order Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/order_line_POE__c/order_line_POE__c.object-meta.xml
<CustomObject>
    <label>Order Line</label>
    <nameField>
        <displayFormat>OL-{00000000}</displayFormat>
        <label>Order Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/order_line_POE__c/fields/AddOn__c.field-meta.xml
<CustomField>
    <fullName>AddOn__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AddOn</label>
    <referenceTo>AddOn__c</referenceTo>
    <relationshipLabel>Order Lines</relationshipLabel>
    <relationshipName>Order_Lines_POE</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/order_line_POE__c/fields/Component_Type__c.field-meta.xml
<CustomField>
    <fullName>Component_Type__c</fullName>
    <formula>IF(NOT(ISBLANK(Component__c) ) , TEXT(Component__r.Component_Type__c),  IF(NOT(ISBLANK(TAD_Booking_Records__c ) ), TEXT(TAD_Booking_Records__r.Booked_Component_Type__c), &apos;Stay Departure date surcharge&apos;)  )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Component Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/order_line_POE__c/fields/Order_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Order_Line_Item__c</fullName>
    <label>Order Line Item</label>
    <referenceTo>order_line_item__c</referenceTo>
    <relationshipLabel>Order Lines</relationshipLabel>
    <relationshipName>Order_Lines_POE</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/order_line_POE__c/fields/TAD_Order__c.field-meta.xml
<CustomField>
    <fullName>TAD_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TAD Order</label>
    <referenceTo>TAD_Order__c</referenceTo>
    <relationshipLabel>Order Lines</relationshipLabel>
    <relationshipName>Order_Lines_POE</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/TAD_Order__c.object-meta.xml
<CustomObject>
    <label>TAD Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TAD Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_info_aesb__c.field-meta.xml
<CustomField>
    <fullName>ordexp_info_aesb__c</fullName>
    <formula>IF(ordexp_aesb_check__c=true &amp;&amp; ordexp_stopover_check__c=true &amp;&amp; ordexp_airline_upgrade_check__c=true, IMAGE(&quot;/resource/Warning_Sign&quot;, &quot;No Image&quot;)+ &apos; Contains AE/SB &amp; Stopover &amp; Airline Upgrade&apos;,  IF(ordexp_aesb_check__c=true &amp;&amp; ordexp_stopover_check__c=false &amp;&amp; ordexp_airline_upgrade_check__c=true, IMAGE(&quot;/resource/Warning_Sign&quot;, &quot;No Image&quot;)+ &apos; Contains AE/SB &amp; Airline Upgrade&apos;,  IF(ordexp_aesb_check__c=false &amp;&amp; ordexp_stopover_check__c=true &amp;&amp; ordexp_airline_upgrade_check__c=true, IMAGE(&quot;/resource/Warning_Sign&quot;, &quot;No Image&quot;)+ &apos; Contains Stopovers &amp; Airline Upgrade&apos;, IF(ordexp_aesb_check__c=false&amp;&amp; ordexp_stopover_check__c=false &amp;&amp; ordexp_airline_upgrade_check__c=true, IMAGE(&quot;/resource/Warning_Sign&quot;, &quot;No Image&quot;)+ &apos; Contains Airline Upgrade&apos;,&apos;&apos;)
))) + &apos; &apos;+ 
IF(ordexp_aesb_check__c=false &amp;&amp; ordexp_stopover_check__c=false &amp;&amp; ordexp_airline_upgrade_check__c=false,  IF(Cancellation_Count__c &gt;0, IMAGE(&quot;/resource/Warning_Sign&quot;, &quot;No Image&quot;) +&apos; Has Cancellation&apos;, &apos;&apos;) ,  IF(Cancellation_Count__c &gt;0, &apos; &amp; Has Cancellation&apos;, &apos;&apos;) )</formula>
    <label>Info</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MP_OrderCancellationController.cls
public class MP_OrderCancellationController {
    
    public class PassengerWrapper{
        
        @AuraEnabled
        public String Name{get;set;} 
        
        @AuraEnabled
        public String NickName{get;set;} 
        
        @AuraEnabled
        public String Status {get;set;}
        
        @AuraEnabled
        public String ComponentType {get;set;}
        
        @AuraEnabled
        public String OrderLineItems {get;set;}
             
    }
    
    public class OrderInfoWrapper{
          @AuraEnabled
        public String OrderInfo {get;set;}
    }
    
    public class OrderCancellationWrapper{
        @AuraEnabled
        public List<PassengerWrapper> passengerWrapperList {get;set;}
        
        @AuraEnabled
        public OrderInfoWrapper info {get;set;}
    }
    
    
    @AuraEnabled
    public static OrderCancellationWrapper fetchOrderCancellationData(String tadOrder){
        Account acc = null;  
        if(!Test.isRunningTest()){
            User user = [SELECT Id, ContactId FROM User Where Id =:UserInfo.getUserId() LIMIT 1];
            Contact con = [SELECT Id, Account.Name,Email, Name FROM Contact WHERE Id = : user.ContactId LIMIT 1];
            acc = [SELECT Id, Name FROM Account WHERE Id =: con.AccountID LIMIT 1];
        }
        List<order_line_POE__c> orderLineLst = [SELECT Id,TAD_Order__r.ordexp_info_aesb__c,Merchant_Name__c,Order_Line_Item__c,Order_Line_Item__r.Id,AddOn__c,Component_Type__c,TAD_Order__c FROM order_line_POE__c WHERE TAD_Order__r.Id =:tadOrder];        
        Set<Id> orderLineItemIDLst = new Set<Id>();
        List<order_line_POE__c> orderLineFilteredList = new List<order_line_POE__c>();
        for(order_line_POE__c orderLines : orderLineLst){
            if(Test.isRunningTest()){
                orderLineItemIDLst.add( orderLines.Order_Line_Item__r.Id);  
				orderLineFilteredList.add(orderLines);                
            }else{                
                if(orderLines.Merchant_Name__c == acc.Name)
                {
                    orderLineItemIDLst.add(orderLines.Order_Line_Item__r.Id);
                    orderLineFilteredList.add(orderLines);
                }
            }
        }
        
        List<AddOn__c> addOnList = [SELECT Id,Passenger__r.Id,AddOn_Status__c,land_activity__r.title__c,Passenger__r.Passenger_Name__c,Passenger__r.ordexp_PAX_Nickname__c,Add_On_Type__c,Order_Line_Item__r.Id,Passenger__c FROM AddOn__c WHERE Order_Line_Item__c IN : orderLineItemIDLst ];        
        List<customer_POE__c> passengerLst = [SELECT Id,Order_Line_Item__r.Id,ordexp_PAX_Nickname__c,Passenger_Name__c,Order_Line_Item_Status__c FROM customer_POE__c WHERE order_line_item__c IN :orderLineItemIDLst];
        
        
        List<PassengerWrapper> wrapperLst = new List<PassengerWrapper>(); 
        
        for(order_line_POE__c orderLine : orderLineFilteredList){
            for(customer_POE__c pssengerObj : passengerLst){
                if((orderLine.Order_Line_Item__r.Id == pssengerObj.Order_Line_Item__r.Id)
                   && orderLine.Component_Type__c != 'Land Activity'){
                       PassengerWrapper wrapper = new PassengerWrapper();
                       if(String.isEmpty(pssengerObj.Passenger_Name__c)){
                           wrapper.Name = '--NA--';
                           
                       }else{
                           wrapper.Name = pssengerObj.Passenger_Name__c;
                       }
                       wrapper.NickName = pssengerObj.ordexp_PAX_Nickname__c;
                       wrapper.Status = pssengerObj.Order_Line_Item_Status__c;                      
                       wrapper.ComponentType = orderLine.Component_Type__c;
                       wrapper.OrderLineItems = pssengerObj.Order_Line_Item__r.Id;
                       wrapperLst.add(wrapper);
                       
                       for(AddOn__c addonObj : addOnList){
                           if(addonObj.Order_Line_Item__r.Id == pssengerObj.Order_Line_Item__r.Id &&
                              addonObj.Passenger__r.Id == pssengerObj.Id){
                                  PassengerWrapper wrapperFromAddOn = new PassengerWrapper();
                                  if(String.isEmpty(addonObj.Passenger__r.Passenger_Name__c)){
                                      wrapperFromAddOn.Name = '--NA--';
                                      
                                  }else{
                                      wrapperFromAddOn.Name = addonObj.Passenger__r.Passenger_Name__c;
                                  }
                                  wrapperFromAddOn.NickName = addonObj.Passenger__r.ordexp_PAX_Nickname__c;
                                  wrapperFromAddOn.Status = addonObj.AddOn_Status__c;
                                  if(addonObj.Add_On_Type__c == 'Land Activity'){
                                      wrapperFromAddOn.ComponentType = 'Land Activity-'+addonObj.land_activity__r.title__c;
                                  }
                                  else{
                                      wrapperFromAddOn.ComponentType = addonObj.Add_On_Type__c;
                                      
                                  }
                                  wrapperFromAddOn.OrderLineItems = addonObj.Order_Line_Item__r.Id;
                                  wrapperLst.add(wrapperFromAddOn);
                              }
                       }
                       
                   }
            }
        }
        
        OrderCancellationWrapper orderCancellWrapper = new OrderCancellationWrapper();
       
        
        String info = orderLineLst[0].TAD_Order__r.ordexp_info_aesb__c;
        OrderInfoWrapper orderWrapper = new OrderInfoWrapper();
        orderWrapper.OrderInfo = info;
        
        orderCancellWrapper.passengerWrapperList = wrapperLst;
        orderCancellWrapper.info = orderWrapper;
       
        return orderCancellWrapper;
        
    }
}