force-app/main/default/objects/AddOn__c/AddOn__c.object-meta.xml
<CustomObject>
    <label>AddOn</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AddOns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AddOn__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Deal</description>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>AddOns</relationshipLabel>
    <relationshipName>AddOns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal__c/Deal__c.object-meta.xml
<CustomObject>
    <label>Deal</label>
    <nameField>
        <label>Deal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal__c/fields/Cloned_From__c.field-meta.xml
<CustomField>
    <fullName>Cloned_From__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cloned From</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Deal</relationshipLabel>
    <relationshipName>Deal</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal__c/fields/Deal_ID_Title__c.field-meta.xml
<CustomField>
    <fullName>Deal_ID_Title__c</fullName>
    <formula>IF( ISBLANK(title__c) , 
Name&amp;&quot;-&quot;&amp;title_nz__c , 
Name&amp;&quot;-&quot;&amp;title__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Deal ID &amp; Title</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/departures_dates__c.object-meta.xml
<CustomObject>
    <label>departures dates</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>departures dates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/departures_dates__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>departures dates</relationshipLabel>
    <relationshipName>departures_dates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/Deal_Title__c.field-meta.xml
<CustomField>
    <fullName>Deal_Title__c</fullName>
    <formula>IF( NOT(ISBLANK( Deal__c )) ,  Deal__r.Deal_ID_Title__c   , IF(NOT(ISBLANK( DealID_from_Option__c )), options__r.Deal__r.Deal_ID_Title__c ,  sub_options__r.options__r.Deal__r.Deal_ID_Title__c  ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Deal + Title</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/Departure_Date_Finalised__c.field-meta.xml
<CustomField>
    <fullName>Departure_Date_Finalised__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Departure Date Finalised?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/Linked_Deal_D_O_S__c.field-meta.xml
<CustomField>
    <fullName>Linked_Deal_D_O_S__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Linked Deal(D/O/S)</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>departures dates (Linked Deal(D/O/S))</relationshipLabel>
    <relationshipName>departures_dates2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/mp_bc_available__c.field-meta.xml
<CustomField>
    <fullName>mp_bc_available__c</fullName>
    <label>BC Available</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NOT AVAILABLE</fullName>
                <default>true</default>
                <label>NOT AVAILABLE</label>
            </value>
            <value>
                <fullName>AVAILABLE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/online_status__c.field-meta.xml
<CustomField>
    <fullName>online_status__c</fullName>
    <label>Online Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Offline - Auto</fullName>
            </value>
            <value>
                <fullName>Offline - Manual</fullName>
            </value>
            <value>
                <fullName>Hidden</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/order_line_item__c/order_line_item__c.object-meta.xml
<CustomObject>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>OLI-{000000}</displayFormat>
        <label>Order Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/order_line_item__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/order_line_item__c/fields/Deal_ID_Title__c.field-meta.xml
<CustomField>
    <fullName>Deal_ID_Title__c</fullName>
    <formula>Deal__r.Deal_ID_Title__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Deal ID Title</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/order_line_item__c/fields/ordexp_departure_date__c.field-meta.xml
<CustomField>
    <fullName>ordexp_departure_date__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Note :- For Stay type Orders, change to Departure Date will be applied to all the OLIs of this Order</inlineHelpText>
    <label>Departure date</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>departures_dates__c.sub_options__c</field>
            <operation>equals</operation>
            <valueField>$Source.Sub_Options__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>departures_dates__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/TAD_Order__c.object-meta.xml
<CustomObject>
    <label>TAD Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TAD Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TAD_Order__c/fields/Cruise_Reference_Required__c.field-meta.xml
<CustomField>
    <fullName>Cruise_Reference_Required__c</fullName>
    <formula>IF(  (TEXT(ordexp_deal__r.Cruise_Cabin_Booked_by__c) ==&apos;Partner&apos;) &amp;&amp;   ordexp_cabin_bookings_outstanding__c != 0, true, false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cruise Reference Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/Deal_Title__c.field-meta.xml
<CustomField>
    <fullName>Deal_Title__c</fullName>
    <formula>ordexp_deal__r.title__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Deal Title</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_departure_date__c.field-meta.xml
<CustomField>
    <fullName>ordexp_departure_date__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Departure date</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>(1 OR 2) AND 3</booleanFilter>
        <filterItems>
            <field>departures_dates__c.Deal__c</field>
            <operation>equals</operation>
            <valueField>$Source.ordexp_deal__c</valueField>
        </filterItems>
        <filterItems>
            <field>departures_dates__c.options__c</field>
            <operation>equals</operation>
            <valueField>$Source.ordexp_option__c</valueField>
        </filterItems>
        <filterItems>
            <field>departures_dates__c.online_status__c</field>
            <operation>equals</operation>
            <value>Online</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>departures_dates__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>TAD_Orders_DD</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_master_status__c.field-meta.xml
<CustomField>
    <fullName>ordexp_master_status__c</fullName>
    <label>Master status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
                <default>true</default>
                <label>On Hold</label>
            </value>
            <value>
                <fullName>Temporary Hold</fullName>
            </value>
            <value>
                <fullName>Secured</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Travelled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>In Progress-Cruise only</fullName>
                <isActive>false</isActive>
                <label>In Progress-Cruise only</label>
            </value>
            <value>
                <fullName>In Progress-Flight only</fullName>
                <isActive>false</isActive>
                <label>In Progress-Flight only</label>
            </value>
            <value>
                <fullName>In Progress-Flights + Cruise</fullName>
                <isActive>false</isActive>
                <label>In Progress-Flights + Cruise</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_sub_status__c.field-meta.xml
<CustomField>
    <fullName>ordexp_sub_status__c</fullName>
    <label>Sub status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ordexp_master_status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial Payment Pending</fullName>
            </value>
            <value>
                <fullName>Cancellation Request</fullName>
            </value>
            <value>
                <fullName>Class (Sub Option) - Accom/Cabin Upgrade</fullName>
            </value>
            <value>
                <fullName>Duration/Extention (Option) - Upgrade</fullName>
            </value>
            <value>
                <fullName>Flight Quote Request</fullName>
            </value>
            <value>
                <fullName>Internal Correction/Change</fullName>
            </value>
            <value>
                <fullName>PAX Change Pending</fullName>
            </value>
            <value>
                <fullName>Paid - PIF/s Overdue</fullName>
            </value>
            <value>
                <fullName>Paid - PIF/s Due</fullName>
            </value>
            <value>
                <fullName>Stay Booking - No Ticketing Required</fullName>
            </value>
            <value>
                <fullName>Cabins Pending - Mins Not Met</fullName>
            </value>
            <value>
                <fullName>Flights Pending - Mins Not Met</fullName>
            </value>
            <value>
                <fullName>Flights Pending - Out of Range</fullName>
            </value>
            <value>
                <fullName>Flights Pending - Ready to Ticket</fullName>
            </value>
            <value>
                <fullName>Cabins Pending/Flights Booked - Cabin Ready to Ticket</fullName>
            </value>
            <value>
                <fullName>Cabins Booked</fullName>
            </value>
            <value>
                <fullName>Flights Booked</fullName>
            </value>
            <value>
                <fullName>Cabins Booked/Flights Booked</fullName>
            </value>
            <value>
                <fullName>BC Sent</fullName>
            </value>
            <value>
                <fullName>TP Sent &amp; Cruise Ticket Pending</fullName>
            </value>
            <value>
                <fullName>Travelling</fullName>
            </value>
            <value>
                <fullName>Survey Sent</fullName>
            </value>
            <value>
                <fullName>Survey Returned</fullName>
            </value>
            <value>
                <fullName>Expired/Time out</fullName>
            </value>
            <value>
                <fullName>Offloaded</fullName>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Customer Request</fullName>
            </value>
            <value>
                <fullName>Min Number - Credit/Refund</fullName>
            </value>
            <value>
                <fullName>Pax No Show</fullName>
            </value>
            <value>
                <fullName>Flights Ticketed - NO S/O</fullName>
            </value>
            <value>
                <fullName>Flights Ticketed - S/O Req</fullName>
            </value>
            <value>
                <fullName>Cabins Pending/Flights Ticketed - NO S/O</fullName>
            </value>
            <value>
                <fullName>Cabins Pending/Flights Ticketed - S/O Req</fullName>
            </value>
            <value>
                <fullName>Cabins Pending - Ready to book</fullName>
            </value>
            <value>
                <fullName>Cabins Booked/Flights Ticketed - NO S/O</fullName>
            </value>
            <value>
                <fullName>Cabins Booked/Flights Ticketed - S/O Req</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TAD_Order__c/recordTypes/TAD.recordType-meta.xml
<RecordType>
    <fullName>TAD</fullName>
    <active>true</active>
    <label>TAD</label>
</RecordType>

force-app/main/default/classes/DeparturesDateTriggerHandler.cls
/**
* ────────────────────────────────────────────────────────────────────────────────────────────────
* DeparturesDateTriggerHandler
* Purpose: Apex Class Used for DeparturedatescTrigger .
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* @createdBy Samriddh Malik  <sachin@psagtechnologies.com.p1>
* @lastModifiedBy Samriddh Malik  <sachin@psagtechnologies.com.p1>

* @version        1.0
* 
* @modified       2020-02-23
* @systemLayer    Apex Class
* ────────────────────────────────────────────────────────────────────────────────────────────────── */
public class DeparturesDateTriggerHandler {
    
    public static void orderValidationAndFinalization(List<departures_dates__c> ddListOld , List<departures_dates__c> ddListNew, Map<Id,departures_dates__c > ddOldMap ){
        
        Set<Id> ddOrderTovalidate = new Set<Id>();
        for(departures_dates__c dd : ddListNew){
            if(dd.Departure_Date_Finalised__c == true && ddOldMap.get(dd.id).Departure_Date_Finalised__c== false && dd.mp_bc_available__c=='NOT AVAILABLE'){
                if(dd.online_status__c == 'Online'){
                    dd.addError('Make Departure Date Offline before Finalizing');  
                } else{
                    System.debug('Inside Else');
                    ddOrderTovalidate.add(dd.id);     
                }
            }
        }
        system.debug('ddOrderTovalidate-->'+ddOrderTovalidate);
        // Logic for Order Validation and email alert
        if(!ddOrderTovalidate.isEmpty()){
            //List<departures_dates__c> deptListToUpdate =  new List<departures_dates__c>();
            Map<Id,List<TAD_Order__c>> orderWithIssue = new Map<Id,List<TAD_Order__c>>();
            /*******************Edited By hansa : Added Cruise_Reference_Required__c field in query****************/
            List<TAD_Order__c> ordersToVerify = [Select id , Name,ordexp_sub_status__c,ordexp_departure_date__c,Cruise_Reference_Required__c from TAD_Order__c where ordexp_departure_date__c IN: ddOrderTovalidate ];
            
            system.debug('ordersToVerify-->'+ordersToVerify);
            /*******************Edited By hansa ***********************************/
            if(!ordersToVerify.isEmpty()){
                for(TAD_Order__c ord : ordersToVerify){
                    
                    if  ( ! (ord.ordexp_sub_status__c == 'Cabins Booked/Flights Ticketed - NO S/O'  || (ord.ordexp_sub_status__c == 'Cabins Pending/Flights Ticketed - NO S/O'  && ord.Cruise_Reference_Required__c==true )
                             ||  ord.ordexp_sub_status__c == 'Cabins Booked/Flights Ticketed - S/O Req' || (ord.ordexp_sub_status__c == 'Cabins Pending/Flights Ticketed - S/O Req'  && ord.Cruise_Reference_Required__c==true)
                             ||  ord.ordexp_sub_status__c == 'Flights Ticketed - NO S/O'  || ord.ordexp_sub_status__c == 'Flights Ticketed - S/O Req' || (ord.ordexp_sub_status__c == 'Cabins Pending - Ready to book'  && ord.Cruise_Reference_Required__c==true)    
                            )){
                                if(!orderWithIssue.containsKey(ord.ordexp_departure_date__c)){
                                    orderWithIssue.put(ord.ordexp_departure_date__c, new List<TAD_Order__c>{ord});     
                                }else{
                                    List<TAD_Order__c> ordList = orderWithIssue.get(ord.ordexp_departure_date__c);
                                    ordList.add(ord);
                                    orderWithIssue.put(ord.ordexp_departure_date__c, ordList);
                                } 
                            }  
                } 
            }
            
            System.debug('orderWithIssue:'+orderWithIssue);
            
            EmailTemplate emailTemp = new EmailTemplate();
            emailTemp = [Select Id, Name,DeveloperName, Subject, Body, HtmlValue from EmailTemplate where DeveloperName = 'Template_For_Email_To_Merchant_For_BC_Due_Date' LIMIT 1];
            
            system.debug('emailTemp -->'+emailTemp.Id);
            Contact targetDummyCon = [select Id from Contact limit 1];
            Map<String, String> param2Emailtemplate = new Map<String, string>();
            
            for(departures_dates__c dds :  ddListNew){
                if( !orderWithIssue.containsKey(dds.Id) ){
                    
                    dds.mp_bc_available__c='AVAILABLE';
                    
                } else if(orderWithIssue.containsKey(dds.Id) && orderWithIssue.get(dds.Id).size() !=0){
                    
                    if(emailTemp.Id != null){
                        
                        system.debug('here in email');
                        String recepient = System.Label.RecepientForEarlyBooking;
                        list<string> toAddresses = new list<string>();
                        toAddresses.add(recepient);
                        toAddresses.add('samriddhmalik@gmail.com');
                        system.debug('emailTemp '+emailTemp.HtmlValue); 
                        String htmlBody = emailTemp.HtmlValue != null ? emailTemp.HtmlValue : '<html></html>';
                        htmlBody = htmlBody.containsIgnoreCase(']]>') ?  htmlBody.remove(']]>') : htmlBody;
                        htmlBody = htmlBody.containsIgnoreCase('{!departures_dates__c.Name}') ? htmlBody.replace('{!departures_dates__c.Name}', dds.Name) :htmlBody ;
                        for(TAD_Order__c ord : orderWithIssue.get(dds.Id)){
                            htmlBody = htmlBody + ' <a href='+System.URL.getSalesforceBaseUrl().toExternalForm()+'"/'+ord.Id+'">Click Here</a><br/>';
                        }
                        system.debug('htmlBody here ------'+htmlBody);
                        param2Emailtemplate.put('htmlBody', htmlBody);
                        param2Emailtemplate.put('Subject', emailTemp.Subject);
                        //param2Emailtemplate.put('plainTextBody', emailTemp.Body);
                        
                        Utility_SingleEmailMessageHandler.EmailHandlerMethodForBeforeTrigger(toAddresses, null ,param2Emailtemplate,  false, false );
                        
                        if(!Test.isRunningTest()){
                            
                            dds.addError('One or More TAD Order has issue. Please check your Email');                            
                        }
                        
                        
                    }
                    
                }  
                
            }
            
            
            
        }
        // Logic for Order Validation and email alert ends
    }
    
    public static void emailAlertsOnDepDates(List<departures_dates__c> ddListOld , List<departures_dates__c> ddListNew, Map<Id,departures_dates__c > ddOldMap ){
        
        Set<Id> dealBCReport = new Set<Id>();
        Set<Id> dealSalesReport = new Set<Id>();
        Map<Id,departures_dates__c> bcDepRecordsMap = new  Map<Id,departures_dates__c>();
        Map<Id,departures_dates__c> salesDepRecordsMap = new  Map<Id,departures_dates__c>();
        
        for(departures_dates__c dd :  ddListNew ){
            /********************************Edited By Hansa : Date - 13-03-2020***************************************************/
            if(dd.online_status__c=='Online' && (ddOldMap.get(dd.id) != null && ddOldMap.get(dd.id).online_status__c=='Offline - Manual') && dd.mp_bc_available__c=='NOT AVAILABLE' ){
                dealSalesReport.add(dd.Linked_Deal_D_O_S__c); 
                salesDepRecordsMap.put(dd.id,dd);
            }
            else if(dd.Departure_Date_Finalised__c==true && dd.mp_bc_available__c=='AVAILABLE' && (ddOldMap.get(dd.id).mp_bc_available__c=='NOT AVAILABLE' ) ){
                dealBCReport.add(dd.Linked_Deal_D_O_S__c);
                bcDepRecordsMap.put(dd.id,dd);
            }
            
        }
        /*
        // Sales Report Availability Mailing
        if(!salesDepRecordsMap.isEmpty()){
            EmailTemplate salesReportEmailTemp = [Select Id, Name,DeveloperName, Subject, Body, HtmlValue from EmailTemplate where DeveloperName = 'Sales_Report_Format' ];
            Map<Id,Set<String>> dealToAddress  = TADUtils.emailAddressMerchants(dealSalesReport); 
            Map<String, String> param2Emailtemplate = new Map<String, string>();
            Contact Con = [SELECT Id, Name from Contact LIMIT 1];
            for(departures_dates__c salesDD : salesDepRecordsMap.values() ){
                
                Set<string> toAddressSet = dealToAddress.get(salesDD.Linked_Deal_D_O_S__c);
                List<string> toAddress =  new  List<string> ();
                toAddress.addAll(toAddressSet); 
                */
                /********* Utility Class For Single Email Message ******************Edited By hansa : 13-03-2020******************/
               /* if(salesReportEmailTemp !=null)
                    Utility_SingleEmailMessageHandler.EmailHandlerMethodForTargetObject(toAddress, null, false, false, false, Con.Id, salesReportEmailTemp.Id, salesDD.Id, null  );
                
            }
            
        }*/
        // Sales Report Availability Mailing Ends
        
        // Booking Confirmation Mailing
        /*
        if(!bcDepRecordsMap.isEmpty()){
            EmailTemplate BookingConfirmation = [Select Id, Name,DeveloperName, Subject, Body, HtmlValue from EmailTemplate where DeveloperName = 'Booking_Confirmation' ];
            Map<Id,Set<String>> dealToAddress  = TADUtils.emailAddressMerchants(dealBCReport); 
            Map<String, String> param2Emailtemplate = new Map<String, string>(); 
            Contact Con = [SELECT Id, Name from Contact LIMIT 1];
            Id communityId = [SELECT ID, name FROM Network WHere Name = 'TAD Merchant Portal' limit 1].Id;
            String communityUrl = Network.getLoginUrl(communityId).containsIgnoreCase('login') ? Network.getLoginUrl(communityId).remove('login') : Network.getLoginUrl(communityId) ;
            system.debug('communityUrl '+communityUrl);
            for(departures_dates__c dd : bcDepRecordsMap.values() ){
                
                Set<string> toAddressSet = dealToAddress.get(dd.Linked_Deal_D_O_S__c);
                List<string> toAddress =  new  List<string> ();
                toAddress.addAll(toAddressSet); 
                String htmlBody = BookingConfirmation.HtmlValue != null ? BookingConfirmation.HtmlValue : '<html></html>';
                htmlBody = htmlBody.containsIgnoreCase(']]>') ?  htmlBody.remove(']]>') : htmlBody;
                htmlBody = htmlBody.containsIgnoreCase('{!departures_dates__c.Name}') ? htmlBody.replace('{!departures_dates__c.Name}', dd.Name) :htmlBody ;
                htmlBody = htmlBody.containsIgnoreCase('{!departures_dates__c.Deal_Title__c}') ? htmlBody.replace('{!departures_dates__c.Deal_Title__c}', dd.Deal__r.Deal_ID_Title__c) :htmlBody ;
                htmlBody = htmlBody + ' <a href="'+communityUrl+'booking-confirmation?dealId='+dd.Linked_Deal_D_O_S__c + '&ddId='+dd.Id+'">Click Here</a>';
                
                system.debug('htmlBody here ------'+htmlBody);
                param2Emailtemplate.put('htmlBody', htmlBody);
                param2Emailtemplate.put('Subject', BookingConfirmation.Subject);
                //param2Emailtemplate.put('plainTextBody', emailTemp.Body);
                
                //Utility_SingleEmailMessageHandler.EmailHandlerMethodForTargetObject(toAddress, null ,,  false, false );
                
                
               
                if(BookingConfirmation != null && !toAddress.isEmpty())
                    Utility_SingleEmailMessageHandler.EmailHandlerMethodForTargetObject(toAddress, null, false, false, false, Con.Id, null, dd.Id, param2Emailtemplate  );
                
            } 
            // Booking Confirmation Mailing ends
            
            // Make Tad Orders as BC SENT
            Set<Id>oliIds = new Set<Id>();
            List<TAD_Order__c> depOrders = [select id, ordexp_master_status__c, ordexp_sub_status__c ,(Select id from Order_Line_Items_orders__r)from TAD_Order__c where ordexp_departure_date__c IN: bcDepRecordsMap.keySet()];
            
            
            if(!depOrders.isEmpty()){
                for(TAD_Order__c dorder : depOrders)
                {
                    dorder.ordexp_master_status__c = 'In Progress';
                    dorder.ordexp_sub_status__c = 'BC Sent';
                    dorder.ordexp_bc_sent__c = true;
                    for(order_line_item__c ol :dorder.Order_Line_Items_orders__r){
                        oliIds.add(ol.id);  
                    }
                }
                
                update depOrders;
                
                List<AddOn__c> addonBooked = [Select id,AddOn_Status__c from AddOn__c where Order_Line_Item__c IN:oliIds];
                
                for(AddOn__c add : addonBooked){
                    if(add.AddOn_Status__c !='Cancelled' && add.AddOn_Status__c !='Booked' ){
                        add.AddOn_Status__c='Booked'; 
                    }
                }
                update addonBooked;
            }
            
            // TAD Order BC Sent ends
            
        } */
        
    }
    
    public static void minNotMetCheckAndUpdateOrders (List<departures_dates__c> ddListNew, Map<Id,departures_dates__c > ddOldMap ){
        
        Set<Id> ddIds = new Set<Id>();
        Set<Id> ddIds1 = new Set<Id>();
        List<tad_order__c> orderToUpdate = new List<tad_order__c>();
        List<tad_order__c> orderToUpdate1 = new List<tad_order__c>();
        
        for(departures_dates__c dd : ddListNew) {
            if(dd.MinNotMetApproval__c != ddOldMap.get(dd.id).MinNotMetApproval__c && dd.MinNotMetApproval__c=='In Progress'){
                ddIds.add(dd.id); 
            }else if(dd.MinNotMetApproval__c != ddOldMap.get(dd.id).MinNotMetApproval__c && dd.MinNotMetApproval__c=='Rejected'){
                ddIds1.add(dd.id);
            }
        }
        
        if(!ddIds.isEmpty()){
            List<tad_order__c> TadOrderList = [Select id ,ordexp_status_check__c,ordexp_total_payment_received__c from tad_order__c where ordexp_departure_date__c IN:ddIds AND ordexp_sub_status__c !='Internal Correction/Change'  AND ordexp_master_status__c !='Cancelled' ];    
            if(!TadOrderList.isEmpty()){
                for(tad_order__c order : TadOrderList){
                    if(order.ordexp_total_payment_received__c!=0){
                        order.ordexp_sub_status__c ='Internal Correction/Change';
                        order.ordexp_master_status__c  ='Temporary Hold';
                        orderToUpdate.add(order) ;
                    }
                }
            }  
        }
        if(!orderToUpdate.isEmpty()){ 
            update orderToUpdate;
        }
        
        if(!ddIds1.isEmpty()){
            List<tad_order__c> TadOrderList = [Select id ,ordexp_status_check__c from tad_order__c where ordexp_departure_date__c IN:ddIds1 AND ordexp_sub_status__c ='Internal Correction/Change'];    
            if(!TadOrderList.isEmpty()){
                for(tad_order__c order : TadOrderList){
                    if(order.ordexp_status_check__c == true){
                        order.ordexp_status_check__c=false; 
                    }
                    else{
                        order.ordexp_status_check__c=true;  
                    }
                    orderToUpdate1.add(order) ;
                }
            }  
        }
        if(!orderToUpdate1.isEmpty()){ 
            update orderToUpdate1;
        }
        
    }
    
    
    public static void approvalProcessValidation(List<departures_dates__c> ddListOld , List<departures_dates__c> ddListNew, Map<Id,departures_dates__c > ddOldMap) {
        Map<Id, departures_dates__c> rejectedStatements 
            = new Map<Id, departures_dates__c>{};
                
                for(departures_dates__c inv: ddListNew)
            {
                /* 
Get the old object record, and check if the approval status 
field has been updated to rejected. If so, put it in a map 
so we only have to use 1 SOQL query to do all checks.
*/
                departures_dates__c oldInv = ddOldMap.get(inv.Id);
                
                if (oldInv.Approval_Status__c != 'Rejected' 
                    && inv.Approval_Status__c == 'Rejected')
                { 
                    rejectedStatements.put(inv.Id, inv);  
                }
            }
        
        if (!rejectedStatements.isEmpty())  
        {
            // UPDATE 2/1/2014: Get the most recent approval process instance for the object.
            // If there are some approvals to be reviewed for approval, then
            // get the most recent process instance for each object.
            List<Id> processInstanceIds = new List<Id>{};
                
                for (departures_dates__c invs : [SELECT (SELECT ID
                                                         FROM ProcessInstances
                                                         ORDER BY CreatedDate DESC
                                                         LIMIT 1)
                                                 FROM departures_dates__c
                                                 WHERE ID IN :rejectedStatements.keySet()])
            {
                processInstanceIds.add(invs.ProcessInstances[0].Id);
            }
            
            // Now that we have the most recent process instances, we can check
            // the most recent process steps for comments.  
            for (ProcessInstance pi : [SELECT TargetObjectId,
                                       (SELECT Id, StepStatus, Comments 
                                        FROM Steps
                                        ORDER BY CreatedDate DESC
                                        LIMIT 1 )
                                       FROM ProcessInstance
                                       WHERE Id IN :processInstanceIds
                                       ORDER BY CreatedDate DESC])   
            {                   
                if ((pi.Steps[0].Comments == null || 
                     pi.Steps[0].Comments.trim().length() == 0))
                {
                    String message = Label.ErrorRejectionComment;  
                    rejectedStatements.get(pi.TargetObjectId).addError(message);
                    
                }
            }  
        }
    }
    
    
}