force-app/main/default/objects/Cancellation_Refund_POE__c/Cancellation_Refund_POE__c.object-meta.xml
<CustomObject>
    <label>Cancellation/Refund</label>
    <nameField>
        <displayFormat>CanRef-{00000}</displayFormat>
        <label>Cancelation/Refund Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cancellations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cancellation_Refund_POE__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Documentation</fullName>
            </value>
            <value>
                <fullName>Pending CS Approval</fullName>
            </value>
            <value>
                <fullName>CS Approved</fullName>
            </value>
            <value>
                <fullName>CS Rejected</fullName>
            </value>
            <value>
                <fullName>Pending Finance Approval</fullName>
            </value>
            <value>
                <fullName>Finance Approved</fullName>
            </value>
            <value>
                <fullName>Finance Rejected</fullName>
            </value>
            <value>
                <fullName>More Information Required by Finance</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Approved-Refund Not Processed</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Approved-Not Processed</fullName>
                <isActive>false</isActive>
                <label>Approved - Refund Not Processed</label>
            </value>
            <value>
                <fullName>Not Approved</fullName>
                <isActive>false</isActive>
                <label>Not Approved</label>
            </value>
            <value>
                <fullName>Not Submitted</fullName>
                <isActive>false</isActive>
                <label>Not Submitted</label>
            </value>
            <value>
                <fullName>Submitted and Pending</fullName>
                <isActive>false</isActive>
                <label>Submitted and Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cancellation_Refund_POE__c/fields/CS_Refund_Rejection_Reason__c.field-meta.xml
<CustomField>
    <fullName>CS_Refund_Rejection_Reason__c</fullName>
    <label>CS Refund Rejection Reason</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Cancellation_Refund_POE__c/fields/Finance_Refund_Rejection_Reason__c.field-meta.xml
<CustomField>
    <fullName>Finance_Refund_Rejection_Reason__c</fullName>
    <label>Finance Refund Rejection Reason</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/CanRefAutoCommentUpdateFuture.cls
public class  CanRefAutoCommentUpdateFuture {
    @future
    public static void  updateComments(Set<Id> canrefRecsIds){
        
        Map<Id,ProcessInstance> mapOfIdAgainstProcessInstance = new Map<Id,ProcessInstance>();
        List<ProcessInstance> newListOfProcessInstance = [SELECT Id, TargetObjectId, Status,(SELECT Id, StepStatus, Comments FROM Steps where StepStatus ='Rejected' Order by CreatedDate DESC) FROM ProcessInstance where TargetObjectId IN:canrefRecsIds order by CompletedDate DESC Limit 1];
        for(ProcessInstance pr: newListOfProcessInstance){
            mapOfIdAgainstProcessInstance.put(pr.TargetObjectId,pr);
        }
        
        List<Cancellation_Refund_POE__c> newListOfCanRef = [Select id, Approval_Status__c,CS_Refund_Rejection_Reason__c,Finance_Refund_Rejection_Reason__c from Cancellation_Refund_POE__c where id in: canrefRecsIds];
        
        system.debug('newListOfProcessInstance'+newListOfProcessInstance);
        //system.debug('newListOfProcessInstanceSteps'+newListOfProcessInstance[0].Steps);
        List<Cancellation_Refund_POE__c> listToBeUpdated = new List<Cancellation_Refund_POE__c>();
        if(!mapOfIdAgainstProcessInstance.isEmpty()){
            for(Cancellation_Refund_POE__c canRefund : newListOfCanRef){
                system.debug('canRefund.CS_Refund_Rejection_Reason__c'+canRefund.CS_Refund_Rejection_Reason__c);
                if(canRefund.Approval_Status__c == 'CS Rejected'){
                    
                    canRefund.CS_Refund_Rejection_Reason__c= (canRefund.CS_Refund_Rejection_Reason__c==null?'':canRefund.CS_Refund_Rejection_Reason__c)
                        + (mapOfIdAgainstProcessInstance.get(canRefund.Id).Steps[0].Comments==null?'': '\n' +mapOfIdAgainstProcessInstance.get(canRefund.Id).Steps[0].Comments);
                    
                    listToBeUpdated.add(canRefund);
                }else if(canRefund.Approval_Status__c == 'Finance Rejected'){
                    
                    canRefund.Finance_Refund_Rejection_Reason__c= (canRefund.Finance_Refund_Rejection_Reason__c==null?'':canRefund.Finance_Refund_Rejection_Reason__c)
                        + (mapOfIdAgainstProcessInstance.get(canRefund.Id).Steps[0].Comments==null?'': '\n' +mapOfIdAgainstProcessInstance.get(canRefund.Id).Steps[0].Comments);
                    listToBeUpdated.add(canRefund);
                }else{
                    system.debug('Thanks!');
                }
            }
            update listToBeUpdated;
        }
        
        
        
        
    } 
}