force-app/main/default/objects/Allocation__c/Allocation__c.object-meta.xml
<CustomObject>
    <description>Auto Generated Name: {DEAL ID}-{DATE}-{POOL DIFFERENTIATOR} Example 1234-2020-11-1-A</description>
    <label>Allocation</label>
    <nameField>
        <label>Allocation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Allocation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Allocation__c/fields/Allocation_Unique_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Allocation_Unique_Identifier__c</fullName>
    <description>This is a unique identifier for the Allocation of Room types.</description>
    <externalId>true</externalId>
    <label>Allocation Unique Identifier</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Allocation__c/fields/comment__c.field-meta.xml
<CustomField>
    <fullName>comment__c</fullName>
    <inlineHelpText>Which option/suboption is this allocation for? Include a list of targeted options/suboption titles for this date allocation...</inlineHelpText>
    <label>Comment</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Allocation__c/fields/deal__c.field-meta.xml
<CustomField>
    <fullName>deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Allocation</relationshipLabel>
    <relationshipName>Allocation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Allocation__c/fields/Total_Allocation__c.field-meta.xml
<CustomField>
    <fullName>Total_Allocation__c</fullName>
    <label>Total Allocation</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Deal__c/Deal__c.object-meta.xml
<CustomObject>
    <label>Deal</label>
    <nameField>
        <label>Deal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal__c/fields/Channel_Partner__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner__c</fullName>
    <label>Channel Partner</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Siteminder</fullName>
                <default>true</default>
                <label>Siteminder</label>
            </value>
            <value>
                <fullName>TravelClick</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal__c/fields/Cloned_From__c.field-meta.xml
<CustomField>
    <fullName>Cloned_From__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cloned From</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Deal</relationshipLabel>
    <relationshipName>Deal</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal__c/fields/Hotel_Code__c.field-meta.xml
<CustomField>
    <fullName>Hotel_Code__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Hotel Code</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Deal__c/recordTypes/Hotel.recordType-meta.xml
<RecordType>
    <fullName>Hotel</fullName>
    <active>true</active>
    <description>This isa new Record Type, for integrating with Siteminder/TravelClcik (Deal shall work as the primary object -- HOTEL).</description>
    <label>Hotel</label>
</RecordType>

force-app/main/default/objects/sub_options__c/sub_options__c.object-meta.xml
<CustomObject>
    <label>Sub Options</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/sub_options__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Sub Options</relationshipLabel>
    <relationshipName>Sub_Options</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sub_options__c/fields/Hotel_Code__c.field-meta.xml
<CustomField>
    <fullName>Hotel_Code__c</fullName>
    <formula>Deal__r.Hotel_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Hotel Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sub_options__c/fields/Rate_Plan_Code__c.field-meta.xml
<CustomField>
    <fullName>Rate_Plan_Code__c</fullName>
    <formula>Rate_Plan__r.Rate_Plan_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Rate Plan Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sub_options__c/fields/Room_Type_Code__c.field-meta.xml
<CustomField>
    <fullName>Room_Type_Code__c</fullName>
    <label>Room Type Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TravelClick_OTAConnect_Errors__mdt/TravelClick_OTAConnect_Errors__mdt.object-meta.xml
<CustomObject>
    <description>This contains the Error Handling Data for OTA Connect by Travel Click.</description>
    <label>TravelClick_OTAConnect Error</label>
    <pluralLabel>TravelClick_OTAConnect Error</pluralLabel>
</CustomObject>

force-app/main/default/objects/TravelClick_OTAConnect_Errors__mdt/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <label>Error Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TravelClick_OTAConnect_Errors__mdt/fields/Short_Text__c.field-meta.xml
<CustomField>
    <fullName>Short_Text__c</fullName>
    <label>Short Text</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/UpdateAllocationValues_OTAConnect.cls
@RestResource(urlmapping='/updateTotalAllocations')
global class UpdateAllocationValues_OTAConnect {
    
    global class mainWrapper{
        global POS POS{get;set;}
        global Inventories Inventories{get;set;}
    }
    
    global class POS{
        global Source Source{get;set;}
    }
    
    global class Source{
        global BookingChannel BookingChannel{get;set;}
    }
    
    global class BookingChannel{
        global integer Type{get;set;}
        global CompanyName CompanyName{get;set;} 
    }
    
    global class CompanyName{
        global string Code{get;set;}
        global string value{get;set;}  
    }
    
    global class Inventories{
        global string HotelCode{get;set;}
        global List<Inventory> Inventory{get;set;}
    }
    
    global class Inventory{
        global StatusApplicationControl StatusApplicationControl{get;set;}
        global InvCounts InvCounts{get;set;}
    }
    
    global class StatusApplicationControl{
        global string Start{get;set;}
        global string EndDate{get;set;}   // Needs to be communicated with the Microservice Team.
        global string InvTypeCode{get;set;}
        global string RatePlanCode{get;set;}
    }
    
    global class InvCounts{
        global InvCount InvCount{get;set;}
    }
    
    global class InvCount{
        global integer Count{get;set;}
        global integer CountType{get;set;}
    }
    
    global class responseStructure{    
        global Errors Errors {get;set;}
        global String successMessage {get;set;}       
    }
    
    global class Errors{
        global Error Error{get;set;}
    }
    
    global class Error{     
        global integer errorType{get;set;}
        global integer Code{get;set;}
        global string ShortText{get;set;} 
        global string errorMessage_Value{get;set;}
    } 
    
    @HttpPost
    global static responseStructure doPost(){
        
        responseStructure response = new responseStructure();
        RestRequest req = RestContext.request;
        string requestBodyString = req.requestBody.tostring();
        
        mainWrapper mainWrap = (mainWrapper)JSON.deserialize(requestBodyString, mainWrapper.class);
        system.debug('mainWrap '+mainWrap);
        if(mainWrap.Inventories.HotelCode != null || mainWrap.Inventories.HotelCode != ''){
            
            List<Deal__c> hotelList = [Select id, Hotel_Code__c from Deal__c where Hotel_Code__c =: mainWrap.Inventories.hotelCode and RecordType.Name = 'Hotel' and Channel_Partner__c = 'TravelClick'];
            if(hotelList.isEmpty()){              
                TravelClick_OTAConnect_Errors__mdt  invalidHotelCodeError = [Select id, Code__c , Short_Text__c , Type__c, Error_Message__c  from TravelClick_OTAConnect_Errors__mdt where DeveloperName = 'Invalid_Hotel'];
                Errors errorsInstance = new Errors();
                Error errorD = new Error();
                errorD.errorType = integer.valueOf(invalidHotelCodeError.Type__c);
                errorD.Code = integer.valueOf(invalidHotelCodeError.Code__c);
                errorD.ShortText = invalidHotelCodeError.Short_Text__c;  
                errorD.errorMessage_Value =  invalidHotelCodeError.Error_Message__c +' '+mainWrap.Inventories.HotelCode;
                errorsInstance.Error = errorD;
                response.Errors = errorsInstance;      
            }else{
                
                Set<String> RatePlanCodeSet = new Set<String>();
                Set<String> InvTypeCodeSet = new Set<String>();
                Map<String,sub_options__c > mapOfRatePlanCodeWithRoomType = new Map<String,sub_options__c>();
                
                for(Inventory  ava : mainWrap.Inventories.Inventory ){
                    RatePlanCodeSet.add(ava.statusApplicationControl.ratePlanCode);                      
                    InvTypeCodeSet.add(ava.statusApplicationControl.invTypeCode);
                }
                
                List<sub_options__c  > roomTypesList = new List<sub_options__c >();
                if(!RatePlanCodeSet.isEmpty() && !InvTypeCodeSet.isEmpty()){
                    roomTypesList = [Select id, Room_Type_Code__c, Rate_Plan_Code__c, Deal__c from sub_options__c  where Room_Type_Code__c in: InvTypeCodeSet and Rate_Plan_Code__c in:RatePlanCodeSet and Hotel_Code__c =: mainWrap.Inventories.hotelCode and Deal__r.RecordType.Name = 'Hotel' and RecordType.Name = 'Room Type'];
                }
                
                if(roomTypesList.isEmpty()){
                    TravelClick_OTAConnect_Errors__mdt  invalidRoomType = [Select id, Code__c , Short_Text__c , Type__c from TravelClick_OTAConnect_Errors__mdt where DeveloperName = 'Invalid_Room_Type'];       
                    Errors errorsInstance = new Errors();
                    Error errorD = new Error();
                    errorD.errorType = integer.valueOf(invalidRoomType.Type__c);
                    errorD.Code = integer.valueOf(invalidRoomType.Code__c);
                    errorD.ShortText = invalidRoomType.Short_Text__c;
                    errorD.errorMessage_Value = 'No rooms have been found to exist under the Hotel Code: '+mainWrap.Inventories.HotelCode;
                    errorsInstance.Error = errorD;
                    response.Errors = errorsInstance;    
                }else{
                    for(sub_options__c rt : roomTypesList){                       
                        mapOfRatePlanCodeWithRoomType.put(rt.Rate_Plan_Code__c,rt);                       
                    }
                    
                    Map<String, Allocation__c> newMapValues = new Map<String, Allocation__c>();
                    for(Inventory ava : mainWrap.Inventories.Inventory){
                        
                        
                        Set<Date> datesSet = new Set<Date>();
                        
                        List<String> startDateList = ava.StatusApplicationControl.Start.split('-');
                        List<String> endDateList = ava.StatusApplicationControl.EndDate.split('-');
                        
                        Date startDateToBeSet = date.newInstance(integer.valueOf(startDateList[0]),integer.valueOf(startDateList[1]),integer.valueOf(startDateList[2])); 
                        
                        Date endDateToBeSet = date.newInstance(integer.valueOf(endDateList[0]),integer.valueOf(endDateList[1]),integer.valueOf(endDateList[2]));
                        
                        
                        Integer diff  = startDateToBeSet.daysBetween(endDateToBeSet);
                        Integer inclusiveDates = diff+1;
                        
                        for(integer i = 0; i<inclusiveDates;i++){
                            
                            if(datesSet.isEmpty()){
                                datesSet.add(startDateToBeSet);
                            }else{
                                datesSet.add(startDateToBeSet+i);
                            }
                        }
                        
                        system.debug('datesSet'+datesSet);
                        
                        for(Date dt : datesSet){                          
                            String uniqueString = mainWrap.Inventories.hotelCode+ava.statusApplicationControl.invTypeCode+ava.statusApplicationControl.ratePlanCode+'-'+string.valueOf(dt);                                 
                            Allocation__c allocation1 = new Allocation__c();
                            allocation1.Name = uniqueString;
                            allocation1.Allocation_Unique_Identifier__c = uniqueString;
                            allocation1.comment__c = 'TESTCOMMENT';
                            allocation1.Total_Allocation__c = Integer.valueOf(ava.InvCounts.InvCount.Count);
                            newMapValues.put(uniqueString, allocation1);
                        }
                    }
                    
                    if(!newMapValues.isEmpty()){                       
                        upsert newMapValues.values() Allocation_Unique_Identifier__c;
                        response.successMessage = 'Success';                        
                    }
                }         
            }        
        }    
        return response;
    }
    
}