force-app/main/default/objects/Allocation__c/Allocation__c.object-meta.xml
<CustomObject>
    <description>Auto Generated Name: {DEAL ID}-{DATE}-{POOL DIFFERENTIATOR} Example 1234-2020-11-1-A</description>
    <label>Allocation</label>
    <nameField>
        <label>Allocation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Allocation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Allocation__c/fields/deal__c.field-meta.xml
<CustomField>
    <fullName>deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Allocation</relationshipLabel>
    <relationshipName>Allocation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal__c/Deal__c.object-meta.xml
<CustomObject>
    <label>Deal</label>
    <nameField>
        <label>Deal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal__c/fields/Allocation_by__c.field-meta.xml
<CustomField>
    <fullName>Allocation_by__c</fullName>
    <label>Allocation by</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Deal</fullName>
                <default>true</default>
                <label>Deal</label>
            </value>
            <value>
                <fullName>Option</fullName>
            </value>
            <value>
                <fullName>Sub option</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal__c/fields/deal_archetype__c.field-meta.xml
<CustomField>
    <fullName>deal_archetype__c</fullName>
    <label>Deal Archetype</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MADU1</fullName>
            </value>
            <value>
                <fullName>MADUZ1</fullName>
            </value>
            <value>
                <fullName>MADU2</fullName>
            </value>
            <value>
                <fullName>MADUZ2</fullName>
            </value>
            <value>
                <fullName>TAIU1</fullName>
            </value>
            <value>
                <fullName>TAIZ1</fullName>
            </value>
            <value>
                <fullName>TAIUZ1</fullName>
            </value>
            <value>
                <fullName>TAIU2</fullName>
            </value>
            <value>
                <fullName>TAIZ2</fullName>
            </value>
            <value>
                <fullName>TAIUZ2</fullName>
            </value>
            <value>
                <fullName>TANU1</fullName>
            </value>
            <value>
                <fullName>TANZ1</fullName>
            </value>
            <value>
                <fullName>TANUZ1</fullName>
            </value>
            <value>
                <fullName>TANU2</fullName>
            </value>
            <value>
                <fullName>TANZ2</fullName>
            </value>
            <value>
                <fullName>TANUZ2</fullName>
            </value>
            <value>
                <fullName>MANU1</fullName>
            </value>
            <value>
                <fullName>MANUZ1</fullName>
            </value>
            <value>
                <fullName>MANU2</fullName>
            </value>
            <value>
                <fullName>MANUZ2</fullName>
            </value>
            <value>
                <fullName>RADU1</fullName>
            </value>
            <value>
                <fullName>RADUZ1</fullName>
            </value>
            <value>
                <fullName>RADU2</fullName>
            </value>
            <value>
                <fullName>RADUZ2</fullName>
            </value>
            <value>
                <fullName>CAIU1</fullName>
            </value>
            <value>
                <fullName>CAIZ1</fullName>
            </value>
            <value>
                <fullName>CAIUZ1</fullName>
            </value>
            <value>
                <fullName>CAIU2</fullName>
            </value>
            <value>
                <fullName>CAIZ2</fullName>
            </value>
            <value>
                <fullName>CAIUZ2</fullName>
            </value>
            <value>
                <fullName>CANU1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal__c/fields/deal_type__c.field-meta.xml
<CustomField>
    <fullName>deal_type__c</fullName>
    <label>deal type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>travel</fullName>
            </value>
            <value>
                <fullName>cruise</fullName>
            </value>
            <value>
                <fullName>stay</fullName>
            </value>
            <value>
                <fullName>Siteminder Hotel</fullName>
            </value>
            <value>
                <fullName>Experiences</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Hero</fullName>
            </value>
            <value>
                <fullName>Published(NRMA)</fullName>
            </value>
            <value>
                <fullName>Published(Staging)</fullName>
            </value>
            <value>
                <fullName>Hero(Staging)</fullName>
            </value>
            <value>
                <fullName>Hidden</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/departures_dates__c/departures_dates__c.object-meta.xml
<CustomObject>
    <label>departures dates</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>departures dates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/departures_dates__c/fields/allocation__c.field-meta.xml
<CustomField>
    <fullName>allocation__c</fullName>
    <label>TOTAL v2 ALLOCATION</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>departures dates</relationshipLabel>
    <relationshipName>departures_dates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/HSS_amount__c.field-meta.xml
<CustomField>
    <fullName>HSS_amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>HSS amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/HSS_amount_nz__c.field-meta.xml
<CustomField>
    <fullName>HSS_amount_nz__c</fullName>
    <defaultValue>0</defaultValue>
    <label>HSS_Amount - NZ</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/Linked_Deal_D_O_S__c.field-meta.xml
<CustomField>
    <fullName>Linked_Deal_D_O_S__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Linked Deal(D/O/S)</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>departures dates (Linked Deal(D/O/S))</relationshipLabel>
    <relationshipName>departures_dates2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/options__c.field-meta.xml
<CustomField>
    <fullName>options__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>options</label>
    <referenceTo>options__c</referenceTo>
    <relationshipLabel>departures dates</relationshipLabel>
    <relationshipName>departures_dates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Close</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/options__c/options__c.object-meta.xml
<CustomObject>
    <label>Options</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/options__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipName>options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/options__c/fields/itinerary_context__c.field-meta.xml
<CustomField>
    <fullName>itinerary_context__c</fullName>
    <label>Itinerary Context</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>Both Extensions</fullName>
                <isActive>false</isActive>
                <label>Both Extensions</label>
            </value>
            <value>
                <fullName>Main Package</fullName>
                <isActive>false</isActive>
                <label>Main Package</label>
            </value>
            <value>
                <fullName>Post Extension</fullName>
                <isActive>false</isActive>
                <label>Post Extension</label>
            </value>
            <value>
                <fullName>Pre Extension</fullName>
                <isActive>false</isActive>
                <label>Pre Extension</label>
            </value>
            <value>
                <fullName>Upgrade</fullName>
                <isActive>false</isActive>
                <label>Upgrade</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Payment_Link__c/Order_Payment_Link__c.object-meta.xml
<CustomObject>
    <label>Order Payment Link</label>
    <nameField>
        <displayFormat>OPL-{0000000}</displayFormat>
        <label>Order Payment Link Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Payment Links</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Payment_Link__c/fields/TAD_Order__c.field-meta.xml
<CustomField>
    <fullName>TAD_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TAD Order</label>
    <referenceTo>TAD_Order__c</referenceTo>
    <relationshipName>Tad_Payment_Links</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/TAD_Order__c.object-meta.xml
<CustomObject>
    <label>TAD Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TAD Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_master_status__c.field-meta.xml
<CustomField>
    <fullName>ordexp_master_status__c</fullName>
    <label>Master status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
                <default>true</default>
                <label>On Hold</label>
            </value>
            <value>
                <fullName>Temporary Hold</fullName>
            </value>
            <value>
                <fullName>Secured</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Travelled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>In Progress-Cruise only</fullName>
                <isActive>false</isActive>
                <label>In Progress-Cruise only</label>
            </value>
            <value>
                <fullName>In Progress-Flight only</fullName>
                <isActive>false</isActive>
                <label>In Progress-Flight only</label>
            </value>
            <value>
                <fullName>In Progress-Flights + Cruise</fullName>
                <isActive>false</isActive>
                <label>In Progress-Flights + Cruise</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TAD_Order__c/recordTypes/TAD.recordType-meta.xml
<RecordType>
    <fullName>TAD</fullName>
    <active>true</active>
    <label>TAD</label>
</RecordType>

force-app/main/default/classes/TAD_OrderPaymentLinkSendEmail_Test.cls
@isTest
public class TAD_OrderPaymentLinkSendEmail_Test {
    @isTest
    static void orderPaymentLinkTestMethod() {
        User testUser = [Select id,Name, Contact.Id,Contact.AccountId, Profile.Name from user where Profile.Name = 'Partner Community Plus User' AND isActive = true LIMIT 1];
        Set<Order_Payment_Link__c> oplIdSet = new Set<Order_Payment_Link__c>();
        List<RecordType> RCTProductPartner = TADUtils.getRecordType(Label.TAD_RT_Product_Partner);
        
        Account acctBussiness = TestDataFactory.createBussinessAccount(RCTProductPartner[0].Id);   // Bussiness account Inserted
        insert acctBussiness;
        
        List<RecordType> RCTTadDeal = TADUtils.getRecordType(Label.TAD_RT_TAD_Deal);
        
        Deal__c deal = TestDataFactory.createMerchantDeal(RCTTadDeal[0].Id , acctBussiness.Id );   // Deals created
        deal.Allocation_by__c='Deal';
        deal.deal_type__c ='stay';
        deal.deal_archetype__c = 'CANU1';
        insert deal;

        options__c options = TestDataFactory.CreateOptions(deal.Id);       // Options crested using the deal
        options.itinerary_context__c='Main Package';
        insert options;
        
        
        Allocation__c acc = TestDataFactory.createAllocationDeal(deal);
        insert acc;
        
        departures_dates__c departureDates = TestDataFactory.createDDWithAllocation(deal,null,null,acc);
        departureDates.Linked_Deal_D_O_S__c = deal.Id;
        departureDates.HSS_amount__c = 100;
        departureDates.HSS_amount_nz__c = 200; 
        insert departureDates;
        
        List<RecordType> RCTPersonAccount = TADUtils.getRecordType(Label.TAD_RT_TAD_Person_Account);
        Account acctPerson = TestDataFactory.createPersonAccount(RCTPersonAccount[0].Id);
        insert acctPerson;
        
        
        ID RTTADOrder1 = Schema.SObjectType.Tad_Order__C.getRecordTypeInfosByDeveloperName().get('TAD').getRecordTypeId();
        Tad_Order__C order1 = TestDataFactory.createTADOrder(acctPerson,deal,options,departureDates,RTTADOrder1);
        order1.ordexp_master_status__c = 'On Hold';
        order1.ordexp_sub_status__c = 'Initial Payment Pending';
        order1.ordexp_gross_amount__c = 1000;
        order1.ordexp_total_payment_received__c = 600;
        
        insert order1;
        
        Order_Payment_Link__c opl = new Order_Payment_Link__c();
        opl.Notify_Me__c = True;
        opl.Notify_user__c = testUser.Id;
        opl.TAD_Order__c = order1.Id;
        opl.Status__c = 'Pending';
        insert opl;
        opl.Status__c = 'Paid';
        update opl;
        oplIdSet.add(opl);
        
        TAD_OrderPaymentLinkSendEmail.sendOrderPaymentLink(oplIdSet);
    }
}