force-app/main/default/objects/Allocation__c/Allocation__c.object-meta.xml
<CustomObject>
    <description>Auto Generated Name: {DEAL ID}-{DATE}-{POOL DIFFERENTIATOR} Example 1234-2020-11-1-A</description>
    <label>Allocation</label>
    <nameField>
        <label>Allocation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Allocation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Allocation__c/fields/deal__c.field-meta.xml
<CustomField>
    <fullName>deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Allocation</relationshipLabel>
    <relationshipName>Allocation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal__c/Deal__c.object-meta.xml
<CustomObject>
    <label>Deal</label>
    <nameField>
        <label>Deal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal__c/fields/Allocation_by__c.field-meta.xml
<CustomField>
    <fullName>Allocation_by__c</fullName>
    <label>Allocation by</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Deal</fullName>
                <default>true</default>
                <label>Deal</label>
            </value>
            <value>
                <fullName>Option</fullName>
            </value>
            <value>
                <fullName>Sub option</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal__c/fields/BDM__c.field-meta.xml
<CustomField>
    <fullName>BDM__c</fullName>
    <label>BDM</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Maite De Hedervary</fullName>
            </value>
            <value>
                <fullName>Silvia Magnani</fullName>
            </value>
            <value>
                <fullName>Teige O&apos;Sullivan</fullName>
            </value>
            <value>
                <fullName>Alison Riordan</fullName>
            </value>
            <value>
                <fullName>Eamonn O&apos;Sullivan</fullName>
            </value>
            <value>
                <fullName>Rebecca Maitland</fullName>
            </value>
            <value>
                <fullName>Andrew Bennett</fullName>
            </value>
            <value>
                <fullName>Holly Littlewood</fullName>
            </value>
            <value>
                <fullName>Nicoline Dolman</fullName>
            </value>
            <value>
                <fullName>Emily Taylor</fullName>
            </value>
            <value>
                <fullName>Alanna Betz</fullName>
            </value>
            <value>
                <fullName>Ben Ellison</fullName>
            </value>
            <value>
                <fullName>Luke Hansell</fullName>
            </value>
            <value>
                <fullName>Laura Newman</fullName>
            </value>
            <value>
                <fullName>Peter Huff</fullName>
            </value>
            <value>
                <fullName>Lexi Graham</fullName>
            </value>
            <value>
                <fullName>Ayu Herawati</fullName>
            </value>
            <value>
                <fullName>Brett Lemish</fullName>
            </value>
            <value>
                <fullName>Pete Timbs</fullName>
            </value>
            <value>
                <fullName>Serena Brillanti</fullName>
            </value>
            <value>
                <fullName>Angelina Hackett</fullName>
            </value>
            <value>
                <fullName>Jeremy Hagan</fullName>
            </value>
            <value>
                <fullName>Paul Wards</fullName>
            </value>
            <value>
                <fullName>Trent Ellen</fullName>
            </value>
            <value>
                <fullName>Alexandra Chakos</fullName>
                <isActive>false</isActive>
                <label>Alexandra Chakos</label>
            </value>
            <value>
                <fullName>Amanda Tennant</fullName>
                <isActive>false</isActive>
                <label>Amanda Tennant</label>
            </value>
            <value>
                <fullName>Cameron Williams</fullName>
                <isActive>false</isActive>
                <label>Cameron Williams</label>
            </value>
            <value>
                <fullName>Chaiy Donati</fullName>
                <isActive>false</isActive>
                <label>Chaiy Donati</label>
            </value>
            <value>
                <fullName>Derek Test Dolan</fullName>
                <isActive>false</isActive>
                <label>Derek Test Dolan</label>
            </value>
            <value>
                <fullName>Ella Dixon</fullName>
                <isActive>false</isActive>
                <label>Ella Dixon</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal__c/fields/deal_type__c.field-meta.xml
<CustomField>
    <fullName>deal_type__c</fullName>
    <label>deal type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>travel</fullName>
            </value>
            <value>
                <fullName>cruise</fullName>
            </value>
            <value>
                <fullName>stay</fullName>
            </value>
            <value>
                <fullName>Siteminder Hotel</fullName>
            </value>
            <value>
                <fullName>Experiences</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal__c/fields/site__c.field-meta.xml
<CustomField>
    <fullName>site__c</fullName>
    <label>Site</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/departure_cities__c/departure_cities__c.object-meta.xml
<CustomObject>
    <label>departure cities</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>departure cities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/departure_cities__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>departure cities</relationshipLabel>
    <relationshipName>departure_cities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/departure_cities__c/fields/site__c.field-meta.xml
<CustomField>
    <fullName>site__c</fullName>
    <label>Site</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/departures_dates__c/departures_dates__c.object-meta.xml
<CustomObject>
    <label>departures dates</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>departures dates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/departures_dates__c/fields/BDM__c.field-meta.xml
<CustomField>
    <fullName>BDM__c</fullName>
    <formula>TEXT(Deal_for_Reporting__r.BDM__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>BDM</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/date__c.field-meta.xml
<CustomField>
    <fullName>date__c</fullName>
    <label>date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>departures dates</relationshipLabel>
    <relationshipName>departures_dates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/Departure_Date_Finalised__c.field-meta.xml
<CustomField>
    <fullName>Departure_Date_Finalised__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Departure Date Finalised?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/min_numbers_met__c.field-meta.xml
<CustomField>
    <fullName>min_numbers_met__c</fullName>
    <defaultValue>false</defaultValue>
    <description>For Flight Ticketing team use - checks as true if number of pax confirmed &gt;= min numbers</description>
    <inlineHelpText>Process Builder - Auto checks as true if number of pax confirmed greater or equal to min. numbers</inlineHelpText>
    <label>Min Numbers Met?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/mp_bc_available__c.field-meta.xml
<CustomField>
    <fullName>mp_bc_available__c</fullName>
    <label>BC Available</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NOT AVAILABLE</fullName>
                <default>true</default>
                <label>NOT AVAILABLE</label>
            </value>
            <value>
                <fullName>AVAILABLE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/online_status__c.field-meta.xml
<CustomField>
    <fullName>online_status__c</fullName>
    <label>Online Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Offline - Auto</fullName>
            </value>
            <value>
                <fullName>Offline - Manual</fullName>
            </value>
            <value>
                <fullName>Hidden</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/site__c.field-meta.xml
<CustomField>
    <fullName>site__c</fullName>
    <label>Site</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/options__c/options__c.object-meta.xml
<CustomObject>
    <label>Options</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/options__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipName>options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/options__c/fields/site__c.field-meta.xml
<CustomField>
    <fullName>site__c</fullName>
    <label>Site</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/sub_options__c/sub_options__c.object-meta.xml
<CustomObject>
    <label>Sub Options</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/sub_options__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Sub Options</relationshipLabel>
    <relationshipName>Sub_Options</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sub_options__c/fields/site__c.field-meta.xml
<CustomField>
    <fullName>site__c</fullName>
    <label>Site</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MP_PaxReachesMax_NotificationTest.cls
@isTest
public class MP_PaxReachesMax_NotificationTest {
 @isTest
    static void dpTest(){
        List<RecordType> RCTProductPartner = TADUtils.getRecordType(Label.TAD_RT_Product_Partner);
        List<RecordType> RCTPersonAccount = TADUtils.getRecordType(Label.TAD_RT_TAD_Person_Account);
        Account acctPerson = TestDataFactory.createPersonAccount(RCTPersonAccount[0].Id);
        insert acctPerson;
        
        Account acctBussiness = TestDataFactory.createBussinessAccount(RCTProductPartner[0].Id);   // Bussiness account Inserted
        acctBussiness.Merchant_Type__c='Multi Line Expense';
        insert acctBussiness;
        Contact con= new Contact();
        con.lastname='test';
        con.AccountId=acctBussiness.id;
        insert con;
        Id p = [select id from profile where name='Partner Community Plus User'].id;
        /*User user = new User(alias = '1234', email='test123@noemail.com',
                             emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
                             localesidkey='en_US', profileid = p, country='United States',IsActive =true,
                             ContactId = con.Id,
                             timezonesidkey='America/Los_Angeles', username='tester@noemail.com');
        
        insert user;*/
      
            
            list<string>newStrList=new list<string>();
            list<departures_dates__c> depdate = new list<departures_dates__c> ();
            departures_dates__c departureDates1 = new departures_dates__c();
            departureDates1.Name = '2020-05-01';
            departureDates1.online_status__c = 'Online';
            departureDates1.min_numbers_met__c = false;
            departureDates1.Departure_Date_Finalised__c = false;
            departureDates1.mp_bc_available__c = 'NOT AVAILABLE';
            departureDates1.site__c = 'AU';
            departureDates1.date__c=system.today();
            insert departureDates1; 
            newStrList.add(departureDates1.id);
            system.debug('departureDates1-->'+departureDates1);
            
            List<RecordType> RCTTadDeal = TADUtils.getRecordType(Label.TAD_RT_TAD_Deal);
            
            Deal__c deal = TestDataFactory.createMerchantDeal(RCTTadDeal[0].Id , acctBussiness.Id );   // Deals created
            deal.Allocation_by__c='Deal';
            deal.deal_type__c ='stay';
            deal.deal_type__c ='stay';
            deal.BDM__c = 'Silvia Magnani';
            deal.deal_archetype__c = 'CANU1';
            insert deal;   
            
            list<Tad_Order__C > tadorderList = new list<Tad_Order__C >();
            Tad_Order__C order = new Tad_Order__C();
            order.ordexp_master_status__c = 'In Progress' ;
            order.ordexp_sub_status__c = 'Travelling';
            order.ordexp_departure_date__c = departureDates1.Id;
           
            order.ordexp_deal__c=deal.id;
            tadorderList.add(order);
            insert tadorderList;
            
            options__c options = TestDataFactory.CreateOptions(deal.Id);       // Options crested using the deal
            options.itinerary_context__c='Main Package';
            insert options;
            
            sub_options__c subOptions = TestDataFactory.createSubOptions(options.Id);   // Sub options created
            subOptions.STD_OPT__c ='Standard';
            subOptions.Deal__c = deal.id  ;
            insert subOptions;
            
        list<Allocation__c> allolist = new list<Allocation__c> ();
        Map<Id,Allocation__c> oldAccMapTest = new Map<Id,Allocation__c>();
        Allocation__c acc = TestDataFactory.createAllocationDeal(deal);
        acc.Total_Allocation__c=10;
        acc.Sold__c=0;
        acc.Held__c=0;
        acc.Order_Nights_Sold_Held__c=0;
        allolist.add(acc);
        insert acc;
   
        Allocation__c aaloc1=[select id,name,Remaining__c from Allocation__c where id=:acc.id];
        aaloc1.Total_Allocation__c=10;
        aaloc1.Sold__c=2;
        aaloc1.Held__c=1;
        aaloc1.Order_Nights_Sold_Held__c=3;
        system.debug('line 84'+aaloc1);
        update aaloc1;
      oldAccMapTest.put(aaloc1.Id, aaloc1);
        
        departures_dates__c departureDates = TestDataFactory.createDDWithAllocation(deal,null,null,acc);
        departureDates.Linked_Deal_D_O_S__c = deal.Id;
        insert departureDates;
        
        departure_cities__c departureCities = TestDataFactory.createDepartureCities(deal.Id);       // Departure cities created
        insert departureCities;
        
            
            
            MP_PaxReachesMax_Notification.PaxReachesMax_Notification(allolist,oldAccMapTest);
            
        
    }
}