force-app/main/default/objects/Allocation__c/Allocation__c.object-meta.xml
<CustomObject>
    <description>Auto Generated Name: {DEAL ID}-{DATE}-{POOL DIFFERENTIATOR} Example 1234-2020-11-1-A</description>
    <label>Allocation</label>
    <nameField>
        <label>Allocation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Allocation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Allocation__c/fields/deal__c.field-meta.xml
<CustomField>
    <fullName>deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Allocation</relationshipLabel>
    <relationshipName>Allocation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal__c/Deal__c.object-meta.xml
<CustomObject>
    <label>Deal</label>
    <nameField>
        <label>Deal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal__c/fields/built_in_stop_over__c.field-meta.xml
<CustomField>
    <fullName>built_in_stop_over__c</fullName>
    <formula>Deal_Draft__r.built_in_stop_over__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>If a Stop Over has been built into the deal as part of the standard itinerary then this check box is checked - see Deal Draft for original check box.</inlineHelpText>
    <label>Built In Stop Over</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Deal__c/fields/Deal_Draft__c.field-meta.xml
<CustomField>
    <fullName>Deal_Draft__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal Draft</label>
    <referenceTo>Deal_Draft__c</referenceTo>
    <relationshipLabel>Deal</relationshipLabel>
    <relationshipName>Deal</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Draft__c/Deal_Draft__c.object-meta.xml
<CustomObject>
    <description>This object is a child object to Deal and provides details for the deal provided by the BDM and also &quot;proofed content&quot; for Product Analysts which are then used by Publishers.

This includes information for both AU and NZ</description>
    <label>Deal Draft</label>
    <nameField>
        <label>Deal Draft Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal Drafts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Draft__c/fields/built_in_stop_over__c.field-meta.xml
<CustomField>
    <fullName>built_in_stop_over__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If you have a Stop Over built into your deal as part of the standard itinerary, please check this box.</inlineHelpText>
    <label>Built In Stop Over</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Deal_Draft__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Deal Drafts</relationshipLabel>
    <relationshipName>Deal_Drafts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/departure_cities__c/departure_cities__c.object-meta.xml
<CustomObject>
    <label>departure cities</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>departure cities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/departure_cities__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>departure cities</relationshipLabel>
    <relationshipName>departure_cities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/departures_dates__c.object-meta.xml
<CustomObject>
    <label>departures dates</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>departures dates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/departures_dates__c/fields/allocation__c.field-meta.xml
<CustomField>
    <fullName>allocation__c</fullName>
    <label>TOTAL v2 ALLOCATION</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/create_sabre_profiles__c.field-meta.xml
<CustomField>
    <fullName>create_sabre_profiles__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Create Sabre Profiles</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/create_sabre_profiles_date__c.field-meta.xml
<CustomField>
    <fullName>create_sabre_profiles_date__c</fullName>
    <label>Create Sabre Profiles Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>departures dates</relationshipLabel>
    <relationshipName>departures_dates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/Linked_Deal_D_O_S__c.field-meta.xml
<CustomField>
    <fullName>Linked_Deal_D_O_S__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Linked Deal(D/O/S)</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>departures dates (Linked Deal(D/O/S))</relationshipLabel>
    <relationshipName>departures_dates2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/options__c.field-meta.xml
<CustomField>
    <fullName>options__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>options</label>
    <referenceTo>options__c</referenceTo>
    <relationshipLabel>departures dates</relationshipLabel>
    <relationshipName>departures_dates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/sub_options__c.field-meta.xml
<CustomField>
    <fullName>sub_options__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>sub options</label>
    <referenceTo>sub_options__c</referenceTo>
    <relationshipLabel>departures dates</relationshipLabel>
    <relationshipName>departures_dates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Itinerary__c/Itinerary__c.object-meta.xml
<CustomObject>
    <label>Itinerary</label>
    <nameField>
        <displayFormat>Itinerary-{00000}</displayFormat>
        <label>Itinerary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Itineraries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Itinerary__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Itinerarys</relationshipLabel>
    <relationshipName>Itinerarys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Itinerary__c/fields/Itinerary__c.field-meta.xml
<CustomField>
    <fullName>Itinerary__c</fullName>
    <label>Itinerary #</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>1</label>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/options__c/options__c.object-meta.xml
<CustomObject>
    <label>Options</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/options__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipName>options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/order_line_item__c/order_line_item__c.object-meta.xml
<CustomObject>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>OLI-{000000}</displayFormat>
        <label>Order Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/order_line_item__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/order_line_item__c/fields/Departure_cities__c.field-meta.xml
<CustomField>
    <fullName>Departure_cities__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Departure cities</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>departure_cities__c.Deal__c</field>
            <operation>equals</operation>
            <valueField>$Source.Deal__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>departure_cities__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items_dc</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/order_line_item__c/fields/Sub_Options__c.field-meta.xml
<CustomField>
    <fullName>Sub_Options__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Note :-  For Stay type Orders, change to Sub-Option will be applied to all the OLIs of this Order</inlineHelpText>
    <label>Sub Options</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>sub_options__c.options__c</field>
            <operation>equals</operation>
            <valueField>$Source.ordexp_Options__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>sub_options__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sub_options__c/sub_options__c.object-meta.xml
<CustomObject>
    <label>Sub Options</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/sub_options__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Sub Options</relationshipLabel>
    <relationshipName>Sub_Options</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sub_options__c/fields/options__c.field-meta.xml
<CustomField>
    <fullName>options__c</fullName>
    <label>options</label>
    <referenceTo>options__c</referenceTo>
    <relationshipLabel>Sub Options</relationshipLabel>
    <relationshipName>sub_options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Test_BatchordercBCUpdate.cls
@isTest
private class Test_BatchordercBCUpdate {

    @TestSetup
    static void makeData(){
        List<RecordType> RCTTadDeal = TADUtils.getRecordType(Label.TAD_RT_TAD_Deal);
        
        List<RecordType> RCTProductPartner = TADUtils.getRecordType(Label.TAD_RT_Product_Partner);
        
        Account acctBussiness = TestDataFactory.createBussinessAccount(RCTProductPartner[0].Id);   // Bussiness account Inserted
        insert acctBussiness;
        
        Deal__c deal = TestDataFactory.createMerchantDeal(RCTTadDeal[0].Id , acctBussiness.Id );   // Deals created
        
        insert deal;
        
        Deal_Draft__c dd= TestDataFactory.createDealDraft(deal);
        dd.built_in_stop_over__c=true;
        dd.deal__c = deal.Id;
        insert dd;
        
        deal.Deal_Draft__c=dd.Id;
        update deal;
        
        options__c options = TestDataFactory.CreateOptions(deal.Id);       // Options crested using the deal
        insert options;
        
        sub_options__c subOptions = TestDataFactory.createSubOptions(options.Id);   // Sub options created
        insert subOptions;
        
       Allocation__c acc = TestDataFactory.createAllocationDeal(deal);
        insert acc;
        
        departures_dates__c departureDates = TestDataFactory.createDDWithAllocation(deal,null,null,acc);
        departureDates.Linked_Deal_D_O_S__c = deal.Id;
        departureDates.create_sabre_profiles_date__c= System.today();
        departureDates.create_sabre_profiles__c=true;
        insert departureDates;
        
        departure_cities__c departureCities = TestDataFactory.createDepartureCities(deal.Id);       // Departure cities created
        insert departureCities;
        
        Itinerary__c itinerary = TestDataFactory.createItinerary(deal,'Main Package',1);
        insert itinerary; 
        
        User__c user = TestDataFactory.createGenericUser();
        insert user;
        
        List<RecordType> RCTPersonAccount = TADUtils.getRecordType(Label.TAD_RT_TAD_Person_Account);
        Account acctPerson = TestDataFactory.createPersonAccount(RCTPersonAccount[0].Id);
        insert acctPerson;
        
        
        List<RecordType> RTTADOrder = TADUtils.getRecordType('TNZ');
        Tad_Order__C order = TestDataFactory.createTADOrder(acctPerson,deal,options,departureDates,RTTADOrder[1].id);
        insert order;
        
        order.ordexp_master_status__c = 'In Progress';
        order.ordexp_sub_status__c = 'Cabins Pending/Flights Booked - Cabin Ready to Ticket';
        order.ordexp_coach_colour__c = 'blue';
        update order;
       
        
        Order_Line_Item__c oli = TestDataFactory.createOrderLineItem(order,subOptions,departureCities,'2', options,deal );
        insert oli;
       
    }
    
    @isTest
    static void testpositiveforbatchorderBsupdate(){
        test.startTest();
        String q = 'Select Id, ordexp_bc_sent__c, ordexp_bc_date__c from Tad_Order__c Limit 1';
        BatchordercBCUpdate bc = new BatchordercBCUpdate(q);
        Database.executeBatch(bc, 200);
        Test.stopTest();
    }
}