force-app/main/default/objects/Allocation__c/Allocation__c.object-meta.xml
<CustomObject>
    <description>Auto Generated Name: {DEAL ID}-{DATE}-{POOL DIFFERENTIATOR} Example 1234-2020-11-1-A</description>
    <label>Allocation</label>
    <nameField>
        <label>Allocation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Allocation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Allocation__c/fields/deal__c.field-meta.xml
<CustomField>
    <fullName>deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Allocation</relationshipLabel>
    <relationshipName>Allocation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Allocation__c/fields/departure_date__c.field-meta.xml
<CustomField>
    <fullName>departure_date__c</fullName>
    <label>Main Tour Departure Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Allocation__c/fields/name__c.field-meta.xml
<CustomField>
    <fullName>name__c</fullName>
    <label>Name</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Deal__c/Deal__c.object-meta.xml
<CustomObject>
    <label>Deal</label>
    <nameField>
        <label>Deal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal__c/fields/Cloned_From__c.field-meta.xml
<CustomField>
    <fullName>Cloned_From__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cloned From</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Deal</relationshipLabel>
    <relationshipName>Deal</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal__c/fields/name__c.field-meta.xml
<CustomField>
    <fullName>name__c</fullName>
    <label>Landing Page Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/departures_dates__c.object-meta.xml
<CustomObject>
    <label>departures dates</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>departures dates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/departures_dates__c/fields/allocation__c.field-meta.xml
<CustomField>
    <fullName>allocation__c</fullName>
    <label>TOTAL v2 ALLOCATION</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/Allocation_Table__c.field-meta.xml
<CustomField>
    <fullName>Allocation_Table__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Allocation Table</label>
    <referenceTo>Allocation__c</referenceTo>
    <relationshipLabel>departures dates</relationshipLabel>
    <relationshipName>departures_dates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/date__c.field-meta.xml
<CustomField>
    <fullName>date__c</fullName>
    <label>date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>departures dates</relationshipLabel>
    <relationshipName>departures_dates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/Deal_for_Reporting__c.field-meta.xml
<CustomField>
    <fullName>Deal_for_Reporting__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Deal for Reporting</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>departures dates (Deal for Reporting)</relationshipLabel>
    <relationshipName>departures_dates1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/Linked_Deal_D_O_S__c.field-meta.xml
<CustomField>
    <fullName>Linked_Deal_D_O_S__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Linked Deal(D/O/S)</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>departures dates (Linked Deal(D/O/S))</relationshipLabel>
    <relationshipName>departures_dates2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/online_status__c.field-meta.xml
<CustomField>
    <fullName>online_status__c</fullName>
    <label>Online Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Offline - Auto</fullName>
            </value>
            <value>
                <fullName>Offline - Manual</fullName>
            </value>
            <value>
                <fullName>Hidden</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/options__c.field-meta.xml
<CustomField>
    <fullName>options__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>options</label>
    <referenceTo>options__c</referenceTo>
    <relationshipLabel>departures dates</relationshipLabel>
    <relationshipName>departures_dates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/sub_options__c.field-meta.xml
<CustomField>
    <fullName>sub_options__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>sub options</label>
    <referenceTo>sub_options__c</referenceTo>
    <relationshipLabel>departures dates</relationshipLabel>
    <relationshipName>departures_dates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/options__c/options__c.object-meta.xml
<CustomObject>
    <label>Options</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/options__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipName>options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/options__c/recordTypes/Option.recordType-meta.xml
<RecordType>
    <fullName>Option</fullName>
    <active>true</active>
    <description>This is a record type for creating a normal Option Record.</description>
    <label>Option</label>
</RecordType>

force-app/main/default/objects/sub_options__c/sub_options__c.object-meta.xml
<CustomObject>
    <label>Sub Options</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/sub_options__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Sub Options</relationshipLabel>
    <relationshipName>Sub_Options</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sub_options__c/fields/options__c.field-meta.xml
<CustomField>
    <fullName>options__c</fullName>
    <label>options</label>
    <referenceTo>options__c</referenceTo>
    <relationshipLabel>Sub Options</relationshipLabel>
    <relationshipName>sub_options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/batchToCreateDepDateCloneDeal.cls
global class batchToCreateDepDateCloneDeal implements Database.Batchable<sObject>{
    
    public String depToParseSet ='';
    
    public batchToCreateDepDateCloneDeal(String depToParseGetRec){
        depToParseSet = depToParseGetRec; 
    }
    
    global Database.QueryLocator start(Database.BatchableContext bc){
    
        return Database.getQueryLocator([select id, name from departures_dates__c where date__c>today and online_status__c='Online' and Deal_for_Reporting__c=: depToParseSet]);
            
    }
    
    global void execute(Database.BatchableContext BC, List<departures_dates__c> scope){
        
        // date Original
        System.debug('scope1'+scope[0].id);
        String depSoql = cloneDealRecords.getCreatableFieldsSOQL('departures_dates__c','Id =' +'\''+ scope[0].id + '\''   );
        System.debug('depSoql'+depSoql);
        List<departures_dates__c> depRec = (List<departures_dates__c>)Database.query(depSoql);
       // 
        departures_dates__c dep = depRec[0];
        
        deal__c deal = [Select id ,name from deal__c where Cloned_From__c=:dep.Deal_for_Reporting__c  order by createddate DESC limit 1 ];
        System.debug('dealData'+deal);
        options__c option= new options__c();
        sub_options__c subOption= new sub_options__c();
        
        if(dep.options__c !=null){
            option = [Select id , Deal__c,Cloned_From__c from options__c where Cloned_From__c=:dep.options__c and Deal__c=:deal.id  limit 1];
        }
        if(dep.sub_options__c !=null){
            subOption = [Select id , Deal__c,Cloned_From__c from sub_options__c where Cloned_From__c=:dep.sub_options__c and Deal__c=:deal.id limit 1];
        }
        
        
        
        // Insert Allocation
        
        String alloSoql = cloneDealRecords.getCreatableFieldsSOQL('Allocation__c','departure_date__c >' + String.valueOf(Date.today()).removeEnd(' 00:00:00')  +'  AND Id='+'\''+ dep.Allocation_Table__c + '\''  );
        system.debug('alloSoql'+alloSoql);
        List<Allocation__c> alloRec = (List<Allocation__c>)Database.query(alloSoql);
        
        List<Allocation__c> alloInsert = new List<Allocation__c>();
        for(Allocation__c  allo :alloRec ){
            Allocation__c  inst = allo.clone(false, true);
            inst.name__c ='testRec'+allo.name;
            inst.deal__c = deal.id;
            inst.ownerId  =userinfo.getUserId();
            alloInsert.add(inst);
        }        
        
        insert alloInsert;
        
        
        List<departures_dates__c> depToInsert = new List<departures_dates__c>();
        
        if( (dep.Deal__c!=null)  || (dep.options__c !=null && option!=null ) || (dep.sub_options__c !=null && subOption!=null ) ){
            departures_dates__c  inst = dep.clone(false, true);
            inst.Allocation_Table__c  = dep.Allocation_Table__c !=null?alloInsert[0].id  : null;
            inst.Deal__c   = dep.Deal__c  != null ? deal.id:null;
            inst.Deal_for_Reporting__c   = deal.id;
            inst.Linked_Deal_D_O_S__c    = dep.Linked_Deal_D_O_S__c!= null ?deal.id:null;
            inst.options__c   = dep.options__c !=null ? option.id  : null;
            inst.Cloned_From__c =alloInsert[0].id;
            inst.sub_options__c   = dep.sub_options__c !=null ? subOption.id  : null;
            inst.ownerId  =userinfo.getUserId();
            depToInsert.add(inst);   
        }
        
        
        insert depToInsert;
        
        
        
        /*
Map<id,Allocation__c  > alloToInsert = new Map<id,Allocation__c  >();

departures_dates__c dateRec = scope[0];
String alloRecId = dateRec.Cloned_From__c;


String alloSoql = cloneDealRecords.getCreatableFieldsSOQL('Allocation__c','departure_date__c >' + String.valueOf(Date.today()).removeEnd(' 00:00:00')  +'  AND Id='+'\''+ alloRecId + '\''  );
system.debug('alloSoql'+alloSoql);
List<Allocation__c> alloRec = (List<Allocation__c>)Database.query(alloSoql);

for(Allocation__c  allo :alloRec ){
Allocation__c  inst = allo.clone(false, true);
inst.name__c ='testRec'+allo.name;
inst.deal__c = dateRec.Deal_for_Reporting__c;
inst.ownerId  =userinfo.getUserId();
alloToInsert.put(allo.id,inst);
}        

insert alloToInsert.values();


List<departures_dates__c> depToInsert = new List<departures_dates__c>();
for(departures_dates__c s : scope){
depToInsert.add(s); 
}      
insert depToInsert; */
    }
    
    global void finish(Database.BatchableContext BC){
        
    }
    
}