force-app/main/default/objects/Booking_Hotel__c/Booking_Hotel__c.object-meta.xml
<CustomObject>
    <label>Booking Hotel</label>
    <nameField>
        <displayFormat>Booking Hotel-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking Hotels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking_Hotel__c/fields/Cancellation_Amount__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Amount__c</fullName>
    <label>Cancellation Amount</label>
    <summarizedField>Room__c.Cancellation_Amount_Room__c</summarizedField>
    <summaryForeignKey>Room__c.Booking_Hotel__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Booking_Hotel__c/fields/Cancellation_Amount_Order__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Amount_Order__c</fullName>
    <label>Cancellation Amount Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Booking_Hotel__c/fields/Cancellation_Refund__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Refund__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cancellation/Refund</label>
    <referenceTo>Cancellation_Refund_POE__c</referenceTo>
    <relationshipLabel>Booking Hotels</relationshipLabel>
    <relationshipName>Booking_Hotels</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking_Hotel__c/fields/CanRef_status__c.field-meta.xml
<CustomField>
    <fullName>CanRef_status__c</fullName>
    <label>CanRef status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Partial Refund Processed</fullName>
            </value>
            <value>
                <fullName>Full Refund Processed</fullName>
            </value>
            <value>
                <fullName>Finance Rejected</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <isActive>false</isActive>
                <label>Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking_Hotel__c/fields/Local_tax_in_AUD__c.field-meta.xml
<CustomField>
    <fullName>Local_tax_in_AUD__c</fullName>
    <label>Local tax in AUD</label>
    <summarizedField>Room__c.Local_tax_in_AUD__c</summarizedField>
    <summaryForeignKey>Room__c.Booking_Hotel__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Booking_Hotel__c/fields/ordexp_Coupon_Payment_Received__c.field-meta.xml
<CustomField>
    <fullName>ordexp_Coupon_Payment_Received__c</fullName>
    <formula>TAD_Order__r.Total_Order_OLI_Coupon__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Coupon Payment Received</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Booking_Hotel__c/fields/ordexp_Total_Payment_Received__c.field-meta.xml
<CustomField>
    <fullName>ordexp_Total_Payment_Received__c</fullName>
    <formula>TAD_Order__r.ordexp_total_payment_received__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Payment Received</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Booking_Hotel__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On Hold</fullName>
                <default>true</default>
                <label>On Hold</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Travelled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking_Hotel__c/fields/Subtotal__c.field-meta.xml
<CustomField>
    <fullName>Subtotal__c</fullName>
    <label>Subtotal</label>
    <summarizedField>Room__c.Total_Room_Cost__c</summarizedField>
    <summaryForeignKey>Room__c.Booking_Hotel__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Booking_Hotel__c/fields/TAD_Order__c.field-meta.xml
<CustomField>
    <fullName>TAD_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TAD Order</label>
    <referenceTo>TAD_Order__c</referenceTo>
    <relationshipLabel>Booking Hotels</relationshipLabel>
    <relationshipName>Booking_Hotels</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking_Hotel__c/fields/Total_Amount_Outstanding__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_Outstanding__c</fullName>
    <formula>IF( ISPICKVAL( CanRef_status__c , &apos;Processed&apos;) , 0, Gross_Cost__c -  (ordexp_Total_Payment_Received__c + ordexp_Coupon_Payment_Received__c))</formula>
    <label>Total Amount Outstanding</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Cancellation_Refund_POE__c/Cancellation_Refund_POE__c.object-meta.xml
<CustomObject>
    <label>Cancellation/Refund</label>
    <nameField>
        <displayFormat>CanRef-{00000}</displayFormat>
        <label>Cancelation/Refund Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cancellations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cancellation_Refund_POE__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Documentation</fullName>
            </value>
            <value>
                <fullName>Pending CS Approval</fullName>
            </value>
            <value>
                <fullName>CS Approved</fullName>
            </value>
            <value>
                <fullName>CS Rejected</fullName>
            </value>
            <value>
                <fullName>Pending Finance Approval</fullName>
            </value>
            <value>
                <fullName>Finance Approved</fullName>
            </value>
            <value>
                <fullName>Finance Rejected</fullName>
            </value>
            <value>
                <fullName>More Information Required by Finance</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Approved-Refund Not Processed</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Approved-Not Processed</fullName>
                <isActive>false</isActive>
                <label>Approved - Refund Not Processed</label>
            </value>
            <value>
                <fullName>Not Approved</fullName>
                <isActive>false</isActive>
                <label>Not Approved</label>
            </value>
            <value>
                <fullName>Not Submitted</fullName>
                <isActive>false</isActive>
                <label>Not Submitted</label>
            </value>
            <value>
                <fullName>Submitted and Pending</fullName>
                <isActive>false</isActive>
                <label>Submitted and Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cancellation_Refund_POE__c/fields/Tad_Booking_Hotel__c.field-meta.xml
<CustomField>
    <fullName>Tad_Booking_Hotel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking Hotel</label>
    <referenceTo>Booking_Hotel__c</referenceTo>
    <relationshipLabel>Cancellations</relationshipLabel>
    <relationshipName>Cancellations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/order_line_POE__c/order_line_POE__c.object-meta.xml
<CustomObject>
    <label>Order Line</label>
    <nameField>
        <displayFormat>OL-{00000000}</displayFormat>
        <label>Order Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/order_line_POE__c/fields/Room__c.field-meta.xml
<CustomField>
    <fullName>Room__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Room</label>
    <referenceTo>Room__c</referenceTo>
    <relationshipLabel>Order Lines</relationshipLabel>
    <relationshipName>Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/order_line_POE__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Updated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/order_line_POE__c/fields/TAD_Order__c.field-meta.xml
<CustomField>
    <fullName>TAD_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TAD Order</label>
    <referenceTo>TAD_Order__c</referenceTo>
    <relationshipLabel>Order Lines</relationshipLabel>
    <relationshipName>Order_Lines_POE</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Room__c/Room__c.object-meta.xml
<CustomObject>
    <label>Room</label>
    <nameField>
        <displayFormat>Room-{0000}</displayFormat>
        <label>Room Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Room__c/fields/Booking_Hotel__c.field-meta.xml
<CustomField>
    <fullName>Booking_Hotel__c</fullName>
    <label>Booking Hotel</label>
    <referenceTo>Booking_Hotel__c</referenceTo>
    <relationshipLabel>Rooms</relationshipLabel>
    <relationshipName>Rooms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/Cancellation_Amount_Room__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Amount_Room__c</fullName>
    <label>Cancellation Amount Room</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/Cancellation_Refund__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Refund__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cancellation/Refund</label>
    <referenceTo>Cancellation_Refund_POE__c</referenceTo>
    <relationshipLabel>Rooms</relationshipLabel>
    <relationshipName>Rooms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/Local_tax_in_AUD__c.field-meta.xml
<CustomField>
    <fullName>Local_tax_in_AUD__c</fullName>
    <label>Local tax in AUD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Room__c/fields/Total_Room_Cost__c.field-meta.xml
<CustomField>
    <fullName>Total_Room_Cost__c</fullName>
    <formula>Room_Price__c + Taxes__c + Extra_guest_price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Room Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/TAD_Order__c.object-meta.xml
<CustomObject>
    <label>TAD Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TAD Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TAD_Order__c/fields/Booking_Hotel__c.field-meta.xml
<CustomField>
    <fullName>Booking_Hotel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking Hotel</label>
    <referenceTo>Booking_Hotel__c</referenceTo>
    <relationshipLabel>TAD Orders</relationshipLabel>
    <relationshipName>TAD_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_total_payment_received__c.field-meta.xml
<CustomField>
    <fullName>ordexp_total_payment_received__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Payment Received</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/recordTypes/Hotel.recordType-meta.xml
<RecordType>
    <fullName>Hotel</fullName>
    <active>true</active>
    <description>Used for Expedia Bookings</description>
    <label>Hotel</label>
</RecordType>

force-app/main/default/classes/Exp_CancellationRefundforHotelHandler.cls
public class Exp_CancellationRefundforHotelHandler {
    public static void createCanRefRecordHotel(Map<Id,Id> HotelcancellationId){
        
        
        Map<Id,Id> tadOrderBookingHotel = new Map<Id,Id>();
        List<Cancellation_Refund_POE__c>canList =new List<Cancellation_Refund_POE__c>();
        
        id TadOrder;
        Id bookingHotelId;
        Id canRefId;
        Id tadownerId;
        Decimal outstandingAmount = 0.00;
        for(Id s : HotelcancellationId.values()){
            TadOrder = s;
        }
        system.debug('Line14 '+TadOrder);
        
       List<Booking_Hotel__c> BookingHotelList = [select Id,ordexp_Total_Payment_Received__c,ordexp_Coupon_Payment_Received__c,Subtotal__c,Total_Amount_Outstanding__c,Cancellation_Amount__c,CanRef_status__c from Booking_Hotel__c where ID IN: HotelcancellationId.keySet()];
                system.debug('Line18 '+BookingHotelList);

        for(Booking_Hotel__c b : BookingHotelList){
              outstandingAmount = -(b.Total_Amount_Outstanding__c);
            if(outstandingAmount < (b.ordexp_Total_Payment_Received__c + b.ordexp_Coupon_Payment_Received__c)){
                system.debug('Line15 ');
                b.CanRef_status__c ='Partial Refund Processed';
            }
            if(outstandingAmount == (b.ordexp_Total_Payment_Received__c + b.ordexp_Coupon_Payment_Received__c)){
                 b.CanRef_status__c ='Full Refund Processed';
            }
        }
        update BookingHotelList;
        
        List<Room__c> roomList = [select Id,Booking_Hotel__c,Total_Room_Cost__c,Booking_Hotel__r.TAD_Order__c,Booking_Hotel__r.Cancellation_Amount_Order__c,Booking_Hotel__r.Subtotal__c,Booking_Hotel__r.Local_tax_in_AUD__c,Cancellation_Refund__c,Cancellation_Refund__r.Approval_Status__c from Room__c where Booking_Hotel__c IN: HotelcancellationId.keySet() AND Status__c = 'Cancelled'];
        system.debug('Line--20-->'+roomList);
        system.debug('Line--20-->'+roomList.size());
        
        /*for(Room__c ro : roomList){
            if(ro.Cancellation_Refund__c !=null && ro.Cancellation_Refund__r.Approval_Status__c != 'Processed'){
                ro.Status__c = 'Cancelled';
                ro.Cancellation_Amount_Room__c =  ((((ro.Booking_Hotel__r.Cancellation_Amount_Order__c)*(ro.Total_Room_Cost__c))/ro.Booking_Hotel__r.Subtotal__c));  
                
                
            }
            if(ro.Cancellation_Refund__c ==null){
                ro.Status__c = 'Cancelled';
                ro.Cancellation_Amount_Room__c =  ((((ro.Booking_Hotel__r.Cancellation_Amount_Order__c)*(ro.Total_Room_Cost__c))/ro.Booking_Hotel__r.Subtotal__c));  
                
            }
            
            
        }
        if(!roomList.isEmpty()){
            update roomList; 
        }*/
        List<order_line_POE__c> OlList = [select Id,Status__c from order_line_POE__c where Room__c IN: roomList];
        system.debug('Line--42-->'+OlList);
        system.debug('Line--43-->'+OlList.size());
        
        for(order_line_POE__c ro : OlList){
            ro.Status__c = 'Cancelled';
        }
        if(!OlList.isEmpty()){
            update OlList;
        }
        
        
        
        
    }
    
    public static void createCanRefRecordRoomHotel(Map<Id,Id> RoomcancellationId){
        
        system.debug('Line--55-->'+RoomcancellationId.values());
        List<Cancellation_Refund_POE__c> deleteOldCanRef = new List<Cancellation_Refund_POE__c>();
        List<Cancellation_Refund_POE__c>oldcanList =[Select Id from Cancellation_Refund_POE__c where Tad_Booking_Hotel__c IN:RoomcancellationId.keyset()];
        system.debug('line--60-->'+oldcanList);
        for(Cancellation_Refund_POE__c can : oldcanList){
            deleteOldCanRef.add(can);
        }
        delete deleteOldCanRef;
        List<Booking_Hotel__c> bookinghotelslist = [select Id,Gross_Cost__c,Total_Amount_Outstanding__c,TAD_Order__c,Expedia_Booking_Amount__c,QFF_Payment__c,Total_Payment_Received_Without_QFF__c,TAD_Order__r.OwnerId,Cancellation_Amount__c,ordexp_Total_QFF_Received__c,ordexp_Coupon_Payment_Received__c,ordexp_Total_Payment_Received__c from Booking_Hotel__c where ID IN: RoomcancellationId.keyset()];
        
        Map<Id,Id> tadOrderBookingHotel = new Map<Id,Id>();
        List<Cancellation_Refund_POE__c>canList =new List<Cancellation_Refund_POE__c>();
        
        //   Id hotelRecordTypeId = Schema.SObjectType.Cancellation_Refund_POE__c.getRecordTypeInfosByName().get('Hotel Cancellation').getRecordTypeId();
        Id roomId;
        Id canRefId;
        Id tadownerId;
        Boolean negativeValue = false;
        Decimal outstandingAmount = 0.00;
        Set<Id> bookingHotelIdSet = new Set<Id>();
        Decimal CanAmt = 0.00;
        for(Booking_Hotel__c bho : bookinghotelslist){
            if(bho.ordexp_Total_QFF_Received__c < 0.00){
                negativeValue = true;
            }
            outstandingAmount = -(bho.Total_Amount_Outstanding__c);
            CanAmt = outstandingAmount;
            tadownerId = bho.TAD_Order__r.OwnerId;
            Cancellation_Refund_POE__c can = new Cancellation_Refund_POE__c();
            can.ordexp_tad_order__c = bho.TAD_Order__c;
            can.Tad_Booking_Hotel__c = bho.Id;
            can.Approval_Status__c = 'Pending Finance Approval';
            can.Cancellation_Type__c = 'Cancellation';
            can.Type__c = 'Refund Required';
            can.Room_Cancellation_Amount__c = -(bho.Total_Amount_Outstanding__c);
            system.debug('Line--103-->'+ bho.Gross_Cost__c);
            
            system.debug('Line--110-->'+bho.ordexp_Coupon_Payment_Received__c);
                 system.debug('Line--111-->'+bho.ordexp_Total_QFF_Received__c);
             system.debug('Line--112-->'+ outstandingAmount);
            if(outstandingAmount > bho.ordexp_Total_QFF_Received__c){
                 system.debug('Line--113-->'+ 'True');
            }
            
            if((bho.ordexp_Coupon_Payment_Received__c == null || bho.ordexp_Coupon_Payment_Received__c == 0.00) && (bho.ordexp_Total_QFF_Received__c == null || bho.ordexp_Total_QFF_Received__c == 0.00)){
                can.Refund_Amount__c = outstandingAmount;                
            }
            if(bho.ordexp_Coupon_Payment_Received__c != null && bho.ordexp_Coupon_Payment_Received__c != 0.00 && (bho.ordexp_Total_QFF_Received__c ==null || bho.ordexp_Total_QFF_Received__c ==0.00) && (outstandingAmount > bho.ordexp_Coupon_Payment_Received__c)){
                can.Coupon_Amount__c = bho.ordexp_Coupon_Payment_Received__c;
                can.Refund_Amount__c = outstandingAmount-bho.ordexp_Coupon_Payment_Received__c;
            }
            if(bho.ordexp_Coupon_Payment_Received__c != null && bho.ordexp_Coupon_Payment_Received__c != 0.00 && (bho.ordexp_Total_QFF_Received__c ==null || bho.ordexp_Total_QFF_Received__c ==0.00) && (outstandingAmount == bho.ordexp_Coupon_Payment_Received__c)){
                can.Coupon_Amount__c = outstandingAmount;
            }
            if(bho.ordexp_Coupon_Payment_Received__c != null && bho.ordexp_Coupon_Payment_Received__c != 0.00 && (bho.ordexp_Total_QFF_Received__c ==null || bho.ordexp_Total_QFF_Received__c ==0.00) && (bho.ordexp_Total_Payment_Received__c  ==null || bho.ordexp_Total_Payment_Received__c  ==0.00) && (outstandingAmount < bho.ordexp_Coupon_Payment_Received__c)){
                can.Coupon_Amount__c = outstandingAmount;
            }
            if(bho.ordexp_Coupon_Payment_Received__c != null && bho.ordexp_Coupon_Payment_Received__c != 0.00 && (bho.ordexp_Total_QFF_Received__c ==null || bho.ordexp_Total_QFF_Received__c ==0.00) && (bho.ordexp_Total_Payment_Received__c  !=null || bho.ordexp_Total_Payment_Received__c  !=0.00) && (outstandingAmount < bho.ordexp_Coupon_Payment_Received__c)){
                can.Coupon_Amount__c = outstandingAmount;
            }
            
            if(bho.ordexp_Coupon_Payment_Received__c != null && bho.ordexp_Coupon_Payment_Received__c != 0.00 && bho.ordexp_Total_QFF_Received__c !=null && bho.ordexp_Total_QFF_Received__c != 0.00 && negativeValue ==false && (outstandingAmount > bho.ordexp_Total_QFF_Received__c)){                       
                can.QFF_Refund__c = bho.ordexp_Total_QFF_Received__c;
                
                if(can.QFF_Refund__c !=Null && ((outstandingAmount - bho.ordexp_Total_QFF_Received__c) > bho.ordexp_Coupon_Payment_Received__c)){
                    can.Coupon_Amount__c = bho.ordexp_Coupon_Payment_Received__c;
                    can.Refund_Amount__c = outstandingAmount - bho.ordexp_Coupon_Payment_Received__c - bho.ordexp_Total_QFF_Received__c;
                    
                }
                else if(can.QFF_Refund__c !=Null && ((outstandingAmount - bho.ordexp_Total_QFF_Received__c) < bho.ordexp_Coupon_Payment_Received__c)){
                    can.Coupon_Amount__c = outstandingAmount - bho.ordexp_Total_QFF_Received__c;
                    if(outstandingAmount > (bho.ordexp_Coupon_Payment_Received__c + bho.ordexp_Total_QFF_Received__c)){
                        can.Refund_Amount__c = outstandingAmount - (bho.ordexp_Coupon_Payment_Received__c + bho.ordexp_Total_QFF_Received__c);
                        
                    }
                    else{
                        can.Refund_Amount__c =0;
                        
                    }
                    
                }
                else if(can.QFF_Refund__c !=Null && ((outstandingAmount - bho.ordexp_Total_QFF_Received__c) == (bho.ordexp_Coupon_Payment_Received__c))){
                    can.Coupon_Amount__c = outstandingAmount - bho.ordexp_Total_QFF_Received__c;
                    
                }
                else{
                    can.Refund_Amount__c = outstandingAmount - bho.ordexp_Total_QFF_Received__c;
                    
                }
                
            }
            if(bho.ordexp_Coupon_Payment_Received__c != null && bho.ordexp_Coupon_Payment_Received__c != 0.00 && bho.ordexp_Total_QFF_Received__c !=null && bho.ordexp_Total_QFF_Received__c != 0.00 && negativeValue ==false && (outstandingAmount < bho.ordexp_Total_QFF_Received__c)){                       
                system.debug('Line--158-->'+bho.ordexp_Coupon_Payment_Received__c);
                 system.debug('Line--159-->'+bho.ordexp_Total_QFF_Received__c);
                can.QFF_Refund__c =0.00;
                can.Coupon_Amount__c = outstandingAmount;
                can.Refund_Amount__c = 0.00;
                
            }
            if(bho.ordexp_Coupon_Payment_Received__c != null && bho.ordexp_Coupon_Payment_Received__c != 0.00 && bho.ordexp_Total_QFF_Received__c !=null && bho.ordexp_Total_QFF_Received__c != 0.00 && bho.QFF_Payment__c == True && negativeValue ==false && (outstandingAmount == bho.ordexp_Total_QFF_Received__c)){                       
                can.QFF_Refund__c = outstandingAmount;
                can.Coupon_Amount__c = 0.00;
                can.Refund_Amount__c = 0.00;
                
            }
            if((bho.ordexp_Coupon_Payment_Received__c == 0.00 || bho.ordexp_Coupon_Payment_Received__c == null) && (bho.ordexp_Total_QFF_Received__c !=null && bho.ordexp_Total_QFF_Received__c != 0.00)  && bho.QFF_Payment__c == True && negativeValue ==false && (outstandingAmount == bho.ordexp_Total_QFF_Received__c)){
                can.QFF_Refund__c = outstandingAmount;
            }
            if((bho.ordexp_Coupon_Payment_Received__c == 0.00 || bho.ordexp_Coupon_Payment_Received__c == null) && (bho.ordexp_Total_QFF_Received__c !=null && bho.ordexp_Total_QFF_Received__c != 0.00) && bho.QFF_Payment__c == True && negativeValue ==false && (outstandingAmount < bho.ordexp_Total_QFF_Received__c)){
                can.Coupon_Amount__c = outstandingAmount;
            }
            if((bho.ordexp_Coupon_Payment_Received__c == 0.00 || bho.ordexp_Coupon_Payment_Received__c == null) && (bho.ordexp_Total_QFF_Received__c !=null && bho.ordexp_Total_QFF_Received__c != 0.00) && (bho.ordexp_Total_Payment_Received__c !=null && bho.ordexp_Total_Payment_Received__c != 0.00) && bho.QFF_Payment__c == True && negativeValue ==false && (outstandingAmount > bho.ordexp_Total_QFF_Received__c)){
                can.QFF_Refund__c = bho.ordexp_Total_QFF_Received__c;
                can.Refund_Amount__c = outstandingAmount - bho.ordexp_Total_QFF_Received__c;
            }
            if((bho.ordexp_Coupon_Payment_Received__c == 0.00 || bho.ordexp_Coupon_Payment_Received__c == null) && (bho.ordexp_Total_QFF_Received__c !=null && bho.ordexp_Total_QFF_Received__c != 0.00) && (bho.ordexp_Total_Payment_Received__c !=null && bho.ordexp_Total_Payment_Received__c != 0.00) && bho.QFF_Payment__c == True && negativeValue ==false && (outstandingAmount < bho.ordexp_Total_QFF_Received__c)){
                can.Coupon_Amount__c = outstandingAmount;
            }
            if((bho.ordexp_Coupon_Payment_Received__c == 0.00 || bho.ordexp_Coupon_Payment_Received__c == null) && (bho.ordexp_Total_QFF_Received__c !=null && bho.ordexp_Total_QFF_Received__c != 0.00) && (bho.ordexp_Total_Payment_Received__c !=null && bho.ordexp_Total_Payment_Received__c != 0.00) && bho.QFF_Payment__c == True && negativeValue ==false && (outstandingAmount == bho.ordexp_Total_QFF_Received__c)){
                can.QFF_Refund__c = bho.ordexp_Total_QFF_Received__c;
                //can.Refund_Amount__c = bho.ordexp_Total_Payment_Received__c - bho.ordexp_Total_QFF_Received__c;
            }
            
            
            canList.add(can);
        }
        if(!canList.isEmpty()){
            insert canList; 
        }
        
        system.debug('Line27 '+canList);
        for(Cancellation_Refund_POE__c can1 : canList){
            
            tadOrderBookingHotel.put(can1.ordexp_tad_order__c,can1.Id);
            
        }
        
        List<Room__c> roomListtoUpdate = new List<Room__c>();
        
        List<Room__c> roomList = [select Id,Booking_Hotel__c,Cancellation_Amount_Room__c,Booking_Hotel__r.TAD_Order__c,Cancellation_Refund__c from Room__c where Booking_Hotel__c IN: RoomcancellationId.keySet() AND Status__c = 'Cancelled'];
       
        for(Room__c r1 : roomList){
            canRefId = tadOrderBookingHotel.get(r1.Booking_Hotel__r.TAD_Order__c);
            r1.Cancellation_Refund__c = tadOrderBookingHotel.get(r1.Booking_Hotel__r.TAD_Order__c);
            roomListtoUpdate.add(r1);
            
        }
        if(!roomListtoUpdate.isEmpty()){
            update roomListtoUpdate; 
        }
        system.debug('Line--180-->'+roomListtoUpdate);
        system.debug('Line--209->'+CanAmt);
        system.debug('Line--210->'+canRefId);
        system.debug('Line--211->'+tadownerId);
        
        
        
        
        Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
        req1.setComments('Submitting request for approval.');
        req1.setObjectId(canRefId);
        req1.setSubmitterId(tadownerId); 
        req1.setProcessDefinitionNameOrId('Cancellation_Refund_Approval_Process_BH');
        req1.setSkipEntryCriteria(true);
        if(CanAmt != null){
        Approval.ProcessResult result = Approval.process(req1);
        }
        // Code to cancel the booking record
        List<Booking_Hotel__c> orderData =[Select id,Status__c,(Select Id,Status__c from Rooms__r where Status__c!='Cancelled' ) from Booking_Hotel__c where Id IN: RoomcancellationId.keyset() AND Modification_in_Progress__c = false AND Expedia_Booking_Amount__c = 0.00];
        
        List<Booking_Hotel__c> bhUpdate = new List<Booking_Hotel__c>();
        for(Booking_Hotel__c td : orderData)
        {    
            if(td.Rooms__r.size() == 0){
                td.Status__c = 'Cancelled';
                bhUpdate.add(td);
            }
        }
        
        if(!bhUpdate.isEmpty()){
            update bhUpdate;   
        }
    }
    
          public static void updateBookingStatusToProcessed(Set<Id> tadCanRefId){
            List<Booking_Hotel__c> bookinghotelslist = [select Id,CanRef_status__c,Refund_Type__c,Cancellation_Refund__c,Cancellation_Refund__r.Approval_Status__c,TAD_Order__c,TAD_Order__r.ordexp_gross_amount__c,Cancellation_Amount__c from Booking_Hotel__c where TAD_Order__c IN: tadCanRefId];
            For(Booking_Hotel__c bo : bookinghotelslist){
                bo.CanRef_status__c = 'Processed';
            }
            System.debug('Line--262-->'+bookinghotelslist);
            update bookinghotelslist;
        }
}