force-app/main/default/objects/Attached_Inclusions__c/Attached_Inclusions__c.object-meta.xml
<CustomObject>
    <label>Attached Inclusions</label>
    <nameField>
        <displayFormat>AttInc-{0000000}</displayFormat>
        <label>Attached Inclusions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attached Inclusions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Attached_Inclusions__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Attached Inclusions</relationshipLabel>
    <relationshipName>Attached_Inclusions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Attached_Inclusions__c/fields/Options__c.field-meta.xml
<CustomField>
    <fullName>Options__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Options</label>
    <referenceTo>options__c</referenceTo>
    <relationshipLabel>Attached Inclusions</relationshipLabel>
    <relationshipName>Attached_Inclusions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal__c/Deal__c.object-meta.xml
<CustomObject>
    <label>Deal</label>
    <nameField>
        <label>Deal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/options__c/options__c.object-meta.xml
<CustomObject>
    <label>Options</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/options__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipName>options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/dealAttachInclusionsController.cls
public class dealAttachInclusionsController {
    
    public class initWrapper{
        @AuraEnabled public integer countOfHighlightedInclusions {get;set;}
        @AuraEnabled public List<RecordTypeWrapper> RecordTypeWrapper {get;set;}
        @AuraEnabled public String highlightsRecordId {get;set;}
        @AuraEnabled public Boolean isDealObject {get;set;}
    }
    
    public class RecordTypeWrapper{
        @AuraEnabled public string RecordTypeName {get;set;}
        @AuraEnabled public string RecordTypeId {get;set;}
    }	    
    
    @AuraEnabled
    public static initWrapper getInitDetails(String recordId){
        
        initWrapper initWrapperInstance = new initWrapper();
        
        Id recordIdFinal = recordId;
        String sObjName = recordIdFinal.getSObjectType().getDescribe().getName();
        
        
        String dealHighlightsRecordTypeID = Schema.SObjectType.Attached_Inclusions__c.getRecordTypeInfosByName().get('Deal - Highlights').getRecordTypeId();
        List<Attached_Inclusions__c> listOfAttachedInclusions = [Select id, Name, RecordTypeId from Attached_Inclusions__c where Deal__c =: recordId and RecordTypeId =: dealHighlightsRecordTypeID];
        initWrapperInstance.countOfHighlightedInclusions = listOfAttachedInclusions.size();
        
        List<RecordTypeWrapper> rctWrapper = new List<RecordTypeWrapper>();
        
        Map<String, Id> mapOfRecordTypeWithIds = TADUtils.getObjectNameRecordTypeId('Attached_Inclusions__c');
        
        for(String str : mapOfRecordTypeWithIds.keyset()){
            if(sObjName == 'Deal__c'){
                initWrapperInstance.isDealObject = true;
                if(!str.containsIgnoreCase('Room')){
                    RecordTypeWrapper rctWrapInstance = new RecordTypeWrapper();
                    rctWrapInstance.RecordTypeName = str;
                    rctWrapInstance.RecordTypeId = mapOfRecordTypeWithIds.get(str);
                    rctWrapper.add(rctWrapInstance);
                }
            }else{
                initWrapperInstance.isDealObject = false;
                if(str.containsIgnoreCase('Room')){
                    RecordTypeWrapper rctWrapInstance = new RecordTypeWrapper();
                    rctWrapInstance.RecordTypeName = str;
                    rctWrapInstance.RecordTypeId = mapOfRecordTypeWithIds.get(str);
                    rctWrapper.add(rctWrapInstance);
                }
            }
        }
        initWrapperInstance.highlightsRecordId = dealHighlightsRecordTypeID;
        initWrapperInstance.RecordTypeWrapper = rctWrapper;
        return initWrapperInstance;
    }
    
    @AuraEnabled
    public static void insertAttachedInclusions(String jsonOfListOfAttachedInclusions, String recordId) {
        
        system.debug('jsonOfListOfAttachedInclusions ---> '+jsonOfListOfAttachedInclusions);
        
        Id recordIdFinal = recordId;
        String sObjName = recordIdFinal.getSObjectType().getDescribe().getName();
        
        
        List<Attached_Inclusions__c> listOfInclusions = (List<Attached_Inclusions__c>) JSON.deserialize(jsonOfListOfAttachedInclusions, List<Attached_Inclusions__c>.class);
        for(Attached_Inclusions__c att: listOfInclusions ){
            if(sObjName == 'Deal__c'){
                att.Deal__c = recordId;
            }
            
            if(sObjName == 'options__c'){
                att.Options__c = recordId;
            }
        }
        
        insert listOfInclusions;
    }
    
    
}