force-app/main/default/objects/customer__c/customer__c.object-meta.xml
<CustomObject>
    <label>Passengers (Old)</label>
    <nameField>
        <displayFormat>PIF-{00000000}</displayFormat>
        <label>id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Passengers (Old)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/customer__c/fields/agency_id__c.field-meta.xml
<CustomField>
    <fullName>agency_id__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Agency Id</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Passengers</relationshipLabel>
    <relationshipName>Passengers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/customer__c/fields/dob__c.field-meta.xml
<CustomField>
    <fullName>dob__c</fullName>
    <label>D.O.B</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/customer__c/fields/link_to_full_name__c.field-meta.xml
<CustomField>
    <fullName>link_to_full_name__c</fullName>
    <label>LINK TO FULL NAME</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/customer__c/fields/order__c.field-meta.xml
<CustomField>
    <fullName>order__c</fullName>
    <label>Order Number</label>
    <referenceTo>order__c</referenceTo>
    <relationshipLabel>Passengers</relationshipLabel>
    <relationshipName>customer</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/order__c/order__c.object-meta.xml
<CustomObject>
    <label>orders</label>
    <nameField>
        <displayFormat>{00}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>order</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>TAD Person Account</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Old)</relationshipLabel>
    <relationshipName>order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/order__c/fields/agency_id__c.field-meta.xml
<CustomField>
    <fullName>agency_id__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Agency Id</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>order (Agency Id)</relationshipLabel>
    <relationshipName>order1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/order__c/fields/Link_to_another_order__c.field-meta.xml
<CustomField>
    <fullName>Link_to_another_order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Link to another order</label>
    <referenceTo>order__c</referenceTo>
    <relationshipLabel>order</relationshipLabel>
    <relationshipName>order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/order__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <formula>Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/customercSearchController.cls
public class customercSearchController {

    @AuraEnabled
    public static customercPagedResult findAll(String searchKey, Decimal pageNumber) {
        Integer pageSize = 12;
        String key = '%' + searchKey + '%';
        Integer offset = ((Integer)pageNumber - 1) * pageSize;

        customercPagedResult r =  new customercPagedResult();
        r.pageSize = pageSize;
        r.page = (Integer) pageNumber;
        r.total = [SELECT count() FROM customer__c
        WHERE (Name LIKE :key OR first_name__c LIKE :key OR last_name__c LIKE :key OR order__r.Name LIKE :key) AND agency_id__c IN (SELECT Id FROM Account WHERE PersonEmail = :UserInfo.getUserEmail())];
        r.products = [SELECT Id, Name, first_name__c, last_name__c, dob__c, order__r.Id, order__r.Name, link_to_full_name__c, pif_final__c FROM customer__c
        WHERE (Name LIKE :key OR first_name__c LIKE :key OR last_name__c LIKE :key OR order__r.Name LIKE :key) AND agency_id__c IN (SELECT Id FROM Account WHERE PersonEmail = :UserInfo.getUserEmail())
        ORDER BY NAME LIMIT 12 OFFSET :offset];
        System.debug(r);
        return r;
    }
}