force-app/main/default/objects/PNR__c/PNR__c.object-meta.xml
<CustomObject>
    <label>PNR (Old)</label>
    <nameField>
        <label>PNR Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PNR (Old)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PNR__c/fields/Base_Price__c.field-meta.xml
<CustomField>
    <fullName>Base_Price__c</fullName>
    <label>Base Price</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PNR__c/fields/Base_Price_Currency__c.field-meta.xml
<CustomField>
    <fullName>Base_Price_Currency__c</fullName>
    <label>Base Price Currency</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PNR__c/fields/Creation_Agent_Id__c.field-meta.xml
<CustomField>
    <fullName>Creation_Agent_Id__c</fullName>
    <label>Creation Agent Id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PNR__c/fields/Equiv_Price__c.field-meta.xml
<CustomField>
    <fullName>Equiv_Price__c</fullName>
    <label>Equiv Price</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PNR__c/fields/Equiv_Price_Currency__c.field-meta.xml
<CustomField>
    <fullName>Equiv_Price_Currency__c</fullName>
    <label>Equiv Price Currency</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PNR__c/fields/PNR_Sequence__c.field-meta.xml
<CustomField>
    <fullName>PNR_Sequence__c</fullName>
    <label>PNR Sequence</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PNR__c/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <label>Total Price from GDS</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PNR__c/fields/Total_Price_Currency__c.field-meta.xml
<CustomField>
    <fullName>Total_Price_Currency__c</fullName>
    <label>Total Price Currency</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PNR__c/fields/Total_Tax_Currency__c.field-meta.xml
<CustomField>
    <fullName>Total_Tax_Currency__c</fullName>
    <label>Total Tax Currency</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PNR_Accounting_Line_POE__c/PNR_Accounting_Line_POE__c.object-meta.xml
<CustomObject>
    <label>PNR Accounting Line</label>
    <nameField>
        <displayFormat>PAL-{000000000}</displayFormat>
        <label>PNR Accounting Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PNR Accounting Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PNR_Accounting_Line_POE__c/fields/pnr__c.field-meta.xml
<CustomField>
    <fullName>pnr__c</fullName>
    <label>PNR</label>
    <referenceTo>PNR_POE__c</referenceTo>
    <relationshipLabel>PNR Accounting Lines</relationshipLabel>
    <relationshipName>PNR_Accounting_Lines_POE</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PNR_Accounting_Line_POE__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Exchanged</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PNR_Accounting_Line_POE__c/fields/type__c.field-meta.xml
<CustomField>
    <fullName>type__c</fullName>
    <label>Type</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PNR_POE__c/PNR_POE__c.object-meta.xml
<CustomObject>
    <label>PNR</label>
    <nameField>
        <label>PNR Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PNR</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PNR_POE__c/fields/Base_Price__c.field-meta.xml
<CustomField>
    <fullName>Base_Price__c</fullName>
    <label>Base Price</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PNR_POE__c/fields/Base_Price_Currency__c.field-meta.xml
<CustomField>
    <fullName>Base_Price_Currency__c</fullName>
    <label>Base Price Currency</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PNR_POE__c/fields/Creation_Agent_Id__c.field-meta.xml
<CustomField>
    <fullName>Creation_Agent_Id__c</fullName>
    <label>Creation Agent Id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PNR_POE__c/fields/Equiv_Price__c.field-meta.xml
<CustomField>
    <fullName>Equiv_Price__c</fullName>
    <label>Equiv Price</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PNR_POE__c/fields/Equiv_Price_Currency__c.field-meta.xml
<CustomField>
    <fullName>Equiv_Price_Currency__c</fullName>
    <label>Equiv Price Currency</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PNR_POE__c/fields/PNR_Sequence__c.field-meta.xml
<CustomField>
    <fullName>PNR_Sequence__c</fullName>
    <label>PNR Sequence</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PNR_POE__c/fields/TAD_Order__c.field-meta.xml
<CustomField>
    <fullName>TAD_Order__c</fullName>
    <label>TAD Order</label>
    <referenceTo>TAD_Order__c</referenceTo>
    <relationshipLabel>PNR (POE)</relationshipLabel>
    <relationshipName>PNR_POE</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PNR_POE__c/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <label>Total Price from GDS</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PNR_POE__c/fields/Total_Price_Currency__c.field-meta.xml
<CustomField>
    <fullName>Total_Price_Currency__c</fullName>
    <label>Total Price Currency</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PNR_POE__c/fields/Total_Tax__c.field-meta.xml
<CustomField>
    <fullName>Total_Tax__c</fullName>
    <label>Total Tax</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PNR_POE__c/fields/Total_Tax_Currency__c.field-meta.xml
<CustomField>
    <fullName>Total_Tax_Currency__c</fullName>
    <label>Total Tax Currency</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Segment_POE__c/Segment_POE__c.object-meta.xml
<CustomObject>
    <label>Segment</label>
    <nameField>
        <displayFormat>SG{00000000}</displayFormat>
        <label>Segment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Segment_POE__c/fields/Action_Code__c.field-meta.xml
<CustomField>
    <fullName>Action_Code__c</fullName>
    <label>Action Code</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Segment_POE__c/fields/arrival_date__c.field-meta.xml
<CustomField>
    <fullName>arrival_date__c</fullName>
    <formula>DATEVALUE( LEFT(Arrival_Date_Time_Text__c, 10) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Arrival Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Segment_POE__c/fields/arrival_date_time__c.field-meta.xml
<CustomField>
    <fullName>arrival_date_time__c</fullName>
    <formula>DATETIMEVALUE( LEFT(Arrival_Date_Time_Text__c, 10) &amp; &quot; &quot; &amp; RIGHT(Arrival_Date_Time_Text__c, 8) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Arrival Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Segment_POE__c/fields/Class_Of_Service__c.field-meta.xml
<CustomField>
    <fullName>Class_Of_Service__c</fullName>
    <label>Class Of Service</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Segment_POE__c/fields/Departure_Airport__c.field-meta.xml
<CustomField>
    <fullName>Departure_Airport__c</fullName>
    <label>Departure Airport</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Segment_POE__c/fields/departure_date__c.field-meta.xml
<CustomField>
    <fullName>departure_date__c</fullName>
    <formula>DATEVALUE( LEFT(Departure_Date_Time_Text__c, 10) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Departure Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Segment_POE__c/fields/departure_date_time__c.field-meta.xml
<CustomField>
    <fullName>departure_date_time__c</fullName>
    <formula>DATETIMEVALUE( LEFT(Departure_Date_Time_Text__c, 10) &amp; &quot; &quot; &amp; RIGHT(Departure_Date_Time_Text__c, 8) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Departure Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Segment_POE__c/fields/Departure_Date_Time_Text__c.field-meta.xml
<CustomField>
    <fullName>Departure_Date_Time_Text__c</fullName>
    <label>Departure Date Time Text</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Segment_POE__c/fields/Departure_Time__c.field-meta.xml
<CustomField>
    <fullName>Departure_Time__c</fullName>
    <formula>TIMEVALUE(departure_date_time__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Departure Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Segment_POE__c/fields/Flight_Number__c.field-meta.xml
<CustomField>
    <fullName>Flight_Number__c</fullName>
    <label>Flight Number</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Segment_POE__c/fields/Operating_Airline_Code__c.field-meta.xml
<CustomField>
    <fullName>Operating_Airline_Code__c</fullName>
    <label>Operating Airline Code</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Segment_POE__c/fields/PNR__c.field-meta.xml
<CustomField>
    <fullName>PNR__c</fullName>
    <label>PNR</label>
    <referenceTo>PNR_POE__c</referenceTo>
    <relationshipLabel>Segments</relationshipLabel>
    <relationshipName>Segments_POE</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Segment_POE__c/fields/Ticket_Number_From_Sabre__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Number_From_Sabre__c</fullName>
    <label>Ticket Number From Sabre</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/TAD_Order__c.object-meta.xml
<CustomObject>
    <label>TAD Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TAD Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TAD_Order__c/fields/mp_Coach_Color__c.field-meta.xml
<CustomField>
    <fullName>mp_Coach_Color__c</fullName>
    <defaultValue>&apos;None&apos;</defaultValue>
    <label>Coach Color</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
            <value>
                <fullName>Pink</fullName>
            </value>
            <value>
                <fullName>Blue</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
            <value>
                <fullName>Black</fullName>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Orange</fullName>
            </value>
            <value>
                <fullName>Purple</fullName>
            </value>
            <value>
                <fullName>Grey</fullName>
            </value>
            <value>
                <fullName>Darkcyan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_account__c.field-meta.xml
<CustomField>
    <fullName>ordexp_account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>TAD Orders</relationshipLabel>
    <relationshipName>TAD_Orders_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_deal__c.field-meta.xml
<CustomField>
    <fullName>ordexp_deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>TAD_Orders_Deal</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/PAX_Qty__c.field-meta.xml
<CustomField>
    <fullName>PAX_Qty__c</fullName>
    <label>PAX Qty</label>
    <summarizedField>order_line_item__c.PAX_Qty__c</summarizedField>
    <summaryFilterItems>
        <field>order_line_item__c.OLI_Status__c</field>
        <operation>notEqual</operation>
        <value>Cancelled</value>
    </summaryFilterItems>
    <summaryForeignKey>order_line_item__c.ordexp_TAD_Order__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/MP_BcPNRManualSync.cls
public class MP_BcPNRManualSync implements Database.Batchable<sObject>,Database.AllowsCallouts, Database.Stateful{
    Set<Id> orderIdSet = new Set<Id>();
    List<Id> orderIDsList = new List<Id>();
    public List<Segment_POE__c> flightManifestList = null;
    public Set<Id> PNRFreshedIDs = new Set<Id>();
    public Set<Id> pnrIdSet = new Set<Id>();
    
    
    public MP_BcPNRManualSync(List<Id> orderIDList){
        orderIDsList = orderIDList;
        orderIdSet.addAll(orderIDsList);
        flightManifestList = new List<Segment_POE__c>();    
    }
    
    public class PNRRequest {
        public string loactorName {get;set;}
        public string pnrRecordId {get;set;}
        public Decimal pnrSequence {get;set;}
        public string creationAgentId {get;set;}
        public Boolean isManualSync {get;set;}
        public string reasonForManualSync {get;set;}      
        public Decimal basePrice {get;set;}
        public string basePriceCurrency {get;set;}
        public Decimal equivPrice {get;set;}
        public string equivPriceCurrency {get;set;}
        public Decimal totalTax {get;set;}
        public string totalTaxCurrency {get;set;}
        public Decimal totalPrice {get;set;}
        public string totalPriceCurrency {get;set;}        
        public List<Segments>segments;
        public List<PNRAccountigLine>pnrAccountingLine;
    }
    
    public class PNRAccountigLine{
        // public string elementId {get;set;}
        public string documentNumber {get;set;}
        public string pnrAccLineRecordId {get;set;}
        //  public string orginalId {get;set;}
        //	public string passengerName {get;set;}
        public string pnrAccLineIdentifier {get;set;}
        
    }
    
    public class Segments{
        public string segmentRecordId {get;set;}
        // public string ticketNumbers {get;set;}
        // public string departureAirport {get;set;}
        // public string arrivalAirport {get;set;}
        public string flightNumber {get;set;}
        public string classOfService {get;set;}
        public string departureDateTime {get;set;}
        public string segmentIdentifier {get;set;}
        
    }
    
    public class FlightManifestWrapper{
        public String deal {get;set;}
        public String order {get;set;}
        public String departureDate {get; set;}
        public String groupColor {get; set;}
        public String pax {get;set;}
        public String departureAirpot {get;set;}
        public String departureDateTime {get;set;}
        public String arrivalDateTime {get;set;}
        public String FlightNumber{get;set;}
        
        
    }
    
    public Iterable<sObject> start(Database.BatchableContext info){    
        System.debug('MP_BcPNRManualSync='+orderIdSet.size());
        List<PNR_POE__c> pnrList = [SELECT id, Name,TAD_Order__r.Name, PNR_Sequence__c, Creation_Agent_Id__c, Base_Price__c, Base_Price_Currency__c, Equiv_Price__c, Equiv_Price_Currency__c, Total_Tax__c, Total_Tax_Currency__c, Total_Price__c, Total_Price_Currency__c,TAD_Order__r.Id FROM PNR_POE__c WHERE TAD_Order__r.Id IN :orderIdSet];
        System.debug('PNR List ='+pnrList.size());
        return pnrList;
    }
    
    public void execute(Database.BatchableContext info, List<PNR_POE__c> pnrList){
        System.debug('pnrList in execute - '+pnrList.size());
        Set<Id> pnrIdSet = (new Map<Id,SObject>(pnrList)).keySet();
        //PNRFreshedIDs.addAll(pnrIdSet);
        System.debug('pnrIdSet ='+pnrIdSet);
        List<PNRAccountigLine> PNRAccountigLineList = new List<PNRAccountigLine>();
        List<Segments> SegmentsList = new List<Segments>();
        List<Segment_POE__c> segsList = [Select id,Arrival_Airport__c,Arrival_Date_Time_Text__c,Operating_Airline_Code__c,PNR__r.TAD_Order__r.MP_Departure_Date__c,PNR__r.TAD_Order__r.Name,PNR__r.TAD_Order__r.ordexp_account__r.Name,PNR__r.TAD_Order__r.ordexp_deal__r.Name,PNR__r.TAD_Order__r.mp_Coach_Color__c, PNR__r.TAD_Order__r.PAX_Qty__c,Name,PNR__c,Type__c,Ticket_Number_From_Sabre__c,Status__c,Action_Code__c,Flight_Number__c,Departure_Date_Time_Text__c,Departure_Airport__c,departure_date__c,departure_date_time__c,Departure_Time__c,arrival_date__c,arrival_date_time__c,Class_Of_Service__c FROM Segment_POE__c where PNR__c IN :pnrIdSet ];        
        
        List<PNR_Accounting_Line_POE__c> palsList = [Select id,Name,PNR__c,Status__c,document_number__c,element_id__c,passenger_name__c from PNR_Accounting_Line_POE__c where PNR__c IN:pnrIdSet];
        
        
        for(PNR_Accounting_Line_POE__c pal : palsList){
           // if(pal.Status__c != 'Exchanged'){
                PNRAccountigLine panrpal = new PNRAccountigLine();
                panrpal.documentNumber = pal.document_number__c;
                //panrpal.elementId = pal.element_id__c;
                panrpal.pnrAccLineRecordId = pal.Id;
                panrpal.pnrAccLineIdentifier = pal.passenger_name__c;
                PNRAccountigLineList.add(panrpal);
          //  }
            
        }
        
        for(Segment_POE__c seg : segsList){

            if(seg.Status__c != 'Exchanged'){
                Segments segm = new Segments();
                segm.segmentRecordId = seg.Id;
                segm.flightNumber = seg.Flight_Number__c;
                segm.departureDateTime = seg.Departure_Date_Time_Text__c;
                segm.classOfService = seg.Class_Of_Service__c;              
                segm.segmentIdentifier = seg.Ticket_Number_From_Sabre__c != null ? seg.Departure_Airport__c+'-'+seg.Arrival_Airport__c+'-'+seg.Ticket_Number_From_Sabre__c :seg.Departure_Airport__c+'-'+seg.Arrival_Airport__c;               
                system.debug('departureDate----'+seg.Departure_Date_Time_Text__c);
                
                SegmentsList.add(segm);
            }           
        }
        
        String accessToken='';
        if(System.Label.PnrIsServerless == 'True'){    
        Http http1 = new Http();           
        HttpRequest request1 = new HttpRequest();     
        String endPointUrl1 = System.Label.Pnr_Token_Callout+System.Label.Pnr_Client_Id+'&scope=sf/write';        
        request1.setEndpoint(endPointUrl1);            
        request1.setMethod('POST');
        request1.setHeader('Authorization', 'Basic ' +System.Label.PnrAuthToken);
        request1.setHeader('Content-Type', 'application/x-www-form-urlencoded');
        request1.setHeader('Accept', '*/*');
        HttpResponse response1 = http1.send(request1);  
        system.debug('response-ses---39->'+response1);
        if(response1.getStatusCode() == 200) {   
            system.debug('response----39->'+response1.getBody());            
            String responseBody = response1.getBody();
           // system.debug('response--getstringtoken--39->'+responseBody);            
            Map<String, String> m = (Map<String, String>) JSON.deserialize(responseBody, Map<String, String>.class);
            accessToken = m.get('access_token');
            //System.debug('Token----'+accessToken);
        }
        }else{
            accessToken='abdhdgd' ;
        }
        
        System.debug('Token-61---'+accessToken);
        if(accessToken != ''){
        for(PNR_POE__c pnrObj : pnrList){
            System.debug('Order Processed'+pnrObj.TAD_Order__r.Name);
            PNRRequest pnrWrapper = new PNRRequest();
            pnrWrapper.pnrSequence = pnrObj.PNR_Sequence__c;
            pnrWrapper.loactorName = pnrObj.Name;
            pnrWrapper.pnrRecordId = pnrObj.Id;
            PNRFreshedIDs.add(pnrObj.Id);
            System.debug('Order procesed -'+pnrObj.TAD_Order__r.Name);
            pnrWrapper.creationAgentId = pnrObj.Creation_Agent_Id__c;
            pnrWrapper.basePrice = pnrObj.Base_Price__c;
            pnrWrapper.basePriceCurrency = pnrObj.Base_Price_Currency__c;
            pnrWrapper.equivPrice = pnrObj.Equiv_Price__c;
            pnrWrapper.equivPriceCurrency = pnrObj.Equiv_Price_Currency__c;
            pnrWrapper.totalTax = pnrObj.Total_Tax__c;
            pnrWrapper.totalTaxCurrency = pnrObj.Total_Tax_Currency__c;
            pnrWrapper.totalPrice = pnrObj.Total_Price__c;
            pnrWrapper.isManualSync = true;
            pnrWrapper.reasonForManualSync = 'Re-Issue';
            
            pnrWrapper.segments=SegmentsList;
            pnrWrapper.pnrAccountingLine=PNRAccountigLineList;
            
            
            String JsonbodyToBeSent =JSON.serialize(pnrWrapper);   
            system.debug('JsonbodyToBeSent----'+JsonbodyToBeSent);
            Http http = new Http();           
            HttpRequest request = new HttpRequest();
            String endPointUrl = System.Label.PnrMakeCallout_for_ManualSync;
            //	String endPointUrl = 'http://162.218.210.103:7071/psag/api/pnr/manualsync';
            system.debug('endPointUrl');
            request.setEndpoint(endPointUrl);            
            request.setMethod('POST');
            request.setHeader('Content-Type', 'application/json');
            if(System.Label.PnrIsServerless == 'True'){  
            request.setHeader('Authorization', 'Bearer '+accessToken);
            }              
            request.setHeader('Accept', 'application/json');
            request.setBody(JsonbodyToBeSent);
            system.debug('requestParameter----125->'+JsonbodyToBeSent);
            HttpResponse response = http.send(request);  
            system.debug('getStatusCode----125->'+response.getStatusCode());
            if(response.getStatusCode() == 200) {   
                system.debug('response----39->'+response.getBody());
                
            }else{
                
            }
        }
        }
        System.debug('PNRFreshedIDs155 ='+PNRFreshedIDs.size()); 
    }
    public void finish(Database.BatchableContext info){  
        DateTime dtCurrentTime = System.now().addminutes(2);       
        String sHour = '', sMinute='', sDayOfMonth='', sMonth='', sYear='';       
        sMinute = String.ValueOf(dtCurrentTime.minute());
        sHour = String.ValueOf(dtCurrentTime.hour());
        sDayOfMonth = String.ValueOf(dtCurrentTime.day());
        sMonth = String.ValueOf(dtCurrentTime.month());
        sYear = String.ValueOf(dtCurrentTime.year());   
        System.debug('FINISH ='+PNRFreshedIDs.size());       
        System.schedule('Schedule Batch Job that runs only once after 2 mins'+ System.now(), '0 '+sMinute+' '+sHour+' '+sDayOfMonth+' '+sMonth+' ?'+' '+sYear, new MP_BcPNRSchedulable(PNRFreshedIDs));
    }
    
    
    
    
}