force-app/main/default/objects/Deal_Transaction_Line__c/Deal_Transaction_Line__c.object-meta.xml
<CustomObject>
    <label>Deal Transaction Line</label>
    <nameField>
        <displayFormat>DTL-{000000}</displayFormat>
        <label>Deal Transaction Line Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Transaction Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Transaction_Line__c/fields/Deal_Transaction_Line__c.field-meta.xml
<CustomField>
    <fullName>Deal_Transaction_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal Transaction Line</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Deal_Transaction_Line__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Forward Contract</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Deal_Transaction_Line__c</referenceTo>
    <relationshipLabel>Deal Transaction Lines</relationshipLabel>
    <relationshipName>Deal_Transaction_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/departures_dates__c.object-meta.xml
<CustomObject>
    <label>departures dates</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>departures dates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DTTermsJunction__c/DTTermsJunction__c.object-meta.xml
<CustomObject>
    <label>DTTermsJunction</label>
    <nameField>
        <displayFormat>DTJ-{000000}</displayFormat>
        <label>DTTermsJunction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DTTermsJunctions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/order_line_POE__c/order_line_POE__c.object-meta.xml
<CustomObject>
    <label>Order Line</label>
    <nameField>
        <displayFormat>OL-{00000000}</displayFormat>
        <label>Order Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/order_line_POE__c/fields/departures_dates__c.field-meta.xml
<CustomField>
    <fullName>departures_dates__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>departures dates</label>
    <referenceTo>departures_dates__c</referenceTo>
    <relationshipLabel>Order Lines</relationshipLabel>
    <relationshipName>Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/createUpdateDTandDTLUtilityTest.cls
@isTest(SeeAllData=true)
public class createUpdateDTandDTLUtilityTest {
    
    @isTest
    public static void departuredateMinNotMet(){
        
        Set<String> recId = new Set<String>();
        Set<Id> recId1 = new Set<Id>();
        Map<id,departures_dates__c> depListMap = new Map<id,departures_dates__c>();
        List<departures_dates__c> depList = [Select id from departures_dates__c limit 1 ];
        depListMap.put(depList[0].id,depList[0]);
        
        Map<id,order_line_POE__c> olListMap = new Map<id,order_line_POE__c>();
        List<order_line_POE__c> olList = [Select id from order_line_POE__c limit 1 ];
        olListMap.put(olList[0].id,olList[0]);
        
        List<DTTermsJunction__c> dtTermList = [Select id from DTTermsJunction__c limit 1 ];
        
        List<Deal_Transaction_Line__c> dtlList = [Select id from Deal_Transaction_Line__c limit 1 ];
        
        createUpdateDTandDTLUtility.updateDTRecordsfromDepartureDate(depList,depListMap);
        createUpdateDTandDTLUtility.updateDTOrderLineJunctionRecords(olList,olListMap);
        createUpdateDTandDTLUtility.createDTRecordsAndDTOLs(recId1);
        createUpdateDTandDTLUtility.updateDtOlRecordsAsInvoiced(recId,recId);
        createUpdateDTandDTLUtility.createUpdateDTLRecordsNonInvoiced(dtTermList);
        createUpdateDTandDTLUtility.createDTLRecordsInvoicedAdjustment(dtTermList);
        createUpdateDTandDTLUtility.rollUpDTlFieldValues(dtlList);
        createUpdateDTandDTLUtility.updateDtlStatusField(dtlList);
        
    }
    
}