force-app/main/default/objects/order_line_item__c/order_line_item__c.object-meta.xml
<CustomObject>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>OLI-{000000}</displayFormat>
        <label>Order Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/order_line_item__c/fields/OLI_Status__c.field-meta.xml
<CustomField>
    <fullName>OLI_Status__c</fullName>
    <label>OLI Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On Hold</fullName>
                <default>true</default>
                <label>On Hold</label>
            </value>
            <value>
                <fullName>Secured</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/order_line_item__c/fields/ordexp_TAD_Order__c.field-meta.xml
<CustomField>
    <fullName>ordexp_TAD_Order__c</fullName>
    <label>Order</label>
    <referenceTo>TAD_Order__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items_orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/order_line_item__c/fields/Source_OLI__c.field-meta.xml
<CustomField>
    <fullName>Source_OLI__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Source OLI</label>
    <referenceTo>order_line_item__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/order_line_item__c/fields/Sub_Options__c.field-meta.xml
<CustomField>
    <fullName>Sub_Options__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Note :-  For Stay type Orders, change to Sub-Option will be applied to all the OLIs of this Order</inlineHelpText>
    <label>Sub Options</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>sub_options__c.options__c</field>
            <operation>equals</operation>
            <valueField>$Source.ordexp_Options__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>sub_options__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sub_options__c/sub_options__c.object-meta.xml
<CustomObject>
    <label>Sub Options</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TAD_Order__c/TAD_Order__c.object-meta.xml
<CustomObject>
    <label>TAD Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TAD Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TAD_Order__c/fields/Suboption_Text__c.field-meta.xml
<CustomField>
    <fullName>Suboption_Text__c</fullName>
    <label>Suboption Text</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/tad_SuboptionNameAndCount.cls
public class tad_SuboptionNameAndCount{


public static void GetSuboptionAndCount(list<order_line_item__c> oliList){
    system.debug('oliList '+oliList);
	Set<Id> ordIdsSet = new Set<Id>();
	Set<string> subOptionIdsSet = new Set<string>();
	Set<Id> oliIdsSet = new Set<Id>();
	Map<string,list<Order_Line_Item__c>> subOptionMap = new Map<string,list<order_line_item__c>>();

	for(order_line_item__c objOLi:oliList){
                ordIdsSet.add(objOLi.ordexp_TAD_Order__c);
				subOptionIdsSet.add(objOLi.Sub_Options__c);
		}//for loop close
	
    if(!subOptionIdsSet.isEmpty()){
        system.debug('subOptionIdsSet '+subOptionIdsSet);
        List<Sub_Options__c> subOptionList = [select id,name,(select id,name,ordexp_TAD_Order__c from Order_Line_Items__r WHERE (OLI_Status__c='Secured' OR OLI_Status__c='Active' OR OLI_Status__c='On Hold')) from Sub_Options__c WHERE Id IN:subOptionIdsSet];
        list<order_line_item__c> oliListWithTadOrder = new List<order_line_item__c>();
        system.debug('subOptionList '+subOptionList);
        for(Sub_Options__c subOpt:subOptionList){
            system.debug('subOpt.Id '+subOpt.Id);
            system.debug('subOpt.Order_Line_Items__r '+subOpt.Order_Line_Items__r);
            subOptionMap.put(subOpt.Id,subOpt.Order_Line_Items__r);
        	}
    	}
    if(!ordIdsSet.isEmpty()){
        List<TAD_Order__c> fetchTadOrder = [SELECT Id,Name,Suboption_Text__c,(SELECT Id,Name,ordexp_TAD_Order__c,Sub_Options__r.Name,Sub_Options__c FROM Order_Line_Items_orders__r) FROM TAD_Order__c WHERE Id IN:ordIdsSet];
        system.debug('fetchTadOrder ' +fetchTadOrder);
        if(!fetchTadOrder.isEmpty()){
            list<order_line_item__c> oliListWithTadOrder = new List<order_line_item__c>();
            
            for(TAD_Order__c ord:fetchTadOrder){
                set<string> strSet = new set<string>();
                oliListWithTadOrder = ord.Order_Line_Items_orders__r;
                if(!oliListWithTadOrder.isEmpty()){
                    for(order_line_item__c oli:oliListWithTadOrder){
                        //system.debug('subOptionMap '+subOptionMap);
                        
                        string subCount;
                        if(oli.ordexp_TAD_Order__c==ord.Id){
                            //subCount = oli.Sub_Options__r.Name+'='+subOptionMap.get(oli.Sub_Options__c).size();
                        }
                        strSet.add(oli.Sub_Options__r.Name);
                    }
                }
    		  List <String> strList = new List <String>(strSet);
              ord.Suboption_Text__c = String.join(strList, ' | ' );
            }
            update fetchTadOrder;
        }
    }
  }
    
    public static void GetSuboptionOLIUpdate(list<order_line_item__c> oliList,Map<Id,order_line_item__c> oliOldMap){
        
        system.debug('oliList '+oliList);
        system.debug('oliList '+oliOldMap);
		Set<Id> ordIdsSet = new Set<Id>();
		Set<string> subOptionIdsSet = new Set<string>();
		Set<Id> oliIdsSet = new Set<Id>();
        Map<string,list<Order_Line_Item__c>> subOptionMap = new Map<string,list<order_line_item__c>>();
        
        for(order_line_item__c objOLi:oliList){
            order_line_item__c oldOli = oliOldMap.get(objOLi.Id);
            system.debug('oldOli '+oldOli);
            if((objOLi.OLI_Status__c!=oldOli.OLI_Status__c) || (objOLi.Sub_Options__c!=oldOli.Sub_Options__c)){
                ordIdsSet.add(objOLi.ordexp_TAD_Order__c);
				subOptionIdsSet.add(objOLi.Sub_Options__c);
            }
        }
        if(!subOptionIdsSet.isEmpty()){
        system.debug('subOptionIdsSet '+subOptionIdsSet);
        List<Sub_Options__c> subOptionList = [select id,name,(select id,name,ordexp_TAD_Order__c from Order_Line_Items__r WHERE (OLI_Status__c='Secured' OR OLI_Status__c='Active' OR OLI_Status__c='On Hold')) from Sub_Options__c WHERE Id IN:subOptionIdsSet];
        list<order_line_item__c> oliListWithTadOrder = new List<order_line_item__c>();
        system.debug('subOptionList '+subOptionList);
        
         for(Sub_Options__c subOpt:subOptionList){
            system.debug('subOpt.Id '+subOpt.Id);
            system.debug('subOpt.Order_Line_Items__r '+subOpt.Order_Line_Items__r);
            subOptionMap.put(subOpt.Id,subOpt.Order_Line_Items__r);
        	}
    	}
        if(!ordIdsSet.isEmpty()){
        List<TAD_Order__c> fetchTadOrder = [SELECT Id,Name,Suboption_Text__c,(SELECT Id,Name,ordexp_TAD_Order__c,Sub_Options__r.Name,Sub_Options__c FROM Order_Line_Items_orders__r WHERE (OLI_Status__c='Secured' OR OLI_Status__c='Active'  OR OLI_Status__c='On Hold')) FROM TAD_Order__c WHERE Id IN:ordIdsSet];
        system.debug('fetchTadOrder ' +fetchTadOrder);
        if(!fetchTadOrder.isEmpty()){
            list<order_line_item__c> oliListWithTadOrder = new List<order_line_item__c>();
            
            for(TAD_Order__c ord:fetchTadOrder){
                set<string> strSet = new set<string>();
                oliListWithTadOrder = ord.Order_Line_Items_orders__r;
                if(!oliListWithTadOrder.isEmpty()){
                    for(order_line_item__c oli:oliListWithTadOrder){
                        //system.debug('subOptionMap '+subOptionMap);
                        
                        string subCount;
                        if(oli.ordexp_TAD_Order__c==ord.Id){
                            //subCount = oli.Sub_Options__r.Name+'='+subOptionMap.get(oli.Sub_Options__c).size();
                        }
                        strSet.add(oli.Sub_Options__r.Name);
                    }
                }
    		  List <String> strList = new List <String>(strSet);
              ord.Suboption_Text__c = String.join(strList, ' | ' );
            }
            update fetchTadOrder;
        }
    }
    }
}