force-app/main/default/objects/order_line_item__c/order_line_item__c.object-meta.xml
<CustomObject>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>OLI-{000000}</displayFormat>
        <label>Order Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/order_line_item__c/fields/OLI_Status__c.field-meta.xml
<CustomField>
    <fullName>OLI_Status__c</fullName>
    <label>OLI Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On Hold</fullName>
                <default>true</default>
                <label>On Hold</label>
            </value>
            <value>
                <fullName>Secured</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/order_line_POE__c/order_line_POE__c.object-meta.xml
<CustomObject>
    <label>Order Line</label>
    <nameField>
        <displayFormat>OL-{00000000}</displayFormat>
        <label>Order Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/order_line_POE__c/fields/mp_Merchant_Acknowledgement_Status__c.field-meta.xml
<CustomField>
    <fullName>mp_Merchant_Acknowledgement_Status__c</fullName>
    <label>BC Acknowledgement Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Acknowledged</fullName>
            </value>
            <value>
                <fullName>Acknowledged</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/order_line_POE__c/fields/Order_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Order_Line_Item__c</fullName>
    <label>Order Line Item</label>
    <referenceTo>order_line_item__c</referenceTo>
    <relationshipLabel>Order Lines</relationshipLabel>
    <relationshipName>Order_Lines_POE</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/order_line_POE__c/fields/TAD_Order__c.field-meta.xml
<CustomField>
    <fullName>TAD_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TAD Order</label>
    <referenceTo>TAD_Order__c</referenceTo>
    <relationshipLabel>Order Lines</relationshipLabel>
    <relationshipName>Order_Lines_POE</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/TAD_Order__c.object-meta.xml
<CustomObject>
    <label>TAD Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TAD Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TAD_Order__c/fields/Order_Acknowledgement__c.field-meta.xml
<CustomField>
    <fullName>Order_Acknowledgement__c</fullName>
    <label>Order Acknowledgement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Non Acknowledged</fullName>
                <default>true</default>
                <label>Non Acknowledged</label>
            </value>
            <value>
                <fullName>Acknowledged</fullName>
            </value>
            <value>
                <fullName>Not Acknowledged</fullName>
                <isActive>false</isActive>
                <label>Not Acknowledged</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TAD_Order__c/recordTypes/TAD.recordType-meta.xml
<RecordType>
    <fullName>TAD</fullName>
    <active>true</active>
    <label>TAD</label>
</RecordType>

force-app/main/default/classes/acknowledgeStatusHandler.cls
public class acknowledgeStatusHandler {
    
    public static void updateAcknStatusonOrder(List<order_line_POE__c> newlist,String type,map<id,order_line_POE__c> oldmap)
    {
        set<id> ordId=new set<id>();
        for(order_line_POE__c olp:newlist){
            if(type=='Insert' || type=='Delete'){
                ordId.add(olp.TAD_Order__c);
            }
            else{
                if(olp.mp_Merchant_Acknowledgement_Status__c!=oldmap.get(olp.id).mp_Merchant_Acknowledgement_Status__c){
                    ordId.add(olp.TAD_Order__c);
                }
            }
        }
        list<TAD_Order__c> tadOrders=[Select id,Order_Acknowledgement__c,(Select id,mp_Merchant_Acknowledgement_Status__c from Order_Lines_POE__r where Order_Line_Item__r.OLI_Status__c!='Cancelled') from TAD_Order__c where id in:ordId];
        List<TAD_Order__c> tadToUpdate = new List<TAD_Order__c>();
        if(!tadOrders.isEmpty()){
            for(TAD_Order__c td:tadOrders)
            {
                Boolean ack=true;
                // if(td.Order_Lines_POE__r.size()==0 && td.Order_Acknowledgement__c!=''){
                //     td.Order_Acknowledgement__c='';
                // }
                for(order_line_POE__c ol:td.Order_Lines_POE__r){
                    if(ol.mp_Merchant_Acknowledgement_Status__c!='Acknowledged')
                    {
                        ack=false;
                        break;
                    }
                }
                
                TAD_Order__c tad = new TAD_Order__c();
                if(ack==true){
                    if(td.Order_Acknowledgement__c!='Acknowledged' ){
                        td.Order_Acknowledgement__c='Acknowledged';
                        tadToUpdate.add(td);
                    }
                }
                else{
                    if(td.Order_Acknowledgement__c=='Acknowledged' ){
                        td.Order_Acknowledgement__c='Non Acknowledged';
                        tadToUpdate.add(td);
                    }
                }
                
            }
            if(!tadToUpdate.isEmpty()){
                update tadToUpdate;   
            }
        }
    }
}