force-app/main/default/objects/Marketing_Spend__c/Marketing_Spend__c.object-meta.xml
<CustomObject>
    <label>Marketing Spend</label>
    <nameField>
        <displayFormat>MA-{000000}</displayFormat>
        <label>Marketing Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Marketing Spend</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketing_Spend__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Marketing_Spend__c/fields/Booking_ID__c.field-meta.xml
<CustomField>
    <fullName>Booking_ID__c</fullName>
    <label>Booking ID - (Print only)</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketing_Spend__c/fields/Deal_ID__c.field-meta.xml
<CustomField>
    <fullName>Deal_ID__c</fullName>
    <formula>Deal__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Deal ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketing_Spend__c/fields/Due_Time__c.field-meta.xml
<CustomField>
    <fullName>Due_Time__c</fullName>
    <label>Due Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Marketing_Spend__c/fields/Inventory_Title__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Title__c</fullName>
    <formula>TEXT(ms_Marketing_inventory__r.ms_Title__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Inventory Title</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketing_Spend__c/fields/ms_Channel_Name__c.field-meta.xml
<CustomField>
    <fullName>ms_Channel_Name__c</fullName>
    <formula>TEXT(ms_Marketing_inventory__r.ms_Channel__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Channel Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketing_Spend__c/fields/ms_Cost__c.field-meta.xml
<CustomField>
    <fullName>ms_Cost__c</fullName>
    <formula>ms_Marketing_inventory__r.ms_Cost__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Marketing_Spend__c/fields/ms_Deal_Title__c.field-meta.xml
<CustomField>
    <fullName>ms_Deal_Title__c</fullName>
    <formula>Deal__r.title__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Deal Title</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketing_Spend__c/fields/ms_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>ms_Due_Date__c</fullName>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Marketing_Spend__c/fields/ms_Geo_c__c.field-meta.xml
<CustomField>
    <fullName>ms_Geo_c__c</fullName>
    <formula>TEXT(ms_Marketing_inventory__r.ms_Geo__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ms_Geo__c</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketing_Spend__c/fields/ms_Placement__c.field-meta.xml
<CustomField>
    <fullName>ms_Placement__c</fullName>
    <formula>TEXT(ms_Marketing_inventory__r.ms_Placement__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Placement</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketing_Spend__c/fields/ms_Spend__c.field-meta.xml
<CustomField>
    <fullName>ms_Spend__c</fullName>
    <formula>ms_Marketing_inventory__r.ms_Spend__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Spend</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Marketing_Spend__c/fields/ms_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>ms_Start_Time__c</fullName>
    <formula>ms_Marketing_inventory__r.ms_Start_Time__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ms_Start_Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Marketing_Spend__c/fields/ms_Status__c.field-meta.xml
<CustomField>
    <fullName>ms_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Waiting on someone else</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Available</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Marketing_Spend__c/fields/ms_Supplier_Name__c.field-meta.xml
<CustomField>
    <fullName>ms_Supplier_Name__c</fullName>
    <formula>TEXT(ms_Marketing_inventory__r.ms_Supplier__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Supplier Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketing_Spend__c/fields/Sub_status__c.field-meta.xml
<CustomField>
    <fullName>Sub_status__c</fullName>
    <label>Sub-status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not started</fullName>
                <default>true</default>
                <label>Not started</label>
            </value>
            <value>
                <fullName>Template in Progress</fullName>
            </value>
            <value>
                <fullName>Template Completed</fullName>
            </value>
            <value>
                <fullName>Test sent</fullName>
            </value>
            <value>
                <fullName>Pending Publishing Approval</fullName>
            </value>
            <value>
                <fullName>Rejected Publishing Approval</fullName>
            </value>
            <value>
                <fullName>Pending Product Approval</fullName>
            </value>
            <value>
                <fullName>Rejected Product Approval</fullName>
            </value>
            <value>
                <fullName>Finalized ready for Scheduling</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Deal Pulled Waiting for New Selection</fullName>
            </value>
            <value>
                <fullName>Brief in progress</fullName>
            </value>
            <value>
                <fullName>Brief ready for IKTP Submission</fullName>
            </value>
            <value>
                <fullName>Brief submitted to IKTP</fullName>
            </value>
            <value>
                <fullName>Finalised -Submitted to IKTP</fullName>
            </value>
            <value>
                <fullName>Ad Delivered</fullName>
            </value>
            <value>
                <fullName>Content Scheduled</fullName>
            </value>
            <value>
                <fullName>Hero Template chosen</fullName>
            </value>
            <value>
                <fullName>Final template in progress</fullName>
            </value>
            <value>
                <fullName>Finalised Ready for delivery</fullName>
            </value>
            <value>
                <fullName>Draft post in progress</fullName>
            </value>
            <value>
                <fullName>Draft post completed</fullName>
            </value>
            <value>
                <fullName>Brief sent to Thumpe Media</fullName>
            </value>
            <value>
                <fullName>Script received from Thumpe Media</fullName>
            </value>
            <value>
                <fullName>Finalised ready for submission to Thumpe media</fullName>
            </value>
            <value>
                <fullName>Confirm Approval with Thumpe media</fullName>
            </value>
            <value>
                <fullName>Finalised ready for ad creation</fullName>
            </value>
            <value>
                <fullName>Ad scheduled</fullName>
            </value>
            <value>
                <fullName>Finalised ready for Completion</fullName>
            </value>
            <value>
                <fullName>Banner set live</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Marketing_Spend_Child__c/Marketing_Spend_Child__c.object-meta.xml
<CustomObject>
    <label>Marketing Spend Child</label>
    <nameField>
        <displayFormat>Marketing ActivityC-{000000}</displayFormat>
        <label>Marketing Spend Child Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Marketing Spend Dates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketing_Spend_Child__c/fields/Deal_ID__c.field-meta.xml
<CustomField>
    <fullName>Deal_ID__c</fullName>
    <formula>ms_Marketing_Spend__r.Deal__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Deal ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketing_Spend_Child__c/fields/ms_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>ms_Approval_Status__c</fullName>
    <formula>TEXT(ms_Marketing_Spend__r.Approval_Status__c)</formula>
    <label>Approval Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketing_Spend_Child__c/fields/ms_Deal_Title__c.field-meta.xml
<CustomField>
    <fullName>ms_Deal_Title__c</fullName>
    <formula>ms_Marketing_Spend__r.ms_Deal_Title__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Deal Title</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketing_Spend_Child__c/fields/ms_Geo_c__c.field-meta.xml
<CustomField>
    <fullName>ms_Geo_c__c</fullName>
    <formula>TEXT( ms_Marketing_Spend__r.ms_Marketing_inventory__r.ms_Geo__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Geo</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketing_Spend_Child__c/fields/ms_Placement__c.field-meta.xml
<CustomField>
    <fullName>ms_Placement__c</fullName>
    <formula>TEXT(ms_Marketing_Spend__r.ms_Marketing_inventory__r.ms_Placement__c)</formula>
    <label>Placement</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketing_Spend_Child__c/fields/ms_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>ms_Start_Time__c</fullName>
    <formula>ms_Marketing_Spend__r.ms_Marketing_inventory__r.ms_TimeText__c</formula>
    <label>Start Time</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketing_Spend_Child__c/fields/ms_Status__c.field-meta.xml
<CustomField>
    <fullName>ms_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Waiting on someone else</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Available</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Marketing_Spend_Child__c/fields/Sub_status__c.field-meta.xml
<CustomField>
    <fullName>Sub_status__c</fullName>
    <formula>Text(ms_Marketing_Spend__r.Sub_status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sub Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ms_HoverCalendarView.cls
public class ms_HoverCalendarView {

    
     public class wrapperofActivity{
        @AuraEnabled public string MarketingActivityName{get;set;}
        @AuraEnabled public String ChannelName{get;set;}
        @AuraEnabled public String SupplierName{get;set;}
        @AuraEnabled public String DealID{get;set;}
        @AuraEnabled public String DealTitle{get;set;}
         @AuraEnabled public String Geo{get;set;}
         @AuraEnabled public String Placement{get;set;}
         @AuraEnabled public String ApprovalStatus{get;set;}
         @AuraEnabled public String BookingID{get;set;}
         @AuraEnabled public String DueDate{get;set;}
         @AuraEnabled public String DueTime{get;set;}
         @AuraEnabled public String Spend{get;set;}
         @AuraEnabled public String Cost{get;set;}
         @AuraEnabled public String InventoryTitle{get;set;}
         @AuraEnabled public String SubStatus{get;set;}
         @AuraEnabled public String starttime{get;set;}
        @AuraEnabled public String Status{get;set;}
         @AuraEnabled public String Activityid{get;set;}
         
         
         
    }

    
    
     @AuraEnabled
    public static list<wrapperofActivity> fetchActivityDetailsParent(String ActivityId){
        Marketing_Spend__c parentdetail = [Select id, ms_Channel_Name__c,ms_Supplier_Name__c,ms_Start_Time__c,Deal_ID__c,ms_Deal_Title__c,
                                                 ms_Geo_c__c,ms_Placement__c,ms_Status__c,Approval_Status__c,Booking_ID__c,ms_Due_Date__c,Due_Time__c,
                                                 ms_Spend__c,ms_Cost__c,Inventory_Title__c,Sub_status__c from Marketing_Spend__c where id=:ActivityId];
        wrapperofActivity parentWrapper = new wrapperofActivity();
        parentWrapper.ChannelName = parentdetail.ms_Channel_Name__c;
        parentWrapper.SupplierName = parentdetail.ms_Supplier_Name__c;
        parentWrapper.DealID = parentdetail.Deal_ID__c;
        parentWrapper.DealTitle = parentdetail.ms_Deal_Title__c;
        parentWrapper.Geo = parentdetail.ms_Geo_c__c;
        parentWrapper.Placement = parentdetail.ms_Placement__c;
        parentWrapper.ApprovalStatus = parentdetail.Approval_Status__c;
        parentWrapper.BookingID = parentdetail.Booking_ID__c;
        parentWrapper.DueDate = String.valueOf(parentdetail.ms_Due_Date__c);
        parentWrapper.DueTime = String.valueOf(parentdetail.Due_Time__c);
        parentWrapper.Spend = String.valueOf(parentdetail.ms_Spend__c);
        parentWrapper.Cost = String.valueOf(parentdetail.ms_Cost__c);
        parentWrapper.InventoryTitle = parentdetail.Inventory_Title__c;
        parentWrapper.SubStatus = parentdetail.Sub_status__c;
        parentWrapper.starttime = String.valueOf(parentdetail.ms_Start_Time__c);
        parentWrapper.Status = parentdetail.ms_Status__c;
        parentWrapper.Activityid = parentdetail.id;
        list<wrapperofActivity> parentWrapperList = new list<wrapperofActivity>();
        parentWrapperList.add(parentWrapper);
        return parentWrapperList;
       
        
    }
     @AuraEnabled
    public static List<wrapperofActivity>fetchActivityDetailsChild(String ActivityId){
        list<Marketing_Spend_Child__c> mscObj = [select Id, ms_Approval_Status__c,  ms_Status__c,Sub_status__c from Marketing_Spend_Child__c where id=: ActivityId];

        list<wrapperofActivity> childactivity = new list<wrapperofActivity>();
    for(Marketing_Spend_Child__c msc:mscObj)
    {
        wrapperofActivity chobj = new wrapperofActivity();
         chobj.ApprovalStatus = msc.ms_Approval_Status__c;
      // childactivity.SubStatus = msc.Sub_status__c;
       chobj.SubStatus = msc.Sub_status__c;
       chobj.Status = msc.ms_Status__c;
         chobj.Activityid = msc.id;
       childactivity.add(chobj);
    }
        return childactivity;
    }
    
    
    
    
    
    public class picklistValues{
        @AuraEnabled  public String label {get;set;}
        @AuraEnabled  public String value {get;set;}
    }

 @AuraEnabled
    public static List<picklistValues> getPicklistvalues(String objectName, String field_apiname){
       
        Map<String,Schema.SObjectType> gd = Schema.getGlobalDescribe();
        Map<String, Schema.SObjectField> field_map = gd.get(objectName.toLowerCase()).getDescribe().fields.getMap();
       
        List<Schema.PicklistEntry> picklistValues = field_map.get(field_apiname).getDescribe().getPickListValues();
       
    List<picklistValues> ddPickList = new List<picklistValues>();
        for (Schema.PicklistEntry pv : picklistValues) {
        picklistValues pv1 = new picklistValues();
        pv1.label=pv.getLabel();
        pv1.value=pv.getValue();
        ddPickList.add(pv1);
        }
       
        return ddPickList;
       
    }
    
    @AuraEnabled
    public static void saveActivityStatus(List<wrapperofActivity> parentdatalist, List<wrapperofActivity> childdatalist){
        system.debug('parentList'+parentdatalist);
        system.debug('childList'+childdatalist);
        if(parentdatalist !=null){
            List<Marketing_Spend__c> mslist = new List<Marketing_Spend__c>();
            for(wrapperofActivity pdl : parentdatalist){
                Marketing_Spend__c msobj = new Marketing_Spend__c();
                msobj.Approval_Status__c = pdl.ApprovalStatus;
                msobj.Sub_status__c = pdl.SubStatus;
                msobj.ms_Status__c = pdl.Status;
                if(!Test.isRunningTest()){
            
                msobj.Id = pdl.Activityid;
                }
                mslist.add(msobj);
            }
            if(!Test.isRunningTest()){
            update mslist;
            }
        }
        if(childdatalist !=null){
            List<Marketing_Spend_Child__c> msclist = new List<Marketing_Spend_Child__c>();
            for(wrapperofActivity pdl : childdatalist){
                Marketing_Spend_Child__c mschobj = new Marketing_Spend_Child__c();
                mschobj.ms_Status__c = pdl.Status;
                if(!Test.isRunningTest()){
            
                mschobj.Id = pdl.Activityid;
                }
                msclist.add(mschobj);
            }
            if(!Test.isRunningTest()){
            update msclist;
            }
        }
    }
    
    
}