force-app/main/default/objects/Siteminder_Room_Reservation_Send_ID__e/Siteminder_Room_Reservation_Send_ID__e.object-meta.xml
<CustomObject>
    <label>Siteminder Room Reservation Send ID</label>
    <pluralLabel>Siteminder Room Reservation Send ID</pluralLabel>
</CustomObject>

force-app/main/default/objects/Siteminder_Room_Reservation_Send_ID__e/fields/Tad_Order_Id__c.field-meta.xml
<CustomField>
    <fullName>Tad_Order_Id__c</fullName>
    <label>Tad Order Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/makeCalloutToSMResMicroServiceConTest.cls
@isTest
public class makeCalloutToSMResMicroServiceConTest {
    
    private class Mock implements HttpCalloutMock {
        
        public HttpResponse respond(HttpRequest req) {
            HttpResponse res = new HttpResponse();
            res.setBody('{"responseCode":200,"responseMessage":"Success!!"}');
            res.setStatusCode(200);
            return res;
        } 
    } 
    
    
    @isTest
    public static void testMethod1() {
        
        // Create a test event instance
        Siteminder_Room_Reservation_Send_ID__e smEvent = new Siteminder_Room_Reservation_Send_ID__e(Tad_Order_Id__c='1234555654');
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new Mock());
        // Publish test event
        Database.SaveResult sr = EventBus.publish(smEvent);
        
        Test.stopTest();
        
    }
}