force-app/main/default/objects/RBA_Exchange_Rate__c/RBA_Exchange_Rate__c.object-meta.xml
<CustomObject>
    <description>Exchange Rates modified Daily from RBA Data</description>
    <label>RBA Exchange Rate</label>
    <nameField>
        <label>RBA Exchange Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RBA Exchange Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RBA_Exchange_Rate__c/fields/currency_code__c.field-meta.xml
<CustomField>
    <fullName>currency_code__c</fullName>
    <label>Currency To</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>CAD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>JPY</fullName>
            </value>
            <value>
                <fullName>CNY</fullName>
            </value>
            <value>
                <fullName>IDR</fullName>
            </value>
            <value>
                <fullName>NZD</fullName>
            </value>
            <value>
                <fullName>THB</fullName>
            </value>
            <value>
                <fullName>TWD</fullName>
            </value>
            <value>
                <fullName>WST</fullName>
            </value>
            <value>
                <fullName>ZAR</fullName>
            </value>
            <value>
                <fullName>VND</fullName>
            </value>
            <value>
                <fullName>FJD</fullName>
            </value>
            <value>
                <fullName>MYR</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
            <value>
                <fullName>CHF</fullName>
            </value>
            <value>
                <fullName>INR</fullName>
            </value>
            <value>
                <fullName>NOK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RBA_Exchange_Rate__c/fields/exchange_rate__c.field-meta.xml
<CustomField>
    <fullName>exchange_rate__c</fullName>
    <label>Exchange Rate AUD</label>
    <precision>15</precision>
    <scale>9</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RBA_Exchange_Rate__c/fields/Exchange_Rate_NZD__c.field-meta.xml
<CustomField>
    <fullName>Exchange_Rate_NZD__c</fullName>
    <label>Exchange Rate NZD</label>
    <precision>15</precision>
    <scale>9</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RBA_Exchange_Rate__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/BatchToPopulateRBARatesFromFF.cls
global class BatchToPopulateRBARatesFromFF implements Database.Batchable<sObject>{
    
    global Database.QueryLocator start(Database.BatchableContext bc){
        //CreatedDate = YESTERDAY in query needs to go below.
        return Database.getQueryLocator([Select id, Name, fferpcore__Rate__c, fferpcore__RateCurrency__c, fferpcore__RateType__c, fferpcore__RelativeCurrency__c, CreatedDate  from fferpcore__ExchangeRateHistory__c where fferpcore__RateType__c = 'Spot' AND(fferpcore__RelativeCurrency__c ='AUD' OR fferpcore__RelativeCurrency__c = 'NZD') AND CreatedDate = TODAY]);
        
    }
    
    global void execute(Database.BatchableContext bc,List<fferpcore__ExchangeRateHistory__c> scope){
        
        List<RBA_Exchange_Rate__c> listOfRBAExchangeRateRecordsToInsert = new List<RBA_Exchange_Rate__c> ();
        
        Set<String> exchangeRateCurrencies = new Set<String>();
        Date todayDate = system.today();
        
        Set<String> uniqueIds = new Set<String>();
        
        Schema.DescribeFieldResult fieldResult = RBA_Exchange_Rate__c.Currency_Code__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for( Schema.PicklistEntry f : ple){
            exchangeRateCurrencies.add(f.getValue());
        }
        
        
        for(fferpcore__ExchangeRateHistory__c exchangeHistoryInstance : scope){
            if(exchangeRateCurrencies.contains(exchangeHistoryInstance.fferpcore__RateCurrency__c)){
                Date instCreatedDate = exchangeHistoryInstance.CreatedDate.date();
                String uniqueId = exchangeHistoryInstance.fferpcore__RelativeCurrency__c + exchangeHistoryInstance.fferpcore__RateCurrency__c;
                if(todayDate.isSameDay(instCreatedDate) && (!uniqueIds.contains(uniqueId))){
                    RBA_Exchange_Rate__c rbaInstance = new RBA_Exchange_Rate__c();          
                    rbaInstance.Name =  uniqueId;
                    rbaInstance.External_Id__c = uniqueId;
                    uniqueIds.add(uniqueId);
                    rbaInstance.currency_code__c = exchangeHistoryInstance.fferpcore__RateCurrency__c;
                    if(exchangeHistoryInstance.fferpcore__RelativeCurrency__c == 'AUD'){
                        rbaInstance.exchange_rate__c = exchangeHistoryInstance.fferpcore__Rate__c;
                    }else{
                        rbaInstance.Exchange_Rate_NZD__c = exchangeHistoryInstance.fferpcore__Rate__c;
                    }  
                    listOfRBAExchangeRateRecordsToInsert.add(rbaInstance);
                }
            }
        }
        
        if(!listOfRBAExchangeRateRecordsToInsert.isEmpty()){
            upsert listOfRBAExchangeRateRecordsToInsert External_Id__c;
        }
    } 
    
    global void finish(Database.BatchableContext BC) {
        
    }
    
}