force-app/main/default/objects/Accommodation__c/Accommodation__c.object-meta.xml
<CustomObject>
    <label>Accommodation</label>
    <nameField>
        <label>Accommodation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accommodation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Component__c/Component__c.object-meta.xml
<CustomObject>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Component__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Components</relationshipLabel>
    <relationshipName>Components</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Component__c/fields/Merchant_Name__c.field-meta.xml
<CustomField>
    <fullName>Merchant_Name__c</fullName>
    <label>Merchant Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Components</relationshipLabel>
    <relationshipName>Components</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Day__c/Day__c.object-meta.xml
<CustomObject>
    <label>Day</label>
    <nameField>
        <displayFormat>D{000000000}</displayFormat>
        <label>Day Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Days</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Day__c/fields/accommodation__c.field-meta.xml
<CustomField>
    <fullName>accommodation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Accommodation</label>
    <referenceTo>Accommodation__c</referenceTo>
    <relationshipLabel>Days</relationshipLabel>
    <relationshipName>Days</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Day__c/fields/departures_dates__c.field-meta.xml
<CustomField>
    <fullName>departures_dates__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>departures dates</label>
    <referenceTo>departures_dates__c</referenceTo>
    <relationshipLabel>Days</relationshipLabel>
    <relationshipName>Days</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal__c/Deal__c.object-meta.xml
<CustomObject>
    <label>Deal</label>
    <nameField>
        <label>Deal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal__c/fields/Cloned_From__c.field-meta.xml
<CustomField>
    <fullName>Cloned_From__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cloned From</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Deal</relationshipLabel>
    <relationshipName>Deal</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal__c/fields/Merchant__c.field-meta.xml
<CustomField>
    <fullName>Merchant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Merchant</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Product Partner, General Expense Vendors</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Deal</relationshipLabel>
    <relationshipName>Deal</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/departures_dates__c.object-meta.xml
<CustomObject>
    <label>departures dates</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>departures dates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/departures_dates__c/fields/date__c.field-meta.xml
<CustomField>
    <fullName>date__c</fullName>
    <label>date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/Day__c.field-meta.xml
<CustomField>
    <fullName>Day__c</fullName>
    <formula>CASE( MOD( date__c - DATE(1900, 1, 7), 7), 0, &quot;Sunday&quot;, 1, &quot;Monday&quot;, 2, &quot;Tuesday&quot;, 3,
&quot;Wednesday&quot;, 4, &quot;Thursday&quot;, 5, &quot;Friday&quot;, 6, &quot;Saturday&quot;,&quot;Error&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Day</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>departures dates</relationshipLabel>
    <relationshipName>departures_dates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DayTriggerHandler.cls
/**
* ────────────────────────────────────────────────────────────────────────────────────────────────
* DayTriggerHandler-
* Purpose: Handler class for  DayTrigger
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* @author         Vinti C   <vinti.chittora@psagtechnologies.com>
* @lastModifiedBy Vinti C   <vinti.chittora@psagtechnologies.com>
* @maintainedBy   Vinti C   <vinti.chittora@psagtechnologies.com>
* @version        1.0
* @created        2020-01-30 
* @systemLayer    Apex Class
* ────────────────────────────────────────────────────────────────────────────────────────────────── */

public class DayTriggerHandler {
    
    public static void SendEmailOnAccomAssign(List<Day__c> newDayList){
        
        system.debug('Trigger.new-->'+newDayList);
        
        set<Id> DepIds = new set<Id>();
        set<Id> DealIds = new set<Id>();
        List<String> emailList = new List<String>();
        Map<String, String> param2Emailtemplate = new Map<String, string>(); 
       
        Boolean AccomFail = false;
        
        for(Day__c d: newDayList){ 
            
            if(d.departures_dates__c!=null ){
                
                DepIds.add(d.departures_dates__c);
                
            }
        }
        
        List <day__c> days =[Select Id,Name,accommodation__c,departures_dates__c from Day__c where departures_dates__c IN:DepIds];
        
        system.debug('days under departure date-->'+days);
        Map<Id,List<day__c>> MapOfDateIdVsDays = new  Map<Id,List<day__c>>();
        for(day__c da :days ){
            if(!MapOfDateIdVsDays.containskey(da.departures_dates__c)){
                MapOfDateIdVsDays.put(da.departures_dates__c, new List<day__c>{da} );
                system.debug('Map dep date vs list of days-->'+MapOfDateIdVsDays);
            }else{
                List<day__c> daysList = MapOfDateIdVsDays.get(da.departures_dates__c);
                daysList.add(da);
                MapOfDateIdVsDays.put(da.departures_dates__c, daysList );
                
                   
            }
            
            
            
        }
        Set<Id> deptIdForAccomodate = new  Set<Id> ();
        for(Id dateId :  MapOfDateIdVsDays.keySet()){
            Integer daysSize =  MapOfDateIdVsDays.get(dateId).size();
            Integer accDate = 0;
            for(day__c da :MapOfDateIdVsDays.get(dateId)){
                if(da.accommodation__c != null){
                    accDate = accDate+ 1;
                }
            }
            if(daysSize == accDate ){
                AccomFail = false;
                deptIdForAccomodate.add(dateId);
                
            }
        }
       
         if(deptIdForAccomodate != null){
             
             List<departures_dates__c> ddList = [Select Id, date__c, Deal__c,Deal__r.Name,  Name  from departures_dates__c where Id IN : deptIdForAccomodate];
            
              for(departures_dates__c dd:ddList ){
            
             if(dd.Deal__c!=null){
            
            DealIds.add(dd.Deal__c);
                 
        }
      
        }           

        
        if(DealIds != null){
            
             for(Component__c comp : [Select Id, Merchant_Name__c, Merchant_Name__r.Name, Merchant_Name__r.Company_Email__c, Deal__c  from Component__c where Deal__c =:DealIds]){
       
            if(comp.Merchant_Name__r.Company_Email__c != null){
                
                emailList.add(comp.Merchant_Name__r.Company_Email__c);
                
                 
            }
       
            }
       	 
        
          EmailTemplate emailTemp = [Select Id, Name,DeveloperName, Subject, Body, HtmlValue from EmailTemplate where DeveloperName = 'Accomodation_Assign_Notification' ];
        	
            for(departures_dates__c d :ddList){
                
                 String sub = emailTemp.Subject.Replace('[Departure Date]', String.valueOf(d.Name));
     			param2Emailtemplate.put('Subject', sub);
                String textbody = emailTemp.Body;
 				 param2Emailtemplate.put('plainTextBody', textbody);

                 String htmlBody = emailTemp.HtmlValue;
                     
                  htmlBody = htmlBody.Replace('[Departure Date]', String.valueOf(d.Name));
                  htmlBody = htmlBody.Replace('[Deal]', String.valueOf(d.Deal__r.Name));
                 param2Emailtemplate.put('htmlBody', htmlBody);
                
                Utility_SingleEmailMessageHandler.EmailHandlerMethod(emailList, null,param2Emailtemplate,true,false );
                
            }
            
    }   
        
    }
    }
}