force-app/main/default/objects/Account/fields/Merchant_Portal_Access__c.field-meta.xml
<CustomField>
    <fullName>Merchant_Portal_Access__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If Merchant has access of merchant portal then the checkbox should be true.</description>
    <label>Merchant Portal Access</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Component__c/Component__c.object-meta.xml
<CustomObject>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Component__c/fields/BC_Required__c.field-meta.xml
<CustomField>
    <fullName>BC_Required__c</fullName>
    <label>BC Required</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Component__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Components</relationshipLabel>
    <relationshipName>Components</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal__c/Deal__c.object-meta.xml
<CustomObject>
    <label>Deal</label>
    <nameField>
        <label>Deal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal__c/fields/Allocation_by__c.field-meta.xml
<CustomField>
    <fullName>Allocation_by__c</fullName>
    <label>Allocation by</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Deal</fullName>
                <default>true</default>
                <label>Deal</label>
            </value>
            <value>
                <fullName>Option</fullName>
            </value>
            <value>
                <fullName>Sub option</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal__c/fields/BC_Required__c.field-meta.xml
<CustomField>
    <fullName>BC_Required__c</fullName>
    <defaultValue>&apos;No&apos;</defaultValue>
    <label>BC Required</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal__c/fields/deal_archetype__c.field-meta.xml
<CustomField>
    <fullName>deal_archetype__c</fullName>
    <label>Deal Archetype</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MADU1</fullName>
            </value>
            <value>
                <fullName>MADUZ1</fullName>
            </value>
            <value>
                <fullName>MADU2</fullName>
            </value>
            <value>
                <fullName>MADUZ2</fullName>
            </value>
            <value>
                <fullName>TAIU1</fullName>
            </value>
            <value>
                <fullName>TAIZ1</fullName>
            </value>
            <value>
                <fullName>TAIUZ1</fullName>
            </value>
            <value>
                <fullName>TAIU2</fullName>
            </value>
            <value>
                <fullName>TAIZ2</fullName>
            </value>
            <value>
                <fullName>TAIUZ2</fullName>
            </value>
            <value>
                <fullName>TANU1</fullName>
            </value>
            <value>
                <fullName>TANZ1</fullName>
            </value>
            <value>
                <fullName>TANUZ1</fullName>
            </value>
            <value>
                <fullName>TANU2</fullName>
            </value>
            <value>
                <fullName>TANZ2</fullName>
            </value>
            <value>
                <fullName>TANUZ2</fullName>
            </value>
            <value>
                <fullName>MANU1</fullName>
            </value>
            <value>
                <fullName>MANUZ1</fullName>
            </value>
            <value>
                <fullName>MANU2</fullName>
            </value>
            <value>
                <fullName>MANUZ2</fullName>
            </value>
            <value>
                <fullName>RADU1</fullName>
            </value>
            <value>
                <fullName>RADUZ1</fullName>
            </value>
            <value>
                <fullName>RADU2</fullName>
            </value>
            <value>
                <fullName>RADUZ2</fullName>
            </value>
            <value>
                <fullName>CAIU1</fullName>
            </value>
            <value>
                <fullName>CAIZ1</fullName>
            </value>
            <value>
                <fullName>CAIUZ1</fullName>
            </value>
            <value>
                <fullName>CAIU2</fullName>
            </value>
            <value>
                <fullName>CAIZ2</fullName>
            </value>
            <value>
                <fullName>CAIUZ2</fullName>
            </value>
            <value>
                <fullName>CANU1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal__c/fields/Deal_Status__c.field-meta.xml
<CustomField>
    <fullName>Deal_Status__c</fullName>
    <inlineHelpText>This field drives the status in the &quot;path&quot; at the top of the page to show the &quot;overall status&quot; of the deal.</inlineHelpText>
    <label>Deal Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BDM - Deal Draft In Progress</fullName>
                <default>true</default>
                <label>BDM - Deal Draft In Progress</label>
            </value>
            <value>
                <fullName>BDM - Submitted</fullName>
            </value>
            <value>
                <fullName>Plan &amp; Configure</fullName>
            </value>
            <value>
                <fullName>Submitted for Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>With_Publishing</fullName>
                <label>With Publishing</label>
            </value>
            <value>
                <fullName>Ready for Proofing</fullName>
            </value>
            <value>
                <fullName>Pre-Published</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
                <color>#57F17C</color>
                <label>Published</label>
            </value>
            <value>
                <fullName>Not Approved</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Analysis &amp; Approval</fullName>
                <isActive>false</isActive>
                <label>Analysis &amp; Approval</label>
            </value>
            <value>
                <fullName>BDM</fullName>
                <isActive>false</isActive>
                <label>BDM</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <isActive>false</isActive>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Marketing</fullName>
                <isActive>false</isActive>
                <label>Marketing</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal__c/fields/deal_type__c.field-meta.xml
<CustomField>
    <fullName>deal_type__c</fullName>
    <label>deal type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>travel</fullName>
            </value>
            <value>
                <fullName>cruise</fullName>
            </value>
            <value>
                <fullName>stay</fullName>
            </value>
            <value>
                <fullName>Siteminder Hotel</fullName>
            </value>
            <value>
                <fullName>Experiences</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal__c/fields/description__c.field-meta.xml
<CustomField>
    <fullName>description__c</fullName>
    <label>Deal Highlights</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal__c/fields/Flight_Book_By__c.field-meta.xml
<CustomField>
    <fullName>Flight_Book_By__c</fullName>
    <label>Flight Book By</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Deal__c/fields/Inclusion_Icons__c.field-meta.xml
<CustomField>
    <fullName>Inclusion_Icons__c</fullName>
    <label>Inclusion Icons</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Flights</fullName>
            </value>
            <value>
                <fullName>Cruise</fullName>
            </value>
            <value>
                <fullName>Rail</fullName>
            </value>
            <value>
                <fullName>Tour</fullName>
            </value>
            <value>
                <fullName>Accom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal__c/fields/Merchant__c.field-meta.xml
<CustomField>
    <fullName>Merchant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Merchant</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Product Partner, General Expense Vendors</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Deal</relationshipLabel>
    <relationshipName>Deal</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal__c/fields/merchant_sharing_deadline__c.field-meta.xml
<CustomField>
    <fullName>merchant_sharing_deadline__c</fullName>
    <inlineHelpText>Number of days prior to departure that merchant will receive booking confirmation. If multi-merchant deal, please use the most restrictive deadline e.g 120 days instead of 90.</inlineHelpText>
    <label>Merchant Sharing Deadline - Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Deal__c/fields/meta_description__c.field-meta.xml
<CustomField>
    <fullName>meta_description__c</fullName>
    <label>Meta Description</label>
    <length>300</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Deal__c/fields/PDF_Image__c.field-meta.xml
<CustomField>
    <fullName>PDF_Image__c</fullName>
    <label>PDF Image</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal__c/fields/site__c.field-meta.xml
<CustomField>
    <fullName>site__c</fullName>
    <label>Site</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Hero</fullName>
            </value>
            <value>
                <fullName>Published(NRMA)</fullName>
            </value>
            <value>
                <fullName>Published(Staging)</fullName>
            </value>
            <value>
                <fullName>Hero(Staging)</fullName>
            </value>
            <value>
                <fullName>Hidden</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal__c/fields/title__c.field-meta.xml
<CustomField>
    <fullName>title__c</fullName>
    <label>title</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal__c/fields/visa_information__c.field-meta.xml
<CustomField>
    <fullName>visa_information__c</fullName>
    <label>Visa Information</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/BAU_List_of_Merchants_On_Deal_Test.cls
@isTest
public class BAU_List_of_Merchants_On_Deal_Test {


     @testSetup static void setup() {
        
        Account acmc = new Account (
            Name = 'newAcc1',
            BC_Required__c = 'Yes',
            Merchant_Portal_Access__c = True
        );  
        insert acmc;
        Contact con = new Contact (
            AccountId = acmc.id,
            LastName = 'portalTestUser'
        );
        
        insert con;
        con.isEnableNotification__c = true;
        update con;
        
        
        List<RecordType> RCTProductPartner = TADUtils.getRecordType(Label.TAD_RT_Product_Partner);
        Account acctBussiness = TestDataFactory.createBussinessAccount(RCTProductPartner[0].Id);   // Bussiness account Inserted
        acctBussiness.Merchant_Type__c='Multi Line Expense';
        acctBussiness.BC_Required__c = 'Yes';
        acctBussiness.Merchant_Portal_Access__c = True;
        
        insert acctBussiness;
        system.debug('Line--33-->'+acctBussiness);
        List<RecordType> RCTTadDeal = TADUtils.getRecordType(Label.TAD_RT_TAD_Deal);
        
        list<String> dealId = new list<String>();
        
        Deal__c deal = TestDataFactory.createMerchantDeal(RCTTadDeal[0].Id , acctBussiness.Id );   // Deals created
         deal.Allocation_by__c='Deal';
        deal.deal_archetype__c = 'CANU1';
        deal.Flight_Book_By__c = 12;
        deal.merchant_sharing_deadline__c = 60;
        //deal.RecordTypeId = RCTTadDeal[0].Id;
        //deal.Merchant__c = acctBussiness.Id;
        deal.Name = '1234';
        deal.site__c = 'AU';
        deal.deal_type__c = 'travel';
        deal.title__c = '12day';
        deal.description__c = 'Deal description';
        deal.status__c = 'Pending';
        deal.Deal_Status__c = 'Approved';
        deal.PDF_Image__c = 'String';
        deal.meta_description__c = 'somestring';
        deal.Inclusion_Icons__c = 'Accom';
        deal.visa_information__c='Done';
        deal.Accounting_Treatment_AU__c  ='Principal';
        deal.Estimated_Weighted_Margin__c =10;
        deal.Finance_Approval_Date_Submitted__c =system.today()-4;
        deal.Continent__c = 'Europe';
        deal.GST_AU__c ='GST free';
        deal.BNCDL__c = True;
        deal.PIF_Module__c ='Passenger Detail';
        deal.WL_Status__c = 'None';
        deal.Qantas_WL_Deal__c = True;
        deal.Flight_Ticketing_Structure__c = 'Group';
		deal.Airline__c = 'Qantas';
        insert deal;
        dealId.add(deal.Id);
        
        
        Product_FX_Pricing__c pfp = TestDataFactory.createPFXP();
        insert pfp;
         
        List<Component__c> compList = new  List<Component__c>();
        
        Component__c dealComp = new Component__c();
        dealComp.Deal__c=deal.id;
        dealComp.LinkedDeal_D_O_S__c=deal.id;
        dealComp.ff_Pricing_structure__c='Not applicable';
        dealComp.Component_Type__c= 'Cruise';
        dealComp.Merchant_Name__c = acmc.Id;
        dealComp.Product_FX_Pricing__c = pfp.Id;
        
        insert  dealComp;
        deal.Deal_Status__c = 'Published';
        deal.Status__c = 'Published';
        Update deal;
    }
    
    @isTest
    static void onHoldMethod(){
        
        
        
        //UserRole ur = [Select PortalType, PortalAccountId From UserRole where PortalType =:'CustomerPortal' limit 1];
        Profile p = [select Id,name from Profile where name ='Partner Community Plus User' limit 1];
        Contact con = [Select Id,Name from Contact limit 1];
        
        User newUser = new User( email='genelia.dsouza@gmail.com',
                                profileid = p.Id, 
                                UserName='genelia.dsouza@gmail.com', 
                                Alias = 'GDS',
                                TimeZoneSidKey='America/New_York',
                                EmailEncodingKey='ISO-8859-1',
                                LocaleSidKey='en_US', 
                                LanguageLocaleKey='en_US',
                                ContactId = con.Id,
                                PortalRole = 'Manager',
                                FirstName = 'Genelia',
                                LastName = 'Dsouza');
        insert newUser;  
        
        
        Account acctBussiness = [SELECT Id FROM Account where Name = 'Merchant' LIMIT 1];  // Bussiness account Inserted
        
        Deal__c deal = [SELECT Id FROM Deal__c where Merchant__c =: acctBussiness.Id LIMIT 1];   // Deals created
        Component__c complist = [Select Id From Component__c where LinkedDeal_D_O_S__c =:deal.Id LIMIT 1];
        
        
        System.runAs(newUser){
            BAU_List_of_Merchants_On_Deal listOfMP = new BAU_List_of_Merchants_On_Deal();
            ID batchprocessid = Database.executeBatch(listOfMP);
            
            BAU_List_ofMerchantsOnDeal_Schedulable sh1 = new BAU_List_ofMerchantsOnDeal_Schedulable();
            String sch = '0 0 2 * * ?'; 
            system.schedule('Test Territory Check', sch, sh1); 
        }
        
    }
}