force-app/main/default/objects/Cruise_Cabin_Booking_POE__c/Cruise_Cabin_Booking_POE__c.object-meta.xml
<CustomObject>
    <label>Cruise Cabin Booking</label>
    <nameField>
        <displayFormat>CCB{0000000}</displayFormat>
        <label>Cruise Cabin Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cruise Cabin Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cruise_Cabin_Booking_POE__c/fields/ordexp_tad_order__c.field-meta.xml
<CustomField>
    <fullName>ordexp_tad_order__c</fullName>
    <label>TAD Order</label>
    <referenceTo>TAD_Order__c</referenceTo>
    <relationshipLabel>Cruise Cabin Bookings</relationshipLabel>
    <relationshipName>Cruise_Cabin_Bookings_POE</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/TAD_Order__c.object-meta.xml
<CustomObject>
    <label>TAD Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TAD Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_cabin_bookings_outstanding__c.field-meta.xml
<CustomField>
    <fullName>ordexp_cabin_bookings_outstanding__c</fullName>
    <formula>Room_Cabin_Required__c - ordexp_cabins_booked__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cabin bookings outstanding</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_cabins_booked__c.field-meta.xml
<CustomField>
    <fullName>ordexp_cabins_booked__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Contains count of Cabins Booked</description>
    <label>Cabins Booked</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_status_check__c.field-meta.xml
<CustomField>
    <fullName>ordexp_status_check__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field especially created for Order Status Updation</description>
    <label>Status Check</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/tad_CruiseCabinBookingRollUpSummary.cls
public class tad_CruiseCabinBookingRollUpSummary {
   
    public static void RollUpSummaryCruiseCabinWithTADOrder(List<Cruise_Cabin_Booking_POE__c> cabinsBookedList){
        List<tad_order__c> ordToUpdate = new List<tad_order__c>();
        
        set<Id> tadOrderIdsSet = new set<id>();
        for(Cruise_Cabin_Booking_POE__c ccPOE: cabinsBookedList){
            tadOrderIdsSet.add(ccPOE.ordexp_tad_order__c);
        }//for closed
        
        if(!tadOrderIdsSet.isEmpty()){           
            List<tad_order__c> fetchOrderDataToUpdate = [Select id, ordexp_status_check__c,ordexp_cabin_bookings_outstanding__c,ordexp_cabins_booked__c,(SELECT Id FROM Cruise_Cabin_Bookings_POE__r) from tad_order__c where id IN:  tadOrderIdsSet  ];
            
            system.debug('fetchOrderDataToUpdate '+fetchOrderDataToUpdate);
            
            for(tad_order__c ord:fetchOrderDataToUpdate){
                ord.ordexp_cabins_booked__c = ord.Cruise_Cabin_Bookings_POE__r.size();
                ordToUpdate.add(ord);
            }
            
            system.debug('ordToUpdate '+ordToUpdate);
            update ordToUpdate;
        }
    }
    
     /***************************Changes Made By AJIT*****PSAG:98**********************************Start*/
     public static void RollUpSummaryCruiseCabinWithTADOrderUpdate(Set<Id> orderIds){
        List<tad_order__c> ordToUpdate = new List<tad_order__c>();

        if(!orderIds.isEmpty()){
            List<tad_order__c> fetchOrderDataToUpdate = [Select id, ordexp_status_check__c,ordexp_cabin_bookings_outstanding__c,ordexp_cabins_booked__c,(SELECT Id FROM Cruise_Cabin_Bookings_POE__r) from tad_order__c where id IN: orderIds];
            
            system.debug('fetchOrderDataToUpdate '+fetchOrderDataToUpdate);
            
            for(tad_order__c ord:fetchOrderDataToUpdate){
                ord.ordexp_cabins_booked__c = ord.Cruise_Cabin_Bookings_POE__r.size();
                ordToUpdate.add(ord);
            }
            
            system.debug('ordToUpdate '+ordToUpdate);
            update ordToUpdate;
        }
    }
     /***************************Changes Made By AJIT*****PSAG:98**********************************End*/
}