force-app/main/default/objects/Cruise_Cabin_Booking_POE__c/Cruise_Cabin_Booking_POE__c.object-meta.xml
<CustomObject>
    <label>Cruise Cabin Booking</label>
    <nameField>
        <displayFormat>CCB{0000000}</displayFormat>
        <label>Cruise Cabin Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cruise Cabin Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cruise_Cabin_Booking_POE__c/fields/cabin_number__c.field-meta.xml
<CustomField>
    <fullName>cabin_number__c</fullName>
    <label>Cabin Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cruise_Cabin_Booking_POE__c/fields/cabin_price__c.field-meta.xml
<CustomField>
    <fullName>cabin_price__c</fullName>
    <label>Cabin Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Cruise_Cabin_Booking_POE__c/fields/cruise_booking_reference__c.field-meta.xml
<CustomField>
    <fullName>cruise_booking_reference__c</fullName>
    <label>Cruise Booking Reference</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cruise_Cabin_Booking_POE__c/fields/cruise_company__c.field-meta.xml
<CustomField>
    <fullName>cruise_company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cruise Company</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Cruise Company must be of Record Type &quot;Product Partner&quot; - Value does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>contains</operation>
            <value>Product Partner</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cruise Cabin Bookings</relationshipLabel>
    <relationshipName>Cruise_Cabin_Bookings_POE</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cruise_Cabin_Booking_POE__c/fields/mp_Cruise_Company__c.field-meta.xml
<CustomField>
    <fullName>mp_Cruise_Company__c</fullName>
    <label>Cruise Company</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MSC</fullName>
            </value>
            <value>
                <fullName>Royal Caribbean</fullName>
            </value>
            <value>
                <fullName>Celebrity Cruises</fullName>
            </value>
            <value>
                <fullName>Costa Cruises</fullName>
            </value>
            <value>
                <fullName>Norwegian Cruise Lines</fullName>
            </value>
            <value>
                <fullName>Carnival Cruises</fullName>
            </value>
            <value>
                <fullName>Holland America</fullName>
            </value>
            <value>
                <fullName>Princess Cruises</fullName>
            </value>
            <value>
                <fullName>P&amp;O Cruises</fullName>
            </value>
            <value>
                <fullName>CMV Cruises</fullName>
            </value>
            <value>
                <fullName>Oceania Cruises</fullName>
            </value>
            <value>
                <fullName>Virgin Voyages</fullName>
            </value>
            <value>
                <fullName>Dream Cruises</fullName>
            </value>
            <value>
                <fullName>Captain Cook Cruises</fullName>
            </value>
            <value>
                <fullName>Pullmantur</fullName>
            </value>
            <value>
                <fullName>Hurtigruten</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cruise_Cabin_Booking_POE__c/fields/ordexp_tad_order__c.field-meta.xml
<CustomField>
    <fullName>ordexp_tad_order__c</fullName>
    <label>TAD Order</label>
    <referenceTo>TAD_Order__c</referenceTo>
    <relationshipLabel>Cruise Cabin Bookings</relationshipLabel>
    <relationshipName>Cruise_Cabin_Bookings_POE</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cruise_Cabin_Booking_POE__c/fields/partner_purchased__c.field-meta.xml
<CustomField>
    <fullName>partner_purchased__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Partner Purchased</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Cruise_Cabin_Booking_POE__c/fields/ship_name__c.field-meta.xml
<CustomField>
    <fullName>ship_name__c</fullName>
    <label>Ship Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal__c/Deal__c.object-meta.xml
<CustomObject>
    <label>Deal</label>
    <nameField>
        <label>Deal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal__c/fields/Cruise_Cabin_Booked_by__c.field-meta.xml
<CustomField>
    <fullName>Cruise_Cabin_Booked_by__c</fullName>
    <defaultValue>&apos;None&apos;</defaultValue>
    <label>Cruise Cabin Booked by</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>TAD</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TAD_Order__c/TAD_Order__c.object-meta.xml
<CustomObject>
    <label>TAD Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TAD Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TAD_Order__c/fields/Cruise_Reference_Required__c.field-meta.xml
<CustomField>
    <fullName>Cruise_Reference_Required__c</fullName>
    <formula>IF(  (TEXT(ordexp_deal__r.Cruise_Cabin_Booked_by__c) ==&apos;Partner&apos;) &amp;&amp;   ordexp_cabin_bookings_outstanding__c != 0, true, false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cruise Reference Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_cabin_bookings_outstanding__c.field-meta.xml
<CustomField>
    <fullName>ordexp_cabin_bookings_outstanding__c</fullName>
    <formula>Room_Cabin_Required__c - ordexp_cabins_booked__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cabin bookings outstanding</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_cabins_booked__c.field-meta.xml
<CustomField>
    <fullName>ordexp_cabins_booked__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Contains count of Cabins Booked</description>
    <label>Cabins Booked</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_deal__c.field-meta.xml
<CustomField>
    <fullName>ordexp_deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>TAD_Orders_Deal</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_deal_type__c.field-meta.xml
<CustomField>
    <fullName>ordexp_deal_type__c</fullName>
    <formula>IF(INCLUDES(ordexp_deal__r.deal_type__c , &apos;stay&apos;), &apos;Stay|&apos;,&apos;&apos;) + IF(INCLUDES(ordexp_deal__r.deal_type__c , &apos;travel&apos;), &apos;Travel|&apos;,&apos;&apos;) +  IF(INCLUDES(ordexp_deal__r.deal_type__c , &apos;Cruise&apos;),&apos;Cruise|&apos; ,&apos;&apos;) + IF(TEXT(ordexp_deal__r.Dates_Flights__c) =&apos;Dates/Domestic Flights&apos; || TEXT(ordexp_deal__r.Dates_Flights__c) =&apos;Dates/International Flights&apos;, &apos;Flight|&apos;,&apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Deal Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_master_status__c.field-meta.xml
<CustomField>
    <fullName>ordexp_master_status__c</fullName>
    <label>Master status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
                <default>true</default>
                <label>On Hold</label>
            </value>
            <value>
                <fullName>Temporary Hold</fullName>
            </value>
            <value>
                <fullName>Secured</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Travelled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>In Progress-Cruise only</fullName>
                <isActive>false</isActive>
                <label>In Progress-Cruise only</label>
            </value>
            <value>
                <fullName>In Progress-Flight only</fullName>
                <isActive>false</isActive>
                <label>In Progress-Flight only</label>
            </value>
            <value>
                <fullName>In Progress-Flights + Cruise</fullName>
                <isActive>false</isActive>
                <label>In Progress-Flights + Cruise</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_status_check__c.field-meta.xml
<CustomField>
    <fullName>ordexp_status_check__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field especially created for Order Status Updation</description>
    <label>Status Check</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CruiseCabinBooking.cls
public class CruiseCabinBooking {
    
    @AuraEnabled
    public static OrderDataRetreived getOrderData (id recId){
        
        OrderDataRetreived wrap = new OrderDataRetreived();
        wrap.proceed=false;
        wrap.cruiseCabinBookedByPartner = false;
        
        tad_order__c orderdata = [Select id , ordexp_deal_type__c,Cruise_Reference_Required__c,ordexp_cabin_bookings_outstanding__c,ordexp_master_status__c, ordexp_deal__r.Cruise_Cabin_Booked_by__c from tad_order__c where id =: recId limit 1 ];
        
        // if(orderdata.ordexp_deal__r.Cruise_Cabin_Booked_by__c == 'Partner'){
        //     wrap.cruiseCabinBookedByPartner = true;
        // }
        if(orderdata.Cruise_Reference_Required__c == true){
            wrap.cruiseCabinBookedByPartner = true;
        }
        else{
            wrap.cruiseCabinBookedByPartner = false;
        }
        
        if(orderdata.ordexp_cabin_bookings_outstanding__c > 0){
            if((orderdata.ordexp_deal_type__c.containsIgnoreCase('Cruise') || (orderdata.ordexp_deal_type__c.containsIgnoreCase('Flight') && orderdata.ordexp_deal_type__c.containsIgnoreCase('Cruise')) ) && orderdata.ordexp_master_status__c== TAD_Constants.TADINPROGRESS ){
                wrap.proceed=true;
                wrap.cabinQty=String.valueOf(orderdata.ordexp_cabin_bookings_outstanding__c);
            } 
        }
        return wrap; 
    }
    
    
    @AuraEnabled
    public static List <Account> fetchLookUpValues(String searchKeyWord) {
        String cruise = Label.Cruise_Company_Names;
        
        List<Account> finalAcc = new List<Account> ();         
        String searchKey =  '%' + searchKeyWord + '%';
        
        list<Account> accList = [select id, Name from Account where Name LIKE: searchKey AND  RecordType.Name='Product Partner' Limit 5 ];
        
        for(Account acc :accList){
            if(cruise.contains(acc.name)){
                finalAcc.add(acc);  
            }
        }        
        
        return finalAcc;
    }
    
    @AuraEnabled
    public static String createCabinRecord (id recId ,Cruise_Cabin_Booking_POE__c cruiseCabinRecord , String cabinQuantity , String cabinNumbers, Boolean partnerBooked){
        
        List<Cruise_Cabin_Booking_POE__c> cabinsBookedList = [select id  from Cruise_Cabin_Booking_POE__c where ordexp_tad_order__c=:recId];
        Integer cabinsBooked = cabinsBookedList.size() + integer.valueof(cabinQuantity) ; 
        
        List<tad_order__c> orderdata = [Select id , ordexp_status_check__c,ordexp_cabin_bookings_outstanding__c from tad_order__c where id =: recId limit 1 ];
        
        String Status = 'proceed';
        
        if(orderdata[0].ordexp_cabin_bookings_outstanding__c<=0){
            Status = 'cabinsBooked'; 
        }
        
        List<Cruise_Cabin_Booking_POE__c> createCabins = new List<Cruise_Cabin_Booking_POE__c> ();
        
        Map<integer,String> cabinNumberMap = new Map<integer,String>();
        
        String []  cabinNumberList = cabinNumbers.trim().split('\n');
        for(integer i=0; i< cabinNumberList.size();i++){
            if(cabinNumberList[0]!='' && cabinNumberList[0]!=null){
                cabinNumberMap.put(i,cabinNumberList[i]) ; 
            }
        }
        System.debug('cabinNumberMap:'+cabinNumberMap);
        System.debug('cabinQuantity:'+cabinQuantity);
        if(cabinNumberMap.size()!=integer.valueof(cabinQuantity)){
            Status = 'cabinMismatch';  
        }
        
        if(Status=='proceed'){
            for(integer i=0 ; i< integer.valueof(cabinQuantity); i++){
                Cruise_Cabin_Booking_POE__c ccb = new Cruise_Cabin_Booking_POE__c();
                ccb.ordexp_tad_order__c= recId;
                // ccb.cruise_company__c=cruiseCabinRecord.cruise_company__c;
                ccb.mp_Cruise_Company__c = cruiseCabinRecord.mp_Cruise_Company__c;
                ccb.cabin_price__c = cruiseCabinRecord.cabin_price__c;
                ccb.cruise_booking_reference__c=cruiseCabinRecord.cruise_booking_reference__c;
                ccb.ship_name__c=cruiseCabinRecord.ship_name__c;
                ccb.ship_sail_date__c=cruiseCabinRecord.ship_sail_date__c;
                ccb.cabin_number__c=cabinNumberMap.get(i);
                ccb.partner_purchased__c=partnerBooked;
                createCabins.add(ccb);  
            }
            
            insert createCabins;  
            
            tad_order__c orderToUpdate = new tad_order__c();
            orderToUpdate.Id=recId;
            orderToUpdate.ordexp_cabins_booked__c=cabinsBooked;
            if(orderdata[0].ordexp_status_check__c==true){
                orderToUpdate.ordexp_status_check__c=false; 
            }
            else{
                orderToUpdate.ordexp_status_check__c=true;  
            }
            
            update orderToUpdate;
            
        }
        return status;
        
    }
    
    @AuraEnabled
    public static List<String> getPicklistvalues(String objectName, String field_apiname,Boolean nullRequired){
        List<String> optionlist = new List<String>();
        
        Map<String,Schema.SObjectType> gd = Schema.getGlobalDescribe(); 
        Map<String, Schema.SObjectField> field_map = gd.get(objectName.toLowerCase()).getDescribe().fields.getMap(); 
        
        List<Schema.PicklistEntry> picklistValues = field_map.get(field_apiname).getDescribe().getPickListValues();
        system.debug(picklistValues);
        
        if(nullRequired == true){
            optionlist.add('--None--');
        }
        
        for (Schema.PicklistEntry pv : picklistValues) {
            optionlist.add(pv.getLabel());
        }
        system.debug(optionlist);
        return optionlist;
        
    }
    
    public class OrderDataRetreived
    {
        @auraEnabled
        public Boolean proceed {get;set;}
        @auraEnabled
        public String cabinQty {get;set;}
        @auraEnabled
        public Boolean cruiseCabinBookedByPartner {get;set;}
    }
    
}