force-app/main/default/objects/Order_Communication_POE__c/Order_Communication_POE__c.object-meta.xml
<CustomObject>
    <description>Records created by scheduled apex</description>
    <label>Order Communication</label>
    <nameField>
        <displayFormat>OC-{00000000}</displayFormat>
        <label>Order Communication Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Communications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Communication_POE__c/fields/order_number__c.field-meta.xml
<CustomField>
    <fullName>order_number__c</fullName>
    <formula>TAD_Order__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Communication_POE__c/fields/Order_Payment_link__c.field-meta.xml
<CustomField>
    <fullName>Order_Payment_link__c</fullName>
    <label>Order Payment link</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Communication_POE__c/fields/TAD_Order__c.field-meta.xml
<CustomField>
    <fullName>TAD_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TAD Order</label>
    <referenceTo>TAD_Order__c</referenceTo>
    <relationshipLabel>Order Communications</relationshipLabel>
    <relationshipName>Order_Communications_POE</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Payment_Link__c/Order_Payment_Link__c.object-meta.xml
<CustomObject>
    <label>Order Payment Link</label>
    <nameField>
        <displayFormat>OPL-{0000000}</displayFormat>
        <label>Order Payment Link Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Payment Links</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Payment_Link__c/fields/Notify_Me__c.field-meta.xml
<CustomField>
    <fullName>Notify_Me__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Notify Me</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order_Payment_Link__c/fields/Notify_user__c.field-meta.xml
<CustomField>
    <fullName>Notify_user__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Notify user</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Order_Payment_Links</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Payment_Link__c/fields/TAD_Order__c.field-meta.xml
<CustomField>
    <fullName>TAD_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TAD Order</label>
    <referenceTo>TAD_Order__c</referenceTo>
    <relationshipName>Tad_Payment_Links</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/TAD_Order__c.object-meta.xml
<CustomObject>
    <label>TAD Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TAD Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TAD_OrderPaymentLinkSendEmail.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 06-15-2023
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public class TAD_OrderPaymentLinkSendEmail {

        public static void sendOrderPaymentLink(Set<Order_Payment_Link__c> recId )
    {
        
        List<Messaging.SingleEmailMessage> allmsg = new List<Messaging.SingleEmailMessage>();

        Order_Payment_Link__c OLPData = [Select Id,CreatedBy.Email,Notify_user__r.Email,TAD_Order__r.Name,Notify_Me__c from Order_Payment_Link__c where Id IN: recId];
        
       
     
        
        if(OLPData != null)
        {
            
            
            
            EmailTemplate tempId=[SELECT Id,Subject,HTMLValue,Body,Name FROM EmailTemplate WHERE Name= 'TAD_OrderPaymentLinkPaymentRecieved' LIMIT 1];
            String emailBody = tempID.HTMLValue;
            String subBody = tempId.Subject;
            List<OrgWideEmailAddress> lstEmailAddress=[select Id from OrgWideEmailAddress WHERE Address='noreply@tripadeal.com.au'];
            List<String> userEmails = new List<String>();
            List<String> consultantEmails = new List<String>();
            if(OLPData.CreatedBy.Email != null && OLPData.Notify_Me__c == true) {
            userEmails.add(OLPData.CreatedBy.Email);
            }
            if(OLPData.Notify_user__r.Email != null) {
                consultantEmails.add(OLPData.Notify_user__r.Email);
            }
            
            String orderName = OLPData.TAD_Order__r.Name;
            
            emailbody=emailBody.replace('{!Order_Communication_POE__c.order_number__c}',orderName);
            subBody=subBody.replace('{!Order_Communication_POE__c.order_number__c}',orderName);
            
               Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                
                system.debug('line 33'+mail.toAddresses);
                system.debug('userEmails'+userEmails.size());

                mail.setToAddresses(userEmails);
                mail.setSubject(subBody);
                mail.setHtmlBody(emailbody);
                mail.setOrgWideEmailAddressId(lstEmailAddress[0].Id); 
                mail.setSaveAsActivity(false);
                if(!userEmails.isEmpty()){
                    allmsg.add(mail);
                }
            
              
               Messaging.SingleEmailMessage mailConsultant = new Messaging.SingleEmailMessage();
                
                system.debug('line 33'+mail.toAddresses);
                system.debug('userEmails'+userEmails.size());

                mailConsultant.setToAddresses(consultantEmails);
                mailConsultant.setSubject(subBody);
                mailConsultant.setHtmlBody(emailbody);
                mailConsultant.setOrgWideEmailAddressId(lstEmailAddress[0].Id); 
                mailConsultant.setSaveAsActivity(false);
                if(!consultantEmails.isEmpty()){
                    allmsg.add(mailConsultant);
                }
            
          
        }
        
          if (!allmsg.isempty()){
                    system.debug('allmsg'+allmsg.size());
               
                    Messaging.SendEmailResult[] results = Messaging.sendEmail(allmsg);
                    //Messaging.sendEmail(allmsg);
                    if (results[0].success) {
                        System.debug('The email was sent successfully.');
                    } else {
                        System.debug('The email failed to send: ' + results[0].errors[0].message);
                    }  
                    system.debug('Line 38');
            }
        
 
    }
    
}