force-app/main/default/objects/Component__c/Component__c.object-meta.xml
<CustomObject>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Component__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Components</relationshipLabel>
    <relationshipName>Components</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Component__c/fields/MPT_JOIN__c.field-meta.xml
<CustomField>
    <fullName>MPT_JOIN__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Terms</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>MPT_JOIN__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Merchant_Name__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>MPT_JOIN__c</referenceTo>
    <relationshipLabel>Components</relationshipLabel>
    <relationshipName>Components</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal__c/Deal__c.object-meta.xml
<CustomObject>
    <label>Deal</label>
    <nameField>
        <label>Deal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal__c/fields/Cloned_From__c.field-meta.xml
<CustomField>
    <fullName>Cloned_From__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cloned From</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Deal</relationshipLabel>
    <relationshipName>Deal</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Merchant_Terms__c/Merchant_Terms__c.object-meta.xml
<CustomObject>
    <label>Merchant Terms</label>
    <nameField>
        <displayFormat>Merchant Terms-{00000}</displayFormat>
        <label>Merchant Terms Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Merchant Terms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Merchant_Terms__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Amount(%)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Merchant_Terms__c/fields/MPT_Join__c.field-meta.xml
<CustomField>
    <fullName>MPT_Join__c</fullName>
    <label>Payment Terms</label>
    <referenceTo>MPT_JOIN__c</referenceTo>
    <relationshipLabel>Merchant Terms</relationshipLabel>
    <relationshipName>Merchant_Terms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MPT_JOIN__c/MPT_JOIN__c.object-meta.xml
<CustomObject>
    <label>MPT_JOIN</label>
    <nameField>
        <label>MPT_JOIN  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MPT_JOINS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MPT_JOIN__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <formula>IF(Account__r.IsPersonAccount, Account__r.FirstName +&apos; &apos;+ Account__r.LastName, Account__r.Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MPT_JOIN__c/fields/Component__c.field-meta.xml
<CustomField>
    <fullName>Component__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Component_MPTJoin Lookup Relationship</description>
    <label>Component</label>
    <referenceTo>Component__c</referenceTo>
    <relationshipLabel>MPT_JOINS</relationshipLabel>
    <relationshipName>MPT_JOINS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MPT_JOIN__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>MPT_JOINS</relationshipLabel>
    <relationshipName>MPT_JOINS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MerchantTermTriggerHandler.cls
public class MerchantTermTriggerHandler {

 
    public static void preventLastRecordDeletion(Map<Id,Merchant_Terms__c> mptOldMap){
        System.debug('mptOldMap---'+mptOldMap);
        Map<Id,List<Merchant_Terms__c>> MPTJoinVsMtMap = new  Map<Id,List<Merchant_Terms__c>>();
        Map<Id,List<Merchant_Terms__c>> MPTJoinVsMtMapToDelete = new  Map<Id,List<Merchant_Terms__c>>();
        Set<Id> mptJoinIdSet = new  Set<Id>();
        for(Merchant_Terms__c mpt: mptOldMap.values()){
            
            mptJoinIdSet.add(mpt.MPT_Join__c);
        }
        
        		for(Merchant_Terms__c mterms : mptOldMap.values()){
            if(MPTJoinVsMtMapToDelete.containsKey(mterms.MPT_Join__c)){
                 List<Merchant_Terms__c> mtListToDelete = MPTJoinVsMtMapToDelete.get(mterms.MPT_Join__c);
                mtListToDelete.add(mterms);
               
            }else{
                
                List<Merchant_Terms__c> mtListToDelete = new List<Merchant_Terms__c>();
                mtListToDelete.add(mterms);
                MPTJoinVsMtMapToDelete.put(mterms.MPT_Join__c, mtListToDelete);
            }
        }
        System.debug('MPTJoinVsMtMapToDelete--'+MPTJoinVsMtMapToDelete);
  		for(Merchant_Terms__c mt : [Select id,Name,MPT_Join__c from Merchant_Terms__c where MPT_Join__c IN : mptJoinIdSet ]){
            if(MPTJoinVsMtMap.containsKey(mt.MPT_Join__c)){
                 List<Merchant_Terms__c> mtList = MPTJoinVsMtMap.get(mt.MPT_Join__c);
                mtList.add(mt);
               
            }else{
                
                List<Merchant_Terms__c> mtList = new List<Merchant_Terms__c>();
                mtList.add(mt);
                MPTJoinVsMtMap.put(mt.MPT_Join__c, mtList);
            }
        }
        
        System.debug('MPTJoinVsMtMap---'+MPTJoinVsMtMap);
        for(Id joinId : MPTJoinVsMtMap.keySet()){
            for(Merchant_Terms__c mpt : MPTJoinVsMtMap.get(joinId)){
                System.debug('MPTJoinVsMtMap.get(joinId).size()---'+MPTJoinVsMtMap.get(joinId).size());
                   System.debug('MPTJoinVsMtMapToDelete.get(joinId).size()---'+MPTJoinVsMtMapToDelete.get(joinId).size());
                if(MPTJoinVsMtMap.get(joinId).size() == MPTJoinVsMtMapToDelete.get(joinId).size()){
                    
                    Merchant_Terms__c actualRecord = mptOldMap.get(mpt.Id);
                   actualRecord.addError('Cannot delete the last record of payment terms. Please edit the existing record');
                }
                
            }
        }
    }
    
    public static void restrictRecordDeletionHavingMptJoin(List<Merchant_Terms__c> mptOldList){
        
        Set<Id> mptJoinIds = new Set<Id>();
        
        for(Merchant_Terms__c mpt : mptOldList){
            
            mptJoinIds.add(mpt.MPT_Join__c);
            system.debug('mptJoinIds--'+mptJoinIds);
        }
        
	 	List<Component__c> compList = [Select Id,Name,MPT_JOIN__c from Component__c where MPT_JOIN__c IN : mptJoinIds ];
        system.debug('compList----'+compList);
        Set<Id> mptJoinIdscomp = new Set<Id>();
        
        for(Component__c comp :compList){
            
            mptJoinIdscomp.add(comp.MPT_JOIN__c);
            system.debug('mptJoinIdscomp---'+mptJoinIdscomp);
        }
        for(Merchant_Terms__c mpt1 : mptOldList){
            system.debug('mpt1--'+mpt1);
       
            if(mptJoinIdscomp.contains(mpt1.MPT_Join__c)) {
                
                mpt1.adderror('You cannot delete this Merchant Term record');
                    
                }
                
            
              
                
            }
        }
    
     public static void updateName(List<Merchant_Terms__c> mtList){
        
        Set<String> setMptId = new Set<String>();
        List<MPT_JOIN__c> lstToUpdateMPT = new List<MPT_JOIN__c>(); 
		For(Merchant_Terms__c mt : mtList)
		{
			setMptId.add(mt.MPT_Join__c);
		}

		List<MPT_JOIN__c> listMptJoin = [select Id,Name,Deal__c,Deal__r.Name ,Account_Name__c,(select Id,Amount__c from Merchant_Terms__r) from MPT_JOIN__c where Id IN :setMptId ];

		For(MPT_JOIN__c mp : listMptJoin)
		{
              String conAmount = '';
			List<Merchant_Terms__c> lstMT = mp.Merchant_Terms__r;
			for(Merchant_Terms__c mpt :lstMT)
		{
            conAmount += String.valueOf(mpt.Amount__c)+'/';
            system.debug('conAmount---'+conAmount);
          }
            conAmount = conAmount.removeEnd('/');
             mp.Name = mp.Deal__r.Name+ '-' +mp.Account_Name__c+'-'+conAmount;
            
            lstToUpdateMPT.add(mp);
            System.debug('lstToUpdateMPT--'+lstToUpdateMPT);
		}
         Update lstToUpdateMPT;
    	}
    

}