force-app/main/default/objects/Component__c/Component__c.object-meta.xml
<CustomObject>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Component__c/fields/name__c.field-meta.xml
<CustomField>
    <fullName>name__c</fullName>
    <label>Name</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Component__c/fields/Options__c.field-meta.xml
<CustomField>
    <fullName>Options__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Options</label>
    <referenceTo>options__c</referenceTo>
    <relationshipLabel>Components</relationshipLabel>
    <relationshipName>Components</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Component__c/fields/Sub_Options__c.field-meta.xml
<CustomField>
    <fullName>Sub_Options__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sub Options</label>
    <referenceTo>sub_options__c</referenceTo>
    <relationshipLabel>Components</relationshipLabel>
    <relationshipName>Components</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/options__c/options__c.object-meta.xml
<CustomObject>
    <label>Options</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/options__c/fields/title__c.field-meta.xml
<CustomField>
    <fullName>title__c</fullName>
    <label>title</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sub_options__c/sub_options__c.object-meta.xml
<CustomObject>
    <label>Sub Options</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/sub_options__c/fields/options__c.field-meta.xml
<CustomField>
    <fullName>options__c</fullName>
    <label>options</label>
    <referenceTo>options__c</referenceTo>
    <relationshipLabel>Sub Options</relationshipLabel>
    <relationshipName>sub_options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/sub_options__c/fields/OptionsTitle__c.field-meta.xml
<CustomField>
    <fullName>OptionsTitle__c</fullName>
    <formula>options__r.title__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Options1</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sub_options__c/fields/title__c.field-meta.xml
<CustomField>
    <fullName>title__c</fullName>
    <label>title</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OptionTriggerHandler.cls
public class OptionTriggerHandler {
    public static boolean runOnce = false;
    
        public static void updateRelatedChild(List<options__c> optList){
        set<Id> subOptIds = new set<ID>(); 
        system.debug('optList '+optList);
        
        
        List<sub_options__c> relatedSubOpt = [SELECT ID,OptionsTitle__c, Name, title__c  FROM sub_options__c WHERE options__c IN:optList];
        system.debug('optList '+relatedSubOpt); 
            
           for(sub_options__c sOpt: relatedSubOpt){
                if(sOpt.Id != null){
                    subOptIds.add(sOpt.Id);
                }
            }
         
        if(!relatedSubOpt.isEmpty()){
                update relatedSubOpt;
            }
            
        if(!subOptIds.isEmpty()){
            List<Component__c> relatedCmp = [SELECT Name, Name__c  From Component__c WHERE options__c IN:optList or Sub_Options__c IN:subOptIds]; 
            if(!relatedCmp.isEmpty()){
                update relatedCmp;
            }
         system.debug('optList '+relatedCmp);    
        }
    }
}