force-app/main/default/objects/Component__c/Component__c.object-meta.xml
<CustomObject>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Component__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Components</relationshipLabel>
    <relationshipName>Components</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Component__c/fields/ff_Pricing_structure__c.field-meta.xml
<CustomField>
    <fullName>ff_Pricing_structure__c</fullName>
    <label>Tiered Cost Rule</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not applicable</fullName>
                <label>General</label>
            </value>
            <value>
                <fullName>Cost Updates</fullName>
                <label>Tiered: Cost updates</label>
            </value>
            <value>
                <fullName>No Order Lines</fullName>
                <isActive>false</isActive>
                <label>No Order Lines</label>
            </value>
            <value>
                <fullName>No Cost Updates</fullName>
                <isActive>false</isActive>
                <label>Tiered: No Cost updates</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Component__c/fields/MPT_JOIN__c.field-meta.xml
<CustomField>
    <fullName>MPT_JOIN__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Terms</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>MPT_JOIN__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Merchant_Name__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>MPT_JOIN__c</referenceTo>
    <relationshipLabel>Components</relationshipLabel>
    <relationshipName>Components</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Component__c/fields/Product_FX_Pricing__c.field-meta.xml
<CustomField>
    <fullName>Product_FX_Pricing__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Currency</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Product_FX_Pricing__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product_FX_Pricing__c</referenceTo>
    <relationshipLabel>Components</relationshipLabel>
    <relationshipName>Components</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Component__c/fields/Ticketing_Side__c.field-meta.xml
<CustomField>
    <fullName>Ticketing_Side__c</fullName>
    <label>Ticketing Side</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TAD</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal__c/Deal__c.object-meta.xml
<CustomObject>
    <label>Deal</label>
    <nameField>
        <label>Deal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Merchant_Terms__c/Merchant_Terms__c.object-meta.xml
<CustomObject>
    <label>Merchant Terms</label>
    <nameField>
        <displayFormat>Merchant Terms-{00000}</displayFormat>
        <label>Merchant Terms Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Merchant Terms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Merchant_Terms__c/fields/MPT_Join__c.field-meta.xml
<CustomField>
    <fullName>MPT_Join__c</fullName>
    <label>Payment Terms</label>
    <referenceTo>MPT_JOIN__c</referenceTo>
    <relationshipLabel>Merchant Terms</relationshipLabel>
    <relationshipName>Merchant_Terms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MPT_JOIN__c/MPT_JOIN__c.object-meta.xml
<CustomObject>
    <label>MPT_JOIN</label>
    <nameField>
        <label>MPT_JOIN  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MPT_JOINS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MPT_JOIN__c/fields/Component__c.field-meta.xml
<CustomField>
    <fullName>Component__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Component_MPTJoin Lookup Relationship</description>
    <label>Component</label>
    <referenceTo>Component__c</referenceTo>
    <relationshipLabel>MPT_JOINS</relationshipLabel>
    <relationshipName>MPT_JOINS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MPT_JOIN__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>MPT_JOINS</relationshipLabel>
    <relationshipName>MPT_JOINS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_FX_Pricing__c/Product_FX_Pricing__c.object-meta.xml
<CustomObject>
    <description>This object is used in pricing products based on the FX rate set bay the CFO.</description>
    <label>Product FX Pricing</label>
    <nameField>
        <label>Product FX Pricing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product FX Pricing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/MerchantTermTriggerHandlerTest.cls
@isTest
public class MerchantTermTriggerHandlerTest {

    @isTest
    static void deleteMpt(){
        
             
        List<RecordType> RCTProductPartner = TADUtils.getRecordType(Label.TAD_RT_Product_Partner);
        
        Account acctBussiness = TestDataFactory.createBussinessAccount(RCTProductPartner[0].Id);   // Bussiness account Inserted
        insert acctBussiness;
        
         List<RecordType> RCTTadDeal = TADUtils.getRecordType(Label.TAD_RT_TAD_Deal);
        
        Deal__c deal = TestDataFactory.createMerchantDeal(RCTTadDeal[0].Id , acctBussiness.Id );   // Deals created
        insert deal;
        
        MPT_JOIN__c mptjoin = TestDataFactory.createMptJoin(acctBussiness);
        insert mptjoin;
        
        List<Merchant_Terms__c> mptToinsert = new List<Merchant_Terms__c>();
        
        Merchant_Terms__c mpt1 = TestDataFactory.createMpt(mptjoin, 'Pending');
        mptToinsert.add(mpt1);
        Merchant_Terms__c mpt2 = TestDataFactory.createMpt(mptjoin, 'Pending');
        mptToinsert.add(mpt2);
        Merchant_Terms__c mpt3 = TestDataFactory.createMpt(mptjoin, 'Pending');
		mptToinsert.add(mpt3);
        
        Insert mptToinsert;
        
       Product_FX_Pricing__c pfp = TestDataFactory.createPFXP();
       insert pfp;
        
         Component__c comp = TestDataFactory.cutomComponent(acctBussiness,'Flight',pfp);
       comp.Deal__c = deal.Id;
       comp.ff_Pricing_structure__c = 'Not applicable';
        comp.Ticketing_Side__c = 'TAD';
       insert comp;
        
        delete mpt1;
        
        
    }
        
}