force-app/main/default/objects/Component__c/Component__c.object-meta.xml
<CustomObject>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Component__c/fields/Cloned_From__c.field-meta.xml
<CustomField>
    <fullName>Cloned_From__c</fullName>
    <label>Cloned From</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Component__c/fields/LinkedDeal_D_O_S__c.field-meta.xml
<CustomField>
    <fullName>LinkedDeal_D_O_S__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>LinkedDeal(D/O/S)</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Components (LinkedDeal(D/O/S))</relationshipLabel>
    <relationshipName>Components1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Component__c/fields/name__c.field-meta.xml
<CustomField>
    <fullName>name__c</fullName>
    <label>Name</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Component_Pricing__c/Component_Pricing__c.object-meta.xml
<CustomObject>
    <label>Component Pricing</label>
    <nameField>
        <label>Component Pricing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Component Pricing</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Component_Pricing__c/fields/Component__c.field-meta.xml
<CustomField>
    <fullName>Component__c</fullName>
    <label>Component</label>
    <referenceTo>Component__c</referenceTo>
    <relationshipLabel>Component Pricing</relationshipLabel>
    <relationshipName>Component_Pricing</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Component_Pricing__c/fields/LinkedDeal_D_O_S__c.field-meta.xml
<CustomField>
    <fullName>LinkedDeal_D_O_S__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>LinkedDeal(D/O/S)</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Component Pricing</relationshipLabel>
    <relationshipName>Component_Pricing</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/batchToCreateComponentPricing.cls
global class batchToCreateComponentPricing implements Database.Batchable<sObject> {
    
    List <Component__c> componentRecordSet = new List<Component__c>();
    
    global batchToCreateComponentPricing( List <Component__c> componentRecordList){
        componentRecordSet = componentRecordList; 
    }
    
    global List<SObject> start(Database.BatchableContext BC){
        return componentRecordSet;
    }
    
    global void execute(Database.BatchableContext BC, List<Component__c> scope){
        
        List<Component__c> compToInsert = new List<Component__c>();
        
        for(Component__c s : scope){
            s.name__c='testComp111';
            compToInsert.add(s); 
        }      
        insert compToInsert;
        
        // Insert Pricing Record
        
        Map<id,Component_Pricing__c> compPriceToInsert = new Map<id,Component_Pricing__c>();
        String recId = compToInsert[0].Cloned_From__c;
        
        String compPriceSoql = cloneDealRecords.getCreatableFieldsSOQL('Component_Pricing__c','Component__c ='+'\''+ recId + '\'' );
        List<Component_Pricing__c> compPriceRec = (List<Component_Pricing__c>)Database.query(compPriceSoql);
        
        for(Component_Pricing__c   compp :compPriceRec ){
            Component_Pricing__c   inst = compp.clone(false, true);
            inst.Component__c   = compToInsert[0].id;
            inst.LinkedDeal_D_O_S__c = compToInsert[0].LinkedDeal_D_O_S__c;
            compPriceToInsert.put(compp.id,inst); 
        }        
        
        Database.insert (compPriceToInsert.values(),false );
        
        
        
    }
    
    global void finish(Database.BatchableContext BC){
        
    }
    
}