force-app/main/default/objects/Component__c/Component__c.object-meta.xml
<CustomObject>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Component__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Components</relationshipLabel>
    <relationshipName>Components</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Component__c/fields/ff_Pricing_structure__c.field-meta.xml
<CustomField>
    <fullName>ff_Pricing_structure__c</fullName>
    <label>Tiered Cost Rule</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not applicable</fullName>
                <label>General</label>
            </value>
            <value>
                <fullName>Cost Updates</fullName>
                <label>Tiered: Cost updates</label>
            </value>
            <value>
                <fullName>No Order Lines</fullName>
                <isActive>false</isActive>
                <label>No Order Lines</label>
            </value>
            <value>
                <fullName>No Cost Updates</fullName>
                <isActive>false</isActive>
                <label>Tiered: No Cost updates</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Component__c/fields/LinkedDeal_D_O_S__c.field-meta.xml
<CustomField>
    <fullName>LinkedDeal_D_O_S__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>LinkedDeal(D/O/S)</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Components (LinkedDeal(D/O/S))</relationshipLabel>
    <relationshipName>Components1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Component__c/fields/Product_FX_Pricing__c.field-meta.xml
<CustomField>
    <fullName>Product_FX_Pricing__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Currency</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Product_FX_Pricing__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product_FX_Pricing__c</referenceTo>
    <relationshipLabel>Components</relationshipLabel>
    <relationshipName>Components</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PIFSummary_Enabled__c.field-meta.xml
<CustomField>
    <fullName>PIFSummary_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PIFSummary Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Deal__c/Deal__c.object-meta.xml
<CustomObject>
    <label>Deal</label>
    <nameField>
        <label>Deal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal__c/fields/Allocation_by__c.field-meta.xml
<CustomField>
    <fullName>Allocation_by__c</fullName>
    <label>Allocation by</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Deal</fullName>
                <default>true</default>
                <label>Deal</label>
            </value>
            <value>
                <fullName>Option</fullName>
            </value>
            <value>
                <fullName>Sub option</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal__c/fields/BDM__c.field-meta.xml
<CustomField>
    <fullName>BDM__c</fullName>
    <label>BDM</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Maite De Hedervary</fullName>
            </value>
            <value>
                <fullName>Silvia Magnani</fullName>
            </value>
            <value>
                <fullName>Teige O&apos;Sullivan</fullName>
            </value>
            <value>
                <fullName>Alison Riordan</fullName>
            </value>
            <value>
                <fullName>Eamonn O&apos;Sullivan</fullName>
            </value>
            <value>
                <fullName>Rebecca Maitland</fullName>
            </value>
            <value>
                <fullName>Andrew Bennett</fullName>
            </value>
            <value>
                <fullName>Holly Littlewood</fullName>
            </value>
            <value>
                <fullName>Nicoline Dolman</fullName>
            </value>
            <value>
                <fullName>Emily Taylor</fullName>
            </value>
            <value>
                <fullName>Alanna Betz</fullName>
            </value>
            <value>
                <fullName>Ben Ellison</fullName>
            </value>
            <value>
                <fullName>Luke Hansell</fullName>
            </value>
            <value>
                <fullName>Laura Newman</fullName>
            </value>
            <value>
                <fullName>Peter Huff</fullName>
            </value>
            <value>
                <fullName>Lexi Graham</fullName>
            </value>
            <value>
                <fullName>Ayu Herawati</fullName>
            </value>
            <value>
                <fullName>Brett Lemish</fullName>
            </value>
            <value>
                <fullName>Pete Timbs</fullName>
            </value>
            <value>
                <fullName>Serena Brillanti</fullName>
            </value>
            <value>
                <fullName>Angelina Hackett</fullName>
            </value>
            <value>
                <fullName>Jeremy Hagan</fullName>
            </value>
            <value>
                <fullName>Paul Wards</fullName>
            </value>
            <value>
                <fullName>Trent Ellen</fullName>
            </value>
            <value>
                <fullName>Alexandra Chakos</fullName>
                <isActive>false</isActive>
                <label>Alexandra Chakos</label>
            </value>
            <value>
                <fullName>Amanda Tennant</fullName>
                <isActive>false</isActive>
                <label>Amanda Tennant</label>
            </value>
            <value>
                <fullName>Cameron Williams</fullName>
                <isActive>false</isActive>
                <label>Cameron Williams</label>
            </value>
            <value>
                <fullName>Chaiy Donati</fullName>
                <isActive>false</isActive>
                <label>Chaiy Donati</label>
            </value>
            <value>
                <fullName>Derek Test Dolan</fullName>
                <isActive>false</isActive>
                <label>Derek Test Dolan</label>
            </value>
            <value>
                <fullName>Ella Dixon</fullName>
                <isActive>false</isActive>
                <label>Ella Dixon</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal__c/fields/Deal_Status__c.field-meta.xml
<CustomField>
    <fullName>Deal_Status__c</fullName>
    <inlineHelpText>This field drives the status in the &quot;path&quot; at the top of the page to show the &quot;overall status&quot; of the deal.</inlineHelpText>
    <label>Deal Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BDM - Deal Draft In Progress</fullName>
                <default>true</default>
                <label>BDM - Deal Draft In Progress</label>
            </value>
            <value>
                <fullName>BDM - Submitted</fullName>
            </value>
            <value>
                <fullName>Plan &amp; Configure</fullName>
            </value>
            <value>
                <fullName>Submitted for Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>With_Publishing</fullName>
                <label>With Publishing</label>
            </value>
            <value>
                <fullName>Ready for Proofing</fullName>
            </value>
            <value>
                <fullName>Pre-Published</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
                <color>#57F17C</color>
                <label>Published</label>
            </value>
            <value>
                <fullName>Not Approved</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Analysis &amp; Approval</fullName>
                <isActive>false</isActive>
                <label>Analysis &amp; Approval</label>
            </value>
            <value>
                <fullName>BDM</fullName>
                <isActive>false</isActive>
                <label>BDM</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <isActive>false</isActive>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Marketing</fullName>
                <isActive>false</isActive>
                <label>Marketing</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal__c/fields/deal_type__c.field-meta.xml
<CustomField>
    <fullName>deal_type__c</fullName>
    <label>deal type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>travel</fullName>
            </value>
            <value>
                <fullName>cruise</fullName>
            </value>
            <value>
                <fullName>stay</fullName>
            </value>
            <value>
                <fullName>Siteminder Hotel</fullName>
            </value>
            <value>
                <fullName>Experiences</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal__c/fields/merchant_sharing_deadline__c.field-meta.xml
<CustomField>
    <fullName>merchant_sharing_deadline__c</fullName>
    <inlineHelpText>Number of days prior to departure that merchant will receive booking confirmation. If multi-merchant deal, please use the most restrictive deadline e.g 120 days instead of 90.</inlineHelpText>
    <label>Merchant Sharing Deadline - Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Deal__c/fields/site__c.field-meta.xml
<CustomField>
    <fullName>site__c</fullName>
    <label>Site</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_FX_Pricing__c/Product_FX_Pricing__c.object-meta.xml
<CustomObject>
    <description>This object is used in pricing products based on the FX rate set bay the CFO.</description>
    <label>Product FX Pricing</label>
    <nameField>
        <label>Product FX Pricing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product FX Pricing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/MP_ProfileDetailsOnCommunity_Test.cls
@istest
public class MP_ProfileDetailsOnCommunity_Test {
    
     @isTest(SeeAllData=true)
    static void testMethod2() {
        List<Id> usrList = new List<Id>();
        User testUser = [Select id,Name,contact.PIFSummary_Enabled__c ,Contact.Id,Contact.AccountId, Profile.Name from user where Profile.Name = 'Partner Community Plus User' AND isActive = true LIMIT 1];
        usrList.add(testUser.Id);
        Account testAcco = [Select id, name from Account where id =: testUser.Contact.AccountId LIMIT 1 ];
        
        List<RecordType> RCTProductPartner = TADUtils.getRecordType(Label.TAD_RT_Product_Partner);
        
        Set<String> accList = new Set<String>();
        Account acctBussiness = TestDataFactory.createBussinessAccount(RCTProductPartner[0].Id);   // Bussiness account Inserted
        acctBussiness.Merchant_Type__c='Multi Line Expense';
        insert acctBussiness;
        accList.add(acctBussiness.Id);
        
        List<RecordType> RCTTadDeal = TADUtils.getRecordType(Label.TAD_RT_TAD_Deal);
        Deal__c deal = TestDataFactory.createMerchantDeal(RCTTadDeal[0].Id , testAcco.Id );   // Deals created
        deal.Name = '1124';
        deal.deal_type__c = 'travel';
        deal.Deal_Status__c = 'Published';
        deal.Allocation_by__c= 'Deal';
        deal.site__c = 'AU';
        deal.BDM__c = 'Maite De Hedervary';
        deal.merchant_sharing_deadline__c = 30;
        insert deal;
        List<String> dealList = New List<String>();
        dealList.add(deal.Id);
        
        
        /*
        Product_FX_Pricing__c pfp = TestDataFactory.createPFXP();
        insert pfp;
        system.debug('pfp '+pfp);
        
        list<Component__c> complist = new list<Component__c> ();
        
        Component__c comp = TestDataFactory.cutomComponent(testAcco,null,pfp);
        comp.Deal__c = deal.Id;
        comp.LinkedDeal_D_O_S__c = deal.Id;
        comp.ff_Pricing_structure__c = 'Not applicable';
        insert comp;
        Profile profile = [Select id, name from profile where name='Partner Community Plus User'];
        List<User> testUsers = new List<User>();
        
        User u = new User();
        u.FirstName = 'Test';
        u.LastName = 'User';
        u.Email = 'test@tripadeal.com.au';
        u.CompanyName = 'tripadeal.com.au';
        u.Title = 'Test User';
        u.Username = 'test@tripadeal.com.au.test';
        u.Alias = 'testuser';
        u.CommunityNickname = 'Test User';
        u.TimeZoneSidKey = 'Australia/Sydney';
        u.LocaleSidKey = 'en_AU';
        u.EmailEncodingKey = 'ISO-8859-1';
        u.ProfileId = profile.id;
        u.LanguageLocaleKey = 'en_US';
        u.ContactId = cons[0].id;
        
        testUsers.add(u);
        
        insert testUsers;
        */
        
        MP_ProfileDetailsOnCommunity.mainWrapper testWrapper = new MP_ProfileDetailsOnCommunity.mainWrapper();
        Test.startTest(); 
        MP_ProfileDetailsOnCommunity.getUser();
        MP_ProfileDetailsOnCommunity.sendEmailEnable(testUser.Id,true,'9999999999');
        MP_ProfileDetailsOnCommunity.enablePIFSummary(testUser.Id,true);
        try{
          //  MP_ProfileDetailsOnCommunity.changePasswordEmail(testUsers[0].id);
        }catch(exception e){}
        Test.stopTest();  
    }
}