force-app/main/default/objects/Component__c/Component__c.object-meta.xml
<CustomObject>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Component__c/fields/BC_Required__c.field-meta.xml
<CustomField>
    <fullName>BC_Required__c</fullName>
    <label>BC Required</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Component__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Components</relationshipLabel>
    <relationshipName>Components</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Component__c/fields/LinkedDeal_D_O_S__c.field-meta.xml
<CustomField>
    <fullName>LinkedDeal_D_O_S__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>LinkedDeal(D/O/S)</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Components (LinkedDeal(D/O/S))</relationshipLabel>
    <relationshipName>Components1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Component__c/fields/Merchant_Name__c.field-meta.xml
<CustomField>
    <fullName>Merchant_Name__c</fullName>
    <label>Merchant Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Components</relationshipLabel>
    <relationshipName>Components</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Component__c/fields/MPT_JOIN__c.field-meta.xml
<CustomField>
    <fullName>MPT_JOIN__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Terms</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>MPT_JOIN__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Merchant_Name__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>MPT_JOIN__c</referenceTo>
    <relationshipLabel>Components</relationshipLabel>
    <relationshipName>Components</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal__c/Deal__c.object-meta.xml
<CustomObject>
    <label>Deal</label>
    <nameField>
        <label>Deal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal__c/fields/BC_Required__c.field-meta.xml
<CustomField>
    <fullName>BC_Required__c</fullName>
    <defaultValue>&apos;No&apos;</defaultValue>
    <label>BC Required</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Marketing_Cloud_Preferences__c/Marketing_Cloud_Preferences__c.object-meta.xml
<CustomObject>
    <label>Marketing Cloud Preferences</label>
    <nameField>
        <displayFormat>MAP-{00000000}</displayFormat>
        <label>Marketing Cloud Preferences Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Marketing Cloud Preferences</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketing_Cloud_Preferences__c/fields/AccountID__c.field-meta.xml
<CustomField>
    <fullName>AccountID__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>AccountID</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Marketing Cloud Preferences</relationshipLabel>
    <relationshipName>Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MPT_JOIN__c/MPT_JOIN__c.object-meta.xml
<CustomObject>
    <label>MPT_JOIN</label>
    <nameField>
        <label>MPT_JOIN  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MPT_JOINS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MPT_JOIN__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>MPT_JOINS</relationshipLabel>
    <relationshipName>MPT_JOINS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MPT_JOIN__c/fields/Component__c.field-meta.xml
<CustomField>
    <fullName>Component__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Component_MPTJoin Lookup Relationship</description>
    <label>Component</label>
    <referenceTo>Component__c</referenceTo>
    <relationshipLabel>MPT_JOINS</relationshipLabel>
    <relationshipName>MPT_JOINS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MPT_JOIN__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>MPT_JOINS</relationshipLabel>
    <relationshipName>MPT_JOINS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/dealMerchantInfoListController.cls
public class dealMerchantInfoListController {
    
    
    // This is the wrapper for dataTable Data
    public class dataTableRecs {
        @AuraEnabled  public List<sObject> recordsDataMerchant  {get;set;}
        @AuraEnabled  public List<sObject> recordsDataMerchantTerms  {get;set;}
    }
    
    @AuraEnabled
    public static dataTableRecs fetchDataToDisplay (String recId){
        
        dataTableRecs dt = new dataTableRecs();
        
        List<Component__c> componentDataList = [Select id , name , Merchant_Name__c  from Component__c where LinkedDeal_D_O_S__c =:recId];
        
        Set<Id> merchantIds = new Set<Id>();
        for(Component__c comp : componentDataList){
            merchantIds.add(comp.Merchant_Name__c);  
        }
        
        List<Account>  accList = [Select id , Name , Merchant_Type__c  ,c2g__CODAAccountTradingCurrency__c ,BC_Required__c  from Account where Id IN:merchantIds];
        dt.recordsDataMerchant= accList;
        
        List<MPT_JOIN__c>  mptList = [Select id , Account__r.Name  , Name ,CurrencyIsoCode,Account__c   from MPT_JOIN__c  where Account__c IN:merchantIds and deal__c =:recId ];
        dt.recordsDataMerchantTerms= mptList;
        
        return dt;
    }
    
}