force-app/main/default/objects/Component__c/Component__c.object-meta.xml
<CustomObject>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Component__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Components</relationshipLabel>
    <relationshipName>Components</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Component__c/fields/LinkedDeal_D_O_S__c.field-meta.xml
<CustomField>
    <fullName>LinkedDeal_D_O_S__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>LinkedDeal(D/O/S)</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Components (LinkedDeal(D/O/S))</relationshipLabel>
    <relationshipName>Components1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Component__c/fields/MPT_JOIN__c.field-meta.xml
<CustomField>
    <fullName>MPT_JOIN__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Terms</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>MPT_JOIN__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Merchant_Name__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>MPT_JOIN__c</referenceTo>
    <relationshipLabel>Components</relationshipLabel>
    <relationshipName>Components</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal__c/Deal__c.object-meta.xml
<CustomObject>
    <label>Deal</label>
    <nameField>
        <label>Deal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MPT_JOIN__c/MPT_JOIN__c.object-meta.xml
<CustomObject>
    <label>MPT_JOIN</label>
    <nameField>
        <label>MPT_JOIN  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MPT_JOINS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MPT_JOIN__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>MPT_JOINS</relationshipLabel>
    <relationshipName>MPT_JOINS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MPT_JOIN__c/fields/Component__c.field-meta.xml
<CustomField>
    <fullName>Component__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Component_MPTJoin Lookup Relationship</description>
    <label>Component</label>
    <referenceTo>Component__c</referenceTo>
    <relationshipLabel>MPT_JOINS</relationshipLabel>
    <relationshipName>MPT_JOINS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MPT_JOIN__c/fields/Currency_merchant__c.field-meta.xml
<CustomField>
    <fullName>Currency_merchant__c</fullName>
    <label>Currency</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MPT_JOIN__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>MPT_JOINS</relationshipLabel>
    <relationshipName>MPT_JOINS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MPT_JoinTriggerHandler.cls
public class MPT_JoinTriggerHandler {

    public static void updateCurrencyField(List<MPT_JOIN__c> mptList){
        
         Map<Id,String> accIdVsCurrency = new Map<Id,String>();
        Map<Id,String> accIdVsCurrency1 = new Map<Id,String>();
        List<Id> accIds = new List<Id>();
        List<Id> compIds = new List<Id>();
        
         for(MPT_JOIN__c mpt : mptList){
            if(mpt.Account__c != null){
                
                accIds.add(mpt.Account__c); 
            }
             if(mpt.Component__c != null){
                 
                 compIds.add(mpt.Component__c);
             }
           
        }
        
          List<Component__c> compList = [Select Id, LinkedDeal_D_O_S__c from Component__c where Id IN : compIds ];
        Map<Id,Id> compIdVsDealId = new Map<Id,Id>();
        
        for(Component__c c : compList){
            
           compIdVsDealId.put(c.Id, c.LinkedDeal_D_O_S__c);
        }
          List<Account> accList = [Select Id, toLabel(CurrencyIsoCode) from Account where Id IN: accIds];
        
          List<Account> accList1 = [Select Id, CurrencyIsoCode from Account where Id IN: accIds];
        
        System.debug('accList---'+accList);
        
        For(Account a : accList){
            
            accIdVsCurrency.put(a.Id, a.CurrencyIsoCode);
            
        }
        
         For(Account a1 : accList1){
            
            accIdVsCurrency1.put(a1.Id, a1.CurrencyIsoCode+' - '+accIdVsCurrency.get(a1.Id));
            
        }
         System.debug('accIdVsCurrency1---'+accIdVsCurrency1);
        for(MPT_JOIN__c mp : mptList){
           
            mp.Currency_merchant__c = accIdVsCurrency1.get(mp.Account__c);
            if(mp.Deal__c==null){
             mp.Deal__c = compIdVsDealId.get(mp.Component__c);
            }
           
            System.debug('compIdVsDealId.get(mp.Component__c)---'+compIdVsDealId.get(mp.Component__c));
        }
    }
}