force-app/main/default/objects/customer_POE__c/customer_POE__c.object-meta.xml
<CustomObject>
    <label>Passengers</label>
    <nameField>
        <displayFormat>PIF-{00000000}</displayFormat>
        <label>id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/customer_POE__c/fields/sabre_delete_profile__c.field-meta.xml
<CustomField>
    <fullName>sabre_delete_profile__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sabre Delete Profile</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/departures_dates__c.object-meta.xml
<CustomObject>
    <label>departures dates</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>departures dates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/departures_dates__c/fields/create_sabre_profiles__c.field-meta.xml
<CustomField>
    <fullName>create_sabre_profiles__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Create Sabre Profiles</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/create_sabre_profiles_date__c.field-meta.xml
<CustomField>
    <fullName>create_sabre_profiles_date__c</fullName>
    <label>Create Sabre Profiles Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/order__c/order__c.object-meta.xml
<CustomObject>
    <label>orders</label>
    <nameField>
        <displayFormat>{00}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>order</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/order__c/fields/departures_dates__c.field-meta.xml
<CustomField>
    <fullName>departures_dates__c</fullName>
    <label>Departure Date</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 OR 2 OR 3) AND (4 OR 5) AND ((6 AND 7) OR (8 AND 9)) AND 10</booleanFilter>
        <errorMessage>departure date - Value does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>departures_dates__c.sub_options__c</field>
            <operation>equals</operation>
            <valueField>$Source.Sub_Options__c</valueField>
        </filterItems>
        <filterItems>
            <field>departures_dates__c.options__c</field>
            <operation>equals</operation>
            <valueField>$Source.Options__c</valueField>
        </filterItems>
        <filterItems>
            <field>departures_dates__c.Deal__c</field>
            <operation>equals</operation>
            <valueField>$Source.deal__c</valueField>
        </filterItems>
        <filterItems>
            <field>departures_dates__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>departures_dates__c.recently_expired__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>departures_dates__c.NRMA_Date__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.Referrer__c</field>
            <operation>notEqual</operation>
            <value>NRMA</value>
        </filterItems>
        <filterItems>
            <field>$Source.Referrer__c</field>
            <operation>equals</operation>
            <value>NRMA</value>
        </filterItems>
        <filterItems>
            <field>departures_dates__c.NRMA_Date__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>departures_dates__c.order_filter__c</field>
            <operation>contains</operation>
            <valueField>$Source.order_record_type_name__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>departures_dates__c</referenceTo>
    <relationshipLabel>order</relationshipLabel>
    <relationshipName>order</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/order__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <formula>Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/order__c/recordTypes/TripADeal.recordType-meta.xml
<RecordType>
    <fullName>TripADeal</fullName>
    <active>true</active>
    <label>TripADeal</label>
</RecordType>

force-app/main/default/objects/PNR_POE__c/PNR_POE__c.object-meta.xml
<CustomObject>
    <label>PNR</label>
    <nameField>
        <label>PNR Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PNR</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PNR_POE__c/fields/TAD_Order__c.field-meta.xml
<CustomField>
    <fullName>TAD_Order__c</fullName>
    <label>TAD Order</label>
    <referenceTo>TAD_Order__c</referenceTo>
    <relationshipLabel>PNR (POE)</relationshipLabel>
    <relationshipName>PNR_POE</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/TAD_Order__c.object-meta.xml
<CustomObject>
    <label>TAD Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TAD Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TAD_Order__c/fields/order__c.field-meta.xml
<CustomField>
    <fullName>order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>orders</label>
    <referenceTo>order__c</referenceTo>
    <relationshipLabel>TAD Orders</relationshipLabel>
    <relationshipName>TAD_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_departure_date__c.field-meta.xml
<CustomField>
    <fullName>ordexp_departure_date__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Departure date</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>(1 OR 2) AND 3</booleanFilter>
        <filterItems>
            <field>departures_dates__c.Deal__c</field>
            <operation>equals</operation>
            <valueField>$Source.ordexp_deal__c</valueField>
        </filterItems>
        <filterItems>
            <field>departures_dates__c.options__c</field>
            <operation>equals</operation>
            <valueField>$Source.ordexp_option__c</valueField>
        </filterItems>
        <filterItems>
            <field>departures_dates__c.online_status__c</field>
            <operation>equals</operation>
            <value>Online</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>departures_dates__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>TAD_Orders_DD</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_master_status__c.field-meta.xml
<CustomField>
    <fullName>ordexp_master_status__c</fullName>
    <label>Master status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
                <default>true</default>
                <label>On Hold</label>
            </value>
            <value>
                <fullName>Temporary Hold</fullName>
            </value>
            <value>
                <fullName>Secured</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Travelled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>In Progress-Cruise only</fullName>
                <isActive>false</isActive>
                <label>In Progress-Cruise only</label>
            </value>
            <value>
                <fullName>In Progress-Flight only</fullName>
                <isActive>false</isActive>
                <label>In Progress-Flight only</label>
            </value>
            <value>
                <fullName>In Progress-Flights + Cruise</fullName>
                <isActive>false</isActive>
                <label>In Progress-Flights + Cruise</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_sabre_delete_group_profile__c.field-meta.xml
<CustomField>
    <fullName>ordexp_sabre_delete_group_profile__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sabre delete group profile</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_sabre_group_profile_uid__c.field-meta.xml
<CustomField>
    <fullName>ordexp_sabre_group_profile_uid__c</fullName>
    <label>Sabre group profile uid</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ScheduleDeleteSabreProfiles.cls
global class ScheduleDeleteSabreProfiles implements Schedulable {

    global void execute(SchedulableContext ctx) {

        //Make sure this is run before 12am maybe aim for 9pm
        Date today = Date.today();
        Map<Id,departures_dates__c> dds = new Map<Id, departures_dates__c>([SELECT Id, Name, create_sabre_profiles__c, create_sabre_profiles_date__c FROM departures_dates__c WHERE create_sabre_profiles_date__c = :today]);
        Map<Id,tad_order__c> orders = new Map<Id, tad_order__c>([SELECT Id, Name, ordexp_master_status__c, ordexp_sabre_delete_group_profile__c, ordexp_sabre_group_profile_uid__c, ordexp_departure_date__c FROM tad_order__c WHERE ordexp_departure_date__c IN :dds.keySet()
        AND ordexp_master_status__c IN ('In Progress', 'Secured')]);
        Map<Id,PNR_POE__c> pnrs = new Map<Id,PNR_POE__c>([SELECT Id, tad_Order__c FROM PNR_POE__c WHERE tad_Order__c IN :orders.keySet()]);
        Set<Id> ordersWithPNRs = new Set<Id>();
        for (Id key : pnrs.keySet()) {
            ordersWithPNRs.add(pnrs.get(key).tad_Order__c);
        }

        List<tad_order__c> ordersToRemoveProfiles = new List<tad_order__c>();
        Set<Id> orderIdsForPaxToRemove = new Set<Id>();
        for (Id oKey : orders.keySet()) {
            tad_order__c o = orders.get(oKey);
            if (ordersWithPNRs.contains(o.Id)) {
                // do nothing
            } else {
                // Set changes in the batch class
                ordersToRemoveProfiles.add(o);
                orderIdsForPaxToRemove.add(o.Id);
            }
        }

        // This section is now covered by workato
        //Map<Id,customer_POE__c> passengers = new Map<Id,customer_POE__c>([SELECT Id, sabre_delete_profile__c, order__c FROM customer_POE__c WHERE order__c IN :orderIdsForPaxToRemove]);
        //for (Id key : passengers.keySet()) {
        //    passengers.get(key).sabre_delete_profile__c = true;
        //}
        //update passengers.values();

        String sub = 'Orders to with no PNR';
        String body = ordersToRemoveProfiles.size() > 0 ? '' : 'I got nothing';

        Set<Id> oIds = new Set<Id>();

        for (tad_order__c o : ordersToRemoveProfiles) {
            body += '<a href="https://tripadeal.my.salesforce.com/' + o.Id + '">' + o.Name +
                    ' | dep date and id' + dds.get(o.ordexp_departure_date__c).Name + ' - ' + dds.get(o.ordexp_departure_date__c).Id +
                    ' | profile push date? ' + dds.get(o.ordexp_departure_date__c).create_sabre_profiles_date__c +
                    ' | delete? ' + o.ordexp_sabre_delete_group_profile__c + '</a><br>';

            oIds.add(o.Id);
        }

        sendEmailToDev(sub,body);

        // Batch stuff here
        if (oIds.size() > 0) {

            String idString = '';

            for (Id id : oIds) {
                idString = idString + '\'' + id + '\',';
            }

            String q = 'SELECT Id, ordexp_sabre_delete_group_profile__c FROM tad_order__c WHERE Id IN (' + idString.left(idString.length() - 1) + ')';
            BatchordercDeleteSabreProfiles batch = new BatchordercDeleteSabreProfiles(q);
            Database.executeBatch(batch, 5);

        }
        // batch stuff to here

        // failed when too many orders... and needed batch.
        //update ordersToRemoveProfiles;
 
    }

  
   private void sendEmailToDev(String subject, String mailBody ) {
        List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        List<String> sendTo = new List<String>();
        sendTo.add('peter.russell@tripadeal.com.au');
        mail.setToAddresses(sendTo);
        mail.setSenderDisplayName('PAI Schedule Delete Sabre Profiles');
        mail.setSubject(subject);
        mail.setPlainTextBody(mailBody);
        mails.add(mail);
        Messaging.sendEmail(mails);
    }
}