force-app/main/default/objects/customer_POE__c/customer_POE__c.object-meta.xml
<CustomObject>
    <label>Passengers</label>
    <nameField>
        <displayFormat>PIF-{00000000}</displayFormat>
        <label>id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/customer_POE__c/fields/first_name__c.field-meta.xml
<CustomField>
    <fullName>first_name__c</fullName>
    <label>First Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/customer_POE__c/fields/last_name__c.field-meta.xml
<CustomField>
    <fullName>last_name__c</fullName>
    <label>Last Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/customer_POE__c/fields/Order_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Order_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Line Item</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>order_line_item__c.ordexp_TAD_Order__c</field>
            <operation>equals</operation>
            <valueField>$Source.ordexp_tad_order__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>order_line_item__c</referenceTo>
    <relationshipLabel>Passengers</relationshipLabel>
    <relationshipName>Passengers_POE</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/customer_POE__c/fields/ordexp_tad_order__c.field-meta.xml
<CustomField>
    <fullName>ordexp_tad_order__c</fullName>
    <label>TAD Order</label>
    <referenceTo>TAD_Order__c</referenceTo>
    <relationshipLabel>Passengers</relationshipLabel>
    <relationshipName>Passengers_POE</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/departures_dates__c.object-meta.xml
<CustomObject>
    <label>departures dates</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>departures dates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/departures_dates__c/fields/date__c.field-meta.xml
<CustomField>
    <fullName>date__c</fullName>
    <label>date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/Nights__c.field-meta.xml
<CustomField>
    <fullName>Nights__c</fullName>
    <formula>IF(options__c!=null, options__r.NIghts__c,  IF( sub_options__c!=null, sub_options__r.options__r.NIghts__c,0) )</formula>
    <label>Nights</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/ordexp_return_date__c.field-meta.xml
<CustomField>
    <fullName>ordexp_return_date__c</fullName>
    <formula>IF (  Nights__c  
 &gt; 0,(date__c+Nights__c)-1,IF ( Deal_for_Reporting__r.number_of_days__c
 &gt; 0, date__c + (Deal_for_Reporting__r.number_of_days__c
 - 1), date__c + (Deal_for_Reporting__r.number_of_days__c
 - 1)
))</formula>
    <label>Return Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/options__c/options__c.object-meta.xml
<CustomObject>
    <label>Options</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/options__c/fields/NIghts__c.field-meta.xml
<CustomField>
    <fullName>NIghts__c</fullName>
    <label>NIghts</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/order_line_item__c/order_line_item__c.object-meta.xml
<CustomObject>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>OLI-{000000}</displayFormat>
        <label>Order Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/order_line_item__c/fields/ordexp_departure_date__c.field-meta.xml
<CustomField>
    <fullName>ordexp_departure_date__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Note :- For Stay type Orders, change to Departure Date will be applied to all the OLIs of this Order</inlineHelpText>
    <label>Departure date</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>departures_dates__c.sub_options__c</field>
            <operation>equals</operation>
            <valueField>$Source.Sub_Options__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>departures_dates__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/order_line_item__c/fields/ordexp_TAD_Order__c.field-meta.xml
<CustomField>
    <fullName>ordexp_TAD_Order__c</fullName>
    <label>Order</label>
    <referenceTo>TAD_Order__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items_orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/order_line_item__c/fields/PAX_Quantity__c.field-meta.xml
<CustomField>
    <fullName>PAX_Quantity__c</fullName>
    <label>PAX Quantity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>26</fullName>
                <isActive>false</isActive>
                <label>26</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TAD_Order__c/TAD_Order__c.object-meta.xml
<CustomObject>
    <label>TAD Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TAD Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TAD_Order__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <formula>IF(ordexp_account__r.IsPersonAccount ,   ordexp_account__r.PersonContact.FirstName +&apos; &apos;+ ordexp_account__r.PersonContact.LastName    ,  ordexp_account__r.Name )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/BNCDL_Order__c.field-meta.xml
<CustomField>
    <fullName>BNCDL_Order__c</fullName>
    <formula>ordexp_departure_date__r.BNCDL__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>BNCDL Order</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <formula>ordexp_account__r.FirstName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>First Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/Is_Siteminder_TravelClick__c.field-meta.xml
<CustomField>
    <fullName>Is_Siteminder_TravelClick__c</fullName>
    <formula>IF(AND(
ordexp_deal__r.RecordType.Name = &quot;Hotel&quot;,
NOT(ISNULL(TEXT(ordexp_deal__r.Channel_Partner__c)))
),&quot;Yes&quot;, &quot;No&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Result of this field = Is this a Siteminder or TravelClick deal?</inlineHelpText>
    <label>Is Siteminder/TravelClick?</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/OLI_Count_Confirmed__c.field-meta.xml
<CustomField>
    <fullName>OLI_Count_Confirmed__c</fullName>
    <label>OLI Count (Confirmed)</label>
    <summaryFilterItems>
        <field>order_line_item__c.OLI_Status__c</field>
        <operation>notEqual</operation>
        <value>Cancelled</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>order_line_item__c.OLI_Status__c</field>
        <operation>notEqual</operation>
        <value>On Hold</value>
    </summaryFilterItems>
    <summaryForeignKey>order_line_item__c.ordexp_TAD_Order__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_account__c.field-meta.xml
<CustomField>
    <fullName>ordexp_account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>TAD Orders</relationshipLabel>
    <relationshipName>TAD_Orders_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_dataloadrefresh__c.field-meta.xml
<CustomField>
    <fullName>ordexp_dataloadrefresh__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DataLoadRefresh</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_departure_date__c.field-meta.xml
<CustomField>
    <fullName>ordexp_departure_date__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Departure date</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>(1 OR 2) AND 3</booleanFilter>
        <filterItems>
            <field>departures_dates__c.Deal__c</field>
            <operation>equals</operation>
            <valueField>$Source.ordexp_deal__c</valueField>
        </filterItems>
        <filterItems>
            <field>departures_dates__c.options__c</field>
            <operation>equals</operation>
            <valueField>$Source.ordexp_option__c</valueField>
        </filterItems>
        <filterItems>
            <field>departures_dates__c.online_status__c</field>
            <operation>equals</operation>
            <value>Online</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>departures_dates__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>TAD_Orders_DD</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_master_status__c.field-meta.xml
<CustomField>
    <fullName>ordexp_master_status__c</fullName>
    <label>Master status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
                <default>true</default>
                <label>On Hold</label>
            </value>
            <value>
                <fullName>Temporary Hold</fullName>
            </value>
            <value>
                <fullName>Secured</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Travelled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>In Progress-Cruise only</fullName>
                <isActive>false</isActive>
                <label>In Progress-Cruise only</label>
            </value>
            <value>
                <fullName>In Progress-Flight only</fullName>
                <isActive>false</isActive>
                <label>In Progress-Flight only</label>
            </value>
            <value>
                <fullName>In Progress-Flights + Cruise</fullName>
                <isActive>false</isActive>
                <label>In Progress-Flights + Cruise</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_option__c.field-meta.xml
<CustomField>
    <fullName>ordexp_option__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Option</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>options__c.Deal__c</field>
            <operation>equals</operation>
            <valueField>$Source.ordexp_deal__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>options__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>TAD_Orders_Options</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_return_date__c.field-meta.xml
<CustomField>
    <fullName>ordexp_return_date__c</fullName>
    <label>Return date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/Siteminder_Reservation_ResId__c.field-meta.xml
<CustomField>
    <fullName>Siteminder_Reservation_ResId__c</fullName>
    <label>Channel Reservation ResId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/sm_End_Date__c.field-meta.xml
<CustomField>
    <fullName>sm_End_Date__c</fullName>
    <description>site minder end date</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/sm_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>sm_Start_Date__c</fullName>
    <description>Site Minder Start Date</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/recordTypes/TAD.recordType-meta.xml
<RecordType>
    <fullName>TAD</fullName>
    <active>true</active>
    <label>TAD</label>
</RecordType>

force-app/main/default/classes/batchSiteminderConfirmationTADOrder.cls
global class batchSiteminderConfirmationTADOrder implements Database.Batchable<sObject> {
    
    global Database.QueryLocator start(Database.BatchableContext bc){
        
        Set<String> orderStatuses = new Set<String>();
        orderStatuses.add('In Progress');
        orderStatuses.add('Secured');
        
        return Database.getQueryLocator([Select id,ordexp_option__r.NIghts__c,name,ordexp_account__r.firstname,ordexp_account__r.lastname,sm_Start_Date__c ,ordexp_dataloadrefresh__c ,sm_End_Date__c ,ordexp_departure_date__r.date__c,ordexp_departure_date__r.ordexp_return_date__c  from TAD_order__c where Is_Siteminder_TravelClick__c = 'Yes' AND Siteminder_Reservation_ResId__c =null AND ordexp_master_status__c IN:orderStatuses AND BNCDL_Order__c =false AND OLI_Count_Confirmed__c >0]);
    }
    
    global void execute(Database.BatchableContext bc,List<TAD_order__c> scope){
        
        TAD_order__c tad = scope[0];
        
        List<order_line_item__c> oli = [Select id,PAX_Quantity__c ,ordexp_tad_order__r.Account_Name__c,ordexp_tad_order__c ,(Select id , first_name__c ,last_name__c ,dob__c   from Passengers_POE__r) from  order_line_item__c where ordexp_TAD_Order__c =: tad.id ];
        
        List<customer_POE__c> poeToInsert = new List<customer_POE__c>();
        List<customer_POE__c> poeToUpdate = new List<customer_POE__c>();
        
        for(order_line_item__c ol : oli){
            Integer paxBalance = Integer.valueOf(ol.PAX_Quantity__c)-ol.Passengers_POE__r.size();
            
            if(paxBalance > 0){
                for(Integer i = 1 ;i<=paxBalance;i++){
                    customer_POE__c poe = new customer_POE__c();
                    poe.first_name__c = tad.ordexp_account__r.firstname;
                    poe.last_name__c = tad.ordexp_account__r.lastname;
                    poe.dob__c  ='01/01/1901';
                    poe.ordexp_tad_order__c = ol.ordexp_tad_order__c;
                    poe.Order_Line_Item__c = ol.id;  
                    poeToInsert.add(poe);
                }
            }
            
            for(customer_POE__c pax : ol.Passengers_POE__r){
                pax.first_name__c = tad.ordexp_account__r.firstname;
                pax.last_name__c = tad.ordexp_account__r.lastname;
                pax.dob__c  ='01/01/1901';
                poeToUpdate.add(pax); 
            }
            
        }
        if(!poeToInsert.isEmpty()){
            insert poeToInsert;  
        }
        if(!poeToUpdate.isEmpty()){
            update poeToUpdate;  
        }
        
        
        System.debug('Start'+tad.ordexp_departure_date__r.date__c);
        System.debug('End'+tad.ordexp_departure_date__r.ordexp_return_date__c);
        
        if( tad.ordexp_option__r.NIghts__c != null){
            tad.sm_Start_Date__c=tad.ordexp_departure_date__r.date__c;
            tad.sm_End_Date__c=tad.ordexp_departure_date__r.date__c.addDays(Integer.valueof(tad.ordexp_option__r.NIghts__c));
            if(tad.ordexp_dataloadrefresh__c==true){
                tad.ordexp_dataloadrefresh__c = false;
            }else{
                tad.ordexp_dataloadrefresh__c = true;
            }
            update tad; 
        }
    }
    
    global void finish(Database.BatchableContext BC) {
        
    }
}