force-app/main/default/objects/customer_POE__c/customer_POE__c.object-meta.xml
<CustomObject>
    <label>Passengers</label>
    <nameField>
        <displayFormat>PIF-{00000000}</displayFormat>
        <label>id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/customer_POE__c/fields/clean_first_name__c.field-meta.xml
<CustomField>
    <fullName>clean_first_name__c</fullName>
    <formula>SUBSTITUTE(
SUBSTITUTE( first_name__c , &quot;-&quot;, &quot;&quot;), &quot;&apos;&quot;, &quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Clean First Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/customer_POE__c/fields/first_name__c.field-meta.xml
<CustomField>
    <fullName>first_name__c</fullName>
    <label>First Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/customer_POE__c/fields/last_name__c.field-meta.xml
<CustomField>
    <fullName>last_name__c</fullName>
    <label>Last Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/customer_POE__c/fields/ordexp_tad_order__c.field-meta.xml
<CustomField>
    <fullName>ordexp_tad_order__c</fullName>
    <label>TAD Order</label>
    <referenceTo>TAD_Order__c</referenceTo>
    <relationshipLabel>Passengers</relationshipLabel>
    <relationshipName>Passengers_POE</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/customer_POE__c/fields/Passenger_Name__c.field-meta.xml
<CustomField>
    <fullName>Passenger_Name__c</fullName>
    <formula>first_name__c&amp;&quot; &quot;&amp;last_name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Passenger_Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/customer_POE__c/fields/second_name__c.field-meta.xml
<CustomField>
    <fullName>second_name__c</fullName>
    <inlineHelpText>Please leave blank if not applicable</inlineHelpText>
    <label>Second Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PAX_Segment_Links__c/PAX_Segment_Links__c.object-meta.xml
<CustomObject>
    <label>PAX Segment Links</label>
    <nameField>
        <displayFormat>PSL-{0000}</displayFormat>
        <label>PAX Segment Links Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PAX Segment Links</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PAX_Segment_Links__c/fields/Passengers__c.field-meta.xml
<CustomField>
    <fullName>Passengers__c</fullName>
    <label>Passengers</label>
    <referenceTo>customer_POE__c</referenceTo>
    <relationshipLabel>PAX Segment Links</relationshipLabel>
    <relationshipName>PAX_Segment_Links</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PAX_Segment_Links__c/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <label>Segment</label>
    <referenceTo>Segment_POE__c</referenceTo>
    <relationshipLabel>PAX Segment Links</relationshipLabel>
    <relationshipName>PAX_Segment_Links</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PNR__c/PNR__c.object-meta.xml
<CustomObject>
    <label>PNR (Old)</label>
    <nameField>
        <label>PNR Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PNR (Old)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PNR_Accounting_Line_POE__c/PNR_Accounting_Line_POE__c.object-meta.xml
<CustomObject>
    <label>PNR Accounting Line</label>
    <nameField>
        <displayFormat>PAL-{000000000}</displayFormat>
        <label>PNR Accounting Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PNR Accounting Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PNR_Accounting_Line_POE__c/fields/passenger_name__c.field-meta.xml
<CustomField>
    <fullName>passenger_name__c</fullName>
    <label>Passenger Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PNR_Accounting_Line_POE__c/fields/pnr__c.field-meta.xml
<CustomField>
    <fullName>pnr__c</fullName>
    <label>PNR</label>
    <referenceTo>PNR_POE__c</referenceTo>
    <relationshipLabel>PNR Accounting Lines</relationshipLabel>
    <relationshipName>PNR_Accounting_Lines_POE</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PNR_POE__c/PNR_POE__c.object-meta.xml
<CustomObject>
    <label>PNR</label>
    <nameField>
        <label>PNR Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PNR</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PNR_POE__c/fields/TAD_Order__c.field-meta.xml
<CustomField>
    <fullName>TAD_Order__c</fullName>
    <label>TAD Order</label>
    <referenceTo>TAD_Order__c</referenceTo>
    <relationshipLabel>PNR (POE)</relationshipLabel>
    <relationshipName>PNR_POE</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Segment__c/Segment__c.object-meta.xml
<CustomObject>
    <label>Segment (Old)</label>
    <nameField>
        <displayFormat>SG{00000000}</displayFormat>
        <label>Segment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segments (Old)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Segment__c/fields/PNR__c.field-meta.xml
<CustomField>
    <fullName>PNR__c</fullName>
    <label>PNR</label>
    <referenceTo>PNR__c</referenceTo>
    <relationshipLabel>Segments</relationshipLabel>
    <relationshipName>Segments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Segment_POE__c/Segment_POE__c.object-meta.xml
<CustomObject>
    <label>Segment</label>
    <nameField>
        <displayFormat>SG{00000000}</displayFormat>
        <label>Segment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Segment_POE__c/fields/PNR__c.field-meta.xml
<CustomField>
    <fullName>PNR__c</fullName>
    <label>PNR</label>
    <referenceTo>PNR_POE__c</referenceTo>
    <relationshipLabel>Segments</relationshipLabel>
    <relationshipName>Segments_POE</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/TAD_Order__c.object-meta.xml
<CustomObject>
    <label>TAD Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TAD Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TAD_Order__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <formula>ordexp_account__r.FirstName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>First Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <formula>ordexp_account__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Last Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PNRAccountingLinePOETriggerHandler.cls
public class PNRAccountingLinePOETriggerHandler {
   
    public static void createPAXSegmentLinkRecord(List<PNR_Accounting_Line_POE__c> listOfAccountingLines){
       
        Set<Id> setOfPNRIds = new Set<Id>();
        Set<String> firstNamesSet = new Set<String>();
        Set<String> lastNamesSet = new Set<String>();
       
        for(PNR_Accounting_Line_POE__c pal : listOfAccountingLines){
            setOfPNRIds.add(pal.pnr__c);
            String paxNameInstance = pal.passenger_name__c;
            if(!paxNameInstance.contains('/')){
                List<String> nameSplit = paxNameInstance.split(' ');
                firstNamesSet.add(nameSplit[1]);
                lastNamesSet.add(nameSplit[0]);
            }else{
                List<String> nameSplit = paxNameInstance.split('/');
                List<String> strLocalList = nameSplit[1].split(' ');
                firstNamesSet.add(strLocalList[0]);
                lastNamesSet.add(nameSplit[0]);
            }    
        }
       system.debug('firstNamesSet:'+firstNamesSet+'lastNamesSet:'+lastNamesSet);
        List<Segment_POE__c> listOfAssocatedSegments = [Select id, PNR__c, PNR__r.TAD_Order__c from Segment_POE__c where PNR__c in:setOfPNRIds];
        Map<String, List<Segment_POE__c>> mapOfOrderAgainstSegment = new Map<String, List<Segment_POE__c>>();
        Set<Id> orderIds = new Set<Id>();
       
        for(Segment_POE__c seg : listOfAssocatedSegments){
            orderIds.add(seg.PNR__r.TAD_Order__c);
            if(mapOfOrderAgainstSegment.containsKey(seg.PNR__r.TAD_Order__c)){
                List<Segment_POE__c> getExistingList = mapOfOrderAgainstSegment.get(seg.PNR__r.TAD_Order__c);
                getExistingList.add(seg);
            }else{
                List<Segment_POE__c> newListOfSegments = new List<Segment_POE__c>();
                newListOfSegments.add(seg);
                mapOfOrderAgainstSegment.put(seg.PNR__r.TAD_Order__c, newListOfSegments);
            }
        }
        List<customer_POE__c> listOfPAX = [Select id, Name, first_name__c, second_name__c, last_name__c, Passenger_Name__c,ordexp_tad_order__c from customer_POE__c where clean_first_name__c in:firstNamesSet AND clean_last_name__c in:lastNamesSet and ordexp_tad_order__c in:orderIds];
       
        Map<String, List<customer_POE__c>> mapOfOrderAgainstPAX = new Map<String, List<customer_POE__c>>();
        for(customer_POE__c cus : listOfPAX){
            if(mapOfOrderAgainstPAX.containsKey(cus.ordexp_tad_order__c)){
                List<customer_POE__c> getExistingList = mapOfOrderAgainstPAX.get(cus.ordexp_tad_order__c);
                getExistingList.add(cus);
            }else{
                List<customer_POE__c> newListOfPAX = new List<customer_POE__c>();
                newListOfPAX.add(cus);
                mapOfOrderAgainstPAX.put(cus.ordexp_tad_order__c, newListOfPAX);
            }
        }
       
       Map<String, List<Segment_POE__c>> mapOfPAXIdWithSegmentList = new Map<String, List<Segment_POE__c>>();
        for(String paxKey : mapOfOrderAgainstPAX.keySet()){
            for(customer_POE__c cus : mapOfOrderAgainstPAX.get(paxKey)){
                if(mapOfOrderAgainstSegment.containsKey(paxKey)){
                    mapOfPAXIdWithSegmentList.put(cus.Id, mapOfOrderAgainstSegment.get(paxKey));
                }
            }
        }
       
        List<PAX_Segment_Links__c> listToInsertJunctionRecords = new List<PAX_Segment_Links__c>();
        if(mapOfPAXIdWithSegmentList != null){
            for(String str : mapOfPAXIdWithSegmentList.keySet()){
                for(Segment_POE__c seg : mapOfPAXIdWithSegmentList.get(str)){
                    PAX_Segment_Links__c paxSegmentLinkInstance = new PAX_Segment_Links__c();
                    paxSegmentLinkInstance.Segment__c = seg.Id;
                    paxSegmentLinkInstance.Passengers__c = str;
                    listToInsertJunctionRecords.add(paxSegmentLinkInstance);
                }
            }
        }
       
        if(!listToInsertJunctionRecords.isEmpty()){
            insert listToInsertJunctionRecords;
        }
       
    }  
}