force-app/main/default/objects/customer_POE__c/customer_POE__c.object-meta.xml
<CustomObject>
    <label>Passengers</label>
    <nameField>
        <displayFormat>PIF-{00000000}</displayFormat>
        <label>id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/customer_POE__c/fields/Order_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Order_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Line Item</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>order_line_item__c.ordexp_TAD_Order__c</field>
            <operation>equals</operation>
            <valueField>$Source.ordexp_tad_order__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>order_line_item__c</referenceTo>
    <relationshipLabel>Passengers</relationshipLabel>
    <relationshipName>Passengers_POE</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal__c/Deal__c.object-meta.xml
<CustomObject>
    <label>Deal</label>
    <nameField>
        <label>Deal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal__c/fields/Allocation_by__c.field-meta.xml
<CustomField>
    <fullName>Allocation_by__c</fullName>
    <label>Allocation by</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Deal</fullName>
                <default>true</default>
                <label>Deal</label>
            </value>
            <value>
                <fullName>Option</fullName>
            </value>
            <value>
                <fullName>Sub option</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/departure_cities__c/departure_cities__c.object-meta.xml
<CustomObject>
    <label>departure cities</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>departure cities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/departure_cities__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>departure cities</relationshipLabel>
    <relationshipName>departure_cities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/departures_dates__c.object-meta.xml
<CustomObject>
    <label>departures dates</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>departures dates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/departures_dates__c/fields/date__c.field-meta.xml
<CustomField>
    <fullName>date__c</fullName>
    <label>date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>departures dates</relationshipLabel>
    <relationshipName>departures_dates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/sub_options__c.field-meta.xml
<CustomField>
    <fullName>sub_options__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>sub options</label>
    <referenceTo>sub_options__c</referenceTo>
    <relationshipLabel>departures dates</relationshipLabel>
    <relationshipName>departures_dates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/order_line_item__c/order_line_item__c.object-meta.xml
<CustomObject>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>OLI-{000000}</displayFormat>
        <label>Order Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/order_line_item__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/order_line_item__c/fields/ordexp_departure_date__c.field-meta.xml
<CustomField>
    <fullName>ordexp_departure_date__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Note :- For Stay type Orders, change to Departure Date will be applied to all the OLIs of this Order</inlineHelpText>
    <label>Departure date</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>departures_dates__c.sub_options__c</field>
            <operation>equals</operation>
            <valueField>$Source.Sub_Options__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>departures_dates__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/order_line_item__c/fields/ordexp_Options__c.field-meta.xml
<CustomField>
    <fullName>ordexp_Options__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Options</label>
    <referenceTo>options__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/order_line_item__c/fields/PAX_Quantity__c.field-meta.xml
<CustomField>
    <fullName>PAX_Quantity__c</fullName>
    <label>PAX Quantity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>26</fullName>
                <isActive>false</isActive>
                <label>26</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/order_line_item__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>26</fullName>
                <isActive>false</isActive>
                <label>26</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/order_line_item__c/fields/Sub_Options__c.field-meta.xml
<CustomField>
    <fullName>Sub_Options__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Note :-  For Stay type Orders, change to Sub-Option will be applied to all the OLIs of this Order</inlineHelpText>
    <label>Sub Options</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>sub_options__c.options__c</field>
            <operation>equals</operation>
            <valueField>$Source.ordexp_Options__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>sub_options__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sub_options__c/sub_options__c.object-meta.xml
<CustomObject>
    <label>Sub Options</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/sub_options__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Sub Options</relationshipLabel>
    <relationshipName>Sub_Options</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/TAD_Order__c.object-meta.xml
<CustomObject>
    <label>TAD Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TAD Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_account__c.field-meta.xml
<CustomField>
    <fullName>ordexp_account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>TAD Orders</relationshipLabel>
    <relationshipName>TAD_Orders_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_deal__c.field-meta.xml
<CustomField>
    <fullName>ordexp_deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>TAD_Orders_Deal</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_departure_date__c.field-meta.xml
<CustomField>
    <fullName>ordexp_departure_date__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Departure date</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>(1 OR 2) AND 3</booleanFilter>
        <filterItems>
            <field>departures_dates__c.Deal__c</field>
            <operation>equals</operation>
            <valueField>$Source.ordexp_deal__c</valueField>
        </filterItems>
        <filterItems>
            <field>departures_dates__c.options__c</field>
            <operation>equals</operation>
            <valueField>$Source.ordexp_option__c</valueField>
        </filterItems>
        <filterItems>
            <field>departures_dates__c.online_status__c</field>
            <operation>equals</operation>
            <value>Online</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>departures_dates__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>TAD_Orders_DD</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_option__c.field-meta.xml
<CustomField>
    <fullName>ordexp_option__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Option</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>options__c.Deal__c</field>
            <operation>equals</operation>
            <valueField>$Source.ordexp_deal__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>options__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>TAD_Orders_Options</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <summarizedField>order_line_item__c.ff_PerQTY_PAX_Count__c</summarizedField>
    <summaryForeignKey>order_line_item__c.ordexp_TAD_Order__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/recordTypes/TAD.recordType-meta.xml
<RecordType>
    <fullName>TAD</fullName>
    <active>true</active>
    <label>TAD</label>
</RecordType>

force-app/main/default/objects/TAD_Order__c/recordTypes/TNZ.recordType-meta.xml
<RecordType>
    <fullName>TNZ</fullName>
    <active>true</active>
    <label>TNZ</label>
</RecordType>

force-app/main/default/classes/MobileAppTADOrderCreation.cls
@RestResource(urlmapping='/settingAppTADOrderCreation')
global class MobileAppTADOrderCreation {
    
    global class mainWrapper{
        global String orderId{get;set;}
        //global String personAccountId{get;set;}
        global String dealId{get;set;}
        global String dealCountry{get;set;}
        global String optionsId{get;set;}
        global String departureDateId{get;set;}
        global String travelType{get;set;}
        
        global String subOptionId{get;set;}
        global Integer quantity{get;set;}
        global String departureCitiesId{get;set;}
        
        // Wrapper for Pax Info Per Sub option
        global List<passengerWapper> passengerDetails{get;set;}
        
        //New attributes as per Elmin's request, also check an 
        global string appSessionCode {get;set;}
        global string accountSFId {get;set;}
        
    }
    
    global class passengerWapper{
        global String subOptionId{get;set;}
        global String travelType{get;set;}
        global String departureCitiesId{get;set;}
        global String departureDateId{get;set;}
        global String passengerName{get;set;}
    }
    
    global class responseWrapper{
        global String orderId{get;set;}
        global String currencyType{get;set;}
        global date fromDate{get;set;}
        global date toDate{get;set;}
        global List<passengerResponse> passenger{get;set;}
        
        //Error which might go through just in case appSessionCode, FirstName and LastName aren't validated.
        global String errorMessage{get;set;}
        global Boolean isSuccess {get;set;}
        
    }
    global class passengerResponse{
        global String passengerName{get;set;}
        global String passengerId{get;set;}
        global String oliId{get;set;}
        
    }
    
    
    
    
    @HttpPost
    global static responseWrapper createTADOrder(mainWrapper orderData){
        responseWrapper reponse = new responseWrapper();
        Boolean proceed = false;
        
        List<Account> actList = [Select id, firstname, lastname, app_session__c from Account 
                                 where Id =:orderData.accountSFId Limit 1];
        
        if(!actList.isEmpty() && (actList[0].app_session__c == orderData.appSessionCode)){
            proceed = true;
        }
        
        /*

deal__c dealRec = [Select id , Allocation_by__c from deal__c where id = : orderData.dealId limit 1];
Set<String> subOptionSet = new  Set<String>();


Map<string,departures_dates__c> keyDatemap = new Map<string,departures_dates__c>();
if(dealRec.Allocation_by__c == 'Sub option'){
for(passengerWapper paxData :orderData.passengerDetails){
subOptionSet.add(paxData.subOptionId);
}
List<departures_dates__c> depDateRecords = [Select id , date__c,sub_options__c from  departures_dates__c where sub_options__c IN:subOptionSet]
for(departures_dates__c depRec :depDateRecords){
keyDatemap.put(depRec.date__c+'-'+depRec.sub_options__c,depRec);
}   
}*/
        
        
        // Create Order Record
        if(proceed == true){
            Tad_Order__c order = new Tad_Order__c();
            order.ordexp_account__c=orderData.accountSFId;
            order.ordexp_deal__c=orderData.dealId;
            order.ordexp_option__c=orderData.optionsId;
            if(orderData.dealCountry=='AUS'){
                order.RecordTypeId = TADUtils.getRecordTypeList('TAD','Tad_Order__c');
                reponse.currencyType='AUD';
            }else{
                order.RecordTypeId = TADUtils.getRecordTypeList('TNZ','Tad_Order__c');
                reponse.currencyType='NZD';
            }
            order.ordexp_departure_date__c=orderData.departureDateId; 
            insert order; 
            
            // Order Creation ends
            
            reponse.orderId = order.id;
            
            List<customer_POE__c> paxToInsert = new List<customer_POE__c>();
            List<Order_Line_Item__c> oliToInsert = new List<Order_Line_Item__c>();
            
            map<integer,String> pasMap = new  map<integer,String>();
            System.debug('orderdata===='+orderData);
            System.debug('orderdata===='+orderData.passengerDetails);
            
            if(orderData.passengerDetails==null || orderData.passengerDetails.isEmpty())
            {        
                Order_Line_Item__c oli = new Order_Line_Item__c();
                oli.Deal__c =orderData.dealId;
                oli.ordexp_Options__c = orderData.optionsId;
                oli.Sub_Options__c=orderData.subOptionId;
                oli.ordexp_departure_date__c=orderData.departureDateId ;
                oli.PAX_Quantity__c=String.valueOf(orderData.quantity);
                oli.Quantity__c=String.valueOf(orderData.quantity);
                oli.Pricing_Model__c = orderData.travelType;
                oli.Departure_cities__c=orderData.departureCitiesId;
                oli.ordexp_TAD_Order__c=order.id;
                insert oli;
                
                for(Integer i=1 ; i<=orderData.quantity ; i++){
                    customer_POE__c pass = new customer_POE__c();
                    pass.last_name__c = 'Passenger '+ i;
                    pass.ordexp_tad_order__c = order.id;
                    pass.Order_Line_Item__c =  oli.id; 
                    paxToInsert.add(pass);   
                }
            }
            else{
                
                integer counter=0;
                for(passengerWapper paxData :orderData.passengerDetails){
                    Order_Line_Item__c oli = new Order_Line_Item__c();
                    oli.Deal__c =orderData.dealId;
                    oli.ordexp_Options__c = orderData.optionsId;
                    oli.Sub_Options__c=paxData.subOptionId;
                    oli.PAX_Quantity__c='1';
                    oli.Quantity__c='1';
                    oli.Pricing_Model__c = paxData.travelType;
                    oli.Departure_cities__c=paxData.departureCitiesId;
                    oli.ordexp_departure_date__c=paxData.departureDateId;
                    oli.ordexp_TAD_Order__c=order.id;
                    oliToInsert.add(oli); 
                    
                    if(paxData.passengerName!= null || paxData.passengerName!= ''){
                        pasMap.put(counter,paxData.passengerName); 
                    }else{
                        pasMap.put(counter,'Passenger ' + counter); 
                    }
                    System.debug('pasMap'+pasMap);
                    System.debug('counter value'+counter);
                    counter=counter+1;
                }
                
                insert  oliToInsert;
                System.debug('pasMap1'+pasMap);
                for(Integer value :pasMap.keySet()){
                    customer_POE__c pass = new customer_POE__c();
                    pass.last_name__c = pasMap.get(value);
                    pass.ordexp_tad_order__c = oliToInsert[value].ordexp_TAD_Order__c;
                    pass.Order_Line_Item__c =  oliToInsert[value].id; 
                    paxToInsert.add(pass);     
                }
                
            }
            
            insert paxToInsert;
            
            List<passengerResponse> paxResList = new List<passengerResponse>();
            for(customer_POE__c cus : paxToInsert){
                passengerResponse  pax = new passengerResponse();
                pax.passengerName =cus.last_name__c;
                pax.passengerId =cus.id;
                pax.oliId=cus.Order_Line_Item__c;
                paxResList.add(pax);
            }
            
            tad_order__c t = [Select id , ordexp_departure_date__r.date__c , ordexp_departure_date__r.ordexp_return_date__c from tad_order__c where id =:order.id  ];
            reponse.fromDate=  t.ordexp_departure_date__r.date__c;
            reponse.toDate= t.ordexp_departure_date__r.ordexp_return_date__c;
            reponse.passenger =  paxResList;
            reponse.isSuccess = true;
            
        }else{
            reponse.errorMessage = 'Please try to Login again!';
            reponse.isSuccess = false;
        }   
        return reponse;
    }
    
}