force-app/main/default/objects/customer_POE__c/customer_POE__c.object-meta.xml
<CustomObject>
    <label>Passengers</label>
    <nameField>
        <displayFormat>PIF-{00000000}</displayFormat>
        <label>id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/customer_POE__c/fields/Instant_Notification__c.field-meta.xml
<CustomField>
    <fullName>Instant_Notification__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Instant Notification</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/customer_POE__c/fields/ordexp_tad_order__c.field-meta.xml
<CustomField>
    <fullName>ordexp_tad_order__c</fullName>
    <label>TAD Order</label>
    <referenceTo>TAD_Order__c</referenceTo>
    <relationshipLabel>Passengers</relationshipLabel>
    <relationshipName>Passengers_POE</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/TAD_Order__c.object-meta.xml
<CustomObject>
    <label>TAD Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TAD Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/NotificationToCustomer_InProgress.cls
public class NotificationToCustomer_InProgress {
    
    public static void InstantNotificationToCustomer(Set<Id> passIdSet){
        List<customer_POE__c> passList = [Select Id, is_waiting_passport__c, Instant_Notification__c, Email__c,ordexp_tad_order__r.Name from customer_POE__c where ordexp_tad_order__c =: passIdSet AND Instant_Notification__c != True AND is_waiting_passport__c = True];
        system.debug('Line--5-->'+passList);
        if(!passList.isEmpty() || passList !=null){
            for(customer_POE__c cus : passList){
                String toEmails = null;
                if(cus.Email__c != null){
                    toEmails = cus.Email__c;
                }
                
                List<OrgWideEmailAddress> lstEmailAddress=[select Id from OrgWideEmailAddress WHERE Address='noreply@tripadeal.com.au'];
                
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                mail.setToAddresses (new String[] { toEmails }); 
                mail.setOrgWideEmailAddressId(lstEmailAddress[0].Id);
                mail.setSubject('Fill passport information for order '+' '+cus.ordexp_tad_order__r.Name);
                
                EmailTemplate tempId=[SELECT Id,HTMLValue,Body,Name FROM EmailTemplate WHERE Name= 'Awaiting New Passport Notification' LIMIT 1];
                String emailBody = tempID.HTMLValue;
                mail.setHtmlBody(emailBody);
                mail.setOrgWideEmailAddressId(lstEmailAddress[0].Id);
                if(toEmails != null){
                    Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
                }
                
                cus.Instant_Notification__c = True; 
            }
            Update passList;
        }
    }
}