force-app/main/default/objects/TAD_Order__c/TAD_Order__c.object-meta.xml
<CustomObject>
    <label>TAD Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TAD Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TAD_Surcharge__c/TAD_Surcharge__c.object-meta.xml
<CustomObject>
    <label>TAD Surcharge</label>
    <nameField>
        <displayFormat>TS-{0000}</displayFormat>
        <label>TAD Surcharge Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TAD Surcharges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TAD_Surcharge__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <label>Reason</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Departure Date Change</fullName>
            </value>
            <value>
                <fullName>Departure City Change</fullName>
            </value>
            <value>
                <fullName>New OLI created</fullName>
            </value>
            <value>
                <fullName>Upgrade Booking</fullName>
            </value>
            <value>
                <fullName>AddOn Created</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>AE/SB + 30 days</fullName>
            </value>
            <value>
                <fullName>Name Change</fullName>
            </value>
            <value>
                <fullName>Legacy Adjustment</fullName>
            </value>
            <value>
                <fullName>Blackout Date Surcharge</fullName>
            </value>
            <value>
                <fullName>Flight Surcharge</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TAD_Surcharge__c/fields/Reason_If_Others__c.field-meta.xml
<CustomField>
    <fullName>Reason_If_Others__c</fullName>
    <label>Reason (If Others)</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TAD_Surcharge__c/fields/TAD_Order__c.field-meta.xml
<CustomField>
    <fullName>TAD_Order__c</fullName>
    <label>TAD Order</label>
    <referenceTo>TAD_Order__c</referenceTo>
    <relationshipLabel>TAD Surcharges</relationshipLabel>
    <relationshipName>TAD_Surcharges</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/tadSurchageController.cls
public class tadSurchageController {
    
    public class initWrapper{
        @AuraEnabled public string tadOrderName {get;set;} 
        @AuraEnabled public string tadCurrISOCode {get;set;} 
    }
    
    @AuraEnabled
    public static initWrapper getInitDetails(String tadOrderID){
        initWrapper initWrapperInstance = new initWrapper();
        
        TAD_Order__c tadOrder = [Select Id, Name, CurrencyIsoCode  from TAD_Order__c where Id =: tadOrderID Limit 1];
        
        initWrapperInstance.tadOrderName = tadOrder.Name;
        initWrapperInstance.tadCurrISOCode = tadOrder.CurrencyIsoCode;
        
        return initWrapperInstance;    
    }
    
    @AuraEnabled
    public static void createTADSurchargeRecord(String tadOrderId , List<String> listOfActions, String otherReason, Decimal surchargeAmount, String currencyIsoCode){
        
        String tadOrderSurchargeReason = '';
        
        for(String str : listOfActions){
            if(tadOrderSurchargeReason == ''){
                tadOrderSurchargeReason = str; 
            }else{
                tadOrderSurchargeReason = tadOrderSurchargeReason + ';' + str;
            }
        }
        
        TAD_Surcharge__c tadSurcharge = new TAD_Surcharge__c();
        tadSurcharge.TAD_Order__c = tadOrderId;
        tadSurcharge.Reason__c = tadOrderSurchargeReason;
        tadSurcharge.Surcharge_Amount__c = surchargeAmount;
        tadSurcharge.CurrencyIsoCode = currencyIsoCode;
        if(otherReason != '' && otherReason != null){
            tadSurcharge.Reason_If_Others__c = otherReason;
        }
        
        insert tadSurcharge;
    }
}