force-app/main/default/objects/TAD_Order__c/TAD_Order__c.object-meta.xml
<CustomObject>
    <label>TAD Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TAD Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_sabre_delete_group_profile__c.field-meta.xml
<CustomField>
    <fullName>ordexp_sabre_delete_group_profile__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sabre delete group profile</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/BatchordercDeleteSabreProfiles.cls
global class BatchordercDeleteSabreProfiles implements Database.Batchable<sObject> {

    global String query;

    global BatchordercDeleteSabreProfiles(String q) {
        this.query = q;
    }

    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext bc, List<tad_order__c> scope) {

        List<tad_order__c> ordersToUpdate = new List<tad_order__c>();
        for (tad_order__c o : scope) {
            o.ordexp_sabre_delete_group_profile__c = true;
            ordersToUpdate.add(o);
        }
        List<Database.SaveResult> sr;
        try {
            sr = Database.update(ordersToUpdate);
        } catch (exception e) {
            System.debug('Batch tad_order__c - BatchordercDeleteSabreProfiles exception: ' + e);
        }
    }

    global void finish(Database.BatchableContext bc) {

    }

}