force-app/main/default/objects/TAD_Order__c/TAD_Order__c.object-meta.xml
<CustomObject>
    <label>TAD Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TAD Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TAD_Order__c/fields/Account_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Account_Email_Address__c</fullName>
    <formula>IF( RecordType.Name=&apos;TAD&apos; || RecordType.Name=&apos;TNZ&apos; || RecordType.Name=&apos;Hotel&apos;  , IF(OR(ordexp_account__r.RecordType.Name = &apos;Product Partner&apos;,ordexp_account__r.RecordType.Name = &apos;PAF Corp Client&apos;), ordexp_account__r.Company_Email__c , ordexp_account__r.PersonEmail),  IF(OR(Agency_Id__r.RecordType.Name = &apos;Product Partner&apos;,Agency_Id__r.RecordType.Name = &apos;PAF Corp Client&apos;), Agency_Id__r.Company_Email__c , Agency_Id__r.PersonEmail))</formula>
    <label>Account Email Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_email_purchaser__c.field-meta.xml
<CustomField>
    <fullName>ordexp_email_purchaser__c</fullName>
    <label>Email(purchaser)</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/Purchaser_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Purchaser_First_Name__c</fullName>
    <formula>ordexp_account__r.FirstName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Purchaser First Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/recordTypes/TAD.recordType-meta.xml
<RecordType>
    <fullName>TAD</fullName>
    <active>true</active>
    <label>TAD</label>
</RecordType>

force-app/main/default/objects/TAD_Order__c/recordTypes/TNZ.recordType-meta.xml
<RecordType>
    <fullName>TNZ</fullName>
    <active>true</active>
    <label>TNZ</label>
</RecordType>

force-app/main/default/objects/TAD_Order__c/recordTypes/WT.recordType-meta.xml
<RecordType>
    <fullName>WT</fullName>
    <active>true</active>
    <label>WT</label>
</RecordType>

force-app/main/default/objects/Travefy_Document_POE__c/Travefy_Document_POE__c.object-meta.xml
<CustomObject>
    <label>Travefy Document</label>
    <nameField>
        <label>Travefy Documentation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Travefy Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Travefy_Document_POE__c/fields/order_record_type__c.field-meta.xml
<CustomField>
    <fullName>order_record_type__c</fullName>
    <formula>ordexp_tad_order__r.RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order Record Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Travefy_Document_POE__c/fields/ordexp_tad_order__c.field-meta.xml
<CustomField>
    <fullName>ordexp_tad_order__c</fullName>
    <label>TAD Order</label>
    <referenceTo>TAD_Order__c</referenceTo>
    <relationshipLabel>Travefy Documents</relationshipLabel>
    <relationshipName>Travefy_Documents_POE</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Travefy_Document_POE__c/fields/send_tp__c.field-meta.xml
<CustomField>
    <fullName>send_tp__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send TP to customer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Travefy_Document_POE__c/fields/trip_purchaser_email__c.field-meta.xml
<CustomField>
    <fullName>trip_purchaser_email__c</fullName>
    <label>Trip Purchaser Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Travefy_Document_POE__c/fields/trip_purchaser_first_name__c.field-meta.xml
<CustomField>
    <fullName>trip_purchaser_first_name__c</fullName>
    <label>Trip Purchaser First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BatchTravefyDocumentsSendEmailPOE.cls
global class BatchTravefyDocumentsSendEmailPOE implements Database.Batchable<sObject> {
    
    global String query;
    
    global BatchTravefyDocumentsSendEmailPOE(String q) {
        this.query = q;
    }
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        System.debug('query'+query);
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext bc, List<Travefy_Document_POE__c> scope) {
        
        List<Travefy_Document_POE__c> tdsToUpdate = new List<Travefy_Document_POE__c>();
        for (Travefy_Document_POE__c td : scope) {
            td.send_tp__c = true;
            
           // if(td.order_record_type__c=='TAD' || td.order_record_type__c=='WT' || td.order_record_type__c=='TNZ'){
           //     td.trip_purchaser_email__c  = td.ordexp_tad_order__r.ordexp_email_purchaser__c;
           //     td.trip_purchaser_first_name__c  = td.ordexp_tad_order__r.Purchaser_First_Name__c;
           // }else{
                td.trip_purchaser_email__c  = td.ordexp_tad_order__r.Account_Email_Address__c; 
                td.trip_purchaser_first_name__c  = td.ordexp_tad_order__r.Purchaser_First_Name__c;
          //  }
            tdsToUpdate.add(td);
        }
        List<Database.SaveResult> sr;
        try {
            sr = Database.update(tdsToUpdate);
        } catch (exception e) {
            System.debug('Batch Travefy Document - BatchTravefyDocumentsSendEmailPOE exception: ' + e);
        }
    }
    
    global void finish(Database.BatchableContext bc) {
        
    }
    
}