force-app/main/default/objects/TAD_Order__c/TAD_Order__c.object-meta.xml
<CustomObject>
    <label>TAD Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TAD Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_deal_id_title__c.field-meta.xml
<CustomField>
    <fullName>ordexp_deal_id_title__c</fullName>
    <formula>ordexp_deal__r.Deal_ID_Title__c</formula>
    <label>Deal ID + Title</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_master_status__c.field-meta.xml
<CustomField>
    <fullName>ordexp_master_status__c</fullName>
    <label>Master status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
                <default>true</default>
                <label>On Hold</label>
            </value>
            <value>
                <fullName>Temporary Hold</fullName>
            </value>
            <value>
                <fullName>Secured</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Travelled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>In Progress-Cruise only</fullName>
                <isActive>false</isActive>
                <label>In Progress-Cruise only</label>
            </value>
            <value>
                <fullName>In Progress-Flight only</fullName>
                <isActive>false</isActive>
                <label>In Progress-Flight only</label>
            </value>
            <value>
                <fullName>In Progress-Flights + Cruise</fullName>
                <isActive>false</isActive>
                <label>In Progress-Flights + Cruise</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_pax_travelling__c.field-meta.xml
<CustomField>
    <fullName>ordexp_pax_travelling__c</fullName>
    <formula>PAX_Qty__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PAX travelling</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_sub_status__c.field-meta.xml
<CustomField>
    <fullName>ordexp_sub_status__c</fullName>
    <label>Sub status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ordexp_master_status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial Payment Pending</fullName>
            </value>
            <value>
                <fullName>Cancellation Request</fullName>
            </value>
            <value>
                <fullName>Class (Sub Option) - Accom/Cabin Upgrade</fullName>
            </value>
            <value>
                <fullName>Duration/Extention (Option) - Upgrade</fullName>
            </value>
            <value>
                <fullName>Flight Quote Request</fullName>
            </value>
            <value>
                <fullName>Internal Correction/Change</fullName>
            </value>
            <value>
                <fullName>PAX Change Pending</fullName>
            </value>
            <value>
                <fullName>Paid - PIF/s Overdue</fullName>
            </value>
            <value>
                <fullName>Paid - PIF/s Due</fullName>
            </value>
            <value>
                <fullName>Stay Booking - No Ticketing Required</fullName>
            </value>
            <value>
                <fullName>Cabins Pending - Mins Not Met</fullName>
            </value>
            <value>
                <fullName>Flights Pending - Mins Not Met</fullName>
            </value>
            <value>
                <fullName>Flights Pending - Out of Range</fullName>
            </value>
            <value>
                <fullName>Flights Pending - Ready to Ticket</fullName>
            </value>
            <value>
                <fullName>Cabins Pending/Flights Booked - Cabin Ready to Ticket</fullName>
            </value>
            <value>
                <fullName>Cabins Booked</fullName>
            </value>
            <value>
                <fullName>Flights Booked</fullName>
            </value>
            <value>
                <fullName>Cabins Booked/Flights Booked</fullName>
            </value>
            <value>
                <fullName>BC Sent</fullName>
            </value>
            <value>
                <fullName>TP Sent &amp; Cruise Ticket Pending</fullName>
            </value>
            <value>
                <fullName>Travelling</fullName>
            </value>
            <value>
                <fullName>Survey Sent</fullName>
            </value>
            <value>
                <fullName>Survey Returned</fullName>
            </value>
            <value>
                <fullName>Expired/Time out</fullName>
            </value>
            <value>
                <fullName>Offloaded</fullName>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Customer Request</fullName>
            </value>
            <value>
                <fullName>Min Number - Credit/Refund</fullName>
            </value>
            <value>
                <fullName>Pax No Show</fullName>
            </value>
            <value>
                <fullName>Flights Ticketed - NO S/O</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TAD_Order__c/recordTypes/TC.recordType-meta.xml
<RecordType>
    <fullName>TC</fullName>
    <active>true</active>
    <label>TC</label>
</RecordType>

force-app/main/default/classes/TCPdfGeneratorSchedule.cls
/**
* ────────────────────────────────────────────────────────────────────────────────────────────────
* TCPdfGeneratorSchedule
* Purpose: Revamping For TCPdfGeneratorSchedule
* ──────────────────────────────────────────────────────────────────────────────────────────────────
 
* @lastModifiedBy Hansa Sabbarwal  <hansa@psagtechnologies.com>

* @version        2.0
* 
* @modified       2019-12-20
* @systemLayer    Apex Class
* ────────────────────────────────────────────────────────────────────────────────────────────────── */
global with sharing class TCPdfGeneratorSchedule implements Schedulable {

    global void execute (SchedulableContext ctx) {

        RecordType rt = [SELECT Id from Recordtype where SobjectType = 'TAD_Order__c' AND Name = 'TC'];

        List<TAD_Order__c> orders = [SELECT Id, Name, ordexp_sub_status__c, ordexp_master_status__c FROM TAD_Order__c WHERE
        (ordexp_master_status__c = 'Secured' OR ordexp_master_status__c = 'In Progress' ) AND RecordTypeId = :rt.Id ORDER BY CreatedDate DESC LIMIT 10];

        Set<Id> oIds = new Set<Id>();
        for (TAD_Order__c o : orders) {
            oIds.add(o.Id);
        }

        List<Attachment> attachments = [SELECT ParentId, Name FROM Attachment WHERE ParentId IN :oIds ORDER BY LastModifiedDate DESC LIMIT 1000];

        for (Attachment a : attachments) {
            if (oIds.contains(a.ParentId)) {
                if (a.name.contains('-Receipt.pdf') ) {
                    oIds.remove(a.ParentId);
                }
            }
        }

        List<TAD_Order__c> newOrders = [SELECT Id, Name, ordexp_deal_id_title__c, ordexp_pax_travelling__c FROM TAD_Order__c WHERE Id IN :oIds];

        for (TAD_Order__c o : newOrders) {
            PageReference pg = Page.WholesaleOptionalExtrasPDF;
            pg.getParameters().put('Id', o.Id);
            
            Blob pdf1 = Test.isRunningTest() ? Blob.valueOf('UNIT.TEST') : pg.getContentAsPDF();
            Attachment a = new Attachment();
            a.Body = pdf1;
            a.Name = o.Name + '-' + o.ordexp_deal_id_title__c + '-' + o.ordexp_pax_travelling__c + '-Receipt.pdf';
            a.ParentId = o.Id;
            a.IsPrivate = false;
            insert a;
        }
    }
}