force-app/main/default/objects/TAD_Order__c/TAD_Order__c.object-meta.xml
<CustomObject>
    <label>TAD Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TAD Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TAD_Order__c/fields/Info_from_Logistic__c.field-meta.xml
<CustomField>
    <fullName>Info_from_Logistic__c</fullName>
    <label>Information for Merchants</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/MP_OrderHistoryTest.cls
@isTest
public class MP_OrderHistoryTest {
    
    @isTest
    public static void orderTest(){
        TAD_Order__c tadOrder = new TAD_Order__c();
        tadOrder.Info_from_Logistic__c = 'Info from log';
        insert tadOrder;    
        
       
        
        
        tadOrder.Info_from_Logistic__c = 'Info from logistics';
        update tadOrder;
        
        TAD_Order__history orderHistory = new TAD_Order__history();
        orderHistory.ParentId = tadOrder.Id;
        orderHistory.Field = 'Info_from_Logistic__c';
        insert orderHistory;
        
        MP_OrderHistory.orderHistoryDetails(tadOrder.Id);
    }

}