force-app/main/default/objects/departures_dates__c/departures_dates__c.object-meta.xml
<CustomObject>
    <label>departures dates</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>departures dates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/departures_dates__c/fields/BC_Due__c.field-meta.xml
<CustomField>
    <fullName>BC_Due__c</fullName>
    <formula>IF(date__c&gt; DATE(2100,01,01) , date__c, IF (
(ISBLANK( BC_Due_Extension__c )),

IF (
(ISBLANK( Deal_for_Reporting__r.merchant_sharing_deadline_date__c )),
(date__c - Deal_for_Reporting__r.merchant_sharing_deadline__c ),
Deal_for_Reporting__r.merchant_sharing_deadline_date__c
),BC_Due_Extension__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Number of days prior to departure that merchant will receive booking confirmation. If multi-merchant deal, please use the most restrictive deadline e.g 120 days instead of 90.</inlineHelpText>
    <label>BC Due</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/Departure_Date_Finalised__c.field-meta.xml
<CustomField>
    <fullName>Departure_Date_Finalised__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Departure Date Finalised?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/mp_bc_available__c.field-meta.xml
<CustomField>
    <fullName>mp_bc_available__c</fullName>
    <label>BC Available</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NOT AVAILABLE</fullName>
                <default>true</default>
                <label>NOT AVAILABLE</label>
            </value>
            <value>
                <fullName>AVAILABLE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/online_status__c.field-meta.xml
<CustomField>
    <fullName>online_status__c</fullName>
    <label>Online Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Offline - Auto</fullName>
            </value>
            <value>
                <fullName>Offline - Manual</fullName>
            </value>
            <value>
                <fullName>Hidden</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TAD_Order__c/TAD_Order__c.object-meta.xml
<CustomObject>
    <label>TAD Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TAD Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_departure_date__c.field-meta.xml
<CustomField>
    <fullName>ordexp_departure_date__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Departure date</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>(1 OR 2) AND 3</booleanFilter>
        <filterItems>
            <field>departures_dates__c.Deal__c</field>
            <operation>equals</operation>
            <valueField>$Source.ordexp_deal__c</valueField>
        </filterItems>
        <filterItems>
            <field>departures_dates__c.options__c</field>
            <operation>equals</operation>
            <valueField>$Source.ordexp_option__c</valueField>
        </filterItems>
        <filterItems>
            <field>departures_dates__c.online_status__c</field>
            <operation>equals</operation>
            <value>Online</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>departures_dates__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>TAD_Orders_DD</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_sub_status__c.field-meta.xml
<CustomField>
    <fullName>ordexp_sub_status__c</fullName>
    <label>Sub status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ordexp_master_status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial Payment Pending</fullName>
            </value>
            <value>
                <fullName>Cancellation Request</fullName>
            </value>
            <value>
                <fullName>Class (Sub Option) - Accom/Cabin Upgrade</fullName>
            </value>
            <value>
                <fullName>Duration/Extention (Option) - Upgrade</fullName>
            </value>
            <value>
                <fullName>Flight Quote Request</fullName>
            </value>
            <value>
                <fullName>Internal Correction/Change</fullName>
            </value>
            <value>
                <fullName>PAX Change Pending</fullName>
            </value>
            <value>
                <fullName>Paid - PIF/s Overdue</fullName>
            </value>
            <value>
                <fullName>Paid - PIF/s Due</fullName>
            </value>
            <value>
                <fullName>Stay Booking - No Ticketing Required</fullName>
            </value>
            <value>
                <fullName>Cabins Pending - Mins Not Met</fullName>
            </value>
            <value>
                <fullName>Flights Pending - Mins Not Met</fullName>
            </value>
            <value>
                <fullName>Flights Pending - Out of Range</fullName>
            </value>
            <value>
                <fullName>Flights Pending - Ready to Ticket</fullName>
            </value>
            <value>
                <fullName>Cabins Pending/Flights Booked - Cabin Ready to Ticket</fullName>
            </value>
            <value>
                <fullName>Cabins Booked</fullName>
            </value>
            <value>
                <fullName>Flights Booked</fullName>
            </value>
            <value>
                <fullName>Cabins Booked/Flights Booked</fullName>
            </value>
            <value>
                <fullName>BC Sent</fullName>
            </value>
            <value>
                <fullName>TP Sent &amp; Cruise Ticket Pending</fullName>
            </value>
            <value>
                <fullName>Travelling</fullName>
            </value>
            <value>
                <fullName>Survey Sent</fullName>
            </value>
            <value>
                <fullName>Survey Returned</fullName>
            </value>
            <value>
                <fullName>Expired/Time out</fullName>
            </value>
            <value>
                <fullName>Offloaded</fullName>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Customer Request</fullName>
            </value>
            <value>
                <fullName>Min Number - Credit/Refund</fullName>
            </value>
            <value>
                <fullName>Pax No Show</fullName>
            </value>
            <value>
                <fullName>Flights Ticketed - NO S/O</fullName>
            </value>
            <value>
                <fullName>Flights Ticketed - S/O Req</fullName>
            </value>
            <value>
                <fullName>Cabins Booked/Flights Ticketed - NO S/O</fullName>
            </value>
            <value>
                <fullName>Cabins Booked/Flights Ticketed - S/O Req</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NotificationToLogisticFor5DaysBeforeDue.cls
/**
* ────────────────────────────────────────────────────────────────────────────────────────────────
* NotificationToLogisticFor5DaysBeforeDue
* Purpose: Apex Class Used for Invocable action from process Builder.
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* @createdBy Hansa Sabbarwal  <hansa@psagtechnologies.com>
* @lastModifiedBy Hansa Sabbarwal  <hansa@psagtechnologies.com>

* @version        1.0
* 
* @modified       2020-02-11
* @systemLayer    Apex Class
* ────────────────────────────────────────────────────────────────────────────────────────────────── */
public class NotificationToLogisticFor5DaysBeforeDue {
    
    @InvocableMethod
    public static void getDeptDateForEmail(List<departures_dates__c> deptDateList){
        Set<Id> DeptDatesId = new set<Id>();
        for(departures_dates__c dd : deptDateList ){
            if((dd.online_status__c == 'Offline - Auto' || dd.online_status__c == 'Offline - Manual') && !dd.Departure_Date_Finalised__c){
                DeptDatesId.add(dd.Id);
            }
        }
        if(!DeptDatesId.isEmpty()){
            
            System.debug('DeptDatesId'+DeptDatesId);
            Map<Id,Set<Id>> mapOfdeptDateIdsVsOPendingOrder = new  Map<Id,Set<Id>>();
            Boolean ispendingDue = false;
            for(TAD_Order__c ord : [select Id, Name, ordexp_sub_status__c, ordexp_departure_date__c, ordexp_departure_date__r.BC_Due__c, ordexp_departure_date__r.Departure_Date_Finalised__c, ordexp_departure_date__r.online_status__c, ordexp_departure_date__r.mp_bc_available__c   from TAD_Order__c where ordexp_departure_date__c IN : DeptDatesId ]){
                if( ord.ordexp_sub_status__c == null || ord.ordexp_sub_status__c == '' || (ord.ordexp_sub_status__c != 'Cabins Booked/Flights Ticketed - NO S/O' && ord.ordexp_sub_status__c != 'Flights Ticketed - NO S/O' && ord.ordexp_sub_status__c != 'Flights Ticketed - S/O Req' && ord.ordexp_sub_status__c != 'Cabins Booked/Flights Ticketed - S/O Req' && ord.ordexp_sub_status__c != 'BC Sent') ){
                    
                    If(!mapOfdeptDateIdsVsOPendingOrder.containsKey(ord.ordexp_departure_date__c)){
                    
                        mapOfdeptDateIdsVsOPendingOrder.put(ord.ordexp_departure_date__c, new Set<Id>{ord.Id});     
                    }else{
                        
                        Set<Id> ordIdSet = mapOfdeptDateIdsVsOPendingOrder.get(ord.ordexp_departure_date__c);
                        ordIdSet.add(ord.Id);
                        mapOfdeptDateIdsVsOPendingOrder.put(ord.ordexp_departure_date__c, ordIdSet);
                        
                    }
                    
                    
                }
            }
            system.debug('ispendingDue '+ispendingDue);
            EmailTemplate emailTemp = [Select Id, Name,DeveloperName, Subject, Body, HtmlValue from EmailTemplate where DeveloperName = 'Template_For_Email_To_Merchant_For_BC_Due_Date' ];
            Contact targetDummyCon = [select Id from Contact limit 1];
            Map<String, String> param2Emailtemplate = new Map<String, string>();
            for(departures_dates__c dept : [Select Id, Name from departures_dates__c where Id IN : mapOfdeptDateIdsVsOPendingOrder.keySet()]){
                system.debug('ispendingDue here ');
                
                String recepient = System.Label.RecepientForEarlyBooking;
                list<string> toAddresses = new list<string>();
                toAddresses.add(recepient);
                
                system.debug('emailTemp '+emailTemp.HtmlValue); 
                String htmlBody = emailTemp.HtmlValue;
                htmlBody = htmlBody.remove(']]>');
                htmlBody = htmlBody.replace('{!departures_dates__c.Name}', dept.Name);
                for(Id ordId : mapOfdeptDateIdsVsOPendingOrder.get(dept.Id)){
                    String baseUrl =System.URL.getSalesforceBaseUrl().toExternalForm();
                    htmlBody = htmlBody + ' <a href='+baseUrl+'/'+ordId+'>Click Here</a><br/>';
                }
                
                system.debug('htmlBody here ------'+htmlBody);
                param2Emailtemplate.put('htmlBody', htmlBody);
				param2Emailtemplate.put('Subject', emailTemp.Subject);
                //param2Emailtemplate.put('plainTextBody', emailTemp.Body);
             
                Utility_SingleEmailMessageHandler.EmailHandlerMethod(toAddresses, null ,param2Emailtemplate,  false, false );
               
                
            }
            
        }
        
    }
}