force-app/main/default/objects/departures_dates__c/departures_dates__c.object-meta.xml
<CustomObject>
    <label>departures dates</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>departures dates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/departures_dates__c/fields/date__c.field-meta.xml
<CustomField>
    <fullName>date__c</fullName>
    <label>date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/ordexp_return_date__c.field-meta.xml
<CustomField>
    <fullName>ordexp_return_date__c</fullName>
    <formula>IF (  Nights__c  
 &gt; 0,(date__c+Nights__c)-1,IF ( Deal_for_Reporting__r.number_of_days__c
 &gt; 0, date__c + (Deal_for_Reporting__r.number_of_days__c
 - 1), date__c + (Deal_for_Reporting__r.number_of_days__c
 - 1)
))</formula>
    <label>Return Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order_Communication_POE__c/Order_Communication_POE__c.object-meta.xml
<CustomObject>
    <description>Records created by scheduled apex</description>
    <label>Order Communication</label>
    <nameField>
        <displayFormat>OC-{00000000}</displayFormat>
        <label>Order Communication Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Communications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Communication_POE__c/fields/communication_code__c.field-meta.xml
<CustomField>
    <fullName>communication_code__c</fullName>
    <label>Communication Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Communication_POE__c/fields/email_purchaser__c.field-meta.xml
<CustomField>
    <fullName>email_purchaser__c</fullName>
    <label>Email(Purchaser)</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Order_Communication_POE__c/fields/ordexp_Departure_Date__c.field-meta.xml
<CustomField>
    <fullName>ordexp_Departure_Date__c</fullName>
    <formula>TAD_Order__r.ordexp_departure_date__r.date__c</formula>
    <label>Departure Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order_Communication_POE__c/fields/purchaser_first_name__c.field-meta.xml
<CustomField>
    <fullName>purchaser_first_name__c</fullName>
    <label>Purchaser First Name</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Communication_POE__c/fields/purchaser_full_name__c.field-meta.xml
<CustomField>
    <fullName>purchaser_full_name__c</fullName>
    <label>Purchaser Full Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Communication_POE__c/fields/return_date__c.field-meta.xml
<CustomField>
    <fullName>return_date__c</fullName>
    <label>Return Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order_Communication_POE__c/fields/TAD_Order__c.field-meta.xml
<CustomField>
    <fullName>TAD_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TAD Order</label>
    <referenceTo>TAD_Order__c</referenceTo>
    <relationshipLabel>Order Communications</relationshipLabel>
    <relationshipName>Order_Communications_POE</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/TAD_Order__c.object-meta.xml
<CustomObject>
    <label>TAD Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TAD Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TAD_Order__c/fields/Account_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Account_Email_Address__c</fullName>
    <formula>IF( RecordType.Name=&apos;TAD&apos; || RecordType.Name=&apos;TNZ&apos; || RecordType.Name=&apos;Hotel&apos;  , IF(OR(ordexp_account__r.RecordType.Name = &apos;Product Partner&apos;,ordexp_account__r.RecordType.Name = &apos;PAF Corp Client&apos;), ordexp_account__r.Company_Email__c , ordexp_account__r.PersonEmail),  IF(OR(Agency_Id__r.RecordType.Name = &apos;Product Partner&apos;,Agency_Id__r.RecordType.Name = &apos;PAF Corp Client&apos;), Agency_Id__r.Company_Email__c , Agency_Id__r.PersonEmail))</formula>
    <label>Account Email Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/Account_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Phone_Number__c</fullName>
    <formula>IF(
NOT(ISBLANK(ordexp_account__r.PersonContact.MobilePhone)),
ordexp_account__r.PersonContact.MobilePhone,
(ordexp_account__r.Phone)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Phone Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_departure_date__c.field-meta.xml
<CustomField>
    <fullName>ordexp_departure_date__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Departure date</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>(1 OR 2) AND 3</booleanFilter>
        <filterItems>
            <field>departures_dates__c.Deal__c</field>
            <operation>equals</operation>
            <valueField>$Source.ordexp_deal__c</valueField>
        </filterItems>
        <filterItems>
            <field>departures_dates__c.options__c</field>
            <operation>equals</operation>
            <valueField>$Source.ordexp_option__c</valueField>
        </filterItems>
        <filterItems>
            <field>departures_dates__c.online_status__c</field>
            <operation>equals</operation>
            <value>Online</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>departures_dates__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>TAD_Orders_DD</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_email_purchaser__c.field-meta.xml
<CustomField>
    <fullName>ordexp_email_purchaser__c</fullName>
    <label>Email(purchaser)</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_master_status__c.field-meta.xml
<CustomField>
    <fullName>ordexp_master_status__c</fullName>
    <label>Master status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
                <default>true</default>
                <label>On Hold</label>
            </value>
            <value>
                <fullName>Temporary Hold</fullName>
            </value>
            <value>
                <fullName>Secured</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Travelled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>In Progress-Cruise only</fullName>
                <isActive>false</isActive>
                <label>In Progress-Cruise only</label>
            </value>
            <value>
                <fullName>In Progress-Flight only</fullName>
                <isActive>false</isActive>
                <label>In Progress-Flight only</label>
            </value>
            <value>
                <fullName>In Progress-Flights + Cruise</fullName>
                <isActive>false</isActive>
                <label>In Progress-Flights + Cruise</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_return_date__c.field-meta.xml
<CustomField>
    <fullName>ordexp_return_date__c</fullName>
    <label>Return date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/Purchaser_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Purchaser_First_Name__c</fullName>
    <formula>ordexp_account__r.FirstName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Purchaser First Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/Purchaser_Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Purchaser_Full_Name__c</fullName>
    <formula>ordexp_account__r.FirstName + &apos; &apos; + ordexp_account__r.LastName</formula>
    <label>Purchaser Full Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/Purchaser_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Purchaser_Last_Name__c</fullName>
    <formula>ordexp_account__r.LastName</formula>
    <label>Purchaser Last Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/Travel_Pack_Delay_Comm_For_This_Order__c.field-meta.xml
<CustomField>
    <fullName>Travel_Pack_Delay_Comm_For_This_Order__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Travel Pack Delay Comm For This Order</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/tad_TravelPackDelayCommsHandler.cls
/*
PBP - 261
*/
public class tad_TravelPackDelayCommsHandler {

    public static void travelPackDelayOrdCommsForAllOrders(Set<Id> ddIdsSet){
        
        List<TAD_Order__c> tadOrdsList = [SELECT Id,Travel_Pack_Delay_Comm_For_This_Order__c,(SELECT Id FROM Order_Communications_POE__r WHERE communication_code__c = 'Travel_Pack_Delayed')ordexp_departure_date__c,ordexp_return_date__c,ordexp_departure_date__r.date__c,ordexp_master_status__c,ordexp_email_purchaser__c,Account_Email_Address__c,Purchaser_First_Name__c,Purchaser_Full_Name__c,Purchaser_Last_Name__c,Account_phone_number__c  FROM TAD_Order__c WHERE ordexp_departure_date__c IN:ddIdsSet AND (ordexp_master_status__c = 'Secured' OR ordexp_master_status__c = 'In Progress')];
        
        if(!tadOrdsList.isEmpty()){
            
            for(TAD_Order__c ord : tadOrdsList){
                if(ord.Travel_Pack_Delay_Comm_For_This_Order__c == false){
                    ord.Travel_Pack_Delay_Comm_For_This_Order__c = true;
                }
            }
            
            update tadOrdsList;
        }
    }
    
    public static void travelPackDelayOrdCommsForThisOrder(Set<Id> tadOrdIdsSet){
        system.debug('tadOrdIdsSet '+tadOrdIdsSet);
        List<Order_Communication_POE__c> ocListToInsert = New List<Order_Communication_POE__c>();
        
        List<TAD_Order__c> tadOrdsList = [SELECT Id,(SELECT Id FROM Order_Communications_POE__r WHERE communication_code__c = 'Travel_Pack_Delayed')ordexp_departure_date__c,ordexp_return_date__c,ordexp_departure_date__r.date__c,ordexp_master_status__c,ordexp_email_purchaser__c,Account_Email_Address__c,Purchaser_First_Name__c,Purchaser_Full_Name__c,Purchaser_Last_Name__c,Account_phone_number__c  FROM TAD_Order__c WHERE Id IN:tadOrdIdsSet AND (ordexp_master_status__c = 'Secured' OR ordexp_master_status__c = 'In Progress')];
        
        if(!tadOrdsList.isEmpty()){
            
            for(TAD_Order__c ord : tadOrdsList){
                system.debug('ord '+ord);
                system.debug('ord '+ord.Order_Communications_POE__r.size());
                if(ord.Order_Communications_POE__r.size() <= 0){
                   Order_Communication_POE__c oc = new Order_Communication_POE__c();
                	oc.TAD_Order__c = ord.Id;
        			oc.purchaser_first_name__c = ord.Purchaser_First_Name__c;
        			oc.purchaser_last_name__c = ord.purchaser_last_name__c;
        			oc.purchaser_full_name__c = ord.purchaser_full_name__c;
        			oc.email_purchaser__c = ord.Account_Email_Address__c;
        			oc.phone__c = ord.Account_phone_number__c;
        			oc.departure_date__c = ord.ordexp_departure_date__r.date__c;
        			oc.return_date__c = ord.ordexp_return_date__c; 
                    oc.communication_code__c = 'Travel_Pack_Delayed';
                    ocListToInsert.add(oc);
                }
            }
        }
        
        if(!ocListToInsert.isEmpty()){
            insert ocListToInsert;
        }
    }
}