force-app/main/default/objects/departures_dates__c/departures_dates__c.object-meta.xml
<CustomObject>
    <label>departures dates</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>departures dates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/departures_dates__c/fields/BC_Due_Extension__c.field-meta.xml
<CustomField>
    <fullName>BC_Due_Extension__c</fullName>
    <label>BC Due Extension</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/Deal_for_Reporting__c.field-meta.xml
<CustomField>
    <fullName>Deal_for_Reporting__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Deal for Reporting</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>departures dates (Deal for Reporting)</relationshipLabel>
    <relationshipName>departures_dates1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/departureDateBcDueExtension_Update.cls
public class departureDateBcDueExtension_Update {
    public static void updateBcDueExtension(Map<String,String> bcExtenstionMap, Date bcDueExtension){
        List<departures_dates__c> ddList = [Select Id, BC_Due_Extension__c from departures_dates__c where Deal_for_Reporting__c IN :bcExtenstionMap.keySet() AND Name IN : bcExtenstionMap.values()];
        for(departures_dates__c dd : ddList){
            dd.BC_Due_Extension__c = bcDueExtension;
        }
        update ddList;
    }
}