force-app/main/default/objects/departures_dates__c/departures_dates__c.object-meta.xml
<CustomObject>
    <label>departures dates</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>departures dates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/departures_dates__c/fields/date__c.field-meta.xml
<CustomField>
    <fullName>date__c</fullName>
    <label>date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/finalise_date__c.field-meta.xml
<CustomField>
    <fullName>finalise_date__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Finalise Date</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/TAD_Order__c.object-meta.xml
<CustomObject>
    <label>TAD Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TAD Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_bc_date__c.field-meta.xml
<CustomField>
    <fullName>ordexp_bc_date__c</fullName>
    <label>BC date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_bc_sent__c.field-meta.xml
<CustomField>
    <fullName>ordexp_bc_sent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BC sent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_departure_date__c.field-meta.xml
<CustomField>
    <fullName>ordexp_departure_date__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Departure date</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>(1 OR 2) AND 3</booleanFilter>
        <filterItems>
            <field>departures_dates__c.Deal__c</field>
            <operation>equals</operation>
            <valueField>$Source.ordexp_deal__c</valueField>
        </filterItems>
        <filterItems>
            <field>departures_dates__c.options__c</field>
            <operation>equals</operation>
            <valueField>$Source.ordexp_option__c</valueField>
        </filterItems>
        <filterItems>
            <field>departures_dates__c.online_status__c</field>
            <operation>equals</operation>
            <value>Online</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>departures_dates__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>TAD_Orders_DD</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_master_status__c.field-meta.xml
<CustomField>
    <fullName>ordexp_master_status__c</fullName>
    <label>Master status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
                <default>true</default>
                <label>On Hold</label>
            </value>
            <value>
                <fullName>Temporary Hold</fullName>
            </value>
            <value>
                <fullName>Secured</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Travelled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>In Progress-Cruise only</fullName>
                <isActive>false</isActive>
                <label>In Progress-Cruise only</label>
            </value>
            <value>
                <fullName>In Progress-Flight only</fullName>
                <isActive>false</isActive>
                <label>In Progress-Flight only</label>
            </value>
            <value>
                <fullName>In Progress-Flights + Cruise</fullName>
                <isActive>false</isActive>
                <label>In Progress-Flights + Cruise</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ScheduleordercBCUpdate.cls
global class ScheduleordercBCUpdate implements Schedulable {

    global void execute(SchedulableContext SC) {

        Date dateScopeStart = Date.today();
        // Date dateScopeEnd = dateScopeStart.addDays(107);

        // Commented to stop date limit.
        //List<departures_dates__c> dds = [SELECT Id FROM departures_dates__c WHERE date__c > :dateScopeStart AND date__c < :dateScopeEnd AND finalise_date__c = true];
        List<departures_dates__c> dds = [SELECT Id FROM departures_dates__c WHERE date__c > :dateScopeStart AND finalise_date__c = true];

        Set<Id> ddIds = new Set<Id>();
        for (departures_dates__c dd : dds) {
            ddIds.add(dd.Id);
        }

        if (ddIds.size() > 0) {

            String idString = '';

            for (Id id : ddIds) {
                idString = idString + '\'' + id + '\',';
            }

            String q = 'SELECT Id, ordexp_bc_sent__c, ordexp_bc_date__c FROM Tad_Order__c WHERE ordexp_departure_date__c IN (' + idString.left(idString.length() - 1) + ') AND ordexp_master_status__c IN (\'In Progress\') AND ordexp_bc_sent__c = false';
            BatchordercBCUpdate batch = new BatchordercBCUpdate(q);
            Database.executeBatch(batch, 10);

        }
    }
}