force-app/main/default/objects/departures_dates__c/departures_dates__c.object-meta.xml
<CustomObject>
    <label>departures dates</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>departures dates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/departures_dates__c/fields/send_to_travefy__c.field-meta.xml
<CustomField>
    <fullName>send_to_travefy__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send To Travefy</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/travel_documentation_created__c.field-meta.xml
<CustomField>
    <fullName>travel_documentation_created__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Travel Documentation Created</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/order__c/order__c.object-meta.xml
<CustomObject>
    <label>orders</label>
    <nameField>
        <displayFormat>{00}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>order</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/order__c/fields/departures_dates__c.field-meta.xml
<CustomField>
    <fullName>departures_dates__c</fullName>
    <label>Departure Date</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 OR 2 OR 3) AND (4 OR 5) AND ((6 AND 7) OR (8 AND 9)) AND 10</booleanFilter>
        <errorMessage>departure date - Value does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>departures_dates__c.sub_options__c</field>
            <operation>equals</operation>
            <valueField>$Source.Sub_Options__c</valueField>
        </filterItems>
        <filterItems>
            <field>departures_dates__c.options__c</field>
            <operation>equals</operation>
            <valueField>$Source.Options__c</valueField>
        </filterItems>
        <filterItems>
            <field>departures_dates__c.Deal__c</field>
            <operation>equals</operation>
            <valueField>$Source.deal__c</valueField>
        </filterItems>
        <filterItems>
            <field>departures_dates__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>departures_dates__c.recently_expired__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>departures_dates__c.NRMA_Date__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.Referrer__c</field>
            <operation>notEqual</operation>
            <value>NRMA</value>
        </filterItems>
        <filterItems>
            <field>$Source.Referrer__c</field>
            <operation>equals</operation>
            <value>NRMA</value>
        </filterItems>
        <filterItems>
            <field>departures_dates__c.NRMA_Date__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>departures_dates__c.order_filter__c</field>
            <operation>contains</operation>
            <valueField>$Source.order_record_type_name__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>departures_dates__c</referenceTo>
    <relationshipLabel>order</relationshipLabel>
    <relationshipName>order</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/order__c/fields/exclude_sending_tp__c.field-meta.xml
<CustomField>
    <fullName>exclude_sending_tp__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Exclude Sending TP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/order__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <formula>Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/order__c/fields/tp_email_sent__c.field-meta.xml
<CustomField>
    <fullName>tp_email_sent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>TP Email Sent from PAI</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Travefy_Document__c/Travefy_Document__c.object-meta.xml
<CustomObject>
    <label>Travefy Document (Old)</label>
    <nameField>
        <label>Travefy Documentation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Travefy Documents (Old)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Travefy_Document__c/fields/departures_dates__c.field-meta.xml
<CustomField>
    <fullName>departures_dates__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Departure Date Id</label>
    <referenceTo>departures_dates__c</referenceTo>
    <relationshipLabel>Travefy Documents</relationshipLabel>
    <relationshipName>Travefy_Documents</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Travefy_Document__c/fields/exclude_sending_tp__c.field-meta.xml
<CustomField>
    <fullName>exclude_sending_tp__c</fullName>
    <formula>order__r.exclude_sending_tp__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Exclude Sending TP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Travefy_Document__c/fields/order__c.field-meta.xml
<CustomField>
    <fullName>order__c</fullName>
    <label>Order</label>
    <referenceTo>order__c</referenceTo>
    <relationshipLabel>Travefy Documents</relationshipLabel>
    <relationshipName>Travefy_Documents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Travefy_Document__c/fields/share_url_path__c.field-meta.xml
<CustomField>
    <fullName>share_url_path__c</fullName>
    <label>Share URL Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Travefy_Document__c/fields/tp_email_sent__c.field-meta.xml
<CustomField>
    <fullName>tp_email_sent__c</fullName>
    <formula>order__r.tp_email_sent__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TP Email Sent From PAI</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Travefy_Document__c/fields/travefy_share_url__c.field-meta.xml
<CustomField>
    <fullName>travefy_share_url__c</fullName>
    <formula>CASE( order_record_type__c , 
&quot;TAD&quot;, &quot;https://app.tripadeal.com.au/&quot; &amp; share_url_path__c, 
&quot;TNZ&quot;, &quot;https://documentation.tripadeal.co.nz/&quot; &amp; share_url_path__c,
&quot;TC&quot; , &quot;https://tcdocumentation.tripadeal.travel/&quot; &amp; share_url_path__c,
&quot;WT&quot;, &quot;https://documentation.tripadeal.co.nz/&quot; &amp; share_url_path__c,
&quot;http://www.tripadeal.com.au/login&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Travefy Share URL</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Travefy_Document__c/fields/tripuser_last_sent__c.field-meta.xml
<CustomField>
    <fullName>tripuser_last_sent__c</fullName>
    <label>TripUser Last Sent</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/SendItinerariesController.cls
public with sharing class SendItinerariesController {

    // Get the url parameters into variables
    public Id ddId = Id.valueOf(System.currentPageReference().getParameters().get('id'));
    public final departures_dates__c dd = [SELECT Id, Name, travel_documentation_created__c, send_to_travefy__c FROM departures_dates__c WHERE Id = :ddId];
    public List<Travefy_Document__c> tds {get;set;}
    private Set<Id> tdIds;

    public Boolean batchStatusBool {get;set;}
    public String batchStatus {get;set;}
    Id batchId;
    public Boolean pollerBool {get;set;}

    public Boolean isSendButtonDisabled {get;set;}

    public SendItinerariesController() {

        tds = [SELECT Id, Name, order__c, exclude_sending_tp__c, send_tp__c, tripfull_last_sent__c, tripuser_last_sent__c, travefy_share_url__c, tp_email_sent__c, share_url_path__c FROM Travefy_Document__c WHERE departures_dates__c = :ddid];
        tdIds = new Set<Id>();
        batchStatusBool = false;
        pollerBool = false;
    }

    public void invokeBatchSend() {
        if (dd.travel_documentation_created__c) {

            tds = [SELECT Id, Name, order__c, exclude_sending_tp__c, send_tp__c, tripfull_last_sent__c, tripuser_last_sent__c, travefy_share_url__c, tp_email_sent__c, share_url_path__c FROM Travefy_Document__c WHERE departures_dates__c = :ddid];

            for (Travefy_Document__c td : tds) {
                if (td.tripfull_last_sent__c != null && td.tripuser_last_sent__c != null && !td.exclude_sending_tp__c && !td.tp_email_sent__c && td.share_url_path__c != null) {
                    tdIds.add(td.Id);
                }
            }

            // Batch stuff here
            if (tdIds.size() > 0) {

                String idString = '';

                for (Id id : tdIds) {
                    idString = idString + '\'' + id + '\',';
                }
                batchStatusBool = true;
                String q = 'SELECT Id, send_tp__c FROM Travefy_Document__c WHERE Id IN (' + idString.left(idString.length() - 1) + ')';
                BatchTravefyDocumentsSendItineraryEmail batch = new BatchTravefyDocumentsSendItineraryEmail(q);
                batchId = Database.executeBatch(batch, 5);
                checkBatchStatus();
            }
        }
    }

    // Function that redirects page on successfull transaction back to original Travel Booking detail
    public PageReference backToDepartureDate() {

        PageReference backToTravelBooking;
        String travelBookingUri = '/' + String.valueOf(ddId);
        backToTravelBooking = new PageReference(travelBookingUri);
        backToTravelBooking.setRedirect(true);

        return backToTravelBooking;
    }

//    public void disableSendButton() {
//        this.isSendButtonDisabled = true;
//    }

    public void checkBatchStatus() {
        AsyncApexJob job = [SELECT Id, Status FROM AsyncApexJob WHERE Id =: batchId];
        batchStatus = job.Status;
        if(batchStatus == 'Completed') {
            pollerBool = false;
        } else {
            pollerBool = true;
        }
    }

}