force-app/main/default/objects/Travelclick_Room_Reservation_Send_ID__e/Travelclick_Room_Reservation_Send_ID__e.object-meta.xml
<CustomObject>
    <label>Travelclick Room Reservation Send ID</label>
    <pluralLabel>Travelclick Room Reservation Send ID</pluralLabel>
</CustomObject>

force-app/main/default/objects/Travelclick_Room_Reservation_Send_ID__e/fields/Tad_Order_Id__c.field-meta.xml
<CustomField>
    <fullName>Tad_Order_Id__c</fullName>
    <label>Tad Order Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/makeResCalloutToTravelClickController.cls
public class makeResCalloutToTravelClickController {
    
    public static void makeCallout(List<Travelclick_Room_Reservation_Send_ID__e> listOfSMPlatformEventRecords){
        
        List<String> ListOfIDs = new List<String>();
        for(Travelclick_Room_Reservation_Send_ID__e sm: listOfSMPlatformEventRecords){
            ListOfIDs.add(sm.Tad_Order_Id__c);
        }  
        
        if(!ListOfIDs.isEmpty()){
            OTA_TravelClick_HotelRes_LegacyOrder.sendRestCalloutToTravelClick(ListOfIDs[0]);
        }
    }
    
    
    
}