force-app/main/default/objects/Airline__c/Airline__c.object-meta.xml
<CustomObject>
    <label>Airline</label>
    <nameField>
        <label>Airline Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Airlines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal__c/Deal__c.object-meta.xml
<CustomObject>
    <label>Deal</label>
    <nameField>
        <label>Deal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal__c/fields/Airline__c.field-meta.xml
<CustomField>
    <fullName>Airline__c</fullName>
    <label>Airline</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Flight_Ticketing_Structure__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>Qantas</fullName>
            </value>
            <value>
                <fullName>Jetstar</fullName>
            </value>
            <value>
                <fullName>Sri Lankan Airlines</fullName>
            </value>
            <value>
                <fullName>Korean Air</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal__c/fields/BNCDL__c.field-meta.xml
<CustomField>
    <fullName>BNCDL__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BNCDL</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Deal__c/fields/Flight_Ticketing_Structure__c.field-meta.xml
<CustomField>
    <fullName>Flight_Ticketing_Structure__c</fullName>
    <label>Flight Ticketing Structure</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>FIT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal__c/fields/Valid_From__c.field-meta.xml
<CustomField>
    <fullName>Valid_From__c</fullName>
    <label>Valid From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Deal__c/fields/Valid_To__c.field-meta.xml
<CustomField>
    <fullName>Valid_To__c</fullName>
    <label>Valid To</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/departures_dates__c.object-meta.xml
<CustomObject>
    <label>departures dates</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>departures dates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/departures_dates__c/fields/Airline__c.field-meta.xml
<CustomField>
    <fullName>Airline__c</fullName>
    <label>Airline</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Flight_Ticketing_Structure__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Qantas</fullName>
            </value>
            <value>
                <fullName>Jetstar</fullName>
            </value>
            <value>
                <fullName>Sri Lankan Airlines</fullName>
            </value>
            <value>
                <fullName>Korean Air</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/Approved_to_Run_Under_Mins__c.field-meta.xml
<CustomField>
    <fullName>Approved_to_Run_Under_Mins__c</fullName>
    <defaultValue>false</defaultValue>
    <description>For Flight Ticketing team use - can be checked as true if approval received by BDM/Merchant to go ahead with ticketing if mins not yet met</description>
    <inlineHelpText>Check this as true if approval received to run under min numbers</inlineHelpText>
    <label>Approved to Run Under Mins?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/BNCDL__c.field-meta.xml
<CustomField>
    <fullName>BNCDL__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BNCDL</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/date__c.field-meta.xml
<CustomField>
    <fullName>date__c</fullName>
    <label>date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>departures dates</relationshipLabel>
    <relationshipName>departures_dates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/Deal_for_Reporting__c.field-meta.xml
<CustomField>
    <fullName>Deal_for_Reporting__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Deal for Reporting</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>departures dates (Deal for Reporting)</relationshipLabel>
    <relationshipName>departures_dates1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/Flight_Ticketing_Structure__c.field-meta.xml
<CustomField>
    <fullName>Flight_Ticketing_Structure__c</fullName>
    <label>Flight Ticketing Structure</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>FIT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/Flight_Ticketing_Updated_Manually__c.field-meta.xml
<CustomField>
    <fullName>Flight_Ticketing_Updated_Manually__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Flight Ticketing Updated Manually</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/min_numbers_met__c.field-meta.xml
<CustomField>
    <fullName>min_numbers_met__c</fullName>
    <defaultValue>false</defaultValue>
    <description>For Flight Ticketing team use - checks as true if number of pax confirmed &gt;= min numbers</description>
    <inlineHelpText>Process Builder - Auto checks as true if number of pax confirmed greater or equal to min. numbers</inlineHelpText>
    <label>Min Numbers Met?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/TAD_Order__c.object-meta.xml
<CustomObject>
    <label>TAD Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TAD Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TAD_Order__c/fields/Airline__c.field-meta.xml
<CustomField>
    <fullName>Airline__c</fullName>
    <label>Airline</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Flight_Ticketing_Structure__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Qantas</fullName>
            </value>
            <value>
                <fullName>Jetstar</fullName>
            </value>
            <value>
                <fullName>Sri Lankan Airlines</fullName>
            </value>
            <value>
                <fullName>Korean Air</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/Flight_Ticketing_Structure__c.field-meta.xml
<CustomField>
    <fullName>Flight_Ticketing_Structure__c</fullName>
    <label>Flight Ticketing Structure</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>FIT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/Flight_Ticketing_Updated_Manually__c.field-meta.xml
<CustomField>
    <fullName>Flight_Ticketing_Updated_Manually__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Flight Ticketing Updated Manually</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_departure_date__c.field-meta.xml
<CustomField>
    <fullName>ordexp_departure_date__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Departure date</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>(1 OR 2) AND 3</booleanFilter>
        <filterItems>
            <field>departures_dates__c.Deal__c</field>
            <operation>equals</operation>
            <valueField>$Source.ordexp_deal__c</valueField>
        </filterItems>
        <filterItems>
            <field>departures_dates__c.options__c</field>
            <operation>equals</operation>
            <valueField>$Source.ordexp_option__c</valueField>
        </filterItems>
        <filterItems>
            <field>departures_dates__c.online_status__c</field>
            <operation>equals</operation>
            <value>Online</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>departures_dates__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>TAD_Orders_DD</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_master_status__c.field-meta.xml
<CustomField>
    <fullName>ordexp_master_status__c</fullName>
    <label>Master status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
                <default>true</default>
                <label>On Hold</label>
            </value>
            <value>
                <fullName>Temporary Hold</fullName>
            </value>
            <value>
                <fullName>Secured</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Travelled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>In Progress-Cruise only</fullName>
                <isActive>false</isActive>
                <label>In Progress-Cruise only</label>
            </value>
            <value>
                <fullName>In Progress-Flight only</fullName>
                <isActive>false</isActive>
                <label>In Progress-Flight only</label>
            </value>
            <value>
                <fullName>In Progress-Flights + Cruise</fullName>
                <isActive>false</isActive>
                <label>In Progress-Flights + Cruise</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_status_check__c.field-meta.xml
<CustomField>
    <fullName>ordexp_status_check__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field especially created for Order Status Updation</description>
    <label>Status Check</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/recordTypes/TAD.recordType-meta.xml
<RecordType>
    <fullName>TAD</fullName>
    <active>true</active>
    <label>TAD</label>
</RecordType>

force-app/main/default/classes/departuredateTriggerHandler.cls
public class departuredateTriggerHandler {
    
    public static boolean runOnce = false;
    public static Boolean isFromParentTrigger = false;

    //PBP - 145 Start
    public static void populateValidToandFroDate(List<departures_dates__c> newDealList){
        //Id batchJobId = Database.executeBatch(new PopulateDealValidFromToBatch(), 1); 
        
        Set<String> dealIdSet = new set<String>();
        Map<id,Deal__c> dealMap = new Map<id,Deal__c>();
        List<Deal__c> dealToUpdate = new List<Deal__c>();
        system.debug('newDealList '+newDealList);
        for(departures_dates__c objDepDate : newDealList){
                dealIdSet.add(objDepDate.Deal_for_Reporting__c);
            }
        
       if(!dealIdSet.isEmpty()){
        
       List<AggregateResult> aggrDealList = [Select Deal_for_Reporting__c, MIN(date__c)minDate ,MAX(date__c)maxDate  FROM departures_dates__c  where  (BNCDL__c = false AND Deal_for_Reporting__c   IN: dealIdSet)  GROUP BY Deal_for_Reporting__c ];
        system.debug('aggrDealList '+aggrDealList);
        for(AggregateResult agr :aggrDealList){
            Date fromDate = (Date)agr.get('minDate');
            Date toDate = (Date)agr.get('maxDate');
            Id dealId = (Id)agr.get('Deal_for_Reporting__c');
            System.debug('fromDate'+fromDate);
            	Deal__c dt = new Deal__c(); 
                dt.Id = dealId;
                dt.Valid_From__c  = fromDate;
                dt.Valid_To__c  = toDate;
              if(dt.Id != Null){
               dealToUpdate.add(dt); 
            }   
          }
        }
        
        if(!dealToUpdate.isEmpty()){
            system.debug('dealToUpdate '+dealToUpdate);
            update dealToUpdate;
        }
    }
    //PBP - 145 Stop
    public static void autoMinNumberMet(List<departures_dates__c> ddlistnew , Map<id,departures_dates__c>ddMapOld){
        
        Set<string> minStatus = new Set<string>();
        minStatus.add('Cabins Pending - Mins Not Met');
        minStatus.add('Flights Pending - Mins Not Met');
        minStatus.add('Cabins Pending/Flights Pending - Mins not met');
        
        Set<id> ddsIds = new  Set<id>();
        for(departures_dates__c dd : ddlistnew){
            if(((dd.Approved_to_Run_Under_Mins__c  != ddMapOld.get(dd.id).Approved_to_Run_Under_Mins__c) ) ||
               ((dd.min_numbers_met__c   != ddMapOld.get(dd.id).min_numbers_met__c ) && dd.min_numbers_met__c  ==true )){
                   ddsIds.add(dd.id);  
               }
        }
        
        if(!ddsIds.isempty()){
            List<tad_order__c> tadOrderList = [Select id,ordexp_status_check__c  from tad_order__c where ordexp_departure_date__c IN:ddsIds AND ordexp_master_status__c != 'Cancelled'];
            
            if(!tadOrderList.isempty()){
                for(tad_order__c tad : tadOrderList){
                    if(tad.ordexp_status_check__c ==true){
                        tad.ordexp_status_check__c = false;  
                    }else{
                        tad.ordexp_status_check__c = true;  
                    }
                }
                
                update tadOrderList;
            }
            
        }
    }  


    //PSAG-280
    public static void updateOrdersWithFlightTicketing(List<departures_dates__c> depNewList , Map<id,departures_dates__c>deptOldMap){
        Set<Id> deptIdSet = new Set<Id>();
        for(departures_dates__c deptObj : depNewList){
            if(((deptObj.Flight_Ticketing_Structure__c != deptOldMap.get(deptObj.Id).Flight_Ticketing_Structure__c) || (deptObj.Airline__c != deptOldMap.get(deptObj.Id).Airline__c)) && (deptObj.Flight_Ticketing_Updated_Manually__c == true)){
                deptIdSet.add(deptObj.Id);
            }            
        }
        if(!deptIdSet.isEmpty()){
           isFromParentTrigger = true;
           List<TAD_Order__c> tadOrderList = [SELECT Id, Flight_Ticketing_Structure__c, Airline__c, ordexp_departure_date__r.Id, ordexp_departure_date__r.Flight_Ticketing_Structure__c,Flight_Ticketing_Updated_Manually__c, ordexp_departure_date__r.Airline__c FROM TAD_Order__c WHERE  ordexp_departure_date__r.Id IN :deptIdSet AND Flight_Ticketing_Updated_Manually__c = false ];
            for(TAD_Order__c orderObj : tadOrderList){
                orderObj.Flight_Ticketing_Structure__c = orderObj.ordexp_departure_date__r.Flight_Ticketing_Structure__c;
                orderObj.Airline__c = orderObj.ordexp_departure_date__r.Airline__c;
            }
			update tadOrderList;
           
        }
        
    }
}