force-app/main/default/objects/Airline__c/Airline__c.object-meta.xml
<CustomObject>
    <label>Airline</label>
    <nameField>
        <label>Airline Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Airlines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal__c/Deal__c.object-meta.xml
<CustomObject>
    <label>Deal</label>
    <nameField>
        <label>Deal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal__c/fields/Airline__c.field-meta.xml
<CustomField>
    <fullName>Airline__c</fullName>
    <label>Airline</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Flight_Ticketing_Structure__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>Qantas</fullName>
            </value>
            <value>
                <fullName>Jetstar</fullName>
            </value>
            <value>
                <fullName>Sri Lankan Airlines</fullName>
            </value>
            <value>
                <fullName>Korean Air</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal__c/fields/Flight_Ticketing_Structure__c.field-meta.xml
<CustomField>
    <fullName>Flight_Ticketing_Structure__c</fullName>
    <label>Flight Ticketing Structure</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>FIT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/departures_dates__c/departures_dates__c.object-meta.xml
<CustomObject>
    <label>departures dates</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>departures dates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/departures_dates__c/fields/Airline__c.field-meta.xml
<CustomField>
    <fullName>Airline__c</fullName>
    <label>Airline</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Flight_Ticketing_Structure__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Qantas</fullName>
            </value>
            <value>
                <fullName>Jetstar</fullName>
            </value>
            <value>
                <fullName>Sri Lankan Airlines</fullName>
            </value>
            <value>
                <fullName>Korean Air</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/Deal_for_Reporting__c.field-meta.xml
<CustomField>
    <fullName>Deal_for_Reporting__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Deal for Reporting</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>departures dates (Deal for Reporting)</relationshipLabel>
    <relationshipName>departures_dates1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/FieldTicketingAirline_Comparison__c.field-meta.xml
<CustomField>
    <fullName>FieldTicketingAirline_Comparison__c</fullName>
    <formula>IF(
/*OR(
AND(
OR(
ISPICKVAL(Flight_Ticketing_Structure__c,&apos;None&apos;),
ISPICKVAL(Flight_Ticketing_Structure__c, &apos;&apos;)
),
OR(
ISPICKVAL(Airline__c,&apos;None&apos;),
ISPICKVAL(Airline__c, &apos;&apos;)
)
),*/

OR
(
 AND(
 NOT(ISBLANK(TEXT(Deal_for_Reporting__r.Flight_Ticketing_Structure__c))),
 TEXT(Flight_Ticketing_Structure__c) &lt;&gt; 
 TEXT(Deal_for_Reporting__r.Flight_Ticketing_Structure__c)),
 AND
 (
 NOT(ISBLANK(Deal_for_Reporting__r.Airline__c)), OR( INCLUDES(Airline__c, &apos;None&apos;),  INCLUDES(Airline__c, &apos;Qantas&apos;) ,INCLUDES(Airline__c, &apos;Jetstar&apos;),INCLUDES(Airline__c, &apos;Sri Lankan Airlines&apos;))  &lt;&gt;  OR(INCLUDES(Deal_for_Reporting__r.Airline__c,&apos;None&apos;),INCLUDES(Deal_for_Reporting__r.Airline__c,&apos;Qantas&apos;),INCLUDES(Deal_for_Reporting__r.Airline__c,&apos;Jetstar&apos;),INCLUDES(Deal_for_Reporting__r.Airline__c,&apos;Sri Lankan Airlines&apos;))
 )
),true,false
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FieldTicketingAirline Comparison</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/Flight_Ticketing_Structure__c.field-meta.xml
<CustomField>
    <fullName>Flight_Ticketing_Structure__c</fullName>
    <label>Flight Ticketing Structure</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>FIT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/Flight_Ticketing_Updated_Manually__c.field-meta.xml
<CustomField>
    <fullName>Flight_Ticketing_Updated_Manually__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Flight Ticketing Updated Manually</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/TAD_Order__c.object-meta.xml
<CustomObject>
    <label>TAD Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TAD Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TAD_Order__c/fields/Airline__c.field-meta.xml
<CustomField>
    <fullName>Airline__c</fullName>
    <label>Airline</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Flight_Ticketing_Structure__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Qantas</fullName>
            </value>
            <value>
                <fullName>Jetstar</fullName>
            </value>
            <value>
                <fullName>Sri Lankan Airlines</fullName>
            </value>
            <value>
                <fullName>Korean Air</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/Flight_Ticketing_Structure__c.field-meta.xml
<CustomField>
    <fullName>Flight_Ticketing_Structure__c</fullName>
    <label>Flight Ticketing Structure</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>FIT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/Flight_Ticketing_Updated_Manually__c.field-meta.xml
<CustomField>
    <fullName>Flight_Ticketing_Updated_Manually__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Flight Ticketing Updated Manually</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_departure_date__c.field-meta.xml
<CustomField>
    <fullName>ordexp_departure_date__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Departure date</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>(1 OR 2) AND 3</booleanFilter>
        <filterItems>
            <field>departures_dates__c.Deal__c</field>
            <operation>equals</operation>
            <valueField>$Source.ordexp_deal__c</valueField>
        </filterItems>
        <filterItems>
            <field>departures_dates__c.options__c</field>
            <operation>equals</operation>
            <valueField>$Source.ordexp_option__c</valueField>
        </filterItems>
        <filterItems>
            <field>departures_dates__c.online_status__c</field>
            <operation>equals</operation>
            <value>Online</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>departures_dates__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>TAD_Orders_DD</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TAD_UpdateDepartureAndOrdersBatch.cls
public class TAD_UpdateDepartureAndOrdersBatch implements Database.Batchable<sObject> {
    public Database.QueryLocator start(Database.BatchableContext BC) {       
        String query = 'SELECT Id,Name,FieldTicketingAirline_Comparison__c, Deal_for_Reporting__r.Name, Flight_Ticketing_Structure__c,Airline__c,Deal_for_Reporting__r.Flight_Ticketing_Structure__c,Deal_for_Reporting__r.Airline__c FROM departures_dates__c WHERE FieldTicketingAirline_Comparison__c = true AND Flight_Ticketing_Updated_Manually__c = false';
        System.debug('query ='+query);
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext BC, List<departures_dates__c> departureDateLst) {  
        System.debug('departureDateLst ='+departureDateLst.size());
        Set<Id> departureIdSet = (new Map<Id,SObject>(departureDateLst)).keySet();        
        List<departures_dates__c> deptLstToUpdate = new List<departures_dates__c>();
        if(!departureDateLst.isEmpty()){
            for(departures_dates__c deptObj : departureDateLst)
            {       
                deptObj.Flight_Ticketing_Structure__c = deptObj.Deal_for_Reporting__r.Flight_Ticketing_Structure__c;
                deptObj.Airline__c = deptObj.Deal_for_Reporting__r.Airline__c; 
                deptObj.Flight_Ticketing_Updated_Manually__c = false;
                deptLstToUpdate.add(deptObj);          
            }
        }
        
        try {
            update deptLstToUpdate;  
            
            List<TAD_Order__c> ordersToUpdateList = [SELECT Id, Flight_Ticketing_Structure__c, Flight_Ticketing_Updated_Manually__c, Airline__c, ordexp_departure_date__r.Id, ordexp_departure_date__r.Flight_Ticketing_Structure__c, ordexp_departure_date__r.Airline__c  FROM TAD_Order__c WHERE ordexp_departure_date__r.Id IN :departureIdSet AND Flight_Ticketing_Updated_Manually__c = false];
            if(!ordersToUpdateList.isEmpty()){
                for(TAD_Order__c orderObj : ordersToUpdateList){
                    orderObj.Flight_Ticketing_Structure__c = orderObj.ordexp_departure_date__r.Flight_Ticketing_Structure__c;
                    orderObj.Airline__c = orderObj.ordexp_departure_date__r.Airline__c;
                    orderObj.Flight_Ticketing_Updated_Manually__c = false;
                } 
            }
            
            update ordersToUpdateList;
        } catch(Exception e) {
            System.debug(e);
        }
        
    }   
    
    public void finish(Database.BatchableContext BC) {
    }
}