force-app/main/default/objects/Knowledge__kav/Knowledge__kav.object-meta.xml
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <label>Knowledge</label>
    <pluralLabel>Knowledge</pluralLabel>
</CustomObject>

force-app/main/default/objects/Knowledge__kav/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <label>Answer</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Knowledge_Type__c.field-meta.xml
<CustomField>
    <fullName>Knowledge_Type__c</fullName>
    <label>Knowledge Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/recordTypes/FAQ.recordType-meta.xml
<RecordType>
    <fullName>FAQ</fullName>
    <active>true</active>
    <description>This can be used for simple question and answer articles</description>
    <label>FAQ</label>
</RecordType>

force-app/main/default/classes/mp_FAQ.cls
public class mp_FAQ {
    
    
    
    public class FaqWrapper {
        
         @AuraEnabled
        public List<Faq> getFaq{get;set;}
    }
    public class Faq { 
         @AuraEnabled
         public String knownId{get;set;}
        @AuraEnabled
         public String question{get;set;}
        @AuraEnabled
        public String answer{get;set;}
         @AuraEnabled
         public String title{get;set;}
       
    }
    
    
     @AuraEnabled(cacheable=true) 
    public static FaqWrapper getFAQ (String faqStrName){
        
        FaqWrapper faqData = new FaqWrapper();
        
        String keyNameString = '%' +  faqStrName + '%';        
        List<Knowledge__kav> faqList = [Select Id,Title,UrlName, Answer__c, Question__c,Knowledge_Type__c from Knowledge__kav where Knowledge_Type__c = 'Community' AND Title like:keyNameString];
     system.debug('faqList--30->'+faqList);
         FaqWrapper wrap = new FaqWrapper();
       // wrap.tadOrder = ord;
        if(faqList.size()>0){
            List<FAQ> faqDataList = new List<FAQ>();
            for(Knowledge__kav kn:faqList){
               
                Faq fa = new Faq();
               
                fa.knownId = kn.Id;
                fa.question = kn.Question__c;
                fa.answer =kn.Answer__c;
                fa.title =kn.Title;
               
                faqDataList.add(fa);

            }
            faqData.getFaq = faqDataList;
        }
    system.debug('faqData--->'+faqData);
    return faqData;
    
    }  
    
    
    
    
    
    
    
    
    

}