force-app/main/default/objects/Knowledge__kav/Knowledge__kav.object-meta.xml
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <label>Knowledge</label>
    <pluralLabel>Knowledge</pluralLabel>
</CustomObject>

force-app/main/default/objects/Knowledge__kav/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <label>Answer</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Article_Category__c.field-meta.xml
<CustomField>
    <fullName>Article_Category__c</fullName>
    <label>Article Category</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Travel information</fullName>
            </value>
            <value>
                <fullName>Booking</fullName>
            </value>
            <value>
                <fullName>General enquiry</fullName>
            </value>
            <value>
                <fullName>Before you travel</fullName>
            </value>
            <value>
                <fullName>FAQ</fullName>
                <isActive>false</isActive>
                <label>FAQ</label>
            </value>
            <value>
                <fullName>Payments</fullName>
                <isActive>false</isActive>
                <label>Payments</label>
            </value>
            <value>
                <fullName>Terms and conditions</fullName>
                <isActive>false</isActive>
                <label>Terms and conditions</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Article_Type__c.field-meta.xml
<CustomField>
    <fullName>Article_Type__c</fullName>
    <label>Article Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Flights</fullName>
            </value>
            <value>
                <fullName>Cruises</fullName>
            </value>
            <value>
                <fullName>Hotels</fullName>
            </value>
            <value>
                <fullName>Tours</fullName>
            </value>
            <value>
                <fullName>Changes</fullName>
            </value>
            <value>
                <fullName>Cancellation</fullName>
            </value>
            <value>
                <fullName>Transfers</fullName>
            </value>
            <value>
                <fullName>Itinerary</fullName>
            </value>
            <value>
                <fullName>Invoices and receipts</fullName>
            </value>
            <value>
                <fullName>Placing an order</fullName>
            </value>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Medical</fullName>
            </value>
            <value>
                <fullName>Refunds</fullName>
            </value>
            <value>
                <fullName>Book with credit</fullName>
                <isActive>false</isActive>
                <label>Book with credit</label>
            </value>
            <value>
                <fullName>Itinerary,Invoices and receipts</fullName>
                <isActive>false</isActive>
                <label>Itinerary,Invoices and receipts</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Content__c.field-meta.xml
<CustomField>
    <fullName>Content__c</fullName>
    <label>Content</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Visible_on_Website__c.field-meta.xml
<CustomField>
    <fullName>Visible_on_Website__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Visible on Website</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Knowledge_Article_Web__c/Knowledge_Article_Web__c.object-meta.xml
<CustomObject>
    <label>Knowledge Article Web</label>
    <nameField>
        <displayFormat>KAB -{0000000}</displayFormat>
        <label>Knowledge Article Web</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Knowledge Articles Web</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Knowledge_Article_Web__c/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <label>Answer</label>
    <length>50000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Knowledge_Article_Web__c/fields/Article_Category__c.field-meta.xml
<CustomField>
    <fullName>Article_Category__c</fullName>
    <label>Article Category</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Travel information</fullName>
            </value>
            <value>
                <fullName>Booking</fullName>
            </value>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>General enquiry</fullName>
            </value>
            <value>
                <fullName>Before you travel</fullName>
            </value>
            <value>
                <fullName>Terms and conditions</fullName>
            </value>
            <value>
                <fullName>FAQ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Knowledge_Article_Web__c/fields/Article_Type__c.field-meta.xml
<CustomField>
    <fullName>Article_Type__c</fullName>
    <label>Article Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Flights</fullName>
            </value>
            <value>
                <fullName>Cruises</fullName>
            </value>
            <value>
                <fullName>Hotels</fullName>
            </value>
            <value>
                <fullName>Tours</fullName>
            </value>
            <value>
                <fullName>Book with credit</fullName>
            </value>
            <value>
                <fullName>Changes</fullName>
            </value>
            <value>
                <fullName>Cancellation</fullName>
            </value>
            <value>
                <fullName>Itinerary</fullName>
            </value>
            <value>
                <fullName>Refunds</fullName>
            </value>
            <value>
                <fullName>Transfers</fullName>
            </value>
            <value>
                <fullName>Placing an order</fullName>
            </value>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Medical</fullName>
            </value>
            <value>
                <fullName>Invoices and receipts</fullName>
            </value>
            <value>
                <fullName>Itinerary,Invoices and receipts</fullName>
                <isActive>false</isActive>
                <label>Itinerary,Invoices and receipts</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Knowledge_Article_Web__c/fields/Knowledge__c.field-meta.xml
<CustomField>
    <fullName>Knowledge__c</fullName>
    <label>Knowledge</label>
    <referenceTo>Knowledge__kav</referenceTo>
    <relationshipLabel>Knowledge Articles Web</relationshipLabel>
    <relationshipName>Knowledge_Articles_Web</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Knowledge_Article_Web__c/fields/Published_Status__c.field-meta.xml
<CustomField>
    <fullName>Published_Status__c</fullName>
    <formula>TEXT(Knowledge__r.PublishStatus )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Published Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge_Article_Web__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/KnowledgeArticleWebArticlesSyncTest.cls
@isTest 
public class KnowledgeArticleWebArticlesSyncTest {
    
    @testSetup static void setup() {
      List<Knowledge__kav> knwldgeLst = new List<Knowledge__kav>();
      List<Knowledge_Article_Web__c> webarticleLst = new List<Knowledge_Article_Web__c>();
      Knowledge__kav knwldge  = new Knowledge__kav();
      knwldge.Title = 'Article - TEST 1';
      knwldge.Answer__c = 'Article - TEST 1';
      knwldge.UrlName = 'abcd-xyz';
      knwldge.Question__c = 'ARTICLE  Question';
      knwldge.Content__c = 'TEST TEST';
      knwldge.Article_Category__c = 'Travel information;Booking';
      knwldge.Article_Type__c = 'flights';
      knwldge.Visible_on_Website__c = true;
      knwldgeLst.add(knwldge);
        
      Knowledge__kav knwldgePublished  = new Knowledge__kav();
      knwldgePublished.Title = 'Article - TEST 2';
      knwldgePublished.Answer__c = 'Article - TEST 11';
      knwldgePublished.UrlName = 'efgh-ijkl';
      knwldgePublished.Question__c = 'ARTICLE  Question One';
      knwldgePublished.Content__c = 'TEST TEST TEST';
      knwldgePublished.Article_Category__c = 'Travel information;Booking';
      knwldgePublished.Article_Type__c = 'flights';
      knwldgePublished.Visible_on_Website__c = true;
      knwldgeLst.add(knwldgePublished);
        
      Knowledge__kav knwldgeNoWebArticle  = new Knowledge__kav();
      knwldgeNoWebArticle.Title = 'Article - TEST 3';
      knwldgeNoWebArticle.Answer__c = 'Article - TEST 111';
      knwldgeNoWebArticle.UrlName = 'efgh-ijklmno';
      knwldgeNoWebArticle.Question__c = 'ARTICLE  Question OneOne';
      knwldgeNoWebArticle.Content__c = 'TEST TEST TEST TEST';
      knwldgeNoWebArticle.Article_Category__c = 'Travel information;Booking';
      knwldgeNoWebArticle.Article_Type__c = 'flights';
      knwldgeNoWebArticle.Visible_on_Website__c = true;
      knwldgeLst.add(knwldgeNoWebArticle);
        
      insert knwldgeLst;
      
      /* 
      Knowledge_Article_Web__c webarticlePublished = new Knowledge_Article_Web__c();
      webarticlePublished.Title__c = 'ARTICLE TEST 5';
      webarticlePublished.Answer__c = 'ARTICLE TEST 5';
	  webarticlePublished.Article_Category__c = 'Travel information;Booking';
      webarticlePublished.Article_Type__c = 'flights';
      webarticlePublished.Visible_on_Website__c= true;
      webarticlePublished.Knowledge__c = knwldgePublished.Id;
	  webarticleLst.add(webarticlePublished);     
        
      Knowledge_Article_Web__c webarticleNoRelatedKnwldge = new Knowledge_Article_Web__c();
      webarticleNoRelatedKnwldge.Title__c = 'ARTICLE TEST 222';
      webarticleNoRelatedKnwldge.Answer__c = 'ARTICLE TEST 222';
	  webarticleNoRelatedKnwldge.Article_Category__c = 'Travel information;Booking';
      webarticleNoRelatedKnwldge.Article_Type__c = 'flights';
      webarticleNoRelatedKnwldge.Visible_on_Website__c= true;
	  webarticleLst.add(webarticleNoRelatedKnwldge);     
      */
        
      insert webarticleLst;
      
    }
    
    @isTest
    public static void testmethod1(){   
        DateTime dt = System.Now().addHours(-2);
        //List<Knowledge__kav> knowledgeLst = [SELECT Id,(SELECT Id,Title__c,Answer__c,Article_Category__c,Article_Type__c,Published_Status__c,Visible_on_Website__c FROM Website_Articles__r), Question__c, Content__c, Article_Category__c, Article_Type__c, PublishStatus,Visible_on_Website__c,LastModifiedDate FROM Knowledge__kav LIMIT 1];
        
        Knowledge__kav objKnowledge = [SELECT Id,KnowledgeArticleId, Question__c, Content__c, Article_Category__c, Article_Type__c, PublishStatus,Visible_on_Website__c,LastModifiedDate From Knowledge__kav LIMIT 1];
        KbManagement.PublishingService.publishArticle(objKnowledge.KnowledgeArticleId, true);
        
        Test.starttest();
        
        KnowledgeWebArticleSynScheduler testsche = new KnowledgeWebArticleSynScheduler();
        //SchedulableContext sContext;
        //scheduler.execute(sContext);
        
        String sch = '0 0 23 * * ?';
        system.schedule('Test status Check', sch, testsche );
        Test.stopTest(); 
    }
    
    @isTest
    public static void testmethod2(){   
        
        Knowledge__kav objKnowledge = [SELECT Id,KnowledgeArticleId, Question__c, Content__c, Article_Category__c, Article_Type__c, PublishStatus,Visible_on_Website__c,LastModifiedDate From Knowledge__kav LIMIT 1];

        List<Knowledge_Article_Web__c> webarticleLst = new List<Knowledge_Article_Web__c>();
        Knowledge_Article_Web__c webarticle = new Knowledge_Article_Web__c();
        webarticle.Title__c = 'ARTICLE TEST 4';
        webarticle.Answer__c = 'ARTICLE TEST 4';
        webarticle.Article_Category__c = 'Travel information;Booking';
        webarticle.Article_Type__c = 'flights';
        webarticle.Visible_on_Website__c= false;
        webarticle.Knowledge__c = objKnowledge.Id;
        webarticleLst.add(webarticle); 
        insert webarticleLst;
        
        KbManagement.PublishingService.publishArticle(objKnowledge.KnowledgeArticleId, true);
        
        Test.starttest();
        
        KnowledgeWebArticleSynScheduler testsche = new KnowledgeWebArticleSynScheduler();
        String sch = '0 0 23 * * ?';
        system.schedule('Test status Check', sch, testsche );
        
        Test.stopTest(); 
    }
}