force-app/main/default/objects/coupon__c/coupon__c.object-meta.xml
<CustomObject>
    <label>coupon</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>coupon</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/coupon__c/fields/account__c.field-meta.xml
<CustomField>
    <fullName>account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>coupon</relationshipLabel>
    <relationshipName>coupon</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/coupon__c/fields/currency_code__c.field-meta.xml
<CustomField>
    <fullName>currency_code__c</fullName>
    <label>Currency Code</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AUD</fullName>
            </value>
            <value>
                <fullName>NZD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/coupon__c/fields/Min_order_value__c.field-meta.xml
<CustomField>
    <fullName>Min_order_value__c</fullName>
    <label>Min order value</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/coupon__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Coupon Name</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/coupon__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Enabled</fullName>
            </value>
            <value>
                <fullName>Disabled</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
                <default>true</default>
                <label>Pending Approval</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/coupon__c/fields/type__c.field-meta.xml
<CustomField>
    <fullName>type__c</fullName>
    <label>type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
                <default>true</default>
                <label>All</label>
            </value>
            <value>
                <fullName>Travel</fullName>
            </value>
            <value>
                <fullName>Cruise</fullName>
            </value>
            <value>
                <fullName>Stay</fullName>
            </value>
            <value>
                <fullName>Airline</fullName>
            </value>
            <value>
                <fullName>Exclusives</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/coupon__c/fields/usable_count__c.field-meta.xml
<CustomField>
    <fullName>usable_count__c</fullName>
    <label>Usable Count</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/NRMAStatusCheck.cls
public class NRMAStatusCheck {

    private static Map<String,NRMAStatusCheck> instances;
    private Account acct;
    private Id acctId;
    private String couponName;
    public List<coupon__c> coupons;
    public coupon__c coupon;

    public NRMAStatusCheck() {
        //constructor
    }

    public static NRMAStatusCheck getInstance(String memberNumber) {

        if (instances == null) {
            instances = new Map<String, NRMAStatusCheck>();
        }
        Object tempInst = instances.get(memberNumber);
        if (!(tempInst instanceof NRMAStatusCheck)) {
            instances.put(memberNumber, new NRMAStatusCheck());
        }
        //System.debug(instances);
        return instances.get(memberNumber);
    }

    @future (callout=true)
    public static void checkStatus(String memberNumber, Id accountId, Boolean isInsert) {

        Boolean newCoupon = false;

        getInstance(memberNumber).acctId = accountId;
        getInstance(memberNumber).acct = [SELECT Id, IsPersonAccount, RecordTypeId, NRMA_Membership_Number__c, NRMA_Id_Type__c, NRMA_Member_Status_Check_Date__c, NRMA_Member_Status_Valid__c, NRMA_New_Customer__c, NRMA_New_Customer_Date__c FROM Account WHERE Id = :accountId];
        getInstance(memberNumber).couponName = 'NRMA100' + memberNumber;
        getInstance(memberNumber).coupons = [SELECT Id, Status__c FROM coupon__c WHERE Name__c = :getInstance(memberNumber).couponName LIMIT 1];

        mynrmaComAuGoeWsdlAbcsMembervalida.GetMemberStatusMemberValidationServiceBindingQSPort nrmaCheck = new mynrmaComAuGoeWsdlAbcsMembervalida.GetMemberStatusMemberValidationServiceBindingQSPort();
        mynrmaComAuGoeSchemaAbcsMembervali.GetMemberStatusResponseType response = nrmaCheck.GetMemberStatus(memberNumber,'','','','','','');

        getInstance(memberNumber).acct.NRMA_Member_Status_Check_Date__c = Datetime.now();

        if (response.MemberStatus == 'True') {

            if (isInsert) {
                getInstance(memberNumber).acct.NRMA_Member_Status_Valid__c = true;
                getInstance(memberNumber).acct.NRMA_Id_Type__c = response.IdType;
                getInstance(memberNumber).acct.NRMA_New_Customer__c = true;
                getInstance(memberNumber).acct.NRMA_New_Customer_Date__c = Date.today();
            } else {
                getInstance(memberNumber).acct.NRMA_Member_Status_Valid__c = true;
                getInstance(memberNumber).acct.NRMA_Id_Type__c = response.IdType;
            }

            if (getInstance(memberNumber).coupons.size() == 0) {
                coupon__c c = new coupon__c();
                c.Name = getInstance(memberNumber).couponName;
                c.Name__c = getInstance(memberNumber).couponName;
                c.Discount__c = 100.00;
                c.usable_count__c = 1;
                c.Status__c = 'Enabled';
                c.type__c = 'All';
                c.Min_order_value__c = 2000;
                c.account__c = getInstance(memberNumber).acct.Id;
                c.currency_code__c = 'AUD';
                getInstance(memberNumber).coupon = c;
                newCoupon = true;
                insert c;
            }
        } else {
            getInstance(memberNumber).acct.NRMA_Member_Status_Valid__c = false;
            getInstance(memberNumber).acct.NRMA_Id_Type__c = '';
        }
        update getInstance(memberNumber).acct;
    }

}