force-app/main/default/objects/coupon__c/coupon__c.object-meta.xml
<CustomObject>
    <label>coupon</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>coupon</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/coupon__c/fields/Coupon_type__c.field-meta.xml
<CustomField>
    <fullName>Coupon_type__c</fullName>
    <label>Coupon Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Unscheduled Event</fullName>
            </value>
            <value>
                <fullName>Customer Compensation</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
            </value>
            <value>
                <fullName>Gift Coupon</fullName>
            </value>
            <value>
                <fullName>Promotion / Competition</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
            <value>
                <fullName>Wholesale Incentive</fullName>
            </value>
            <value>
                <fullName>Complaint</fullName>
            </value>
            <value>
                <fullName>Gift Voucher</fullName>
            </value>
            <value>
                <fullName>Promotion</fullName>
            </value>
            <value>
                <fullName>Change to deal</fullName>
            </value>
            <value>
                <fullName>Minimum Numbers</fullName>
            </value>
            <value>
                <fullName>Customer Offload</fullName>
            </value>
            <value>
                <fullName>Partner Discount</fullName>
            </value>
            <value>
                <fullName>Forfeit Flights</fullName>
            </value>
            <value>
                <fullName>BER</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/coupon__c/fields/currency_code__c.field-meta.xml
<CustomField>
    <fullName>currency_code__c</fullName>
    <label>Currency Code</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AUD</fullName>
            </value>
            <value>
                <fullName>NZD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/coupon__c/fields/Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiry_Date__c</fullName>
    <label>Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/coupon__c/fields/Is_Agent_Coupon__c.field-meta.xml
<CustomField>
    <fullName>Is_Agent_Coupon__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Agent Coupon</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/coupon__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Coupon Name</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/coupon__c/fields/usable_count__c.field-meta.xml
<CustomField>
    <fullName>usable_count__c</fullName>
    <label>Usable Count</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/coupon__c/fields/Usage__c.field-meta.xml
<CustomField>
    <fullName>Usage__c</fullName>
    <inlineHelpText>Single : Single use no balance | Balance : Single user but can be used incrementally | Multi : Multiple users can use the one coupon code</inlineHelpText>
    <label>Usage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single</fullName>
            </value>
            <value>
                <fullName>Balance</fullName>
            </value>
            <value>
                <fullName>Multi</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Tad_UpdateCouponExpiryBatchTest.cls
@isTest
public class Tad_UpdateCouponExpiryBatchTest {
@isTest
    public static void testMethod1(){
        test.startTest();
        coupon__c coupon = new coupon__c(Name__c = 'test Coupon',Coupon_type__c = 'Staff', currency_code__c ='AUD',Usage__c = 'Multi',usable_count__c = 5,Is_Agent_Coupon__c = true,Expiry_Date__c = System.today());
        insert coupon;
        Tad_UpdateCouponExpiryBatchScheduler sch = new Tad_UpdateCouponExpiryBatchScheduler();
        String cron = '0 0 2 * * ?'; 
        System.schedule('testjob',cron,sch);
        test.stopTest();
    }
}