force-app/main/default/objects/coupon__c/coupon__c.object-meta.xml
<CustomObject>
    <label>coupon</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>coupon</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/coupon__c/fields/balance_remaining__c.field-meta.xml
<CustomField>
    <fullName>balance_remaining__c</fullName>
    <formula>aggregate_discount__c - (aggregate_used__c + OLI_Aggregate_Used__c + EB_used__c + Order_aggregate_used__c  )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Balance Remaining</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/MobileAppGetCouponDetails_Test.cls
@istest
public class MobileAppGetCouponDetails_Test {
    
    @isTest
    static void TestMethod1() {
        
        
        coupon__c Coupon=TestDataFactory.createCoupon();
        insert Coupon;
        system.debug('Coupon'+Coupon);
        
        coupon__c cs=[SELECT id,Name ,balance_remaining__c from coupon__c where id =:Coupon.Id];
        system.debug('cs line 13 '+cs);
        
        MobileAppGetCouponDetails.couponRequest cq= new MobileAppGetCouponDetails.couponRequest();
        
        cq.CouponName=cs.Name;
        cq.orderAmount= 2000;
        system.debug('cq line 19 '+cq);
        Test.startTest();
        MobileAppGetCouponDetails.discountSearch(cq);
        Test.stopTest();
    }
     @isTest
    static void TestMethod2() {
        
        
        coupon__c Coupon=TestDataFactory.createCoupon();
        insert Coupon;
        system.debug('Coupon'+Coupon);
        
        coupon__c cs=[SELECT id,Name ,balance_remaining__c from coupon__c where id =:Coupon.Id];
        system.debug('cs line 13 '+cs);
        
        MobileAppGetCouponDetails.couponRequest cq= new MobileAppGetCouponDetails.couponRequest();
        
        cq.CouponName=cs.Name;
        cq.orderAmount= 50;
        system.debug('cq line 19 '+cq);
        Test.startTest();
        MobileAppGetCouponDetails.discountSearch(cq);
        Test.stopTest();
    }
     @isTest
    static void TestMethod3() {
        
        MobileAppGetCouponDetails.couponRequest cq= new MobileAppGetCouponDetails.couponRequest();
        
        cq.CouponName='test1';
        cq.orderAmount= 50;
        system.debug('cq line 19 '+cq);
        Test.startTest();
        MobileAppGetCouponDetails.discountSearch(cq);
        Test.stopTest();
    }
    
}