force-app/main/default/objects/Day_POE__c/Day_POE__c.object-meta.xml
<CustomObject>
    <label>Day POE</label>
    <nameField>
        <displayFormat>DAY-{0000000}</displayFormat>
        <label>Days POE Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Day POE</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Day_POE__c/fields/departures_dates__c.field-meta.xml
<CustomField>
    <fullName>departures_dates__c</fullName>
    <label>departures dates</label>
    <referenceTo>departures_dates__c</referenceTo>
    <relationshipLabel>Day POE</relationshipLabel>
    <relationshipName>Day_POE</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/departures_dates__c.object-meta.xml
<CustomObject>
    <label>departures dates</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>departures dates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/departures_dates__c/fields/Create_OLI_Itineries_POE__c.field-meta.xml
<CustomField>
    <fullName>Create_OLI_Itineries_POE__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Create OLI Itineries POE</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/create_travel_documentation_poe__c.field-meta.xml
<CustomField>
    <fullName>create_travel_documentation_poe__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Create Travel Documentation POE</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/Delete_Travefy_Docs_POE__c.field-meta.xml
<CustomField>
    <fullName>Delete_Travefy_Docs_POE__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Delete Travefy Docs POE</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/Send_to_Travefy_POE__c.field-meta.xml
<CustomField>
    <fullName>Send_to_Travefy_POE__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send to Travefy POE</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order_Itinerary__c/Order_Itinerary__c.object-meta.xml
<CustomObject>
    <label>Order Itinerary</label>
    <nameField>
        <displayFormat>OI{00000000}</displayFormat>
        <label>Order Itinerary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Itineraries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Itinerary__c/fields/Day_POE__c.field-meta.xml
<CustomField>
    <fullName>Day_POE__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Day POE</label>
    <referenceTo>Day_POE__c</referenceTo>
    <relationshipLabel>Order Itineraries</relationshipLabel>
    <relationshipName>Order_Itineraries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Itinerary__c/fields/Order_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Order_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Line Item</label>
    <referenceTo>order_line_item__c</referenceTo>
    <relationshipLabel>Order Itineraries</relationshipLabel>
    <relationshipName>Order_Itineraries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/order_line_item__c/order_line_item__c.object-meta.xml
<CustomObject>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>OLI-{000000}</displayFormat>
        <label>Order Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/order_line_item__c/fields/ordexp_departure_date__c.field-meta.xml
<CustomField>
    <fullName>ordexp_departure_date__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Note :- For Stay type Orders, change to Departure Date will be applied to all the OLIs of this Order</inlineHelpText>
    <label>Departure date</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>departures_dates__c.sub_options__c</field>
            <operation>equals</operation>
            <valueField>$Source.Sub_Options__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>departures_dates__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Travefy_Document_POE__c/Travefy_Document_POE__c.object-meta.xml
<CustomObject>
    <label>Travefy Document</label>
    <nameField>
        <label>Travefy Documentation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Travefy Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Travefy_Document_POE__c/fields/departures_dates__c.field-meta.xml
<CustomField>
    <fullName>departures_dates__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Departure Date Id</label>
    <referenceTo>departures_dates__c</referenceTo>
    <relationshipLabel>Travefy Documents</relationshipLabel>
    <relationshipName>Travefy_Documents_POE</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Travefy_Document_POE__c/fields/Order_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Order_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Line Item</label>
    <referenceTo>order_line_item__c</referenceTo>
    <relationshipLabel>Travefy Documents</relationshipLabel>
    <relationshipName>Travefy_Documents_POE</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/deleteRelatedTravelpackandOrderIti.cls
public class deleteRelatedTravelpackandOrderIti {
    
    public static void deleteRelatedTravelpackmethod(String ddates){
        set<String> setId=new set<String>();
        setId.add(ddates);
        
        if(!setId.isempty()){
            List<departures_dates__c> deptList=[select id,Create_OLI_Itineries_POE__c,create_travel_documentation_poe__c,Send_to_Travefy_POE__c,Delete_Travefy_Docs_POE__c from departures_dates__c where id in:setId];
            List<Order_Itinerary__c> ordItis=[Select id from Order_Itinerary__c where day_poe__r.departures_dates__c in:setId or Order_Line_Item__r.ordexp_departure_date__c in:setId ];
            List<Travefy_Document_POE__c> tdocs=[Select id from Travefy_Document_POE__c where departures_dates__c in:setId];  
            system.debug('ordItis'+ordItis);
            system.debug('tdocs'+tdocs);   
            if(!ordItis.IsEmpty()){
                Delete ordItis;
            }
            if(!tdocs.IsEmpty()){
                Delete tdocs;
            }
            for(departures_dates__c dd:deptList){        
                dd.Create_OLI_Itineries_POE__c=false;
                dd.create_travel_documentation_poe__c=false;
                dd.Send_to_Travefy_POE__c=false;
                dd.Delete_Travefy_Docs_POE__c=false;
            }
            update deptList;
        }
        
    }
}