force-app/main/default/objects/departure_cities__c/departure_cities__c.object-meta.xml
<CustomObject>
    <label>departure cities</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>departure cities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/General_Pricing__c/General_Pricing__c.object-meta.xml
<CustomObject>
    <label>General Pricing</label>
    <nameField>
        <displayFormat>GP-{0000000}</displayFormat>
        <label>General Pricing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>General Pricings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/General_Pricing__c/fields/Departure_City__c.field-meta.xml
<CustomField>
    <fullName>Departure_City__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Departure City</label>
    <referenceTo>departure_cities__c</referenceTo>
    <relationshipLabel>General Pricings</relationshipLabel>
    <relationshipName>General_Pricings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/General_Pricing__c/fields/Surcharge_AUD__c.field-meta.xml
<CustomField>
    <fullName>Surcharge_AUD__c</fullName>
    <label>Surcharge - AUD</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/General_Pricing__c/fields/Surcharge_NZD__c.field-meta.xml
<CustomField>
    <fullName>Surcharge_NZD__c</fullName>
    <label>Surcharge - NZD</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/order_line_item__c/order_line_item__c.object-meta.xml
<CustomObject>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>OLI-{000000}</displayFormat>
        <label>Order Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/order_line_item__c/fields/Departure_cities__c.field-meta.xml
<CustomField>
    <fullName>Departure_cities__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Departure cities</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>departure_cities__c.Deal__c</field>
            <operation>equals</operation>
            <valueField>$Source.Deal__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>departure_cities__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items_dc</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/order_line_item__c/fields/General_Pricing__c.field-meta.xml
<CustomField>
    <fullName>General_Pricing__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>General Pricing</label>
    <referenceTo>General_Pricing__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/order_line_item__c/fields/GP_Dep_City__c.field-meta.xml
<CustomField>
    <fullName>GP_Dep_City__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GP Dep City</label>
    <referenceTo>General_Pricing__c</referenceTo>
    <relationshipLabel>Order Line Items (GP Dep City)</relationshipLabel>
    <relationshipName>Order_Line_Items1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Tad_BatchToAttachGPDepCity.cls
public class Tad_BatchToAttachGPDepCity implements  Database.Batchable<sObject>{
    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator('select Id, Name,Departure_cities__c, GP_Dep_City__c from order_line_item__c where GP_Dep_City__c = null AND Departure_cities__c !=null');
    }
    public void execute(Database.BatchableContext bc, List<order_line_item__c> oliRecords){
        Set<Id> depCityIds = new Set<Id>();
        for(order_line_item__c oli :oliRecords){
            depCityIds.add(oli.Departure_cities__c);
        }
        List<General_Pricing__c> depGpRecords = [select id,name,Surcharge_AUD__c,Surcharge_NZD__c,Departure_City__c from General_Pricing__c where Active__c = true and Departure_City__c IN:depCityIds];
        for(order_line_item__c oli :oliRecords){
            for(General_Pricing__c gp :depGpRecords){
                if(gp.Departure_City__c == oli.Departure_cities__c){
                    oli.GP_Dep_City__c = gp.Id;
                }
            }
        }
        update oliRecords;
        
    }
      public void finish(Database.BatchableContext bc){
        System.debug('GP records Created successfuly');
    } 
}