force-app/main/default/objects/departure_cities__c/departure_cities__c.object-meta.xml
<CustomObject>
    <label>departure cities</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>departure cities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/departure_cities__c/fields/site__c.field-meta.xml
<CustomField>
    <fullName>site__c</fullName>
    <label>Site</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/departure_cities__c/fields/Surcharge__c.field-meta.xml
<CustomField>
    <fullName>Surcharge__c</fullName>
    <label>Surcharge</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/departure_cities__c/fields/surcharge_nz__c.field-meta.xml
<CustomField>
    <fullName>surcharge_nz__c</fullName>
    <label>Surcharge - NZD</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/General_Pricing__c/General_Pricing__c.object-meta.xml
<CustomObject>
    <label>General Pricing</label>
    <nameField>
        <displayFormat>GP-{0000000}</displayFormat>
        <label>General Pricing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>General Pricings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/General_Pricing__c/fields/Departure_City__c.field-meta.xml
<CustomField>
    <fullName>Departure_City__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Departure City</label>
    <referenceTo>departure_cities__c</referenceTo>
    <relationshipLabel>General Pricings</relationshipLabel>
    <relationshipName>General_Pricings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/General_Pricing__c/fields/Surcharge_AUD__c.field-meta.xml
<CustomField>
    <fullName>Surcharge_AUD__c</fullName>
    <label>Surcharge - AUD</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/General_Pricing__c/fields/Surcharge_NZD__c.field-meta.xml
<CustomField>
    <fullName>Surcharge_NZD__c</fullName>
    <label>Surcharge - NZD</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/General_Pricing__c/recordTypes/Departure_City.recordType-meta.xml
<RecordType>
    <fullName>Departure_City</fullName>
    <active>true</active>
    <label>Departure City</label>
</RecordType>

force-app/main/default/objects/Surcharge__c/Surcharge__c.object-meta.xml
<CustomObject>
    <label>Surcharge</label>
    <nameField>
        <displayFormat>SU{0000000}</displayFormat>
        <label>Surcharge Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Surcharges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/Tad_BatchToCreateDepcityGP.cls
public class Tad_BatchToCreateDepcityGP implements  Database.Batchable<sObject> {

    public Database.QueryLocator start(Database.BatchableContext bc){
         return Database.getQueryLocator('select id,name,Surcharge__c,surcharge_nz__c,site__c from departure_cities__c where id NOT IN (select Departure_City__c from General_Pricing__c where Active__c = true)');
    }
    public void execute(Database.BatchableContext bc, List<departure_cities__c> depcityRecords){
        List<General_Pricing__c> gpRecordsToInsert = new List<General_Pricing__c>();
        String depcityRCT = Schema.SObjectType.general_pricing__c.getRecordTypeInfosByDeveloperName().get('Departure_City').getRecordTypeId();
        for(departure_cities__c dep:depcityRecords){
            General_Pricing__c gp= new General_Pricing__c();
            gp.Active__c = true;
            if(dep.site__c == 'AU'){
               gp.Surcharge_AUD__c = dep.Surcharge__c;
            }else{
                gp.Surcharge_NZD__c = dep.surcharge_nz__c;
            }
            gp.Departure_City__c = dep.Id;
            gp.RecordTypeId = depcityRCT;
            gpRecordsToInsert.add(gp);
        }
        try{
            insert gpRecordsToInsert;
        }catch(Exception ex){
            System.debug('Error while creating new gp records for departure city'+ex.getMessage());
        }
    } 
    public void finish(Database.BatchableContext bc){
        System.debug('GP records Created successfuly');
    } 
}