force-app/main/default/objects/order__c/order__c.object-meta.xml
<CustomObject>
    <label>orders</label>
    <nameField>
        <displayFormat>{00}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>order</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/order__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <formula>Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Transaction__c/Payment_Transaction__c.object-meta.xml
<CustomObject>
    <label>Payment Transaction (Old)</label>
    <nameField>
        <displayFormat>{YY}{00000000}</displayFormat>
        <label>Payment Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Transactions (Old)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Transaction__c/fields/order__c.field-meta.xml
<CustomField>
    <fullName>order__c</fullName>
    <label>Order</label>
    <referenceTo>order__c</referenceTo>
    <relationshipLabel>Payment Transactions</relationshipLabel>
    <relationshipName>Payment_Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/classes/TheBetootaAdvocate.cls
/**
 * Created by PedroRusooli on the 25th of Never.
 */

public with sharing class TheBetootaAdvocate {

    @InvocableMethod
    public static void activateFluxCapacitor(List<Id> orderIds)
    {
        // Boolean fluxCapacitor = true;
        // List PTs =[select id from Payment_Transaction__c
        // where order__c in :orderIds];
        // dml PTs;
        // flux capacitors don't exist so just do nothing
    }
}