force-app/main/default/objects/order__c/order__c.object-meta.xml
<CustomObject>
    <label>orders</label>
    <nameField>
        <displayFormat>{00}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>order</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/order__c/fields/agency_id__c.field-meta.xml
<CustomField>
    <fullName>agency_id__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Agency Id</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>order (Agency Id)</relationshipLabel>
    <relationshipName>order1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/order__c/fields/agent_name__c.field-meta.xml
<CustomField>
    <fullName>agent_name__c</fullName>
    <description>(TC + NRMA)</description>
    <label>Consultant Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/order__c/fields/Deal_and_Option__c.field-meta.xml
<CustomField>
    <fullName>Deal_and_Option__c</fullName>
    <formula>IF(
OR(TEXT(order_record_type_name__c) = &quot;TNZ&quot;,TEXT(order_record_type_name__c) = &quot;WT&quot;),
deal__r.title_nz__c,
deal__r.title__c
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Deal Title</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/order__c/fields/Deal_ID__c.field-meta.xml
<CustomField>
    <fullName>Deal_ID__c</fullName>
    <formula>deal__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Deal ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/order__c/fields/description__c.field-meta.xml
<CustomField>
    <fullName>description__c</fullName>
    <label>description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/order__c/fields/email_purchaser__c.field-meta.xml
<CustomField>
    <fullName>email_purchaser__c</fullName>
    <label>Email(Purchaser)</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/order__c/fields/full_name_purchaser__c.field-meta.xml
<CustomField>
    <fullName>full_name_purchaser__c</fullName>
    <label>Purchaser Full Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/order__c/fields/grand_total__c.field-meta.xml
<CustomField>
    <fullName>grand_total__c</fullName>
    <formula>IF(  ISBLANK( Wholesale_Commissions__c ) ,
(total_price__c +  Flight_Surcharge__c ) - total_discounts__c,
(Wholesale_Amount_Payable__c +  Flight_Surcharge__c ) - total_discounts__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Grand Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/order__c/fields/old_NRMA_order_number__c.field-meta.xml
<CustomField>
    <fullName>old_NRMA_order_number__c</fullName>
    <label>Old NRMA Order Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/order__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <formula>Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/order__c/fields/TC_Booking_Status__c.field-meta.xml
<CustomField>
    <fullName>TC_Booking_Status__c</fullName>
    <label>Order Status (WS)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>PIF Required</fullName>
                <default>true</default>
                <label>PIF Required</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ordercSearchController.cls
public class ordercSearchController {

    @AuraEnabled
    public static PagedResult findAll(String searchKey, Decimal pageNumber) {
        Integer pageSize = 12;
        String key = '%' + searchKey + '%';
        Integer offset = ((Integer)pageNumber - 1) * pageSize;

        PagedResult r =  new PagedResult();
        r.pageSize = pageSize;
        r.page = (Integer) pageNumber;
        r.total = [SELECT count() FROM order__c
        WHERE (Name LIKE :key OR full_name_purchaser__c LIKE :key OR email_purchaser__c LIKE :key OR agent_name__c LIKE :key OR old_NRMA_order_number__c LIKE :key) AND agency_id__c IN (SELECT Id FROM Account WHERE PersonEmail = :UserInfo.getUserName())];
        r.products = [SELECT Id, Name, RecordTypeId, old_NRMA_order_number__c ,TC_Booking_Status__c, full_name_purchaser__c, email_purchaser__c, Deal_ID__c, Deal_and_Option__c, description__c, grand_total__c, agent_name__c FROM order__c
        WHERE (Name LIKE :key OR full_name_purchaser__c LIKE :key OR email_purchaser__c LIKE :key OR agent_name__c LIKE :key OR old_NRMA_order_number__c LIKE :key) AND agency_id__c IN (SELECT Id FROM Account WHERE PersonEmail = :UserInfo.getUserName())
        ORDER BY NAME LIMIT 12 OFFSET :offset];
        System.debug(r);
        return r;
    }

    @AuraEnabled
    public static PagedResult defaultOrders (Decimal pageNumber) {
        Integer pageSize = 12;
        Integer offset = ((Integer)pageNumber - 1) * pageSize;
        
        PagedResult r =  new PagedResult();
        r.pageSize = pageSize;
        r.page = (Integer) pageNumber;
        r.total = [SELECT count() FROM order__c WHERE agency_id__c IN (SELECT Id FROM Account WHERE PersonEmail = :UserInfo.getUserName())];
        r.products = [SELECT Id, Name, RecordTypeId, old_NRMA_order_number__c ,TC_Booking_Status__c, full_name_purchaser__c, email_purchaser__c, Deal_ID__c, Deal_and_Option__c, description__c, grand_total__c, agent_name__c FROM order__c WHERE agency_id__c IN (SELECT Id FROM Account WHERE PersonEmail = :UserInfo.getUserName())];
        return r;
    }
}