force-app/main/default/objects/order__c/order__c.object-meta.xml
<CustomObject>
    <label>orders</label>
    <nameField>
        <displayFormat>{00}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>order</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/order__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <formula>Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/order__c/fields/PNR__c.field-meta.xml
<CustomField>
    <fullName>PNR__c</fullName>
    <label>PNR</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PNR__c/PNR__c.object-meta.xml
<CustomObject>
    <label>PNR (Old)</label>
    <nameField>
        <label>PNR Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PNR (Old)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PNR__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>order__c</referenceTo>
    <relationshipLabel>PNR</relationshipLabel>
    <relationshipName>PNR</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/classes/RestSabreListener.cls
@RestResource(urlMapping='/pnrevents/*')
global class RestSabreListener {

    @HttpPost
    global static void handlePost() {
        try {

            RestContext.response.statusCode = 202;
            String webhookBody = RestContext.request.requestBody.toString();
            SabrePNRUpdateInboundRequest.PNRCHNG pnrChange = SabrePNRUpdateInboundRequest.parsePnrChange(webhookBody);

            if (pnrChange.notificationType == 'PNRCHNG') {
                String pnrName = pnrChange.locator;

                PNR__c pnr = [SELECT Id, Name, Order__c FROM PNR__c WHERE Name = :pnrName];

                PNR__c newPnr = new PNR__c();
                newPnr.Name = pnrName;
                newPnr.Order__c = pnr.Order__c;

                //delete pnr;
                System.debug('pnr to delete: ' + pnr);
                //insert newPnr;
                System.debug('newPnr to insert ' + newPnr);
            }

        } catch (Exception e) {
            //do some error handling
            System.debug('pnrevents POST Listener no good');
            RestContext.response.statusCode = 202;
        }
    }

    @HttpGet
    global static void handleGet() {

        // Purely for Sabre validation
        RestContext.response.statusCode = 202;

    }

}