force-app/main/default/objects/order__c/order__c.object-meta.xml
<CustomObject>
    <label>orders</label>
    <nameField>
        <displayFormat>{00}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>order</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/order__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <formula>Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/order__c/fields/order_status__c.field-meta.xml
<CustomField>
    <fullName>order_status__c</fullName>
    <inlineHelpText>OH - Order is held|
con - Order paid awaiting PIF|
RFE - PIF/PAX = QTY|
Ex - Order is locked, ticketing has begun|
pending C - If purchaser cancels order|
cancelled - Auto set by booking status DNT|
expired - Not required</inlineHelpText>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>On Hold</fullName>
                <default>true</default>
                <label>On Hold</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Ready For Export</fullName>
            </value>
            <value>
                <fullName>Exported</fullName>
            </value>
            <value>
                <fullName>Pending Cancellation</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Migrate</fullName>
            </value>
            <value>
                <fullName>Migrated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BatchLegacyOrderUpdateToMigrated.cls
global class BatchLegacyOrderUpdateToMigrated implements Database.Batchable<sObject> , Database.Stateful{

    global Database.QueryLocator start(Database.BatchableContext bc)
    {
        return Database.getQueryLocator([Select id, order_status__c  from order__c where order_status__c ='Migrate']);
    }
    
    global void execute(Database.BatchableContext bc, List<order__c> legacyOrder){
		
 
		List<order__c> ordToUpdate = new List<order__c>();	        
        for(order__c ord : legacyOrder){
            ord.order_status__c = 'Migrated';
            ordToUpdate.add(ord);
        }  
        
        if(!ordToUpdate.isEmpty()){
            update ordToUpdate;
        }
        
    }
    
    global void finish(Database.BatchableContext bc)
    {
        
    }
}