force-app/main/default/objects/AE_SB__c/AE_SB__c.object-meta.xml
<CustomObject>
    <label>AE/SB</label>
    <nameField>
        <label>AE/SB Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AE/SB</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AE_SB__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>AE/SB</relationshipLabel>
    <relationshipName>AE_SB</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/airline_upgrade__c/airline_upgrade__c.object-meta.xml
<CustomObject>
    <label>airline upgrade</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>airline upgrade</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/airline_upgrade__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>airline upgrade</relationshipLabel>
    <relationshipName>airline_upgrade</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Carrier__c/Carrier__c.object-meta.xml
<CustomObject>
    <label>Carrier</label>
    <nameField>
        <displayFormat>Car-{000}</displayFormat>
        <label>Carrier Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Carriers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Carrier__c/fields/Carrier_Price__c.field-meta.xml
<CustomField>
    <fullName>Carrier_Price__c</fullName>
    <label>Carrier Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Carrier__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Carriers</relationshipLabel>
    <relationshipName>Carriers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Carrier_Addon_Junction__c/Carrier_Addon_Junction__c.object-meta.xml
<CustomObject>
    <label>Carrier Addon Junction</label>
    <nameField>
        <displayFormat>CAJ-{000}</displayFormat>
        <label>Carrier Addon Junction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Carrier Addon Junctions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Carrier_Addon_Junction__c/fields/AE_SB__c.field-meta.xml
<CustomField>
    <fullName>AE_SB__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AE/SB</label>
    <referenceTo>AE_SB__c</referenceTo>
    <relationshipLabel>Carrier Addon Junctions</relationshipLabel>
    <relationshipName>Carrier_Addon_Junctions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Carrier_Addon_Junction__c/fields/airline_upgrade__c.field-meta.xml
<CustomField>
    <fullName>airline_upgrade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>airline upgrade</label>
    <referenceTo>airline_upgrade__c</referenceTo>
    <relationshipLabel>Carrier Addon Junctions</relationshipLabel>
    <relationshipName>Carrier_Addon_Junctions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Carrier_Addon_Junction__c/fields/Carrier__c.field-meta.xml
<CustomField>
    <fullName>Carrier__c</fullName>
    <label>Carrier</label>
    <referenceTo>Carrier__c</referenceTo>
    <relationshipLabel>Carrier Addon Junctions</relationshipLabel>
    <relationshipName>Carrier_Addon_Junctions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Carrier_Addon_Junction__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Carrier Addon Junctions</relationshipLabel>
    <relationshipName>Carrier_Addon_Junctions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Carrier_Addon_Junction__c/fields/stopover__c.field-meta.xml
<CustomField>
    <fullName>stopover__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>stopover</label>
    <referenceTo>stopover__c</referenceTo>
    <relationshipLabel>Carrier Addon Junctions</relationshipLabel>
    <relationshipName>Carrier_Addon_Junctions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Carrier_Addon_Junction__c/fields/sub_stopover__c.field-meta.xml
<CustomField>
    <fullName>sub_stopover__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>sub stopover</label>
    <referenceTo>sub_stopover__c</referenceTo>
    <relationshipLabel>Carrier Addon Junctions</relationshipLabel>
    <relationshipName>Carrier_Addon_Junctions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal__c/Deal__c.object-meta.xml
<CustomObject>
    <label>Deal</label>
    <nameField>
        <label>Deal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal__c/fields/Allocation_by__c.field-meta.xml
<CustomField>
    <fullName>Allocation_by__c</fullName>
    <label>Allocation by</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Deal</fullName>
                <default>true</default>
                <label>Deal</label>
            </value>
            <value>
                <fullName>Option</fullName>
            </value>
            <value>
                <fullName>Sub option</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal__c/fields/Arrival_Airport_Code__c.field-meta.xml
<CustomField>
    <fullName>Arrival_Airport_Code__c</fullName>
    <label>Arrival Airport Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal__c/fields/deal_archetype__c.field-meta.xml
<CustomField>
    <fullName>deal_archetype__c</fullName>
    <label>Deal Archetype</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MADU1</fullName>
            </value>
            <value>
                <fullName>MADUZ1</fullName>
            </value>
            <value>
                <fullName>MADU2</fullName>
            </value>
            <value>
                <fullName>MADUZ2</fullName>
            </value>
            <value>
                <fullName>TAIU1</fullName>
            </value>
            <value>
                <fullName>TAIZ1</fullName>
            </value>
            <value>
                <fullName>TAIUZ1</fullName>
            </value>
            <value>
                <fullName>TAIU2</fullName>
            </value>
            <value>
                <fullName>TAIZ2</fullName>
            </value>
            <value>
                <fullName>TAIUZ2</fullName>
            </value>
            <value>
                <fullName>TANU1</fullName>
            </value>
            <value>
                <fullName>TANZ1</fullName>
            </value>
            <value>
                <fullName>TANUZ1</fullName>
            </value>
            <value>
                <fullName>TANU2</fullName>
            </value>
            <value>
                <fullName>TANZ2</fullName>
            </value>
            <value>
                <fullName>TANUZ2</fullName>
            </value>
            <value>
                <fullName>MANU1</fullName>
            </value>
            <value>
                <fullName>MANUZ1</fullName>
            </value>
            <value>
                <fullName>MANU2</fullName>
            </value>
            <value>
                <fullName>MANUZ2</fullName>
            </value>
            <value>
                <fullName>RADU1</fullName>
            </value>
            <value>
                <fullName>RADUZ1</fullName>
            </value>
            <value>
                <fullName>RADU2</fullName>
            </value>
            <value>
                <fullName>RADUZ2</fullName>
            </value>
            <value>
                <fullName>CAIU1</fullName>
            </value>
            <value>
                <fullName>CAIZ1</fullName>
            </value>
            <value>
                <fullName>CAIUZ1</fullName>
            </value>
            <value>
                <fullName>CAIU2</fullName>
            </value>
            <value>
                <fullName>CAIZ2</fullName>
            </value>
            <value>
                <fullName>CAIUZ2</fullName>
            </value>
            <value>
                <fullName>CANU1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal__c/fields/deal_type__c.field-meta.xml
<CustomField>
    <fullName>deal_type__c</fullName>
    <label>deal type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>travel</fullName>
            </value>
            <value>
                <fullName>cruise</fullName>
            </value>
            <value>
                <fullName>stay</fullName>
            </value>
            <value>
                <fullName>Siteminder Hotel</fullName>
            </value>
            <value>
                <fullName>Experiences</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal__c/fields/Departure_Airport_Code__c.field-meta.xml
<CustomField>
    <fullName>Departure_Airport_Code__c</fullName>
    <label>Departure Airport Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal__c/fields/Flight_Book_By__c.field-meta.xml
<CustomField>
    <fullName>Flight_Book_By__c</fullName>
    <label>Flight Book By</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Deal__c/fields/merchant_sharing_deadline__c.field-meta.xml
<CustomField>
    <fullName>merchant_sharing_deadline__c</fullName>
    <inlineHelpText>Number of days prior to departure that merchant will receive booking confirmation. If multi-merchant deal, please use the most restrictive deadline e.g 120 days instead of 90.</inlineHelpText>
    <label>Merchant Sharing Deadline - Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Deal__c/fields/merchant_sharing_deadline_date__c.field-meta.xml
<CustomField>
    <fullName>merchant_sharing_deadline_date__c</fullName>
    <inlineHelpText>Date that merchant is to receive booking confirmation. If multi-merchant deal, please use the most restrictive deadline.</inlineHelpText>
    <label>Merchant Sharing Deadline - Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Deal__c/fields/PIF_Module__c.field-meta.xml
<CustomField>
    <fullName>PIF_Module__c</fullName>
    <label>PIF Module</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hotel Only</fullName>
            </value>
            <value>
                <fullName>Passenger Detail</fullName>
            </value>
            <value>
                <fullName>Passenger Address</fullName>
            </value>
            <value>
                <fullName>Passenger Passport</fullName>
            </value>
            <value>
                <fullName>Requests</fullName>
            </value>
            <value>
                <fullName>Emergency Contact</fullName>
            </value>
            <value>
                <fullName>Height and Weight</fullName>
            </value>
            <value>
                <fullName>Passport Mandatory</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal__c/fields/Send_Merchant_Confirmation_email__c.field-meta.xml
<CustomField>
    <fullName>Send_Merchant_Confirmation_email__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send Merchant Confirmation email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Deal__c/recordTypes/Hotel.recordType-meta.xml
<RecordType>
    <fullName>Hotel</fullName>
    <active>true</active>
    <description>This isa new Record Type, for integrating with Siteminder/TravelClcik (Deal shall work as the primary object -- HOTEL).</description>
    <label>Hotel</label>
</RecordType>

force-app/main/default/objects/stopover__c/stopover__c.object-meta.xml
<CustomObject>
    <label>stopover</label>
    <nameField>
        <label>id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>stopover</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/stopover__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>stopover</relationshipLabel>
    <relationshipName>stopover</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/sub_stopover__c/sub_stopover__c.object-meta.xml
<CustomObject>
    <label>sub stopover</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>sub stopover</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sub_stopover__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>sub stopover</relationshipLabel>
    <relationshipName>sub_stopover</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sub_stopover__c/fields/stopover__c.field-meta.xml
<CustomField>
    <fullName>stopover__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>stopover</label>
    <referenceTo>stopover__c</referenceTo>
    <relationshipLabel>sub stopover</relationshipLabel>
    <relationshipName>sub_stopover</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/flightCustomisationTest.cls
@isTest
public class flightCustomisationTest  {

    @isTest
    public static void testMethod1(){
        
        List<RecordType> RCTProductPartner = TADUtils.getRecordType(Label.TAD_RT_Product_Partner);
        Account acctBussiness = TestDataFactory.createBussinessAccount(RCTProductPartner[0].Id);   // Bussiness account Inserted
        acctBussiness.Merchant_Type__c='Multi Line Expense';
        
        insert acctBussiness;
        
        List<RecordType> RCTTadDeal = TADUtils.getRecordType(Label.TAD_RT_TAD_Deal);
        
        list<String> dealId = new list<String>();
        
        List<Deal__c> dealList = new List<Deal__c>();
        Deal__c deal = TestDataFactory.createMerchantDeal(RCTTadDeal[0].Id , acctBussiness.Id );   // Deals created
        deal.Allocation_by__c='Deal';
        deal.deal_type__c ='stay';
        deal.deal_archetype__c = 'CANU1';
        deal.PIF_Module__c = 'Hotel Only';
        //deal.merchant_sharing_deadline__c = 60;
        deal.merchant_sharing_deadline_date__c = system.today().addDays(-6);
        
        deal.Send_Merchant_Confirmation_email__c = true;
        deal.Arrival_Airport_Code__c = 'AUH';
        deal.Departure_Airport_Code__c = 'SYD';
        
        dealList.add(deal);
        dealId.add(deal.Id);
        
        deal__c deal1 = TestDataFactory.createMerchantdeal(RCTTaddeal[0].Id , acctBussiness.Id );   // deal1s created
        deal1.Allocation_by__c='Deal';
        deal1.Flight_Book_By__c = 1;
        deal1.deal_type__c ='stay';
        deal1.deal_archetype__c = 'CANU1';
        deal1.PIF_Module__c = 'Hotel Only';
        //deal1.merchant_sharing_deadline__c = 60;
        deal1.merchant_sharing_deadline_date__c = system.today().addDays(-6);
        
        deal1.Send_Merchant_Confirmation_email__c = true;
        deal1.Arrival_Airport_Code__c = 'SYD';
        deal1.Departure_Airport_Code__c = 'AUH';
        
        dealList.add(deal1);
        dealId.add(deal1.Id);
        
        insert dealList;
        
        AE_SB__c aesb = TestDataFactory.createAE_SBBasic(deal);
        insert aesb;
        airline_upgrade__c airlineUpgrade = TestDataFactory.airlineUpgrade(deal);
        insert airlineUpgrade;
        stopover__c stopOver = TestDataFactory.createStopover(deal);
        insert stopOver;
        sub_stopover__c substopover = TestDataFactory.createSubStopover(deal);
        insert substopover;
        
        Carrier__c carrier= new carrier__c();
        carrier.Deal__c = deal.id;
        carrier.Carrier_Price__c = 200;
        carrier.Carrier_Group__c = 'Emirates';
        insert carrier;
        
        Carrier_Addon_Junction__c caj = new Carrier_Addon_Junction__c();
        caj.deal__c = deal.id;
        caj.airline_upgrade__c = airlineUpgrade.id;
        caj.Carrier__c=carrier.id;
        insert caj;
        list<flightCustomisation.CarrierAddon> caListSave = new list<flightCustomisation.CarrierAddon>();
        flightCustomisation.CarrierAddon ca =new flightCustomisation.CarrierAddon();
        ca.addon = aesb.id;
        ca.carrier='Emirates';
        ca.type='aesb';
        caListSave.add(ca);
        
        flightCustomisation.CarrierAddon ca1 =new flightCustomisation.CarrierAddon();
        ca1.addon = airlineUpgrade.id;
        ca1.carrier='Emirates';
        ca1.type='airlineUpgrade';
        caListSave.add(ca1);
        
        flightCustomisation.CarrierAddon ca2 =new flightCustomisation.CarrierAddon();
        ca2.addon = substopover.id;
        ca2.carrier='Emirates';
        ca2.type='stopOver';
        caListSave.add(ca2);
        
        flightCustomisation.getDealData(deal.id);
        flightCustomisation.getCarriers(deal.id);
        flightCustomisation.getCarrierAddons(deal.id);
        flightCustomisation.getAESB(deal.id);
        flightCustomisation.getAirLineUpgrade(deal.id);
        //flightCustomisation.getStopOver(deal.id);
        flightCustomisation.saveRecords(caListSave,deal.id);
        flightCustomisation.deleteRecords(caListSave,deal.id);
    }
}