force-app/main/default/objects/AE_SB__c/AE_SB__c.object-meta.xml
<CustomObject>
    <label>AE/SB</label>
    <nameField>
        <label>AE/SB Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AE/SB</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AE_SB__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>AE/SB</relationshipLabel>
    <relationshipName>AE_SB</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Allocation__c/Allocation__c.object-meta.xml
<CustomObject>
    <description>Auto Generated Name: {DEAL ID}-{DATE}-{POOL DIFFERENTIATOR} Example 1234-2020-11-1-A</description>
    <label>Allocation</label>
    <nameField>
        <label>Allocation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Allocation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Allocation__c/fields/deal__c.field-meta.xml
<CustomField>
    <fullName>deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Allocation</relationshipLabel>
    <relationshipName>Allocation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal__c/Deal__c.object-meta.xml
<CustomObject>
    <label>Deal</label>
    <nameField>
        <label>Deal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal__c/fields/Allocation_by__c.field-meta.xml
<CustomField>
    <fullName>Allocation_by__c</fullName>
    <label>Allocation by</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Deal</fullName>
                <default>true</default>
                <label>Deal</label>
            </value>
            <value>
                <fullName>Option</fullName>
            </value>
            <value>
                <fullName>Sub option</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal__c/fields/deal_archetype__c.field-meta.xml
<CustomField>
    <fullName>deal_archetype__c</fullName>
    <label>Deal Archetype</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MADU1</fullName>
            </value>
            <value>
                <fullName>MADUZ1</fullName>
            </value>
            <value>
                <fullName>MADU2</fullName>
            </value>
            <value>
                <fullName>MADUZ2</fullName>
            </value>
            <value>
                <fullName>TAIU1</fullName>
            </value>
            <value>
                <fullName>TAIZ1</fullName>
            </value>
            <value>
                <fullName>TAIUZ1</fullName>
            </value>
            <value>
                <fullName>TAIU2</fullName>
            </value>
            <value>
                <fullName>TAIZ2</fullName>
            </value>
            <value>
                <fullName>TAIUZ2</fullName>
            </value>
            <value>
                <fullName>TANU1</fullName>
            </value>
            <value>
                <fullName>TANZ1</fullName>
            </value>
            <value>
                <fullName>TANUZ1</fullName>
            </value>
            <value>
                <fullName>TANU2</fullName>
            </value>
            <value>
                <fullName>TANZ2</fullName>
            </value>
            <value>
                <fullName>TANUZ2</fullName>
            </value>
            <value>
                <fullName>MANU1</fullName>
            </value>
            <value>
                <fullName>MANUZ1</fullName>
            </value>
            <value>
                <fullName>MANU2</fullName>
            </value>
            <value>
                <fullName>MANUZ2</fullName>
            </value>
            <value>
                <fullName>RADU1</fullName>
            </value>
            <value>
                <fullName>RADUZ1</fullName>
            </value>
            <value>
                <fullName>RADU2</fullName>
            </value>
            <value>
                <fullName>RADUZ2</fullName>
            </value>
            <value>
                <fullName>CAIU1</fullName>
            </value>
            <value>
                <fullName>CAIZ1</fullName>
            </value>
            <value>
                <fullName>CAIUZ1</fullName>
            </value>
            <value>
                <fullName>CAIU2</fullName>
            </value>
            <value>
                <fullName>CAIZ2</fullName>
            </value>
            <value>
                <fullName>CAIUZ2</fullName>
            </value>
            <value>
                <fullName>SANUZ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal__c/fields/Deal_Draft__c.field-meta.xml
<CustomField>
    <fullName>Deal_Draft__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal Draft</label>
    <referenceTo>Deal_Draft__c</referenceTo>
    <relationshipLabel>Deal</relationshipLabel>
    <relationshipName>Deal</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal__c/fields/deal_type__c.field-meta.xml
<CustomField>
    <fullName>deal_type__c</fullName>
    <label>deal type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>travel</fullName>
            </value>
            <value>
                <fullName>cruise</fullName>
            </value>
            <value>
                <fullName>stay</fullName>
            </value>
            <value>
                <fullName>Siteminder Hotel</fullName>
            </value>
            <value>
                <fullName>Experiences</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal__c/fields/number_of_days__c.field-meta.xml
<CustomField>
    <fullName>number_of_days__c</fullName>
    <label>number of days</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Deal__c/fields/per_night_allocation__c.field-meta.xml
<CustomField>
    <fullName>per_night_allocation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Per Night Allocation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Deal_Draft__c/Deal_Draft__c.object-meta.xml
<CustomObject>
    <description>This object is a child object to Deal and provides details for the deal provided by the BDM and also &quot;proofed content&quot; for Product Analysts which are then used by Publishers.

This includes information for both AU and NZ</description>
    <label>Deal Draft</label>
    <nameField>
        <label>Deal Draft Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal Drafts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Draft__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Deal Drafts</relationshipLabel>
    <relationshipName>Deal_Drafts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/departure_cities__c/departure_cities__c.object-meta.xml
<CustomObject>
    <label>departure cities</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>departure cities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/departure_cities__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>departure cities</relationshipLabel>
    <relationshipName>departure_cities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/departures_dates__c.object-meta.xml
<CustomObject>
    <label>departures dates</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>departures dates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/departures_dates__c/fields/allocation__c.field-meta.xml
<CustomField>
    <fullName>allocation__c</fullName>
    <label>TOTAL v2 ALLOCATION</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>departures dates</relationshipLabel>
    <relationshipName>departures_dates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Itinerary__c/Itinerary__c.object-meta.xml
<CustomObject>
    <label>Itinerary</label>
    <nameField>
        <displayFormat>Itinerary-{00000}</displayFormat>
        <label>Itinerary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Itineraries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Itinerary__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Itinerarys</relationshipLabel>
    <relationshipName>Itinerarys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/land_activity__c/land_activity__c.object-meta.xml
<CustomObject>
    <label>land activity</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>land activity</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/land_activity__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>land activity</relationshipLabel>
    <relationshipName>land_activity</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/options__c/options__c.object-meta.xml
<CustomObject>
    <label>Options</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/options__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipName>options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/options__c/recordTypes/Option.recordType-meta.xml
<RecordType>
    <fullName>Option</fullName>
    <active>true</active>
    <description>This is a record type for creating a normal Option Record.</description>
    <label>Option</label>
</RecordType>

force-app/main/default/objects/order_line_item__c/order_line_item__c.object-meta.xml
<CustomObject>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>OLI-{000000}</displayFormat>
        <label>Order Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/order_line_item__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sub_options__c/sub_options__c.object-meta.xml
<CustomObject>
    <label>Sub Options</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/sub_options__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Sub Options</relationshipLabel>
    <relationshipName>Sub_Options</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sub_stopover__c/sub_stopover__c.object-meta.xml
<CustomObject>
    <label>sub stopover</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>sub stopover</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sub_stopover__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>sub stopover</relationshipLabel>
    <relationshipName>sub_stopover</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AB_TestAuraComponentControllerTest.cls
@istest
public class AB_TestAuraComponentControllerTest {

    @isTest
    static void testMethod1(){
        List<RecordType> RCTProductPartner = TADUtils.getRecordType(Label.TAD_RT_Product_Partner);
        
        Account acctBussiness = TestDataFactory.createBussinessAccount(RCTProductPartner[0].Id);   // Bussiness account Inserted
        insert acctBussiness;
        
        List<RecordType> RCTTadDeal = TADUtils.getRecordType(Label.TAD_RT_TAD_Deal);
        
        // Inserting Deal with Allocation By Deal
        Deal__c deal = TestDataFactory.createMerchantDeal(RCTTadDeal[0].Id , acctBussiness.Id );   // Deals created
        deal.Allocation_by__c = 'Deal';
        deal.number_of_days__c = 12;
        deal.deal_type__c = 'travel';
        deal.per_night_allocation__c = true;
        deal.deal_archetype__c = 'SANUZ';
        insert deal;
        
        
        // Inserting Deal Draft for Deal with Allocation by Deal
        Deal_Draft__c dealDraft = new Deal_Draft__c();
        dealDraft.Deal__c = deal.Id;
        dealDraft.Name = deal.Name;
        insert dealDraft;  
        
        
        // Inserting Options for Deal with Allocation by Deal
        options__c options = TestDataFactory.CreateOptions(deal.Id);       // Options crested using the deal
        insert options;
        
        
        
        // Inserting sub options for Deal with allocation by Deal
        sub_options__c subOptions = TestDataFactory.createSubOptions(options.Id);   // Sub options created
        insert subOptions;
        
        
        
        //Creating Allocations for Deal with Allocation by Deal
        Allocation__c allocation = TestDataFactory.createAllocationDeal(deal);
        insert allocation;
        
        
        //Creating departure dates for Deal with Allocation by Option
        departures_dates__c departureDates1 = TestDataFactory.createDDWithAllocation(deal,options,subOptions,allocation);  // Departure dates data created
        departureDates1.options__c = options.Id;
        departureDates1.HSS__c = true;
        //departureDates1.Deal__c = null;
        
        insert departureDates1;
        system.debug('status....'+departureDates1.online_status__c);
        //Creating departure dates for Deal with Allocation by Deal
        departures_dates__c departureDates = TestDataFactory.createDDWithAllocation(deal,options,subOptions,allocation); 
        departureDates.Linked_Deal_D_O_S__c = deal.Id;
        departureDates.MinNotMetApproval__c = 'Processed';
        departureDates.online_status__c ='Online';
        departureDates.Deal__c = deal.id;
        insert departureDates;
        
        //Creating departure dates for Deal with Allocation by Deal
        departures_dates__c departureDates2 = TestDataFactory.createDDWithAllocation(deal,options,subOptions,allocation); 
        departureDates2.Linked_Deal_D_O_S__c = deal.Id;
        departureDates2.MinNotMetApproval__c = 'Not Required';
        departureDates2.online_status__c ='Online';
        departureDates2.Deal__c = deal.id;
        insert departureDates2;
        
        
        //Creating departure cities for Deal with Allocation by Deal
        departure_cities__c departureCities = TestDataFactory.createDepartureCities(deal.Id);       // Departure cities created
        insert departureCities;
        
        
        
        // Creating itinerary for Deal with Allocation by Deal        
        Itinerary__c itinerary = TestDataFactory.createItinerary(deal,'Main Package',1);
        insert itinerary;
        
        
        
        // Creating Sub Stopovers for Deal with allocation by Deal
        sub_stopover__c subStopover = TestDataFactory.createSubStopover(deal);
        insert subStopover;
        
        
        
        //Creating Land Activity for Deal with allocation by Deal
        land_activity__c la = TestDataFactory.createLandActivity(deal, itinerary);
        insert la;
        
        Map<String,Deal__c> dealMap = new Map<String,Deal__c>();
        dealMap.put('CreateAESBRecords',deal);
        List<AE_SB__c> listOfAESBs = TestDataFactory.createTestAESBs(dealMap);
        insert listOfAESBs; 
        
        List<RecordType> RCTPersonAccount = TADUtils.getRecordType(Label.TAD_RT_TAD_Person_Account);
        Account acctPerson = TestDataFactory.createPersonAccount(RCTPersonAccount[0].Id);
        insert acctPerson;
        
        Test.startTest();
        Id recrdTypeTADId = TADUtils.getRecordTypeList('TAD','TAD_Order__c');
        
        //Inserting TAD Order for Deal with Allocation by Deal
        TAD_Order__c orders = TestDataFactory.createTADOrder(acctPerson, deal , options , departureDates , recrdTypeTADId); // orders created for the controller using person account and deals using bussiness account
        orders.ordexp_deal__c = deal.id;
        insert orders;
        
        system.debug('Looking at the departure date value of this order:::'+orders.ordexp_departure_date__r.date__c);
        
        //Creating OLI for Deal with Allocation by Deal
        Order_Line_Item__c oli1 = TestDataFactory.createOrderLineItem(orders,subOptions,departureCities,'2',options,deal);
        oli1.Quantity__c = '2';
        insert oli1;
        
        ABTest_AuraComponentController.getIframeURL(orders.Id);
        
        Test.stopTest();
    }
    
}