force-app/main/default/objects/AE_SB__c/AE_SB__c.object-meta.xml
<CustomObject>
    <label>AE/SB</label>
    <nameField>
        <label>AE/SB Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AE/SB</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AE_SB__c/fields/price_nz__c.field-meta.xml
<CustomField>
    <fullName>price_nz__c</fullName>
    <label>Price - NZD</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/airline_upgrade__c/airline_upgrade__c.object-meta.xml
<CustomObject>
    <label>airline upgrade</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>airline upgrade</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/airline_upgrade__c/fields/price_nz__c.field-meta.xml
<CustomField>
    <fullName>price_nz__c</fullName>
    <label>Price - NZD</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/departure_cities__c/departure_cities__c.object-meta.xml
<CustomObject>
    <label>departure cities</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>departure cities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/departure_cities__c/fields/Surcharge__c.field-meta.xml
<CustomField>
    <fullName>Surcharge__c</fullName>
    <label>Surcharge</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/departure_cities__c/fields/surcharge_nz__c.field-meta.xml
<CustomField>
    <fullName>surcharge_nz__c</fullName>
    <label>Surcharge - NZD</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/departures_dates__c.object-meta.xml
<CustomObject>
    <label>departures dates</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>departures dates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/departures_dates__c/fields/HSS__c.field-meta.xml
<CustomField>
    <fullName>HSS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>HSS</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/HSS_amount__c.field-meta.xml
<CustomField>
    <fullName>HSS_amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>HSS amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/HSS_amount_nz__c.field-meta.xml
<CustomField>
    <fullName>HSS_amount_nz__c</fullName>
    <defaultValue>0</defaultValue>
    <label>HSS_Amount - NZ</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/HSS_Cost__c.field-meta.xml
<CustomField>
    <fullName>HSS_Cost__c</fullName>
    <label>HSS Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/HSS_nz__c.field-meta.xml
<CustomField>
    <fullName>HSS_nz__c</fullName>
    <defaultValue>false</defaultValue>
    <label>HSS - NZ</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/PRICE__c.field-meta.xml
<CustomField>
    <fullName>PRICE__c</fullName>
    <formula>IF( NOT(ISBLANK( Deal__c )) ,  Deal__r.price__c  , IF(NOT(ISBLANK( DealID_from_Option__c )),  options__r.price__c  ,  sub_options__r.Price1__c  ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PRICE</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/departures_dates__c/fields/sub_options__c.field-meta.xml
<CustomField>
    <fullName>sub_options__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>sub options</label>
    <referenceTo>sub_options__c</referenceTo>
    <relationshipLabel>departures dates</relationshipLabel>
    <relationshipName>departures_dates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/General_Pricing__c/General_Pricing__c.object-meta.xml
<CustomObject>
    <label>General Pricing</label>
    <nameField>
        <displayFormat>GP-{0000000}</displayFormat>
        <label>General Pricing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>General Pricings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/General_Pricing__c/fields/AE_SB__c.field-meta.xml
<CustomField>
    <fullName>AE_SB__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AE/SB</label>
    <referenceTo>AE_SB__c</referenceTo>
    <relationshipLabel>General Pricings</relationshipLabel>
    <relationshipName>General_Pricings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/General_Pricing__c/fields/Airline_Upgrade__c.field-meta.xml
<CustomField>
    <fullName>Airline_Upgrade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Airline Upgrade</label>
    <referenceTo>airline_upgrade__c</referenceTo>
    <relationshipLabel>General Pricings</relationshipLabel>
    <relationshipName>General_Pricings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/General_Pricing__c/fields/Departure_City__c.field-meta.xml
<CustomField>
    <fullName>Departure_City__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Departure City</label>
    <referenceTo>departure_cities__c</referenceTo>
    <relationshipLabel>General Pricings</relationshipLabel>
    <relationshipName>General_Pricings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/General_Pricing__c/fields/Departures_dates__c.field-meta.xml
<CustomField>
    <fullName>Departures_dates__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Departures dates</label>
    <referenceTo>departures_dates__c</referenceTo>
    <relationshipLabel>General Pricings</relationshipLabel>
    <relationshipName>General_Pricings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/General_Pricing__c/fields/HSS_Amount__c.field-meta.xml
<CustomField>
    <fullName>HSS_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>HSS Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/General_Pricing__c/fields/HSS_Amount_NZ__c.field-meta.xml
<CustomField>
    <fullName>HSS_Amount_NZ__c</fullName>
    <defaultValue>0</defaultValue>
    <label>HSS Amount NZ</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/General_Pricing__c/fields/HSS_Cost__c.field-meta.xml
<CustomField>
    <fullName>HSS_Cost__c</fullName>
    <defaultValue>0</defaultValue>
    <label>HSS Cost</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/General_Pricing__c/fields/Land_Activity__c.field-meta.xml
<CustomField>
    <fullName>Land_Activity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Land Activity</label>
    <referenceTo>land_activity__c</referenceTo>
    <relationshipLabel>General Pricings</relationshipLabel>
    <relationshipName>General_Pricings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/General_Pricing__c/fields/Price_Airline_upgrade__c.field-meta.xml
<CustomField>
    <fullName>Price_Airline_upgrade__c</fullName>
    <label>Price</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/General_Pricing__c/fields/Price_Airline_upgrade_NZD__c.field-meta.xml
<CustomField>
    <fullName>Price_Airline_upgrade_NZD__c</fullName>
    <label>Price - NZD</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/General_Pricing__c/fields/Price_AUD__c.field-meta.xml
<CustomField>
    <fullName>Price_AUD__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Price - AUD</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/General_Pricing__c/fields/Price_NZD__c.field-meta.xml
<CustomField>
    <fullName>Price_NZD__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Price - NZD</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/General_Pricing__c/fields/Solo_Surcharge_AUD__c.field-meta.xml
<CustomField>
    <fullName>Solo_Surcharge_AUD__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Solo Surcharge - AUD</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/General_Pricing__c/fields/Solo_Surcharge_NZD__c.field-meta.xml
<CustomField>
    <fullName>Solo_Surcharge_NZD__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Solo Surcharge - NZD</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/General_Pricing__c/fields/Sub_Options__c.field-meta.xml
<CustomField>
    <fullName>Sub_Options__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sub Options</label>
    <referenceTo>sub_options__c</referenceTo>
    <relationshipLabel>General Pricings</relationshipLabel>
    <relationshipName>General_Pricings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/General_Pricing__c/fields/Sub_Stopover__c.field-meta.xml
<CustomField>
    <fullName>Sub_Stopover__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stopover</label>
    <referenceTo>sub_stopover__c</referenceTo>
    <relationshipLabel>General Pricings</relationshipLabel>
    <relationshipName>General_Pricings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/General_Pricing__c/fields/Surcharge_AUD__c.field-meta.xml
<CustomField>
    <fullName>Surcharge_AUD__c</fullName>
    <label>Surcharge - AUD</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/General_Pricing__c/fields/Surcharge_NZD__c.field-meta.xml
<CustomField>
    <fullName>Surcharge_NZD__c</fullName>
    <label>Surcharge - NZD</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/land_activity__c/land_activity__c.object-meta.xml
<CustomObject>
    <label>land activity</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>land activity</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/land_activity__c/fields/price__c.field-meta.xml
<CustomField>
    <fullName>price__c</fullName>
    <label>twin price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/land_activity__c/fields/price_nz__c.field-meta.xml
<CustomField>
    <fullName>price_nz__c</fullName>
    <label>Twin Price - NZD</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/sub_options__c/sub_options__c.object-meta.xml
<CustomObject>
    <label>Sub Options</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/sub_options__c/fields/Price1__c.field-meta.xml
<CustomField>
    <fullName>Price1__c</fullName>
    <label>Price1</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/sub_options__c/fields/price__c.field-meta.xml
<CustomField>
    <fullName>price__c</fullName>
    <label>price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/sub_options__c/fields/price_nz__c.field-meta.xml
<CustomField>
    <fullName>price_nz__c</fullName>
    <label>Price - NZD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/sub_options__c/fields/solo_surcharge__c.field-meta.xml
<CustomField>
    <fullName>solo_surcharge__c</fullName>
    <label>solo surcharge</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/sub_options__c/fields/solo_surcharge_nz__c.field-meta.xml
<CustomField>
    <fullName>solo_surcharge_nz__c</fullName>
    <label>Solo Surcharge - NZD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/sub_stopover__c/sub_stopover__c.object-meta.xml
<CustomObject>
    <label>sub stopover</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>sub stopover</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sub_stopover__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price(Twin)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/sub_stopover__c/fields/price_nz__c.field-meta.xml
<CustomField>
    <fullName>price_nz__c</fullName>
    <label>Price(Twin) NZD</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/generalPricingTriggerHandler.cls
public class generalPricingTriggerHandler {
    
    public static void updateRollUpValues(List<General_Pricing__c> gpRecords){
        
        Set<id> subOptionIds = new Set<id>();
        Set<id> depDateIds = new Set<id>();
        Set<id> depCityIds = new Set<id>();
        Set<id> airlineUpgradeIds = new Set<id>();
        Set<id> landActivityIds = new Set<id>();
        Set<id> aesbIds = new Set<id>();
        Set<id> stopOverIds = new Set<id>();
        Set<id> activeGpIds = new Set<id>();
        Map<id,General_Pricing__c> recordVsPricing = new  Map<id,General_Pricing__c>();
        
        for(General_Pricing__c gp : gpRecords){
            activeGpIds.add(gp.id);
            // GP for sub-option
            if(gp.Sub_Options__c !=null){
                subOptionIds.add(gp.Sub_Options__c);
                recordVsPricing.put(gp.Sub_Options__c,gp);                
            }
            
            // GP for depdate
            if(gp.Departures_dates__c  !=null){
                depDateIds.add(gp.Departures_dates__c);
                recordVsPricing.put(gp.Departures_dates__c,gp);                
            }
            // GP for depCity
            if(gp.Departure_City__c  !=null){
                depCityIds.add(gp.Departure_City__c);
                recordVsPricing.put(gp.Departure_City__c,gp);                
            }
            // GP for Airline Upgrade
            if(gp.Airline_Upgrade__c != null){
                airlineUpgradeIds.add(gp.Airline_Upgrade__c);
                recordVsPricing.put(gp.Airline_Upgrade__c,gp);
            }
            // GP for Airline Upgrade
            if(gp.Sub_Stopover__c != null){
                stopOverIds.add(gp.Sub_Stopover__c);
                recordVsPricing.put(gp.Sub_Stopover__c,gp);
            }
            // GP for Land Activity
            if(gp.Land_Activity__c != null){
                landActivityIds.add(gp.Land_Activity__c);
                recordVsPricing.put(gp.Land_Activity__c,gp);
            }
            // GP for AE/SB
             if(gp.AE_SB__c != null){
                aesbIds.add(gp.AE_SB__c);
                recordVsPricing.put(gp.AE_SB__c,gp);
            }
            
        }
        
        // GP Sub Option Logic
        if(!subOptionIds.isEmpty()){
            list<Sub_Options__c> subList = [Select id, Price1__c ,solo_surcharge__c  ,price_nz__c ,solo_surcharge_nz__c  from Sub_Options__c where id in:subOptionIds];
            System.debug('subList'+subList);
            for(Sub_Options__c sub : subList){
                sub.Price1__c=recordVsPricing.get(sub.id).Price_AUD__c;
                sub.solo_surcharge__c=recordVsPricing.get(sub.id).Solo_Surcharge_AUD__c ;
                sub.price_nz__c=recordVsPricing.get(sub.id).Price_NZD__c ;
                sub.solo_surcharge_nz__c=recordVsPricing.get(sub.id).Solo_Surcharge_NZD__c ;
            }
            
            update subList;
            
        }
        
        // GP Dep Date Logic
        if(!depDateIds.isEmpty()){
            list<Departures_dates__c> depList = [Select id, HSS_amount__c ,HSS_Cost__c  ,HSS_amount_nz__c,HSS__c,HSS_nz__c  from Departures_dates__c where id in:depDateIds];
            System.debug('depList'+depList);
            for(Departures_dates__c dep : depList){
                dep.HSS_amount__c=recordVsPricing.get(dep.id).HSS_Amount__c ;
                dep.HSS_Cost__c =recordVsPricing.get(dep.id).HSS_Cost__c ;
                dep.HSS_amount_nz__c =recordVsPricing.get(dep.id).HSS_Amount_NZ__c ;
                if(recordVsPricing.get(dep.id).HSS_Cost__c !=0){
                    dep.HSS__c = true;
                }else{
                    dep.HSS__c = false;
                }
                
                if(recordVsPricing.get(dep.id).HSS_Amount_NZ__c !=0){
                    dep.HSS_nz__c = true;
                }else{
                    dep.HSS_nz__c = false;
                }
                
            }
            update depList;
        }
        //GP DepCity logic
        if(!depCityIds.isEmpty()){
            list<departure_cities__c> depCityList = [Select id, Surcharge__c ,surcharge_nz__c from departure_cities__c where id in:depCityIds];
            for(departure_cities__c depCity :depCityList){
                depCity.Surcharge__c = recordVsPricing.get(depCity.id).Surcharge_AUD__c ;
                depCity.surcharge_nz__c = recordVsPricing.get(depCity.id).Surcharge_NZD__c ;
            }
            update depCityList;
        }
        // GP Airline Upgrade logic
        if(!airlineUpgradeIds.isEmpty()){
            list<airline_upgrade__c> airlineUpgradeList = [select id, price__c,price_nz__c from airline_upgrade__c where id In :airlineUpgradeIds];
            for(airline_upgrade__c au :airlineUpgradeList){
                au.price__c = recordVsPricing.get(au.id).Price_Airline_upgrade__c ;
                au.price_nz__c = recordVsPricing.get(au.id).Price_Airline_upgrade_NZD__c ;
            }
            update airlineUpgradeList;
        }
        // GP Stopover logic
        if(!stopOverIds.isEmpty()){
            list<sub_stopover__c> stopoverList = [select Price_Solo__c, Price__c,site__c,price_nz__c,Price_Solo_nz__c from sub_stopover__c where id In: stopOverIds];
            for(sub_stopover__c st :stopoverList){
                if(st.site__c!=null){
                if(st.site__c.contains('AU')){
                st.Price_Solo__c = recordVsPricing.get(st.id).Stopover_Solo_Price__c;
                st.Price__c = recordVsPricing.get(st.id).Stopover_Twin_Price__c;
                }
                    if(st.site__c.contains('NZ')){
                    st.Price_Solo_nz__c = recordVsPricing.get(st.id).Stopover_Solo_Price__c;
                    st.price_nz__c = recordVsPricing.get(st.id).Stopover_Twin_Price__c;
                }
            }
            }
            update stopoverList;
        }
        // GP Land Actiity logic
        if(!landActivityIds.isEmpty()){
            list<land_activity__c> laList = [select solo_price__c, price__c,site__c,price_nz__c,solo_price_nz__c from land_activity__c where id In: landActivityIds];
            for(land_activity__c la :laList){
                if(la.site__c!=null){
                if(la.site__c.contains('AU')){
                la.solo_price__c = recordVsPricing.get(la.id).LA_Solo_Price__c;
                la.price__c = recordVsPricing.get(la.id).LA_Twin_Price__c;
                }
                if(la.site__c.contains('NZ')){
                    la.solo_price_nz__c = recordVsPricing.get(la.id).LA_Solo_Price__c;
                    la.price_nz__c = recordVsPricing.get(la.id).LA_Twin_Price__c;
                }
               }
            }
            update laList;
        }
        // GP AE/SB logic
        if(!aesbIds.isEmpty()){
            list<AE_SB__c> aesbList = [select id, price__c,price_nz__c,site__c from AE_SB__c where id In :aesbIds];
            for(AE_SB__c aesb :aesbList){
                if(aesb.site__c!=null){
                aesb.price__c = recordVsPricing.get(aesb.id).AE_SB_Price__c ;
                aesb.price_nz__c = recordVsPricing.get(aesb.id).AE_SB_Price_NZD__c ;
                }
            }
            update aesbList;
        }
        
        // deactivate other active General Pricing
        Map<id,General_Pricing__c> gpRecordsToDeActivate = new Map<id,General_Pricing__c>();
        
        if(!gpRecords.isEmpty()){
            List<General_Pricing__c>  gpToUncheck = [Select id,Active__c from General_Pricing__c where (Sub_Options__c IN:subOptionIds or Departures_dates__c IN:depDateIds or Departure_City__c IN:depCityIds or Airline_Upgrade__c IN:airlineUpgradeIds or Sub_Stopover__c IN: stopOverIds or Land_Activity__c IN:landActivityIds or AE_SB__c IN:aesbIds) and  Active__c=true and id NOT IN: activeGpIds ];
            if(!gpToUncheck.isEmpty()){
                for(General_Pricing__c gp : gpToUncheck){
                    gp.Active__c=false;
                    gpRecordsToDeActivate.put(gp.id,gp);
                }
            }
        }
        /*
        if(!gpRecords.isEmpty()){
            List<General_Pricing__c>  gpToUncheck = [Select id,Active__c from General_Pricing__c where Departures_dates__c IN:depDateIds and  Active__c=true and id NOT IN: activeGpIds ];
            if(!gpToUncheck.isEmpty()){
                for(General_Pricing__c gp : gpToUncheck){
                    gp.Active__c=false;
                    gpRecordsToDeActivate.put(gp.id,gp);
                }
            }
        } 
        if(!gpRecords.isEmpty()){
            List<General_Pricing__c>  gpToUncheck = [Select id,Active__c from General_Pricing__c where Departure_City__c IN:depCityIds and  Active__c=true and id NOT IN: activeGpIds ];
            if(!gpToUncheck.isEmpty()){
                for(General_Pricing__c gp : gpToUncheck){
                    gp.Active__c=false;
                    gpRecordsToDeActivate.put(gp.id,gp);
                }
            }
        } 
        if(!gpRecords.isEmpty()){
            List<General_Pricing__c>  gpToUncheck = [Select id,Active__c from General_Pricing__c where Airline_Upgrade__c IN:airlineUpgradeIds and  Active__c=true and id NOT IN: activeGpIds ];
            if(!gpToUncheck.isEmpty()){
                for(General_Pricing__c gp : gpToUncheck){
                    gp.Active__c=false;
                    gpRecordsToDeActivate.put(gp.id,gp);
                }
            }
        } 
        */
        if(!gpRecordsToDeActivate.Isempty()){
            update gpRecordsToDeActivate.values();
        }
        
    }
    
    /*
    public static void deactivateDepDateRecord(Set<String> gpListDep){
        
        List<Departures_dates__c> depDateDisableHss = [Select id,name,(Select id from General_Pricings__r where Active__c= true)  from Departures_dates__c where id IN:gpListDep and (HSS__c=true OR HSS_nz__c=true) ];
        
        Integer gpRecordsSize;
        
        for(String depDate : depDateDisableHss ){
            
            gpRecordsSize = depDate.General_Pricings__r.size();
          
            if(){
                
                
                
            }
        }
        
        
    } */
    
}