force-app/main/default/objects/General_Pricing__c/General_Pricing__c.object-meta.xml
<CustomObject>
    <label>General Pricing</label>
    <nameField>
        <displayFormat>GP-{0000000}</displayFormat>
        <label>General Pricing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>General Pricings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/General_Pricing__c/fields/LA_Solo_Price__c.field-meta.xml
<CustomField>
    <fullName>LA_Solo_Price__c</fullName>
    <label>LA Solo Price</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/General_Pricing__c/fields/LA_Twin_Price__c.field-meta.xml
<CustomField>
    <fullName>LA_Twin_Price__c</fullName>
    <label>LA Twin Price</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/General_Pricing__c/fields/Land_Activity__c.field-meta.xml
<CustomField>
    <fullName>Land_Activity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Land Activity</label>
    <referenceTo>land_activity__c</referenceTo>
    <relationshipLabel>General Pricings</relationshipLabel>
    <relationshipName>General_Pricings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/General_Pricing__c/recordTypes/Land_Activity.recordType-meta.xml
<RecordType>
    <fullName>Land_Activity</fullName>
    <active>true</active>
    <label>Land Activity</label>
</RecordType>

force-app/main/default/objects/land_activity__c/land_activity__c.object-meta.xml
<CustomObject>
    <label>land activity</label>
    <nameField>
        <label>id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>land activity</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/land_activity__c/fields/price__c.field-meta.xml
<CustomField>
    <fullName>price__c</fullName>
    <label>twin price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/land_activity__c/fields/solo_price__c.field-meta.xml
<CustomField>
    <fullName>solo_price__c</fullName>
    <label>solo price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/Tad_BatchToCreateLAGP.cls
public class Tad_BatchToCreateLAGP implements  Database.Batchable<sObject> {

     public Database.QueryLocator start(Database.BatchableContext bc){
         return Database.getQueryLocator('select id,name,solo_price__c,price__c from land_activity__c where id NOT IN (select land_activity__c from 	General_Pricing__c where Active__c = true)');
    }
    public void execute(Database.BatchableContext bc, List<land_activity__c> laRecords){
        List<General_Pricing__c> gpRecordsToInsert = new List<General_Pricing__c>();
        String landActivityRCT = Schema.SObjectType.general_pricing__c.getRecordTypeInfosByDeveloperName().get('Land_Activity').getRecordTypeId();
        for(land_activity__c la:laRecords){
            General_Pricing__c gp= new General_Pricing__c();
            gp.Active__c = true;
            gp.LA_Solo_Price__c = la.solo_price__c;
            gp.LA_Twin_Price__c = la.price__c;
            gp.Land_Activity__c = la.Id;
            gp.RecordTypeId = landActivityRCT;
            gpRecordsToInsert.add(gp);
        }
        try{
            insert gpRecordsToInsert;
        }catch(Exception ex){
            System.debug('Error while creating new gp records for Land Activity'+ex.getMessage());
        }
    } 
    public void finish(Database.BatchableContext bc){
        System.debug('GP records Created successfuly');
    } 
}