force-app/main/default/objects/General_Pricing__c/General_Pricing__c.object-meta.xml
<CustomObject>
    <label>General Pricing</label>
    <nameField>
        <displayFormat>GP-{0000000}</displayFormat>
        <label>General Pricing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>General Pricings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/order_line_item__c/order_line_item__c.object-meta.xml
<CustomObject>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>OLI-{000000}</displayFormat>
        <label>Order Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/order_line_item__c/fields/General_Pricing__c.field-meta.xml
<CustomField>
    <fullName>General_Pricing__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>General Pricing</label>
    <referenceTo>General_Pricing__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/order_line_item__c/fields/OLI_Status__c.field-meta.xml
<CustomField>
    <fullName>OLI_Status__c</fullName>
    <label>OLI Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On Hold</fullName>
                <default>true</default>
                <label>On Hold</label>
            </value>
            <value>
                <fullName>Secured</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/order_line_item__c/fields/ordexp_TAD_Order__c.field-meta.xml
<CustomField>
    <fullName>ordexp_TAD_Order__c</fullName>
    <label>Order</label>
    <referenceTo>TAD_Order__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items_orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/TAD_Order__c.object-meta.xml
<CustomObject>
    <label>TAD Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TAD Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_master_status__c.field-meta.xml
<CustomField>
    <fullName>ordexp_master_status__c</fullName>
    <label>Master status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
                <default>true</default>
                <label>On Hold</label>
            </value>
            <value>
                <fullName>Temporary Hold</fullName>
            </value>
            <value>
                <fullName>Secured</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Travelled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>In Progress-Cruise only</fullName>
                <isActive>false</isActive>
                <label>In Progress-Cruise only</label>
            </value>
            <value>
                <fullName>In Progress-Flight only</fullName>
                <isActive>false</isActive>
                <label>In Progress-Flight only</label>
            </value>
            <value>
                <fullName>In Progress-Flights + Cruise</fullName>
                <isActive>false</isActive>
                <label>In Progress-Flights + Cruise</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TAD_Order__c/fields/ordexp_sub_status__c.field-meta.xml
<CustomField>
    <fullName>ordexp_sub_status__c</fullName>
    <label>Sub status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ordexp_master_status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial Payment Pending</fullName>
            </value>
            <value>
                <fullName>Cancellation Request</fullName>
            </value>
            <value>
                <fullName>Class (Sub Option) - Accom/Cabin Upgrade</fullName>
            </value>
            <value>
                <fullName>Duration/Extention (Option) - Upgrade</fullName>
            </value>
            <value>
                <fullName>Flight Quote Request</fullName>
            </value>
            <value>
                <fullName>Internal Correction/Change</fullName>
            </value>
            <value>
                <fullName>PAX Change Pending</fullName>
            </value>
            <value>
                <fullName>Paid - PIF/s Overdue</fullName>
            </value>
            <value>
                <fullName>Paid - PIF/s Due</fullName>
            </value>
            <value>
                <fullName>Stay Booking - No Ticketing Required</fullName>
            </value>
            <value>
                <fullName>Cabins Pending - Mins Not Met</fullName>
            </value>
            <value>
                <fullName>Flights Pending - Mins Not Met</fullName>
            </value>
            <value>
                <fullName>Flights Pending - Out of Range</fullName>
            </value>
            <value>
                <fullName>Flights Pending - Ready to Ticket</fullName>
            </value>
            <value>
                <fullName>Cabins Pending/Flights Booked - Cabin Ready to Ticket</fullName>
            </value>
            <value>
                <fullName>Cabins Booked</fullName>
            </value>
            <value>
                <fullName>Flights Booked</fullName>
            </value>
            <value>
                <fullName>Cabins Booked/Flights Booked</fullName>
            </value>
            <value>
                <fullName>BC Sent</fullName>
            </value>
            <value>
                <fullName>TP Sent &amp; Cruise Ticket Pending</fullName>
            </value>
            <value>
                <fullName>Travelling</fullName>
            </value>
            <value>
                <fullName>Survey Sent</fullName>
            </value>
            <value>
                <fullName>Survey Returned</fullName>
            </value>
            <value>
                <fullName>Expired/Time out</fullName>
            </value>
            <value>
                <fullName>Offloaded</fullName>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Customer Request</fullName>
            </value>
            <value>
                <fullName>Min Number - Credit/Refund</fullName>
            </value>
            <value>
                <fullName>Pax No Show</fullName>
            </value>
            <value>
                <fullName>Flights Ticketed - NO S/O</fullName>
            </value>
            <value>
                <fullName>Travel Pack Sent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/redirectToAddOnCreateFlowApexController.cls
public class redirectToAddOnCreateFlowApexController {

    @AuraEnabled
    public static string fetchTadOrderStatus(String orderId){
        String toBeReturned = '';
        TAD_Order__c ord = [Select id, ordexp_master_status__c from TAD_Order__c where id =:orderId];
        toBeReturned = ord.ordexp_master_status__c;
        if(ord.ordexp_master_status__c != 'Cancelled'){
             List<General_Pricing__c> gpList = [select Id, Active__c from General_Pricing__c where Id IN (select General_Pricing__c from order_line_item__c where ordexp_TAD_Order__c =:orderId AND OLI_Status__c != 'Secured' AND OLI_Status__c != 'Active') AND Active__c = false];
        if(!gpList.isEmpty()){
            toBeReturned = 'Price has changed.';
        }
        }
        return toBeReturned;
    }
    
    //PBP - 215 Start
    @AuraEnabled
    public static boolean OrderSubStatus(String orderId){
        
        TAD_Order__c ord = [Select id, ordexp_master_status__c,ordexp_sub_status__c from TAD_Order__c where id =:orderId];
        If(ord.ordexp_master_status__c=='In Progress' && (ord.ordexp_sub_status__c=='BC Sent' || ord.ordexp_sub_status__c=='Travel Pack Sent'))
        {
            return true;
        }
        else{
            return false;
        }
    }
    //PBP - 215 Stop
}