force-app/main/default/objects/mp_Quote_Detail_POE__c/mp_Quote_Detail_POE__c.object-meta.xml
<CustomObject>
    <label>Quote Detail</label>
    <nameField>
        <displayFormat>QD-{0000}</displayFormat>
        <label>Quote Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/mp_Quote_Detail_POE__c/fields/Merchant__c.field-meta.xml
<CustomField>
    <fullName>Merchant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Merchant</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quote Details</relationshipLabel>
    <relationshipName>Quote_Details_POE</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/mp_Quote_Detail_POE__c/fields/Merchant_Email__c.field-meta.xml
<CustomField>
    <fullName>Merchant_Email__c</fullName>
    <label>Merchant Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/mp_Quote_Detail_POE__c/fields/mp_Merchant_Currency__c.field-meta.xml
<CustomField>
    <fullName>mp_Merchant_Currency__c</fullName>
    <label>Merchant Currency</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/mp_Quote_Detail_POE__c/fields/mp_Merchant_Price__c.field-meta.xml
<CustomField>
    <fullName>mp_Merchant_Price__c</fullName>
    <label>Merchant Cost</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/mp_Quote_Detail_POE__c/fields/mp_Order_Customisation__c.field-meta.xml
<CustomField>
    <fullName>mp_Order_Customisation__c</fullName>
    <label>Order Customisation</label>
    <referenceTo>Order_Customisations_POE__c</referenceTo>
    <relationshipLabel>Quote Details</relationshipLabel>
    <relationshipName>Quote_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/mp_Quote_Detail_POE__c/fields/Quote_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Quote_Approval_Status__c</fullName>
    <label>Quote Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approve</fullName>
                <label>Quote Received</label>
            </value>
            <value>
                <fullName>Decline</fullName>
                <label>Quote Decline</label>
            </value>
            <value>
                <fullName>Pending</fullName>
                <label>Quote Requested</label>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Acknowledged</fullName>
            </value>
            <value>
                <fullName>Note Only</fullName>
            </value>
            <value>
                <fullName>CustomerApproved</fullName>
                <label>Customer Accepted</label>
            </value>
            <value>
                <fullName>Quote Sent To Customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/mp_Quote_Detail_POE__c/fields/RBA_Exchange_Rate__c.field-meta.xml
<CustomField>
    <fullName>RBA_Exchange_Rate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RBA Exchange Rate</label>
    <referenceTo>RBA_Exchange_Rate__c</referenceTo>
    <relationshipLabel>Quote Details</relationshipLabel>
    <relationshipName>Quote_Details_POE</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/mp_Quote_Detail_POE__c/fields/TAD_Price__c.field-meta.xml
<CustomField>
    <fullName>TAD_Price__c</fullName>
    <label>TAD Price</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order_Customisations_POE__c/Order_Customisations_POE__c.object-meta.xml
<CustomObject>
    <description>Order Customisation 
This is a combination of additional accommodations, flight Customisations and Cruise Customisation</description>
    <label>Order Customisation</label>
    <nameField>
        <displayFormat>Customisatio-{0000}</displayFormat>
        <label>Order Customisations  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Customisations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Customisations_POE__c/fields/mp_tad_order__c.field-meta.xml
<CustomField>
    <fullName>mp_tad_order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TAD Order</label>
    <referenceTo>TAD_Order__c</referenceTo>
    <relationshipLabel>Order Customisations</relationshipLabel>
    <relationshipName>Order_Customisations_POE</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Customisations_POE__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Quote_Requested</fullName>
                <default>true</default>
                <label>Quote Requested</label>
            </value>
            <value>
                <fullName>Accepted_and_Paid</fullName>
                <label>Accepted and Paid</label>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Customer Approved</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
                <isActive>false</isActive>
                <label>Accepted</label>
            </value>
            <value>
                <fullName>Acknowledged</fullName>
                <isActive>false</isActive>
                <label>Acknowledged</label>
            </value>
            <value>
                <fullName>Note Only</fullName>
                <isActive>false</isActive>
                <label>Note Only</label>
            </value>
            <value>
                <fullName>Quote_Received</fullName>
                <isActive>false</isActive>
                <label>Quote Received</label>
            </value>
            <value>
                <fullName>Quoted</fullName>
                <isActive>false</isActive>
                <label>Quoted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Customisations_POE__c/recordTypes/Miscellaneous.recordType-meta.xml
<RecordType>
    <fullName>Miscellaneous</fullName>
    <active>true</active>
    <label>Miscellaneous</label>
</RecordType>

force-app/main/default/objects/RBA_Exchange_Rate__c/RBA_Exchange_Rate__c.object-meta.xml
<CustomObject>
    <description>Exchange Rates modified Daily from RBA Data</description>
    <label>RBA Exchange Rate</label>
    <nameField>
        <label>RBA Exchange Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RBA Exchange Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RBA_Exchange_Rate__c/fields/currency_code__c.field-meta.xml
<CustomField>
    <fullName>currency_code__c</fullName>
    <label>Currency To</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>CAD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>JPY</fullName>
            </value>
            <value>
                <fullName>CNY</fullName>
            </value>
            <value>
                <fullName>IDR</fullName>
            </value>
            <value>
                <fullName>NZD</fullName>
            </value>
            <value>
                <fullName>THB</fullName>
            </value>
            <value>
                <fullName>TWD</fullName>
            </value>
            <value>
                <fullName>WST</fullName>
            </value>
            <value>
                <fullName>ZAR</fullName>
            </value>
            <value>
                <fullName>VND</fullName>
            </value>
            <value>
                <fullName>FJD</fullName>
            </value>
            <value>
                <fullName>MYR</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
            <value>
                <fullName>CHF</fullName>
            </value>
            <value>
                <fullName>INR</fullName>
            </value>
            <value>
                <fullName>NOK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RBA_Exchange_Rate__c/fields/exchange_rate__c.field-meta.xml
<CustomField>
    <fullName>exchange_rate__c</fullName>
    <label>Exchange Rate AUD</label>
    <precision>15</precision>
    <scale>9</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/TAD_Order__c.object-meta.xml
<CustomObject>
    <label>TAD Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TAD Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TAD_Order__c/fields/Merchant__c.field-meta.xml
<CustomField>
    <fullName>Merchant__c</fullName>
    <formula>ordexp_deal__r.Merchant__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Merchant</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TAD_Order__c/recordTypes/TAD.recordType-meta.xml
<RecordType>
    <fullName>TAD</fullName>
    <active>true</active>
    <label>TAD</label>
</RecordType>

force-app/main/default/objects/TAD_Order__c/recordTypes/TC.recordType-meta.xml
<RecordType>
    <fullName>TC</fullName>
    <active>true</active>
    <label>TC</label>
</RecordType>

force-app/main/default/objects/TAD_Order__c/recordTypes/TNZ.recordType-meta.xml
<RecordType>
    <fullName>TNZ</fullName>
    <active>true</active>
    <label>TNZ</label>
</RecordType>

force-app/main/default/objects/TAD_Order__c/recordTypes/WT.recordType-meta.xml
<RecordType>
    <fullName>WT</fullName>
    <active>true</active>
    <label>WT</label>
</RecordType>

force-app/main/default/classes/QuoteDetailTriggerHandler.cls
/**
* ────────────────────────────────────────────────────────────────────────────────────────────────
* TADOrderTriggerHandler
* Purpose: Apex Class Used for QuoteDetailTrigger .
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* @createdBy Vinti Chittora  <vinti.chittora@psagtechnologies.com>
* @lastModifiedBy Bharat Joshi  <bharat.joshi@psagtechnologies.com>

* @version        2.0
* 
* @modified       2020-02-28
* @systemLayer    Apex Class
* ────────────────────────────────────────────────────────────────────────────────────────────────── */


public class QuoteDetailTriggerHandler {
    
    public static void populateFieldValues(List<mp_Quote_Detail_POE__c> newQuoteDetail){
        Map<Id,Account> idAccountMap = new  Map<Id,Account>();
        Map<String,RBA_Exchange_Rate__c> currCodeVsRbaExchangeMap = new  Map<String,RBA_Exchange_Rate__c>();
        Set<Id> accIds = new Set<Id>();
        
        List<RBA_Exchange_Rate__c> rbaExchangeList = [Select id,Name,currency_code__c,exchange_rate__c from RBA_Exchange_Rate__c ];
        
        if(rbaExchangeList != null){
            
            for(RBA_Exchange_Rate__c rba:rbaExchangeList)
            {
                currCodeVsRbaExchangeMap.put(rba.Name,rba);
            }
            
            System.debug('#### currCodeVsRbaExchangeMap : ' + currCodeVsRbaExchangeMap);
        }
        
        
        
        for(mp_Quote_Detail_POE__c Qdetail : newQuoteDetail){
            
            accIds.add(Qdetail.Merchant__c);            
        }
        System.debug('#### accIds : ' + accIds);
        
        List<Account> accList = [Select id,name,Payment_Currency__c, CurrencyIsoCode, Company_Email__c, c2g__CODAAccountTradingCurrency__c from Account where id IN:accIds] ;
        
        for(Account acc:accList){
            
            idAccountMap.put(acc.id,acc);
        }
        System.debug('#### idAccountMap : ' + idAccountMap);
        
        Set<Id> orderCustomisationSet = new Set<Id>();
        Map<Id,String> orderCustomTADOrderMap = new Map<Id,String>();
        Map<Id,String> quoteDetailTADPriceMap = new Map<Id,String>();
        for(mp_Quote_Detail_POE__c qd : newQuoteDetail)
        {
            orderCustomisationSet.add(qd.mp_Order_Customisation__c);
        }
        System.debug('#### orderCustomisationSet : ' + orderCustomisationSet);
        
        for(Order_Customisations_POE__c oc : [Select id,recordType.Name, mp_tad_order__c, mp_tad_order__r.RecordTypeId, mp_tad_order__r.RecordType.DeveloperName from Order_Customisations_POE__c where id in: orderCustomisationSet])
        {
            orderCustomTADOrderMap.put(oc.Id,oc.mp_tad_order__r.RecordType.DeveloperName);
            quoteDetailTADPriceMap.put(oc.Id,oc.recordType.Name);
        }
        System.debug('#### orderCustomTADOrderMap : ' + orderCustomTADOrderMap);
        
        for(mp_Quote_Detail_POE__c qd :newQuoteDetail){
            String merchantCurrency = '';
            if(idAccountMap.get(qd.Merchant__c) != null){
                merchantCurrency= idAccountMap.get(qd.Merchant__c).CurrencyIsoCode;
                System.debug('#### merchantCurrency : ' + merchantCurrency);
                qd.CurrencyIsoCode = idAccountMap.get(qd.Merchant__c).CurrencyIsoCode;
                qd.Merchant_Email__c = idAccountMap.get(qd.Merchant__c).Company_Email__c;
                qd.mp_Merchant_Currency__c = merchantCurrency;
            }
            String recType = '';
            if(orderCustomTADOrderMap.get(qd.mp_Order_Customisation__c) == 'TAD' || orderCustomTADOrderMap.get(qd.mp_Order_Customisation__c) == 'TC')
            {
                recType = 'AUD';
            }
            else if(orderCustomTADOrderMap.get(qd.mp_Order_Customisation__c) == 'TNZ' || orderCustomTADOrderMap.get(qd.mp_Order_Customisation__c) == 'WT')
            {
                recType = 'NZD';
            }
            String rbaExKey = recType +  merchantCurrency;
            System.debug('#### rbaExKey : ' + rbaExKey);
            
            if(currCodeVsRbaExchangeMap.containsKey(rbaExKey)){
                
                qd.RBA_Exchange_Rate__c =  currCodeVsRbaExchangeMap.get(rbaExKey).id;
            }
            if(quoteDetailTADPriceMap.get(qd.mp_Order_Customisation__c) == 'Miscellaneous'){
                qd.CurrencyIsoCode = 'AUD';
                qd.TAD_Price__c =qd.mp_Merchant_Price__c;
            }
            else
            {
            if(qd.mp_Merchant_Price__c != null && merchantCurrency != null && currCodeVsRbaExchangeMap.get(rbaExKey) != null)
            {
                qd.CurrencyIsoCode = 'AUD';
                qd.TAD_Price__c = (((qd.mp_Merchant_Price__c / currCodeVsRbaExchangeMap.get(rbaExKey).exchange_rate__c)) * 11/10).setScale(2);               
            }
            }
            System.debug('#### qd : ' + qd);
            
        }
        
    }
    
    
    
    public static void settingOrdCustomStatus(List<mp_Quote_Detail_POE__c> quoteDetailList ,Map<Id, mp_Quote_Detail_POE__c> quoteOldmap){
        
        Set<ID> initalListOrderCus = new Set<ID>();
        List<mp_Quote_Detail_POE__c> listOfQD = new LIST<mp_Quote_Detail_POE__c>();
        Map<Id,Order_Customisations_POE__c> mapOfOcToUpdate = new  Map<Id,Order_Customisations_POE__c>();
        
        for(mp_Quote_Detail_POE__c qd: quoteDetailList){
            if(qd.Quote_Approval_Status__c != quoteOldmap.get(qd.Id).Quote_Approval_Status__c && (qd.Quote_Approval_Status__c == 'Decline' || qd.Quote_Approval_Status__c == 'CustomerApproved')){
                initalListOrderCus.add(qd.mp_Order_Customisation__c);
            }
        } 
        List <Order_Customisations_POE__c> ocList = [Select id ,Status__c,(Select id ,Quote_Approval_Status__c from Quote_Details__r) from Order_Customisations_POE__c where id IN:initalListOrderCus ];
        
        for(Order_Customisations_POE__c oc: ocList){
            for( mp_Quote_Detail_POE__c  quote: oc.Quote_Details__r){
                if(quote.Quote_Approval_Status__c=='CustomerApproved' || quote.Quote_Approval_Status__c=='Decline' ){
                    mapOfOcToUpdate.put(oc.id,oc);    
                }else{
                    if(mapOfOcToUpdate.get(oc.id) != null){
                        mapOfOcToUpdate.remove(oc.id); 
                        break;
                    }else{
                        break;
                    }
                } 
            } 
        }
        
        
        if(!mapOfOcToUpdate.isEmpty()){
            List<Order_Customisations_POE__c> ocToUpdate = new List<Order_Customisations_POE__c>();
            
            for (Order_Customisations_POE__c oc : mapOfOcToUpdate.Values()){
                
                Boolean isApproved = false;
                
                for( mp_Quote_Detail_POE__c  quote: oc.Quote_Details__r){
                    if(quote.Quote_Approval_Status__c=='CustomerApproved'){
                        isApproved=true;
                        break;
                    } 
                }
                if(isApproved==true){
                    Order_Customisations_POE__c ocRec = new Order_Customisations_POE__c();
                    ocRec.id =oc.id;
                    ocRec.Status__c='Customer Approved';
                    ocToUpdate.add(ocRec);   
                }else{
                    Order_Customisations_POE__c ocRec1 = new Order_Customisations_POE__c();
                    ocRec1.id =oc.id;
                    ocRec1.Status__c='Declined';
                    ocToUpdate.add(ocRec1);   
                } 
            }
            
            if(!ocToUpdate.isEmpty()){
                update ocToUpdate;
            }
            
        }
        
    }
    
    
    
    public class innerwrap{
        
        public Order_Customisations_POE__c oc{get;set;}
        public List<mp_Quote_Detail_POE__c> mqd{get;set;}
        
    } 
}