force-app/main/default/objects/PNR_POE_Platform_Event__e/PNR_POE_Platform_Event__e.object-meta.xml
<CustomObject>
    <label>PNR POE Platform Event</label>
    <pluralLabel>PNR POE Platform Event</pluralLabel>
</CustomObject>

force-app/main/default/objects/PNR_POE_Platform_Event__e/fields/PNR_Name__c.field-meta.xml
<CustomField>
    <fullName>PNR_Name__c</fullName>
    <label>PNR Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PNR_POE_Platform_Event__e/fields/PNR_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>PNR_Record_Id__c</fullName>
    <label>PNR Record Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MakeCalloutToPNRGetReservationContTest.cls
@isTest
public class MakeCalloutToPNRGetReservationContTest {

    private class Mock implements HttpCalloutMock {
        
        public HttpResponse respond(HttpRequest req) {
            HttpResponse res = new HttpResponse();
            res.setBody('{"responseCode":200,"responseMessage":"Success!!"}');
            res.setStatusCode(200);
            return res;
        } 
    } 
    
    
    @isTest
    public static void testMethod1() {
        
        
        
        
        
        // Create a test event instance
        PNR_POE_Platform_Event__e  smEvent = new PNR_POE_Platform_Event__e(PNR_Name__c ='BWODNR', PNR_Record_Id__c='aGO1e0000004CG9GAM', Status__c ='New');
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new Mock());
        // Publish test event
        Database.SaveResult sr = EventBus.publish(smEvent);
        
        Test.stopTest();
        
    }
    
}